/**
 * Cyc_H_OroRecord.java
 * Self generated code for Bussines Object CYC_FICHA_EMPLEADO.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_ficha_empleado;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_H_Oro.
 * @author Meta4
 */
public 
class Cyc_H_OroRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_FICHA_EMPLEADO";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_H_ORO";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_H_OroRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item AREA */
    public String area = null;
    private void setarea(String ai_value)
    {
        area = ai_value;
    }
    private String getarea()
    {
        return area;
    }

    /* item ID_HR */
    public String id_Hr = null;
    private void setid_Hr(String ai_value)
    {
        id_Hr = ai_value;
    }
    private String getid_Hr()
    {
        return id_Hr;
    }

    /* item PUESTO */
    public String puesto = null;
    private void setpuesto(String ai_value)
    {
        puesto = ai_value;
    }
    private String getpuesto()
    {
        return puesto;
    }

    /* item FAMILIA */
    public String familia = null;
    private void setfamilia(String ai_value)
    {
        familia = ai_value;
    }
    private String getfamilia()
    {
        return familia;
    }

    /* item ID_AREA */
    public String id_Area = null;
    private void setid_Area(String ai_value)
    {
        id_Area = ai_value;
    }
    private String getid_Area()
    {
        return id_Area;
    }

    /* item SERVICIO */
    public String servicio = null;
    private void setservicio(String ai_value)
    {
        servicio = ai_value;
    }
    private String getservicio()
    {
        return servicio;
    }

    /* item DIRECCION */
    public String direccion = null;
    private void setdireccion(String ai_value)
    {
        direccion = ai_value;
    }
    private String getdireccion()
    {
        return direccion;
    }

    /* item ID_PUESTO */
    public String id_Puesto = null;
    private void setid_Puesto(String ai_value)
    {
        id_Puesto = ai_value;
    }
    private String getid_Puesto()
    {
        return id_Puesto;
    }

    /* item ID_FAMILIA */
    public String id_Familia = null;
    private void setid_Familia(String ai_value)
    {
        id_Familia = ai_value;
    }
    private String getid_Familia()
    {
        return id_Familia;
    }

    /* item ID_SERVICIO */
    public String id_Servicio = null;
    private void setid_Servicio(String ai_value)
    {
        id_Servicio = ai_value;
    }
    private String getid_Servicio()
    {
        return id_Servicio;
    }

    /* item CYC_N_UNIDAD */
    public String cyc_N_Unidad = null;
    private void setcyc_N_Unidad(String ai_value)
    {
        cyc_N_Unidad = ai_value;
    }
    private String getcyc_N_Unidad()
    {
        return cyc_N_Unidad;
    }

    /* item ID_DIRECCION */
    public String id_Direccion = null;
    private void setid_Direccion(String ai_value)
    {
        id_Direccion = ai_value;
    }
    private String getid_Direccion()
    {
        return id_Direccion;
    }

    /* item CYC_ID_UNIDAD */
    public String cyc_Id_Unidad = null;
    private void setcyc_Id_Unidad(String ai_value)
    {
        cyc_Id_Unidad = ai_value;
    }
    private String getcyc_Id_Unidad()
    {
        return cyc_Id_Unidad;
    }

    /* item ID_ORGANIZATION */
    public String id_Organization = null;
    private void setid_Organization(String ai_value)
    {
        id_Organization = ai_value;
    }
    private String getid_Organization()
    {
        return id_Organization;
    }

    /* node CYC_H_ORO_PERIOD */
    public Cyc_H_Oro_PeriodBlock Cyc_H_Oro_Period = null;
    private void setcyc_H_Oro_Period(Cyc_H_Oro_PeriodBlock ai_value)
    {
        Cyc_H_Oro_Period = ai_value;
    }
    private Cyc_H_Oro_PeriodBlock getCyc_H_Oro_Period()
    {
        return Cyc_H_Oro_Period;
    }

    /* node CYC_H_ORO_PERSON */
    public Cyc_H_Oro_PersonBlock Cyc_H_Oro_Person = null;
    private void setcyc_H_Oro_Person(Cyc_H_Oro_PersonBlock ai_value)
    {
        Cyc_H_Oro_Person = ai_value;
    }
    private Cyc_H_Oro_PersonBlock getCyc_H_Oro_Person()
    {
        return Cyc_H_Oro_Person;
    }

    /* node CYC_H_ORO_TRABAJO */
    public Cyc_H_Oro_TrabajoBlock Cyc_H_Oro_Trabajo = null;
    private void setcyc_H_Oro_Trabajo(Cyc_H_Oro_TrabajoBlock ai_value)
    {
        Cyc_H_Oro_Trabajo = ai_value;
    }
    private Cyc_H_Oro_TrabajoBlock getCyc_H_Oro_Trabajo()
    {
        return Cyc_H_Oro_Trabajo;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // AREA.
        if (area != null)
        {
            htItems.put("AREA", M4BusinessMethodArg.toString(area));
        }
        // ID_HR.
        if (id_Hr != null)
        {
            htItems.put("ID_HR", M4BusinessMethodArg.toString(id_Hr));
        }
        // PUESTO.
        if (puesto != null)
        {
            htItems.put("PUESTO", M4BusinessMethodArg.toString(puesto));
        }
        // FAMILIA.
        if (familia != null)
        {
            htItems.put("FAMILIA", M4BusinessMethodArg.toString(familia));
        }
        // ID_AREA.
        if (id_Area != null)
        {
            htItems.put("ID_AREA", M4BusinessMethodArg.toString(id_Area));
        }
        // SERVICIO.
        if (servicio != null)
        {
            htItems.put("SERVICIO", M4BusinessMethodArg.toString(servicio));
        }
        // DIRECCION.
        if (direccion != null)
        {
            htItems.put("DIRECCION", M4BusinessMethodArg.toString(direccion));
        }
        // ID_PUESTO.
        if (id_Puesto != null)
        {
            htItems.put("ID_PUESTO", M4BusinessMethodArg.toString(id_Puesto));
        }
        // ID_FAMILIA.
        if (id_Familia != null)
        {
            htItems.put("ID_FAMILIA", M4BusinessMethodArg.toString(id_Familia));
        }
        // ID_SERVICIO.
        if (id_Servicio != null)
        {
            htItems.put("ID_SERVICIO", M4BusinessMethodArg.toString(id_Servicio));
        }
        // CYC_N_UNIDAD.
        if (cyc_N_Unidad != null)
        {
            htItems.put("CYC_N_UNIDAD", M4BusinessMethodArg.toString(cyc_N_Unidad));
        }
        // ID_DIRECCION.
        if (id_Direccion != null)
        {
            htItems.put("ID_DIRECCION", M4BusinessMethodArg.toString(id_Direccion));
        }
        // CYC_ID_UNIDAD.
        if (cyc_Id_Unidad != null)
        {
            htItems.put("CYC_ID_UNIDAD", M4BusinessMethodArg.toString(cyc_Id_Unidad));
        }
        // ID_ORGANIZATION.
        if (id_Organization != null)
        {
            htItems.put("ID_ORGANIZATION", M4BusinessMethodArg.toString(id_Organization));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

        // write data for node CYC_H_ORO_PERIOD.
        if ( Cyc_H_Oro_Period != null) 
        {
           Cyc_H_Oro_Period.writeOperations(ai_m4Op);
        }

        // write data for node CYC_H_ORO_PERSON.
        if ( Cyc_H_Oro_Person != null) 
        {
           Cyc_H_Oro_Person.writeOperations(ai_m4Op);
        }

        // write data for node CYC_H_ORO_TRABAJO.
        if ( Cyc_H_Oro_Trabajo != null) 
        {
           Cyc_H_Oro_Trabajo.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read AREA.
        sItemName = "AREA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        area = sItemValue;

        // read ID_HR.
        sItemName = "ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Hr = sItemValue;

        // read PUESTO.
        sItemName = "PUESTO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        puesto = sItemValue;

        // read FAMILIA.
        sItemName = "FAMILIA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        familia = sItemValue;

        // read ID_AREA.
        sItemName = "ID_AREA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Area = sItemValue;

        // read SERVICIO.
        sItemName = "SERVICIO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        servicio = sItemValue;

        // read DIRECCION.
        sItemName = "DIRECCION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        direccion = sItemValue;

        // read ID_PUESTO.
        sItemName = "ID_PUESTO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Puesto = sItemValue;

        // read ID_FAMILIA.
        sItemName = "ID_FAMILIA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Familia = sItemValue;

        // read ID_SERVICIO.
        sItemName = "ID_SERVICIO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Servicio = sItemValue;

        // read CYC_N_UNIDAD.
        sItemName = "CYC_N_UNIDAD";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_N_Unidad = sItemValue;

        // read ID_DIRECCION.
        sItemName = "ID_DIRECCION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Direccion = sItemValue;

        // read CYC_ID_UNIDAD.
        sItemName = "CYC_ID_UNIDAD";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Unidad = sItemValue;

        // read ID_ORGANIZATION.
        sItemName = "ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Organization = sItemValue;

        // read data for node CYC_H_ORO_PERIOD.
        Cyc_H_Oro_Period = new Cyc_H_Oro_PeriodBlock();
        Cyc_H_Oro_Period.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_H_Oro_PeriodBlock.NODE_NAME));

        // read data for node CYC_H_ORO_PERSON.
        Cyc_H_Oro_Person = new Cyc_H_Oro_PersonBlock();
        Cyc_H_Oro_Person.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_H_Oro_PersonBlock.NODE_NAME));

        // read data for node CYC_H_ORO_TRABAJO.
        Cyc_H_Oro_Trabajo = new Cyc_H_Oro_TrabajoBlock();
        Cyc_H_Oro_Trabajo.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_H_Oro_TrabajoBlock.NODE_NAME));


    } /* end of method readOperations */


} /* end of class Cyc_H_OroRecord */

