/**
 * Cyc_TitulacionesRecord.java
 * Self generated code for Bussines Object CYC_FICHA_EMPLEADO.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_ficha_empleado;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Titulaciones.
 * @author Meta4
 */
public 
class Cyc_TitulacionesRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_FICHA_EMPLEADO";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_TITULACIONES";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_TitulacionesRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item STD_ID_HR */
    public String std_Id_Hr = null;
    private void setstd_Id_Hr(String ai_value)
    {
        std_Id_Hr = ai_value;
    }
    private String getstd_Id_Hr()
    {
        return std_Id_Hr;
    }

    /* item STD_N_EDU_SP */
    public String std_N_Edu_Sp = null;
    private void setstd_N_Edu_Sp(String ai_value)
    {
        std_N_Edu_Sp = ai_value;
    }
    private String getstd_N_Edu_Sp()
    {
        return std_N_Edu_Sp;
    }

    /* item STD_ID_EDU_SP */
    public String std_Id_Edu_Sp = null;
    private void setstd_Id_Edu_Sp(String ai_value)
    {
        std_Id_Edu_Sp = ai_value;
    }
    private String getstd_Id_Edu_Sp()
    {
        return std_Id_Edu_Sp;
    }

    /* item STD_N_EDU_TYPE */
    public String std_N_Edu_Type = null;
    private void setstd_N_Edu_Type(String ai_value)
    {
        std_N_Edu_Type = ai_value;
    }
    private String getstd_N_Edu_Type()
    {
        return std_N_Edu_Type;
    }

    /* item STD_ID_EDU_TYPE */
    public String std_Id_Edu_Type = null;
    private void setstd_Id_Edu_Type(String ai_value)
    {
        std_Id_Edu_Type = ai_value;
    }
    private String getstd_Id_Edu_Type()
    {
        return std_Id_Edu_Type;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // STD_ID_HR.
        if (std_Id_Hr != null)
        {
            htItems.put("STD_ID_HR", M4BusinessMethodArg.toString(std_Id_Hr));
        }
        // STD_N_EDU_SP.
        if (std_N_Edu_Sp != null)
        {
            htItems.put("STD_N_EDU_SP", M4BusinessMethodArg.toString(std_N_Edu_Sp));
        }
        // STD_ID_EDU_SP.
        if (std_Id_Edu_Sp != null)
        {
            htItems.put("STD_ID_EDU_SP", M4BusinessMethodArg.toString(std_Id_Edu_Sp));
        }
        // STD_N_EDU_TYPE.
        if (std_N_Edu_Type != null)
        {
            htItems.put("STD_N_EDU_TYPE", M4BusinessMethodArg.toString(std_N_Edu_Type));
        }
        // STD_ID_EDU_TYPE.
        if (std_Id_Edu_Type != null)
        {
            htItems.put("STD_ID_EDU_TYPE", M4BusinessMethodArg.toString(std_Id_Edu_Type));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read STD_ID_HR.
        sItemName = "STD_ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Id_Hr = sItemValue;

        // read STD_N_EDU_SP.
        sItemName = "STD_N_EDU_SP";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_Edu_Sp = sItemValue;

        // read STD_ID_EDU_SP.
        sItemName = "STD_ID_EDU_SP";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Id_Edu_Sp = sItemValue;

        // read STD_N_EDU_TYPE.
        sItemName = "STD_N_EDU_TYPE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_Edu_Type = sItemValue;

        // read STD_ID_EDU_TYPE.
        sItemName = "STD_ID_EDU_TYPE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Id_Edu_Type = sItemValue;


    } /* end of method readOperations */


} /* end of class Cyc_TitulacionesRecord */

