/**
 * Cyc_Datos_Fase_IiiRecord.java
 * Self generated code for Bussines Object CYC_FICHA_EMPLEADO.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_ficha_empleado;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Datos_Fase_Iii.
 * @author Meta4
 */
public 
class Cyc_Datos_Fase_IiiRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_FICHA_EMPLEADO";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_DATOS_FASE_III";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Datos_Fase_IiiRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item CYC_R9 */
    public Double cyc_R9 = null;
    private void setcyc_R9(Double ai_value)
    {
        cyc_R9 = ai_value;
    }
    private Double getcyc_R9()
    {
        return cyc_R9;
    }

    /* item DT_END */
    public Calendar dt_End = null;
    private void setdt_End(Calendar ai_value)
    {
        dt_End = ai_value;
    }
    private Calendar getdt_End()
    {
        return dt_End;
    }

    /* item CYC_R10 */
    public Double cyc_R10 = null;
    private void setcyc_R10(Double ai_value)
    {
        cyc_R10 = ai_value;
    }
    private Double getcyc_R10()
    {
        return cyc_R10;
    }

    /* item DT_START */
    public Calendar dt_Start = null;
    private void setdt_Start(Calendar ai_value)
    {
        dt_Start = ai_value;
    }
    private Calendar getdt_Start()
    {
        return dt_Start;
    }

    /* item CYC_ID_HR */
    public String cyc_Id_Hr = null;
    private void setcyc_Id_Hr(String ai_value)
    {
        cyc_Id_Hr = ai_value;
    }
    private String getcyc_Id_Hr()
    {
        return cyc_Id_Hr;
    }

    /* item CYC_COMENT */
    public String cyc_Coment = null;
    private void setcyc_Coment(String ai_value)
    {
        cyc_Coment = ai_value;
    }
    private String getcyc_Coment()
    {
        return cyc_Coment;
    }

    /* item CHECK_TOEIC */
    public String check_Toeic = null;
    private void setcheck_Toeic(String ai_value)
    {
        check_Toeic = ai_value;
    }
    private String getcheck_Toeic()
    {
        return check_Toeic;
    }

    /* item CYC_RANKING */
    public Double cyc_Ranking = null;
    private void setcyc_Ranking(Double ai_value)
    {
        cyc_Ranking = ai_value;
    }
    private Double getcyc_Ranking()
    {
        return cyc_Ranking;
    }

    /* item CYC_FEC_EVALUA */
    public Calendar cyc_Fec_Evalua = null;
    private void setcyc_Fec_Evalua(Calendar ai_value)
    {
        cyc_Fec_Evalua = ai_value;
    }
    private Calendar getcyc_Fec_Evalua()
    {
        return cyc_Fec_Evalua;
    }

    /* item CYC_N_COLECTIVO */
    public String cyc_N_Colectivo = null;
    private void setcyc_N_Colectivo(String ai_value)
    {
        cyc_N_Colectivo = ai_value;
    }
    private String getcyc_N_Colectivo()
    {
        return cyc_N_Colectivo;
    }

    /* item CYC_SUPERADA_F3 */
    public String cyc_Superada_F3 = null;
    private void setcyc_Superada_F3(String ai_value)
    {
        cyc_Superada_F3 = ai_value;
    }
    private String getcyc_Superada_F3()
    {
        return cyc_Superada_F3;
    }

    /* item ID_ORGANIZATION */
    public String id_Organization = null;
    private void setid_Organization(String ai_value)
    {
        id_Organization = ai_value;
    }
    private String getid_Organization()
    {
        return id_Organization;
    }

    /* item CHECK_COMPROMISO */
    public String check_Compromiso = null;
    private void setcheck_Compromiso(String ai_value)
    {
        check_Compromiso = ai_value;
    }
    private String getcheck_Compromiso()
    {
        return check_Compromiso;
    }

    /* item CYC_FEC_REALIZACION */
    public Calendar cyc_Fec_Realizacion = null;
    private void setcyc_Fec_Realizacion(Calendar ai_value)
    {
        cyc_Fec_Realizacion = ai_value;
    }
    private Calendar getcyc_Fec_Realizacion()
    {
        return cyc_Fec_Realizacion;
    }

    /* item CYC_ORIENT_RTDOS_F3 */
    public Double cyc_Orient_Rtdos_F3 = null;
    private void setcyc_Orient_Rtdos_F3(Double ai_value)
    {
        cyc_Orient_Rtdos_F3 = ai_value;
    }
    private Double getcyc_Orient_Rtdos_F3()
    {
        return cyc_Orient_Rtdos_F3;
    }

    /* item CYC_PORC_DESARROLLO */
    public Double cyc_Porc_Desarrollo = null;
    private void setcyc_Porc_Desarrollo(Double ai_value)
    {
        cyc_Porc_Desarrollo = ai_value;
    }
    private Double getcyc_Porc_Desarrollo()
    {
        return cyc_Porc_Desarrollo;
    }

    /* item CYC_COMENTARIOS_RRHH */
    public String cyc_Comentarios_Rrhh = null;
    private void setcyc_Comentarios_Rrhh(String ai_value)
    {
        cyc_Comentarios_Rrhh = ai_value;
    }
    private String getcyc_Comentarios_Rrhh()
    {
        return cyc_Comentarios_Rrhh;
    }

    /* item CYC_COMUN_IMP_INF_F3 */
    public Double cyc_Comun_Imp_Inf_F3 = null;
    private void setcyc_Comun_Imp_Inf_F3(Double ai_value)
    {
        cyc_Comun_Imp_Inf_F3 = ai_value;
    }
    private Double getcyc_Comun_Imp_Inf_F3()
    {
        return cyc_Comun_Imp_Inf_F3;
    }

    /* item CYC_CAPAC_ANALITIC_F3 */
    public Double cyc_Capac_Analitic_F3 = null;
    private void setcyc_Capac_Analitic_F3(Double ai_value)
    {
        cyc_Capac_Analitic_F3 = ai_value;
    }
    private Double getcyc_Capac_Analitic_F3()
    {
        return cyc_Capac_Analitic_F3;
    }

    /* item CYC_FEC_ENTREV_FEEDBK */
    public Calendar cyc_Fec_Entrev_Feedbk = null;
    private void setcyc_Fec_Entrev_Feedbk(Calendar ai_value)
    {
        cyc_Fec_Entrev_Feedbk = ai_value;
    }
    private Calendar getcyc_Fec_Entrev_Feedbk()
    {
        return cyc_Fec_Entrev_Feedbk;
    }

    /* item CYC_LIDER_DIR_EQUIP_F3 */
    public Double cyc_Lider_Dir_Equip_F3 = null;
    private void setcyc_Lider_Dir_Equip_F3(Double ai_value)
    {
        cyc_Lider_Dir_Equip_F3 = ai_value;
    }
    private Double getcyc_Lider_Dir_Equip_F3()
    {
        return cyc_Lider_Dir_Equip_F3;
    }

    /* item CYC_OBSERVACIONES_RRHH */
    public String cyc_Observaciones_Rrhh = null;
    private void setcyc_Observaciones_Rrhh(String ai_value)
    {
        cyc_Observaciones_Rrhh = ai_value;
    }
    private String getcyc_Observaciones_Rrhh()
    {
        return cyc_Observaciones_Rrhh;
    }

    /* item CYC_PERFIL_PROFESIONAL */
    public String cyc_Perfil_Profesional = null;
    private void setcyc_Perfil_Profesional(String ai_value)
    {
        cyc_Perfil_Profesional = ai_value;
    }
    private String getcyc_Perfil_Profesional()
    {
        return cyc_Perfil_Profesional;
    }

    /* item CYC_VISION_GBAL_EST_F3 */
    public Double cyc_Vision_Gbal_Est_F3 = null;
    private void setcyc_Vision_Gbal_Est_F3(Double ai_value)
    {
        cyc_Vision_Gbal_Est_F3 = ai_value;
    }
    private Double getcyc_Vision_Gbal_Est_F3()
    {
        return cyc_Vision_Gbal_Est_F3;
    }

    /* item CYC_COMENTARIOS_EMPLEADO */
    public String cyc_Comentarios_Empleado = null;
    private void setcyc_Comentarios_Empleado(String ai_value)
    {
        cyc_Comentarios_Empleado = ai_value;
    }
    private String getcyc_Comentarios_Empleado()
    {
        return cyc_Comentarios_Empleado;
    }

    /* item CYC_RECOMENDACIONES_RRHH */
    public String cyc_Recomendaciones_Rrhh = null;
    private void setcyc_Recomendaciones_Rrhh(String ai_value)
    {
        cyc_Recomendaciones_Rrhh = ai_value;
    }
    private String getcyc_Recomendaciones_Rrhh()
    {
        return cyc_Recomendaciones_Rrhh;
    }

    /* item CYC_FEC_ACEPTACION_FEEDBK */
    public Calendar cyc_Fec_Aceptacion_Feedbk = null;
    private void setcyc_Fec_Aceptacion_Feedbk(Calendar ai_value)
    {
        cyc_Fec_Aceptacion_Feedbk = ai_value;
    }
    private Calendar getcyc_Fec_Aceptacion_Feedbk()
    {
        return cyc_Fec_Aceptacion_Feedbk;
    }

    /* node CYC_ASSESMENT */
    public Cyc_AssesmentBlock Cyc_Assesment = null;
    private void setcyc_Assesment(Cyc_AssesmentBlock ai_value)
    {
        Cyc_Assesment = ai_value;
    }
    private Cyc_AssesmentBlock getCyc_Assesment()
    {
        return Cyc_Assesment;
    }

    /* node CYC_PUNTOS_FUERTES_FIII */
    public Cyc_Puntos_Fuertes_FiiiBlock Cyc_Puntos_Fuertes_Fiii = null;
    private void setcyc_Puntos_Fuertes_Fiii(Cyc_Puntos_Fuertes_FiiiBlock ai_value)
    {
        Cyc_Puntos_Fuertes_Fiii = ai_value;
    }
    private Cyc_Puntos_Fuertes_FiiiBlock getCyc_Puntos_Fuertes_Fiii()
    {
        return Cyc_Puntos_Fuertes_Fiii;
    }

    /* node CYC_ACCIONES_MEJORA_FIII */
    public Cyc_Acciones_Mejora_FiiiBlock Cyc_Acciones_Mejora_Fiii = null;
    private void setcyc_Acciones_Mejora_Fiii(Cyc_Acciones_Mejora_FiiiBlock ai_value)
    {
        Cyc_Acciones_Mejora_Fiii = ai_value;
    }
    private Cyc_Acciones_Mejora_FiiiBlock getCyc_Acciones_Mejora_Fiii()
    {
        return Cyc_Acciones_Mejora_Fiii;
    }

    /* node CYC_ACCIONES_FORMACION_FIII */
    public Cyc_Acciones_Formacion_FiiiBlock Cyc_Acciones_Formacion_Fiii = null;
    private void setcyc_Acciones_Formacion_Fiii(Cyc_Acciones_Formacion_FiiiBlock ai_value)
    {
        Cyc_Acciones_Formacion_Fiii = ai_value;
    }
    private Cyc_Acciones_Formacion_FiiiBlock getCyc_Acciones_Formacion_Fiii()
    {
        return Cyc_Acciones_Formacion_Fiii;
    }

    /* node CYC_ACCIONES_DESARROLLO_FIII */
    public Cyc_Acciones_Desarrollo_FiiiBlock Cyc_Acciones_Desarrollo_Fiii = null;
    private void setcyc_Acciones_Desarrollo_Fiii(Cyc_Acciones_Desarrollo_FiiiBlock ai_value)
    {
        Cyc_Acciones_Desarrollo_Fiii = ai_value;
    }
    private Cyc_Acciones_Desarrollo_FiiiBlock getCyc_Acciones_Desarrollo_Fiii()
    {
        return Cyc_Acciones_Desarrollo_Fiii;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // CYC_R9.
        if (cyc_R9 != null)
        {
            htItems.put("CYC_R9", M4BusinessMethodArg.toString(cyc_R9));
        }
        // DT_END.
        if (dt_End != null)
        {
            htItems.put("DT_END", M4BusinessMethodArg.toString(dt_End));
        }
        // CYC_R10.
        if (cyc_R10 != null)
        {
            htItems.put("CYC_R10", M4BusinessMethodArg.toString(cyc_R10));
        }
        // DT_START.
        if (dt_Start != null)
        {
            htItems.put("DT_START", M4BusinessMethodArg.toString(dt_Start));
        }
        // CYC_ID_HR.
        if (cyc_Id_Hr != null)
        {
            htItems.put("CYC_ID_HR", M4BusinessMethodArg.toString(cyc_Id_Hr));
        }
        // CYC_COMENT.
        if (cyc_Coment != null)
        {
            htItems.put("CYC_COMENT", M4BusinessMethodArg.toString(cyc_Coment));
        }
        // CHECK_TOEIC.
        if (check_Toeic != null)
        {
            htItems.put("CHECK_TOEIC", M4BusinessMethodArg.toString(check_Toeic));
        }
        // CYC_RANKING.
        if (cyc_Ranking != null)
        {
            htItems.put("CYC_RANKING", M4BusinessMethodArg.toString(cyc_Ranking));
        }
        // CYC_FEC_EVALUA.
        if (cyc_Fec_Evalua != null)
        {
            htItems.put("CYC_FEC_EVALUA", M4BusinessMethodArg.toString(cyc_Fec_Evalua));
        }
        // CYC_N_COLECTIVO.
        if (cyc_N_Colectivo != null)
        {
            htItems.put("CYC_N_COLECTIVO", M4BusinessMethodArg.toString(cyc_N_Colectivo));
        }
        // CYC_SUPERADA_F3.
        if (cyc_Superada_F3 != null)
        {
            htItems.put("CYC_SUPERADA_F3", M4BusinessMethodArg.toString(cyc_Superada_F3));
        }
        // ID_ORGANIZATION.
        if (id_Organization != null)
        {
            htItems.put("ID_ORGANIZATION", M4BusinessMethodArg.toString(id_Organization));
        }
        // CHECK_COMPROMISO.
        if (check_Compromiso != null)
        {
            htItems.put("CHECK_COMPROMISO", M4BusinessMethodArg.toString(check_Compromiso));
        }
        // CYC_FEC_REALIZACION.
        if (cyc_Fec_Realizacion != null)
        {
            htItems.put("CYC_FEC_REALIZACION", M4BusinessMethodArg.toString(cyc_Fec_Realizacion));
        }
        // CYC_ORIENT_RTDOS_F3.
        if (cyc_Orient_Rtdos_F3 != null)
        {
            htItems.put("CYC_ORIENT_RTDOS_F3", M4BusinessMethodArg.toString(cyc_Orient_Rtdos_F3));
        }
        // CYC_PORC_DESARROLLO.
        if (cyc_Porc_Desarrollo != null)
        {
            htItems.put("CYC_PORC_DESARROLLO", M4BusinessMethodArg.toString(cyc_Porc_Desarrollo));
        }
        // CYC_COMENTARIOS_RRHH.
        if (cyc_Comentarios_Rrhh != null)
        {
            htItems.put("CYC_COMENTARIOS_RRHH", M4BusinessMethodArg.toString(cyc_Comentarios_Rrhh));
        }
        // CYC_COMUN_IMP_INF_F3.
        if (cyc_Comun_Imp_Inf_F3 != null)
        {
            htItems.put("CYC_COMUN_IMP_INF_F3", M4BusinessMethodArg.toString(cyc_Comun_Imp_Inf_F3));
        }
        // CYC_CAPAC_ANALITIC_F3.
        if (cyc_Capac_Analitic_F3 != null)
        {
            htItems.put("CYC_CAPAC_ANALITIC_F3", M4BusinessMethodArg.toString(cyc_Capac_Analitic_F3));
        }
        // CYC_FEC_ENTREV_FEEDBK.
        if (cyc_Fec_Entrev_Feedbk != null)
        {
            htItems.put("CYC_FEC_ENTREV_FEEDBK", M4BusinessMethodArg.toString(cyc_Fec_Entrev_Feedbk));
        }
        // CYC_LIDER_DIR_EQUIP_F3.
        if (cyc_Lider_Dir_Equip_F3 != null)
        {
            htItems.put("CYC_LIDER_DIR_EQUIP_F3", M4BusinessMethodArg.toString(cyc_Lider_Dir_Equip_F3));
        }
        // CYC_OBSERVACIONES_RRHH.
        if (cyc_Observaciones_Rrhh != null)
        {
            htItems.put("CYC_OBSERVACIONES_RRHH", M4BusinessMethodArg.toString(cyc_Observaciones_Rrhh));
        }
        // CYC_PERFIL_PROFESIONAL.
        if (cyc_Perfil_Profesional != null)
        {
            htItems.put("CYC_PERFIL_PROFESIONAL", M4BusinessMethodArg.toString(cyc_Perfil_Profesional));
        }
        // CYC_VISION_GBAL_EST_F3.
        if (cyc_Vision_Gbal_Est_F3 != null)
        {
            htItems.put("CYC_VISION_GBAL_EST_F3", M4BusinessMethodArg.toString(cyc_Vision_Gbal_Est_F3));
        }
        // CYC_COMENTARIOS_EMPLEADO.
        if (cyc_Comentarios_Empleado != null)
        {
            htItems.put("CYC_COMENTARIOS_EMPLEADO", M4BusinessMethodArg.toString(cyc_Comentarios_Empleado));
        }
        // CYC_RECOMENDACIONES_RRHH.
        if (cyc_Recomendaciones_Rrhh != null)
        {
            htItems.put("CYC_RECOMENDACIONES_RRHH", M4BusinessMethodArg.toString(cyc_Recomendaciones_Rrhh));
        }
        // CYC_FEC_ACEPTACION_FEEDBK.
        if (cyc_Fec_Aceptacion_Feedbk != null)
        {
            htItems.put("CYC_FEC_ACEPTACION_FEEDBK", M4BusinessMethodArg.toString(cyc_Fec_Aceptacion_Feedbk));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

        // write data for node CYC_ASSESMENT.
        if ( Cyc_Assesment != null) 
        {
           Cyc_Assesment.writeOperations(ai_m4Op);
        }

        // write data for node CYC_PUNTOS_FUERTES_FIII.
        if ( Cyc_Puntos_Fuertes_Fiii != null) 
        {
           Cyc_Puntos_Fuertes_Fiii.writeOperations(ai_m4Op);
        }

        // write data for node CYC_ACCIONES_MEJORA_FIII.
        if ( Cyc_Acciones_Mejora_Fiii != null) 
        {
           Cyc_Acciones_Mejora_Fiii.writeOperations(ai_m4Op);
        }

        // write data for node CYC_ACCIONES_FORMACION_FIII.
        if ( Cyc_Acciones_Formacion_Fiii != null) 
        {
           Cyc_Acciones_Formacion_Fiii.writeOperations(ai_m4Op);
        }

        // write data for node CYC_ACCIONES_DESARROLLO_FIII.
        if ( Cyc_Acciones_Desarrollo_Fiii != null) 
        {
           Cyc_Acciones_Desarrollo_Fiii.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read CYC_R9.
        sItemName = "CYC_R9";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_R9 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read DT_END.
        sItemName = "DT_END";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_End = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_R10.
        sItemName = "CYC_R10";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_R10 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read DT_START.
        sItemName = "DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_ID_HR.
        sItemName = "CYC_ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Hr = sItemValue;

        // read CYC_COMENT.
        sItemName = "CYC_COMENT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Coment = sItemValue;

        // read CHECK_TOEIC.
        sItemName = "CHECK_TOEIC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        check_Toeic = sItemValue;

        // read CYC_RANKING.
        sItemName = "CYC_RANKING";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Ranking = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_FEC_EVALUA.
        sItemName = "CYC_FEC_EVALUA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Fec_Evalua = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_N_COLECTIVO.
        sItemName = "CYC_N_COLECTIVO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_N_Colectivo = sItemValue;

        // read CYC_SUPERADA_F3.
        sItemName = "CYC_SUPERADA_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Superada_F3 = sItemValue;

        // read ID_ORGANIZATION.
        sItemName = "ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Organization = sItemValue;

        // read CHECK_COMPROMISO.
        sItemName = "CHECK_COMPROMISO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        check_Compromiso = sItemValue;

        // read CYC_FEC_REALIZACION.
        sItemName = "CYC_FEC_REALIZACION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Fec_Realizacion = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_ORIENT_RTDOS_F3.
        sItemName = "CYC_ORIENT_RTDOS_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Orient_Rtdos_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_PORC_DESARROLLO.
        sItemName = "CYC_PORC_DESARROLLO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Porc_Desarrollo = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_COMENTARIOS_RRHH.
        sItemName = "CYC_COMENTARIOS_RRHH";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Comentarios_Rrhh = sItemValue;

        // read CYC_COMUN_IMP_INF_F3.
        sItemName = "CYC_COMUN_IMP_INF_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Comun_Imp_Inf_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_CAPAC_ANALITIC_F3.
        sItemName = "CYC_CAPAC_ANALITIC_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Capac_Analitic_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_FEC_ENTREV_FEEDBK.
        sItemName = "CYC_FEC_ENTREV_FEEDBK";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Fec_Entrev_Feedbk = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_LIDER_DIR_EQUIP_F3.
        sItemName = "CYC_LIDER_DIR_EQUIP_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Lider_Dir_Equip_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_OBSERVACIONES_RRHH.
        sItemName = "CYC_OBSERVACIONES_RRHH";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Observaciones_Rrhh = sItemValue;

        // read CYC_PERFIL_PROFESIONAL.
        sItemName = "CYC_PERFIL_PROFESIONAL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Perfil_Profesional = sItemValue;

        // read CYC_VISION_GBAL_EST_F3.
        sItemName = "CYC_VISION_GBAL_EST_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Vision_Gbal_Est_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_COMENTARIOS_EMPLEADO.
        sItemName = "CYC_COMENTARIOS_EMPLEADO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Comentarios_Empleado = sItemValue;

        // read CYC_RECOMENDACIONES_RRHH.
        sItemName = "CYC_RECOMENDACIONES_RRHH";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Recomendaciones_Rrhh = sItemValue;

        // read CYC_FEC_ACEPTACION_FEEDBK.
        sItemName = "CYC_FEC_ACEPTACION_FEEDBK";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Fec_Aceptacion_Feedbk = M4BusinessMethodArg.toCalendar(sItemValue);

        // read data for node CYC_ASSESMENT.
        Cyc_Assesment = new Cyc_AssesmentBlock();
        Cyc_Assesment.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_AssesmentBlock.NODE_NAME));

        // read data for node CYC_PUNTOS_FUERTES_FIII.
        Cyc_Puntos_Fuertes_Fiii = new Cyc_Puntos_Fuertes_FiiiBlock();
        Cyc_Puntos_Fuertes_Fiii.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_Puntos_Fuertes_FiiiBlock.NODE_NAME));

        // read data for node CYC_ACCIONES_MEJORA_FIII.
        Cyc_Acciones_Mejora_Fiii = new Cyc_Acciones_Mejora_FiiiBlock();
        Cyc_Acciones_Mejora_Fiii.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_Acciones_Mejora_FiiiBlock.NODE_NAME));

        // read data for node CYC_ACCIONES_FORMACION_FIII.
        Cyc_Acciones_Formacion_Fiii = new Cyc_Acciones_Formacion_FiiiBlock();
        Cyc_Acciones_Formacion_Fiii.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_Acciones_Formacion_FiiiBlock.NODE_NAME));

        // read data for node CYC_ACCIONES_DESARROLLO_FIII.
        Cyc_Acciones_Desarrollo_Fiii = new Cyc_Acciones_Desarrollo_FiiiBlock();
        Cyc_Acciones_Desarrollo_Fiii.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_Acciones_Desarrollo_FiiiBlock.NODE_NAME));


    } /* end of method readOperations */


} /* end of class Cyc_Datos_Fase_IiiRecord */

