/**
 * Csp_Generar_DocRecord.java
 * Self generated code for Bussines Object CSP_PRUEBA_DOC.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_prueba_doc;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Generar_Doc.
 * @author Meta4
 */
public 
class Csp_Generar_DocRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_PRUEBA_DOC";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_GENERAR_DOC";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Generar_DocRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item ID_DOC */
    public Double id_Doc = null;
    private void setid_Doc(Double ai_value)
    {
        id_Doc = ai_value;
    }
    private Double getid_Doc()
    {
        return id_Doc;
    }

    /* item FICHERO */
    public String fichero = null;
    private void setfichero(String ai_value)
    {
        fichero = ai_value;
    }
    private String getfichero()
    {
        return fichero;
    }

    /* item P_BLOB_PHOTO */
    public String p_Blob_Photo = null;
    private void setp_Blob_Photo(String ai_value)
    {
        p_Blob_Photo = ai_value;
    }
    private String getp_Blob_Photo()
    {
        return p_Blob_Photo;
    }

    /* item DOC_EXTENSION */
    public String doc_Extension = null;
    private void setdoc_Extension(String ai_value)
    {
        doc_Extension = ai_value;
    }
    private String getdoc_Extension()
    {
        return doc_Extension;
    }

    /* item DOC_TITLE_ESP */
    public String doc_Title_Esp = null;
    private void setdoc_Title_Esp(String ai_value)
    {
        doc_Title_Esp = ai_value;
    }
    private String getdoc_Title_Esp()
    {
        return doc_Title_Esp;
    }

    /* item DOC_CONTENT_ESP */
    public String doc_Content_Esp = null;
    private void setdoc_Content_Esp(String ai_value)
    {
        doc_Content_Esp = ai_value;
    }
    private String getdoc_Content_Esp()
    {
        return doc_Content_Esp;
    }

    /* item BLOB_DOC_CONTENT */
    public DataHandler blob_Doc_Content = null;
    private void setblob_Doc_Content(DataHandler ai_value)
    {
        blob_Doc_Content = ai_value;
    }
    private DataHandler getblob_Doc_Content()
    {
        return blob_Doc_Content;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // ID_DOC.
        if (id_Doc != null)
        {
            htItems.put("ID_DOC", M4BusinessMethodArg.toString(id_Doc));
        }
        // FICHERO.
        if (fichero != null)
        {
            htItems.put("FICHERO", M4BusinessMethodArg.toString(fichero));
        }
        // P_BLOB_PHOTO.
        if (p_Blob_Photo != null)
        {
            htItems.put("P_BLOB_PHOTO", M4BusinessMethodArg.toString(p_Blob_Photo));
        }
        // DOC_EXTENSION.
        if (doc_Extension != null)
        {
            htItems.put("DOC_EXTENSION", M4BusinessMethodArg.toString(doc_Extension));
        }
        // DOC_TITLE_ESP.
        if (doc_Title_Esp != null)
        {
            htItems.put("DOC_TITLE_ESP", M4BusinessMethodArg.toString(doc_Title_Esp));
        }
        // DOC_CONTENT_ESP.
        if (doc_Content_Esp != null)
        {
            htItems.put("DOC_CONTENT_ESP", M4BusinessMethodArg.toString(doc_Content_Esp));
        }
        // BLOB_DOC_CONTENT.
        if ( blob_Doc_Content != null )
        {
            htBlobs.put("BLOB_DOC_CONTENT", blob_Doc_Content.getName());
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read ID_DOC.
        sItemName = "ID_DOC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Doc = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read FICHERO.
        sItemName = "FICHERO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        
        try {
          sItemValue = ai_xml.getOptionalAttValue(nItem, "value64");
        } catch (Exception v64e) {
          m_log.debug ("Empty binary string for item " + sItemName);
        }
        fichero = sItemValue;

        // read P_BLOB_PHOTO.
        sItemName = "P_BLOB_PHOTO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        
        try {
          sItemValue = ai_xml.getOptionalAttValue(nItem, "value64");
        } catch (Exception v64e) {
          m_log.debug ("Empty binary string for item " + sItemName);
        }
        p_Blob_Photo = sItemValue;

        // read DOC_EXTENSION.
        sItemName = "DOC_EXTENSION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        doc_Extension = sItemValue;

        // read DOC_TITLE_ESP.
        sItemName = "DOC_TITLE_ESP";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        doc_Title_Esp = sItemValue;

        // read DOC_CONTENT_ESP.
        sItemName = "DOC_CONTENT_ESP";
        nItem = ai_xml.findItem(ai_record, sItemName);
        
        try {
          sItemValue = ai_xml.getOptionalAttValue(nItem, "value64");
        } catch (Exception v64e) {
          m_log.debug ("Empty binary string for item " + sItemName);
        }
        doc_Content_Esp = sItemValue;

        // read BLOB_DOC_CONTENT.
        sItemName = "BLOB_DOC_CONTENT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getOptionalAttValue(nItem, "fileindex");
        if (sItemValue != null)
        {
            sItemValue = ai_m4Op.getFileByIndex(Integer.parseInt(sItemValue));
            blob_Doc_Content = new DataHandler(new M4FileDataSource(sItemValue));
        } 
        else // the case where there is no file in the item
        {
            blob_Doc_Content = null;
        }


        // read BLOB_DOC_CONTENT.
        sItemName = "BLOB_DOC_CONTENT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getOptionalAttValue(nItem, "fileindex");
        if (sItemValue != null)
        {
            sItemValue = ai_m4Op.getFileByIndex(Integer.parseInt(sItemValue));
            blob_Doc_Content = new DataHandler(new M4FileDataSource(sItemValue));
        } 
        else // the case where there is no file in the item
        {
            blob_Doc_Content = null;
        }



    } /* end of method readOperations */


} /* end of class Csp_Generar_DocRecord */

