/**
 * Csp_Planificacion_DtRecord.java
 * Self generated code for Bussines Object CSP_GD_PLANIFICACION_DT.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_gd_planificacion_dt;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Planificacion_Dt.
 * @author Meta4
 */
public 
class Csp_Planificacion_DtRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_GD_PLANIFICACION_DT";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_PLANIFICACION_DT";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Planificacion_DtRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item NOMBRE */
    public String nombre = null;
    private void setnombre(String ai_value)
    {
        nombre = ai_value;
    }
    private String getnombre()
    {
        return nombre;
    }

    /* item N_PUESTO */
    public String n_Puesto = null;
    private void setn_Puesto(String ai_value)
    {
        n_Puesto = ai_value;
    }
    private String getn_Puesto()
    {
        return n_Puesto;
    }

    /* item SCO_ID_HR */
    public String sco_Id_Hr = null;
    private void setsco_Id_Hr(String ai_value)
    {
        sco_Id_Hr = ai_value;
    }
    private String getsco_Id_Hr()
    {
        return sco_Id_Hr;
    }

    /* item APELLIDO_1 */
    public String apellido_1 = null;
    private void setapellido_1(String ai_value)
    {
        apellido_1 = ai_value;
    }
    private String getapellido_1()
    {
        return apellido_1;
    }

    /* item APELLIDO_2 */
    public String apellido_2 = null;
    private void setapellido_2(String ai_value)
    {
        apellido_2 = ai_value;
    }
    private String getapellido_2()
    {
        return apellido_2;
    }

    /* item ID_TIPO_PUESTO */
    public String id_Tipo_Puesto = null;
    private void setid_Tipo_Puesto(String ai_value)
    {
        id_Tipo_Puesto = ai_value;
    }
    private String getid_Tipo_Puesto()
    {
        return id_Tipo_Puesto;
    }

    /* item CYC_MAX_NUM_OBJ */
    public Double cyc_Max_Num_Obj = null;
    private void setcyc_Max_Num_Obj(Double ai_value)
    {
        cyc_Max_Num_Obj = ai_value;
    }
    private Double getcyc_Max_Num_Obj()
    {
        return cyc_Max_Num_Obj;
    }

    /* item CYC_MIN_NUM_OBJ */
    public Double cyc_Min_Num_Obj = null;
    private void setcyc_Min_Num_Obj(Double ai_value)
    {
        cyc_Min_Num_Obj = ai_value;
    }
    private Double getcyc_Min_Num_Obj()
    {
        return cyc_Min_Num_Obj;
    }

    /* item ID_CLASE_PUESTO */
    public String id_Clase_Puesto = null;
    private void setid_Clase_Puesto(String ai_value)
    {
        id_Clase_Puesto = ai_value;
    }
    private String getid_Clase_Puesto()
    {
        return id_Clase_Puesto;
    }

    /* item ID_ORGANIZATION */
    public String id_Organization = null;
    private void setid_Organization(String ai_value)
    {
        id_Organization = ai_value;
    }
    private String getid_Organization()
    {
        return id_Organization;
    }

    /* item SCO_ID_JOB_CODE */
    public String sco_Id_Job_Code = null;
    private void setsco_Id_Job_Code(String ai_value)
    {
        sco_Id_Job_Code = ai_value;
    }
    private String getsco_Id_Job_Code()
    {
        return sco_Id_Job_Code;
    }

    /* item ID_STATUS_PUESTO */
    public String id_Status_Puesto = null;
    private void setid_Status_Puesto(String ai_value)
    {
        id_Status_Puesto = ai_value;
    }
    private String getid_Status_Puesto()
    {
        return id_Status_Puesto;
    }

    /* item STD_ID_JOB_INT_FAM */
    public String std_Id_Job_Int_Fam = null;
    private void setstd_Id_Job_Int_Fam(String ai_value)
    {
        std_Id_Job_Int_Fam = ai_value;
    }
    private String getstd_Id_Job_Int_Fam()
    {
        return std_Id_Job_Int_Fam;
    }

    /* node CSP_OBJ_DE_PL */
    public Csp_Obj_De_PlBlock Csp_Obj_De_Pl = null;
    private void setcsp_Obj_De_Pl(Csp_Obj_De_PlBlock ai_value)
    {
        Csp_Obj_De_Pl = ai_value;
    }
    private Csp_Obj_De_PlBlock getCsp_Obj_De_Pl()
    {
        return Csp_Obj_De_Pl;
    }

    /* node CSP_COMP_DE_PL */
    public Csp_Comp_De_PlBlock Csp_Comp_De_Pl = null;
    private void setcsp_Comp_De_Pl(Csp_Comp_De_PlBlock ai_value)
    {
        Csp_Comp_De_Pl = ai_value;
    }
    private Csp_Comp_De_PlBlock getCsp_Comp_De_Pl()
    {
        return Csp_Comp_De_Pl;
    }

    /* node CSP_COMENT_DE_PL */
    public Csp_Coment_De_PlBlock Csp_Coment_De_Pl = null;
    private void setcsp_Coment_De_Pl(Csp_Coment_De_PlBlock ai_value)
    {
        Csp_Coment_De_Pl = ai_value;
    }
    private Csp_Coment_De_PlBlock getCsp_Coment_De_Pl()
    {
        return Csp_Coment_De_Pl;
    }

    /* node LIST_PLAN_EVAL_DE_PL */
    public List_Plan_Eval_De_PlBlock List_Plan_Eval_De_Pl = null;
    private void setlist_Plan_Eval_De_Pl(List_Plan_Eval_De_PlBlock ai_value)
    {
        List_Plan_Eval_De_Pl = ai_value;
    }
    private List_Plan_Eval_De_PlBlock getList_Plan_Eval_De_Pl()
    {
        return List_Plan_Eval_De_Pl;
    }

    /* node CSP_COMENT_NO_CONF_DE_PL */
    public Csp_Coment_No_Conf_De_PlBlock Csp_Coment_No_Conf_De_Pl = null;
    private void setcsp_Coment_No_Conf_De_Pl(Csp_Coment_No_Conf_De_PlBlock ai_value)
    {
        Csp_Coment_No_Conf_De_Pl = ai_value;
    }
    private Csp_Coment_No_Conf_De_PlBlock getCsp_Coment_No_Conf_De_Pl()
    {
        return Csp_Coment_No_Conf_De_Pl;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // NOMBRE.
        if (nombre != null)
        {
            htItems.put("NOMBRE", M4BusinessMethodArg.toString(nombre));
        }
        // N_PUESTO.
        if (n_Puesto != null)
        {
            htItems.put("N_PUESTO", M4BusinessMethodArg.toString(n_Puesto));
        }
        // SCO_ID_HR.
        if (sco_Id_Hr != null)
        {
            htItems.put("SCO_ID_HR", M4BusinessMethodArg.toString(sco_Id_Hr));
        }
        // APELLIDO_1.
        if (apellido_1 != null)
        {
            htItems.put("APELLIDO_1", M4BusinessMethodArg.toString(apellido_1));
        }
        // APELLIDO_2.
        if (apellido_2 != null)
        {
            htItems.put("APELLIDO_2", M4BusinessMethodArg.toString(apellido_2));
        }
        // ID_TIPO_PUESTO.
        if (id_Tipo_Puesto != null)
        {
            htItems.put("ID_TIPO_PUESTO", M4BusinessMethodArg.toString(id_Tipo_Puesto));
        }
        // CYC_MAX_NUM_OBJ.
        if (cyc_Max_Num_Obj != null)
        {
            htItems.put("CYC_MAX_NUM_OBJ", M4BusinessMethodArg.toString(cyc_Max_Num_Obj));
        }
        // CYC_MIN_NUM_OBJ.
        if (cyc_Min_Num_Obj != null)
        {
            htItems.put("CYC_MIN_NUM_OBJ", M4BusinessMethodArg.toString(cyc_Min_Num_Obj));
        }
        // ID_CLASE_PUESTO.
        if (id_Clase_Puesto != null)
        {
            htItems.put("ID_CLASE_PUESTO", M4BusinessMethodArg.toString(id_Clase_Puesto));
        }
        // ID_ORGANIZATION.
        if (id_Organization != null)
        {
            htItems.put("ID_ORGANIZATION", M4BusinessMethodArg.toString(id_Organization));
        }
        // SCO_ID_JOB_CODE.
        if (sco_Id_Job_Code != null)
        {
            htItems.put("SCO_ID_JOB_CODE", M4BusinessMethodArg.toString(sco_Id_Job_Code));
        }
        // ID_STATUS_PUESTO.
        if (id_Status_Puesto != null)
        {
            htItems.put("ID_STATUS_PUESTO", M4BusinessMethodArg.toString(id_Status_Puesto));
        }
        // STD_ID_JOB_INT_FAM.
        if (std_Id_Job_Int_Fam != null)
        {
            htItems.put("STD_ID_JOB_INT_FAM", M4BusinessMethodArg.toString(std_Id_Job_Int_Fam));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

        // write data for node CSP_OBJ_DE_PL.
        if ( Csp_Obj_De_Pl != null) 
        {
           Csp_Obj_De_Pl.writeOperations(ai_m4Op);
        }

        // write data for node CSP_COMP_DE_PL.
        if ( Csp_Comp_De_Pl != null) 
        {
           Csp_Comp_De_Pl.writeOperations(ai_m4Op);
        }

        // write data for node CSP_COMENT_DE_PL.
        if ( Csp_Coment_De_Pl != null) 
        {
           Csp_Coment_De_Pl.writeOperations(ai_m4Op);
        }

        // write data for node LIST_PLAN_EVAL_DE_PL.
        if ( List_Plan_Eval_De_Pl != null) 
        {
           List_Plan_Eval_De_Pl.writeOperations(ai_m4Op);
        }

        // write data for node CSP_COMENT_NO_CONF_DE_PL.
        if ( Csp_Coment_No_Conf_De_Pl != null) 
        {
           Csp_Coment_No_Conf_De_Pl.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read NOMBRE.
        sItemName = "NOMBRE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        nombre = sItemValue;

        // read N_PUESTO.
        sItemName = "N_PUESTO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        n_Puesto = sItemValue;

        // read SCO_ID_HR.
        sItemName = "SCO_ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Hr = sItemValue;

        // read APELLIDO_1.
        sItemName = "APELLIDO_1";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        apellido_1 = sItemValue;

        // read APELLIDO_2.
        sItemName = "APELLIDO_2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        apellido_2 = sItemValue;

        // read ID_TIPO_PUESTO.
        sItemName = "ID_TIPO_PUESTO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Tipo_Puesto = sItemValue;

        // read CYC_MAX_NUM_OBJ.
        sItemName = "CYC_MAX_NUM_OBJ";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Max_Num_Obj = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_MIN_NUM_OBJ.
        sItemName = "CYC_MIN_NUM_OBJ";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Min_Num_Obj = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read ID_CLASE_PUESTO.
        sItemName = "ID_CLASE_PUESTO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Clase_Puesto = sItemValue;

        // read ID_ORGANIZATION.
        sItemName = "ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Organization = sItemValue;

        // read SCO_ID_JOB_CODE.
        sItemName = "SCO_ID_JOB_CODE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Job_Code = sItemValue;

        // read ID_STATUS_PUESTO.
        sItemName = "ID_STATUS_PUESTO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Status_Puesto = sItemValue;

        // read STD_ID_JOB_INT_FAM.
        sItemName = "STD_ID_JOB_INT_FAM";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Id_Job_Int_Fam = sItemValue;

        // read data for node CSP_OBJ_DE_PL.
        Csp_Obj_De_Pl = new Csp_Obj_De_PlBlock();
        Csp_Obj_De_Pl.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_Obj_De_PlBlock.NODE_NAME));

        // read data for node CSP_COMP_DE_PL.
        Csp_Comp_De_Pl = new Csp_Comp_De_PlBlock();
        Csp_Comp_De_Pl.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_Comp_De_PlBlock.NODE_NAME));

        // read data for node CSP_COMENT_DE_PL.
        Csp_Coment_De_Pl = new Csp_Coment_De_PlBlock();
        Csp_Coment_De_Pl.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_Coment_De_PlBlock.NODE_NAME));

        // read data for node LIST_PLAN_EVAL_DE_PL.
        List_Plan_Eval_De_Pl = new List_Plan_Eval_De_PlBlock();
        List_Plan_Eval_De_Pl.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + List_Plan_Eval_De_PlBlock.NODE_NAME));

        // read data for node CSP_COMENT_NO_CONF_DE_PL.
        Csp_Coment_No_Conf_De_Pl = new Csp_Coment_No_Conf_De_PlBlock();
        Csp_Coment_No_Conf_De_Pl.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_Coment_No_Conf_De_PlBlock.NODE_NAME));


    } /* end of method readOperations */


} /* end of class Csp_Planificacion_DtRecord */

