// Generado por scripts/portal/soap-catalog.ts. No editar a mano.
import type { SoapServiceContract } from "./types";

export const SOAP_CATALOG = {
  CSP_CONSULTA_LIST_EMPL: {
    service: "CSP_CONSULTA_LIST_EMPL",
    m4Object: "CSP_CONSULTA_LIST_EMPL",
    deployedInWsdd: true,
    serialization: {
      style: "wrapped",
      use: "literal",
      namespace: "http://schemas.meta4.com/",
      encodingStyle: "",
    },
    operations: [
      {
        operation: "CSP_CONSULTA_LIST_EMPL",
        methodNode: "CSP_CONSULTA_LIST_EMPL",
        methodName: "CSP_CONSULTA_LIST_EMPL",
        args: [
          {
            name: "ARG_SOCIEDAD",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "ARG_LISTA_UNIDAD",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
        ],
        blocks: [
          {
            field: "Csp_Consulta_List_Empl",
            node: "CSP_CONSULTA_LIST_EMPL",
            recordSet: "Csp_Consulta_List_EmplRecordSet",
            items: ["ID_EMPLEADO"],
            children: [],
          },
        ],
      },
      {
        operation: "M4LoadObject",
        methodNode: "CSP_CONSULTA_LIST_EMPL",
        methodName: "ROOTLOAD",
        args: [
          {
            name: "CSP_CONSULTA_LIST_EMPL",
            kind: "block",
            node: "CSP_CONSULTA_LIST_EMPL",
            xmlType: "m4:Csp_Consulta_List_EmplBlock",
            nullable: true,
          },
        ],
        blocks: [
          {
            field: "Csp_Consulta_List_Empl",
            node: "CSP_CONSULTA_LIST_EMPL",
            recordSet: "Csp_Consulta_List_EmplRecordSet",
            items: ["ID_EMPLEADO"],
            children: [],
          },
        ],
      },
    ],
  },
  CSP_CONSULTA_ORO_INTRAN_WU: {
    service: "CSP_CONSULTA_ORO_INTRAN_WU",
    m4Object: "CSP_CONSULTA_ORO_INTRAN_WU",
    deployedInWsdd: true,
    serialization: {
      style: "wrapped",
      use: "literal",
      namespace: "http://schemas.meta4.com/",
      encodingStyle: "",
    },
    operations: [
      {
        operation: "CSP_CONSULTA_ORO_INTRAN_WU",
        methodNode: "CSP_CONSULTA_ORO_INTRAN_WU",
        methodName: "CSP_CONSULTA_ORO_INTRAN_WU",
        args: [
          {
            name: "ARG_SOCIEDAD",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "ARG_ID_UNIDAD",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "ARG_TIPO_NODO",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "ARG_RAIZ",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "ARG_PADRE",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
        ],
        blocks: [
          {
            field: "Csp_Consulta_Oro_Intran_Wu",
            node: "CSP_CONSULTA_ORO_INTRAN_WU",
            recordSet: "Csp_Consulta_Oro_Intran_WuRecordSet",
            items: [
              "NOMBRE",
              "ID_PUESTO",
              "N_PUESTOV",
              "APELLIDO_1",
              "APELLIDO_2",
              "ID_EMPLEADO",
              "N_TIPO_PUESTO",
              "ID_TIPO_PUESTO",
              "STD_ID_WU_TYPE",
              "ID_ORGANIZATION",
              "STD_N_WORK_UNIT",
              "STD_ID_WORK_UNIT",
              "STD_N_WORK_UNIT_1",
              "STD_ID_WU_INT_TYPE",
              "SCO_ID_WORK_UNIT_PARENT",
            ],
            children: [],
          },
        ],
      },
      {
        operation: "M4LoadObject",
        methodNode: "CSP_CONSULTA_ORO_INTRAN_WU",
        methodName: "SYS_LOAD_SERVER",
        args: [
          {
            name: "CSP_BUSQUEDA_RECURSIVA",
            kind: "block",
            node: "CSP_BUSQUEDA_RECURSIVA",
            xmlType: "m4:Csp_Busqueda_RecursivaBlock",
            nullable: true,
          },
          {
            name: "CSP_CONSULTA_ORO_INTRAN_WU",
            kind: "block",
            node: "CSP_CONSULTA_ORO_INTRAN_WU",
            xmlType: "m4:Csp_Consulta_Oro_Intran_WuBlock",
            nullable: true,
          },
        ],
        blocks: [
          {
            field: "Csp_Busqueda_Recursiva",
            node: "CSP_BUSQUEDA_RECURSIVA",
            recordSet: "Csp_Busqueda_RecursivaRecordSet",
            items: [
              "NOMBRE",
              "ID_PUESTO",
              "N_PUESTOV",
              "APELLIDO_1",
              "APELLIDO_2",
              "ID_EMPLEADO",
              "N_TIPO_PUESTO",
              "ID_TIPO_PUESTO",
              "STD_ID_WU_TYPE",
              "ID_ORGANIZATION",
              "STD_N_WORK_UNIT",
              "STD_ID_WORK_UNIT",
              "STD_N_WORK_UNIT_1",
              "STD_ID_WU_INT_TYPE",
              "SCO_ID_WORK_UNIT_PARENT",
            ],
            children: [],
          },
          {
            field: "Csp_Consulta_Oro_Intran_Wu",
            node: "CSP_CONSULTA_ORO_INTRAN_WU",
            recordSet: "Csp_Consulta_Oro_Intran_WuRecordSet",
            items: [
              "NOMBRE",
              "ID_PUESTO",
              "N_PUESTOV",
              "APELLIDO_1",
              "APELLIDO_2",
              "ID_EMPLEADO",
              "N_TIPO_PUESTO",
              "ID_TIPO_PUESTO",
              "STD_ID_WU_TYPE",
              "ID_ORGANIZATION",
              "STD_N_WORK_UNIT",
              "STD_ID_WORK_UNIT",
              "STD_N_WORK_UNIT_1",
              "STD_ID_WU_INT_TYPE",
              "SCO_ID_WORK_UNIT_PARENT",
            ],
            children: [],
          },
        ],
      },
    ],
  },
  CSP_CONSULTA_ORO_NEW: {
    service: "CSP_CONSULTA_ORO_NEW",
    m4Object: "CSP_CONSULTA_ORO_NEW",
    deployedInWsdd: true,
    serialization: {
      style: "wrapped",
      use: "literal",
      namespace: "http://schemas.meta4.com/",
      encodingStyle: "",
    },
    operations: [
      {
        operation: "CSP_CONSULTA_ORO_NEW",
        methodNode: "CSP_CONSULTA_ORO",
        methodName: "CSP_CONSULTA_ORO",
        args: [
          {
            name: "ARG_SOCIEDAD",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "ARG_EMPLEADO",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "ARG_COMPUTA",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
        ],
        blocks: [
          {
            field: "Csp_Consulta_Oro",
            node: "CSP_CONSULTA_ORO",
            recordSet: "Csp_Consulta_OroRecordSet",
            items: [
              "CORREO",
              "NOMBRE",
              "N_AREA",
              "COMPUTA",
              "ID_AREA",
              "NOMBREV",
              "N_AREAV",
              "ID_LEGAL",
              "N_PUESTO",
              "N_UNIDAD",
              "ID_PUESTO",
              "ID_UNIDAD",
              "N_PUESTOV",
              "N_UNIDADV",
              "APELLIDO_1",
              "APELLIDO_2",
              "CLAVE_SELF",
              "N_SERVICIO",
              "APELLIDO_1V",
              "APELLIDO_2V",
              "ID_EMPLEADO",
              "ID_SERVICIO",
              "N_DIRECCION",
              "N_SERVICIOV",
              "ID_DIRECCION",
              "ID_TIPO_AREA",
              "N_DIRECCIONV",
              "N_TIPO_PUESTO",
              "N_UNIDAD_RAIZ",
              "FEC_ANTIGUEDAD",
              "FEC_NACIMIENTO",
              "ID_RESPONSABLE",
              "ID_TIPO_PUESTO",
              "ID_TIPO_UNIDAD",
              "ID_UNIDAD_RAIZ",
              "N_CLASE_PUESTO",
              "N_UNIDAD_RAIZV",
              "ID_CLASE_PUESTO",
              "ID_ESTADO_CIVIL",
              "N_CENT_TRAB_FIS",
              "N_STATUS_PUESTO",
              "CSP_LUGAR_WU_ORO",
              "ID_CENT_TRAB_FIS",
              "ID_STATUS_PUESTO",
              "ID_TIPO_SERVICIO",
              "N_CENTRO_TRABAJO",
              "FEC_ALTA_EMPLEADO",
              "ID_CENTRO_TRABAJO",
              "ID_TIPO_DIRECCION",
              "NUM_AFILIACION_SS",
              "N_CENTRO_TRABAJOV",
              "DIR_CENTRO_TRABAJO",
              "N_LUGAR_WU_ORO_AREA",
              "N_LUGAR_WU_ORO_UNIDAD",
              "N_LUGAR_WU_ORO_SERVICIO",
              "N_LUGAR_WU_ORO_DIRECCION",
            ],
            children: [],
          },
        ],
      },
      {
        operation: "M4LoadObject",
        methodNode: "CSP_CONSULTA_ORO",
        methodName: "ROOTLOAD",
        args: [
          {
            name: "CSP_CONSULTA_ORO",
            kind: "block",
            node: "CSP_CONSULTA_ORO",
            xmlType: "m4:Csp_Consulta_OroBlock",
            nullable: true,
          },
        ],
        blocks: [
          {
            field: "Csp_Consulta_Oro",
            node: "CSP_CONSULTA_ORO",
            recordSet: "Csp_Consulta_OroRecordSet",
            items: [
              "CORREO",
              "NOMBRE",
              "N_AREA",
              "COMPUTA",
              "ID_AREA",
              "NOMBREV",
              "N_AREAV",
              "ID_LEGAL",
              "N_PUESTO",
              "N_UNIDAD",
              "ID_PUESTO",
              "ID_UNIDAD",
              "N_PUESTOV",
              "N_UNIDADV",
              "APELLIDO_1",
              "APELLIDO_2",
              "CLAVE_SELF",
              "N_SERVICIO",
              "APELLIDO_1V",
              "APELLIDO_2V",
              "ID_EMPLEADO",
              "ID_SERVICIO",
              "N_DIRECCION",
              "N_SERVICIOV",
              "ID_DIRECCION",
              "ID_TIPO_AREA",
              "N_DIRECCIONV",
              "N_TIPO_PUESTO",
              "N_UNIDAD_RAIZ",
              "FEC_ANTIGUEDAD",
              "FEC_NACIMIENTO",
              "ID_RESPONSABLE",
              "ID_TIPO_PUESTO",
              "ID_TIPO_UNIDAD",
              "ID_UNIDAD_RAIZ",
              "N_CLASE_PUESTO",
              "N_UNIDAD_RAIZV",
              "ID_CLASE_PUESTO",
              "ID_ESTADO_CIVIL",
              "N_CENT_TRAB_FIS",
              "N_STATUS_PUESTO",
              "CSP_LUGAR_WU_ORO",
              "ID_CENT_TRAB_FIS",
              "ID_STATUS_PUESTO",
              "ID_TIPO_SERVICIO",
              "N_CENTRO_TRABAJO",
              "FEC_ALTA_EMPLEADO",
              "ID_CENTRO_TRABAJO",
              "ID_TIPO_DIRECCION",
              "NUM_AFILIACION_SS",
              "N_CENTRO_TRABAJOV",
              "DIR_CENTRO_TRABAJO",
              "N_LUGAR_WU_ORO_AREA",
              "N_LUGAR_WU_ORO_UNIDAD",
              "N_LUGAR_WU_ORO_SERVICIO",
              "N_LUGAR_WU_ORO_DIRECCION",
            ],
            children: [],
          },
        ],
      },
    ],
  },
  CSP_CONSULTA_WORK_UNIT: {
    service: "CSP_CONSULTA_WORK_UNIT",
    m4Object: "CSP_CONSULTA_WORK_UNIT",
    deployedInWsdd: true,
    serialization: {
      style: "wrapped",
      use: "literal",
      namespace: "http://schemas.meta4.com/",
      encodingStyle: "",
    },
    operations: [
      {
        operation: "CSP_CONSULTA_WORK_UNIT",
        methodNode: "CSP_CONSULTA_7",
        methodName: "CSP_CONSULTA_7",
        args: [
          {
            name: "ARG_UNIDAD",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
        ],
        blocks: [
          {
            field: "Csp_Consulta_7",
            node: "CSP_CONSULTA_7",
            recordSet: "Csp_Consulta_7RecordSet",
            items: ["STD_N_WORK_UNIT", "STD_N_WU_INT_TYPE", "SCO_ID_WORK_UNIT_PARENT"],
            children: [],
          },
        ],
      },
      {
        operation: "M4LoadObject",
        methodNode: "CSP_CONSULTA_7",
        methodName: "ROOTLOAD",
        args: [
          {
            name: "CSP_CONSULTA_7",
            kind: "block",
            node: "CSP_CONSULTA_7",
            xmlType: "m4:Csp_Consulta_7Block",
            nullable: true,
          },
        ],
        blocks: [
          {
            field: "Csp_Consulta_7",
            node: "CSP_CONSULTA_7",
            recordSet: "Csp_Consulta_7RecordSet",
            items: ["STD_N_WORK_UNIT", "STD_N_WU_INT_TYPE", "SCO_ID_WORK_UNIT_PARENT"],
            children: [],
          },
        ],
      },
    ],
  },
  CSP_SERVICIO_CV: {
    service: "CSP_SERVICIO_CV",
    m4Object: "CSP_SERVICIO_CV",
    deployedInWsdd: true,
    serialization: {
      style: "wrapped",
      use: "literal",
      namespace: "http://schemas.meta4.com/",
      encodingStyle: "",
    },
    operations: [
      {
        operation: "CSP_SERVICIO_CV",
        methodNode: "CSP_SERVICIO_CV",
        methodName: "CARGA",
        args: [
          {
            name: "ARG_ID_EMPLEADO",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
        ],
        blocks: [
          {
            field: "Csp_Servicio_Cv",
            node: "CSP_SERVICIO_CV",
            recordSet: "Csp_Servicio_CvRecordSet",
            items: [],
            children: [],
          },
        ],
      },
      {
        operation: "M4LoadObject",
        methodNode: "CSP_CV",
        methodName: "SYS_LOAD_SERVER",
        args: [
          {
            name: "CSP_CV",
            kind: "block",
            node: "CSP_CV",
            xmlType: "m4:Csp_CvBlock",
            nullable: true,
          },
          {
            name: "CSP_SERVICIO_CV",
            kind: "block",
            node: "CSP_SERVICIO_CV",
            xmlType: "m4:Csp_Servicio_CvBlock",
            nullable: true,
          },
          {
            name: "CSP_PARAM_GLOBAL",
            kind: "block",
            node: "CSP_PARAM_GLOBAL",
            xmlType: "m4:Csp_Param_GlobalBlock",
            nullable: true,
          },
          {
            name: "T_AUX_FILE_MANAGER",
            kind: "block",
            node: "T_AUX_FILE_MANAGER",
            xmlType: "m4:T_Aux_File_ManagerBlock",
            nullable: true,
          },
        ],
        blocks: [
          {
            field: "Csp_Cv",
            node: "CSP_CV",
            recordSet: "Csp_CvRecordSet",
            items: [
              "STD_EMAIL",
              "STD_ID_HR",
              "SCO_DT_START",
              "STD_DT_BIRTH",
              "SCO_BLOB_PHOTO",
              "STD_N_JOB_CODE",
              "ID_ORGANIZATION",
              "SSP_ID_CATEGORIA",
              "SSP_NM_CATEGORIA",
              "STD_N_FIRST_NAME",
              "SSP_FEC_ANTIGUEDAD",
              "STD_N_FAMILY_NAME_1",
              "CSP_N_WORK_FUNCTIONAL",
              "CSP_ID_WORK_FUNCTIONAL",
            ],
            children: [
              {
                field: "Csp_Idiomas",
                node: "CSP_IDIOMAS",
                recordSet: "Csp_IdiomasRecordSet",
                items: [
                  "CSP_TOEIC",
                  "STD_N_LANGUAGE",
                  "CSP_FECHA_TOEIC",
                  "STD_ID_LANGUAGE",
                  "STD_N_LANG_LEVEL",
                ],
                children: [],
              },
              {
                field: "Csp_Titulacion",
                node: "CSP_TITULACION",
                recordSet: "Csp_TitulacionRecordSet",
                items: [
                  "STD_COMMENT",
                  "STD_DT_START",
                  "STD_N_EDU_SP",
                  "STD_ID_EDU_SP",
                  "STD_ID_SECTOR",
                  "STD_N_COUNTRY",
                  "STD_N_EXT_ORG",
                  "SCO_CK_END_DIP",
                  "STD_ID_DIPLOMA",
                  "STD_N_EDU_TYPE",
                  "STD_ID_EDU_TYPE",
                  "STD_ORD_ACD_BACK",
                  "STD_ID_EDU_CENTER",
                  "STD_DT_EARNED_EXPE",
                  "STD_ID_SUB_GEO_DIV",
                  "STD_COMPLETED_YEARS",
                  "STD_DESC_EDU_CENTER",
                  "STD_TOTAL_YEARS_DIP",
                ],
                children: [],
              },
              {
                field: "Csp_Otros_Titulos",
                node: "CSP_OTROS_TITULOS",
                recordSet: "Csp_Otros_TitulosRecordSet",
                items: ["DT_END", "DT_START", "CSP_TITULO"],
                children: [],
              },
              {
                field: "Csp_Certificados_Cv",
                node: "CSP_CERTIFICADOS_CV",
                recordSet: "Csp_Certificados_CvRecordSet",
                items: [
                  "SCO_COMMENT",
                  "SCO_DT_ISSUE",
                  "SCO_N_CERTIF",
                  "SCO_DT_EXPIRED",
                  "SCO_ID_COUNTRY",
                  "SCO_CERT_NUMBER",
                  "SCO_OR_CERTIF_LIC",
                  "SCO_ID_CERTIF_TYPE",
                  "SCO_ID_ISSUE_ENTIT",
                ],
                children: [],
              },
              {
                field: "Csp_Formacion_Externa",
                node: "CSP_FORMACION_EXTERNA",
                recordSet: "Csp_Formacion_ExternaRecordSet",
                items: [
                  "SCO_DT_END",
                  "SCO_DT_START",
                  "SCO_N_CENTER",
                  "SCO_N_COURSE",
                  "SCO_NUMBER_HOURS",
                ],
                children: [],
              },
              {
                field: "Csp_Formacion_Interna",
                node: "CSP_FORMACION_INTERNA",
                recordSet: "Csp_Formacion_InternaRecordSet",
                items: [
                  "SCO_DT_END",
                  "SCO_DT_START",
                  "SCO_N_CENTER",
                  "SCO_N_COURSE",
                  "SCO_NUMBER_HOURS",
                ],
                children: [],
              },
              {
                field: "Csp_Experiencia_Prof_Externa",
                node: "CSP_EXPERIENCIA_PROF_EXTERNA",
                recordSet: "Csp_Experiencia_Prof_ExternaRecordSet",
                items: [
                  "STD_DT_END",
                  "STD_DT_START",
                  "STD_EMPLOYER",
                  "STD_N_SECTOR",
                  "STD_N_COUNTRY",
                  "STD_INITIAL_JOB",
                ],
                children: [],
              },
              {
                field: "Csp_Experiencia_Prof_Interna",
                node: "CSP_EXPERIENCIA_PROF_INTERNA",
                recordSet: "Csp_Experiencia_Prof_InternaRecordSet",
                items: ["STD_DT_END", "STD_DT_START", "CSP_N_PREV_JOB"],
                children: [],
              },
            ],
          },
          {
            field: "Csp_Servicio_Cv",
            node: "CSP_SERVICIO_CV",
            recordSet: "Csp_Servicio_CvRecordSet",
            items: [],
            children: [],
          },
          {
            field: "Csp_Param_Global",
            node: "CSP_PARAM_GLOBAL",
            recordSet: "Csp_Param_GlobalRecordSet",
            items: ["VALOR", "PARAMETRO"],
            children: [],
          },
          {
            field: "T_Aux_File_Manager",
            node: "T_AUX_FILE_MANAGER",
            recordSet: "T_Aux_File_ManagerRecordSet",
            items: [],
            children: [],
          },
        ],
      },
    ],
  },
  M4_PNET_INITIAL_DATA: {
    service: "M4_PNET_INITIAL_DATA",
    m4Object: "M4_PNET_INITIAL_DATA",
    deployedInWsdd: true,
    serialization: {
      style: "wrapped",
      use: "literal",
      namespace: "http://schemas.meta4.com/",
      encodingStyle: "",
    },
    operations: [
      {
        operation: "LOAD_DATA",
        methodNode: "M4_PNET_INITIAL_DATA",
        methodName: "LOAD_DATA",
        args: [
          {
            name: "APPLICATIONS",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "LOAD_ANALYTICAL",
            kind: "number",
            xmlType: "xsd:double",
            nullable: true,
          },
          {
            name: "LOAD_WORKLIST",
            kind: "number",
            xmlType: "xsd:double",
            nullable: true,
          },
        ],
        blocks: [],
      },
      {
        operation: "M4LoadObject",
        methodNode: "M4_PNET_INITIAL_DATA",
        methodName: "ROOTLOAD",
        args: [
          {
            name: "M4_PNET_INITIAL_DATA",
            kind: "block",
            node: "M4_PNET_INITIAL_DATA",
            xmlType: "m4:M4_Pnet_Initial_DataBlock",
            nullable: true,
          },
        ],
        blocks: [
          {
            field: "M4_Pnet_Initial_Data",
            node: "M4_PNET_INITIAL_DATA",
            recordSet: "M4_Pnet_Initial_DataRecordSet",
            items: [],
            children: [],
          },
        ],
      },
    ],
  },
  PGCO_ES_WS_VALIDATIONS: {
    service: "PGCO_ES_WS_VALIDATIONS",
    m4Object: "PGCO_ES_WS_VALIDATIONS",
    deployedInWsdd: true,
    serialization: {
      style: "wrapped",
      use: "literal",
      namespace: "http://schemas.meta4.com/",
      encodingStyle: "",
    },
    operations: [
      {
        operation: "PGCO_TASKS",
        methodNode: "PGCO_ES_WS_VALIDATIONS",
        methodName: "PGCO_TASKS",
        args: [],
        blocks: [
          {
            field: "Pgco_Es_Ws_Validations",
            node: "PGCO_ES_WS_VALIDATIONS",
            recordSet: "Pgco_Es_Ws_ValidationsRecordSet",
            items: [
              "PGCO_LEVEL",
              "PGCO_TITLE",
              "PGCO_TOOLTIP",
              "PGCO_VAL_LINK",
              "PGCO_DESC_LINK",
              "PGCO_TASK_LINK",
              "PGCO_VAL_COUNT",
              "PGCO_VAL_TITLE",
              "PGCO_LINK_LEVEL",
              "PGCO_TASK_COUNT",
              "PGCO_TASK_TITLE",
              "PGCO_COUNT_LEVEL",
              "PGCO_LAST_UPDATE",
              "PGCO_VAL_TOOLTIP",
              "PGCO_TASK_TOOLTIP",
              "PGCO_TOOLTIP_LEVEL",
              "PGCO_TASK_DT_DEADLINE",
            ],
            children: [],
          },
        ],
      },
      {
        operation: "PGCO_VALUATIONS",
        methodNode: "PGCO_ES_WS_VALIDATIONS",
        methodName: "PGCO_VALUATIONS",
        args: [],
        blocks: [
          {
            field: "Pgco_Es_Ws_Validations",
            node: "PGCO_ES_WS_VALIDATIONS",
            recordSet: "Pgco_Es_Ws_ValidationsRecordSet",
            items: [
              "PGCO_LEVEL",
              "PGCO_TITLE",
              "PGCO_TOOLTIP",
              "PGCO_VAL_LINK",
              "PGCO_DESC_LINK",
              "PGCO_TASK_LINK",
              "PGCO_VAL_COUNT",
              "PGCO_VAL_TITLE",
              "PGCO_LINK_LEVEL",
              "PGCO_TASK_COUNT",
              "PGCO_TASK_TITLE",
              "PGCO_COUNT_LEVEL",
              "PGCO_LAST_UPDATE",
              "PGCO_VAL_TOOLTIP",
              "PGCO_TASK_TOOLTIP",
              "PGCO_TOOLTIP_LEVEL",
              "PGCO_TASK_DT_DEADLINE",
            ],
            children: [],
          },
        ],
      },
      {
        operation: "PGCO_VALIDATIONS",
        methodNode: "PGCO_ES_WS_VALIDATIONS",
        methodName: "PGCO_VALIDATIONS",
        args: [],
        blocks: [
          {
            field: "Pgco_Es_Ws_Validations",
            node: "PGCO_ES_WS_VALIDATIONS",
            recordSet: "Pgco_Es_Ws_ValidationsRecordSet",
            items: [
              "PGCO_LEVEL",
              "PGCO_TITLE",
              "PGCO_TOOLTIP",
              "PGCO_VAL_LINK",
              "PGCO_DESC_LINK",
              "PGCO_TASK_LINK",
              "PGCO_VAL_COUNT",
              "PGCO_VAL_TITLE",
              "PGCO_LINK_LEVEL",
              "PGCO_TASK_COUNT",
              "PGCO_TASK_TITLE",
              "PGCO_COUNT_LEVEL",
              "PGCO_LAST_UPDATE",
              "PGCO_VAL_TOOLTIP",
              "PGCO_TASK_TOOLTIP",
              "PGCO_TOOLTIP_LEVEL",
              "PGCO_TASK_DT_DEADLINE",
            ],
            children: [],
          },
        ],
      },
      {
        operation: "M4LoadObject",
        methodNode: "PGCO_ES_WS_VALIDATIONS",
        methodName: "ROOTLOAD",
        args: [
          {
            name: "PGCO_ES_WS_VALIDATIONS",
            kind: "block",
            node: "PGCO_ES_WS_VALIDATIONS",
            xmlType: "m4:Pgco_Es_Ws_ValidationsBlock",
            nullable: true,
          },
        ],
        blocks: [
          {
            field: "Pgco_Es_Ws_Validations",
            node: "PGCO_ES_WS_VALIDATIONS",
            recordSet: "Pgco_Es_Ws_ValidationsRecordSet",
            items: [
              "PGCO_LEVEL",
              "PGCO_TITLE",
              "PGCO_TOOLTIP",
              "PGCO_VAL_LINK",
              "PGCO_DESC_LINK",
              "PGCO_TASK_LINK",
              "PGCO_VAL_COUNT",
              "PGCO_VAL_TITLE",
              "PGCO_LINK_LEVEL",
              "PGCO_TASK_COUNT",
              "PGCO_TASK_TITLE",
              "PGCO_COUNT_LEVEL",
              "PGCO_LAST_UPDATE",
              "PGCO_VAL_TOOLTIP",
              "PGCO_TASK_TOOLTIP",
              "PGCO_TOOLTIP_LEVEL",
              "PGCO_TASK_DT_DEADLINE",
            ],
            children: [],
          },
        ],
      },
    ],
  },
  SNTC_AD_MANAGERS: {
    service: "SNTC_AD_MANAGERS",
    m4Object: "SNTC_AD_MANAGERS",
    deployedInWsdd: true,
    serialization: {
      style: "rpc",
      use: "encoded",
      namespace: "http://schemas.meta4.com/",
      encodingStyle: "http://schemas.xmlsoap.org/soap/encoding/",
    },
    operations: [
      {
        operation: "MOVETO_WU",
        methodNode: "SNCO_AD_MANAGERS",
        methodName: "MOVETO_WU",
        args: [
          {
            name: "AI_SID_WU",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "SNCO_AD_MANAGERS",
            kind: "block",
            node: "SNCO_AD_MANAGERS",
            xmlType: "m4:Snco_Ad_ManagersBlock",
            nullable: true,
          },
        ],
        blocks: [
          {
            field: "Snco_Ad_Managers",
            node: "SNCO_AD_MANAGERS",
            recordSet: "Snco_Ad_ManagersRecordSet",
            items: [
              "STD_N_WU",
              "SCO_ID_HR",
              "SCO_ID_WU",
              "SCO_DT_END",
              "SCO_DT_START",
              "SCO_ID_TYPE_RESP",
              "SCO_ID_WU_PARENT",
              "SCO_OR_HR_PERIOD",
              "SCO_MANAGER_OBJETIVES",
            ],
            children: [
              {
                field: "Snco_Info_Person",
                node: "SNCO_INFO_PERSON",
                recordSet: "Snco_Info_PersonRecordSet",
                items: [
                  "DT_START",
                  "SCO_ID_HR",
                  "SCO_PHOTO_SERV",
                  "HAS_PRIVATE_DATA",
                  "SCO_OR_HR_PERIOD",
                ],
                children: [],
              },
              {
                field: "Snco_Ad_Wu_By_Manager",
                node: "SNCO_AD_WU_BY_MANAGER",
                recordSet: "Snco_Ad_Wu_By_ManagerRecordSet",
                items: ["SCO_ID_WU", "SCO_ID_WU_PARENT"],
                children: [],
              },
              {
                field: "Snco_Ad_Wu_Objectives",
                node: "SNCO_AD_WU_OBJECTIVES",
                recordSet: "Snco_Ad_Wu_ObjectivesRecordSet",
                items: [
                  "SCO_MEANING",
                  "SCO_PERCENT",
                  "SCO_DT_START",
                  "SCO_ID_LEVEL",
                  "SCO_ID_MAGNITUD",
                  "SCO_ID_OBJECTIVE",
                  "SCO_NM_MAGNITUDE",
                  "SCO_NM_OBJECTIVE",
                ],
                children: [],
              },
              {
                field: "Snco_Ad_Count_Employees",
                node: "SNCO_AD_COUNT_EMPLOYEES",
                recordSet: "Snco_Ad_Count_EmployeesRecordSet",
                items: ["COUNT_EMPLOYEE"],
                children: [],
              },
            ],
          },
        ],
      },
      {
        operation: "LOAD_MANAGERS",
        methodNode: "SNCO_AD_MANAGERS",
        methodName: "LOAD_MANAGERS",
        args: [
          {
            name: "AI_ID_WU",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "AI_ID_TYPE_RESP",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "AI_DFILTER_DATE",
            kind: "date",
            xmlType: "xsd:dateTime",
            nullable: true,
          },
          {
            name: "AI_BONLY_FIRST_LEVEL",
            kind: "number",
            xmlType: "xsd:double",
            nullable: true,
          },
          {
            name: "SNCO_AD_MANAGERS",
            kind: "block",
            node: "SNCO_AD_MANAGERS",
            xmlType: "m4:Snco_Ad_ManagersBlock",
            nullable: true,
          },
        ],
        blocks: [
          {
            field: "Snco_Ad_Managers",
            node: "SNCO_AD_MANAGERS",
            recordSet: "Snco_Ad_ManagersRecordSet",
            items: [
              "STD_N_WU",
              "SCO_ID_HR",
              "SCO_ID_WU",
              "SCO_DT_END",
              "SCO_DT_START",
              "SCO_ID_TYPE_RESP",
              "SCO_ID_WU_PARENT",
              "SCO_OR_HR_PERIOD",
              "SCO_MANAGER_OBJETIVES",
            ],
            children: [
              {
                field: "Snco_Info_Person",
                node: "SNCO_INFO_PERSON",
                recordSet: "Snco_Info_PersonRecordSet",
                items: [
                  "DT_START",
                  "SCO_ID_HR",
                  "SCO_PHOTO_SERV",
                  "HAS_PRIVATE_DATA",
                  "SCO_OR_HR_PERIOD",
                ],
                children: [],
              },
              {
                field: "Snco_Ad_Wu_By_Manager",
                node: "SNCO_AD_WU_BY_MANAGER",
                recordSet: "Snco_Ad_Wu_By_ManagerRecordSet",
                items: ["SCO_ID_WU", "SCO_ID_WU_PARENT"],
                children: [],
              },
              {
                field: "Snco_Ad_Wu_Objectives",
                node: "SNCO_AD_WU_OBJECTIVES",
                recordSet: "Snco_Ad_Wu_ObjectivesRecordSet",
                items: [
                  "SCO_MEANING",
                  "SCO_PERCENT",
                  "SCO_DT_START",
                  "SCO_ID_LEVEL",
                  "SCO_ID_MAGNITUD",
                  "SCO_ID_OBJECTIVE",
                  "SCO_NM_MAGNITUDE",
                  "SCO_NM_OBJECTIVE",
                ],
                children: [],
              },
              {
                field: "Snco_Ad_Count_Employees",
                node: "SNCO_AD_COUNT_EMPLOYEES",
                recordSet: "Snco_Ad_Count_EmployeesRecordSet",
                items: ["COUNT_EMPLOYEE"],
                children: [],
              },
            ],
          },
        ],
      },
      {
        operation: "M4LoadObject",
        methodNode: "SNCO_AD_MANAGERS",
        methodName: "SYS_LOAD_SERVER",
        args: [
          {
            name: "SNCO_AD_MANAGERS",
            kind: "block",
            node: "SNCO_AD_MANAGERS",
            xmlType: "m4:Snco_Ad_ManagersBlock",
            nullable: true,
          },
          {
            name: "SNCO_AD_POP_CONST",
            kind: "block",
            node: "SNCO_AD_POP_CONST",
            xmlType: "m4:Snco_Ad_Pop_ConstBlock",
            nullable: true,
          },
          {
            name: "SNCO_AD_INFO_PERSON",
            kind: "block",
            node: "SNCO_AD_INFO_PERSON",
            xmlType: "m4:Snco_Ad_Info_PersonBlock",
            nullable: true,
          },
          {
            name: "SNCO_AD_HIERARCHIC_WU",
            kind: "block",
            node: "SNCO_AD_HIERARCHIC_WU",
            xmlType: "m4:Snco_Ad_Hierarchic_WuBlock",
            nullable: true,
          },
          {
            name: "SNCO_AD_INFO_PERSON_PRIVATE",
            kind: "block",
            node: "SNCO_AD_INFO_PERSON_PRIVATE",
            xmlType: "m4:Snco_Ad_Info_Person_PrivateBlock",
            nullable: true,
          },
          {
            name: "SNCO_AD_POP_MAX_SCALE_LEVEL",
            kind: "block",
            node: "SNCO_AD_POP_MAX_SCALE_LEVEL",
            xmlType: "m4:Snco_Ad_Pop_Max_Scale_LevelBlock",
            nullable: true,
          },
        ],
        blocks: [
          {
            field: "Snco_Ad_Managers",
            node: "SNCO_AD_MANAGERS",
            recordSet: "Snco_Ad_ManagersRecordSet",
            items: [
              "STD_N_WU",
              "SCO_ID_HR",
              "SCO_ID_WU",
              "SCO_DT_END",
              "SCO_DT_START",
              "SCO_ID_TYPE_RESP",
              "SCO_ID_WU_PARENT",
              "SCO_OR_HR_PERIOD",
              "SCO_MANAGER_OBJETIVES",
            ],
            children: [
              {
                field: "Snco_Info_Person",
                node: "SNCO_INFO_PERSON",
                recordSet: "Snco_Info_PersonRecordSet",
                items: [
                  "DT_START",
                  "SCO_ID_HR",
                  "SCO_PHOTO_SERV",
                  "HAS_PRIVATE_DATA",
                  "SCO_OR_HR_PERIOD",
                ],
                children: [],
              },
              {
                field: "Snco_Ad_Wu_By_Manager",
                node: "SNCO_AD_WU_BY_MANAGER",
                recordSet: "Snco_Ad_Wu_By_ManagerRecordSet",
                items: ["SCO_ID_WU", "SCO_ID_WU_PARENT"],
                children: [],
              },
              {
                field: "Snco_Ad_Wu_Objectives",
                node: "SNCO_AD_WU_OBJECTIVES",
                recordSet: "Snco_Ad_Wu_ObjectivesRecordSet",
                items: [
                  "SCO_MEANING",
                  "SCO_PERCENT",
                  "SCO_DT_START",
                  "SCO_ID_LEVEL",
                  "SCO_ID_MAGNITUD",
                  "SCO_ID_OBJECTIVE",
                  "SCO_NM_MAGNITUDE",
                  "SCO_NM_OBJECTIVE",
                ],
                children: [],
              },
              {
                field: "Snco_Ad_Count_Employees",
                node: "SNCO_AD_COUNT_EMPLOYEES",
                recordSet: "Snco_Ad_Count_EmployeesRecordSet",
                items: ["COUNT_EMPLOYEE"],
                children: [],
              },
            ],
          },
          {
            field: "Snco_Ad_Pop_Const",
            node: "SNCO_AD_POP_CONST",
            recordSet: "Snco_Ad_Pop_ConstRecordSet",
            items: ["LANG_WU_WITH_CHILDREN"],
            children: [],
          },
          {
            field: "Snco_Ad_Info_Person",
            node: "SNCO_AD_INFO_PERSON",
            recordSet: "Snco_Ad_Info_PersonRecordSet",
            items: [
              "DT_START",
              "SCO_ID_HR",
              "SCO_PHOTO_SERV",
              "HAS_PRIVATE_DATA",
              "SCO_OR_HR_PERIOD",
            ],
            children: [],
          },
          {
            field: "Snco_Ad_Hierarchic_Wu",
            node: "SNCO_AD_HIERARCHIC_WU",
            recordSet: "Snco_Ad_Hierarchic_WuRecordSet",
            items: [
              "SCO_N_WU",
              "HAS_CHILD",
              "SCO_ID_WU",
              "SCO_DT_END",
              "SCO_DT_START",
              "SCO_LEFT_VALUE",
              "SCO_RIGHT_VALUE",
              "SCO_ID_TYPE_RESP",
              "SCO_ID_WU_PARENT",
            ],
            children: [],
          },
          {
            field: "Snco_Ad_Info_Person_Private",
            node: "SNCO_AD_INFO_PERSON_PRIVATE",
            recordSet: "Snco_Ad_Info_Person_PrivateRecordSet",
            items: ["DT_START", "SCO_ID_HR", "SCO_OR_HR_PERIOD"],
            children: [],
          },
          {
            field: "Snco_Ad_Pop_Max_Scale_Level",
            node: "SNCO_AD_POP_MAX_SCALE_LEVEL",
            recordSet: "Snco_Ad_Pop_Max_Scale_LevelRecordSet",
            items: ["SCO_NUM_LEVEL"],
            children: [],
          },
        ],
      },
    ],
  },
  SNTC_AD_POPULATION: {
    service: "SNTC_AD_POPULATION",
    m4Object: "SNTC_AD_POPULATION",
    deployedInWsdd: true,
    serialization: {
      style: "rpc",
      use: "encoded",
      namespace: "http://schemas.meta4.com/",
      encodingStyle: "http://schemas.xmlsoap.org/soap/encoding/",
    },
    operations: [
      {
        operation: "LOAD_PERSONS",
        methodNode: "SNCO_AD_POPULATION",
        methodName: "LOAD_PERSONS",
        args: [
          {
            name: "AI_ID_HR",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "AI_GB_NAME",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "AI_WORK_UNIT",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "AI_WORK_LOCATION",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "AI_JOB_CODE",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "AI_PHONE",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "AI_FILTER_DATE",
            kind: "date",
            xmlType: "xsd:dateTime",
            nullable: true,
          },
          {
            name: "AI_TYPE_POP",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "AI_ONLY_ONE_EMPLOYEE",
            kind: "string",
            xmlType: "xsd:string",
            nullable: true,
          },
          {
            name: "SNCO_AD_POPULATION",
            kind: "block",
            node: "SNCO_AD_POPULATION",
            xmlType: "m4:Snco_Ad_PopulationBlock",
            nullable: true,
          },
        ],
        blocks: [
          {
            field: "Snco_Ad_Population",
            node: "SNCO_AD_POPULATION",
            recordSet: "Snco_Ad_PopulationRecordSet",
            items: [
              "DT_END",
              "API_SQL",
              "DT_START",
              "API_SQL_R",
              "SCO_UNION",
              "HIERARCHIC",
              "SCO_COMMENT",
              "ISREFERENCED",
              "SCO_IS_FIXED",
              "SCO_IS_PUBLIC",
              "SCO_ID_HR_OWNER",
              "SCO_NATURAL_LANG",
              "HAS_FIELD_PRIVATE",
              "SCO_ID_POPULATION",
              "SCO_NM_POPULATION",
              "SCO_ID_PROCESS_TYPE",
              "SCO_NM_PROCESS_TYPE",
              "SCO_IS_PUBLIC_IN_PORTAL",
            ],
            children: [
              {
                field: "Snco_Ad_Filter",
                node: "SNCO_AD_FILTER",
                recordSet: "Snco_Ad_FilterRecordSet",
                items: ["SCO_VALUE", "SCO_OPERATOR", "SCO_ID_FILTER", "SCO_NM_FILTER"],
                children: [],
              },
              {
                field: "Snco_Ad_Criteria",
                node: "SNCO_AD_CRITERIA",
                recordSet: "Snco_Ad_CriteriaRecordSet",
                items: ["SCO_TYPE", "SCO_HIERARCHY", "SCO_ID_CRITERION"],
                children: [],
              },
              {
                field: "Snco_Info_Person",
                node: "SNCO_INFO_PERSON",
                recordSet: "Snco_Info_PersonRecordSet",
                items: [
                  "DT_START",
                  "SCO_ID_HR",
                  "SCO_PHOTO_SERV",
                  "HAS_PRIVATE_DATA",
                  "SCO_OR_HR_PERIOD",
                ],
                children: [],
              },
              {
                field: "Snco_Info_Person_Private",
                node: "SNCO_INFO_PERSON_PRIVATE",
                recordSet: "Snco_Info_Person_PrivateRecordSet",
                items: ["DT_START", "SCO_ID_HR", "SCO_OR_HR_PERIOD"],
                children: [],
              },
              {
                field: "Snco_Ad_Info_Fixed_Person",
                node: "SNCO_AD_INFO_FIXED_PERSON",
                recordSet: "Snco_Ad_Info_Fixed_PersonRecordSet",
                items: [
                  "DT_END",
                  "DT_START",
                  "SCO_ID_HR",
                  "SCO_COMMENT",
                  "SCO_OR_HR_PERIOD",
                  "SCO_ID_EMPLOYEE_CHANGE_TYPE",
                  "SCO_NM_EMPLOYEE_CHANGE_TYPE",
                ],
                children: [],
              },
              {
                field: "Snco_Ad_Count_Employee_Pop",
                node: "SNCO_AD_COUNT_EMPLOYEE_POP",
                recordSet: "Snco_Ad_Count_Employee_PopRecordSet",
                items: ["ID", "NAME", "EMPTY", "FILTER_MAX", "COUNT_EMPLOYEE"],
                children: [],
              },
            ],
          },
        ],
      },
      {
        operation: "CALC_SENTENCE",
        methodNode: "SNCO_AD_POPULATION",
        methodName: "_CALC_SENTENCE",
        args: [
          {
            name: "AI_DFILTER_DATE",
            kind: "date",
            xmlType: "xsd:dateTime",
            nullable: true,
          },
          {
            name: "AI_BHIERARCHIC",
            kind: "number",
            xmlType: "xsd:double",
            nullable: true,
          },
          {
            name: "AI_BWITH_FILTERS",
            kind: "number",
            xmlType: "xsd:double",
            nullable: true,
          },
          {
            name: "AI_BONLY_FIRST_LEVEL",
            kind: "number",
            xmlType: "xsd:double",
            nullable: true,
          },
          {
            name: "DELETE_FILTER",
            kind: "number",
            xmlType: "xsd:double",
            nullable: true,
          },
          {
            name: "SNCO_AD_POPULATION",
            kind: "block",
            node: "SNCO_AD_POPULATION",
            xmlType: "m4:Snco_Ad_PopulationBlock",
            nullable: true,
          },
        ],
        blocks: [
          {
            field: "Snco_Ad_Population",
            node: "SNCO_AD_POPULATION",
            recordSet: "Snco_Ad_PopulationRecordSet",
            items: [
              "DT_END",
              "API_SQL",
              "DT_START",
              "API_SQL_R",
              "SCO_UNION",
              "HIERARCHIC",
              "SCO_COMMENT",
              "ISREFERENCED",
              "SCO_IS_FIXED",
              "SCO_IS_PUBLIC",
              "SCO_ID_HR_OWNER",
              "SCO_NATURAL_LANG",
              "HAS_FIELD_PRIVATE",
              "SCO_ID_POPULATION",
              "SCO_NM_POPULATION",
              "SCO_ID_PROCESS_TYPE",
              "SCO_NM_PROCESS_TYPE",
              "SCO_IS_PUBLIC_IN_PORTAL",
            ],
            children: [
              {
                field: "Snco_Ad_Filter",
                node: "SNCO_AD_FILTER",
                recordSet: "Snco_Ad_FilterRecordSet",
                items: ["SCO_VALUE", "SCO_OPERATOR", "SCO_ID_FILTER", "SCO_NM_FILTER"],
                children: [],
              },
              {
                field: "Snco_Ad_Criteria",
                node: "SNCO_AD_CRITERIA",
                recordSet: "Snco_Ad_CriteriaRecordSet",
                items: ["SCO_TYPE", "SCO_HIERARCHY", "SCO_ID_CRITERION"],
                children: [],
              },
              {
                field: "Snco_Info_Person",
                node: "SNCO_INFO_PERSON",
                recordSet: "Snco_Info_PersonRecordSet",
                items: [
                  "DT_START",
                  "SCO_ID_HR",
                  "SCO_PHOTO_SERV",
                  "HAS_PRIVATE_DATA",
                  "SCO_OR_HR_PERIOD",
                ],
                children: [],
              },
              {
                field: "Snco_Info_Person_Private",
                node: "SNCO_INFO_PERSON_PRIVATE",
                recordSet: "Snco_Info_Person_PrivateRecordSet",
                items: ["DT_START", "SCO_ID_HR", "SCO_OR_HR_PERIOD"],
                children: [],
              },
              {
                field: "Snco_Ad_Info_Fixed_Person",
                node: "SNCO_AD_INFO_FIXED_PERSON",
                recordSet: "Snco_Ad_Info_Fixed_PersonRecordSet",
                items: [
                  "DT_END",
                  "DT_START",
                  "SCO_ID_HR",
                  "SCO_COMMENT",
                  "SCO_OR_HR_PERIOD",
                  "SCO_ID_EMPLOYEE_CHANGE_TYPE",
                  "SCO_NM_EMPLOYEE_CHANGE_TYPE",
                ],
                children: [],
              },
              {
                field: "Snco_Ad_Count_Employee_Pop",
                node: "SNCO_AD_COUNT_EMPLOYEE_POP",
                recordSet: "Snco_Ad_Count_Employee_PopRecordSet",
                items: ["ID", "NAME", "EMPTY", "FILTER_MAX", "COUNT_EMPLOYEE"],
                children: [],
              },
            ],
          },
        ],
      },
      {
        operation: "M4LoadObject",
        methodNode: "SNCO_AD_POPULATION",
        methodName: "SYS_LOAD_SERVER",
        args: [
          {
            name: "SNCO_AD_H_HR_RESP",
            kind: "block",
            node: "SNCO_AD_H_HR_RESP",
            xmlType: "m4:Snco_Ad_H_Hr_RespBlock",
            nullable: true,
          },
          {
            name: "SNCO_AD_POP_CONST",
            kind: "block",
            node: "SNCO_AD_POP_CONST",
            xmlType: "m4:Snco_Ad_Pop_ConstBlock",
            nullable: true,
          },
          {
            name: "SNCO_AD_POPULATION",
            kind: "block",
            node: "SNCO_AD_POPULATION",
            xmlType: "m4:Snco_Ad_PopulationBlock",
            nullable: true,
          },
          {
            name: "SNCO_AD_PERSON_LIST",
            kind: "block",
            node: "SNCO_AD_PERSON_LIST",
            xmlType: "m4:Snco_Ad_Person_ListBlock",
            nullable: true,
          },
          {
            name: "SNCO_AD_HIERARCHIC_WU",
            kind: "block",
            node: "SNCO_AD_HIERARCHIC_WU",
            xmlType: "m4:Snco_Ad_Hierarchic_WuBlock",
            nullable: true,
          },
          {
            name: "SNCO_AD_CRITERIA_NAMES",
            kind: "block",
            node: "SNCO_AD_CRITERIA_NAMES",
            xmlType: "m4:Snco_Ad_Criteria_NamesBlock",
            nullable: true,
          },
          {
            name: "SNCO_AD_GR_HIERARCHIC_INFO",
            kind: "block",
            node: "SNCO_AD_GR_HIERARCHIC_INFO",
            xmlType: "m4:Snco_Ad_Gr_Hierarchic_InfoBlock",
            nullable: true,
          },
          {
            name: "SNCO_AD_CRITERIA_POPULATION",
            kind: "block",
            node: "SNCO_AD_CRITERIA_POPULATION",
            xmlType: "m4:Snco_Ad_Criteria_PopulationBlock",
            nullable: true,
          },
          {
            name: "SNCO_AD_POP_MAX_SCALE_LEVEL",
            kind: "block",
            node: "SNCO_AD_POP_MAX_SCALE_LEVEL",
            xmlType: "m4:Snco_Ad_Pop_Max_Scale_LevelBlock",
            nullable: true,
          },
        ],
        blocks: [
          {
            field: "Snco_Ad_H_Hr_Resp",
            node: "SNCO_AD_H_HR_RESP",
            recordSet: "Snco_Ad_H_Hr_RespRecordSet",
            items: [
              "SCO_LEFT_VALUE",
              "SCO_RIGHT_VALUE",
              "STD_N_WORK_UNIT",
              "SCO_ID_WU_PARENT",
              "STD_ID_WORK_UNIT",
            ],
            children: [],
          },
          {
            field: "Snco_Ad_Pop_Const",
            node: "SNCO_AD_POP_CONST",
            recordSet: "Snco_Ad_Pop_ConstRecordSet",
            items: ["LANG_WU_WITH_CHILDREN"],
            children: [],
          },
          {
            field: "Snco_Ad_Population",
            node: "SNCO_AD_POPULATION",
            recordSet: "Snco_Ad_PopulationRecordSet",
            items: [
              "DT_END",
              "API_SQL",
              "DT_START",
              "API_SQL_R",
              "SCO_UNION",
              "HIERARCHIC",
              "SCO_COMMENT",
              "ISREFERENCED",
              "SCO_IS_FIXED",
              "SCO_IS_PUBLIC",
              "SCO_ID_HR_OWNER",
              "SCO_NATURAL_LANG",
              "HAS_FIELD_PRIVATE",
              "SCO_ID_POPULATION",
              "SCO_NM_POPULATION",
              "SCO_ID_PROCESS_TYPE",
              "SCO_NM_PROCESS_TYPE",
              "SCO_IS_PUBLIC_IN_PORTAL",
            ],
            children: [
              {
                field: "Snco_Ad_Filter",
                node: "SNCO_AD_FILTER",
                recordSet: "Snco_Ad_FilterRecordSet",
                items: ["SCO_VALUE", "SCO_OPERATOR", "SCO_ID_FILTER", "SCO_NM_FILTER"],
                children: [],
              },
              {
                field: "Snco_Ad_Criteria",
                node: "SNCO_AD_CRITERIA",
                recordSet: "Snco_Ad_CriteriaRecordSet",
                items: ["SCO_TYPE", "SCO_HIERARCHY", "SCO_ID_CRITERION"],
                children: [],
              },
              {
                field: "Snco_Info_Person",
                node: "SNCO_INFO_PERSON",
                recordSet: "Snco_Info_PersonRecordSet",
                items: [
                  "DT_START",
                  "SCO_ID_HR",
                  "SCO_PHOTO_SERV",
                  "HAS_PRIVATE_DATA",
                  "SCO_OR_HR_PERIOD",
                ],
                children: [],
              },
              {
                field: "Snco_Info_Person_Private",
                node: "SNCO_INFO_PERSON_PRIVATE",
                recordSet: "Snco_Info_Person_PrivateRecordSet",
                items: ["DT_START", "SCO_ID_HR", "SCO_OR_HR_PERIOD"],
                children: [],
              },
              {
                field: "Snco_Ad_Info_Fixed_Person",
                node: "SNCO_AD_INFO_FIXED_PERSON",
                recordSet: "Snco_Ad_Info_Fixed_PersonRecordSet",
                items: [
                  "DT_END",
                  "DT_START",
                  "SCO_ID_HR",
                  "SCO_COMMENT",
                  "SCO_OR_HR_PERIOD",
                  "SCO_ID_EMPLOYEE_CHANGE_TYPE",
                  "SCO_NM_EMPLOYEE_CHANGE_TYPE",
                ],
                children: [],
              },
              {
                field: "Snco_Ad_Count_Employee_Pop",
                node: "SNCO_AD_COUNT_EMPLOYEE_POP",
                recordSet: "Snco_Ad_Count_Employee_PopRecordSet",
                items: ["ID", "NAME", "EMPTY", "FILTER_MAX", "COUNT_EMPLOYEE"],
                children: [],
              },
            ],
          },
          {
            field: "Snco_Ad_Person_List",
            node: "SNCO_AD_PERSON_LIST",
            recordSet: "Snco_Ad_Person_ListRecordSet",
            items: ["SCO_ID_HR"],
            children: [],
          },
          {
            field: "Snco_Ad_Hierarchic_Wu",
            node: "SNCO_AD_HIERARCHIC_WU",
            recordSet: "Snco_Ad_Hierarchic_WuRecordSet",
            items: [
              "SCO_N_WU",
              "HAS_CHILD",
              "SCO_ID_WU",
              "SCO_DT_END",
              "SCO_DT_START",
              "SCO_LEFT_VALUE",
              "SCO_RIGHT_VALUE",
              "SCO_ID_TYPE_RESP",
              "SCO_ID_WU_PARENT",
            ],
            children: [],
          },
          {
            field: "Snco_Ad_Criteria_Names",
            node: "SNCO_AD_CRITERIA_NAMES",
            recordSet: "Snco_Ad_Criteria_NamesRecordSet",
            items: ["SCO_TYPE", "SCO_ID_CRITERION", "SCO_NM_CRITERION"],
            children: [],
          },
          {
            field: "Snco_Ad_Gr_Hierarchic_Info",
            node: "SNCO_AD_GR_HIERARCHIC_INFO",
            recordSet: "Snco_Ad_Gr_Hierarchic_InfoRecordSet",
            items: ["HAS_CHILD", "N_WORKUNIT", "ID_WORKUNIT", "HIERARCHIC_SENTENCE"],
            children: [],
          },
          {
            field: "Snco_Ad_Criteria_Population",
            node: "SNCO_AD_CRITERIA_POPULATION",
            recordSet: "Snco_Ad_Criteria_PopulationRecordSet",
            items: ["SCO_ID_CRITERION", "SCO_ID_POPULATION"],
            children: [],
          },
          {
            field: "Snco_Ad_Pop_Max_Scale_Level",
            node: "SNCO_AD_POP_MAX_SCALE_LEVEL",
            recordSet: "Snco_Ad_Pop_Max_Scale_LevelRecordSet",
            items: ["SCO_NUM_LEVEL"],
            children: [],
          },
        ],
      },
    ],
  },
} as const satisfies Record<string, SoapServiceContract>;

export type SoapServiceName = keyof typeof SOAP_CATALOG;
