/**
 * Csp_Acciones_DesarrolloBlock.java
 * Self generated code for Bussines Object CSP_ACCIONES_DESARROLLO.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.csp_acciones_desarrollo;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Csp_Acciones_Desarrollo.
 * @author Meta4
 */
public 
class Csp_Acciones_DesarrolloBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_ACCIONES_DESARROLLO";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_ACCIONES_DESARROLLO";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Acciones_DesarrolloBlock.class.getName());

    /* item CSP_ID_FASE */
    public String csp_Id_Fase = null;
    private void setcsp_Id_Fase(String ai_value)
    {
        csp_Id_Fase = ai_value;
    }
    private String getcsp_Id_Fase()
    {
        return csp_Id_Fase;
    }

    /* the recordset */
    public Csp_Acciones_DesarrolloRecord[] Csp_Acciones_DesarrolloRecordSet = null;
    private void setCsp_Acciones_DesarrolloRecordSet(Csp_Acciones_DesarrolloRecord[] ai_arg)
    {
        Csp_Acciones_DesarrolloRecordSet = ai_arg;
    }
    private Csp_Acciones_DesarrolloRecord[] getCsp_Acciones_DesarrolloRecordSet()
    {
        return Csp_Acciones_DesarrolloRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Csp_Acciones_DesarrolloBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // CSP_ID_FASE.
        if (csp_Id_Fase != null)
        {
            htItems.put("CSP_ID_FASE", M4BusinessMethodArg.toString(csp_Id_Fase));
        }

        // insert 'block scope' values in CSP_ACCIONES_DESARROLLO.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in CSP_ACCIONES_DESARROLLO.
        if (Csp_Acciones_DesarrolloRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Csp_Acciones_DesarrolloRecordSet.length; i++)
        {
            Csp_Acciones_DesarrolloRecord record = Csp_Acciones_DesarrolloRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in CSP_ACCIONES_DESARROLLO.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;

        // read CSP_ID_FASE.
        sItemName = "CSP_ID_FASE";
        nItem = ai_xml.findItem(ai_node, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Fase = sItemValue;

        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Csp_Acciones_DesarrolloRecordSet = new Csp_Acciones_DesarrolloRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Csp_Acciones_DesarrolloRecord record = new Csp_Acciones_DesarrolloRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Csp_Acciones_DesarrolloRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Csp_Acciones_DesarrolloBlock */

