/* =========================================================
	@(#) FileVersion: 818.005.010
	@(#) FileDescription: m4mobile_de.js
	@(#) CompanyName: Meta4 Spain, S.A.
	@(#) LegalCopyright: (c) 2022
	@(#) ProductName: PeopleNet
========================================================= */

// Autogenerated file. Do not touch.

var _document_open_error = "Das Dokument kann nicht angezeigt werden. Vergewissern Sie sich, dass eine Anwendung installiert ist, mit der das Dokument sich anzeigen lässt.";
var _gen_loadingMsg = "Werden geladen...";
var _levelTwoPwdPopupCancel = "Ablehnen";
var _levelTwoPwdPopupLabel = "Zur Ausführung dieser Aktion müssen Sie Ihr Kennwort eingeben";
var _levelTwoPwdPopupMustFillPwd = "Geben Sie das Kennwort ein";
var _levelTwoPwdPopupPwd = "Kennwort";
var _levelTwoPwdPopupPwdReq = "Das Kennwort ist erforderlich";
var _levelTwoPwdPopupPwdWrong = "Das Kennwort ist ungültig";
var _levelTwoPwdPopupSend = "Senden";
var _levelTwoPwdPopupUser = "Benutzer:";
var _m4requestError = "An error occurred when loading the data.";
var _m4untypedError = "An error occurred when accessing the system.";
var _popupCancel = "Ablehnen";
var _popupContinue = "Verbindung trennen";
var _popupLogoutLabel1 = "Verbindung wird getrennt in";
var _popupLogoutLabel2 = "Sekunden...";
var _sessionTimeout = "Die Sitzung ist wegen einer längeren Verbindungsunterbrechung oder Inaktivität abgelaufen.";
