/* =========================================================
	@(#) FileVersion: 818.005.010
	@(#) FileDescription: m4news_it.js
	@(#) CompanyName: Meta4 Spain, S.A.
	@(#) LegalCopyright: (c) 2022
	@(#) ProductName: PeopleNet
========================================================= */

// Autogenerated file. Do not touch.

var _emptyNews = "Non ci sono notizie da mostrare";
var _label_next = "Avanti";
var _label_previous = "Indietro";
var _news_title_toolbar = "Notizie";
