/**
 * Csp_Obj_Colaboradores_De_MiRecord.java
 * Self generated code for Bussines Object CSP_OBJ_COLABORADORES_DE_MI.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_obj_colaboradores_de_mi;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Obj_Colaboradores_De_Mi.
 * @author Meta4
 */
public 
class Csp_Obj_Colaboradores_De_MiRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_OBJ_COLABORADORES_DE_MI";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_OBJ_COLABORADORES_DE_MI";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Obj_Colaboradores_De_MiRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item NOMBRE */
    public String nombre = null;
    private void setnombre(String ai_value)
    {
        nombre = ai_value;
    }
    private String getnombre()
    {
        return nombre;
    }

    /* item ID_AREA */
    public String id_Area = null;
    private void setid_Area(String ai_value)
    {
        id_Area = ai_value;
    }
    private String getid_Area()
    {
        return id_Area;
    }

    /* item EMPLEADO */
    public String empleado = null;
    private void setempleado(String ai_value)
    {
        empleado = ai_value;
    }
    private String getempleado()
    {
        return empleado;
    }

    /* item EVALUADOR */
    public String evaluador = null;
    private void setevaluador(String ai_value)
    {
        evaluador = ai_value;
    }
    private String getevaluador()
    {
        return evaluador;
    }

    /* item ID_UNIDAD */
    public String id_Unidad = null;
    private void setid_Unidad(String ai_value)
    {
        id_Unidad = ai_value;
    }
    private String getid_Unidad()
    {
        return id_Unidad;
    }

    /* item APELLIDO_1 */
    public String apellido_1 = null;
    private void setapellido_1(String ai_value)
    {
        apellido_1 = ai_value;
    }
    private String getapellido_1()
    {
        return apellido_1;
    }

    /* item APELLIDO_2 */
    public String apellido_2 = null;
    private void setapellido_2(String ai_value)
    {
        apellido_2 = ai_value;
    }
    private String getapellido_2()
    {
        return apellido_2;
    }

    /* item ID_PROCESO */
    public String id_Proceso = null;
    private void setid_Proceso(String ai_value)
    {
        id_Proceso = ai_value;
    }
    private String getid_Proceso()
    {
        return id_Proceso;
    }

    /* item ID_SERVICIO */
    public String id_Servicio = null;
    private void setid_Servicio(String ai_value)
    {
        id_Servicio = ai_value;
    }
    private String getid_Servicio()
    {
        return id_Servicio;
    }

    /* item ANNO_PROCESO */
    public String anno_Proceso = null;
    private void setanno_Proceso(String ai_value)
    {
        anno_Proceso = ai_value;
    }
    private String getanno_Proceso()
    {
        return anno_Proceso;
    }

    /* item ORGANIZACION */
    public String organizacion = null;
    private void setorganizacion(String ai_value)
    {
        organizacion = ai_value;
    }
    private String getorganizacion()
    {
        return organizacion;
    }

    /* item FECHA_PROCESO */
    public Calendar fecha_Proceso = null;
    private void setfecha_Proceso(Calendar ai_value)
    {
        fecha_Proceso = ai_value;
    }
    private Calendar getfecha_Proceso()
    {
        return fecha_Proceso;
    }

    /* item TEXTO_PROCESO */
    public String texto_Proceso = null;
    private void settexto_Proceso(String ai_value)
    {
        texto_Proceso = ai_value;
    }
    private String gettexto_Proceso()
    {
        return texto_Proceso;
    }

    /* item FECHA_BUSQUEDA */
    public String fecha_Busqueda = null;
    private void setfecha_Busqueda(String ai_value)
    {
        fecha_Busqueda = ai_value;
    }
    private String getfecha_Busqueda()
    {
        return fecha_Busqueda;
    }

    /* item FECHA_EVAL_ACT */
    public Calendar fecha_Eval_Act = null;
    private void setfecha_Eval_Act(Calendar ai_value)
    {
        fecha_Eval_Act = ai_value;
    }
    private Calendar getfecha_Eval_Act()
    {
        return fecha_Eval_Act;
    }

    /* item FECHA_PLAN_ACT */
    public Calendar fecha_Plan_Act = null;
    private void setfecha_Plan_Act(Calendar ai_value)
    {
        fecha_Plan_Act = ai_value;
    }
    private Calendar getfecha_Plan_Act()
    {
        return fecha_Plan_Act;
    }

    /* item FECHA_PLAN_ANT */
    public Calendar fecha_Plan_Ant = null;
    private void setfecha_Plan_Ant(Calendar ai_value)
    {
        fecha_Plan_Ant = ai_value;
    }
    private Calendar getfecha_Plan_Ant()
    {
        return fecha_Plan_Ant;
    }

    /* item NOMBRE_PROCESO */
    public String nombre_Proceso = null;
    private void setnombre_Proceso(String ai_value)
    {
        nombre_Proceso = ai_value;
    }
    private String getnombre_Proceso()
    {
        return nombre_Proceso;
    }

    /* item ESTADO_EVAL_ACT */
    public String estado_Eval_Act = null;
    private void setestado_Eval_Act(String ai_value)
    {
        estado_Eval_Act = ai_value;
    }
    private String getestado_Eval_Act()
    {
        return estado_Eval_Act;
    }

    /* item ESTADO_PLAN_ACT */
    public String estado_Plan_Act = null;
    private void setestado_Plan_Act(String ai_value)
    {
        estado_Plan_Act = ai_value;
    }
    private String getestado_Plan_Act()
    {
        return estado_Plan_Act;
    }

    /* item ESTADO_PLAN_ANT */
    public String estado_Plan_Ant = null;
    private void setestado_Plan_Ant(String ai_value)
    {
        estado_Plan_Ant = ai_value;
    }
    private String getestado_Plan_Ant()
    {
        return estado_Plan_Ant;
    }

    /* item EVALUADOR_PADRE */
    public String evaluador_Padre = null;
    private void setevaluador_Padre(String ai_value)
    {
        evaluador_Padre = ai_value;
    }
    private String getevaluador_Padre()
    {
        return evaluador_Padre;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // NOMBRE.
        if (nombre != null)
        {
            htItems.put("NOMBRE", M4BusinessMethodArg.toString(nombre));
        }
        // ID_AREA.
        if (id_Area != null)
        {
            htItems.put("ID_AREA", M4BusinessMethodArg.toString(id_Area));
        }
        // EMPLEADO.
        if (empleado != null)
        {
            htItems.put("EMPLEADO", M4BusinessMethodArg.toString(empleado));
        }
        // EVALUADOR.
        if (evaluador != null)
        {
            htItems.put("EVALUADOR", M4BusinessMethodArg.toString(evaluador));
        }
        // ID_UNIDAD.
        if (id_Unidad != null)
        {
            htItems.put("ID_UNIDAD", M4BusinessMethodArg.toString(id_Unidad));
        }
        // APELLIDO_1.
        if (apellido_1 != null)
        {
            htItems.put("APELLIDO_1", M4BusinessMethodArg.toString(apellido_1));
        }
        // APELLIDO_2.
        if (apellido_2 != null)
        {
            htItems.put("APELLIDO_2", M4BusinessMethodArg.toString(apellido_2));
        }
        // ID_PROCESO.
        if (id_Proceso != null)
        {
            htItems.put("ID_PROCESO", M4BusinessMethodArg.toString(id_Proceso));
        }
        // ID_SERVICIO.
        if (id_Servicio != null)
        {
            htItems.put("ID_SERVICIO", M4BusinessMethodArg.toString(id_Servicio));
        }
        // ANNO_PROCESO.
        if (anno_Proceso != null)
        {
            htItems.put("ANNO_PROCESO", M4BusinessMethodArg.toString(anno_Proceso));
        }
        // ORGANIZACION.
        if (organizacion != null)
        {
            htItems.put("ORGANIZACION", M4BusinessMethodArg.toString(organizacion));
        }
        // FECHA_PROCESO.
        if (fecha_Proceso != null)
        {
            htItems.put("FECHA_PROCESO", M4BusinessMethodArg.toString(fecha_Proceso));
        }
        // TEXTO_PROCESO.
        if (texto_Proceso != null)
        {
            htItems.put("TEXTO_PROCESO", M4BusinessMethodArg.toString(texto_Proceso));
        }
        // FECHA_BUSQUEDA.
        if (fecha_Busqueda != null)
        {
            htItems.put("FECHA_BUSQUEDA", M4BusinessMethodArg.toString(fecha_Busqueda));
        }
        // FECHA_EVAL_ACT.
        if (fecha_Eval_Act != null)
        {
            htItems.put("FECHA_EVAL_ACT", M4BusinessMethodArg.toString(fecha_Eval_Act));
        }
        // FECHA_PLAN_ACT.
        if (fecha_Plan_Act != null)
        {
            htItems.put("FECHA_PLAN_ACT", M4BusinessMethodArg.toString(fecha_Plan_Act));
        }
        // FECHA_PLAN_ANT.
        if (fecha_Plan_Ant != null)
        {
            htItems.put("FECHA_PLAN_ANT", M4BusinessMethodArg.toString(fecha_Plan_Ant));
        }
        // NOMBRE_PROCESO.
        if (nombre_Proceso != null)
        {
            htItems.put("NOMBRE_PROCESO", M4BusinessMethodArg.toString(nombre_Proceso));
        }
        // ESTADO_EVAL_ACT.
        if (estado_Eval_Act != null)
        {
            htItems.put("ESTADO_EVAL_ACT", M4BusinessMethodArg.toString(estado_Eval_Act));
        }
        // ESTADO_PLAN_ACT.
        if (estado_Plan_Act != null)
        {
            htItems.put("ESTADO_PLAN_ACT", M4BusinessMethodArg.toString(estado_Plan_Act));
        }
        // ESTADO_PLAN_ANT.
        if (estado_Plan_Ant != null)
        {
            htItems.put("ESTADO_PLAN_ANT", M4BusinessMethodArg.toString(estado_Plan_Ant));
        }
        // EVALUADOR_PADRE.
        if (evaluador_Padre != null)
        {
            htItems.put("EVALUADOR_PADRE", M4BusinessMethodArg.toString(evaluador_Padre));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read NOMBRE.
        sItemName = "NOMBRE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        nombre = sItemValue;

        // read ID_AREA.
        sItemName = "ID_AREA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Area = sItemValue;

        // read EMPLEADO.
        sItemName = "EMPLEADO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        empleado = sItemValue;

        // read EVALUADOR.
        sItemName = "EVALUADOR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        evaluador = sItemValue;

        // read ID_UNIDAD.
        sItemName = "ID_UNIDAD";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Unidad = sItemValue;

        // read APELLIDO_1.
        sItemName = "APELLIDO_1";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        apellido_1 = sItemValue;

        // read APELLIDO_2.
        sItemName = "APELLIDO_2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        apellido_2 = sItemValue;

        // read ID_PROCESO.
        sItemName = "ID_PROCESO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Proceso = sItemValue;

        // read ID_SERVICIO.
        sItemName = "ID_SERVICIO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Servicio = sItemValue;

        // read ANNO_PROCESO.
        sItemName = "ANNO_PROCESO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        anno_Proceso = sItemValue;

        // read ORGANIZACION.
        sItemName = "ORGANIZACION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        organizacion = sItemValue;

        // read FECHA_PROCESO.
        sItemName = "FECHA_PROCESO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        fecha_Proceso = M4BusinessMethodArg.toCalendar(sItemValue);

        // read TEXTO_PROCESO.
        sItemName = "TEXTO_PROCESO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        texto_Proceso = sItemValue;

        // read FECHA_BUSQUEDA.
        sItemName = "FECHA_BUSQUEDA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        fecha_Busqueda = sItemValue;

        // read FECHA_EVAL_ACT.
        sItemName = "FECHA_EVAL_ACT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        fecha_Eval_Act = M4BusinessMethodArg.toCalendar(sItemValue);

        // read FECHA_PLAN_ACT.
        sItemName = "FECHA_PLAN_ACT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        fecha_Plan_Act = M4BusinessMethodArg.toCalendar(sItemValue);

        // read FECHA_PLAN_ANT.
        sItemName = "FECHA_PLAN_ANT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        fecha_Plan_Ant = M4BusinessMethodArg.toCalendar(sItemValue);

        // read NOMBRE_PROCESO.
        sItemName = "NOMBRE_PROCESO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        nombre_Proceso = sItemValue;

        // read ESTADO_EVAL_ACT.
        sItemName = "ESTADO_EVAL_ACT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        estado_Eval_Act = sItemValue;

        // read ESTADO_PLAN_ACT.
        sItemName = "ESTADO_PLAN_ACT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        estado_Plan_Act = sItemValue;

        // read ESTADO_PLAN_ANT.
        sItemName = "ESTADO_PLAN_ANT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        estado_Plan_Ant = sItemValue;

        // read EVALUADOR_PADRE.
        sItemName = "EVALUADOR_PADRE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        evaluador_Padre = sItemValue;


    } /* end of method readOperations */


} /* end of class Csp_Obj_Colaboradores_De_MiRecord */

