/**
 * Csp_Consulta_HijaBlock.java
 * Self generated code for Bussines Object CSP_EMPLEADOS_EVALUADOR.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.csp_empleados_evaluador;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Csp_Consulta_Hija.
 * @author Meta4
 */
public 
class Csp_Consulta_HijaBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_EMPLEADOS_EVALUADOR";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_CONSULTA_HIJA";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Consulta_HijaBlock.class.getName());

    /* item SQL_ARBOL_RECURSIVO */
    public String sql_Arbol_Recursivo = null;
    private void setsql_Arbol_Recursivo(String ai_value)
    {
        sql_Arbol_Recursivo = ai_value;
    }
    private String getsql_Arbol_Recursivo()
    {
        return sql_Arbol_Recursivo;
    }

    /* the recordset */
    public Csp_Consulta_HijaRecord[] Csp_Consulta_HijaRecordSet = null;
    private void setCsp_Consulta_HijaRecordSet(Csp_Consulta_HijaRecord[] ai_arg)
    {
        Csp_Consulta_HijaRecordSet = ai_arg;
    }
    private Csp_Consulta_HijaRecord[] getCsp_Consulta_HijaRecordSet()
    {
        return Csp_Consulta_HijaRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Csp_Consulta_HijaBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // SQL_ARBOL_RECURSIVO.
        if (sql_Arbol_Recursivo != null)
        {
            htItems.put("SQL_ARBOL_RECURSIVO", M4BusinessMethodArg.toString(sql_Arbol_Recursivo));
        }

        // insert 'block scope' values in CSP_CONSULTA_HIJA.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in CSP_CONSULTA_HIJA.
        if (Csp_Consulta_HijaRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Csp_Consulta_HijaRecordSet.length; i++)
        {
            Csp_Consulta_HijaRecord record = Csp_Consulta_HijaRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in CSP_CONSULTA_HIJA.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;

        // read SQL_ARBOL_RECURSIVO.
        sItemName = "SQL_ARBOL_RECURSIVO";
        nItem = ai_xml.findItem(ai_node, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sql_Arbol_Recursivo = sItemValue;

        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Csp_Consulta_HijaRecordSet = new Csp_Consulta_HijaRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Csp_Consulta_HijaRecord record = new Csp_Consulta_HijaRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Csp_Consulta_HijaRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Csp_Consulta_HijaBlock */

