/**
 * Csp_Consulta_UnidadRecord.java
 * Self generated code for Bussines Object CSP_EMPLEADOS_EVALUADOR.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_empleados_evaluador;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Consulta_Unidad.
 * @author Meta4
 */
public 
class Csp_Consulta_UnidadRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_EMPLEADOS_EVALUADOR";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_CONSULTA_UNIDAD";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Consulta_UnidadRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item ID_AREA */
    public String id_Area = null;
    private void setid_Area(String ai_value)
    {
        id_Area = ai_value;
    }
    private String getid_Area()
    {
        return id_Area;
    }

    /* item N_UNIDAD */
    public String n_Unidad = null;
    private void setn_Unidad(String ai_value)
    {
        n_Unidad = ai_value;
    }
    private String getn_Unidad()
    {
        return n_Unidad;
    }

    /* item ID_UNIDAD */
    public String id_Unidad = null;
    private void setid_Unidad(String ai_value)
    {
        id_Unidad = ai_value;
    }
    private String getid_Unidad()
    {
        return id_Unidad;
    }

    /* item ID_DIRECCION */
    public String id_Direccion = null;
    private void setid_Direccion(String ai_value)
    {
        id_Direccion = ai_value;
    }
    private String getid_Direccion()
    {
        return id_Direccion;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // ID_AREA.
        if (id_Area != null)
        {
            htItems.put("ID_AREA", M4BusinessMethodArg.toString(id_Area));
        }
        // N_UNIDAD.
        if (n_Unidad != null)
        {
            htItems.put("N_UNIDAD", M4BusinessMethodArg.toString(n_Unidad));
        }
        // ID_UNIDAD.
        if (id_Unidad != null)
        {
            htItems.put("ID_UNIDAD", M4BusinessMethodArg.toString(id_Unidad));
        }
        // ID_DIRECCION.
        if (id_Direccion != null)
        {
            htItems.put("ID_DIRECCION", M4BusinessMethodArg.toString(id_Direccion));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read ID_AREA.
        sItemName = "ID_AREA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Area = sItemValue;

        // read N_UNIDAD.
        sItemName = "N_UNIDAD";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        n_Unidad = sItemValue;

        // read ID_UNIDAD.
        sItemName = "ID_UNIDAD";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Unidad = sItemValue;

        // read ID_DIRECCION.
        sItemName = "ID_DIRECCION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Direccion = sItemValue;


    } /* end of method readOperations */


} /* end of class Csp_Consulta_UnidadRecord */

