#[=====================================================]
# @(#) FileVersion: 815.002.001
# @(#) FileDescription: Headers to be set on choosing no-store.
# @(#) CompanyName: Meta4 Spain, S.A.
# @(#) LegalCopyright: (c) 2018
# @(#) ProductName: PeopleNet
#[=====================================================]
#
# This setting defines for each servlet or filter the Cache-Control header is set
# --------------------------------
# Example: m4fileservletutils: no-store, no-cache, must-revalidate, pre-check=0, post-check=0, max-age=0, s-maxage=0
# The default is: no-store, no-cache 
#
m4fileservletutils=no-store, no-cache