#[=====================================================]
#
#	@(#)FileVersion: 811.000.009
#	@(#)FileDescription: CSRF Validator Configuration
#	@(#)CompanyName: Meta4 Spain, S.A.
#	@(#)LegalCopyright: (c)2014
#	@(#)ProductName: PeopleNet KSystem
#	@(#)ProductVersion: 8.1SP1
#	@(#)InternalName: m4csrfvalidator.properties
#	@(#)Date: 14/03/2014
#
#[=====================================================] --%>
#
# Activation of the csrf validator
# --------------------------------
m4csrfvalidator.active=false

# Behavior of the validator 
# (dologoutonerror=true needed for SSO)
# -------------------------------------
m4csrfvalidator.dologoutonerror=true

#
# Definition of unprotected resources. It is not mandatory to define the first portal page.
# 
# Example:
# 
# m4csrfvalidator.unprotected.tec.0=/servlet/CheckSecurity/JSP/tctask/tcpage.jsp

m4csrfvalidator.unprotected.tec.0=/mobile/index.jsp
m4csrfvalidator.unprotected.tec.1=/servlet/CheckSecurity/JSP/mobile/index.jsp
m4csrfvalidator.unprotected.tec.2=/servlet/CheckSecurity/JSP/shco_g0/shco_gen_logout.jsp
# 
m4csrfvalidator.unprotected.ess.0=/servlet/CheckSecurity/JSP/sse_generico/sgco_menu_back.jsp
m4csrfvalidator.unprotected.ess.1=/servlet/CheckSecurity/JSP/sse_generico/generico_invisible.jsp
m4csrfvalidator.unprotected.ess.2=/servlet/CheckSecurity/JSP/sse_generico/ssco_portal.jsp
m4csrfvalidator.unprotected.ess.3=/servlet/CheckSecurity/JSP/sse_generico/sse_logout.jsp

