/* =======================================================
@(#) FileVersion: 815.002.001
@(#) FileDescription: Properties for M4FileServlet.
@(#) CompanyName: Meta4 Spain, S.A.
@(#) LegalCopyright: (c) 2018
@(#) ProductName: PeopleNet
======================================================= */

/* -- File Service parameters -- */

/* -- Connection Pool parameters -- */

/* Number of Connections: 
	The maximum number of simultaneous connections to the application server. This defines the parallelism level when processing files. */
fileservice.connectionpool.NMaxConnections=10

/* Connection User ID: 
	The user id for the server connection. */
fileservice.connectionpool.UserId=M4ADM

/* Private Key file: 
	The file contains the encrypted password for the key repository file. */
fileservice.connectionpool.PrivateFile=pass.key

/* Key Repository File: 
	The file contains the private key used to generate certificates. */
fileservice.connectionpool.PrivatePassFile=private.key

/* Server Name: 
	The name or ip of the application server or dispatcher to connect to. */
fileservice.connectionpool.Server=localhost

/* Server Port: 
	The port of the application server or dispatcher to connect to. */
fileservice.connectionpool.ServerPort=3002

/* SSL Mode: 
	If True enables SSL transport. */
fileservice.connectionpool.UseSSL=False

/* Connection Language: 
	Indicates the language to connect to the application server or dispatcher. */
fileservice.connectionpool.Language=2

/* -- Security parameters -- */

/* Enabled: 
	Indicates that the access to file resources are securized. To access a resource we need a special token parameter from Rich or a valid session in portal. */
fileservice.security.Enabled=true

/* SessionVerifierCookieName: 
	Indicates the cookie name for the remote session verifier access */
fileservice.security.SessionVerifierCookieName=m4svctx

/* SessionCacheTimeout: 
	Indicates the timeout in ms of the cookie expiration. While not expired no session validation per user will be requested*/
fileservice.security.SessionCacheTimeout=15000

/* -- Servlet parameters -- */

/* Client Cache Expiration (seconds): 
	Defines the EXPIRES header value to define how many seconds the file will be cached at client side.  */
fileservice.servlet.ClientExpires=86400

/* -- Cache parameters -- */

/* Max Memory Usage (Megabytes): 
	Defines the maximum amount of memory for the cache. Oldest elements will be dropped after that limit. */
fileservice.cache.MaxMemoryUsage=100

/* Cache Entry Data Expire (seconds): 
	How long the internal cache will keep the information before ask the server to validate it again. */
fileservice.cache.DataExpire=3600

/* Cache Entry Max Number Entries: 
	The maximum number of entries in the cache. */
fileservice.cache.MaxNEntries=100000

/* Cache Elevation Role Id: 
	The role id used to load the data. This will be applied at m4object level. */
fileservice.cache.ElevationRole=M4ADM

/* -- General Parameters -- */

/* The temp directory: 
	The directory where temporary file are downloaded to. */
fileservice.general.TempDir=default

