/**
 * Cyc_Filt_OroRecord.java
 * Self generated code for Bussines Object CYC_FILTRO_FASE_I.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_filtro_fase_i;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Filt_Oro.
 * @author Meta4
 */
public 
class Cyc_Filt_OroRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_FILTRO_FASE_I";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_FILT_ORO";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Filt_OroRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item N_AREA */
    public String n_Area = null;
    private void setn_Area(String ai_value)
    {
        n_Area = ai_value;
    }
    private String getn_Area()
    {
        return n_Area;
    }

    /* item CYC_FASE */
    public String cyc_Fase = null;
    private void setcyc_Fase(String ai_value)
    {
        cyc_Fase = ai_value;
    }
    private String getcyc_Fase()
    {
        return cyc_Fase;
    }

    /* item N_UNIDAD */
    public String n_Unidad = null;
    private void setn_Unidad(String ai_value)
    {
        n_Unidad = ai_value;
    }
    private String getn_Unidad()
    {
        return n_Unidad;
    }

    /* item CLAVE_SELF */
    public String clave_Self = null;
    private void setclave_Self(String ai_value)
    {
        clave_Self = ai_value;
    }
    private String getclave_Self()
    {
        return clave_Self;
    }

    /* item CYC_APENOM */
    public String cyc_Apenom = null;
    private void setcyc_Apenom(String ai_value)
    {
        cyc_Apenom = ai_value;
    }
    private String getcyc_Apenom()
    {
        return cyc_Apenom;
    }

    /* item N_SERVICIO */
    public String n_Servicio = null;
    private void setn_Servicio(String ai_value)
    {
        n_Servicio = ai_value;
    }
    private String getn_Servicio()
    {
        return n_Servicio;
    }

    /* item ID_EMPLEADO */
    public String id_Empleado = null;
    private void setid_Empleado(String ai_value)
    {
        id_Empleado = ai_value;
    }
    private String getid_Empleado()
    {
        return id_Empleado;
    }

    /* item N_DIRECCION */
    public String n_Direccion = null;
    private void setn_Direccion(String ai_value)
    {
        n_Direccion = ai_value;
    }
    private String getn_Direccion()
    {
        return n_Direccion;
    }

    /* item P_COLECTIVO */
    public String p_Colectivo = null;
    private void setp_Colectivo(String ai_value)
    {
        p_Colectivo = ai_value;
    }
    private String getp_Colectivo()
    {
        return p_Colectivo;
    }

    /* item P_GRUPONIVEL */
    public String p_Gruponivel = null;
    private void setp_Gruponivel(String ai_value)
    {
        p_Gruponivel = ai_value;
    }
    private String getp_Gruponivel()
    {
        return p_Gruponivel;
    }

    /* item N_TIPO_PUESTO */
    public String n_Tipo_Puesto = null;
    private void setn_Tipo_Puesto(String ai_value)
    {
        n_Tipo_Puesto = ai_value;
    }
    private String getn_Tipo_Puesto()
    {
        return n_Tipo_Puesto;
    }

    /* item FEC_ANTIGUEDAD */
    public Calendar fec_Antiguedad = null;
    private void setfec_Antiguedad(Calendar ai_value)
    {
        fec_Antiguedad = ai_value;
    }
    private Calendar getfec_Antiguedad()
    {
        return fec_Antiguedad;
    }

    /* item FEC_NACIMIENTO */
    public Calendar fec_Nacimiento = null;
    private void setfec_Nacimiento(Calendar ai_value)
    {
        fec_Nacimiento = ai_value;
    }
    private Calendar getfec_Nacimiento()
    {
        return fec_Nacimiento;
    }

    /* item ID_ORGANIZATION */
    public String id_Organization = null;
    private void setid_Organization(String ai_value)
    {
        id_Organization = ai_value;
    }
    private String getid_Organization()
    {
        return id_Organization;
    }

    /* item N_CENT_TRAB_FIS */
    public String n_Cent_Trab_Fis = null;
    private void setn_Cent_Trab_Fis(String ai_value)
    {
        n_Cent_Trab_Fis = ai_value;
    }
    private String getn_Cent_Trab_Fis()
    {
        return n_Cent_Trab_Fis;
    }

    /* item N_CENTRO_TRABAJO */
    public String n_Centro_Trabajo = null;
    private void setn_Centro_Trabajo(String ai_value)
    {
        n_Centro_Trabajo = ai_value;
    }
    private String getn_Centro_Trabajo()
    {
        return n_Centro_Trabajo;
    }

    /* item P_ULT_ACTUALIZACION */
    public Calendar p_Ult_Actualizacion = null;
    private void setp_Ult_Actualizacion(Calendar ai_value)
    {
        p_Ult_Actualizacion = ai_value;
    }
    private Calendar getp_Ult_Actualizacion()
    {
        return p_Ult_Actualizacion;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // N_AREA.
        if (n_Area != null)
        {
            htItems.put("N_AREA", M4BusinessMethodArg.toString(n_Area));
        }
        // CYC_FASE.
        if (cyc_Fase != null)
        {
            htItems.put("CYC_FASE", M4BusinessMethodArg.toString(cyc_Fase));
        }
        // N_UNIDAD.
        if (n_Unidad != null)
        {
            htItems.put("N_UNIDAD", M4BusinessMethodArg.toString(n_Unidad));
        }
        // CLAVE_SELF.
        if (clave_Self != null)
        {
            htItems.put("CLAVE_SELF", M4BusinessMethodArg.toString(clave_Self));
        }
        // CYC_APENOM.
        if (cyc_Apenom != null)
        {
            htItems.put("CYC_APENOM", M4BusinessMethodArg.toString(cyc_Apenom));
        }
        // N_SERVICIO.
        if (n_Servicio != null)
        {
            htItems.put("N_SERVICIO", M4BusinessMethodArg.toString(n_Servicio));
        }
        // ID_EMPLEADO.
        if (id_Empleado != null)
        {
            htItems.put("ID_EMPLEADO", M4BusinessMethodArg.toString(id_Empleado));
        }
        // N_DIRECCION.
        if (n_Direccion != null)
        {
            htItems.put("N_DIRECCION", M4BusinessMethodArg.toString(n_Direccion));
        }
        // P_COLECTIVO.
        if (p_Colectivo != null)
        {
            htItems.put("P_COLECTIVO", M4BusinessMethodArg.toString(p_Colectivo));
        }
        // P_GRUPONIVEL.
        if (p_Gruponivel != null)
        {
            htItems.put("P_GRUPONIVEL", M4BusinessMethodArg.toString(p_Gruponivel));
        }
        // N_TIPO_PUESTO.
        if (n_Tipo_Puesto != null)
        {
            htItems.put("N_TIPO_PUESTO", M4BusinessMethodArg.toString(n_Tipo_Puesto));
        }
        // FEC_ANTIGUEDAD.
        if (fec_Antiguedad != null)
        {
            htItems.put("FEC_ANTIGUEDAD", M4BusinessMethodArg.toString(fec_Antiguedad));
        }
        // FEC_NACIMIENTO.
        if (fec_Nacimiento != null)
        {
            htItems.put("FEC_NACIMIENTO", M4BusinessMethodArg.toString(fec_Nacimiento));
        }
        // ID_ORGANIZATION.
        if (id_Organization != null)
        {
            htItems.put("ID_ORGANIZATION", M4BusinessMethodArg.toString(id_Organization));
        }
        // N_CENT_TRAB_FIS.
        if (n_Cent_Trab_Fis != null)
        {
            htItems.put("N_CENT_TRAB_FIS", M4BusinessMethodArg.toString(n_Cent_Trab_Fis));
        }
        // N_CENTRO_TRABAJO.
        if (n_Centro_Trabajo != null)
        {
            htItems.put("N_CENTRO_TRABAJO", M4BusinessMethodArg.toString(n_Centro_Trabajo));
        }
        // P_ULT_ACTUALIZACION.
        if (p_Ult_Actualizacion != null)
        {
            htItems.put("P_ULT_ACTUALIZACION", M4BusinessMethodArg.toString(p_Ult_Actualizacion));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read N_AREA.
        sItemName = "N_AREA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        n_Area = sItemValue;

        // read CYC_FASE.
        sItemName = "CYC_FASE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Fase = sItemValue;

        // read N_UNIDAD.
        sItemName = "N_UNIDAD";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        n_Unidad = sItemValue;

        // read CLAVE_SELF.
        sItemName = "CLAVE_SELF";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        clave_Self = sItemValue;

        // read CYC_APENOM.
        sItemName = "CYC_APENOM";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Apenom = sItemValue;

        // read N_SERVICIO.
        sItemName = "N_SERVICIO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        n_Servicio = sItemValue;

        // read ID_EMPLEADO.
        sItemName = "ID_EMPLEADO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Empleado = sItemValue;

        // read N_DIRECCION.
        sItemName = "N_DIRECCION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        n_Direccion = sItemValue;

        // read P_COLECTIVO.
        sItemName = "P_COLECTIVO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Colectivo = sItemValue;

        // read P_GRUPONIVEL.
        sItemName = "P_GRUPONIVEL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Gruponivel = sItemValue;

        // read N_TIPO_PUESTO.
        sItemName = "N_TIPO_PUESTO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        n_Tipo_Puesto = sItemValue;

        // read FEC_ANTIGUEDAD.
        sItemName = "FEC_ANTIGUEDAD";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        fec_Antiguedad = M4BusinessMethodArg.toCalendar(sItemValue);

        // read FEC_NACIMIENTO.
        sItemName = "FEC_NACIMIENTO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        fec_Nacimiento = M4BusinessMethodArg.toCalendar(sItemValue);

        // read ID_ORGANIZATION.
        sItemName = "ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Organization = sItemValue;

        // read N_CENT_TRAB_FIS.
        sItemName = "N_CENT_TRAB_FIS";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        n_Cent_Trab_Fis = sItemValue;

        // read N_CENTRO_TRABAJO.
        sItemName = "N_CENTRO_TRABAJO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        n_Centro_Trabajo = sItemValue;

        // read P_ULT_ACTUALIZACION.
        sItemName = "P_ULT_ACTUALIZACION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Ult_Actualizacion = M4BusinessMethodArg.toCalendar(sItemValue);


    } /* end of method readOperations */


} /* end of class Cyc_Filt_OroRecord */

