/**
 * Cyc_Filtro_F_IBlock.java
 * Self generated code for Bussines Object CYC_FILTRO_FASE_I.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.cyc_filtro_fase_i;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Cyc_Filtro_F_I.
 * @author Meta4
 */
public 
class Cyc_Filtro_F_IBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_FILTRO_FASE_I";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_FILTRO_F_I";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Filtro_F_IBlock.class.getName());

    /* the recordset */
    public Cyc_Filtro_F_IRecord[] Cyc_Filtro_F_IRecordSet = null;
    private void setCyc_Filtro_F_IRecordSet(Cyc_Filtro_F_IRecord[] ai_arg)
    {
        Cyc_Filtro_F_IRecordSet = ai_arg;
    }
    private Cyc_Filtro_F_IRecord[] getCyc_Filtro_F_IRecordSet()
    {
        return Cyc_Filtro_F_IRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Cyc_Filtro_F_IBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();

        // insert 'block scope' values in CYC_FILTRO_F_I.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in CYC_FILTRO_F_I.
        if (Cyc_Filtro_F_IRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Cyc_Filtro_F_IRecordSet.length; i++)
        {
            Cyc_Filtro_F_IRecord record = Cyc_Filtro_F_IRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in CYC_FILTRO_F_I.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;


        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Cyc_Filtro_F_IRecordSet = new Cyc_Filtro_F_IRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Cyc_Filtro_F_IRecord record = new Cyc_Filtro_F_IRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Cyc_Filtro_F_IRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Cyc_Filtro_F_IBlock */

