/**
 * Csp_Obtener_FeedbackRecord.java
 * Self generated code for Bussines Object CSP_OBTENER_FEEDBACK.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_obtener_feedback;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Obtener_Feedback.
 * @author Meta4
 */
public 
class Csp_Obtener_FeedbackRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_OBTENER_FEEDBACK";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_OBTENER_FEEDBACK";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Obtener_FeedbackRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item DT_END */
    public Calendar dt_End = null;
    private void setdt_End(Calendar ai_value)
    {
        dt_End = ai_value;
    }
    private Calendar getdt_End()
    {
        return dt_End;
    }

    /* item DT_START */
    public Calendar dt_Start = null;
    private void setdt_Start(Calendar ai_value)
    {
        dt_Start = ai_value;
    }
    private Calendar getdt_Start()
    {
        return dt_Start;
    }

    /* item CYC_ID_HR */
    public String cyc_Id_Hr = null;
    private void setcyc_Id_Hr(String ai_value)
    {
        cyc_Id_Hr = ai_value;
    }
    private String getcyc_Id_Hr()
    {
        return cyc_Id_Hr;
    }

    /* item CYC_COMENT */
    public String cyc_Coment = null;
    private void setcyc_Coment(String ai_value)
    {
        cyc_Coment = ai_value;
    }
    private String getcyc_Coment()
    {
        return cyc_Coment;
    }

    /* item CYC_ESTADO */
    public String cyc_Estado = null;
    private void setcyc_Estado(String ai_value)
    {
        cyc_Estado = ai_value;
    }
    private String getcyc_Estado()
    {
        return cyc_Estado;
    }

    /* item CHECK_TOEIC */
    public String check_Toeic = null;
    private void setcheck_Toeic(String ai_value)
    {
        check_Toeic = ai_value;
    }
    private String getcheck_Toeic()
    {
        return check_Toeic;
    }

    /* item CYC_ID_FASE */
    public String cyc_Id_Fase = null;
    private void setcyc_Id_Fase(String ai_value)
    {
        cyc_Id_Fase = ai_value;
    }
    private String getcyc_Id_Fase()
    {
        return cyc_Id_Fase;
    }

    /* item CHECK_COMPROMISO */
    public String check_Compromiso = null;
    private void setcheck_Compromiso(String ai_value)
    {
        check_Compromiso = ai_value;
    }
    private String getcheck_Compromiso()
    {
        return check_Compromiso;
    }

    /* item CYC_ID_OBSERVACION */
    public String cyc_Id_Observacion = null;
    private void setcyc_Id_Observacion(String ai_value)
    {
        cyc_Id_Observacion = ai_value;
    }
    private String getcyc_Id_Observacion()
    {
        return cyc_Id_Observacion;
    }

    /* item CYC_FEC_REALIZACION */
    public Calendar cyc_Fec_Realizacion = null;
    private void setcyc_Fec_Realizacion(Calendar ai_value)
    {
        cyc_Fec_Realizacion = ai_value;
    }
    private Calendar getcyc_Fec_Realizacion()
    {
        return cyc_Fec_Realizacion;
    }

    /* item CYC_COMENTARIOS_RRHH */
    public String cyc_Comentarios_Rrhh = null;
    private void setcyc_Comentarios_Rrhh(String ai_value)
    {
        cyc_Comentarios_Rrhh = ai_value;
    }
    private String getcyc_Comentarios_Rrhh()
    {
        return cyc_Comentarios_Rrhh;
    }

    /* item CYC_FEC_ENTREV_FEEDBK */
    public Calendar cyc_Fec_Entrev_Feedbk = null;
    private void setcyc_Fec_Entrev_Feedbk(Calendar ai_value)
    {
        cyc_Fec_Entrev_Feedbk = ai_value;
    }
    private Calendar getcyc_Fec_Entrev_Feedbk()
    {
        return cyc_Fec_Entrev_Feedbk;
    }

    /* item CYC_OBSERVACIONES_RRHH */
    public String cyc_Observaciones_Rrhh = null;
    private void setcyc_Observaciones_Rrhh(String ai_value)
    {
        cyc_Observaciones_Rrhh = ai_value;
    }
    private String getcyc_Observaciones_Rrhh()
    {
        return cyc_Observaciones_Rrhh;
    }

    /* item CYC_PERFIL_PROFESIONAL */
    public String cyc_Perfil_Profesional = null;
    private void setcyc_Perfil_Profesional(String ai_value)
    {
        cyc_Perfil_Profesional = ai_value;
    }
    private String getcyc_Perfil_Profesional()
    {
        return cyc_Perfil_Profesional;
    }

    /* item CYC_COMENTARIOS_EMPLEADO */
    public String cyc_Comentarios_Empleado = null;
    private void setcyc_Comentarios_Empleado(String ai_value)
    {
        cyc_Comentarios_Empleado = ai_value;
    }
    private String getcyc_Comentarios_Empleado()
    {
        return cyc_Comentarios_Empleado;
    }

    /* item CYC_RECOMENDACIONES_RRHH */
    public String cyc_Recomendaciones_Rrhh = null;
    private void setcyc_Recomendaciones_Rrhh(String ai_value)
    {
        cyc_Recomendaciones_Rrhh = ai_value;
    }
    private String getcyc_Recomendaciones_Rrhh()
    {
        return cyc_Recomendaciones_Rrhh;
    }

    /* item CYC_FEC_ACEPTACION_FEEDBK */
    public Calendar cyc_Fec_Aceptacion_Feedbk = null;
    private void setcyc_Fec_Aceptacion_Feedbk(Calendar ai_value)
    {
        cyc_Fec_Aceptacion_Feedbk = ai_value;
    }
    private Calendar getcyc_Fec_Aceptacion_Feedbk()
    {
        return cyc_Fec_Aceptacion_Feedbk;
    }

    /* node CSP_NOTAS_OBT */
    public Csp_Notas_ObtBlock Csp_Notas_Obt = null;
    private void setcsp_Notas_Obt(Csp_Notas_ObtBlock ai_value)
    {
        Csp_Notas_Obt = ai_value;
    }
    private Csp_Notas_ObtBlock getCsp_Notas_Obt()
    {
        return Csp_Notas_Obt;
    }

    /* node CSP_LISTA_NOTAS */
    public Csp_Lista_NotasBlock Csp_Lista_Notas = null;
    private void setcsp_Lista_Notas(Csp_Lista_NotasBlock ai_value)
    {
        Csp_Lista_Notas = ai_value;
    }
    private Csp_Lista_NotasBlock getCsp_Lista_Notas()
    {
        return Csp_Lista_Notas;
    }

    /* node CSP_LISTA_NOTAS_FASE1 */
    public Csp_Lista_Notas_Fase1Block Csp_Lista_Notas_Fase1 = null;
    private void setcsp_Lista_Notas_Fase1(Csp_Lista_Notas_Fase1Block ai_value)
    {
        Csp_Lista_Notas_Fase1 = ai_value;
    }
    private Csp_Lista_Notas_Fase1Block getCsp_Lista_Notas_Fase1()
    {
        return Csp_Lista_Notas_Fase1;
    }

    /* node CSP_LISTA_NOTAS_FASE2 */
    public Csp_Lista_Notas_Fase2Block Csp_Lista_Notas_Fase2 = null;
    private void setcsp_Lista_Notas_Fase2(Csp_Lista_Notas_Fase2Block ai_value)
    {
        Csp_Lista_Notas_Fase2 = ai_value;
    }
    private Csp_Lista_Notas_Fase2Block getCsp_Lista_Notas_Fase2()
    {
        return Csp_Lista_Notas_Fase2;
    }

    /* node CSP_LISTA_NOTAS_FASE3 */
    public Csp_Lista_Notas_Fase3Block Csp_Lista_Notas_Fase3 = null;
    private void setcsp_Lista_Notas_Fase3(Csp_Lista_Notas_Fase3Block ai_value)
    {
        Csp_Lista_Notas_Fase3 = ai_value;
    }
    private Csp_Lista_Notas_Fase3Block getCsp_Lista_Notas_Fase3()
    {
        return Csp_Lista_Notas_Fase3;
    }

    /* node CSP_H_PUNTOS_FUER_FASE */
    public Csp_H_Puntos_Fuer_FaseBlock Csp_H_Puntos_Fuer_Fase = null;
    private void setcsp_H_Puntos_Fuer_Fase(Csp_H_Puntos_Fuer_FaseBlock ai_value)
    {
        Csp_H_Puntos_Fuer_Fase = ai_value;
    }
    private Csp_H_Puntos_Fuer_FaseBlock getCsp_H_Puntos_Fuer_Fase()
    {
        return Csp_H_Puntos_Fuer_Fase;
    }

    /* node CSP_H_PUNTOS_MEJOR_FASE */
    public Csp_H_Puntos_Mejor_FaseBlock Csp_H_Puntos_Mejor_Fase = null;
    private void setcsp_H_Puntos_Mejor_Fase(Csp_H_Puntos_Mejor_FaseBlock ai_value)
    {
        Csp_H_Puntos_Mejor_Fase = ai_value;
    }
    private Csp_H_Puntos_Mejor_FaseBlock getCsp_H_Puntos_Mejor_Fase()
    {
        return Csp_H_Puntos_Mejor_Fase;
    }

    /* node CSP_ACCIONES_DESA_FEEDBK */
    public Csp_Acciones_Desa_FeedbkBlock Csp_Acciones_Desa_Feedbk = null;
    private void setcsp_Acciones_Desa_Feedbk(Csp_Acciones_Desa_FeedbkBlock ai_value)
    {
        Csp_Acciones_Desa_Feedbk = ai_value;
    }
    private Csp_Acciones_Desa_FeedbkBlock getCsp_Acciones_Desa_Feedbk()
    {
        return Csp_Acciones_Desa_Feedbk;
    }

    /* node CSP_ACCIONES_FORM_FEEDBK */
    public Csp_Acciones_Form_FeedbkBlock Csp_Acciones_Form_Feedbk = null;
    private void setcsp_Acciones_Form_Feedbk(Csp_Acciones_Form_FeedbkBlock ai_value)
    {
        Csp_Acciones_Form_Feedbk = ai_value;
    }
    private Csp_Acciones_Form_FeedbkBlock getCsp_Acciones_Form_Feedbk()
    {
        return Csp_Acciones_Form_Feedbk;
    }

    /* node CSP_ACCIONES_PROP_FEEDBK */
    public Csp_Acciones_Prop_FeedbkBlock Csp_Acciones_Prop_Feedbk = null;
    private void setcsp_Acciones_Prop_Feedbk(Csp_Acciones_Prop_FeedbkBlock ai_value)
    {
        Csp_Acciones_Prop_Feedbk = ai_value;
    }
    private Csp_Acciones_Prop_FeedbkBlock getCsp_Acciones_Prop_Feedbk()
    {
        return Csp_Acciones_Prop_Feedbk;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // DT_END.
        if (dt_End != null)
        {
            htItems.put("DT_END", M4BusinessMethodArg.toString(dt_End));
        }
        // DT_START.
        if (dt_Start != null)
        {
            htItems.put("DT_START", M4BusinessMethodArg.toString(dt_Start));
        }
        // CYC_ID_HR.
        if (cyc_Id_Hr != null)
        {
            htItems.put("CYC_ID_HR", M4BusinessMethodArg.toString(cyc_Id_Hr));
        }
        // CYC_COMENT.
        if (cyc_Coment != null)
        {
            htItems.put("CYC_COMENT", M4BusinessMethodArg.toString(cyc_Coment));
        }
        // CYC_ESTADO.
        if (cyc_Estado != null)
        {
            htItems.put("CYC_ESTADO", M4BusinessMethodArg.toString(cyc_Estado));
        }
        // CHECK_TOEIC.
        if (check_Toeic != null)
        {
            htItems.put("CHECK_TOEIC", M4BusinessMethodArg.toString(check_Toeic));
        }
        // CYC_ID_FASE.
        if (cyc_Id_Fase != null)
        {
            htItems.put("CYC_ID_FASE", M4BusinessMethodArg.toString(cyc_Id_Fase));
        }
        // CHECK_COMPROMISO.
        if (check_Compromiso != null)
        {
            htItems.put("CHECK_COMPROMISO", M4BusinessMethodArg.toString(check_Compromiso));
        }
        // CYC_ID_OBSERVACION.
        if (cyc_Id_Observacion != null)
        {
            htItems.put("CYC_ID_OBSERVACION", M4BusinessMethodArg.toString(cyc_Id_Observacion));
        }
        // CYC_FEC_REALIZACION.
        if (cyc_Fec_Realizacion != null)
        {
            htItems.put("CYC_FEC_REALIZACION", M4BusinessMethodArg.toString(cyc_Fec_Realizacion));
        }
        // CYC_COMENTARIOS_RRHH.
        if (cyc_Comentarios_Rrhh != null)
        {
            htItems.put("CYC_COMENTARIOS_RRHH", M4BusinessMethodArg.toString(cyc_Comentarios_Rrhh));
        }
        // CYC_FEC_ENTREV_FEEDBK.
        if (cyc_Fec_Entrev_Feedbk != null)
        {
            htItems.put("CYC_FEC_ENTREV_FEEDBK", M4BusinessMethodArg.toString(cyc_Fec_Entrev_Feedbk));
        }
        // CYC_OBSERVACIONES_RRHH.
        if (cyc_Observaciones_Rrhh != null)
        {
            htItems.put("CYC_OBSERVACIONES_RRHH", M4BusinessMethodArg.toString(cyc_Observaciones_Rrhh));
        }
        // CYC_PERFIL_PROFESIONAL.
        if (cyc_Perfil_Profesional != null)
        {
            htItems.put("CYC_PERFIL_PROFESIONAL", M4BusinessMethodArg.toString(cyc_Perfil_Profesional));
        }
        // CYC_COMENTARIOS_EMPLEADO.
        if (cyc_Comentarios_Empleado != null)
        {
            htItems.put("CYC_COMENTARIOS_EMPLEADO", M4BusinessMethodArg.toString(cyc_Comentarios_Empleado));
        }
        // CYC_RECOMENDACIONES_RRHH.
        if (cyc_Recomendaciones_Rrhh != null)
        {
            htItems.put("CYC_RECOMENDACIONES_RRHH", M4BusinessMethodArg.toString(cyc_Recomendaciones_Rrhh));
        }
        // CYC_FEC_ACEPTACION_FEEDBK.
        if (cyc_Fec_Aceptacion_Feedbk != null)
        {
            htItems.put("CYC_FEC_ACEPTACION_FEEDBK", M4BusinessMethodArg.toString(cyc_Fec_Aceptacion_Feedbk));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

        // write data for node CSP_NOTAS_OBT.
        if ( Csp_Notas_Obt != null) 
        {
           Csp_Notas_Obt.writeOperations(ai_m4Op);
        }

        // write data for node CSP_LISTA_NOTAS.
        if ( Csp_Lista_Notas != null) 
        {
           Csp_Lista_Notas.writeOperations(ai_m4Op);
        }

        // write data for node CSP_LISTA_NOTAS_FASE1.
        if ( Csp_Lista_Notas_Fase1 != null) 
        {
           Csp_Lista_Notas_Fase1.writeOperations(ai_m4Op);
        }

        // write data for node CSP_LISTA_NOTAS_FASE2.
        if ( Csp_Lista_Notas_Fase2 != null) 
        {
           Csp_Lista_Notas_Fase2.writeOperations(ai_m4Op);
        }

        // write data for node CSP_LISTA_NOTAS_FASE3.
        if ( Csp_Lista_Notas_Fase3 != null) 
        {
           Csp_Lista_Notas_Fase3.writeOperations(ai_m4Op);
        }

        // write data for node CSP_H_PUNTOS_FUER_FASE.
        if ( Csp_H_Puntos_Fuer_Fase != null) 
        {
           Csp_H_Puntos_Fuer_Fase.writeOperations(ai_m4Op);
        }

        // write data for node CSP_H_PUNTOS_MEJOR_FASE.
        if ( Csp_H_Puntos_Mejor_Fase != null) 
        {
           Csp_H_Puntos_Mejor_Fase.writeOperations(ai_m4Op);
        }

        // write data for node CSP_ACCIONES_DESA_FEEDBK.
        if ( Csp_Acciones_Desa_Feedbk != null) 
        {
           Csp_Acciones_Desa_Feedbk.writeOperations(ai_m4Op);
        }

        // write data for node CSP_ACCIONES_FORM_FEEDBK.
        if ( Csp_Acciones_Form_Feedbk != null) 
        {
           Csp_Acciones_Form_Feedbk.writeOperations(ai_m4Op);
        }

        // write data for node CSP_ACCIONES_PROP_FEEDBK.
        if ( Csp_Acciones_Prop_Feedbk != null) 
        {
           Csp_Acciones_Prop_Feedbk.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read DT_END.
        sItemName = "DT_END";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_End = M4BusinessMethodArg.toCalendar(sItemValue);

        // read DT_START.
        sItemName = "DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_ID_HR.
        sItemName = "CYC_ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Hr = sItemValue;

        // read CYC_COMENT.
        sItemName = "CYC_COMENT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Coment = sItemValue;

        // read CYC_ESTADO.
        sItemName = "CYC_ESTADO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Estado = sItemValue;

        // read CHECK_TOEIC.
        sItemName = "CHECK_TOEIC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        check_Toeic = sItemValue;

        // read CYC_ID_FASE.
        sItemName = "CYC_ID_FASE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Fase = sItemValue;

        // read CHECK_COMPROMISO.
        sItemName = "CHECK_COMPROMISO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        check_Compromiso = sItemValue;

        // read CYC_ID_OBSERVACION.
        sItemName = "CYC_ID_OBSERVACION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Observacion = sItemValue;

        // read CYC_FEC_REALIZACION.
        sItemName = "CYC_FEC_REALIZACION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Fec_Realizacion = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_COMENTARIOS_RRHH.
        sItemName = "CYC_COMENTARIOS_RRHH";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Comentarios_Rrhh = sItemValue;

        // read CYC_FEC_ENTREV_FEEDBK.
        sItemName = "CYC_FEC_ENTREV_FEEDBK";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Fec_Entrev_Feedbk = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_OBSERVACIONES_RRHH.
        sItemName = "CYC_OBSERVACIONES_RRHH";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Observaciones_Rrhh = sItemValue;

        // read CYC_PERFIL_PROFESIONAL.
        sItemName = "CYC_PERFIL_PROFESIONAL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Perfil_Profesional = sItemValue;

        // read CYC_COMENTARIOS_EMPLEADO.
        sItemName = "CYC_COMENTARIOS_EMPLEADO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Comentarios_Empleado = sItemValue;

        // read CYC_RECOMENDACIONES_RRHH.
        sItemName = "CYC_RECOMENDACIONES_RRHH";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Recomendaciones_Rrhh = sItemValue;

        // read CYC_FEC_ACEPTACION_FEEDBK.
        sItemName = "CYC_FEC_ACEPTACION_FEEDBK";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Fec_Aceptacion_Feedbk = M4BusinessMethodArg.toCalendar(sItemValue);

        // read data for node CSP_NOTAS_OBT.
        Csp_Notas_Obt = new Csp_Notas_ObtBlock();
        Csp_Notas_Obt.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_Notas_ObtBlock.NODE_NAME));

        // read data for node CSP_LISTA_NOTAS.
        Csp_Lista_Notas = new Csp_Lista_NotasBlock();
        Csp_Lista_Notas.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_Lista_NotasBlock.NODE_NAME));

        // read data for node CSP_LISTA_NOTAS_FASE1.
        Csp_Lista_Notas_Fase1 = new Csp_Lista_Notas_Fase1Block();
        Csp_Lista_Notas_Fase1.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_Lista_Notas_Fase1Block.NODE_NAME));

        // read data for node CSP_LISTA_NOTAS_FASE2.
        Csp_Lista_Notas_Fase2 = new Csp_Lista_Notas_Fase2Block();
        Csp_Lista_Notas_Fase2.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_Lista_Notas_Fase2Block.NODE_NAME));

        // read data for node CSP_LISTA_NOTAS_FASE3.
        Csp_Lista_Notas_Fase3 = new Csp_Lista_Notas_Fase3Block();
        Csp_Lista_Notas_Fase3.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_Lista_Notas_Fase3Block.NODE_NAME));

        // read data for node CSP_H_PUNTOS_FUER_FASE.
        Csp_H_Puntos_Fuer_Fase = new Csp_H_Puntos_Fuer_FaseBlock();
        Csp_H_Puntos_Fuer_Fase.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_H_Puntos_Fuer_FaseBlock.NODE_NAME));

        // read data for node CSP_H_PUNTOS_MEJOR_FASE.
        Csp_H_Puntos_Mejor_Fase = new Csp_H_Puntos_Mejor_FaseBlock();
        Csp_H_Puntos_Mejor_Fase.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_H_Puntos_Mejor_FaseBlock.NODE_NAME));

        // read data for node CSP_ACCIONES_DESA_FEEDBK.
        Csp_Acciones_Desa_Feedbk = new Csp_Acciones_Desa_FeedbkBlock();
        Csp_Acciones_Desa_Feedbk.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_Acciones_Desa_FeedbkBlock.NODE_NAME));

        // read data for node CSP_ACCIONES_FORM_FEEDBK.
        Csp_Acciones_Form_Feedbk = new Csp_Acciones_Form_FeedbkBlock();
        Csp_Acciones_Form_Feedbk.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_Acciones_Form_FeedbkBlock.NODE_NAME));

        // read data for node CSP_ACCIONES_PROP_FEEDBK.
        Csp_Acciones_Prop_Feedbk = new Csp_Acciones_Prop_FeedbkBlock();
        Csp_Acciones_Prop_Feedbk.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_Acciones_Prop_FeedbkBlock.NODE_NAME));


    } /* end of method readOperations */


} /* end of class Csp_Obtener_FeedbackRecord */

