/**
 * Csp_Lista_NotasBlock.java
 * Self generated code for Bussines Object CSP_OBTENER_FEEDBACK.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.csp_obtener_feedback;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Csp_Lista_Notas.
 * @author Meta4
 */
public 
class Csp_Lista_NotasBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_OBTENER_FEEDBACK";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_LISTA_NOTAS";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Lista_NotasBlock.class.getName());

    /* the recordset */
    public Csp_Lista_NotasRecord[] Csp_Lista_NotasRecordSet = null;
    private void setCsp_Lista_NotasRecordSet(Csp_Lista_NotasRecord[] ai_arg)
    {
        Csp_Lista_NotasRecordSet = ai_arg;
    }
    private Csp_Lista_NotasRecord[] getCsp_Lista_NotasRecordSet()
    {
        return Csp_Lista_NotasRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Csp_Lista_NotasBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();

        // insert 'block scope' values in CSP_LISTA_NOTAS.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in CSP_LISTA_NOTAS.
        if (Csp_Lista_NotasRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Csp_Lista_NotasRecordSet.length; i++)
        {
            Csp_Lista_NotasRecord record = Csp_Lista_NotasRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in CSP_LISTA_NOTAS.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;


        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Csp_Lista_NotasRecordSet = new Csp_Lista_NotasRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Csp_Lista_NotasRecord record = new Csp_Lista_NotasRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Csp_Lista_NotasRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Csp_Lista_NotasBlock */

