/**
 * Csp_Acciones_Prop_FeedbkRecord.java
 * Self generated code for Bussines Object CSP_OBTENER_FEEDBACK.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_obtener_feedback;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Acciones_Prop_Feedbk.
 * @author Meta4
 */
public 
class Csp_Acciones_Prop_FeedbkRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_OBTENER_FEEDBACK";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_ACCIONES_PROP_FEEDBK";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Acciones_Prop_FeedbkRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item CHECK_SELECCIONADO */
    public String check_Seleccionado = null;
    private void setcheck_Seleccionado(String ai_value)
    {
        check_Seleccionado = ai_value;
    }
    private String getcheck_Seleccionado()
    {
        return check_Seleccionado;
    }

    /* item CYC_ID_TIPO_ACCION */
    public String cyc_Id_Tipo_Accion = null;
    private void setcyc_Id_Tipo_Accion(String ai_value)
    {
        cyc_Id_Tipo_Accion = ai_value;
    }
    private String getcyc_Id_Tipo_Accion()
    {
        return cyc_Id_Tipo_Accion;
    }

    /* item SCO_ID_DEV_SUBPRODUCT */
    public String sco_Id_Dev_Subproduct = null;
    private void setsco_Id_Dev_Subproduct(String ai_value)
    {
        sco_Id_Dev_Subproduct = ai_value;
    }
    private String getsco_Id_Dev_Subproduct()
    {
        return sco_Id_Dev_Subproduct;
    }

    /* item SCO_NM_DEV_SUBPRODUCT */
    public String sco_Nm_Dev_Subproduct = null;
    private void setsco_Nm_Dev_Subproduct(String ai_value)
    {
        sco_Nm_Dev_Subproduct = ai_value;
    }
    private String getsco_Nm_Dev_Subproduct()
    {
        return sco_Nm_Dev_Subproduct;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // CHECK_SELECCIONADO.
        if (check_Seleccionado != null)
        {
            htItems.put("CHECK_SELECCIONADO", M4BusinessMethodArg.toString(check_Seleccionado));
        }
        // CYC_ID_TIPO_ACCION.
        if (cyc_Id_Tipo_Accion != null)
        {
            htItems.put("CYC_ID_TIPO_ACCION", M4BusinessMethodArg.toString(cyc_Id_Tipo_Accion));
        }
        // SCO_ID_DEV_SUBPRODUCT.
        if (sco_Id_Dev_Subproduct != null)
        {
            htItems.put("SCO_ID_DEV_SUBPRODUCT", M4BusinessMethodArg.toString(sco_Id_Dev_Subproduct));
        }
        // SCO_NM_DEV_SUBPRODUCT.
        if (sco_Nm_Dev_Subproduct != null)
        {
            htItems.put("SCO_NM_DEV_SUBPRODUCT", M4BusinessMethodArg.toString(sco_Nm_Dev_Subproduct));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read CHECK_SELECCIONADO.
        sItemName = "CHECK_SELECCIONADO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        check_Seleccionado = sItemValue;

        // read CYC_ID_TIPO_ACCION.
        sItemName = "CYC_ID_TIPO_ACCION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Tipo_Accion = sItemValue;

        // read SCO_ID_DEV_SUBPRODUCT.
        sItemName = "SCO_ID_DEV_SUBPRODUCT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Dev_Subproduct = sItemValue;

        // read SCO_NM_DEV_SUBPRODUCT.
        sItemName = "SCO_NM_DEV_SUBPRODUCT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Nm_Dev_Subproduct = sItemValue;


    } /* end of method readOperations */


} /* end of class Csp_Acciones_Prop_FeedbkRecord */

