import type { QuinquenalRow } from "@/types/quinquenal";

/** Fila ficticia: valores inventados, sin datos de empleados reales. */
export const sampleQuinquenalRow: QuinquenalRow = {
  employeeId: "9001",
  legalEntity: "ACYC_ES",
  firstName: "Ana",
  lastName1: "Prueba",
  lastName2: "Ejemplo",
  birthDate: "1980-05-01",
  seniorityDate: "2005-09-15",
  fusionId: "100001",
  structureId: "0",
  structureName: "Empleado",
  ceo: { id: "0-CEO", name: "CEO" },
  mb: { id: "1_MB", name: "MB" },
  alt: { id: "2_ALT", name: "Alt" },
  direction: { id: null, name: null },
  area: { id: "4_AREA", name: "Área" },
  unit: { id: "5_UNIDAD", name: "Unidad" },
  service: { id: null, name: null },
  jobId: "PUE",
  jobName: "Puesto de prueba",
  categoryId: "II4",
  categoryName: "Grupo II-Nivel 4",
  jobGroup: "II",
  jobLevel: "4",
  costCenter: "000001",
  atradiusJob: "JOB01",
  variableModel: "Modelo",
  atradiusCategory: "S2",
  globalGrade: 8,
  jobFamilyId: "FAM",
  jobFamilyName: "Familia",
  years: [
    { year: 2026, coefficient: 1, salary: 40000, reducedSalary: 40000, variable: 2000 },
    { year: 2025, coefficient: 0.5, salary: 39000, reducedSalary: 19500, variable: 1800 },
    { year: 2024, coefficient: 1, salary: 38000, reducedSalary: 38000, variable: 0 },
    { year: 2023, coefficient: null, salary: null, reducedSalary: null, variable: null },
    { year: 2022, coefficient: 1, salary: 36000, reducedSalary: 36000, variable: 1500 },
  ],
};
