/* Root Menu */
DELETE FROM M4RMN_OPTIONS
WHERE ID_MENU = 'SGCO_MENU';

INSERT INTO M4RMN_OPTIONS (ID_MENU, TRANS_MENUGER, TRANS_MENUFRA, TRANS_MENUESP, TRANS_MENUENG, TRANS_MENUGEN, N_MENU, ICON, OWNER_FLAG, DT_LAST_UPDATE, ID_SECUSER, ID_APPROLE) VALUES
('SGCO_MENU', 'ESS/MSS Menu', 'ESS/MSS Menu', 'ESS/MSS Menu', 'ESS/MSS Menu', 'ESS/MSS Menu', 'ESS/MSS Menu', 'XCLOSEDBLUEBOOK', 120, '2009-01-01 00:00:00','M4ADM', 'M4ADM');

DELETE FROM M4RMN_OPTIONS1
WHERE ID_MENU = 'SGCO_MENU';

INSERT INTO M4RMN_OPTIONS1 (ID_MENU) VALUES
('SGCO_MENU');

DELETE FROM M4RMN_TREE
WHERE ID_MENU = 'SGCO_MENU';

INSERT INTO M4RMN_TREE VALUES 
('SGCO_MENU','SHCO_GN_MENU_CONFIG', 10, '2009-01-01 00:00:00','M4ADM', 'M4ADM');

DELETE FROM M4RMN_TREE
WHERE ID_PARENT_MENU = 'SGCO_MENU';

/* ESS Root Menu */
DELETE FROM M4RMN_TREE
WHERE ID_MENU = 'SSCO_MENU';

INSERT INTO M4RMN_TREE VALUES 
('SSCO_MENU','SGCO_MENU', 1, '2009-01-01 00:00:00','M4ADM', 'M4ADM');

DELETE FROM M4RMN_OPTIONS
WHERE ID_MENU = 'SSCO_MENU';

INSERT INTO M4RMN_OPTIONS (ID_MENU, TRANS_MENUGER, TRANS_MENUFRA, TRANS_MENUESP, TRANS_MENUENG, TRANS_MENUGEN, N_MENU, ICON, OWNER_FLAG, DT_LAST_UPDATE, ID_SECUSER, ID_APPROLE) VALUES
('SSCO_MENU', 'ESS Menu', 'ESS Menu', 'ESS Menu', 'ESS Menu', 'ESS Menu', 'ESS Menu', 'XCLOSEDBLUEBOOK', 120, '2009-01-01 00:00:00','M4ADM', 'M4ADM');

DELETE FROM M4RMN_OPTIONS1
WHERE ID_MENU = 'SSCO_MENU';

INSERT INTO M4RMN_OPTIONS1 (ID_MENU) VALUES
('SSCO_MENU');

/* MSS Root Menu */
DELETE FROM M4RMN_TREE
WHERE ID_MENU = 'SMCO_MENU';

INSERT INTO M4RMN_TREE VALUES 
('SMCO_MENU','SGCO_MENU', 2, '2009-01-01 00:00:00','M4ADM', 'M4ADM');

DELETE FROM M4RMN_OPTIONS
WHERE ID_MENU = 'SMCO_MENU';

INSERT INTO M4RMN_OPTIONS (ID_MENU, TRANS_MENUGER, TRANS_MENUFRA, TRANS_MENUESP, TRANS_MENUENG, TRANS_MENUGEN, N_MENU, ICON, OWNER_FLAG, DT_LAST_UPDATE, ID_SECUSER, ID_APPROLE) VALUES
('SMCO_MENU', 'MSS Menu', 'MSS Menu', 'MSS Menu', 'MSS Menu', 'MSS Menu', 'MSS Menu', 'XCLOSEDBLUEBOOK', 120, '2009-01-01 00:00:00','M4ADM', 'M4ADM');

DELETE FROM M4RMN_OPTIONS1
WHERE ID_MENU = 'SMCO_MENU';

INSERT INTO M4RMN_OPTIONS1 (ID_MENU) VALUES
('SMCO_MENU');

/* ESS To Do List */
DELETE FROM M4RMN_TREE
WHERE ID_MENU = 'SSCO_G0';

INSERT INTO M4RMN_TREE VALUES 
('SSCO_G0', 'SSCO_MENU', 0, '2009-01-01 00:00:00', 'M4ADM', 'M4ADM');

DELETE FROM M4RMN_OPTIONS
WHERE ID_MENU = 'SSCO_G0';

INSERT INTO M4RMN_OPTIONS (ID_MENU, TRANS_MENUGER, TRANS_MENUFRA, TRANS_MENUESP, TRANS_MENUENG, TRANS_MENUGEN, N_MENU, ICON, OWNER_FLAG, DT_LAST_UPDATE, ID_SECUSER, ID_APPROLE) VALUES
('SSCO_G0', 'As minhas ferramentas', 'Vos outils', 'Mis herramientas', 'My Tools', 'My Tools', 'My Tools', 'XCLOSEDBLUEBOOK', 120, '2009-01-01 00:00:00','M4ADM', 'M4ADM');

DELETE FROM M4RMN_OPTIONS1
WHERE ID_MENU = 'SSCO_G0';

INSERT INTO M4RMN_OPTIONS1 (ID_MENU) VALUES
('SSCO_G0');

DELETE FROM M4RMN_TREE
WHERE ID_MENU = 'SSCO_G0_TO_DO_LIST';

INSERT INTO M4RMN_TREE VALUES 
('SSCO_G0_TO_DO_LIST', 'SSCO_G0', 0, '2009-01-01 00:00:00', 'M4ADM', 'M4ADM');

DELETE FROM M4RMN_OPTIONS
WHERE ID_MENU = 'SSCO_G0_TO_DO_LIST';

INSERT INTO M4RMN_OPTIONS (ID_MENU, TRANS_MENUGER, TRANS_MENUFRA, TRANS_MENUESP, TRANS_MENUENG, TRANS_MENUGEN, N_MENU, ICON, OWNER_FLAG, DT_LAST_UPDATE, ID_SECUSER, ID_APPROLE) VALUES
('SSCO_G0_TO_DO_LIST', 'As minhas tarefas', 'Vos tâches', 'Mis tareas', 'My Tasks', 'My Tasks', 'My Tasks', 'XCLOSEDBLUEBOOK', 120, '2009-01-01 00:00:00','M4ADM', 'M4ADM');

DELETE FROM M4RMN_OPTIONS1
WHERE ID_MENU = 'SSCO_G0_TO_DO_LIST';

INSERT INTO M4RMN_OPTIONS1 (ID_MENU, N_HTTPGER, N_HTTPFRA, N_HTTPESP, N_HTTPENG, N_HTTPGEN) VALUES
('SSCO_G0_TO_DO_LIST', '/servlet/CheckSecurity/JSP/sse_generico/ssegenerico_pendientes.jsp?estado=0', '/servlet/CheckSecurity/JSP/sse_generico/ssegenerico_pendientes.jsp?estado=0', '/servlet/CheckSecurity/JSP/sse_generico/ssegenerico_pendientes.jsp?estado=0', '/servlet/CheckSecurity/JSP/sse_generico/ssegenerico_pendientes.jsp?estado=0', '/servlet/CheckSecurity/JSP/sse_generico/ssegenerico_pendientes.jsp?estado=0');

/* MSS To Do List */
DELETE FROM M4RMN_TREE
WHERE ID_MENU = 'SMCO_G0';

INSERT INTO M4RMN_TREE VALUES 
('SMCO_G0', 'SMCO_MENU', 0, '2009-01-01 00:00:00', 'M4ADM', 'M4ADM');

DELETE FROM M4RMN_OPTIONS
WHERE ID_MENU = 'SMCO_G0';

INSERT INTO M4RMN_OPTIONS (ID_MENU, TRANS_MENUGER, TRANS_MENUFRA, TRANS_MENUESP, TRANS_MENUENG, TRANS_MENUGEN, N_MENU, ICON, OWNER_FLAG, DT_LAST_UPDATE, ID_SECUSER, ID_APPROLE) VALUES
('SMCO_G0', 'Minhas ferramentas', 'Mes outils', 'Mis herramientas', 'My Tools', 'My Tools', 'My Tools', 'XCLOSEDBLUEBOOK', 120, '2009-01-01 00:00:00','M4ADM', 'M4ADM');

DELETE FROM M4RMN_OPTIONS1
WHERE ID_MENU = 'SMCO_G0';

INSERT INTO M4RMN_OPTIONS1 (ID_MENU) VALUES
('SMCO_G0');

DELETE FROM M4RMN_TREE
WHERE ID_MENU = 'SMCO_G0_TO_DO_LIST';

INSERT INTO M4RMN_TREE VALUES 
('SMCO_G0_TO_DO_LIST', 'SMCO_G0', 0, '2009-01-01 00:00:00', 'M4ADM', 'M4ADM');

DELETE FROM M4RMN_OPTIONS
WHERE ID_MENU = 'SMCO_G0_TO_DO_LIST';

INSERT INTO M4RMN_OPTIONS (ID_MENU, TRANS_MENUGER, TRANS_MENUFRA, TRANS_MENUESP, TRANS_MENUENG, TRANS_MENUGEN, N_MENU, ICON, OWNER_FLAG, DT_LAST_UPDATE, ID_SECUSER, ID_APPROLE) VALUES
('SMCO_G0_TO_DO_LIST', 'As minhas tarefas', 'Vos tâches', 'Mis tareas', 'My Tasks', 'My Tasks', 'My Tasks', 'XCLOSEDBLUEBOOK', 120, '2009-01-01 00:00:00','M4ADM', 'M4ADM');

DELETE FROM M4RMN_OPTIONS1
WHERE ID_MENU = 'SMCO_G0_TO_DO_LIST';

INSERT INTO M4RMN_OPTIONS1 (ID_MENU, N_HTTPGER, N_HTTPFRA, N_HTTPESP, N_HTTPENG, N_HTTPGEN) VALUES
('SMCO_G0_TO_DO_LIST', '/servlet/CheckSecurity/JSP/mss_generico/mssgenerico_pendientes.jsp?estado=0', '/servlet/CheckSecurity/JSP/mss_generico/mssgenerico_pendientes.jsp?estado=0', '/servlet/CheckSecurity/JSP/mss_generico/mssgenerico_pendientes.jsp?estado=0', '/servlet/CheckSecurity/JSP/mss_generico/mssgenerico_pendientes.jsp?estado=0', '/servlet/CheckSecurity/JSP/mss_generico/mssgenerico_pendientes.jsp?estado=0');
