/**
 * Cyc_Filt_Fases_F2Record.java
 * Self generated code for Bussines Object CYC_FILT_VALORES_F2.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_filt_valores_f2;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Filt_Fases_F2.
 * @author Meta4
 */
public 
class Cyc_Filt_Fases_F2Record 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_FILT_VALORES_F2";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_FILT_FASES_F2";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Filt_Fases_F2Record.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item CYC_COMP_IMPLI_F2 */
    public Double cyc_Comp_Impli_F2 = null;
    private void setcyc_Comp_Impli_F2(Double ai_value)
    {
        cyc_Comp_Impli_F2 = ai_value;
    }
    private Double getcyc_Comp_Impli_F2()
    {
        return cyc_Comp_Impli_F2;
    }

    /* item CYC_TOMA_DECIS_F2 */
    public Double cyc_Toma_Decis_F2 = null;
    private void setcyc_Toma_Decis_F2(Double ai_value)
    {
        cyc_Toma_Decis_F2 = ai_value;
    }
    private Double getcyc_Toma_Decis_F2()
    {
        return cyc_Toma_Decis_F2;
    }

    /* item CYC_DESA_PERSON_F2 */
    public Double cyc_Desa_Person_F2 = null;
    private void setcyc_Desa_Person_F2(Double ai_value)
    {
        cyc_Desa_Person_F2 = ai_value;
    }
    private Double getcyc_Desa_Person_F2()
    {
        return cyc_Desa_Person_F2;
    }

    /* item CYC_MEJORA_CONT_F2 */
    public Double cyc_Mejora_Cont_F2 = null;
    private void setcyc_Mejora_Cont_F2(Double ai_value)
    {
        cyc_Mejora_Cont_F2 = ai_value;
    }
    private Double getcyc_Mejora_Cont_F2()
    {
        return cyc_Mejora_Cont_F2;
    }

    /* item CYC_ORIENT_CAMB_F2 */
    public Double cyc_Orient_Camb_F2 = null;
    private void setcyc_Orient_Camb_F2(Double ai_value)
    {
        cyc_Orient_Camb_F2 = ai_value;
    }
    private Double getcyc_Orient_Camb_F2()
    {
        return cyc_Orient_Camb_F2;
    }

    /* item CYC_TRAB_EQUIPO_F2 */
    public Double cyc_Trab_Equipo_F2 = null;
    private void setcyc_Trab_Equipo_F2(Double ai_value)
    {
        cyc_Trab_Equipo_F2 = ai_value;
    }
    private Double getcyc_Trab_Equipo_F2()
    {
        return cyc_Trab_Equipo_F2;
    }

    /* item CYC_COMUNICACION_F2 */
    public Double cyc_Comunicacion_F2 = null;
    private void setcyc_Comunicacion_F2(Double ai_value)
    {
        cyc_Comunicacion_F2 = ai_value;
    }
    private Double getcyc_Comunicacion_F2()
    {
        return cyc_Comunicacion_F2;
    }

    /* item CYC_FLEXIBILIDAD_F2 */
    public Double cyc_Flexibilidad_F2 = null;
    private void setcyc_Flexibilidad_F2(Double ai_value)
    {
        cyc_Flexibilidad_F2 = ai_value;
    }
    private Double getcyc_Flexibilidad_F2()
    {
        return cyc_Flexibilidad_F2;
    }

    /* item CYC_AUTOCONFIANZA_F2 */
    public Double cyc_Autoconfianza_F2 = null;
    private void setcyc_Autoconfianza_F2(Double ai_value)
    {
        cyc_Autoconfianza_F2 = ai_value;
    }
    private Double getcyc_Autoconfianza_F2()
    {
        return cyc_Autoconfianza_F2;
    }

    /* item CYC_DIREC_EQUIPOS_F2 */
    public Double cyc_Direc_Equipos_F2 = null;
    private void setcyc_Direc_Equipos_F2(Double ai_value)
    {
        cyc_Direc_Equipos_F2 = ai_value;
    }
    private Double getcyc_Direc_Equipos_F2()
    {
        return cyc_Direc_Equipos_F2;
    }

    /* item CYC_ORIENT_CLIENT_F2 */
    public Double cyc_Orient_Client_F2 = null;
    private void setcyc_Orient_Client_F2(Double ai_value)
    {
        cyc_Orient_Client_F2 = ai_value;
    }
    private Double getcyc_Orient_Client_F2()
    {
        return cyc_Orient_Client_F2;
    }

    /* item CYC_ORIENT_RESULT_F2 */
    public Double cyc_Orient_Result_F2 = null;
    private void setcyc_Orient_Result_F2(Double ai_value)
    {
        cyc_Orient_Result_F2 = ai_value;
    }
    private Double getcyc_Orient_Result_F2()
    {
        return cyc_Orient_Result_F2;
    }

    /* item CYC_CAPAC_ANALITIC_F2 */
    public Double cyc_Capac_Analitic_F2 = null;
    private void setcyc_Capac_Analitic_F2(Double ai_value)
    {
        cyc_Capac_Analitic_F2 = ai_value;
    }
    private Double getcyc_Capac_Analitic_F2()
    {
        return cyc_Capac_Analitic_F2;
    }

    /* item CYC_PLANIF_ORGANIZ_F2 */
    public Double cyc_Planif_Organiz_F2 = null;
    private void setcyc_Planif_Organiz_F2(Double ai_value)
    {
        cyc_Planif_Organiz_F2 = ai_value;
    }
    private Double getcyc_Planif_Organiz_F2()
    {
        return cyc_Planif_Organiz_F2;
    }

    /* item CYC_VISION_GBAL_EST_F2 */
    public Double cyc_Vision_Gbal_Est_F2 = null;
    private void setcyc_Vision_Gbal_Est_F2(Double ai_value)
    {
        cyc_Vision_Gbal_Est_F2 = ai_value;
    }
    private Double getcyc_Vision_Gbal_Est_F2()
    {
        return cyc_Vision_Gbal_Est_F2;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // CYC_COMP_IMPLI_F2.
        if (cyc_Comp_Impli_F2 != null)
        {
            htItems.put("CYC_COMP_IMPLI_F2", M4BusinessMethodArg.toString(cyc_Comp_Impli_F2));
        }
        // CYC_TOMA_DECIS_F2.
        if (cyc_Toma_Decis_F2 != null)
        {
            htItems.put("CYC_TOMA_DECIS_F2", M4BusinessMethodArg.toString(cyc_Toma_Decis_F2));
        }
        // CYC_DESA_PERSON_F2.
        if (cyc_Desa_Person_F2 != null)
        {
            htItems.put("CYC_DESA_PERSON_F2", M4BusinessMethodArg.toString(cyc_Desa_Person_F2));
        }
        // CYC_MEJORA_CONT_F2.
        if (cyc_Mejora_Cont_F2 != null)
        {
            htItems.put("CYC_MEJORA_CONT_F2", M4BusinessMethodArg.toString(cyc_Mejora_Cont_F2));
        }
        // CYC_ORIENT_CAMB_F2.
        if (cyc_Orient_Camb_F2 != null)
        {
            htItems.put("CYC_ORIENT_CAMB_F2", M4BusinessMethodArg.toString(cyc_Orient_Camb_F2));
        }
        // CYC_TRAB_EQUIPO_F2.
        if (cyc_Trab_Equipo_F2 != null)
        {
            htItems.put("CYC_TRAB_EQUIPO_F2", M4BusinessMethodArg.toString(cyc_Trab_Equipo_F2));
        }
        // CYC_COMUNICACION_F2.
        if (cyc_Comunicacion_F2 != null)
        {
            htItems.put("CYC_COMUNICACION_F2", M4BusinessMethodArg.toString(cyc_Comunicacion_F2));
        }
        // CYC_FLEXIBILIDAD_F2.
        if (cyc_Flexibilidad_F2 != null)
        {
            htItems.put("CYC_FLEXIBILIDAD_F2", M4BusinessMethodArg.toString(cyc_Flexibilidad_F2));
        }
        // CYC_AUTOCONFIANZA_F2.
        if (cyc_Autoconfianza_F2 != null)
        {
            htItems.put("CYC_AUTOCONFIANZA_F2", M4BusinessMethodArg.toString(cyc_Autoconfianza_F2));
        }
        // CYC_DIREC_EQUIPOS_F2.
        if (cyc_Direc_Equipos_F2 != null)
        {
            htItems.put("CYC_DIREC_EQUIPOS_F2", M4BusinessMethodArg.toString(cyc_Direc_Equipos_F2));
        }
        // CYC_ORIENT_CLIENT_F2.
        if (cyc_Orient_Client_F2 != null)
        {
            htItems.put("CYC_ORIENT_CLIENT_F2", M4BusinessMethodArg.toString(cyc_Orient_Client_F2));
        }
        // CYC_ORIENT_RESULT_F2.
        if (cyc_Orient_Result_F2 != null)
        {
            htItems.put("CYC_ORIENT_RESULT_F2", M4BusinessMethodArg.toString(cyc_Orient_Result_F2));
        }
        // CYC_CAPAC_ANALITIC_F2.
        if (cyc_Capac_Analitic_F2 != null)
        {
            htItems.put("CYC_CAPAC_ANALITIC_F2", M4BusinessMethodArg.toString(cyc_Capac_Analitic_F2));
        }
        // CYC_PLANIF_ORGANIZ_F2.
        if (cyc_Planif_Organiz_F2 != null)
        {
            htItems.put("CYC_PLANIF_ORGANIZ_F2", M4BusinessMethodArg.toString(cyc_Planif_Organiz_F2));
        }
        // CYC_VISION_GBAL_EST_F2.
        if (cyc_Vision_Gbal_Est_F2 != null)
        {
            htItems.put("CYC_VISION_GBAL_EST_F2", M4BusinessMethodArg.toString(cyc_Vision_Gbal_Est_F2));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read CYC_COMP_IMPLI_F2.
        sItemName = "CYC_COMP_IMPLI_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Comp_Impli_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_TOMA_DECIS_F2.
        sItemName = "CYC_TOMA_DECIS_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Toma_Decis_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_DESA_PERSON_F2.
        sItemName = "CYC_DESA_PERSON_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Desa_Person_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_MEJORA_CONT_F2.
        sItemName = "CYC_MEJORA_CONT_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Mejora_Cont_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_ORIENT_CAMB_F2.
        sItemName = "CYC_ORIENT_CAMB_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Orient_Camb_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_TRAB_EQUIPO_F2.
        sItemName = "CYC_TRAB_EQUIPO_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Trab_Equipo_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_COMUNICACION_F2.
        sItemName = "CYC_COMUNICACION_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Comunicacion_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_FLEXIBILIDAD_F2.
        sItemName = "CYC_FLEXIBILIDAD_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Flexibilidad_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_AUTOCONFIANZA_F2.
        sItemName = "CYC_AUTOCONFIANZA_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Autoconfianza_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_DIREC_EQUIPOS_F2.
        sItemName = "CYC_DIREC_EQUIPOS_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Direc_Equipos_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_ORIENT_CLIENT_F2.
        sItemName = "CYC_ORIENT_CLIENT_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Orient_Client_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_ORIENT_RESULT_F2.
        sItemName = "CYC_ORIENT_RESULT_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Orient_Result_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_CAPAC_ANALITIC_F2.
        sItemName = "CYC_CAPAC_ANALITIC_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Capac_Analitic_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_PLANIF_ORGANIZ_F2.
        sItemName = "CYC_PLANIF_ORGANIZ_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Planif_Organiz_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_VISION_GBAL_EST_F2.
        sItemName = "CYC_VISION_GBAL_EST_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Vision_Gbal_Est_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);


    } /* end of method readOperations */


} /* end of class Cyc_Filt_Fases_F2Record */

