import type { PortalDomain } from "../types";

/** Dominios del portal, en el orden del menú original (SSE y SSM). */
export const PORTAL_DOMAINS: readonly PortalDomain[] = [
  {
    id: "datos",
    profile: "empleado",
    title: "Mis datos",
    summary: "Datos personales y profesionales, IRPF, emergencia, dependientes y documentos.",
    icon: "id-card",
    route: "/portal/empleado/datos",
    guide: "empleado/datos/guia.md",
  },
  {
    id: "retribucion",
    profile: "empleado",
    title: "Retribución",
    summary: "Bancos, nóminas, certificados, préstamos, beneficios y proyecciones.",
    icon: "payslip",
    route: "/portal/empleado/retribucion",
    guide: "empleado/retribucion/guia.md",
  },
  {
    id: "tiempo",
    profile: "empleado",
    title: "Tiempo",
    summary: "Vacaciones, incidencias, festivos, ausencias, planificación y reloj.",
    icon: "calendar",
    route: "/portal/empleado/tiempo",
    guide: "empleado/tiempo/guia.md",
  },
  {
    id: "talento",
    profile: "empleado",
    title: "Talento",
    summary: "Puesto, formación, evaluación, carrera, movilidad y desarrollo.",
    icon: "career",
    route: "/portal/empleado/talento",
    guide: "empleado/talento/guia.md",
  },
  {
    id: "organizacion",
    profile: "empleado",
    title: "Organización",
    summary: "Quién es quién, organigrama y contactos.",
    icon: "org",
    route: "/portal/organizacion",
    guide: "empleado/organizacion/guia.md",
  },
  {
    id: "conocimiento",
    profile: "empleado",
    title: "Conocimiento",
    summary: "Mi conocimiento y sistemas enlazados.",
    icon: "knowledge",
    route: "/portal/empleado/conocimiento",
    guide: "empleado/conocimiento/guia.md",
  },
  {
    id: "tareas",
    profile: "responsable",
    title: "Tareas",
    summary: "Validaciones, valoraciones y tareas pendientes.",
    icon: "tasks",
    route: "/portal/tareas",
    guide: "responsable/tareas/guia.md",
  },
  {
    id: "alcance",
    profile: "responsable",
    title: "Alcance",
    summary: "Población visible, unidades y delegaciones.",
    icon: "scope",
    route: "/portal/responsable/alcance",
    guide: "responsable/tareas/guia.md",
  },
  {
    id: "equipo",
    profile: "responsable",
    title: "Equipo",
    summary: "Listado y dossier del equipo, validaciones de datos e informes.",
    icon: "team",
    route: "/portal/responsable/equipo",
    guide: "responsable/equipo/guia.md",
  },
  {
    id: "retribucion-equipo",
    profile: "responsable",
    title: "Retribución",
    summary: "Salarios, presupuesto, aprobaciones económicas y revisión salarial.",
    icon: "salary",
    route: "/portal/responsable/retribucion",
    guide: "responsable/retribucion/guia.md",
  },
  {
    id: "talento-equipo",
    profile: "responsable",
    title: "Talento",
    summary: "Evaluación, objetivos, formación, carrera, vacantes, entrevistas y movimientos.",
    icon: "evaluation",
    route: "/portal/responsable/talento",
    guide: "responsable/talento/guia.md",
  },
  {
    id: "tiempo-equipo",
    profile: "responsable",
    title: "Tiempo",
    summary: "Vacaciones aceptadas, ausencias, bolsas, validaciones y planificación.",
    icon: "planning",
    route: "/portal/responsable/tiempo",
    guide: "responsable/tiempo/guia.md",
  },
];
