import type { PortalFeature } from "../types";
import {
  area,
  check,
  consult,
  date,
  form,
  genericWrite,
  methodWrite,
  note,
  pendingRead,
  pendingSelect,
  text,
} from "./helpers";

const TAL = "empleado/talento";
const base = "/portal/empleado/talento";

export const EMPLEADO_TALENTO: readonly PortalFeature[] = [
  {
    id: "empleado.talento.puesto",
    profile: "empleado",
    domain: "talento",
    title: "Historial de puestos",
    summary: "Tus puestos con sus periodos y la descripción del puesto (DPT).",
    icon: "job",
    route: `${base}/puesto`,
    sources: [
      "sse_g3/sse_g3_p0.jsp",
      "sse_g3/sse_g3_p0_desc.jsp",
      "sse_g1/sse_g1_p1_dpt.jsp",
      "sse_g2/sse_g2_p5_det.jsp",
    ],
    ficha: `${TAL}/sse_g3--sse_g3_p0.md`,
    keywords: ["puesto", "dpt", "funciones", "historial"],
    sensitive: false,
    read: pendingRead(["SSE_JOB!SSE_JOB_PRINCIPAL.CARGA", "CSP_RP_JOB_DESCR!STD_JOB.LANZAR_LOADS"]),
    view: "generic",
    sections: [
      consult("historial", "Historial de puestos", "SSE_JOB", "list", [
        [null, "Puesto"],
        [null, "Inicio"],
        [null, "Fin"],
      ]),
      note(
        "Descripción del puesto (DPT)",
        "El original genera la DPT con el informe CSP_RP_JOB_DESCR y, en CYC, el documento CSP_DOC_PUESTO_FICHA cuando CSP_MOSTRAR_DOC lo permite. Se ofrecerá cuando su documento esté verificado (P08).",
      ),
    ],
  },
  {
    id: "empleado.talento.formacion",
    profile: "empleado",
    domain: "talento",
    title: "Catálogo de formación",
    summary: "Cursos y productos formativos, eventos, destinatarios e inscripción.",
    icon: "training",
    route: `${base}/formacion`,
    sources: [
      "sse_g3/sse_g3_p3.jsp",
      "sse_g3/sse_g3_p3_desc.jsp",
      "sse_g3/sse_g3_p3_desc2.jsp",
      "sse_g3/sse_g3_p3_desc3.jsp",
      "sse_g3/sse_g3_p3_desc4.jsp",
      "sse_g3/sse_g3_p3_dest.jsp",
      "sse_g3/sse_g3_p3_mod1.jsp",
      "sse_g3/sse_g3_p3_mod2.jsp",
      "sse_g3/sse_g3_p3_mod3.jsp",
    ],
    ficha: `${TAL}/sse_g3--sse_g3_p3_mod1.md`,
    keywords: ["cursos", "formación", "inscripción", "catálogo"],
    sensitive: false,
    read: pendingRead(["CSP_SSE_TRAINING_REQUEST!SSE_PRINCIPAL.CARGA", "SGCO_TRAINING_DESC"]),
    view: "generic",
    sections: [
      consult("curso", "Descripción del curso de formación", "CSP_SSE_TRAINING_REQUEST", "record", [
        [null, "Tipo de formación"],
        [null, "Producto"],
        [null, "Curso"],
        [null, "Lugar"],
        [null, "Días"],
        [null, "Número de horas"],
        [null, "Número de horas fuera de jornada"],
        [null, "Número mínimo de asistentes"],
        [null, "Número máximo de asistentes"],
        [null, "Modalidad"],
        [null, "Objetivo formativo"],
        [null, "Destinatarios"],
      ]),
      form({
        id: "inscripcion",
        title: "Inscripción en curso",
        description: "Solicita un curso del catálogo indicando tus preferencias.",
        fields: [
          pendingSelect("SCO_ID_COURSE", "Curso", "CSP_SSE_TRAINING_REQUEST!SCO_COURSE", {
            required: true,
          }),
          date("SCO_DT_START_PREF", "Inicio preferido"),
          date("SCO_DT_END_PREF", "Fin preferido"),
          pendingSelect("SCO_ID_LANGUAGE", "Lenguaje", "CSP_SSE_TRAINING_REQUEST!SCO_LANGUAGE"),
          area("SCO_COMMENT", "Información adicional", { maxLength: 1000 }),
        ],
        rules: [
          {
            kind: "dateOrder",
            start: "SCO_DT_START_PREF",
            end: "SCO_DT_END_PREF",
            message: "El fin preferido no puede ser anterior al inicio.",
          },
        ],
        write: genericWrite(
          "inscripcion",
          "Solicitar inscripción",
          "CSP_SSE_TRAINING_REQUEST",
          "INSERTAR",
          "CSP_SSE_TRAINING_REQUEST",
        ),
      }),
    ],
  },
  {
    id: "empleado.talento.solicitudes-formacion",
    profile: "empleado",
    domain: "talento",
    title: "Inscripción en cursos",
    summary: "Tus solicitudes de formación pendientes de aprobar y las ya aceptadas.",
    icon: "training",
    route: `${base}/solicitudes-formacion`,
    sources: ["sse_g3/sse_g3_p7.jsp"],
    ficha: `${TAL}/sse_g3--sse_g3_p7.md`,
    sensitive: false,
    read: pendingRead(["CSP_SSE_TRAINING_REQUEST", "SSE_TRAINING_REQUEST"]),
    view: "generic",
    sections: [
      consult("pendientes", "Solicitudes pendientes", "CSP_SSE_TRAINING_REQUEST", "list", [
        [null, "Curso"],
        [null, "Tipo"],
        [null, "Programado"],
      ]),
      consult("aceptadas", "Solicitudes aceptadas", "CSP_SSE_TRAINING_REQUEST", "list", [
        [null, "Curso"],
        [null, "Tipo"],
        [null, "Sesión"],
        [null, "Inicio"],
        [null, "Fin"],
      ]),
    ],
    writes: [
      genericWrite(
        "borrar",
        "Borrar solicitud",
        "CSP_SSE_TRAINING_REQUEST",
        "BORRAR",
        "CSP_SSE_TRAINING_REQUEST",
      ),
    ],
  },
  {
    id: "empleado.talento.formacion-realizada",
    profile: "empleado",
    domain: "talento",
    title: "Formación realizada",
    summary: "Cursos realizados y sus certificados.",
    icon: "certificate",
    route: `${base}/formacion-realizada`,
    sources: [
      "sse_g3/sse_g3_p21.jsp",
      "sse_g3/sse_g3_p21_certificado.jsp",
      "sse_g3/certificado/sse_g3_p21_certificado.jsp",
    ],
    ficha: `${TAL}/sse_g3--sse_g3_p21.md`,
    keywords: ["cursos realizados", "certificado de formación"],
    sensitive: false,
    read: pendingRead([
      "SSE_H_HR_COURSE!SSE_H_HR_COURSE.SMCO_MAIN_LOAD_PROCESS",
      "CSP_MNG_DIPLOMAS_PORTAL",
    ]),
    view: "generic",
    sections: [
      note(
        "Certificados",
        "El certificado de cada curso es un documento de Meta4; se ofrecerá cuando su formato y permisos estén verificados (P08).",
      ),
    ],
  },
  {
    id: "empleado.talento.evaluacion-cursos",
    profile: "empleado",
    domain: "talento",
    title: "Evaluación de cursos",
    summary: "Valora los cursos en los que has participado con su cuestionario.",
    icon: "evaluation",
    route: `${base}/evaluacion-cursos`,
    sources: ["sse_g3/sse_g3_p8.jsp", "sse_g3/sse_g3_p8_desc.jsp", "sse_g3/sse_g3_p8_act.jsp"],
    ficha: `${TAL}/sse_g3--sse_g3_p8_desc.md`,
    sensitive: false,
    read: pendingRead([
      "SSE_TRAINING_EVAL!SSE_EVEN_EVAL_SHEET.CARGA",
      "CSP_TRAINING_EVAL!SSE_EVEN_EVAL_SHEET.CARGA",
    ]),
    view: "generic",
    sections: [
      consult("pendientes", "Cursos pendientes de evaluar", "SSE_TRAINING_EVAL", "list", [
        [null, "Curso"],
        [null, "Realizado en"],
      ]),
      note(
        "Cuestionario",
        "Cada pregunta tiene su tipo de respuesta y sus opciones definidas en Meta4 (texto libre o lista). No se sustituyen por una escala inventada; el cuestionario se mostrará con sus preguntas reales.",
      ),
    ],
    writes: [
      methodWrite("cuestionario", "Enviar cuestionario", "CSP_TRAINING_EVAL (sse_g3_p8_act.jsp)"),
    ],
  },
  {
    id: "empleado.talento.documentacion",
    profile: "empleado",
    domain: "talento",
    title: "Documentación publicada",
    summary: "Documentos de formación publicados para ti.",
    icon: "document",
    route: `${base}/documentacion`,
    sources: ["sse_g3/ssco_g3_pform.jsp"],
    ficha: `${TAL}/sse_g3--ssco_g3_pform.md`,
    sensitive: false,
    read: {
      kind: "pending",
      meta4: ["CSP_PUBLICACIONES_ESS!CSP_PUBLICACIONES_ESS.CSP_CARGA"],
      pending: ["P02", "P08"],
      detail:
        "Los documentos se descargan con el servlet download_blob de Meta4; falta su tabla, formato y permisos verificados.",
    },
    view: "generic",
  },
  {
    id: "empleado.talento.evaluacion",
    profile: "empleado",
    domain: "talento",
    title: "Evaluación del desempeño",
    summary:
      "Tus evaluaciones como evaluado y como evaluador, criterios, objetivos y conocimientos.",
    icon: "evaluation",
    route: `${base}/evaluacion`,
    sources: [
      "sse_g3/ssco_evaluator.jsp",
      "sse_g3/ssco_evaluator_body.jsp",
      "sse_g3/ssco_evaluator_seg.jsp",
      "sse_g3/ssco_evaluate.jsp",
      "sse_g3/ssco_evaluate_body.jsp",
      "sse_g3/ssco_evaluator_questions.jsp",
      "sse_g3/sse_g3_p5.jsp",
      "sse_g3/sse_g3_p5_open.jsp",
      "sse_g3/sse_g3_p6.jsp",
      "sse_g3/sse_g3_p17.jsp",
      "sse_g3/sse_g3_p22.jsp",
      "sse_g3/sse_g3_eval_ex.jsp",
    ],
    ficha: `${TAL}/sse_g3--ssco_evaluator_body.md`,
    keywords: ["evaluación", "objetivos", "competencias", "autoevaluación"],
    sensitive: true,
    read: pendingRead([
      "SSCO_H_EVALUTE!SSCO_H_EVALUATE.SSCO_LOAD",
      "SSE_H_EVALUATOR_HIST",
      "SSE_OBJECTIVES!SSE_OBJETIVES.CARGA",
      "SSM_EV_ROL_LV_OBJ!SSE_PRINCIPAL.CARGA",
      "SSE_H_HR_KNC_LVL!SSE_H_HR_KNC_LVL.SMCO_MAIN_LOAD_PROCESS",
    ]),
    view: "generic",
    sections: [
      consult("procesos", "Evaluaciones", "SSCO_H_EVALUTE", "list", [
        [null, "Proceso"],
        [null, "Rol"],
        [null, "Periodo de cuestionarios"],
        [null, "Estado"],
      ]),
      note(
        "Criterios y cálculo",
        "Cada criterio conserva peso, nivel esperado y obtenido, magnitud, resultado y comentarios según su tipo; los objetivos cuantitativos y cualitativos se separan. Las notas las calcula Meta4 con sus ponderaciones: no se hacen medias simples ni se cierra una evaluación al guardar un borrador.",
      ),
    ],
    writes: [
      methodWrite(
        "guardar-evaluacion",
        "Guardar evaluación",
        "SSCO_H_EVALUTE (ssco_evaluator_act.jsp)",
      ),
      methodWrite(
        "cerrar-evaluacion",
        "Cerrar y enviar evaluación",
        "SSCO_H_EVALUTE (ssco_evaluator_seg_act.jsp)",
      ),
      methodWrite(
        "objetivos",
        "Guardar objetivos",
        "SSE_EVAL_OBJECT / M4T_EVAL_OBJECT (sse_g3_p5_open.jsp)",
      ),
    ],
  },
  {
    id: "empleado.talento.evaluadores",
    profile: "empleado",
    domain: "talento",
    title: "Evaluadores 360",
    summary: "Solicita evaluadores para tu evaluación 360 y consulta tus peticiones.",
    icon: "team",
    route: `${base}/evaluadores`,
    sources: [
      "sse_g3/sse_g3_p4_1.jsp",
      "sse_g3/sse_g3_p4_1_mod.jsp",
      "sse_g3/sse_g3_p4_1_mod2.jsp",
      "sse_g3/sse_g3_p4_1_vis.jsp",
      "sse_g3/sse_g3_p18.jsp",
    ],
    ficha: `${TAL}/sse_g3--sse_g3_p4_1_mod.md`,
    sensitive: false,
    read: pendingRead(["SSE_EVAL360!SSE_PRINCIPAL.CARGA", "SSE_EVALUATOR"]),
    view: "generic",
    sections: [
      note(
        "Fase",
        "El estándar solo permite elegir evaluadores en la fase de fijación de criterios; la fase la determina el proceso en Meta4.",
      ),
      form({
        id: "evaluador",
        title: "Solicitar evaluador",
        fields: [
          text("SCO_GB_NAME", "Evaluador", {
            required: true,
            maxLength: 62,
            span: 2,
            help: "Nombre de la persona evaluadora.",
          }),
          check("SCO_EVALUATION_DEF", "Evaluación definitiva"),
        ],
        write: genericWrite(
          "evaluador",
          "Enviar petición",
          "SSE_EVAL360",
          "INSERTAR",
          "SSE_EVAL360",
        ),
      }),
    ],
    writes: [
      genericWrite(
        "evaluador-anular",
        "Anular petición de evaluador",
        "SSE_EVALUATOR",
        "ANULAR",
        "SSE_EVALUATOR",
      ),
    ],
  },
  {
    id: "empleado.talento.carrera",
    profile: "empleado",
    domain: "talento",
    title: "Plan de carrera",
    summary: "Puestos de tu plan de carrera, mentor y periodos previstos.",
    icon: "career",
    route: `${base}/carrera`,
    sources: ["sse_g3/sse_g3_p9.jsp", "sse_g3/sse_g3_p9_desc.jsp"],
    ficha: `${TAL}/sse_g3--sse_g3_p9.md`,
    keywords: ["carrera", "mentor", "promoción"],
    sensitive: false,
    read: pendingRead(["SSE_CAREER_PLAN!SSE_CR_PLAN_HT.SMCO_MAIN_LOAD_PROCESS"]),
    view: "generic",
    sections: [
      consult("plan", "Plan de carrera", "SSE_CAREER_PLAN", "record", [
        [null, "Plan de carrera"],
        [null, "Mentor"],
        [null, "Puestos y periodos (desde)"],
      ]),
    ],
  },
  {
    id: "empleado.talento.movilidad",
    profile: "empleado",
    domain: "talento",
    title: "Movilidad interna",
    summary: "Puestos vacantes disponibles, su descripción y tus peticiones de movilidad.",
    icon: "mobility",
    route: `${base}/movilidad`,
    sources: ["sse_g3/sse_g3_p2.jsp", "sse_g3/sse_g3_p2_mod.jsp", "sse_g3/sse_g3_p2_vis.jsp"],
    ficha: `${TAL}/sse_g3--sse_g3_p2.md`,
    keywords: ["vacantes", "movilidad", "traslado"],
    sensitive: false,
    read: pendingRead(["SSE_INT_MOVILITY!SSE_PRINCIPAL.CARGA"]),
    view: "generic",
    sections: [
      consult("vacantes", "Puestos vacantes", "SSE_INT_MOVILITY", "list", [[null, "Puesto"]]),
      consult("peticiones", "Peticiones de movilidad", "SSE_INT_MOVILITY", "list", [
        [null, "Puesto"],
        [null, "Fecha de solicitud"],
      ]),
      note(
        "Estados",
        "Las peticiones aceptadas quedan incluidas o por incluir en un proceso de selección y el Departamento de Selección se pondrá en contacto contigo.",
      ),
      form({
        id: "movilidad",
        title: "Solicitar movilidad",
        fields: [
          pendingSelect("SCO_ID_JOB", "Puesto", "SSE_INT_MOVILITY!SCO_JOB", {
            required: true,
            span: 2,
          }),
        ],
        write: genericWrite(
          "movilidad",
          "Enviar petición",
          "SSE_INT_MOVILITY",
          "INSERTAR",
          "SSE_INT_MOVILITY",
        ),
      }),
    ],
  },
  {
    id: "empleado.talento.desarrollo",
    profile: "empleado",
    domain: "talento",
    title: "Plan de desarrollo",
    summary: "Acciones de desarrollo asignadas, su seguimiento y tus preferencias de carrera.",
    icon: "goal",
    route: `${base}/desarrollo`,
    sources: [
      "sse_g3/ssco_g3_pdev.jsp",
      "sse_g3/ssco_g3_pdev_body.jsp",
      "sse_g3/ssco_g3_pdev_det.jsp",
      "sse_g3/ssco_g3_p23.jsp",
      "sse_g3/ssco_g3_p23_body.jsp",
      "sse_g3/ssco_g3_p23_mod1.jsp",
      "sse_g3/ssco_evaluator_questions_gest_plan.jsp",
    ],
    ficha: `${TAL}/sse_g3--ssco_g3_pdev_body.md`,
    keywords: ["desarrollo", "preferencias", "plan de acción"],
    sensitive: false,
    read: pendingRead([
      "SSCO_DEV_PLAN!SSCO_DEV_PLAN.SSCO_DEV_PLAN_LOAD",
      "SSE_CR_PREFERENC!SSE_PRINCIPAL.CARGA",
      "SSE_PLAN_ACTION",
    ]),
    view: "generic",
    sections: [
      consult("acciones", "Acciones de desarrollo", "SSCO_DEV_PLAN", "list", [
        [null, "Acción"],
        [null, "Estado"],
        [null, "Seguimiento"],
      ]),
    ],
    writes: [
      genericWrite(
        "preferencia",
        "Registrar preferencia de carrera",
        "SSE_CR_PREFERENC",
        "INSERTAR",
        "SSE_CR_PREFERENC",
      ),
      genericWrite(
        "preferencia-anular",
        "Anular preferencia",
        "SSE_CR_PREFERENC",
        "ANULAR",
        "SSE_CR_PREFERENC",
      ),
      genericWrite(
        "plan-accion",
        "Registrar seguimiento de la acción",
        "SSE_PLAN_ACTION",
        "INSERTAR",
        "SSE_PLAN_ACTION",
      ),
    ],
  },
  {
    id: "empleado.talento.entrevistas",
    profile: "empleado",
    domain: "talento",
    title: "Entrevistas",
    summary: "Tus entrevistas, su detalle y las peticiones asociadas.",
    icon: "interview",
    route: `${base}/entrevistas`,
    sources: ["sse_g3/ssco_g3_p11.jsp", "sse_g3/ssco_g3_p11_det.jsp", "sse_g3/ssco_g3_p11_pet.jsp"],
    ficha: `${TAL}/sse_g3--ssco_g3_p11.md`,
    sensitive: false,
    read: pendingRead(["SSE_GN_INTERVIEW!SSE_PRINCIPAL.CARGA"]),
    view: "generic",
    writes: [
      genericWrite(
        "entrevista",
        "Solicitar entrevista",
        "SSE_GN_INTERVIEW",
        "INSERTAR",
        "SSE_GN_INTERVIEW",
      ),
    ],
  },
];
