import type { PortalFeature } from "../types";
import {
  area,
  check,
  date,
  form,
  genericWrite,
  methodWrite,
  note,
  pendingSelect,
  sqlConsult,
  sqlRead,
  text,
} from "./helpers";
import { TALENTO_SQL } from "./sql/talento";

const TAL = "empleado/talento";
const base = "/portal/empleado/talento";

export const EMPLEADO_TALENTO: readonly PortalFeature[] = [
  {
    id: "empleado.talento.puesto",
    profile: "empleado",
    domain: "talento",
    title: "Historial de puestos",
    summary: "Tus puestos con sus periodos y la descripción del puesto (DPT).",
    icon: "job",
    route: `${base}/puesto`,
    sources: [
      "sse_g3/sse_g3_p0.jsp",
      "sse_g3/sse_g3_p0_desc.jsp",
      "sse_g1/sse_g1_p1_dpt.jsp",
      "sse_g2/sse_g2_p5_det.jsp",
    ],
    ficha: `${TAL}/sse_g3--sse_g3_p0.md`,
    keywords: ["puesto", "dpt", "funciones", "historial"],
    sensitive: false,
    read: sqlRead(TALENTO_SQL.puestos.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "historial",
        "Historial de puestos",
        "SSE_JOB!SSE_H_HR_JOB",
        "list",
        [
          ["STD_N_JOB_CODE", "Puesto"],
          ["SCO_DT_START", "Inicio"],
          ["SCO_DT_END", "Fin"],
        ],
        TALENTO_SQL.puestos,
      ),
      note(
        "Descripción del puesto (DPT)",
        "El original genera la DPT con el informe CSP_RP_JOB_DESCR y, en CYC, el documento CSP_DOC_PUESTO_FICHA cuando CSP_MOSTRAR_DOC lo permite. Se ofrecerá cuando su documento esté verificado (P08).",
      ),
    ],
  },
  {
    id: "empleado.talento.formacion",
    profile: "empleado",
    domain: "talento",
    title: "Catálogo de formación",
    summary: "Cursos y productos formativos, eventos, destinatarios e inscripción.",
    icon: "training",
    route: `${base}/formacion`,
    sources: [
      "sse_g3/sse_g3_p3.jsp",
      "sse_g3/sse_g3_p3_desc.jsp",
      "sse_g3/sse_g3_p3_desc2.jsp",
      "sse_g3/sse_g3_p3_desc3.jsp",
      "sse_g3/sse_g3_p3_desc4.jsp",
      "sse_g3/sse_g3_p3_dest.jsp",
      "sse_g3/sse_g3_p3_mod1.jsp",
      "sse_g3/sse_g3_p3_mod2.jsp",
      "sse_g3/sse_g3_p3_mod3.jsp",
    ],
    ficha: `${TAL}/sse_g3--sse_g3_p3_mod1.md`,
    keywords: ["cursos", "formación", "inscripción", "catálogo"],
    sensitive: false,
    read: sqlRead(TALENTO_SQL.cursosOfertados.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "curso",
        "Cursos publicados",
        "SSE_TRAINING_REQUEST!M4T_CURSOS",
        "list",
        [
          ["SCO_NM_DEV_SUBPRODUCT", "Curso"],
          ["SCO_DAYS", "Días"],
          ["SCO_HOURS", "Número de horas"],
          ["SCO_HOURS_OTW", "Número de horas fuera de jornada"],
          ["SCO_NB_MIN", "Número mínimo de asistentes"],
          ["SCO_NB_MAX", "Número máximo de asistentes"],
          ["SCO_EDUCAT_OBJ", "Objetivo formativo"],
        ],
        TALENTO_SQL.cursosOfertados,
        "Cursos del catálogo con publicación vigente que se pueden solicitar.",
      ),
      form({
        id: "inscripcion",
        title: "Inscripción en curso",
        description: "Solicita un curso del catálogo indicando tus preferencias.",
        fields: [
          pendingSelect("SCO_ID_COURSE", "Curso", "CSP_SSE_TRAINING_REQUEST!SCO_COURSE", {
            required: true,
          }),
          date("SCO_DT_START_PREF", "Inicio preferido"),
          date("SCO_DT_END_PREF", "Fin preferido"),
          pendingSelect("SCO_ID_LANGUAGE", "Lenguaje", "CSP_SSE_TRAINING_REQUEST!SCO_LANGUAGE"),
          area("SCO_COMMENT", "Información adicional", { maxLength: 1000 }),
        ],
        rules: [
          {
            kind: "dateOrder",
            start: "SCO_DT_START_PREF",
            end: "SCO_DT_END_PREF",
            message: "El fin preferido no puede ser anterior al inicio.",
          },
        ],
        write: genericWrite(
          "inscripcion",
          "Solicitar inscripción",
          "CSP_SSE_TRAINING_REQUEST",
          "INSERTAR",
          "CSP_SSE_TRAINING_REQUEST",
        ),
      }),
    ],
  },
  {
    id: "empleado.talento.solicitudes-formacion",
    profile: "empleado",
    domain: "talento",
    title: "Inscripción en cursos",
    summary: "Tus solicitudes de formación pendientes de aprobar y las ya aceptadas.",
    icon: "training",
    route: `${base}/solicitudes-formacion`,
    sources: ["sse_g3/sse_g3_p7.jsp"],
    ficha: `${TAL}/sse_g3--sse_g3_p7.md`,
    sensitive: false,
    read: sqlRead([
      ...TALENTO_SQL.solicitudesPendientes.tables,
      ...TALENTO_SQL.solicitudesAceptadas.tables,
    ]),
    view: "generic",
    sections: [
      sqlConsult(
        "pendientes",
        "Solicitudes pendientes",
        "SSE_TRAINING_REQUEST!SSE_TRAINING_REQUEST",
        "list",
        [
          ["SCO_NM_TRAINING", "Curso"],
          ["SCO_NM_TYPE", "Tipo"],
          ["N_ACCION", "Estado"],
        ],
        TALENTO_SQL.solicitudesPendientes,
      ),
      sqlConsult(
        "aceptadas",
        "Solicitudes tramitadas",
        "SSE_TRAINING_REQUEST!M4T_SOLICITUDES_ACEPTADAS",
        "list",
        [
          ["SCO_NM_DEV_SUBPRODUCT", "Curso"],
          ["SCO_NM_DEV_SUBACTION", "Sesión"],
          ["SCO_NM_REQ_STATUS", "Estado"],
          ["DT_START", "Inicio"],
          ["DT_END", "Fin"],
        ],
        TALENTO_SQL.solicitudesAceptadas,
      ),
    ],
    writes: [
      genericWrite(
        "borrar",
        "Borrar solicitud",
        "CSP_SSE_TRAINING_REQUEST",
        "BORRAR",
        "CSP_SSE_TRAINING_REQUEST",
      ),
    ],
  },
  {
    id: "empleado.talento.formacion-realizada",
    profile: "empleado",
    domain: "talento",
    title: "Formación realizada",
    summary: "Cursos realizados y sus certificados.",
    icon: "certificate",
    route: `${base}/formacion-realizada`,
    sources: [
      "sse_g3/sse_g3_p21.jsp",
      "sse_g3/sse_g3_p21_certificado.jsp",
      "sse_g3/certificado/sse_g3_p21_certificado.jsp",
    ],
    ficha: `${TAL}/sse_g3--sse_g3_p21.md`,
    keywords: ["cursos realizados", "certificado de formación"],
    sensitive: false,
    read: sqlRead(TALENTO_SQL.formacionRealizada.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "cursos",
        "Cursos realizados",
        "SSE_H_HR_COURSE!SSE_H_HR_COURSE",
        "list",
        [
          ["SCO_NM_DEV_SUBPRODUCT", "Curso"],
          ["SCO_DT_START", "Inicio"],
          ["SCO_DT_END", "Fin"],
          ["SCO_NM_STATE", "Estado"],
        ],
        TALENTO_SQL.formacionRealizada,
      ),
      note(
        "Certificados",
        "El certificado de cada curso es un documento de Meta4; se ofrecerá cuando su formato y permisos estén verificados (P08).",
      ),
    ],
  },
  {
    id: "empleado.talento.evaluacion-cursos",
    profile: "empleado",
    domain: "talento",
    title: "Evaluación de cursos",
    summary: "Valora los cursos en los que has participado con su cuestionario.",
    icon: "evaluation",
    route: `${base}/evaluacion-cursos`,
    sources: ["sse_g3/sse_g3_p8.jsp", "sse_g3/sse_g3_p8_desc.jsp", "sse_g3/sse_g3_p8_act.jsp"],
    ficha: `${TAL}/sse_g3--sse_g3_p8_desc.md`,
    sensitive: false,
    read: sqlRead(TALENTO_SQL.evaluacionCursos.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "pendientes",
        "Cuestionarios de cursos",
        "SSE_TRAINING_EVAL!SSE_EVEN_EVAL_SHEET",
        "list",
        [
          ["SCO_NM_DEV_SUBACTION", "Curso"],
          ["DT_START", "Inicio"],
          ["DT_END", "Fin"],
        ],
        TALENTO_SQL.evaluacionCursos,
      ),
      note(
        "Cuestionario",
        "Cada pregunta tiene su tipo de respuesta y sus opciones definidas en Meta4 (texto libre o lista). No se sustituyen por una escala inventada; el cuestionario se mostrará con sus preguntas reales.",
      ),
    ],
    writes: [
      methodWrite("cuestionario", "Enviar cuestionario", "CSP_TRAINING_EVAL (sse_g3_p8_act.jsp)"),
    ],
  },
  {
    id: "empleado.talento.documentacion",
    profile: "empleado",
    domain: "talento",
    title: "Documentación publicada",
    summary: "Documentos de formación publicados para ti.",
    icon: "document",
    route: `${base}/documentacion`,
    sources: ["sse_g3/ssco_g3_pform.jsp"],
    ficha: `${TAL}/sse_g3--ssco_g3_pform.md`,
    sensitive: false,
    read: sqlRead(TALENTO_SQL.publicaciones.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "publicaciones",
        "Documentación de RR. HH.",
        "CSP_PUBLICACIONES_ESS!CSP_PUBLICACIONES_ESS",
        "list",
        [
          ["N_FILE", "Documento"],
          ["COMMENTS", "Descripción"],
        ],
        TALENTO_SQL.publicaciones,
        "Publicaciones de la plantilla PUBLICACIONESESS. La descarga se añadirá cuando haya documentos publicados con los que verificarla.",
      ),
    ],
  },
  {
    id: "empleado.talento.evaluacion",
    profile: "empleado",
    domain: "talento",
    title: "Evaluación del desempeño",
    summary:
      "Tus evaluaciones como evaluado y como evaluador, criterios, objetivos y conocimientos.",
    icon: "evaluation",
    route: `${base}/evaluacion`,
    sources: [
      "sse_g3/ssco_evaluator.jsp",
      "sse_g3/ssco_evaluator_body.jsp",
      "sse_g3/ssco_evaluator_seg.jsp",
      "sse_g3/ssco_evaluate.jsp",
      "sse_g3/ssco_evaluate_body.jsp",
      "sse_g3/ssco_evaluator_questions.jsp",
      "sse_g3/sse_g3_p5.jsp",
      "sse_g3/sse_g3_p5_open.jsp",
      "sse_g3/sse_g3_p6.jsp",
      "sse_g3/sse_g3_p17.jsp",
      "sse_g3/sse_g3_p22.jsp",
      "sse_g3/sse_g3_eval_ex.jsp",
    ],
    ficha: `${TAL}/sse_g3--ssco_evaluator_body.md`,
    keywords: ["evaluación", "objetivos", "competencias", "autoevaluación"],
    sensitive: true,
    read: sqlRead(TALENTO_SQL.evaluaciones.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "procesos",
        "Evaluaciones",
        "SSCO_H_EVALUTE!SSCO_H_EVALUATE",
        "list",
        [
          ["SCO_NM_EVAL_PROC", "Proceso"],
          ["SCO_DT_ST_EV_PER", "Inicio del periodo evaluado"],
          ["SCO_DT_END_EV_PER", "Fin del periodo evaluado"],
          ["SCO_NM_LEVEL_OBJ", "Nivel de objetivos"],
          ["SCO_NM_LEVEL_CAP", "Nivel de competencias"],
        ],
        TALENTO_SQL.evaluaciones,
      ),
      note(
        "Criterios y cálculo",
        "Cada criterio conserva peso, nivel esperado y obtenido, magnitud, resultado y comentarios según su tipo; los objetivos cuantitativos y cualitativos se separan. Las notas las calcula Meta4 con sus ponderaciones: no se hacen medias simples ni se cierra una evaluación al guardar un borrador.",
      ),
    ],
    writes: [
      methodWrite(
        "guardar-evaluacion",
        "Guardar evaluación",
        "SSCO_H_EVALUTE (ssco_evaluator_act.jsp)",
      ),
      methodWrite(
        "cerrar-evaluacion",
        "Cerrar y enviar evaluación",
        "SSCO_H_EVALUTE (ssco_evaluator_seg_act.jsp)",
      ),
      methodWrite(
        "objetivos",
        "Guardar objetivos",
        "SSE_EVAL_OBJECT / M4T_EVAL_OBJECT (sse_g3_p5_open.jsp)",
      ),
    ],
  },
  {
    id: "empleado.talento.evaluadores",
    profile: "empleado",
    domain: "talento",
    title: "Evaluadores 360",
    summary: "Solicita evaluadores para tu evaluación 360 y consulta tus peticiones.",
    icon: "team",
    route: `${base}/evaluadores`,
    sources: [
      "sse_g3/sse_g3_p4_1.jsp",
      "sse_g3/sse_g3_p4_1_mod.jsp",
      "sse_g3/sse_g3_p4_1_mod2.jsp",
      "sse_g3/sse_g3_p4_1_vis.jsp",
      "sse_g3/sse_g3_p18.jsp",
    ],
    ficha: `${TAL}/sse_g3--sse_g3_p4_1_mod.md`,
    sensitive: false,
    read: sqlRead(TALENTO_SQL.evaluadores.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "evaluadores",
        "Mis evaluadores",
        "SSCO_H_EVALUTE!SSCO_EVALUATOR",
        "list",
        [
          ["SCO_NM_EVALUATOR", "Evaluador"],
          ["SCO_DT_START_EVAL", "Evaluación"],
          ["SCO_EVALUAT_DATE", "Fecha de evaluación"],
        ],
        TALENTO_SQL.evaluadores,
      ),
      note(
        "Fase",
        "El estándar solo permite elegir evaluadores en la fase de fijación de criterios; la fase la determina el proceso en Meta4.",
      ),
      form({
        id: "evaluador",
        title: "Solicitar evaluador",
        fields: [
          text("SCO_GB_NAME", "Evaluador", {
            required: true,
            maxLength: 62,
            span: 2,
            help: "Nombre de la persona evaluadora.",
          }),
          check("SCO_EVALUATION_DEF", "Evaluación definitiva"),
        ],
        write: genericWrite(
          "evaluador",
          "Enviar petición",
          "SSE_EVAL360",
          "INSERTAR",
          "SSE_EVAL360",
        ),
      }),
    ],
    writes: [
      genericWrite(
        "evaluador-anular",
        "Anular petición de evaluador",
        "SSE_EVALUATOR",
        "ANULAR",
        "SSE_EVALUATOR",
      ),
    ],
  },
  {
    id: "empleado.talento.carrera",
    profile: "empleado",
    domain: "talento",
    title: "Plan de carrera",
    summary: "Puestos de tu plan de carrera, mentor y periodos previstos.",
    icon: "career",
    route: `${base}/carrera`,
    sources: ["sse_g3/sse_g3_p9.jsp", "sse_g3/sse_g3_p9_desc.jsp"],
    ficha: `${TAL}/sse_g3--sse_g3_p9.md`,
    keywords: ["carrera", "mentor", "promoción"],
    sensitive: false,
    read: sqlRead(TALENTO_SQL.carrera.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "plan",
        "Plan de carrera",
        "SSE_CAREER_PLAN!SSE_CR_PLAN_HT",
        "list",
        [
          ["SCO_NM_CR_PLAN", "Plan de carrera"],
          ["DT_START", "Desde"],
          ["DT_END", "Hasta"],
        ],
        TALENTO_SQL.carrera,
      ),
    ],
  },
  {
    id: "empleado.talento.movilidad",
    profile: "empleado",
    domain: "talento",
    title: "Movilidad interna",
    summary: "Puestos vacantes disponibles, su descripción y tus peticiones de movilidad.",
    icon: "mobility",
    route: `${base}/movilidad`,
    sources: ["sse_g3/sse_g3_p2.jsp", "sse_g3/sse_g3_p2_mod.jsp", "sse_g3/sse_g3_p2_vis.jsp"],
    ficha: `${TAL}/sse_g3--sse_g3_p2.md`,
    keywords: ["vacantes", "movilidad", "traslado"],
    sensitive: false,
    read: sqlRead([...TALENTO_SQL.vacantes.tables, ...TALENTO_SQL.peticionesMovilidad.tables]),
    view: "generic",
    sections: [
      sqlConsult(
        "vacantes",
        "Puestos vacantes",
        "SSE_INT_MOVILITY!M4T_RECRUIT_PRO",
        "list",
        [
          ["SCO_NM_RECRUIT", "Proceso"],
          ["STD_N_JOB_CODE", "Puesto"],
          ["SCO_DT_LIMIT", "Plazo"],
        ],
        TALENTO_SQL.vacantes,
      ),
      sqlConsult(
        "peticiones",
        "Peticiones de movilidad",
        "SSE_INT_MOVILITY!SSE_INT_MOVILITY",
        "list",
        [
          ["SCO_NM_RECRUIT", "Puesto"],
          ["SSE_SOLIC_DATE", "Fecha de solicitud"],
          ["ID_ESTADO_REG", "Estado"],
        ],
        TALENTO_SQL.peticionesMovilidad,
      ),
      note(
        "Estados",
        "Las peticiones aceptadas quedan incluidas o por incluir en un proceso de selección y el Departamento de Selección se pondrá en contacto contigo.",
      ),
      form({
        id: "movilidad",
        title: "Solicitar movilidad",
        fields: [
          pendingSelect("SCO_ID_JOB", "Puesto", "SSE_INT_MOVILITY!SCO_JOB", {
            required: true,
            span: 2,
          }),
        ],
        write: genericWrite(
          "movilidad",
          "Enviar petición",
          "SSE_INT_MOVILITY",
          "INSERTAR",
          "SSE_INT_MOVILITY",
        ),
      }),
    ],
  },
  {
    id: "empleado.talento.desarrollo",
    profile: "empleado",
    domain: "talento",
    title: "Plan de desarrollo",
    summary: "Acciones de desarrollo asignadas, su seguimiento y tus preferencias de carrera.",
    icon: "goal",
    route: `${base}/desarrollo`,
    sources: [
      "sse_g3/ssco_g3_pdev.jsp",
      "sse_g3/ssco_g3_pdev_body.jsp",
      "sse_g3/ssco_g3_pdev_det.jsp",
      "sse_g3/ssco_g3_p23.jsp",
      "sse_g3/ssco_g3_p23_body.jsp",
      "sse_g3/ssco_g3_p23_mod1.jsp",
      "sse_g3/ssco_evaluator_questions_gest_plan.jsp",
    ],
    ficha: `${TAL}/sse_g3--ssco_g3_pdev_body.md`,
    keywords: ["desarrollo", "preferencias", "plan de acción"],
    sensitive: false,
    read: sqlRead(TALENTO_SQL.desarrollo.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "acciones",
        "Acciones de desarrollo",
        "SSCO_DEV_PLAN!SSCO_DEV_PLAN",
        "list",
        [
          ["SCO_NM_ACTION", "Acción"],
          ["SCO_DT_START", "Inicio"],
          ["SCO_DT_END", "Fin"],
          ["SCO_IS_FINISHED", "Estado"],
          ["SCO_FINISH_DESC", "Seguimiento"],
        ],
        TALENTO_SQL.desarrollo,
      ),
    ],
    writes: [
      genericWrite(
        "preferencia",
        "Registrar preferencia de carrera",
        "SSE_CR_PREFERENC",
        "INSERTAR",
        "SSE_CR_PREFERENC",
      ),
      genericWrite(
        "preferencia-anular",
        "Anular preferencia",
        "SSE_CR_PREFERENC",
        "ANULAR",
        "SSE_CR_PREFERENC",
      ),
      genericWrite(
        "plan-accion",
        "Registrar seguimiento de la acción",
        "SSE_PLAN_ACTION",
        "INSERTAR",
        "SSE_PLAN_ACTION",
      ),
    ],
  },
  {
    id: "empleado.talento.entrevistas",
    profile: "empleado",
    domain: "talento",
    title: "Entrevistas",
    summary: "Tus entrevistas, su detalle y las peticiones asociadas.",
    icon: "interview",
    route: `${base}/entrevistas`,
    sources: ["sse_g3/ssco_g3_p11.jsp", "sse_g3/ssco_g3_p11_det.jsp", "sse_g3/ssco_g3_p11_pet.jsp"],
    ficha: `${TAL}/sse_g3--ssco_g3_p11.md`,
    sensitive: false,
    read: sqlRead(TALENTO_SQL.entrevistas.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "entrevistas",
        "Mis entrevistas",
        "SSE_GN_INTERVIEW!M4T_GN_INTERVIEW",
        "list",
        [
          ["SCO_INTERVIEW_NAME", "Entrevista"],
          ["SCO_NM_IV_TYPE", "Tipo"],
          ["SCO_DT_REQUEST", "Solicitada"],
          ["SCO_DT_FINISH", "Finalizada"],
        ],
        TALENTO_SQL.entrevistas,
      ),
    ],
    writes: [
      genericWrite(
        "entrevista",
        "Solicitar entrevista",
        "SSE_GN_INTERVIEW",
        "INSERTAR",
        "SSE_GN_INTERVIEW",
      ),
    ],
  },
];
