import type { PortalFeature } from "../types";
import { PORTAL_READERS } from "./readers";
import {
  consult,
  date,
  form,
  genericWrite,
  methodWrite,
  note,
  pendingSelect,
  sqlConsult,
  sqlRead,
  staticSelect,
  text,
} from "./helpers";
import { RETRIBUCION_SQL } from "./sql/retribucion";

const RET = "empleado/retribucion";
const base = "/portal/empleado/retribucion";

const BANK_FIELDS = [
  date("STD_DT_START", "Inicio", { required: true }),
  pendingSelect("SCO_IBAN_CODE", "Código país", "SSE_PAYMENT_DATA!SSP_CODIGO_ISO", {
    required: true,
  }),
  text("SCO_IBAN_KEY", "Clave IBAN", {
    maxLength: 2,
    pattern: { regex: "^[0-9]{2}$", message: "Campo obligatorio numérico de 2 caracteres." },
  }),
  text("SCO_ID_BANK_BRANCH", "Código bancario (entidad y sucursal)", {
    required: true,
    pattern: { regex: "^[0-9]{8}$", message: "Entidad y sucursal: 8 dígitos (4 + 4)." },
  }),
  text("SCO_ACCOUNT_NUMBER", "Número de cuenta", {
    required: true,
    maxLength: 20,
    pattern: {
      regex: "^[0-9]{10,20}$",
      message: "Campo obligatorio numérico (dígitos de control y cuenta).",
    },
  }),
] as const;

export const EMPLEADO_RETRIBUCION: readonly PortalFeature[] = [
  {
    id: "empleado.retribucion.nominas",
    profile: "empleado",
    domain: "retribucion",
    title: "Últimos recibos de salarios",
    summary: "Consulta tus recibos: periodo de liquidación, conceptos, bases, totales y líquido.",
    icon: "payslip",
    route: `${base}/nominas`,
    sources: [
      "sse_g2/sse_g2_p4.jsp",
      "sse_g2/sse_g2_rec.jsp",
      "sse_g2/sse_g2_rec_imp.jsp",
      "sse_g2/sse_g2_table_rec.jsp",
    ],
    ficha: `${RET}/sse_g2--sse_g2_p4.md`,
    keywords: ["nómina", "recibo", "salario", "líquido", "neto"],
    sensitive: true,
    read: {
      kind: "sql",
      tables: [
        "M4SCO_HT_PAYS",
        "M4SCO_AC_HR_PERIOD",
        "M4CSP_AC_HR_PERIOD",
        "M4SCO_ROWS",
        "STD_HR_PERIOD",
      ],
      verified: true,
    },
    view: "payslips",
    sections: [
      note(
        "Pagas retroactivas",
        "El original marca la retroactividad de cada paga (SSE_LAST_PAYS). La consulta de pagas retroactivas sigue pendiente de las SELECT que usa Meta4 para ese modo; hoy se muestran las pagas actuales.",
      ),
    ],
  },
  {
    id: "empleado.retribucion.recibos-pdf",
    profile: "empleado",
    domain: "retribucion",
    title: "Recibos por año",
    summary: "Documentos de nómina publicados por año (SSE_LAST_HR_PAY_DOCS).",
    icon: "document",
    route: `${base}/recibos-por-ano`,
    sources: ["sse_g2/ssco_g2_p12.jsp"],
    ficha: `${RET}/sse_g2--ssco_g2_p12.md`,
    sensitive: true,
    read: sqlRead(RETRIBUCION_SQL.recibos.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "recibos",
        "Recibos de nómina",
        "SSE_LAST_HR_PAY_DOCS!SSE_LAST_HR_PAY_DOCS",
        "list",
        [
          ["SCO_NM_PAY", "Paga"],
          ["SCO_DT_PAYMENT", "Fecha de pago"],
          ["SCO_NM_PAY_ALLOCATION", "Imputación"],
          ["SCO_NM_DOC", "Documento"],
        ],
        RETRIBUCION_SQL.recibos,
        "Recibos publicados que PeopleNet guarda en PDF, del más reciente al más antiguo.",
        { kind: "payslip", label: "Descargar PDF" },
      ),
    ],
  },
  {
    id: "empleado.retribucion.cuenta-principal",
    profile: "empleado",
    domain: "retribucion",
    title: "Cuenta bancaria principal",
    summary: "Tu cuenta de cobro y la petición de cambio por IBAN.",
    icon: "bank",
    route: `${base}/cuenta-principal`,
    sources: [
      "sse_g2/sse_g2_p1.jsp",
      "sse_g2/sse_g2_p1_mod.jsp",
      "sse_g2/sse_g2_p1_mod_iban.jsp",
      "sse_g2/sse_g2_p1_mod_iban_n.jsp",
      "sse_g2/sse_g2_p1_mod_n.jsp",
      "sse_g2/sse_payment_data_trans.jsp",
    ],
    ficha: `${RET}/sse_g2--sse_g2_p1.md`,
    keywords: ["banco", "iban", "cuenta", "domiciliación"],
    sensitive: true,
    read: PORTAL_READERS["own-payment-accounts"],
    view: "generic",
    variants: {
      BASE: "El cambio es efectivo a partir del día 1 del próximo mes.",
      IBER: "La fecha efectiva del cambio se calcula en función de los procesos de nómina calculados (formularios «_n»).",
      COLL: "La fecha efectiva del cambio se calcula en función de los procesos de nómina calculados (formularios «_n»).",
    },
    sections: [
      consult(
        "cuenta",
        "Cuentas de cobro vigentes",
        "SSE_PAYMENT_DATA",
        "list",
        [
          ["SCO_DT_START", "Inicio"],
          ["SCO_DT_END", "Fin"],
          ["SCO_GB_IBAN", "IBAN"],
          ["SCO_OR_HR_PERIOD", "Periodo de contrato"],
        ],
        "Lectura de PAYMENT_DATA y PERSON_BANK usada en los recibos. Las reglas de selección de cuenta principal del JSP requieren contraste en la VM.",
        "own-payment-accounts",
      ),
      note(
        "Campos pendientes del original",
        "La moneda y el número de cuenta desglosado necesitan su correspondencia de columnas verificada. Las cuentas de beneficiarios se documentan por separado y no se deducen de estas cuentas de cobro.",
      ),
      form({
        id: "cuenta-principal",
        title: "Modificar cuenta bancaria principal",
        description: "Modifica tus datos bancarios.",
        fields: [...BANK_FIELDS],
        write: genericWrite(
          "cuenta-principal",
          "Enviar petición",
          "SSE_PAYMENT_DATA",
          "INSERTAR",
          "SSE_PAYMENT_DATA",
        ),
        notice:
          "El original avisa: «El cambio será efectivo a partir del día 1 del próximo mes» (BASE) o «se calculará en función de los procesos de nómina calculados» (IBER y COLL).",
      }),
    ],
  },
  {
    id: "empleado.retribucion.otras-cuentas",
    profile: "empleado",
    domain: "retribucion",
    title: "Otras cuentas bancarias",
    summary: "Cuentas adicionales y de beneficiarios con importe fijo o porcentaje.",
    icon: "bank",
    route: `${base}/otras-cuentas`,
    sources: [
      "sse_g2/sse_g2_p2.jsp",
      "sse_g2/sse_g2_p2_n.jsp",
      "sse_g2/sse_g2_p2_add.jsp",
      "sse_g2/sse_g2_p2_add_iban.jsp",
      "sse_g2/sse_g2_p2_add_iban_n.jsp",
      "sse_g2/sse_g2_p2_add_n.jsp",
      "sse_g2/sse_g2_p2_mod.jsp",
      "sse_g2/sse_g2_p2_mod_iban.jsp",
    ],
    ficha: `${RET}/sse_g2--sse_g2_p2.md`,
    sensitive: true,
    read: sqlRead(RETRIBUCION_SQL.otrasCuentas.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "otras",
        "Otras cuentas bancarias",
        "SSE_OTHER_PDATA!M4T_OTHER_PDATA",
        "list",
        [
          ["SCO_ENTITLED", "Titular"],
          ["SCO_GB_IBAN", "IBAN"],
          ["SCO_NM_PAYMFORMULA", "Tipo de importe"],
          ["SCO_NM_PAYM_TYPE", "Forma de pago"],
          ["SCO_DT_START", "Inicio"],
          ["SCO_DT_END", "Fin"],
        ],
        RETRIBUCION_SQL.otrasCuentas,
      ),
      form({
        id: "otra-cuenta",
        title: "Dar de alta otra cuenta bancaria",
        fields: [
          ...BANK_FIELDS,
          pendingSelect("SCO_ID_PERSON", "Beneficiario", "SSE_OTHER_PDATA!SCO_PERSON", {
            required: true,
          }),
          staticSelect(
            "SSP_PAY_FORM_TP",
            "Tipo de importe",
            [
              { value: "1", label: "Fijo" },
              { value: "2", label: "Porcentaje" },
            ],
            { required: true },
          ),
          {
            name: "SCO_VALUE",
            label: "Importe",
            type: "number",
            required: true,
            min: 0,
            maxLength: 20,
          },
          {
            name: "SCO_ID_CURRENCY",
            label: "Moneda",
            type: "select",
            options: { kind: "catalog", catalog: "currency" },
            showWhen: { field: "SSP_PAY_FORM_TP", equals: ["1"] },
          },
        ],
        write: genericWrite(
          "otra-cuenta",
          "Enviar petición",
          "SSE_OTHER_PDATA",
          "INSERTAR",
          "SSE_OTHER_PDATA",
        ),
      }),
    ],
    writes: [
      genericWrite(
        "otra-cuenta-anular",
        "Anular cuenta",
        "SSE_OTHER_PDATA",
        "ANULAR",
        "SSE_OTHER_PDATA",
      ),
    ],
  },
  {
    id: "empleado.retribucion.certificados",
    profile: "empleado",
    domain: "retribucion",
    title: "Certificados de retenciones",
    summary: "Tu certificado de retenciones e ingresos a cuenta por ejercicio.",
    icon: "certificate",
    route: `${base}/certificados`,
    sources: ["sse_g2/sse_g2_cert_hab.jsp", "sse_g2/sse_g2_cert_hab_cyc.jsp"],
    ficha: `${RET}/sse_g2--sse_g2_cert_hab_cyc.md`,
    keywords: ["certificado", "irpf", "retenciones", "haberes"],
    sensitive: true,
    read: sqlRead(RETRIBUCION_SQL.certificados.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "certificados",
        "Certificados guardados",
        "CSP_CERT_DOC!CSP_CERT_DOC",
        "list",
        [
          ["ANIO", "Ejercicio"],
          ["SCO_NM_DOC", "Documento"],
        ],
        RETRIBUCION_SQL.certificados,
        "Certificados que PeopleNet tiene guardados (CSP_CERT_DOC). Los ejercicios que el original genera al momento con el motor de informes de Meta4 (CYC_RP_CERT_HAB_<año>, SSP_RP_CERT_HAB) no están en tablas y no se pueden leer por SQL.",
        { kind: "certificate", label: "Descargar PDF" },
      ),
    ],
    variants: {
      CYC: "Lista de ejercicios (CSP_CERTIFICADO_HAB_ANIOS) con informes CYC_RP_CERT_HAB_2015–2017 e IBER_RP_CERT_HAB_2018–2021, y documentos históricos (CSP_CERT_DOC).",
      BASE: "Certificado del año en curso con SSP_RP_CERT_HAB.",
    },
  },
  {
    id: "empleado.retribucion.proyecciones",
    profile: "empleado",
    domain: "retribucion",
    title: "Informes de proyecciones",
    summary: "Proyección teórica de haberes y compensación total por año.",
    icon: "chart",
    route: `${base}/proyecciones`,
    sources: [
      "sse_g2/sse_g2_proyecciones.jsp",
      "sse_g2/sse_g2_inf_proyec.jsp",
      "sse_g2/proyecciones/index.jsp",
      "sse_g2/proy_ret_json.jsp",
    ],
    ficha: `${RET}/sse_g2--sse_g2_inf_proyec.md`,
    keywords: ["proyección", "haberes", "compensación total", "beneficios sociales"],
    sensitive: true,
    availableIn: ["CYC", "IBER", "COLL"],
    read: sqlRead([
      ...RETRIBUCION_SQL.proyeccionDatos.tables,
      ...RETRIBUCION_SQL.proyeccionConceptos.tables,
      ...RETRIBUCION_SQL.proyeccionInformes.tables,
    ]),
    view: "generic",
    sections: [
      sqlConsult(
        "datos",
        "Última proyección calculada",
        "CSP_RP_PROYECCIONES!SSE_DATOS_PROYECCION",
        "record",
        [
          ["CSP_FEC_EJECUCION", "Calculada el"],
          ["SSP_NM_CATEGORIA", "Categoría"],
          ["SCO_N_WORK_LOCATION", "Centro de trabajo"],
          ["PAGA_TOT", "Total anual"],
        ],
        RETRIBUCION_SQL.proyeccionDatos,
      ),
      sqlConsult(
        "bloques",
        "Proyección teórica de haberes",
        "CSP_RP_PROYECCIONES!SSE_EXTRAC_PROYECCION",
        "list",
        [
          ["CSP_GRUPO", "Bloque"],
          ["ID_ITEM", "Concepto"],
          ["TOTAL", "Total anual"],
        ],
        RETRIBUCION_SQL.proyeccionConceptos,
        "Conceptos que Meta4 extrae al calcular la proyección, en su orden original.",
      ),
      sqlConsult(
        "informes",
        "Informes guardados",
        "CSP_RP_PROYECCIONES!CSP_ANIOS_PROYECCIONES",
        "list",
        [
          ["ANIO", "Año"],
          ["SCO_NM_DOC", "Documento"],
        ],
        RETRIBUCION_SQL.proyeccionInformes,
        undefined,
        { kind: "projection", label: "Descargar PDF" },
      ),
      note(
        "Cálculo",
        "La proyección conserva sus fórmulas y métodos de Meta4; no se sustituye por una suma genérica ni se presenta como nómina real.",
      ),
    ],
  },
  {
    id: "empleado.retribucion.prestamos",
    profile: "empleado",
    domain: "retribucion",
    title: "Préstamos",
    summary: "Préstamos concedidos, simulación, solicitud y detalle.",
    icon: "loan",
    route: `${base}/prestamos`,
    sources: [
      "sse_g2/sse_g2_p3_pc.jsp",
      "sse_g2/sse_g2_p5.jsp",
      "sse_g2/sse_g2_p5_sim.jsp",
      "sse_g2/sse_g2_p5_desc.jsp",
      "sse_g2/sse_g2_p5_p.jsp",
    ],
    ficha: `${RET}/sse_g2--sse_g2_p5.md`,
    keywords: ["préstamo", "anticipo", "simulación", "cuotas"],
    sensitive: true,
    read: sqlRead(RETRIBUCION_SQL.prestamos.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "concedidos",
        "Consulta de préstamos",
        "SSE_LOANS!M4T_LN_HT_HR_LOANS",
        "list",
        [
          ["SCO_NM_LOAN", "Préstamo"],
          ["SCO_DT_APPROVAL", "Concesión"],
          ["SCO_AMT_LOAN", "Capital"],
          ["SCO_NUM_QUOTAS", "Cuotas"],
        ],
        RETRIBUCION_SQL.prestamos,
      ),
      sqlConsult(
        "detalle",
        "Detalle del préstamo",
        "SSE_LOANS!M4T_LN_HT_CONDITIONS",
        "list",
        [
          ["SCO_DT_APPLICATION", "Fecha de solicitud"],
          ["SCO_NM_LOAN", "Tipo de préstamo"],
          ["SCO_RATE", "Interés"],
          ["SCO_AMT_LOAN", "Capital"],
          ["SCO_NM_REASON", "Motivo"],
          ["SCO_NM_PAY_OFF_FREQ", "Frecuencia"],
          ["SCO_DT_REQ_PAYMENT", "Primer pago solicitado"],
          ["SCO_AMT_QUOTAS", "Importe de la cuota"],
        ],
        RETRIBUCION_SQL.prestamos,
      ),
      form({
        id: "simulacion",
        title: "Simulación del préstamo",
        description:
          "Introduce primero la fecha de solicitud y el tipo de préstamo para obtener su interés; después el capital y el importe de la cuota o el número de cuotas. El cálculo lo resuelve Meta4.",
        fields: [
          date("SCO_DT_APPLICATION", "Fecha de solicitud", { required: true }),
          pendingSelect("SCO_ID_LOAN", "Tipo de préstamo", "SSE_LOANS!SCO_LOAN", {
            required: true,
          }),
          { name: "RATE", label: "Cambiar interés (%)", type: "number", min: 0, maxLength: 4 },
          { name: "SCO_AMT_LOAN", label: "Capital", type: "number", required: true, min: 0 },
          {
            name: "ID_CURRENCY",
            label: "Moneda",
            type: "select",
            options: { kind: "catalog", catalog: "currency" },
          },
          staticSelect(
            "QUOTAS",
            "Calcular por",
            [
              { value: "Primero", label: "Importe de la cuota" },
              { value: "Segundo", label: "Número de cuotas" },
            ],
            { required: true },
          ),
          {
            name: "SCO_QUOTAS",
            label: "Importe de la cuota o número de cuotas",
            type: "number",
            required: true,
            min: 0,
          },
          {
            name: "NUM_PER_YEAR",
            label: "Número de cuotas por año",
            type: "number",
            required: true,
            min: 1,
            max: 99,
          },
        ],
        write: methodWrite(
          "simulacion",
          "Simular",
          "SSE_LOANS (cálculo en sse_g2_p5_sim.jsp)",
          undefined,
          ["P02", "P05"],
        ),
        mode: "query",
      }),
      form({
        id: "solicitud",
        title: "Solicitud de préstamo",
        fields: [
          date("SCO_DT_APPLICATION", "Fecha de solicitud", { required: true }),
          pendingSelect("SCO_ID_LOAN", "Tipo de préstamo", "SSE_LOANS!SCO_LOAN", {
            required: true,
          }),
          pendingSelect("SCO_ID_REASON", "Motivo del préstamo", "SSE_LOANS!SCO_REASON", {
            required: true,
          }),
          pendingSelect("SCO_ID_PAY_OFF_FREQ", "Tipo de frecuencia", "SSE_LOANS!SCO_PAY_OFF_FREQ", {
            required: true,
          }),
          { name: "SCO_AMT_LOAN", label: "Capital", type: "number", required: true, min: 0 },
          {
            name: "ID_CURRENCY",
            label: "Moneda",
            type: "select",
            options: { kind: "catalog", catalog: "currency" },
          },
          date("SCO_DT_FIRST_PAY", "Fecha solicitada del primer pago", { required: true }),
          {
            name: "SCO_AMT_QUOTA",
            label: "Importe de la cuota",
            type: "number",
            required: true,
            min: 0,
          },
        ],
        rules: [
          {
            kind: "dateOrder",
            start: "SCO_DT_APPLICATION",
            end: "SCO_DT_FIRST_PAY",
            message: "El primer pago no puede ser anterior a la solicitud.",
          },
        ],
        write: genericWrite(
          "solicitud",
          "Solicitar préstamo",
          "SSE_LOANS",
          "INSERTAR",
          "SSE_LOANS",
        ),
      }),
    ],
  },
  {
    id: "empleado.retribucion.beneficios",
    profile: "empleado",
    domain: "retribucion",
    title: "Retribución flexible y beneficios",
    summary:
      "Planes y beneficios actuales, selección y simulación, solicitud, cambios, historial y anexo.",
    icon: "benefit",
    route: `${base}/beneficios`,
    sources: [
      "sse_g2/sse_g2_p6.jsp",
      "sse_g2/sse_g2_p6_det.jsp",
      "sse_g2/sse_g2_p6_prf.jsp",
      "sse_g2/sse_g2_p7.jsp",
      "sse_g2/sse_g2_p7_det.jsp",
      "sse_g2/sse_g2_p7_det2.jsp",
      "sse_g2/sse_g2_p7_sim.jsp",
      "sse_g2/sse_g2_p7_act.jsp",
      "sse_g2/sse_g2_p8.jsp",
      "sse_g2/sse_g2_p8_act.jsp",
      "sse_g2/sse_g2_p9.jsp",
      "sse_g2/sse_g2_p11.jsp",
    ],
    ficha: `${RET}/sse_g2--sse_g2_p7.md`,
    keywords: ["beneficios", "retribución flexible", "seguro médico", "cobertura"],
    sensitive: true,
    read: sqlRead(RETRIBUCION_SQL.beneficios.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "actuales",
        "Mis beneficios",
        "SSE_BFT_H_EE_IN_BNFT!M4T_H_EE_IN_BNFT",
        "list",
        [
          ["SUS_N_OPTION", "Beneficio"],
          ["SUS_N_PLAN", "Plan"],
          ["SUS_DT_START", "Inicio"],
          ["SUS_DT_END", "Fin"],
          ["SUS_PRICE", "Coste empleado"],
          ["SUS_ER_CONTR", "Coste empresa"],
        ],
        RETRIBUCION_SQL.beneficios,
      ),
      note(
        "Selección de beneficios",
        "La selección marca y bloquea los beneficios obligatorios o «core» del plan; la cobertura familiar se elige por persona dependiente (SSE_DEP_BENE_COV) con fechas de inicio y fin. La simulación no es un beneficio contratado.",
      ),
      form({
        id: "baja-beneficio",
        title: "Modificar o dar de baja un beneficio",
        fields: [
          pendingSelect("SCO_ID_BENEFIT", "Beneficio", "SSE_BFT_H_EE_IN_BNFT_MOD!SCO_BENEFIT", {
            required: true,
          }),
          date("SSE_DT_END", "Fecha de fin", { required: true }),
        ],
        write: genericWrite(
          "baja-beneficio",
          "Enviar petición",
          "SSE_BFT_H_EE_IN_BNFT_MOD",
          "INSERTAR",
          "SSE_H_EE_IN_BNFT_MOD",
        ),
      }),
    ],
    writes: [
      genericWrite(
        "seleccion",
        "Solicitar beneficios seleccionados",
        "SSE_BFT_EE_BNFT_ELEC",
        "INSERTAR",
        "SSE_BFT_EE_BNFT_ELEC",
      ),
      genericWrite(
        "cobertura",
        "Solicitar cobertura de dependientes",
        "SSE_BFT_DEP_BENE_COV",
        "INSERTAR",
        "SSE_DEP_BENE_COV",
      ),
      methodWrite(
        "anexo",
        "Generar anexo al Plan de retribución flexible",
        "SSP_RP_ANEXO_BNFT (informe)",
        undefined,
        ["P08"],
      ),
    ],
  },
  {
    id: "empleado.retribucion.paquete",
    profile: "empleado",
    domain: "retribucion",
    title: "Datos salariales",
    summary:
      "Tu retribución fija y variable, jornada y beneficios (teórico y real en jornada parcial).",
    icon: "package",
    route: `${base}/paquete`,
    sources: ["sse_g2/sse_g2_p10.jsp"],
    ficha: `${RET}/sse_g2--sse_g2_p10.md`,
    keywords: ["salario", "retribución", "fijo", "variable", "paquete"],
    sensitive: true,
    read: sqlRead(RETRIBUCION_SQL.paquete.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "salario",
        "Datos salariales",
        "SSE_H_SAL_DATA!SSE_H_SAL_DATA",
        "record",
        [
          ["SCO_FIX_SALARY", "Salario fijo"],
          ["SCO_FIX_SALARY_REAL", "Salario fijo real (jornada)"],
          ["SCO_VAR_SALARY", "Salario variable"],
          ["SCO_VAR_SALARY_REAL", "Salario variable real (jornada)"],
          ["SCO_VAR_SALARY_PER", "% variable"],
          ["SCO_BNFT_LEG_ENT", "Beneficios"],
          ["ID_CURRENCY", "Moneda"],
          ["SCO_DT_START", "Desde"],
        ],
        RETRIBUCION_SQL.paquete,
      ),
    ],
  },
];
