import type { PortalFeature } from "../types";
import {
  ADDRESS_FIELDS,
  area,
  check,
  consult,
  date,
  form,
  genericWrite,
  methodWrite,
  note,
  pendingSelect,
  sqlConsult,
  sqlRead,
  text,
} from "./helpers";
import { DATOS_SQL, PROFESIONALES_SQL } from "./sql/datos";

const DATOS = "empleado/datos";
const base = "/portal/empleado/datos";

export const EMPLEADO_DATOS: readonly PortalFeature[] = [
  {
    id: "empleado.datos.ficha",
    profile: "empleado",
    domain: "datos",
    title: "Mi ficha",
    summary: "Tus datos de empresa, puesto, unidad, centro y contacto, como el dossier del portal.",
    icon: "id-card",
    route: base,
    sources: ["sse_g1/sse_g1_p1.jsp", "sse_g1/sse_g1_p1_min.jsp", "sse_g1/sse_g1_menu.jsp"],
    ficha: `${DATOS}/sse_g1--sse_g1_p1.md`,
    keywords: ["dossier", "quién es quién", "datos personales", "puesto", "centro"],
    sensitive: true,
    read: { kind: "sql", tables: ["M4ORO_EMPLEADOS", "STD_EMAIL"], verified: true },
    view: "my-file",
    variants: {
      CYC: "Dossier corporativo CSP_QUIEN_ES_QUIEN: ficha detallada, organización, cuentas, beneficiario, direcciones, correos, responsable, IRPF y puesto.",
      IBER: "Dossier estándar con SSE_ADDRESS y apartados de datos personales.",
      COLL: "Dossier estándar con SSE_ADDRESS y apartados de datos personales.",
    },
    sections: [
      consult(
        "dossier-cyc",
        "Datos de pago y cuentas",
        "CSP_QUIEN_ES_QUIEN!CSP_DATOS_PAGO_EMPLEADO",
        "list",
        [
          ["SCO_GB_IBAN", "IBAN"],
          ["SCO_DT_START", "Inicio"],
          ["SCO_OR_HR_PERIOD", "Periodo de contrato"],
        ],
        "Cuentas de cobro vigentes en PeopleNet; pueden existir varias asignaciones. La equivalencia con el dossier se contrasta en la VM.",
        "own-payment-accounts",
      ),
      sqlConsult(
        "beneficiario",
        "Cuenta del beneficiario",
        "CSP_QUIEN_ES_QUIEN!CSP_CUENTA_BENEFICIARIO",
        "list",
        [["SCO_GB_IBAN", "IBAN"]],
        DATOS_SQL.beneficiario,
      ),
      sqlConsult(
        "dossier-irpf",
        "IRPF y familia",
        "CSP_QUIEN_ES_QUIEN!CSP_FAM_IRPF",
        "list",
        [
          ["NOMBRECOMPLETO", "Nombre"],
          ["STD_DT_BIRTH", "Fecha de nacimiento"],
          ["STD_N_ACT_DEP_TYPE", "Parentesco"],
        ],
        DATOS_SQL.famIrpf,
      ),
      sqlConsult(
        "grupo-nivel",
        "Grupo y nivel",
        "CSP_QUIEN_ES_QUIEN!CSP_GRUPO_NIVEL",
        "record",
        [["SSP_NM_CATEGORIA", "Grupo y nivel"]],
        DATOS_SQL.grupoNivel,
      ),
      consult(
        "correos",
        "Correos electrónicos",
        "STD_EMAIL",
        "list",
        [
          ["STD_EMAIL", "Correo"],
          ["STD_DT_START", "Inicio"],
          ["STD_DT_END", "Fin"],
          ["STD_ID_LOCAT_TYPE", "Tipo de lugar"],
        ],
        undefined,
        "own-emails",
      ),
    ],
  },
  {
    id: "empleado.datos.direccion-fiscal",
    profile: "empleado",
    domain: "datos",
    title: "Dirección fiscal",
    summary: "Consulta tu dirección fiscal y prepara la petición de cambio.",
    icon: "address",
    route: `${base}/direccion-fiscal`,
    sources: ["sse_g1/sse_g1_p1_mod.jsp", "sse_g1/cod_postal.jsp"],
    ficha: `${DATOS}/sse_g1--sse_g1_p1_mod.md`,
    keywords: ["domicilio", "dirección", "código postal"],
    sensitive: true,
    read: sqlRead(DATOS_SQL.direccionFiscal.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "actual",
        "Dirección fiscal actual",
        "SSE_ADDRESS!M4T_ADDRESS",
        "record",
        [
          ["STD_ADDRESS_LINE_1", "Vía pública"],
          ["SSP_NUM_VIA", "Número"],
          ["SSP_BLOQUE", "Bloque"],
          ["SSP_PISO", "Piso"],
          ["SSP_ESCALERA", "Escalera"],
          ["SSP_PUERTA", "Puerta"],
          ["SSP_DISTRIT_POSTAL", "Código postal"],
          ["STD_N_GEO_PLACE", "Población"],
          ["STD_N_SUB_GEO_DIV", "Provincia"],
          ["STD_N_COUNTRY", "País"],
        ],
        DATOS_SQL.direccionFiscal,
      ),
      form({
        id: "direccion-fiscal",
        title: "Modifica tu dirección",
        description:
          "Los campos marcados son obligatorios. País, comunidad, provincia y población se obtienen del código postal.",
        fields: [
          ...ADDRESS_FIELDS,
          text("STD_N_COUNTRY", "País", { help: "Se completa desde el código postal." }),
          text("STD_N_GEO_DIV", "Comunidad", { help: "Se completa desde el código postal." }),
          text("STD_N_SUB_GEO_DIV", "Provincia", { help: "Se completa desde el código postal." }),
          text("STD_N_GEO_PLACE", "Población", { help: "Se completa desde el código postal." }),
        ],
        write: genericWrite(
          "direccion-fiscal",
          "Enviar petición de cambio",
          "SSE_ADDRESS",
          "INSERTAR",
          "SSE_ADDRESS",
        ),
        notice:
          "Si no encuentras tu código postal, ponte en contacto con Recursos Humanos para darlo de alta.",
      }),
    ],
  },
  {
    id: "empleado.datos.correo",
    profile: "empleado",
    domain: "datos",
    title: "Correo personal",
    summary: "Tus direcciones de correo y la petición de alta de un correo personal.",
    icon: "mail",
    route: `${base}/correo`,
    sources: ["sse_g1/sse_g1_p1_mod2.jsp"],
    ficha: `${DATOS}/sse_g1--sse_g1_p1_mod2.md`,
    keywords: ["email", "correo electrónico"],
    sensitive: true,
    read: { kind: "sql", tables: ["STD_EMAIL"], verified: true },
    view: "generic",
    sections: [
      consult(
        "correos",
        "Correos electrónicos",
        "STD_EMAIL",
        "list",
        [
          ["STD_EMAIL", "Correo"],
          ["STD_DT_START", "Inicio"],
          ["STD_DT_END", "Fin"],
          ["STD_ID_LOCAT_TYPE", "Tipo de lugar"],
        ],
        undefined,
        "own-emails",
      ),
      form({
        id: "correo",
        title: "Nuevo correo personal",
        description: "Da de alta o modifica tu dirección de correo electrónico personal.",
        fields: [
          {
            name: "STD_EMAIL",
            label: "Nuevo correo personal",
            type: "email",
            required: true,
            maxLength: 40,
          },
        ],
        write: genericWrite("correo", "Enviar petición", "SSE_E_MAIL", "INSERTAR", "SSE_E_MAIL"),
      }),
    ],
  },
  {
    id: "empleado.datos.telefonos",
    profile: "empleado",
    domain: "datos",
    title: "Teléfonos",
    summary: "Tus teléfonos y la petición de alta o cambio.",
    icon: "phone",
    route: `${base}/telefonos`,
    sources: ["sse_g1/sse_g1_p1_mod3.jsp"],
    ficha: `${DATOS}/sse_g1--sse_g1_p1_mod3.md`,
    keywords: ["teléfono", "móvil"],
    sensitive: true,
    read: sqlRead(DATOS_SQL.telefonos.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "telefonos",
        "Teléfonos",
        "SSE_PHONE_FAX!M4T_PHONE_FAX",
        "list",
        [
          ["STD_PHONE", "Teléfono"],
          ["STD_N_LINE_TYPE", "Tipo de línea"],
          ["STD_N_LOCATION_TYPE", "Lugar"],
        ],
        DATOS_SQL.telefonos,
      ),
      form({
        id: "telefono",
        title: "Número de teléfono",
        fields: [
          text("STD_PHONE", "Teléfono", {
            required: true,
            maxLength: 11,
            help: "Hasta 11 caracteres.",
          }),
          pendingSelect("STD_ID_LINE_TYPE", "Tipo de línea", "SSE_PHONE_FAX!STD_LU_LINE_TYPE"),
        ],
        write: genericWrite(
          "telefono",
          "Enviar petición",
          "SSE_PHONE_FAX",
          "INSERTAR",
          "SSE_PHONE_FAX",
        ),
      }),
    ],
  },
  {
    id: "empleado.datos.otras-direcciones",
    profile: "empleado",
    domain: "datos",
    title: "Otras direcciones",
    summary: "Domicilios distintos del fiscal y la petición de alta o cambio.",
    icon: "address",
    route: `${base}/otras-direcciones`,
    sources: ["sse_g1/sse_g1_p1_mod4.jsp"],
    ficha: `${DATOS}/sse_g1--sse_g1_p1_mod4.md`,
    keywords: ["domicilio", "dirección postal"],
    sensitive: true,
    read: sqlRead(DATOS_SQL.otrasDirecciones.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "otras",
        "Otros domicilios",
        "SSE_ADDRESS_OTROS!M4T_ADDRESS_OTROS",
        "list",
        [
          ["STD_N_LOCATION_TYPE", "Tipo"],
          ["STD_ADDRESS_LINE_1", "Vía pública"],
          ["SSP_NUM_VIA", "Número"],
          ["SSP_BLOQUE", "Bloque"],
          ["SSP_PISO", "Piso"],
          ["SSP_ESCALERA", "Escalera"],
          ["SSP_PUERTA", "Puerta"],
          ["SSP_DISTRIT_POSTAL", "Código postal"],
          ["STD_N_GEO_PLACE", "Población"],
          ["STD_N_SUB_GEO_DIV", "Provincia"],
          ["STD_N_GEO_DIV", "Comunidad"],
          ["STD_N_COUNTRY", "País"],
        ],
        DATOS_SQL.otrasDirecciones,
      ),
      form({
        id: "otra-direccion",
        title: "Dirección",
        fields: [
          {
            name: "STD_ID_LOCATION_TYPE",
            label: "Tipo de dirección",
            type: "select",
            required: true,
            options: { kind: "catalog", catalog: "locationType" },
          },
          ...ADDRESS_FIELDS,
          {
            name: "STD_ID_COUNTRY",
            label: "País",
            type: "select",
            options: { kind: "catalog", catalog: "country" },
          },
          {
            name: "STD_ID_GEO_DIV",
            label: "Comunidad",
            type: "select",
            options: { kind: "catalog", catalog: "community" },
          },
          {
            name: "STD_ID_SUB_GEO_DIV",
            label: "Provincia",
            type: "select",
            options: { kind: "catalog", catalog: "province" },
          },
          text("STD_ID_GEO_PLACE", "Población", {
            required: true,
            help: "La población debe pertenecer a la provincia elegida.",
          }),
        ],
        write: genericWrite(
          "otra-direccion",
          "Enviar petición",
          "SSE_ADDRESS_OTROS",
          "INSERTAR",
          "SSE_ADDRESS_OTROS",
        ),
      }),
    ],
  },
  {
    id: "empleado.datos.teletrabajo",
    profile: "empleado",
    domain: "datos",
    title: "Domicilio de teletrabajo",
    summary: "Da de alta o modifica el domicilio desde el que teletrabajas.",
    icon: "address",
    route: `${base}/teletrabajo`,
    sources: ["sse_g1/sse_g1_p1_mod_da.jsp"],
    ficha: `${DATOS}/sse_g1--sse_g1_p1_mod_da.md`,
    keywords: ["teletrabajo", "remoto", "domicilio"],
    sensitive: true,
    availableIn: ["CYC", "IBER", "COLL"],
    read: sqlRead(DATOS_SQL.teletrabajo.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "actual",
        "Domicilio de teletrabajo actual",
        "SSE_ADDRESS_OTROS!M4T_ADDRESS_OTROS",
        "record",
        [
          ["STD_ADDRESS_LINE_1", "Vía pública"],
          ["SSP_NUM_VIA", "Número"],
          ["SSP_BLOQUE", "Bloque"],
          ["SSP_PISO", "Piso"],
          ["SSP_ESCALERA", "Escalera"],
          ["SSP_PUERTA", "Puerta"],
          ["SSP_DISTRIT_POSTAL", "Código postal"],
          ["STD_N_COUNTRY", "País"],
          ["STD_N_GEO_DIV", "Comunidad"],
          ["STD_N_SUB_GEO_DIV", "Provincia"],
          ["STD_N_GEO_PLACE", "Población"],
        ],
        DATOS_SQL.teletrabajo,
      ),
      form({
        id: "teletrabajo",
        title: "Domicilio de teletrabajo",
        fields: [...ADDRESS_FIELDS, text("STD_N_GEO_PLACE", "Población", { required: true })],
        write: genericWrite(
          "teletrabajo",
          "Enviar petición",
          "SSE_ADDRESS_OTROS",
          "INSERTAR",
          "SSE_ADDRESS_OTROS",
        ),
        notice:
          "Si no encuentras tu código postal, ponte en contacto con Recursos Humanos para darlo de alta.",
      }),
    ],
  },
  {
    id: "empleado.datos.estado-civil",
    profile: "empleado",
    domain: "datos",
    title: "Estado civil",
    summary: "Tu estado civil vigente y la petición de cambio con fecha de inicio.",
    icon: "family",
    route: `${base}/estado-civil`,
    sources: ["sse_g1/sse_g1_p1_mod5.jsp", "sse_g1/ssco_g1_p1_mod5.jsp"],
    ficha: `${DATOS}/sse_g1--ssco_g1_p1_mod5.md`,
    sensitive: true,
    read: sqlRead(DATOS_SQL.estadoCivil.tables),
    view: "generic",
    sections: [
      consult(
        "actual-oro",
        "Estado civil en la ficha actual",
        "M4ORO_EMPLEADOS",
        "record",
        [["ID_ESTADO_CIVIL", "Código de estado civil"]],
        "Código registrado en ORO.",
        "own-oro-status",
      ),
      sqlConsult(
        "historico",
        "Estado civil",
        "SSE_HT_MAR_STAT!M4T_HT_MAR_STAT",
        "list",
        [
          ["STD_N_MARITAL_STAT", "Estado civil"],
          ["STD_DT_START", "Fecha de inicio"],
          ["STD_DT_END", "Fin"],
        ],
        DATOS_SQL.estadoCivil,
      ),
      form({
        id: "estado-civil",
        title: "Cambiar estado civil",
        fields: [
          date("STD_DT_START", "Fecha de inicio", { required: true }),
          {
            name: "STD_ID_MARITAL_STAT",
            label: "Estado civil",
            type: "select",
            required: true,
            options: { kind: "catalog", catalog: "maritalStatus" },
          },
        ],
        write: genericWrite(
          "estado-civil",
          "Enviar petición",
          "SSE_HT_MAR_STAT",
          "INSERTAR",
          "SSE_HT_MAR_STAT",
        ),
      }),
    ],
  },
  {
    id: "empleado.datos.pagina-web",
    profile: "empleado",
    domain: "datos",
    title: "Página web",
    summary: "Tu página web personal.",
    icon: "link",
    route: `${base}/pagina-web`,
    sources: ["sse_g1/sse_g1_p1_mod6.jsp", "sse_g1/ssco_g1_p1_mod6.jsp"],
    ficha: `${DATOS}/sse_g1--ssco_g1_p1_mod6.md`,
    sensitive: false,
    read: sqlRead(DATOS_SQL.paginaWeb.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "actual",
        "Página web actual",
        "SSE_HOME_PAGE!M4T_HOME_PAGE",
        "record",
        [["SCO_HOME_PAGE", "Página web"]],
        DATOS_SQL.paginaWeb,
      ),
      form({
        id: "pagina-web",
        title: "Página web",
        fields: [text("SCO_HOME_PAGE", "Página web", { required: true, maxLength: 254, span: 2 })],
        write: genericWrite(
          "pagina-web",
          "Enviar petición",
          "SSE_HOME_PAGE",
          "INSERTAR",
          "SSE_HOME_PAGE",
        ),
      }),
    ],
  },
  {
    id: "empleado.datos.otras-formas-contacto",
    profile: "empleado",
    domain: "datos",
    title: "Otras formas de contacto",
    summary: "Otros medios de contacto con su tipo.",
    icon: "contact",
    route: `${base}/otras-formas-contacto`,
    sources: ["sse_g1/ssco_g1_p1_mod7.jsp"],
    ficha: `${DATOS}/sse_g1--ssco_g1_p1_mod7.md`,
    sensitive: true,
    read: sqlRead(DATOS_SQL.otrasFormasContacto.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "actuales",
        "Formas de contacto actuales",
        "SSE_OTH_CONTACT_FORMS!M4T_OTH_CONTACT_FORMS",
        "list",
        [
          ["SCO_N_CONTACT_TYPE", "Tipo"],
          ["SCO_CONTACTO", "Contacto"],
          ["SCO_DT_START", "Inicio"],
        ],
        DATOS_SQL.otrasFormasContacto,
      ),
      form({
        id: "otra-forma-contacto",
        title: "Nueva forma de contacto",
        fields: [
          text("SCO_CONTACTO", "Contacto", { required: true }),
          pendingSelect(
            "SCO_ID_CONTACT_TYPE",
            "Tipo de contacto",
            "SSE_OTH_CONTACT_FORMS!SCO_CONTACT_TYPE",
            { required: true },
          ),
        ],
        write: genericWrite(
          "otra-forma-contacto",
          "Enviar petición",
          "SSE_OTH_CONTACT_FORMS",
          "INSERTAR",
          "SSE_OTH_CONTACT_FORMS",
        ),
      }),
    ],
  },
  {
    id: "empleado.datos.profesionales",
    profile: "empleado",
    domain: "datos",
    title: "Datos profesionales",
    summary:
      "Titulaciones, idiomas, experiencia, certificados, otros cursos, asociaciones e información complementaria.",
    icon: "career",
    route: `${base}/profesionales`,
    sources: [
      "sse_g1/sse_g1_p3.jsp",
      "sse_g1/sse_g1_p3_mod.jsp",
      "sse_g1/sse_g1_p3_mod2.jsp",
      "sse_g1/sse_g1_p3_mod3.jsp",
      "sse_g1/ssco_g1_p3_mod4.jsp",
      "sse_g1/ssco_g1_p3_mod5.jsp",
      "sse_g1/ssco_g1_p3_mod6.jsp",
      "sse_g1/ssco_g1_p3_mod7.jsp",
    ],
    ficha: `${DATOS}/sse_g1--sse_g1_p3.md`,
    keywords: ["currículo", "titulación", "idiomas", "experiencia", "certificados", "cursos"],
    sensitive: true,
    read: sqlRead([...new Set(Object.values(PROFESIONALES_SQL).flatMap((query) => query.tables))]),
    view: "generic",
    variants: { CYC: "Idiomas añade puntuación TOEIC (CSP_TOEIC) y su fecha." },
    sections: [
      sqlConsult(
        "titulaciones",
        "Titulaciones",
        "SSE_EMP_BACKGROUND!M4T_EMP_BACKGROUND",
        "list",
        [
          ["STD_N_DIPLOMA", "Titulación"],
          ["STD_N_EDU_SP", "Especialidad"],
          ["STD_DESC_EDU_CENTER", "Centro"],
          ["STD_DT_EARNED_EXPE", "Fecha de obtención"],
        ],
        PROFESIONALES_SQL.titulaciones,
      ),
      sqlConsult(
        "idiomas",
        "Idiomas",
        "SSE_EMP_LANGUAGES!M4T_EMP_LANGUAGES",
        "list",
        [
          ["STD_N_LANGUAGE", "Idioma"],
          ["STD_N_SPEAK_LEVEL", "Hablado"],
          ["STD_N_LISTEN_LEVEL", "Comprensión"],
          ["STD_N_WRITE_LEVEL", "Escrito"],
        ],
        PROFESIONALES_SQL.idiomas,
      ),
      sqlConsult(
        "experiencia",
        "Experiencia profesional",
        "SSE_EMP_PREV_JOBS!M4T_EMP_PREV_JOBS",
        "list",
        [
          ["STD_EMPLOYER", "Empresa"],
          ["STD_FINAL_JOB", "Puesto"],
          ["STD_DT_START", "Inicio"],
          ["STD_DT_END", "Fin"],
        ],
        PROFESIONALES_SQL.experiencia,
      ),
      sqlConsult(
        "certificados",
        "Certificados y licencias",
        "SSE_CERTIFICATION_LICEN!M4T_CERTIFICATION_LICEN",
        "list",
        [
          ["SCO_N_CERTIF", "Certificado"],
          ["STD_N_CERTIF_TYPE", "Tipo"],
          ["SCO_DT_ISSUE", "Expedición"],
          ["SCO_DT_EXPIRED", "Caducidad"],
        ],
        PROFESIONALES_SQL.certificados,
      ),
      sqlConsult(
        "otros-cursos",
        "Otros cursos",
        "SSE_HR_COMP_BACKGROUND!M4T_HR_COMP_BACKGROUND",
        "list",
        [
          ["SCO_N_COURSE", "Curso"],
          ["SCO_N_CENTER", "Centro"],
          ["SCO_NUMBER_HOURS", "Horas"],
          ["SCO_DT_START", "Inicio"],
          ["SCO_DT_END", "Fin"],
        ],
        PROFESIONALES_SQL.otrosCursos,
      ),
      sqlConsult(
        "asociaciones",
        "Asociaciones",
        "SSE_ASSOCIATION_ME!M4T_ASSOCIATION_ME",
        "list",
        [
          ["SCO_N_ASSOCIATION", "Asociación"],
          ["SCO_NM_POSITION", "Cargo"],
          ["SCO_DT_START", "Inicio"],
          ["SCO_DT_END", "Fin"],
        ],
        PROFESIONALES_SQL.asociaciones,
      ),
      sqlConsult(
        "informacion-complementaria",
        "Información complementaria",
        "SSE_HR_COMP_INFORMATION!M4T_HR_COMP_INFORMATION",
        "record",
        [
          ["SCO_CK_TRAVEL_DISP", "Disponibilidad para viajar"],
          ["SCO_CK_MOV_NAC", "Movilidad nacional"],
          ["SCO_CK_MOV_INTER", "Movilidad internacional"],
          ["SCO_HOBBIES", "Aficiones"],
          ["SCO_OTHERS", "Otros"],
        ],
        PROFESIONALES_SQL.complementaria,
      ),
      form({
        id: "titulacion",
        title: "Titulación",
        fields: [
          date("STD_DT_START", "Fecha de inicio", { required: true }),
          date("STD_DT_EARNED_EXPE", "Fecha de obtención"),
          pendingSelect("STD_ID_DIPLOMA", "Tipo de diploma", "SSE_EMP_BACKGROUND!STD_DIPLOMA", {
            required: true,
          }),
          pendingSelect("STD_ID_EDU_TYPE", "Titulación", "SSE_EMP_BACKGROUND!STD_EDU_TYPE", {
            required: true,
          }),
          pendingSelect("STD_ID_EDU_SP", "Especialidad", "SSE_EMP_BACKGROUND!STD_EDU_SP"),
          pendingSelect("STD_ID_EDU_CENTER", "Centro", "SSE_EMP_BACKGROUND!STD_EDU_CENTER", {
            required: true,
          }),
          area("STD_COMMENT", "Descripción", { maxLength: 1000 }),
        ],
        rules: [
          {
            kind: "dateOrder",
            start: "STD_DT_START",
            end: "STD_DT_EARNED_EXPE",
            message: "La fecha de inicio debe ser anterior o igual a la de obtención.",
          },
        ],
        write: genericWrite(
          "titulacion",
          "Enviar petición",
          "SSE_EMP_BACKGROUND",
          "INSERTAR",
          "SSE_EMP_BACKGROUND",
        ),
      }),
      form({
        id: "idioma",
        title: "Idiomas",
        fields: [
          pendingSelect("STD_ID_LANGUAGE", "Idioma", "SSE_EMP_LANGUAGES!STD_LANGUAGE", {
            required: true,
          }),
          pendingSelect("STD_ID_SPEAK_LEVEL", "Nivel", "SSE_EMP_LANGUAGES!STD_LANG_LEVEL"),
          text("CSP_TOEIC", "TOEIC", { maxLength: 4 }),
          date("CSP_FECHA_TOEIC", "Fecha TOEIC"),
        ],
        write: genericWrite(
          "idioma",
          "Enviar petición",
          "SSE_EMP_LANGUAGES",
          "INSERTAR",
          "SSE_EMP_LANGUAGES",
        ),
      }),
      form({
        id: "experiencia",
        title: "Experiencia profesional",
        fields: [
          date("STD_DT_START", "Fecha de inicio", { required: true }),
          date("STD_DT_END", "Fecha de fin"),
          pendingSelect("STD_ID_SECTOR", "Sector", "SSE_EMP_PREV_JOBS!STD_SECTOR", {
            required: true,
          }),
          text("STD_EMPLOYER", "Empresa", { maxLength: 62 }),
          pendingSelect("SCO_ID_AREA", "Área", "SSE_EMP_PREV_JOBS!SCO_AREA"),
          {
            name: "STD_ID_COUNTRY",
            label: "País",
            type: "select",
            options: { kind: "catalog", catalog: "country" },
          },
          text("STD_INITIAL_JOB", "Puesto", { span: 2 }),
          area("STD_DEVELOPED_ACTIVITIES", "Actividades desarrolladas", { maxLength: 1000 }),
        ],
        rules: [
          {
            kind: "dateOrder",
            start: "STD_DT_START",
            end: "STD_DT_END",
            message: "La fecha de inicio debe ser anterior o igual a la de fin.",
          },
        ],
        write: genericWrite(
          "experiencia",
          "Enviar petición",
          "SSE_EMP_PREV_JOBS",
          "INSERTAR",
          "SSE_EMP_PREV_JOBS",
        ),
      }),
      form({
        id: "certificado",
        title: "Certificados y licencias",
        fields: [
          date("SCO_DT_ISSUE", "Fecha de emisión", { required: true }),
          date("SCO_DT_EXPIRED", "Fecha de validez"),
          text("SCO_N_CERTIF", "Certificado", { required: true, span: 2 }),
          pendingSelect(
            "SCO_ID_CERTIF_TYPE",
            "Tipo de certificado",
            "SSE_CERTIFICATION_LICEN!SCO_CERTIF_TYPE",
            { required: true },
          ),
          text("SCO_CERT_NUMBER", "Número"),
          pendingSelect(
            "SCO_ID_ISSUE_ENTIT",
            "Entidad emisora",
            "SSE_CERTIFICATION_LICEN!SCO_ISSUE_ENTIT",
          ),
          {
            name: "SCO_ID_COUNTRY",
            label: "País",
            type: "select",
            options: { kind: "catalog", catalog: "country" },
          },
        ],
        rules: [
          {
            kind: "dateOrder",
            start: "SCO_DT_ISSUE",
            end: "SCO_DT_EXPIRED",
            message: "La fecha de emisión tiene que ser menor o igual a la fecha de validez.",
          },
        ],
        write: genericWrite(
          "certificado",
          "Enviar petición",
          "SSE_CERTIFICATION_LICEN",
          "INSERTAR",
          "SSE_CERTIFICATION_LICEN",
        ),
      }),
      form({
        id: "otros-cursos",
        title: "Otros cursos",
        description: "Indica tu formación externa.",
        fields: [
          date("SCO_DT_START", "Fecha de inicio", { required: true }),
          date("SCO_DT_END", "Fecha de fin"),
          text("SCO_N_COURSE", "Curso", { required: true, span: 2 }),
          { name: "SCO_NUMBER_HOURS", label: "Horas", type: "number", min: 0 },
          text("SCO_N_CENTER", "Centro"),
          {
            name: "STD_ID_COUNTRY",
            label: "País",
            type: "select",
            options: { kind: "catalog", catalog: "country" },
          },
          area("SCO_COMMENT", "Comentario"),
        ],
        rules: [
          {
            kind: "dateOrder",
            start: "SCO_DT_START",
            end: "SCO_DT_END",
            message: "La fecha de inicio debe ser anterior o igual a la de fin.",
          },
        ],
        write: genericWrite(
          "otros-cursos",
          "Enviar petición",
          "SSE_HR_COMP_BACKGROUND",
          "INSERTAR",
          "SSE_HR_COMP_BACKGROUND",
        ),
      }),
      form({
        id: "asociacion",
        title: "Asociaciones",
        fields: [
          date("SCO_DT_START", "Fecha de inicio", { required: true }),
          date("SCO_DT_END", "Fecha de fin"),
          pendingSelect(
            "SCO_ID_ASSOC_TYPE",
            "Tipo de asociación",
            "SSE_ASSOCIATION_ME!SCO_ASSOC_TYPE",
            { required: true },
          ),
          pendingSelect("SCO_ID_ASSOCIATION", "Asociación", "SSE_ASSOCIATION_ME!SCO_ASSOCIATION", {
            required: true,
          }),
          text("SCO_N_ACTIVITY", "Actividad"),
          text("SCO_NM_POSITION", "Cargo"),
        ],
        rules: [
          {
            kind: "dateOrder",
            start: "SCO_DT_START",
            end: "SCO_DT_END",
            message: "La fecha de inicio debe ser anterior o igual a la de fin.",
          },
        ],
        write: genericWrite(
          "asociacion",
          "Enviar petición",
          "SSE_ASSOCIATION_ME",
          "INSERTAR",
          "SSE_ASSOCIATION_ME",
        ),
      }),
      form({
        id: "complementaria",
        title: "Información complementaria",
        fields: [
          check("SCO_CK_MOV_INTERA", "Movilidad internacional"),
          check("SCO_CK_MOV_NACA", "Movilidad nacional"),
          check("SCO_CK_TRAVEL_DISPOA", "Disponibilidad para viajar"),
          text("SCO_OTHERS", "Otros", { span: 2 }),
          text("SCO_HOBBIES", "Aficiones", { span: 2 }),
        ],
        write: genericWrite(
          "complementaria",
          "Enviar petición",
          "SSE_HR_COMP_INFORMATION",
          "INSERTAR",
          "SSE_HR_COMP_INFORMATION",
        ),
      }),
    ],
    writes: [
      genericWrite(
        "titulacion-borrar",
        "Borrar titulación",
        "SSE_EMP_BACKGROUND",
        "BORRAR",
        "SSE_EMP_BACKGROUND",
      ),
      genericWrite(
        "idioma-borrar",
        "Borrar idioma",
        "SSE_EMP_LANGUAGES",
        "BORRAR",
        "SSE_EMP_LANGUAGES",
      ),
      genericWrite(
        "experiencia-borrar",
        "Borrar experiencia",
        "SSE_EMP_PREV_JOBS",
        "BORRAR",
        "SSE_EMP_PREV_JOBS",
      ),
      genericWrite(
        "certificado-borrar",
        "Borrar certificado",
        "SSE_CERTIFICATION_LICEN",
        "BORRAR",
        "SSE_CERTIFICATION_LICEN",
      ),
      genericWrite(
        "curso-borrar",
        "Borrar curso",
        "SSE_HR_COMP_BACKGROUND",
        "BORRAR",
        "SSE_HR_COMP_BACKGROUND",
      ),
      genericWrite(
        "asociacion-borrar",
        "Borrar asociación",
        "SSE_ASSOCIATION_ME",
        "BORRAR",
        "SSE_ASSOCIATION_ME",
      ),
      genericWrite(
        "complementaria-borrar",
        "Borrar información",
        "SSE_HR_COMP_INFORMATION",
        "BORRAR",
        "SSE_HR_COMP_INFORMATION",
      ),
    ],
  },
  {
    id: "empleado.datos.cv",
    profile: "empleado",
    domain: "datos",
    title: "Currículum",
    summary: "Informe de currículum generado por Meta4.",
    icon: "document",
    route: `${base}/cv`,
    sources: ["sse_g1/sse_g1_p3_cv.jsp"],
    ficha: `${DATOS}/sse_g1--sse_g1_p3_cv.md`,
    keywords: ["cv", "curriculum"],
    sensitive: true,
    availableIn: ["CYC", "IBER", "COLL"],
    read: sqlRead([
      ...new Set([
        ...PROFESIONALES_SQL.titulaciones.tables,
        ...PROFESIONALES_SQL.idiomas.tables,
        ...PROFESIONALES_SQL.experiencia.tables,
        ...PROFESIONALES_SQL.formacionInterna.tables,
        ...PROFESIONALES_SQL.otrosTitulos.tables,
      ]),
    ]),
    view: "generic",
    sections: [
      note(
        "Documento",
        "El PDF del CV lo genera el motor de informes de Meta4 (CSP_RP_CV) y no se puede leer por SQL. Aquí se muestran los datos que lo componen (CSP_CV).",
      ),
      sqlConsult(
        "titulaciones",
        "Titulaciones",
        "CSP_CV!CSP_TITULACION",
        "list",
        [
          ["STD_N_DIPLOMA", "Titulación"],
          ["STD_N_EDU_SP", "Especialidad"],
          ["STD_DESC_EDU_CENTER", "Centro"],
          ["STD_DT_EARNED_EXPE", "Fecha de obtención"],
        ],
        PROFESIONALES_SQL.titulaciones,
      ),
      sqlConsult(
        "otros-titulos",
        "Otros títulos",
        "CSP_CV!CSP_OTROS_TITULOS",
        "list",
        [
          ["CSP_TITULO", "Título"],
          ["DT_START", "Inicio"],
          ["DT_END", "Fin"],
        ],
        PROFESIONALES_SQL.otrosTitulos,
      ),
      sqlConsult(
        "idiomas",
        "Idiomas",
        "CSP_CV!CSP_IDIOMAS",
        "list",
        [
          ["STD_N_LANGUAGE", "Idioma"],
          ["STD_N_SPEAK_LEVEL", "Hablado"],
          ["STD_N_LISTEN_LEVEL", "Comprensión"],
          ["STD_N_WRITE_LEVEL", "Escrito"],
        ],
        PROFESIONALES_SQL.idiomas,
      ),
      sqlConsult(
        "experiencia",
        "Experiencia profesional",
        "CSP_CV!CSP_EXPERIENCIA_PROF_EXTERNA",
        "list",
        [
          ["STD_EMPLOYER", "Empresa"],
          ["STD_FINAL_JOB", "Puesto"],
          ["STD_DT_START", "Inicio"],
          ["STD_DT_END", "Fin"],
        ],
        PROFESIONALES_SQL.experiencia,
      ),
      sqlConsult(
        "formacion-interna",
        "Formación interna",
        "CSP_CV!CSP_FORMACION_INTERNA",
        "list",
        [
          ["SCO_N_COURSE", "Curso"],
          ["SCO_N_CENTER", "Centro"],
          ["SCO_NUMBER_HOURS", "Horas"],
          ["SCO_DT_START", "Inicio"],
          ["SCO_DT_END", "Fin"],
        ],
        PROFESIONALES_SQL.formacionInterna,
      ),
    ],
  },
  {
    id: "empleado.datos.irpf",
    profile: "empleado",
    domain: "datos",
    title: "IRPF y Modelo 145",
    summary: "Situación fiscal, historial, Modelo 145 y documentación que debes aportar.",
    icon: "tax",
    route: `${base}/irpf`,
    sources: [
      "sse_g1/ssco_g1_p6.jsp",
      "sse_g1/ssco_g1_p6_mod.jsp",
      "sse_g1/ssco_g1_p6_mod2.jsp",
      "sse_g1/sssp_g1_p6_sit.jsp",
      "sse_g1/sssp_g1_p6_sit_mod.jsp",
      "sse_g1/sssp_g1_p6_hist.jsp",
      "sse_g1/sssp_g1_p6_mod145.jsp",
    ],
    ficha: `${DATOS}/sse_g1--sssp_g1_p6_sit_mod.md`,
    keywords: ["irpf", "modelo 145", "retenciones", "descendientes", "ascendientes"],
    sensitive: true,
    read: sqlRead(DATOS_SQL.irpf.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "situacion",
        "Situación actual",
        "SSE_MOD_SITIRPF!SSE_DATA_DATOS_PERCEPTOR",
        "record",
        [
          ["SSP_N_EST_IRPF", "Situación familiar"],
          ["SSP_NIF_CONYUGE", "NIF del cónyuge"],
          ["SSP_N_MINUSVALIA", "Discapacidad"],
          ["SSP_NUM_HIJOS_IRPF", "Número de hijos para el IRPF"],
          ["SSP_CON_RED_VIVIENDA", "Préstamo por adquisición de vivienda habitual"],
          ["DT_START", "Desde"],
        ],
        DATOS_SQL.irpf,
        "Pensiones y anualidades solo constan en la petición de modificación, no en la situación registrada.",
      ),
      form({
        id: "situacion-irpf",
        title: "Modificar situación fiscal",
        description:
          "Es necesario que realices al menos una modificación en alguno de tus datos para el IRPF.",
        fields: [
          pendingSelect("SSP_ID_EST_IRPF", "Situación familiar", "SSE_MOD_SITIRPF!SSP_EST_IRPF", {
            required: true,
          }),
          pendingSelect(
            "SSP_ID_TP_DOC",
            "Tipo de documento del cónyuge",
            "SSE_MOD_SITIRPF!SSP_TP_DOC",
            {
              showWhen: { field: "SSP_ID_EST_IRPF", equals: ["2"] },
            },
          ),
          text("SSP_NIF_CONYUGE", "NIF del cónyuge", {
            maxLength: 9,
            showWhen: { field: "SSP_ID_EST_IRPF", equals: ["2"] },
            help: "Solo se consigna con una situación familiar «2».",
          }),
          pendingSelect("SSP_ID_MINUSVALIA", "Discapacidad", "SSE_MOD_SITIRPF!SSP_MINUSVALIA"),
          {
            name: "SSP_NUM_HIJOS_IRPF",
            label: "Número de hijos para el IRPF",
            type: "number",
            min: 0,
            max: 9,
          },
          {
            name: "SSP_PENSION_CONYUGE",
            label: "Pensión compensatoria al cónyuge",
            type: "number",
            min: 0,
          },
          {
            name: "SSP_PENSION_HIJO",
            label: "Anualidades por alimentos a hijos",
            type: "number",
            min: 0,
          },
          {
            name: "SSP_CON_RED_VIVIENDA",
            label: "Año de adquisición de la vivienda habitual",
            type: "number",
            min: 1900,
            max: 2100,
          },
        ],
        write: methodWrite(
          "situacion-irpf",
          "Enviar petición",
          "SSE_MOD_SITIRPF (sssp_g1_p6_actualizar.jsp)",
          "Descendientes y ascendientes con año de nacimiento, adopción, discapacidad y cómputo",
        ),
        notice:
          "El original añade descendientes y ascendientes por filas (año de nacimiento, adopción o acogimiento, discapacidad, cómputo por entero y convivencia).",
      }),
      form({
        id: "documento",
        title: "Aportar documentación",
        fields: [
          pendingSelect("SCO_ID_DOC_TYPE", "Tipo de documento", "SSCO_HR_DOCUMENTS!SCO_DOC_TYPE", {
            required: true,
          }),
          date("SCO_DT_EMISSION", "Fecha de emisión", { required: true }),
          check("chkdoc", "Confirmo que aporto la documentación"),
        ],
        write: genericWrite(
          "documento",
          "Enviar documentación",
          "SSCO_HR_DOCUMENTS",
          "INSERTAR",
          "SSE_HR_DOC",
        ),
      }),
      note(
        "Modelo 145",
        "El original genera el Modelo 145 con SRSP_GENERAR_MOD_145.SRSP_LOAD_FROM_ESS. El documento se ofrecerá cuando su servicio y formato estén verificados (P08).",
      ),
    ],
    writes: [
      genericWrite(
        "documento-anular",
        "Anular documento",
        "SSCO_HR_DOCUMENTS",
        "ANULAR",
        "SSE_HR_DOC",
      ),
    ],
  },
  {
    id: "empleado.datos.emergencia",
    profile: "empleado",
    domain: "datos",
    title: "Contactos de emergencia",
    summary: "Personas a las que avisar en caso de emergencia, con teléfono y prioridad.",
    icon: "emergency",
    route: `${base}/emergencia`,
    sources: ["sse_g1/sse_g1_p4.jsp", "sse_g1/sse_g1_p4_mod.jsp"],
    ficha: `${DATOS}/sse_g1--sse_g1_p4_mod.md`,
    keywords: ["emergencia", "contacto"],
    sensitive: true,
    read: sqlRead(DATOS_SQL.emergencia.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "contactos",
        "Contactos de emergencia",
        "SSE_HR_CONTACT!M4T_HR_CONTACT",
        "list",
        [
          ["STD_N_CONTACT", "Nombre"],
          ["STD_PHONE_NUMBER_1", "Teléfono"],
          ["SCO_ICE", "Prioridad"],
        ],
        DATOS_SQL.emergencia,
      ),
      form({
        id: "emergencia",
        title: "Nuevo contacto de emergencia",
        fields: [
          text("STD_N_CONTACT", "Nombre", { required: true, maxLength: 62, span: 2 }),
          text("STD_INT_COUNTRY_CODE_1", "Prefijo internacional", { maxLength: 5 }),
          text("STD_INT_REGION_CODE_1", "Prefijo regional internacional", { maxLength: 5 }),
          text("STD_NAT_REGION_CODE_1", "Prefijo nacional", { maxLength: 5 }),
          text("STD_PHONE_NUMBER_1", "Teléfono", { required: true, maxLength: 62 }),
          { name: "SCO_ICE", label: "Prioridad", type: "number", required: true, min: 1, max: 99 },
        ],
        write: genericWrite(
          "emergencia",
          "Enviar petición",
          "SSE_HR_CONTACT",
          "INSERTAR",
          "SSE_HR_CONTACT",
        ),
      }),
    ],
  },
  {
    id: "empleado.datos.dependientes",
    profile: "empleado",
    domain: "datos",
    title: "Dependientes",
    summary: "Familiares dependientes con nacimiento, periodo y tipo.",
    icon: "family",
    route: `${base}/dependientes`,
    sources: ["sse_g1/sse_g1_p5.jsp", "sse_g1/sse_g1_p5_mod.jsp"],
    ficha: `${DATOS}/sse_g1--sse_g1_p5_mod.md`,
    keywords: ["familia", "hijos", "dependientes"],
    sensitive: true,
    read: sqlRead(DATOS_SQL.dependientes.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "dependientes",
        "Dependientes",
        "SSE_FAMILY!M4T_FAMILY",
        "list",
        [
          ["STD_N_FIRST_NAME", "Nombre"],
          ["SSP_PRIMER_APELLIDO", "Primer apellido"],
          ["STD_N_MAIDEN_NAME", "Segundo apellido"],
          ["STD_DT_BIRTH", "Fecha de nacimiento"],
          ["STD_N_DEP_TYPE", "Tipo"],
          ["STD_DT_START", "Inicio"],
        ],
        DATOS_SQL.dependientes,
      ),
      form({
        id: "dependiente",
        title: "Nuevo dependiente",
        description:
          "El estándar no permite cambiar nombre ni fecha de nacimiento de un dependiente existente y avisa de homónimos.",
        fields: [
          text("STD_N_FIRST_NAME", "Nombre", { required: true, maxLength: 50 }),
          text("SSP_PRIMER_APELLIDO", "Primer apellido", { required: true, maxLength: 50 }),
          text("STD_N_MAIDEN_NAME", "Segundo apellido", { maxLength: 50 }),
          date("STD_DT_BIRTH", "Fecha de nacimiento", { required: true }),
          pendingSelect("STD_ID_DEP_TYPE", "Tipo de dependiente", "SSE_FAMILY!STD_DEP_TYPE", {
            required: true,
          }),
          date("STD_DT_START", "Fecha de inicio", { required: true }),
        ],
        write: genericWrite(
          "dependiente",
          "Enviar petición",
          "SSE_FAMILY",
          "INSERTAR",
          "SSE_FAMILY",
        ),
      }),
    ],
  },
  {
    id: "empleado.datos.eventos",
    profile: "empleado",
    domain: "datos",
    title: "Life events",
    summary: "Guía de los trámites asociados a acontecimientos de tu vida.",
    icon: "document",
    route: `${base}/eventos`,
    sources: ["sse_g1/sse_g1_p2.jsp"],
    ficha: `${DATOS}/sse_g1--sse_g1_p2.md`,
    sensitive: false,
    read: {
      kind: "pending",
      meta4: [],
      pending: ["P01", "P05"],
      detail:
        "La página original contiene un texto orientativo de ejemplo; su uso real no está confirmado.",
    },
    view: "generic",
  },
];
