import type { PortalFeature } from "../types";
import {
  area,
  date,
  form,
  methodWrite,
  note,
  pendingSelect,
  sqlConsult,
  sqlRead,
  text,
  validationForm,
} from "./helpers";
import { RESPONSABLE_SQL } from "./sql/responsable";

const TAL = "responsable/talento";
const base = "/portal/responsable/talento";

export const RESPONSABLE_TALENTO: readonly PortalFeature[] = [
  {
    id: "responsable.talento.evaluacion",
    profile: "responsable",
    domain: "talento-equipo",
    title: "Evaluación y objetivos",
    summary: "Evalúa a tu equipo, fija y valida objetivos, consulta historiales y resultados.",
    icon: "evaluation",
    route: `${base}/evaluacion`,
    sources: [
      "mss_g3/mss_g3_p15.jsp",
      "mss_g3/mss_g3_p16.jsp",
      "mss_g3/mss_g3_p16_close.jsp",
      "mss_g3/mss_g3_p20.jsp",
      "mss_g3/mss_g3_p21.jsp",
      "mss_g3/mss_g3_p22.jsp",
      "mss_g3/mss_g3_p23.jsp",
      "mss_g3/mss_g3_p4_1_val.jsp",
      "mss_g3/mss_g3_p15_val1.jsp",
      "mss_g3/mss_g3_p5.jsp",
      "mss_g3/mss_g3_p5_mod.jsp",
      "mss_g3/smco_evaluator.jsp",
      "mss_g3/smco_evaluator_val.jsp",
      "mss_g3/smco_objetives.jsp",
      "mss_g3/smco_eval_criteria.jsp",
      "mss_g3/smco_ev_gauss.jsp",
    ],
    ficha: `${TAL}/mss_g3--mss_g3_p5.md`,
    keywords: ["evaluación", "objetivos", "validar evaluaciones", "historial"],
    sensitive: true,
    read: sqlRead(RESPONSABLE_SQL.evaluaciones.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "historial",
        "Historiales de evaluación",
        "SSCO_H_EVALUTE!SSCO_H_EVALUATE",
        "list",
        [
          ["EMPLEADO", "Empleado"],
          ["SCO_NM_EVAL_PROC", "Proceso"],
          ["SCO_NM_LEVEL_OBJ", "Resultado global"],
          ["SCO_DT_START_EVAL", "Evaluación"],
        ],
        RESPONSABLE_SQL.evaluaciones,
      ),
      note(
        "Roles y fases",
        "El responsable actúa como evaluador, validador o jerárquico según el plan. Guardar no cierra la evaluación; el cálculo de notas y el cierre son de Meta4. La validación de objetivos tras la valoración del empleado es una fase propia.",
      ),
      validationForm(
        "validar-evaluadores",
        "Validar evaluadores 360",
        "SSE_EVAL360",
        "SSE_EVAL360",
      ),
      validationForm(
        "validar-objetivos",
        "Validar objetivos",
        "SSM_EV_ROL_LV_OBJ",
        "SSM_EV_ROL_LV_OBJ",
      ),
    ],
    writes: [
      methodWrite("guardar", "Guardar evaluación", "SSCO_H_EVALUTE (smco_evaluator_seg_act.jsp)"),
      methodWrite("cerrar", "Cerrar evaluación", "SSM_DEFINE_CRITERIA (mss_g3_p16_close.jsp)"),
      methodWrite("exportar", "Exportar historial", "SSCO_H_EVALUTE (exportación)", undefined, [
        "P04",
        "P08",
      ]),
    ],
  },
  {
    id: "responsable.talento.formacion",
    profile: "responsable",
    domain: "talento-equipo",
    title: "Formación del equipo",
    summary:
      "Solicita necesidades y formación, valida inscripciones, eventos convocados, valoraciones y eficacia.",
    icon: "training",
    route: `${base}/formacion`,
    sources: [
      "mss_g3/mss_g3_p6.jsp",
      "mss_g3/mss_g3_p6_mod1.jsp",
      "mss_g3/mss_g3_p6_mod2.jsp",
      "mss_g3/mss_g3_p6_insert.jsp",
      "mss_g3/mss_g3_p12.jsp",
      "mss_g3/mss_g3_p13.jsp",
      "mss_g3/mss_g3_p13_det.jsp",
      "mss_g3/mss_g3_p3_val.jsp",
      "mss_g3/mss_g3_p10.jsp",
      "mss_g3/mss_g3_p10_2.jsp",
      "mss_g3/mss_g3_p11.jsp",
      "mss_g3/mss_g3_p14.jsp",
      "mss_g3/mss_g3_p24.jsp",
      "mss_g3/mss_g3_fnrc.jsp",
      "mss_g3/mss_g3_val_efi.jsp",
      "mss_g3/smco_estimated_req_cost.jsp",
    ],
    ficha: `${TAL}/mss_g3--mss_g3_p6_mod1.md`,
    keywords: ["formación", "necesidades", "cursos", "eficacia"],
    sensitive: false,
    read: sqlRead(RESPONSABLE_SQL.formacion.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "solicitudes",
        "Solicitudes de formación del equipo",
        "SSM_TRAINING_REQUEST!M4T_REQ_DETAIL",
        "list",
        [
          ["EMPLEADO", "Empleado"],
          ["SCO_NM_DEV_SUBPRODUCT", "Curso"],
          ["SCO_NM_REQ_STATUS", "Estado"],
          ["DT_START", "Fecha"],
        ],
        RESPONSABLE_SQL.formacion,
      ),
      form({
        id: "necesidad",
        title: "Solicita necesidades de formación",
        description:
          "Formación del catálogo o fuera de catálogo, con plazas y personas. Los costes los calcula Meta4.",
        fields: [
          pendingSelect(
            "SCO_ID_PRODUCT",
            "Producto formativo",
            "SSM_TRAINING_REQUEST!SCO_PRODUCT",
            { required: true },
          ),
          pendingSelect(
            "SCO_ID_TRAINING_TYPE",
            "Tipo de formación",
            "SSM_TRAINING_REQUEST!SCO_TRAINING_TYPE",
          ),
          { name: "SCO_NUM_PLACES", label: "Plazas", type: "number", min: 1, required: true },
          { name: "SCO_HOURS", label: "Horas", type: "number", min: 0 },
          text("SCO_PLACE", "Lugar"),
          area("SCO_COMMENT", "Comentario", { maxLength: 1000 }),
        ],
        write: methodWrite("necesidad", "Solicitar", "SSM_TRAINING_REQUEST (mss_g3_p6_insert.jsp)"),
      }),
      validationForm(
        "validar-formacion",
        "Validar solicitudes de formación",
        "SSE_TRAINING_REQUEST",
        "SSE_TRAINING_REQUEST",
      ),
      note(
        "Eficacia",
        "La valoración de eficacia del responsable (CSP_MNG_VALORA_EFICA) se registra por curso realizado.",
      ),
    ],
    writes: [
      methodWrite(
        "eficacia",
        "Valorar eficacia",
        "CSP_MNG_VALORA_EFICA (actualizar_valoracion_eficacia.jsp)",
      ),
    ],
  },
  {
    id: "responsable.talento.carrera",
    profile: "responsable",
    domain: "talento-equipo",
    title: "Carrera y GAP",
    summary:
      "Planes de carrera y comparación del nivel actual con el requerido por el puesto y el siguiente.",
    icon: "career",
    route: `${base}/carrera`,
    sources: [
      "mss_g3/mss_g3_p8.jsp",
      "mss_g3/mss_g3_p8_pc.jsp",
      "mss_g3/mss_g3_p8_desc.jsp",
      "mss_g3/mss_g3_p9.jsp",
    ],
    ficha: `${TAL}/mss_g3--mss_g3_p8.md`,
    keywords: ["carrera", "gap", "competencias"],
    sensitive: true,
    read: sqlRead(RESPONSABLE_SQL.carrera.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "planes",
        "Planes de carrera del equipo",
        "SSM_CAREER_PLAN!SSM_CAREER_PLAN",
        "list",
        [
          ["EMPLEADO", "Empleado"],
          ["SCO_NM_CR_PLAN", "Plan"],
          ["DT_START", "Desde"],
          ["DT_END", "Hasta"],
        ],
        RESPONSABLE_SQL.carrera,
      ),
      note("No valorado", "«No valorado» no equivale a cero ni a ausencia de competencia."),
    ],
  },
  {
    id: "responsable.talento.vacantes",
    profile: "responsable",
    domain: "talento-equipo",
    title: "Vacantes y selección",
    summary: "Procesos abiertos, candidatos y asistente de apertura de vacante.",
    icon: "vacancy",
    route: `${base}/vacantes`,
    sources: [
      "mss_g3/mss_g3_p1.jsp",
      "mss_g3/mss_g3_p1_det.jsp",
      "mss_g3/mss_g3_p1_des.jsp",
      "mss_g3/mss_g3_p1_wiz1.jsp",
      "mss_g3/mss_g3_p1_wiz2.jsp",
      "mss_g3/mss_g3_p1_wiz3.jsp",
      "mss_g3/mss_g3_p1_wiz4.jsp",
      "mss_g3/mss_g3_p1_wiz5.jsp",
      "mss_g3/mss_g3_p1_wiz6.jsp",
      "mss_g3/mss_g3_p1_wiz7.jsp",
      "mss_g3/mss_g3_persist_wiz.jsp",
    ],
    ficha: `${TAL}/mss_g3--mss_g3_p1_wiz1.md`,
    keywords: ["vacante", "selección", "candidatos"],
    sensitive: false,
    read: sqlRead(RESPONSABLE_SQL.vacantes.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "procesos",
        "Procesos de selección",
        "SSM_RECRUIT_PRO!SSM_RECRUIT_PRO",
        "list",
        [
          ["SCO_NM_RECRUIT", "Proceso"],
          ["STD_N_JOB_CODE", "Puesto"],
          ["SCO_NU_POST_ESTIMA", "Vacantes"],
          ["SCO_DT_LIMIT", "Plazo"],
        ],
        RESPONSABLE_SQL.vacantes,
      ),
      form({
        id: "vacante",
        title: "Definición de la vacante",
        description:
          "El asistente original sigue con experiencia profesional, certificados y licencias, historial académico, obligaciones, idiomas y competencias (pasos 2 a 7).",
        fields: [
          pendingSelect("SCO_ID_JOB", "Puesto", "SSM_VACANT!SCO_JOB", { required: true }),
          {
            name: "SCO_NUM_VACANTS",
            label: "Número de vacantes",
            type: "number",
            min: 1,
            required: true,
          },
          pendingSelect("SCO_ID_MOBILITY", "Movilidad", "SSM_VACANT!SCO_MOBILITY"),
          pendingSelect("SCO_ID_WORK_LOCATION", "Lugar", "SSM_VACANT!SCO_WORK_LOCATION"),
        ],
        write: methodWrite("vacante", "Abrir vacante", "SSM_VACANT (mss_g3_persist_wiz.jsp)"),
      }),
    ],
  },
  {
    id: "responsable.talento.entrevistas",
    profile: "responsable",
    domain: "talento-equipo",
    title: "Entrevistas",
    summary: "Solicitudes de entrevista, resultados, documentos y su validación.",
    icon: "interview",
    route: `${base}/entrevistas`,
    sources: [
      "mss_g3/smco_g3_p30.jsp",
      "mss_g3/smco_g3_p30_det.jsp",
      "mss_g3/smco_g3_p30_list.jsp",
      "mss_g3/smco_g3_p30_pet.jsp",
      "mss_g3/smco_g3_p30_val.jsp",
      "mss_g3/smco_g3_p31.jsp",
      "mss_g3/smco_g3_p31_det.jsp",
    ],
    ficha: `${TAL}/mss_g3--smco_g3_p30_pet.md`,
    sensitive: true,
    read: sqlRead(RESPONSABLE_SQL.entrevistas.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "entrevistas",
        "Entrevistas del equipo",
        "SSM_GN_INTERVIEW!M4T_GN_INTERVIEW",
        "list",
        [
          ["EMPLEADO", "Empleado"],
          ["SCO_INTERVIEW_NAME", "Entrevista"],
          ["SCO_NM_IV_TYPE", "Tipo"],
          ["SCO_DT_REQUEST", "Solicitada"],
          ["SCO_DT_FINISH", "Finalizada"],
        ],
        RESPONSABLE_SQL.entrevistas,
      ),
      form({
        id: "entrevista",
        title: "Solicitud de entrevista",
        fields: [
          text("SCO_ID_HR", "Persona entrevistada", {
            required: true,
            help: "Persona de tu población.",
          }),
          pendingSelect(
            "SCO_ID_INTERVIEW_TYPE",
            "Tipo de entrevista",
            "SSM_GN_INTERVIEW!SCO_INTERVIEW_TYPE",
            { required: true },
          ),
          date("SCO_DT_INTERVIEW", "Fecha", { required: true }),
          area("SCO_COMMENT", "Comentarios"),
        ],
        write: methodWrite(
          "entrevista",
          "Solicitar entrevista",
          "SSM_GN_INTERVIEW (smco_g3_p30_send.jsp)",
          undefined,
          ["P03", "P04"],
        ),
      }),
      validationForm(
        "validar-entrevistas",
        "Valida las entrevistas",
        "SSM_GN_INTERVIEW",
        "SSM_GN_INTERVIEW",
      ),
    ],
  },
  {
    id: "responsable.talento.preferencias",
    profile: "responsable",
    domain: "talento-equipo",
    title: "Preferencias de carrera",
    summary: "Preferencias profesionales de tu equipo y su validación.",
    icon: "goal",
    route: `${base}/preferencias`,
    sources: ["mss_g3/smco_g3_p32.jsp", "mss_g3/smco_g3_p32_val.jsp"],
    ficha: `${TAL}/mss_g3--smco_g3_p32_val.md`,
    sensitive: false,
    read: sqlRead(RESPONSABLE_SQL.preferencias.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "preferencias",
        "Preferencias del equipo",
        "SSM_CR_PREFERENC!SSM_CR_PREFERENC",
        "list",
        [
          ["EMPLEADO", "Empleado"],
          ["SCO_PREFERENCES", "Preferencia"],
          ["SCO_PREF_PRIORITY", "Prioridad"],
          ["DT_START", "Desde"],
        ],
        RESPONSABLE_SQL.preferencias,
      ),
      validationForm(
        "validar-preferencias",
        "Validar preferencias",
        "SSE_CR_PREFERENC",
        "SSE_CR_PREFERENC",
      ),
    ],
  },
  {
    id: "responsable.talento.movimientos",
    profile: "responsable",
    domain: "talento-equipo",
    title: "Cambios profesionales",
    summary:
      "Cambios de puesto, posición y traslados: solicitud, seguimiento, cancelación y archivo; movilidad interna.",
    icon: "movement",
    route: `${base}/movimientos`,
    sources: [
      "mss_g3/mss_g3_p17.jsp",
      "mss_g3/mss_g3_p17_mod.jsp",
      "mss_g3/mss_g3_p18_mod.jsp",
      "mss_g3/smco_g3_p17_mod_prof.jsp",
      "mss_g3/smco_pm_modification.jsp",
      "mss_g3/smco_pm_wz_job_pos.jsp",
      "mss_g3/smco_pm_wz_transfer.jsp",
      "mss_g3/mss_g3_p2_val.jsp",
    ],
    ficha: `${TAL}/mss_g3--smco_pm_modification.md`,
    keywords: ["traslado", "cambio de puesto", "movilidad"],
    sensitive: true,
    read: sqlRead(RESPONSABLE_SQL.movimientos.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "peticiones",
        "Peticiones de movimiento",
        "SRCO_PA_MODIFICATION!SRCO_PA_PM_H_HRP_REQUEST",
        "list",
        [
          ["EMPLEADO", "Empleado"],
          ["SCO_ID_PM_TYPE", "Tipo"],
          ["SCO_DT_START", "Inicio"],
          ["SCO_DT_END", "Fin"],
        ],
        RESPONSABLE_SQL.movimientos,
      ),
      note(
        "Cancelación y archivo",
        "Una solicitud se cancela antes de la respuesta de RRHH y se archiva después de resolverse; las archivadas pueden mostrarse a petición.",
      ),
      validationForm(
        "validar-movilidad",
        "Valida las solicitudes de movilidad interna",
        "SSE_INT_MOVILITY",
        "SSE_INT_MOVILITY",
      ),
    ],
    writes: [
      methodWrite(
        "cambio-puesto",
        "Solicitar cambio de puesto o posición",
        "SRCO_PA_MODIFICATION (smco_pm_wz_job_pos.jsp)",
      ),
      methodWrite(
        "traslado",
        "Solicitar traslado",
        "SRCO_PA_MODIFICATION (smco_pm_wz_transfer.jsp)",
      ),
    ],
  },
  {
    id: "responsable.talento.desarrollo",
    profile: "responsable",
    domain: "talento-equipo",
    title: "Planes de desarrollo",
    summary: "Asigna acciones de desarrollo y haz su seguimiento.",
    icon: "goal",
    route: `${base}/desarrollo`,
    sources: [
      "mss_g3/smco_g3_dev_plan_emp.jsp",
      "mss_g3/smco_g3_dev_plan_emp_new.jsp",
      "mss_g3/smco_g3_dev_plan_emp_mod.jsp",
      "mss_g3/smco_g3_dev_plan_emp_rec.jsp",
      "mss_g3/smco_g3_dev_plan_seg.jsp",
    ],
    ficha: `${TAL}/mss_g3--smco_g3_dev_plan_emp.md`,
    sensitive: false,
    read: sqlRead(RESPONSABLE_SQL.desarrollo.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "acciones",
        "Acciones de desarrollo del equipo",
        "SMCO_DEV_PLAN_ACCION!SMCO_DEV_PLAN_ACCION",
        "list",
        [
          ["EMPLEADO", "Empleado"],
          ["SCO_NM_ACTION", "Acción"],
          ["SCO_DT_START", "Inicio"],
          ["SCO_IS_FINISHED", "Estado"],
        ],
        RESPONSABLE_SQL.desarrollo,
      ),
    ],
    writes: [
      methodWrite("asignar", "Asignar acción", "SMCO_DEV_PLAN_ACCION (smco_g3_dev_plan_act.jsp)"),
      methodWrite(
        "seguimiento",
        "Registrar seguimiento",
        "SMCO_DEV_PLAN_ACCION_SEG (smco_g3_dev_plan_emp_rec_act.jsp)",
      ),
    ],
  },
];
