import type { PortalFeature } from "../types";
import {
  date,
  form,
  methodWrite,
  note,
  pendingSelect,
  sqlConsult,
  sqlRead,
  text,
  validationForm,
} from "./helpers";
import { RESPONSABLE_SQL } from "./sql/responsable";

const TAR = "responsable/tareas";
const EQ = "responsable/equipo";

export const RESPONSABLE_ALCANCE: readonly PortalFeature[] = [
  {
    id: "responsable.alcance.poblacion",
    profile: "responsable",
    domain: "alcance",
    title: "Población",
    summary: "Unidades de responsabilidad y personas que puedes consultar.",
    icon: "scope",
    route: "/portal/responsable/alcance",
    sources: [
      "mss_generico/mss_set_wunit_resp.jsp",
      "mss_generico/mss_set_wunit_resp_p.jsp",
      "mss_generico/mss_set_wunit_resp_p2.jsp",
      "mss_generico/mss_list_employees.jsp",
      "mss_generico/mss_list_all_employees.jsp",
      "mss_generico/mss_list_all_employees_noenlaces.jsp",
      "mss_generico/mss_wunit_detail.jsp",
    ],
    ficha: `${TAR}/mss_generico--mss_set_wunit_resp.md`,
    keywords: ["población", "unidades", "responsabilidad", "equipo"],
    sensitive: false,
    read: {
      kind: "soap",
      service: "SNTC_AD_POPULATION",
      operation: "LOAD_PERSONS",
      verified: false,
    },
    view: "population",
    sections: [
      note(
        "Árbol activo",
        "En el SSM se marca un árbol activo por tipo de responsabilidad (SSM_SET_WORK_UNIT_TO_SEE): marcar unidades cambia la población de las consultas, exige al menos un empleado y no acumula árboles. La revisión salarial usa sus propias responsabilidades y no participa en esta selección.",
      ),
    ],
    writes: [
      methodWrite(
        "arbol",
        "Cambiar unidades visibles",
        "SSM_SET_WORK_UNIT_TO_SEE.SSM_LOAD_WORK_UNITS (mss_set_wunit_resp_p.jsp)",
      ),
    ],
  },
  {
    id: "responsable.alcance.delegaciones",
    profile: "responsable",
    domain: "alcance",
    title: "Delegaciones",
    summary: "Delega tus validaciones en otra persona durante un periodo.",
    icon: "delegation",
    route: "/portal/responsable/alcance/delegaciones",
    sources: [
      "mss_generico/mss_delegation.jsp",
      "mss_generico/mss_delegation_informacion_usuario.jsp",
    ],
    ficha: `${TAR}/mss_generico--mss_delegation.md`,
    keywords: ["delegación", "sustituto", "ausencia"],
    sensitive: false,
    read: sqlRead(RESPONSABLE_SQL.delegaciones.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "delegaciones",
        "Mis delegaciones",
        "MSS_DELEGATION!MSS_DELEGATION",
        "list",
        [
          ["SCO_ID_PROCESS", "Proceso"],
          ["DELEGADO", "Delegado"],
          ["DT_START", "Inicio"],
          ["DT_END", "Fin"],
        ],
        RESPONSABLE_SQL.delegaciones,
      ),
      form({
        id: "delegacion",
        title: "Nueva delegación",
        description:
          "La delegación puede transferir validaciones pendientes; terminarla afecta a las nuevas solicitudes según el periodo. No equivale a compartir tu sesión.",
        fields: [
          pendingSelect("SCO_ID_PROCESS", "Proceso", "MSS_DELEGATION!SCO_PROCESS", {
            required: true,
          }),
          date("DT_START", "Fecha de inicio", { required: true }),
          date("DT_END", "Fecha de fin"),
          text("SCO_GB_NAME", "Delegado", {
            required: true,
            maxLength: 62,
            span: 2,
            help: "Persona con contrato en la empresa.",
          }),
        ],
        rules: [
          {
            kind: "dateOrder",
            start: "DT_START",
            end: "DT_END",
            message: "La fecha de fin no puede ser anterior a la de inicio.",
          },
        ],
        write: methodWrite(
          "delegacion",
          "Crear delegación",
          "MSS_DELEGATION (ACC=INS, mss_delegation.jsp)",
          undefined,
          ["P03", "P04"],
        ),
      }),
    ],
  },
];

const personalValidations = [
  ["direcciones", "Direcciones", "SSE_ADDRESS", "SSE_ADDRESS"],
  ["email", "Correo electrónico", "SSE_E_MAIL", "SSE_E_MAIL"],
  ["telefonos", "Teléfonos", "SSE_PHONE_FAX", "SSE_PHONE_FAX"],
  ["otras-direcciones", "Otras direcciones", "SSE_ADDRESS_OTROS", "SSE_ADDRESS_OTROS"],
  ["estado-civil", "Estado civil", "SSE_HT_MAR_STAT", "SSE_HT_MAR_STAT"],
  ["pagina-web", "Página web", "SSE_HOME_PAGE", "SSE_HOME_PAGE"],
  [
    "otras-formas-contacto",
    "Otras formas de contacto",
    "SSE_OTH_CONTACT_FORMS",
    "SSE_OTH_CONTACT_FORMS",
  ],
  ["emergencia", "Contactos de emergencia", "SSE_HR_CONTACT", "SSE_HR_CONTACT"],
  ["dependientes", "Dependientes", "SSE_FAMILY", "SSE_FAMILY"],
] as const;

const professionalValidations = [
  ["titulaciones", "Titulaciones", "SSE_EMP_BACKGROUND", "SSE_EMP_BACKGROUND"],
  ["idiomas", "Idiomas", "SSE_EMP_LANGUAGES", "SSE_EMP_LANGUAGES"],
  ["experiencia", "Experiencia profesional", "SSE_EMP_PREV_JOBS", "SSE_EMP_PREV_JOBS"],
  [
    "certificados",
    "Certificados y licencias",
    "SSE_CERTIFICATION_LICEN",
    "SSE_CERTIFICATION_LICEN",
  ],
  ["otros-cursos", "Otros cursos", "SSE_HR_COMP_BACKGROUND", "SSE_HR_COMP_BACKGROUND"],
  ["asociaciones", "Asociaciones", "SSE_ASSOCIATION_ME", "SSE_ASSOCIATION_ME"],
  [
    "complementaria",
    "Información complementaria",
    "SSE_HR_COMP_INFORMATION",
    "SSE_HR_COMP_INFORMATION",
  ],
] as const;

export const RESPONSABLE_EQUIPO: readonly PortalFeature[] = [
  {
    id: "responsable.equipo.listado",
    profile: "responsable",
    domain: "equipo",
    title: "Mi equipo",
    summary: "Empleados de tus unidades visibles, con filtros por nombre, unidad, puesto y lugar.",
    icon: "team",
    route: "/portal/responsable/equipo",
    sources: ["mss_g1/mss_g1_p1.jsp", "mss_generico/mssgenerico_filtro_emp.jsp"],
    ficha: `${EQ}/mss_g1--mss_g1_p1.md`,
    keywords: ["equipo", "empleados", "colaboradores"],
    sensitive: false,
    read: {
      kind: "soap",
      service: "SNTC_AD_POPULATION",
      operation: "LOAD_PERSONS",
      verified: false,
    },
    view: "team",
    sections: [
      note(
        "Inventario del original",
        "El listado original (SSE_INVENTARIO.CARGA) filtra por nombre, apellido, unidad, puesto y lugar de trabajo y enlaza con el currículum de cada persona.",
      ),
    ],
  },
  {
    id: "responsable.equipo.ficha",
    profile: "responsable",
    domain: "equipo",
    title: "Ficha profesional",
    summary:
      "Dossier del empleado: situación actual, puestos, contratos, formación, evaluaciones, salario y tiempo.",
    icon: "id-card",
    route: "/portal/responsable/equipo/ficha",
    sources: [
      "mss_g1/smco_g1_profs_info_select_employee.jsp",
      "mss_g1/smco_g1_profs_info_cabecera.jsp",
      "mss_g1/smco_g1_profs_info_puestos.jsp",
      "mss_g1/smco_g1_profs_info_contratos.jsp",
      "mss_g1/smco_g1_profs_info_cursos.jsp",
      "mss_g1/smco_g1_profs_info_evaluaciones.jsp",
      "mss_g1/smco_g1_profs_info_salario.jsp",
      "mss_g1/smco_g1_profs_info_tiempo.jsp",
      "mss_g2/mss_g2_dosier.jsp",
    ],
    ficha: `${EQ}/mss_g1--smco_g1_profs_info_cabecera.md`,
    keywords: ["dossier", "ficha", "empleado"],
    sensitive: true,
    read: sqlRead(RESPONSABLE_SQL.ficha.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "apartados",
        "Situación actual del equipo",
        "SMCO_EMPLOYEE_PROFESIONAL_DATA!SMCO_PROFS_INFO_TODAY_MAIN_ROL",
        "list",
        [
          ["EMPLEADO", "Empleado"],
          ["N_PUESTO", "Puesto"],
          ["N_UNIDAD", "Unidad"],
          ["N_CENTRO_TRABAJO", "Centro de trabajo"],
          ["FEC_ANTIGUEDAD", "Antigüedad"],
          ["CORREO", "Correo"],
        ],
        RESPONSABLE_SQL.ficha,
      ),
    ],
  },
  {
    id: "responsable.equipo.validar-personales",
    profile: "responsable",
    domain: "equipo",
    title: "Validar datos personales",
    summary:
      "Peticiones de cambio de direcciones, contacto, estado civil, emergencia y dependientes de tu equipo.",
    icon: "approval",
    route: "/portal/responsable/equipo/validar-personales",
    sources: [
      "mss_g1/mss_g1_p1_val.jsp",
      "mss_g1/mss_g1_p1_val2.jsp",
      "mss_g1/mss_g1_p1_val3.jsp",
      "mss_g1/mss_g1_p1_val4.jsp",
      "mss_g1/mss_g1_p1_val5.jsp",
      "mss_g1/mss_g1_p1_val6.jsp",
      "mss_g1/smco_g1_p1_val5.jsp",
      "mss_g1/smco_g1_p1_val6.jsp",
      "mss_g1/smco_g1_p1_val7.jsp",
      "mss_g1/mss_g1_p4_val.jsp",
      "mss_g1/mss_g1_p5_val.jsp",
    ],
    ficha: `${EQ}/mss_g1--mss_g1_p1_val.md`,
    keywords: ["validar", "aprobar", "direcciones", "teléfonos"],
    sensitive: true,
    read: sqlRead(RESPONSABLE_SQL.validarPersonales.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "peticiones",
        "Peticiones pendientes",
        "SSE_ADDRESS!SSE_ADDRESS_VAL",
        "list",
        [
          ["EMPLEADO", "Empleado"],
          ["TIPO", "Dato"],
          ["NIVEL_ACEPTADO", "Nivel de validación"],
          ["MOTIVO_ACCION", "Comentario"],
        ],
        RESPONSABLE_SQL.validarPersonales,
      ),
      ...personalValidations.map(([id, title, tag, nod]) =>
        validationForm(`validar-${id}`, `Validar ${title.toLowerCase()}`, tag, nod),
      ),
    ],
  },
  {
    id: "responsable.equipo.validar-profesionales",
    profile: "responsable",
    domain: "equipo",
    title: "Validar datos profesionales",
    summary:
      "Peticiones de titulaciones, idiomas, experiencia, certificados, cursos y asociaciones.",
    icon: "approval",
    route: "/portal/responsable/equipo/validar-profesionales",
    sources: [
      "mss_g1/mss_g1_p3_val.jsp",
      "mss_g1/mss_g1_p3_val2.jsp",
      "mss_g1/mss_g1_p3_val3.jsp",
      "mss_g1/smco_g1_p3_val4.jsp",
      "mss_g1/smco_g1_p3_val5.jsp",
      "mss_g1/smco_g1_p3_val6.jsp",
      "mss_g1/smco_g1_p3_val7.jsp",
    ],
    ficha: `${EQ}/mss_g1--mss_g1_p3_val.md`,
    sensitive: true,
    read: sqlRead(RESPONSABLE_SQL.validarProfesionales.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "peticiones",
        "Peticiones pendientes",
        "SSE_EMP_BACKGROUND!SSE_EMP_BACKGROUND_VAL",
        "list",
        [
          ["EMPLEADO", "Empleado"],
          ["TIPO", "Dato"],
          ["NIVEL_ACEPTADO", "Nivel de validación"],
          ["MOTIVO_ACCION", "Comentario"],
        ],
        RESPONSABLE_SQL.validarProfesionales,
      ),
      ...professionalValidations.map(([id, title, tag, nod]) =>
        validationForm(`validar-${id}`, `Validar ${title.toLowerCase()}`, tag, nod),
      ),
    ],
  },
  {
    id: "responsable.equipo.validar-irpf",
    profile: "responsable",
    domain: "equipo",
    title: "IRPF y documentación",
    summary: "Situaciones fiscales, Modelo 145 y documentos aportados por tu equipo.",
    icon: "tax",
    route: "/portal/responsable/equipo/validar-irpf",
    sources: [
      "mss_g1/smco_g1_p6_val.jsp",
      "mss_g1/smsp_g1_p6_val.jsp",
      "mss_g1/smsp_g1_p6_actualizar.jsp",
    ],
    ficha: `${EQ}/mss_g1--smco_g1_p6_val.md`,
    sensitive: true,
    read: sqlRead(RESPONSABLE_SQL.validarIrpf.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "modificaciones",
        "Modificaciones del IRPF",
        "SSE_MOD_SITIRPF!SSE_VAL_ACUSE_RECIBO",
        "list",
        [
          ["EMPLEADO", "Empleado"],
          ["SSP_NM_ESTADO", "Estado"],
          ["SSP_FEC_SOLIC", "Solicitud"],
          ["SSP_FEC_EFECTO", "Efecto"],
        ],
        RESPONSABLE_SQL.validarIrpf,
      ),
      note(
        "Acuse del Modelo 145",
        "El estándar distingue los estados de entrega de documentación 01, 02 y 03 con fechas condicionadas; no equivalen a una autorización fiscal automática.",
      ),
      validationForm(
        "validar-documentos",
        "Validar documentación",
        "SSCO_HR_DOCUMENTS",
        "SSE_HR_DOC",
      ),
      validationForm(
        "validar-situacion",
        "Validar situación fiscal",
        "SSE_MOD_SITIRPF",
        "SSE_MOD_SITIRPF",
      ),
    ],
  },
  {
    id: "responsable.equipo.cv",
    profile: "responsable",
    domain: "equipo",
    title: "Currículum del empleado",
    summary: "Currículum de una persona de tu equipo.",
    icon: "document",
    route: "/portal/responsable/equipo/cv",
    sources: ["mss_g1/mss_g1_p3_cv.jsp", "mss_g1/mss_g1_cv.jsp"],
    ficha: `${EQ}/mss_g1--mss_g1_p3_cv.md`,
    sensitive: true,
    read: sqlRead([
      ...new Set([...RESPONSABLE_SQL.cvTitulaciones.tables, ...RESPONSABLE_SQL.cvIdiomas.tables]),
    ]),
    view: "generic",
    sections: [
      note(
        "Documento",
        "El PDF del CV lo genera el motor de informes de Meta4 (CSP_RP_CV) y no se puede leer por SQL. Aquí se muestran los datos que lo componen para tu equipo.",
      ),
      sqlConsult(
        "titulaciones",
        "Titulaciones del equipo",
        "SSE_EMP_CV!M4T_EMP_BACKGROUND",
        "list",
        [
          ["EMPLEADO", "Empleado"],
          ["STD_N_DIPLOMA", "Titulación"],
          ["STD_DESC_EDU_CENTER", "Centro"],
          ["STD_DT_EARNED_EXPE", "Fecha de obtención"],
        ],
        RESPONSABLE_SQL.cvTitulaciones,
      ),
      sqlConsult(
        "idiomas",
        "Idiomas del equipo",
        "SSE_EMP_CV!M4T_EMP_CV_LANGUAGES",
        "list",
        [
          ["EMPLEADO", "Empleado"],
          ["STD_N_LANGUAGE", "Idioma"],
        ],
        RESPONSABLE_SQL.cvIdiomas,
      ),
    ],
  },
  {
    id: "responsable.equipo.informes",
    profile: "responsable",
    domain: "equipo",
    title: "Informes",
    summary: "Mapa de puestos, puestos por unidad, salarios totales y por unidad, e informe ORO.",
    icon: "report",
    route: "/portal/responsable/equipo/informes",
    sources: [
      "mss_g1/mss_g1_rp_mapa_puestos.jsp",
      "mss_g1/mss_g1_rp_puestos.jsp",
      "mss_g1/mss_g1_rp_saltot.jsp",
      "mss_g1/mss_g1_rp_saluni.jsp",
      "mss_g1/mss_g1_mostrar_informe_oro.jsp",
    ],
    ficha: `${EQ}/mss_g1--mss_g1_rp_puestos.md`,
    keywords: ["informe", "puestos", "salarios", "oro"],
    sensitive: true,
    read: sqlRead(RESPONSABLE_SQL.informeOro.tables),
    view: "generic",
    sections: [
      sqlConsult(
        "oro",
        "Informe ORO de tu organización",
        "CSP_RP_ORO_MSS!CSP_RP_ORO_MSS",
        "list",
        [
          ["EMPLEADO", "Empleado"],
          ["N_DIRECCION", "Dirección"],
          ["N_AREA", "Área"],
          ["N_UNIDAD", "Unidad"],
          ["N_PUESTO", "Puesto"],
          ["N_CENTRO_TRABAJO", "Centro de trabajo"],
          ["FEC_ALTA_EMPLEADO", "Alta"],
        ],
        RESPONSABLE_SQL.informeOro,
        "Los datos del informe ORO para tu equipo. Los PDF de mapa de puestos y salarios los genera el motor de informes de Meta4 y no se pueden leer por SQL.",
      ),
      form({
        id: "filtro-informe",
        title: "Filtro: informe de puestos por unidad",
        fields: [
          pendingSelect("DIRECCION", "Dirección", "CSP_RP_ORO_MSS!CSP_CONSULTA_DIRECCION"),
          pendingSelect("AREA", "Área", "CSP_RP_ORO_MSS!CSP_CONSULTA_AREAS"),
          pendingSelect("PUESTO", "Puesto", "CSP_RP_ORO_MSS!CSP_CONSULTA_PUESTO"),
        ],
        write: methodWrite(
          "informe",
          "Generar informe",
          "CSP_RP_ORO_MSS (actualizar_informe_oro.jsp)",
          undefined,
          ["P08"],
        ),
        mode: "query",
      }),
    ],
  },
];
