import type { PortalFeature } from "../types";
import { methodWrite, note, pendingRead } from "./helpers";

const ORG = "empleado/organizacion";
const NAV = "transversal/navegacion";

export const TRANSVERSAL: readonly PortalFeature[] = [
  {
    id: "inicio",
    profile: "empleado",
    domain: "inicio",
    title: "Inicio",
    summary: "Tu portal: datos, tareas y accesos a todos los apartados.",
    icon: "home",
    route: "/portal",
    sources: [
      "sse_generico/sgco_portal.jsp",
      "sse_generico/generico_portal.jsp",
      "sse_generico/sgco_engine_tasks.jsp",
    ],
    ficha: `${NAV}/sse_generico--sgco_portal.md`,
    sensitive: false,
    read: {
      kind: "soap",
      service: "PGCO_ES_WS_VALIDATIONS",
      operation: "PGCO_TASKS",
      verified: false,
    },
    view: "home",
    writes: [
      methodWrite(
        "favorito-alta",
        "Agregar a favoritos",
        "SGCO_FAVOURITE!SGCO_FAVOURITE.SCO_LOAD (alta)",
        "sse_g0/sse_g0_actualizar_links.jsp",
      ),
      methodWrite(
        "favorito-baja",
        "Borrar favorito",
        "SGCO_FAVOURITE (baja)",
        "sse_g0/sse_g0_actualizar_g0_p1.jsp",
      ),
    ],
  },
  {
    id: "tareas",
    profile: "responsable",
    domain: "tareas",
    title: "Mis tareas",
    summary: "Validaciones, valoraciones y tareas pendientes por funcionalidad y nivel.",
    icon: "tasks",
    route: "/portal/tareas",
    sources: [
      "sse_generico/sgco_engine_tasks.jsp",
      "sse_generico/ssegenerico_pendientes.jsp",
      "mss_generico/mssgenerico_pendientes.jsp",
      "sse_g0/ssco_easy_task_list.jsp",
    ],
    ficha: `${NAV}/sse_generico--sgco_engine_tasks.md`,
    keywords: ["validaciones", "pendientes", "aprobaciones", "valoraciones"],
    sensitive: false,
    read: {
      kind: "soap",
      service: "PGCO_ES_WS_VALIDATIONS",
      operation: "PGCO_VALIDATIONS",
      verified: false,
    },
    view: "tasks",
    writes: [
      methodWrite(
        "tarea-hecho",
        "Marcar tarea como hecha",
        "SSCO_WF_EASY_TASK (ssco_easy_task_list.jsp)",
      ),
    ],
  },
  {
    id: "organizacion.quien-es-quien",
    profile: "empleado",
    domain: "organizacion",
    title: "Quién es quién",
    summary: "Busca personas y unidades de tu sociedad y abre su ficha de contacto.",
    icon: "search",
    route: "/portal/organizacion",
    sources: [
      "sse_g0/ssco_g0_who_is_who.jsp",
      "sse_g0/ssco_g0_who_is_who_empl.jsp",
      "sse_g0/ssco_engine_who.jsp",
      "sse_generico/sgco_search_emp.jsp",
    ],
    ficha: `${ORG}/sse_g0--ssco_g0_who_is_who.md`,
    keywords: ["directorio", "buscar persona", "contacto", "teléfono", "correo"],
    sensitive: false,
    read: { kind: "sql", tables: ["M4ORO_EMPLEADOS", "STD_EMAIL"], verified: true },
    view: "directory",
  },
  {
    id: "organizacion.organigrama",
    profile: "empleado",
    domain: "organizacion",
    title: "Organigrama",
    summary: "Navega por las unidades de la sociedad, sus responsables y sus personas.",
    icon: "org",
    route: "/portal/organizacion/organigrama",
    sources: [
      "sse_g0/sse_g0_organigramas.jsp",
      "sse_g0/sse_g0_organigrama.jsp",
      "sse_g0/ssco_g0_org_chart_dyn.jsp",
      "sse_g0/ssco_engine_org_chart_dyn.jsp",
      "sse_g0/organigrama-portal-QOrg.jsp",
    ],
    ficha: `${ORG}/sse_g0--sse_g0_organigramas.md`,
    keywords: ["unidades", "estructura", "jerarquía"],
    sensitive: false,
    read: { kind: "sql", tables: ["M4ORO_EMPLEADOS"], verified: true },
    view: "orgchart",
    variants: {
      CYC: "Organigrama QOrg corporativo (CSP_ORGANIGRAMA) además del organigrama dinámico. El árbol se construye con la jerarquía de M4ORO_EMPLEADOS; el servicio publicado CSP_CONSULTA_ORO_INTRAN_WU queda como alternativa por verificar.",
    },
  },
  {
    id: "organizacion.contactos",
    profile: "empleado",
    domain: "organizacion",
    title: "Mis contactos",
    summary: "Personas que guardaste como contacto en el directorio.",
    icon: "contact",
    route: "/portal/organizacion/contactos",
    sources: [
      "sse_g0/sse_g0_p1.jsp",
      "sse_g0/sse_g0_buscar_contactos.jsp",
      "sse_g0/ssco_g0_contact.jsp",
    ],
    ficha: `${ORG}/sse_g0--sse_g0_p1.md`,
    sensitive: false,
    read: pendingRead(["SGCO_CONTACT", "SSCO_WHO_IS_WHO"]),
    view: "generic",
    writes: [
      methodWrite("contacto-alta", "Añadir contacto", "SGCO_CONTACT (ssco_g0_contact.jsp)"),
      methodWrite("contacto-baja", "Eliminar contacto", "SGCO_CONTACT (ssco_mn_contact.jsp)"),
    ],
  },
  {
    id: "organizacion.contrasena",
    profile: "empleado",
    domain: "organizacion",
    title: "Cambio de contraseña",
    summary: "Cambia la contraseña de tu usuario Meta4.",
    icon: "id-card",
    route: "/portal/organizacion/contrasena",
    sources: [
      "sse_g0/change_password.jsp",
      "sse_g0/change_password_action.jsp",
      "tctools/change_password.jsp",
    ],
    ficha: `${ORG}/sse_g0--change_password.md`,
    sensitive: true,
    read: {
      kind: "pending",
      meta4: [],
      pending: ["P04"],
      detail: "El cambio de contraseña es una escritura externa de Meta4.",
    },
    view: "generic",
    sections: [
      note(
        "Contraseña",
        "powermeta4 no guarda tu contraseña. El cambio se hace en Meta4; el portal lo ofrecerá cuando exista un servicio publicado y aprobado.",
      ),
    ],
    writes: [
      methodWrite("contrasena", "Cambiar contraseña", "tctools/change_password_operation.jsp"),
    ],
  },
  {
    id: "responsable.inicio",
    profile: "responsable",
    domain: "inicio",
    title: "Inicio del responsable",
    summary: "Tu equipo, tus tareas de validación y los accesos del autoservicio del responsable.",
    icon: "team",
    route: "/portal/responsable",
    sources: [
      "mss_generico/mssgenerico_portal.jsp",
      "mss_generico/smco_portal.jsp",
      "mss_generico/generico_mapa.jsp",
    ],
    ficha: "responsable/tareas/mss_generico--mssgenerico_portal.md",
    sensitive: false,
    read: {
      kind: "soap",
      service: "SNTC_AD_POPULATION",
      operation: "LOAD_PERSONS",
      verified: false,
    },
    view: "manager-home",
  },
];
