/**
 * Snco_Ad_Hierarchic_WuRecord.java
 * Self generated code for Bussines Object SNTC_AD_POPULATION.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.sntc_ad_population;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Snco_Ad_Hierarchic_Wu.
 * @author Meta4
 */
public 
class Snco_Ad_Hierarchic_WuRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "SNTC_AD_POPULATION";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "SNCO_AD_HIERARCHIC_WU";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Snco_Ad_Hierarchic_WuRecord.class.getName());

    /* new persistence member - RecordID */    
    private String m4AutoGeneratedRecordID = null; 
    
    public String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    public void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    private boolean m4AutoGeneratedToDelete = false; 
    
    public boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    public void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item SCO_N_WU */
    private String sco_N_Wu = null;
    public void setsco_N_Wu(String ai_value)
    {
        sco_N_Wu = ai_value;
    }
    public String getsco_N_Wu()
    {
        return sco_N_Wu;
    }

    /* item HAS_CHILD */
    private Double has_Child = null;
    public void sethas_Child(Double ai_value)
    {
        has_Child = ai_value;
    }
    public Double gethas_Child()
    {
        return has_Child;
    }

    /* item SCO_ID_WU */
    private String sco_Id_Wu = null;
    public void setsco_Id_Wu(String ai_value)
    {
        sco_Id_Wu = ai_value;
    }
    public String getsco_Id_Wu()
    {
        return sco_Id_Wu;
    }

    /* item SCO_DT_END */
    private Calendar sco_Dt_End = null;
    public void setsco_Dt_End(Calendar ai_value)
    {
        sco_Dt_End = ai_value;
    }
    public Calendar getsco_Dt_End()
    {
        return sco_Dt_End;
    }

    /* item SCO_DT_START */
    private Calendar sco_Dt_Start = null;
    public void setsco_Dt_Start(Calendar ai_value)
    {
        sco_Dt_Start = ai_value;
    }
    public Calendar getsco_Dt_Start()
    {
        return sco_Dt_Start;
    }

    /* item SCO_LEFT_VALUE */
    private Double sco_Left_Value = null;
    public void setsco_Left_Value(Double ai_value)
    {
        sco_Left_Value = ai_value;
    }
    public Double getsco_Left_Value()
    {
        return sco_Left_Value;
    }

    /* item SCO_RIGHT_VALUE */
    private Double sco_Right_Value = null;
    public void setsco_Right_Value(Double ai_value)
    {
        sco_Right_Value = ai_value;
    }
    public Double getsco_Right_Value()
    {
        return sco_Right_Value;
    }

    /* item SCO_ID_TYPE_RESP */
    private String sco_Id_Type_Resp = null;
    public void setsco_Id_Type_Resp(String ai_value)
    {
        sco_Id_Type_Resp = ai_value;
    }
    public String getsco_Id_Type_Resp()
    {
        return sco_Id_Type_Resp;
    }

    /* item SCO_ID_WU_PARENT */
    private String sco_Id_Wu_Parent = null;
    public void setsco_Id_Wu_Parent(String ai_value)
    {
        sco_Id_Wu_Parent = ai_value;
    }
    public String getsco_Id_Wu_Parent()
    {
        return sco_Id_Wu_Parent;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // SCO_N_WU.
        if (sco_N_Wu != null)
        {
            htItems.put("SCO_N_WU", M4BusinessMethodArg.toString(sco_N_Wu));
        }
        // HAS_CHILD.
        if (has_Child != null)
        {
            htItems.put("HAS_CHILD", M4BusinessMethodArg.toString(has_Child));
        }
        // SCO_ID_WU.
        if (sco_Id_Wu != null)
        {
            htItems.put("SCO_ID_WU", M4BusinessMethodArg.toString(sco_Id_Wu));
        }
        // SCO_DT_END.
        if (sco_Dt_End != null)
        {
            htItems.put("SCO_DT_END", M4BusinessMethodArg.toString(sco_Dt_End));
        }
        // SCO_DT_START.
        if (sco_Dt_Start != null)
        {
            htItems.put("SCO_DT_START", M4BusinessMethodArg.toString(sco_Dt_Start));
        }
        // SCO_LEFT_VALUE.
        if (sco_Left_Value != null)
        {
            htItems.put("SCO_LEFT_VALUE", M4BusinessMethodArg.toString(sco_Left_Value));
        }
        // SCO_RIGHT_VALUE.
        if (sco_Right_Value != null)
        {
            htItems.put("SCO_RIGHT_VALUE", M4BusinessMethodArg.toString(sco_Right_Value));
        }
        // SCO_ID_TYPE_RESP.
        if (sco_Id_Type_Resp != null)
        {
            htItems.put("SCO_ID_TYPE_RESP", M4BusinessMethodArg.toString(sco_Id_Type_Resp));
        }
        // SCO_ID_WU_PARENT.
        if (sco_Id_Wu_Parent != null)
        {
            htItems.put("SCO_ID_WU_PARENT", M4BusinessMethodArg.toString(sco_Id_Wu_Parent));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read SCO_N_WU.
        sItemName = "SCO_N_WU";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_N_Wu = sItemValue;

        // read HAS_CHILD.
        sItemName = "HAS_CHILD";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        has_Child = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read SCO_ID_WU.
        sItemName = "SCO_ID_WU";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Wu = sItemValue;

        // read SCO_DT_END.
        sItemName = "SCO_DT_END";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Dt_End = M4BusinessMethodArg.toCalendar(sItemValue);

        // read SCO_DT_START.
        sItemName = "SCO_DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read SCO_LEFT_VALUE.
        sItemName = "SCO_LEFT_VALUE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Left_Value = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read SCO_RIGHT_VALUE.
        sItemName = "SCO_RIGHT_VALUE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Right_Value = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read SCO_ID_TYPE_RESP.
        sItemName = "SCO_ID_TYPE_RESP";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Type_Resp = sItemValue;

        // read SCO_ID_WU_PARENT.
        sItemName = "SCO_ID_WU_PARENT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Wu_Parent = sItemValue;


    } /* end of method readOperations */


} /* end of class Snco_Ad_Hierarchic_WuRecord */

