/**
 * Snco_Ad_Gr_Hierarchic_InfoRecord.java
 * Self generated code for Bussines Object SNTC_AD_POPULATION.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.sntc_ad_population;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Snco_Ad_Gr_Hierarchic_Info.
 * @author Meta4
 */
public 
class Snco_Ad_Gr_Hierarchic_InfoRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "SNTC_AD_POPULATION";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "SNCO_AD_GR_HIERARCHIC_INFO";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Snco_Ad_Gr_Hierarchic_InfoRecord.class.getName());

    /* new persistence member - RecordID */    
    private String m4AutoGeneratedRecordID = null; 
    
    public String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    public void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    private boolean m4AutoGeneratedToDelete = false; 
    
    public boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    public void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item HAS_CHILD */
    private String has_Child = null;
    public void sethas_Child(String ai_value)
    {
        has_Child = ai_value;
    }
    public String gethas_Child()
    {
        return has_Child;
    }

    /* item N_WORKUNIT */
    private String n_Workunit = null;
    public void setn_Workunit(String ai_value)
    {
        n_Workunit = ai_value;
    }
    public String getn_Workunit()
    {
        return n_Workunit;
    }

    /* item ID_WORKUNIT */
    private String id_Workunit = null;
    public void setid_Workunit(String ai_value)
    {
        id_Workunit = ai_value;
    }
    public String getid_Workunit()
    {
        return id_Workunit;
    }

    /* item HIERARCHIC_SENTENCE */
    private String hierarchic_Sentence = null;
    public void sethierarchic_Sentence(String ai_value)
    {
        hierarchic_Sentence = ai_value;
    }
    public String gethierarchic_Sentence()
    {
        return hierarchic_Sentence;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // HAS_CHILD.
        if (has_Child != null)
        {
            htItems.put("HAS_CHILD", M4BusinessMethodArg.toString(has_Child));
        }
        // N_WORKUNIT.
        if (n_Workunit != null)
        {
            htItems.put("N_WORKUNIT", M4BusinessMethodArg.toString(n_Workunit));
        }
        // ID_WORKUNIT.
        if (id_Workunit != null)
        {
            htItems.put("ID_WORKUNIT", M4BusinessMethodArg.toString(id_Workunit));
        }
        // HIERARCHIC_SENTENCE.
        if (hierarchic_Sentence != null)
        {
            htItems.put("HIERARCHIC_SENTENCE", M4BusinessMethodArg.toString(hierarchic_Sentence));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read HAS_CHILD.
        sItemName = "HAS_CHILD";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        has_Child = sItemValue;

        // read N_WORKUNIT.
        sItemName = "N_WORKUNIT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        n_Workunit = sItemValue;

        // read ID_WORKUNIT.
        sItemName = "ID_WORKUNIT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Workunit = sItemValue;

        // read HIERARCHIC_SENTENCE.
        sItemName = "HIERARCHIC_SENTENCE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        hierarchic_Sentence = sItemValue;


    } /* end of method readOperations */


} /* end of class Snco_Ad_Gr_Hierarchic_InfoRecord */

