/**
 * Snco_Ad_PopulationRecord.java
 * Self generated code for Bussines Object SNTC_AD_POPULATION.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.sntc_ad_population;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Snco_Ad_Population.
 * @author Meta4
 */
public 
class Snco_Ad_PopulationRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "SNTC_AD_POPULATION";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "SNCO_AD_POPULATION";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Snco_Ad_PopulationRecord.class.getName());

    /* new persistence member - RecordID */    
    private String m4AutoGeneratedRecordID = null; 
    
    public String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    public void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    private boolean m4AutoGeneratedToDelete = false; 
    
    public boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    public void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item DT_END */
    private Calendar dt_End = null;
    public void setdt_End(Calendar ai_value)
    {
        dt_End = ai_value;
    }
    public Calendar getdt_End()
    {
        return dt_End;
    }

    /* item API_SQL */
    private String api_Sql = null;
    public void setapi_Sql(String ai_value)
    {
        api_Sql = ai_value;
    }
    public String getapi_Sql()
    {
        return api_Sql;
    }

    /* item DT_START */
    private Calendar dt_Start = null;
    public void setdt_Start(Calendar ai_value)
    {
        dt_Start = ai_value;
    }
    public Calendar getdt_Start()
    {
        return dt_Start;
    }

    /* item API_SQL_R */
    private String api_Sql_R = null;
    public void setapi_Sql_R(String ai_value)
    {
        api_Sql_R = ai_value;
    }
    public String getapi_Sql_R()
    {
        return api_Sql_R;
    }

    /* item SCO_UNION */
    private Double sco_Union = null;
    public void setsco_Union(Double ai_value)
    {
        sco_Union = ai_value;
    }
    public Double getsco_Union()
    {
        return sco_Union;
    }

    /* item HIERARCHIC */
    private Double hierarchic = null;
    public void sethierarchic(Double ai_value)
    {
        hierarchic = ai_value;
    }
    public Double gethierarchic()
    {
        return hierarchic;
    }

    /* item SCO_COMMENT */
    private String sco_Comment = null;
    public void setsco_Comment(String ai_value)
    {
        sco_Comment = ai_value;
    }
    public String getsco_Comment()
    {
        return sco_Comment;
    }

    /* item ISREFERENCED */
    private Double isreferenced = null;
    public void setisreferenced(Double ai_value)
    {
        isreferenced = ai_value;
    }
    public Double getisreferenced()
    {
        return isreferenced;
    }

    /* item SCO_IS_FIXED */
    private Double sco_Is_Fixed = null;
    public void setsco_Is_Fixed(Double ai_value)
    {
        sco_Is_Fixed = ai_value;
    }
    public Double getsco_Is_Fixed()
    {
        return sco_Is_Fixed;
    }

    /* item SCO_IS_PUBLIC */
    private Double sco_Is_Public = null;
    public void setsco_Is_Public(Double ai_value)
    {
        sco_Is_Public = ai_value;
    }
    public Double getsco_Is_Public()
    {
        return sco_Is_Public;
    }

    /* item SCO_ID_HR_OWNER */
    private String sco_Id_Hr_Owner = null;
    public void setsco_Id_Hr_Owner(String ai_value)
    {
        sco_Id_Hr_Owner = ai_value;
    }
    public String getsco_Id_Hr_Owner()
    {
        return sco_Id_Hr_Owner;
    }

    /* item SCO_NATURAL_LANG */
    private String sco_Natural_Lang = null;
    public void setsco_Natural_Lang(String ai_value)
    {
        sco_Natural_Lang = ai_value;
    }
    public String getsco_Natural_Lang()
    {
        return sco_Natural_Lang;
    }

    /* item HAS_FIELD_PRIVATE */
    private Double has_Field_Private = null;
    public void sethas_Field_Private(Double ai_value)
    {
        has_Field_Private = ai_value;
    }
    public Double gethas_Field_Private()
    {
        return has_Field_Private;
    }

    /* item SCO_ID_POPULATION */
    private String sco_Id_Population = null;
    public void setsco_Id_Population(String ai_value)
    {
        sco_Id_Population = ai_value;
    }
    public String getsco_Id_Population()
    {
        return sco_Id_Population;
    }

    /* item SCO_NM_POPULATION */
    private String sco_Nm_Population = null;
    public void setsco_Nm_Population(String ai_value)
    {
        sco_Nm_Population = ai_value;
    }
    public String getsco_Nm_Population()
    {
        return sco_Nm_Population;
    }

    /* item SCO_ID_PROCESS_TYPE */
    private String sco_Id_Process_Type = null;
    public void setsco_Id_Process_Type(String ai_value)
    {
        sco_Id_Process_Type = ai_value;
    }
    public String getsco_Id_Process_Type()
    {
        return sco_Id_Process_Type;
    }

    /* item SCO_NM_PROCESS_TYPE */
    private String sco_Nm_Process_Type = null;
    public void setsco_Nm_Process_Type(String ai_value)
    {
        sco_Nm_Process_Type = ai_value;
    }
    public String getsco_Nm_Process_Type()
    {
        return sco_Nm_Process_Type;
    }

    /* item SCO_IS_PUBLIC_IN_PORTAL */
    private Double sco_Is_Public_In_Portal = null;
    public void setsco_Is_Public_In_Portal(Double ai_value)
    {
        sco_Is_Public_In_Portal = ai_value;
    }
    public Double getsco_Is_Public_In_Portal()
    {
        return sco_Is_Public_In_Portal;
    }

    /* node SNCO_AD_FILTER */
    private Snco_Ad_FilterBlock Snco_Ad_Filter = null;
    public void setsnco_Ad_Filter(Snco_Ad_FilterBlock ai_value)
    {
        Snco_Ad_Filter = ai_value;
    }
    public Snco_Ad_FilterBlock getSnco_Ad_Filter()
    {
        return Snco_Ad_Filter;
    }

    /* node SNCO_AD_CRITERIA */
    private Snco_Ad_CriteriaBlock Snco_Ad_Criteria = null;
    public void setsnco_Ad_Criteria(Snco_Ad_CriteriaBlock ai_value)
    {
        Snco_Ad_Criteria = ai_value;
    }
    public Snco_Ad_CriteriaBlock getSnco_Ad_Criteria()
    {
        return Snco_Ad_Criteria;
    }

    /* node SNCO_INFO_PERSON */
    private Snco_Info_PersonBlock Snco_Info_Person = null;
    public void setsnco_Info_Person(Snco_Info_PersonBlock ai_value)
    {
        Snco_Info_Person = ai_value;
    }
    public Snco_Info_PersonBlock getSnco_Info_Person()
    {
        return Snco_Info_Person;
    }

    /* node SNCO_INFO_PERSON_PRIVATE */
    private Snco_Info_Person_PrivateBlock Snco_Info_Person_Private = null;
    public void setsnco_Info_Person_Private(Snco_Info_Person_PrivateBlock ai_value)
    {
        Snco_Info_Person_Private = ai_value;
    }
    public Snco_Info_Person_PrivateBlock getSnco_Info_Person_Private()
    {
        return Snco_Info_Person_Private;
    }

    /* node SNCO_AD_INFO_FIXED_PERSON */
    private Snco_Ad_Info_Fixed_PersonBlock Snco_Ad_Info_Fixed_Person = null;
    public void setsnco_Ad_Info_Fixed_Person(Snco_Ad_Info_Fixed_PersonBlock ai_value)
    {
        Snco_Ad_Info_Fixed_Person = ai_value;
    }
    public Snco_Ad_Info_Fixed_PersonBlock getSnco_Ad_Info_Fixed_Person()
    {
        return Snco_Ad_Info_Fixed_Person;
    }

    /* node SNCO_AD_COUNT_EMPLOYEE_POP */
    private Snco_Ad_Count_Employee_PopBlock Snco_Ad_Count_Employee_Pop = null;
    public void setsnco_Ad_Count_Employee_Pop(Snco_Ad_Count_Employee_PopBlock ai_value)
    {
        Snco_Ad_Count_Employee_Pop = ai_value;
    }
    public Snco_Ad_Count_Employee_PopBlock getSnco_Ad_Count_Employee_Pop()
    {
        return Snco_Ad_Count_Employee_Pop;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // DT_END.
        if (dt_End != null)
        {
            htItems.put("DT_END", M4BusinessMethodArg.toString(dt_End));
        }
        // API_SQL.
        if (api_Sql != null)
        {
            htItems.put("API_SQL", M4BusinessMethodArg.toString(api_Sql));
        }
        // DT_START.
        if (dt_Start != null)
        {
            htItems.put("DT_START", M4BusinessMethodArg.toString(dt_Start));
        }
        // API_SQL_R.
        if (api_Sql_R != null)
        {
            htItems.put("API_SQL_R", M4BusinessMethodArg.toString(api_Sql_R));
        }
        // SCO_UNION.
        if (sco_Union != null)
        {
            htItems.put("SCO_UNION", M4BusinessMethodArg.toString(sco_Union));
        }
        // HIERARCHIC.
        if (hierarchic != null)
        {
            htItems.put("HIERARCHIC", M4BusinessMethodArg.toString(hierarchic));
        }
        // SCO_COMMENT.
        if (sco_Comment != null)
        {
            htItems.put("SCO_COMMENT", M4BusinessMethodArg.toString(sco_Comment));
        }
        // ISREFERENCED.
        if (isreferenced != null)
        {
            htItems.put("ISREFERENCED", M4BusinessMethodArg.toString(isreferenced));
        }
        // SCO_IS_FIXED.
        if (sco_Is_Fixed != null)
        {
            htItems.put("SCO_IS_FIXED", M4BusinessMethodArg.toString(sco_Is_Fixed));
        }
        // SCO_IS_PUBLIC.
        if (sco_Is_Public != null)
        {
            htItems.put("SCO_IS_PUBLIC", M4BusinessMethodArg.toString(sco_Is_Public));
        }
        // SCO_ID_HR_OWNER.
        if (sco_Id_Hr_Owner != null)
        {
            htItems.put("SCO_ID_HR_OWNER", M4BusinessMethodArg.toString(sco_Id_Hr_Owner));
        }
        // SCO_NATURAL_LANG.
        if (sco_Natural_Lang != null)
        {
            htItems.put("SCO_NATURAL_LANG", M4BusinessMethodArg.toString(sco_Natural_Lang));
        }
        // HAS_FIELD_PRIVATE.
        if (has_Field_Private != null)
        {
            htItems.put("HAS_FIELD_PRIVATE", M4BusinessMethodArg.toString(has_Field_Private));
        }
        // SCO_ID_POPULATION.
        if (sco_Id_Population != null)
        {
            htItems.put("SCO_ID_POPULATION", M4BusinessMethodArg.toString(sco_Id_Population));
        }
        // SCO_NM_POPULATION.
        if (sco_Nm_Population != null)
        {
            htItems.put("SCO_NM_POPULATION", M4BusinessMethodArg.toString(sco_Nm_Population));
        }
        // SCO_ID_PROCESS_TYPE.
        if (sco_Id_Process_Type != null)
        {
            htItems.put("SCO_ID_PROCESS_TYPE", M4BusinessMethodArg.toString(sco_Id_Process_Type));
        }
        // SCO_NM_PROCESS_TYPE.
        if (sco_Nm_Process_Type != null)
        {
            htItems.put("SCO_NM_PROCESS_TYPE", M4BusinessMethodArg.toString(sco_Nm_Process_Type));
        }
        // SCO_IS_PUBLIC_IN_PORTAL.
        if (sco_Is_Public_In_Portal != null)
        {
            htItems.put("SCO_IS_PUBLIC_IN_PORTAL", M4BusinessMethodArg.toString(sco_Is_Public_In_Portal));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

        // write data for node SNCO_AD_FILTER.
        if ( Snco_Ad_Filter != null) 
        {
           Snco_Ad_Filter.writeOperations(ai_m4Op);
        }

        // write data for node SNCO_AD_CRITERIA.
        if ( Snco_Ad_Criteria != null) 
        {
           Snco_Ad_Criteria.writeOperations(ai_m4Op);
        }

        // write data for node SNCO_INFO_PERSON.
        if ( Snco_Info_Person != null) 
        {
           Snco_Info_Person.writeOperations(ai_m4Op);
        }

        // write data for node SNCO_INFO_PERSON_PRIVATE.
        if ( Snco_Info_Person_Private != null) 
        {
           Snco_Info_Person_Private.writeOperations(ai_m4Op);
        }

        // write data for node SNCO_AD_INFO_FIXED_PERSON.
        if ( Snco_Ad_Info_Fixed_Person != null) 
        {
           Snco_Ad_Info_Fixed_Person.writeOperations(ai_m4Op);
        }

        // write data for node SNCO_AD_COUNT_EMPLOYEE_POP.
        if ( Snco_Ad_Count_Employee_Pop != null) 
        {
           Snco_Ad_Count_Employee_Pop.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read DT_END.
        sItemName = "DT_END";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_End = M4BusinessMethodArg.toCalendar(sItemValue);

        // read API_SQL.
        sItemName = "API_SQL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        api_Sql = sItemValue;

        // read DT_START.
        sItemName = "DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read API_SQL_R.
        sItemName = "API_SQL_R";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        api_Sql_R = sItemValue;

        // read SCO_UNION.
        sItemName = "SCO_UNION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Union = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read HIERARCHIC.
        sItemName = "HIERARCHIC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        hierarchic = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read SCO_COMMENT.
        sItemName = "SCO_COMMENT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Comment = sItemValue;

        // read ISREFERENCED.
        sItemName = "ISREFERENCED";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        isreferenced = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read SCO_IS_FIXED.
        sItemName = "SCO_IS_FIXED";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Is_Fixed = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read SCO_IS_PUBLIC.
        sItemName = "SCO_IS_PUBLIC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Is_Public = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read SCO_ID_HR_OWNER.
        sItemName = "SCO_ID_HR_OWNER";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Hr_Owner = sItemValue;

        // read SCO_NATURAL_LANG.
        sItemName = "SCO_NATURAL_LANG";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Natural_Lang = sItemValue;

        // read HAS_FIELD_PRIVATE.
        sItemName = "HAS_FIELD_PRIVATE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        has_Field_Private = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read SCO_ID_POPULATION.
        sItemName = "SCO_ID_POPULATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Population = sItemValue;

        // read SCO_NM_POPULATION.
        sItemName = "SCO_NM_POPULATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Nm_Population = sItemValue;

        // read SCO_ID_PROCESS_TYPE.
        sItemName = "SCO_ID_PROCESS_TYPE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Process_Type = sItemValue;

        // read SCO_NM_PROCESS_TYPE.
        sItemName = "SCO_NM_PROCESS_TYPE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Nm_Process_Type = sItemValue;

        // read SCO_IS_PUBLIC_IN_PORTAL.
        sItemName = "SCO_IS_PUBLIC_IN_PORTAL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Is_Public_In_Portal = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read data for node SNCO_AD_FILTER.
        Snco_Ad_Filter = new Snco_Ad_FilterBlock();
        Snco_Ad_Filter.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Snco_Ad_FilterBlock.NODE_NAME));

        // read data for node SNCO_AD_CRITERIA.
        Snco_Ad_Criteria = new Snco_Ad_CriteriaBlock();
        Snco_Ad_Criteria.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Snco_Ad_CriteriaBlock.NODE_NAME));

        // read data for node SNCO_INFO_PERSON.
        Snco_Info_Person = new Snco_Info_PersonBlock();
        Snco_Info_Person.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Snco_Info_PersonBlock.NODE_NAME));

        // read data for node SNCO_INFO_PERSON_PRIVATE.
        Snco_Info_Person_Private = new Snco_Info_Person_PrivateBlock();
        Snco_Info_Person_Private.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Snco_Info_Person_PrivateBlock.NODE_NAME));

        // read data for node SNCO_AD_INFO_FIXED_PERSON.
        Snco_Ad_Info_Fixed_Person = new Snco_Ad_Info_Fixed_PersonBlock();
        Snco_Ad_Info_Fixed_Person.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Snco_Ad_Info_Fixed_PersonBlock.NODE_NAME));

        // read data for node SNCO_AD_COUNT_EMPLOYEE_POP.
        Snco_Ad_Count_Employee_Pop = new Snco_Ad_Count_Employee_PopBlock();
        Snco_Ad_Count_Employee_Pop.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Snco_Ad_Count_Employee_PopBlock.NODE_NAME));


    } /* end of method readOperations */


} /* end of class Snco_Ad_PopulationRecord */

