/**
 * Snco_Ad_Count_Employee_PopRecord.java
 * Self generated code for Bussines Object SNTC_AD_POPULATION.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.sntc_ad_population;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Snco_Ad_Count_Employee_Pop.
 * @author Meta4
 */
public 
class Snco_Ad_Count_Employee_PopRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "SNTC_AD_POPULATION";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "SNCO_AD_COUNT_EMPLOYEE_POP";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Snco_Ad_Count_Employee_PopRecord.class.getName());

    /* new persistence member - RecordID */    
    private String m4AutoGeneratedRecordID = null; 
    
    public String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    public void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    private boolean m4AutoGeneratedToDelete = false; 
    
    public boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    public void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item ID */
    private String id = null;
    public void setid(String ai_value)
    {
        id = ai_value;
    }
    public String getid()
    {
        return id;
    }

    /* item NAME */
    private String name = null;
    public void setname(String ai_value)
    {
        name = ai_value;
    }
    public String getname()
    {
        return name;
    }

    /* item EMPTY */
    private String empty = null;
    public void setempty(String ai_value)
    {
        empty = ai_value;
    }
    public String getempty()
    {
        return empty;
    }

    /* item FILTER_MAX */
    private Double filter_Max = null;
    public void setfilter_Max(Double ai_value)
    {
        filter_Max = ai_value;
    }
    public Double getfilter_Max()
    {
        return filter_Max;
    }

    /* item COUNT_EMPLOYEE */
    private Double count_Employee = null;
    public void setcount_Employee(Double ai_value)
    {
        count_Employee = ai_value;
    }
    public Double getcount_Employee()
    {
        return count_Employee;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // ID.
        if (id != null)
        {
            htItems.put("ID", M4BusinessMethodArg.toString(id));
        }
        // NAME.
        if (name != null)
        {
            htItems.put("NAME", M4BusinessMethodArg.toString(name));
        }
        // EMPTY.
        if (empty != null)
        {
            htItems.put("EMPTY", M4BusinessMethodArg.toString(empty));
        }
        // FILTER_MAX.
        if (filter_Max != null)
        {
            htItems.put("FILTER_MAX", M4BusinessMethodArg.toString(filter_Max));
        }
        // COUNT_EMPLOYEE.
        if (count_Employee != null)
        {
            htItems.put("COUNT_EMPLOYEE", M4BusinessMethodArg.toString(count_Employee));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read ID.
        sItemName = "ID";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id = sItemValue;

        // read NAME.
        sItemName = "NAME";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        name = sItemValue;

        // read EMPTY.
        sItemName = "EMPTY";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        empty = sItemValue;

        // read FILTER_MAX.
        sItemName = "FILTER_MAX";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        filter_Max = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read COUNT_EMPLOYEE.
        sItemName = "COUNT_EMPLOYEE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        count_Employee = M4BusinessMethodArg.toDoubleNillable(sItemValue);


    } /* end of method readOperations */


} /* end of class Snco_Ad_Count_Employee_PopRecord */

