/**
 * Snco_Ad_Gr_Hierarchic_InfoBlock.java
 * Self generated code for Bussines Object SNTC_AD_POPULATION.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.sntc_ad_population;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Snco_Ad_Gr_Hierarchic_Info.
 * @author Meta4
 */
public 
class Snco_Ad_Gr_Hierarchic_InfoBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "SNTC_AD_POPULATION";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "SNCO_AD_GR_HIERARCHIC_INFO";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Snco_Ad_Gr_Hierarchic_InfoBlock.class.getName());

    /* the recordset */
    private Snco_Ad_Gr_Hierarchic_InfoRecord[] Snco_Ad_Gr_Hierarchic_InfoRecordSet = null;
    public void setSnco_Ad_Gr_Hierarchic_InfoRecordSet(Snco_Ad_Gr_Hierarchic_InfoRecord[] ai_arg)
    {
        Snco_Ad_Gr_Hierarchic_InfoRecordSet = ai_arg;
    }
    public Snco_Ad_Gr_Hierarchic_InfoRecord[] getSnco_Ad_Gr_Hierarchic_InfoRecordSet()
    {
        return Snco_Ad_Gr_Hierarchic_InfoRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Snco_Ad_Gr_Hierarchic_InfoBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();

        // insert 'block scope' values in SNCO_AD_GR_HIERARCHIC_INFO.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in SNCO_AD_GR_HIERARCHIC_INFO.
        if (Snco_Ad_Gr_Hierarchic_InfoRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Snco_Ad_Gr_Hierarchic_InfoRecordSet.length; i++)
        {
            Snco_Ad_Gr_Hierarchic_InfoRecord record = Snco_Ad_Gr_Hierarchic_InfoRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in SNCO_AD_GR_HIERARCHIC_INFO.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;


        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Snco_Ad_Gr_Hierarchic_InfoRecordSet = new Snco_Ad_Gr_Hierarchic_InfoRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Snco_Ad_Gr_Hierarchic_InfoRecord record = new Snco_Ad_Gr_Hierarchic_InfoRecord();
                      
			      record.setM4AutoGeneratedRecordID (sRecordID) ; 
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Snco_Ad_Gr_Hierarchic_InfoRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Snco_Ad_Gr_Hierarchic_InfoBlock */

