
;--------------------------------------------------------------------------------------
;  - file: WEB-INF/classes/com/meta4/soapservices/services/rpc/CSP_CONSULTA_WORK_UNIT/service.properties
;  - description: Self generated service properties file for CSP_CONSULTA_WORK_UNIT Soap Service
;  -
;  - Copyright Meta4 Spain S.A.
;  - Centro Europa Empresarial - Edf. Roma
;  - C/ Rozabella, 8
;  - 28230 Las Rozas - Madrid
;  - Spain
;  -
;--------------------------------------------------------------------------------------- 

metadate=2018-04-26 15:02:49

