/**
 * Csp_Consul_OroBlock.java
 * Self generated code for Bussines Object CSP_TP_OBJ_CUANT.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.csp_tp_obj_cuant;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Csp_Consul_Oro.
 * @author Meta4
 */
public 
class Csp_Consul_OroBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_TP_OBJ_CUANT";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_CONSUL_ORO";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Consul_OroBlock.class.getName());

    /* item ID_EMP */
    public String id_Emp = null;
    private void setid_Emp(String ai_value)
    {
        id_Emp = ai_value;
    }
    private String getid_Emp()
    {
        return id_Emp;
    }

    /* the recordset */
    public Csp_Consul_OroRecord[] Csp_Consul_OroRecordSet = null;
    private void setCsp_Consul_OroRecordSet(Csp_Consul_OroRecord[] ai_arg)
    {
        Csp_Consul_OroRecordSet = ai_arg;
    }
    private Csp_Consul_OroRecord[] getCsp_Consul_OroRecordSet()
    {
        return Csp_Consul_OroRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Csp_Consul_OroBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // ID_EMP.
        if (id_Emp != null)
        {
            htItems.put("ID_EMP", M4BusinessMethodArg.toString(id_Emp));
        }

        // insert 'block scope' values in CSP_CONSUL_ORO.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in CSP_CONSUL_ORO.
        if (Csp_Consul_OroRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Csp_Consul_OroRecordSet.length; i++)
        {
            Csp_Consul_OroRecord record = Csp_Consul_OroRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in CSP_CONSUL_ORO.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;

        // read ID_EMP.
        sItemName = "ID_EMP";
        nItem = ai_xml.findItem(ai_node, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Emp = sItemValue;

        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Csp_Consul_OroRecordSet = new Csp_Consul_OroRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Csp_Consul_OroRecord record = new Csp_Consul_OroRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Csp_Consul_OroRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Csp_Consul_OroBlock */

