
;--------------------------------------------------------------------------------------
;  - file: WEB-INF/classes/com/meta4/soapservices/services/rpc/CSP_TP_OBJ_CUANT/service.properties
;  - description: Self generated service properties file for CSP_TP_OBJ_CUANT Soap Service
;  -
;  - Copyright Meta4 Spain S.A.
;  - Centro Europa Empresarial - Edf. Roma
;  - C/ Rozabella, 8
;  - 28230 Las Rozas - Madrid
;  - Spain
;  -
;--------------------------------------------------------------------------------------- 

metadate=2020-03-04 08:20:45

