/**
 * Cyc_Pcp_Soap_PrefaseivRecord.java
 * Self generated code for Bussines Object CYC_PCP_SOAP_PREFASEIV.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_pcp_soap_prefaseiv;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Pcp_Soap_Prefaseiv.
 * @author Meta4
 */
public 
class Cyc_Pcp_Soap_PrefaseivRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_PCP_SOAP_PREFASEIV";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_PCP_SOAP_PREFASEIV";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Pcp_Soap_PrefaseivRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item DT_END */
    public Calendar dt_End = null;
    private void setdt_End(Calendar ai_value)
    {
        dt_End = ai_value;
    }
    private Calendar getdt_End()
    {
        return dt_End;
    }

    /* item DT_START */
    public Calendar dt_Start = null;
    private void setdt_Start(Calendar ai_value)
    {
        dt_Start = ai_value;
    }
    private Calendar getdt_Start()
    {
        return dt_Start;
    }

    /* item CYC_ID_HR */
    public String cyc_Id_Hr = null;
    private void setcyc_Id_Hr(String ai_value)
    {
        cyc_Id_Hr = ai_value;
    }
    private String getcyc_Id_Hr()
    {
        return cyc_Id_Hr;
    }

    /* item CYC_ACCIONES */
    public String cyc_Acciones = null;
    private void setcyc_Acciones(String ai_value)
    {
        cyc_Acciones = ai_value;
    }
    private String getcyc_Acciones()
    {
        return cyc_Acciones;
    }

    /* item CYC_NOMBRE_MC */
    public String cyc_Nombre_Mc = null;
    private void setcyc_Nombre_Mc(String ai_value)
    {
        cyc_Nombre_Mc = ai_value;
    }
    private String getcyc_Nombre_Mc()
    {
        return cyc_Nombre_Mc;
    }

    /* item CYC_OBJETIVOS */
    public String cyc_Objetivos = null;
    private void setcyc_Objetivos(String ai_value)
    {
        cyc_Objetivos = ai_value;
    }
    private String getcyc_Objetivos()
    {
        return cyc_Objetivos;
    }

    /* item CYC_COMPROMISO */
    public String cyc_Compromiso = null;
    private void setcyc_Compromiso(String ai_value)
    {
        cyc_Compromiso = ai_value;
    }
    private String getcyc_Compromiso()
    {
        return cyc_Compromiso;
    }

    /* item CYC_MENTOR_OR_COACH */
    public String cyc_Mentor_Or_Coach = null;
    private void setcyc_Mentor_Or_Coach(String ai_value)
    {
        cyc_Mentor_Or_Coach = ai_value;
    }
    private String getcyc_Mentor_Or_Coach()
    {
        return cyc_Mentor_Or_Coach;
    }

    /* item CYC_PERIOD_REUNIONES */
    public String cyc_Period_Reuniones = null;
    private void setcyc_Period_Reuniones(String ai_value)
    {
        cyc_Period_Reuniones = ai_value;
    }
    private String getcyc_Period_Reuniones()
    {
        return cyc_Period_Reuniones;
    }

    /* item CYC_AVANCES_CONSECUCIONES */
    public String cyc_Avances_Consecuciones = null;
    private void setcyc_Avances_Consecuciones(String ai_value)
    {
        cyc_Avances_Consecuciones = ai_value;
    }
    private String getcyc_Avances_Consecuciones()
    {
        return cyc_Avances_Consecuciones;
    }

    /* node CYC_PCP_SOAP_DESC_PREFASEIV */
    public Cyc_Pcp_Soap_Desc_PrefaseivBlock Cyc_Pcp_Soap_Desc_Prefaseiv = null;
    private void setcyc_Pcp_Soap_Desc_Prefaseiv(Cyc_Pcp_Soap_Desc_PrefaseivBlock ai_value)
    {
        Cyc_Pcp_Soap_Desc_Prefaseiv = ai_value;
    }
    private Cyc_Pcp_Soap_Desc_PrefaseivBlock getCyc_Pcp_Soap_Desc_Prefaseiv()
    {
        return Cyc_Pcp_Soap_Desc_Prefaseiv;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // DT_END.
        if (dt_End != null)
        {
            htItems.put("DT_END", M4BusinessMethodArg.toString(dt_End));
        }
        // DT_START.
        if (dt_Start != null)
        {
            htItems.put("DT_START", M4BusinessMethodArg.toString(dt_Start));
        }
        // CYC_ID_HR.
        if (cyc_Id_Hr != null)
        {
            htItems.put("CYC_ID_HR", M4BusinessMethodArg.toString(cyc_Id_Hr));
        }
        // CYC_ACCIONES.
        if (cyc_Acciones != null)
        {
            htItems.put("CYC_ACCIONES", M4BusinessMethodArg.toString(cyc_Acciones));
        }
        // CYC_NOMBRE_MC.
        if (cyc_Nombre_Mc != null)
        {
            htItems.put("CYC_NOMBRE_MC", M4BusinessMethodArg.toString(cyc_Nombre_Mc));
        }
        // CYC_OBJETIVOS.
        if (cyc_Objetivos != null)
        {
            htItems.put("CYC_OBJETIVOS", M4BusinessMethodArg.toString(cyc_Objetivos));
        }
        // CYC_COMPROMISO.
        if (cyc_Compromiso != null)
        {
            htItems.put("CYC_COMPROMISO", M4BusinessMethodArg.toString(cyc_Compromiso));
        }
        // CYC_MENTOR_OR_COACH.
        if (cyc_Mentor_Or_Coach != null)
        {
            htItems.put("CYC_MENTOR_OR_COACH", M4BusinessMethodArg.toString(cyc_Mentor_Or_Coach));
        }
        // CYC_PERIOD_REUNIONES.
        if (cyc_Period_Reuniones != null)
        {
            htItems.put("CYC_PERIOD_REUNIONES", M4BusinessMethodArg.toString(cyc_Period_Reuniones));
        }
        // CYC_AVANCES_CONSECUCIONES.
        if (cyc_Avances_Consecuciones != null)
        {
            htItems.put("CYC_AVANCES_CONSECUCIONES", M4BusinessMethodArg.toString(cyc_Avances_Consecuciones));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

        // write data for node CYC_PCP_SOAP_DESC_PREFASEIV.
        if ( Cyc_Pcp_Soap_Desc_Prefaseiv != null) 
        {
           Cyc_Pcp_Soap_Desc_Prefaseiv.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read DT_END.
        sItemName = "DT_END";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_End = M4BusinessMethodArg.toCalendar(sItemValue);

        // read DT_START.
        sItemName = "DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_ID_HR.
        sItemName = "CYC_ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Hr = sItemValue;

        // read CYC_ACCIONES.
        sItemName = "CYC_ACCIONES";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Acciones = sItemValue;

        // read CYC_NOMBRE_MC.
        sItemName = "CYC_NOMBRE_MC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Nombre_Mc = sItemValue;

        // read CYC_OBJETIVOS.
        sItemName = "CYC_OBJETIVOS";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Objetivos = sItemValue;

        // read CYC_COMPROMISO.
        sItemName = "CYC_COMPROMISO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Compromiso = sItemValue;

        // read CYC_MENTOR_OR_COACH.
        sItemName = "CYC_MENTOR_OR_COACH";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Mentor_Or_Coach = sItemValue;

        // read CYC_PERIOD_REUNIONES.
        sItemName = "CYC_PERIOD_REUNIONES";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Period_Reuniones = sItemValue;

        // read CYC_AVANCES_CONSECUCIONES.
        sItemName = "CYC_AVANCES_CONSECUCIONES";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Avances_Consecuciones = sItemValue;

        // read data for node CYC_PCP_SOAP_DESC_PREFASEIV.
        Cyc_Pcp_Soap_Desc_Prefaseiv = new Cyc_Pcp_Soap_Desc_PrefaseivBlock();
        Cyc_Pcp_Soap_Desc_Prefaseiv.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_Pcp_Soap_Desc_PrefaseivBlock.NODE_NAME));


    } /* end of method readOperations */


} /* end of class Cyc_Pcp_Soap_PrefaseivRecord */

