/**
 * Csp_Insertar_PuntosRecord.java
 * Self generated code for Bussines Object CSP_GUARDAR_FEEDBACK_2.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_guardar_feedback_2;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Insertar_Puntos.
 * @author Meta4
 */
public 
class Csp_Insertar_PuntosRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_GUARDAR_FEEDBACK_2";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_INSERTAR_PUNTOS";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Insertar_PuntosRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item P_PUNTUACION */
    public Double p_Puntuacion = null;
    private void setp_Puntuacion(Double ai_value)
    {
        p_Puntuacion = ai_value;
    }
    private Double getp_Puntuacion()
    {
        return p_Puntuacion;
    }

    /* item P_TIPO_PUNTO */
    public String p_Tipo_Punto = null;
    private void setp_Tipo_Punto(String ai_value)
    {
        p_Tipo_Punto = ai_value;
    }
    private String getp_Tipo_Punto()
    {
        return p_Tipo_Punto;
    }

    /* item P_ID_VALOR_PONDER */
    public String p_Id_Valor_Ponder = null;
    private void setp_Id_Valor_Ponder(String ai_value)
    {
        p_Id_Valor_Ponder = ai_value;
    }
    private String getp_Id_Valor_Ponder()
    {
        return p_Id_Valor_Ponder;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // P_PUNTUACION.
        if (p_Puntuacion != null)
        {
            htItems.put("P_PUNTUACION", M4BusinessMethodArg.toString(p_Puntuacion));
        }
        // P_TIPO_PUNTO.
        if (p_Tipo_Punto != null)
        {
            htItems.put("P_TIPO_PUNTO", M4BusinessMethodArg.toString(p_Tipo_Punto));
        }
        // P_ID_VALOR_PONDER.
        if (p_Id_Valor_Ponder != null)
        {
            htItems.put("P_ID_VALOR_PONDER", M4BusinessMethodArg.toString(p_Id_Valor_Ponder));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read P_PUNTUACION.
        sItemName = "P_PUNTUACION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Puntuacion = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_TIPO_PUNTO.
        sItemName = "P_TIPO_PUNTO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Tipo_Punto = sItemValue;

        // read P_ID_VALOR_PONDER.
        sItemName = "P_ID_VALOR_PONDER";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Id_Valor_Ponder = sItemValue;


    } /* end of method readOperations */


} /* end of class Csp_Insertar_PuntosRecord */

