/**
 * Csp_Insertar_Datos_FbRecord.java
 * Self generated code for Bussines Object CSP_GUARDAR_FEEDBACK_2.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_guardar_feedback_2;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Insertar_Datos_Fb.
 * @author Meta4
 */
public 
class Csp_Insertar_Datos_FbRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_GUARDAR_FEEDBACK_2";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_INSERTAR_DATOS_FB";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Insertar_Datos_FbRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item P_COMENT */
    public String p_Coment = null;
    private void setp_Coment(String ai_value)
    {
        p_Coment = ai_value;
    }
    private String getp_Coment()
    {
        return p_Coment;
    }

    /* item P_FEC_REALIZACION */
    public String p_Fec_Realizacion = null;
    private void setp_Fec_Realizacion(String ai_value)
    {
        p_Fec_Realizacion = ai_value;
    }
    private String getp_Fec_Realizacion()
    {
        return p_Fec_Realizacion;
    }

    /* item P_COMENTARIOS_RRHH */
    public String p_Comentarios_Rrhh = null;
    private void setp_Comentarios_Rrhh(String ai_value)
    {
        p_Comentarios_Rrhh = ai_value;
    }
    private String getp_Comentarios_Rrhh()
    {
        return p_Comentarios_Rrhh;
    }

    /* item P_FEC_ENTREV_FEEDBK */
    public String p_Fec_Entrev_Feedbk = null;
    private void setp_Fec_Entrev_Feedbk(String ai_value)
    {
        p_Fec_Entrev_Feedbk = ai_value;
    }
    private String getp_Fec_Entrev_Feedbk()
    {
        return p_Fec_Entrev_Feedbk;
    }

    /* item P_OBSERVACIONES_RRHH */
    public String p_Observaciones_Rrhh = null;
    private void setp_Observaciones_Rrhh(String ai_value)
    {
        p_Observaciones_Rrhh = ai_value;
    }
    private String getp_Observaciones_Rrhh()
    {
        return p_Observaciones_Rrhh;
    }

    /* item P_PERFIL_PROFESIONAL */
    public String p_Perfil_Profesional = null;
    private void setp_Perfil_Profesional(String ai_value)
    {
        p_Perfil_Profesional = ai_value;
    }
    private String getp_Perfil_Profesional()
    {
        return p_Perfil_Profesional;
    }

    /* item P_RECOMENDACIONES_RRHH */
    public String p_Recomendaciones_Rrhh = null;
    private void setp_Recomendaciones_Rrhh(String ai_value)
    {
        p_Recomendaciones_Rrhh = ai_value;
    }
    private String getp_Recomendaciones_Rrhh()
    {
        return p_Recomendaciones_Rrhh;
    }

    /* item P_FEC_ACEPTACION_FEEDBK */
    public String p_Fec_Aceptacion_Feedbk = null;
    private void setp_Fec_Aceptacion_Feedbk(String ai_value)
    {
        p_Fec_Aceptacion_Feedbk = ai_value;
    }
    private String getp_Fec_Aceptacion_Feedbk()
    {
        return p_Fec_Aceptacion_Feedbk;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // P_COMENT.
        if (p_Coment != null)
        {
            htItems.put("P_COMENT", M4BusinessMethodArg.toString(p_Coment));
        }
        // P_FEC_REALIZACION.
        if (p_Fec_Realizacion != null)
        {
            htItems.put("P_FEC_REALIZACION", M4BusinessMethodArg.toString(p_Fec_Realizacion));
        }
        // P_COMENTARIOS_RRHH.
        if (p_Comentarios_Rrhh != null)
        {
            htItems.put("P_COMENTARIOS_RRHH", M4BusinessMethodArg.toString(p_Comentarios_Rrhh));
        }
        // P_FEC_ENTREV_FEEDBK.
        if (p_Fec_Entrev_Feedbk != null)
        {
            htItems.put("P_FEC_ENTREV_FEEDBK", M4BusinessMethodArg.toString(p_Fec_Entrev_Feedbk));
        }
        // P_OBSERVACIONES_RRHH.
        if (p_Observaciones_Rrhh != null)
        {
            htItems.put("P_OBSERVACIONES_RRHH", M4BusinessMethodArg.toString(p_Observaciones_Rrhh));
        }
        // P_PERFIL_PROFESIONAL.
        if (p_Perfil_Profesional != null)
        {
            htItems.put("P_PERFIL_PROFESIONAL", M4BusinessMethodArg.toString(p_Perfil_Profesional));
        }
        // P_RECOMENDACIONES_RRHH.
        if (p_Recomendaciones_Rrhh != null)
        {
            htItems.put("P_RECOMENDACIONES_RRHH", M4BusinessMethodArg.toString(p_Recomendaciones_Rrhh));
        }
        // P_FEC_ACEPTACION_FEEDBK.
        if (p_Fec_Aceptacion_Feedbk != null)
        {
            htItems.put("P_FEC_ACEPTACION_FEEDBK", M4BusinessMethodArg.toString(p_Fec_Aceptacion_Feedbk));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read P_COMENT.
        sItemName = "P_COMENT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Coment = sItemValue;

        // read P_FEC_REALIZACION.
        sItemName = "P_FEC_REALIZACION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Fec_Realizacion = sItemValue;

        // read P_COMENTARIOS_RRHH.
        sItemName = "P_COMENTARIOS_RRHH";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Comentarios_Rrhh = sItemValue;

        // read P_FEC_ENTREV_FEEDBK.
        sItemName = "P_FEC_ENTREV_FEEDBK";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Fec_Entrev_Feedbk = sItemValue;

        // read P_OBSERVACIONES_RRHH.
        sItemName = "P_OBSERVACIONES_RRHH";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Observaciones_Rrhh = sItemValue;

        // read P_PERFIL_PROFESIONAL.
        sItemName = "P_PERFIL_PROFESIONAL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Perfil_Profesional = sItemValue;

        // read P_RECOMENDACIONES_RRHH.
        sItemName = "P_RECOMENDACIONES_RRHH";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Recomendaciones_Rrhh = sItemValue;

        // read P_FEC_ACEPTACION_FEEDBK.
        sItemName = "P_FEC_ACEPTACION_FEEDBK";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Fec_Aceptacion_Feedbk = sItemValue;


    } /* end of method readOperations */


} /* end of class Csp_Insertar_Datos_FbRecord */

