/**
 * Cyc_Buscador_FaseivRecord.java
 * Self generated code for Bussines Object CYC_BUSCADOR_FASEIV.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_buscador_faseiv;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Buscador_Faseiv.
 * @author Meta4
 */
public 
class Cyc_Buscador_FaseivRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_BUSCADOR_FASEIV";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_BUSCADOR_FASEIV";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Buscador_FaseivRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item CYC_FASE */
    public String cyc_Fase = null;
    private void setcyc_Fase(String ai_value)
    {
        cyc_Fase = ai_value;
    }
    private String getcyc_Fase()
    {
        return cyc_Fase;
    }

    /* item DT_START */
    public Calendar dt_Start = null;
    private void setdt_Start(Calendar ai_value)
    {
        dt_Start = ai_value;
    }
    private Calendar getdt_Start()
    {
        return dt_Start;
    }

    /* item CYC_ID_HR */
    public String cyc_Id_Hr = null;
    private void setcyc_Id_Hr(String ai_value)
    {
        cyc_Id_Hr = ai_value;
    }
    private String getcyc_Id_Hr()
    {
        return cyc_Id_Hr;
    }

    /* item P_NOMCOMPL */
    public String p_Nomcompl = null;
    private void setp_Nomcompl(String ai_value)
    {
        p_Nomcompl = ai_value;
    }
    private String getp_Nomcompl()
    {
        return p_Nomcompl;
    }

    /* item CYC_ID_FASE */
    public String cyc_Id_Fase = null;
    private void setcyc_Id_Fase(String ai_value)
    {
        cyc_Id_Fase = ai_value;
    }
    private String getcyc_Id_Fase()
    {
        return cyc_Id_Fase;
    }

    /* item STD_N_FIRST_NAME */
    public String std_N_First_Name = null;
    private void setstd_N_First_Name(String ai_value)
    {
        std_N_First_Name = ai_value;
    }
    private String getstd_N_First_Name()
    {
        return std_N_First_Name;
    }

    /* item STD_N_MAIDEN_NAME */
    public String std_N_Maiden_Name = null;
    private void setstd_N_Maiden_Name(String ai_value)
    {
        std_N_Maiden_Name = ai_value;
    }
    private String getstd_N_Maiden_Name()
    {
        return std_N_Maiden_Name;
    }

    /* item SSP_PRIMER_APELLIDO */
    public String ssp_Primer_Apellido = null;
    private void setssp_Primer_Apellido(String ai_value)
    {
        ssp_Primer_Apellido = ai_value;
    }
    private String getssp_Primer_Apellido()
    {
        return ssp_Primer_Apellido;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // CYC_FASE.
        if (cyc_Fase != null)
        {
            htItems.put("CYC_FASE", M4BusinessMethodArg.toString(cyc_Fase));
        }
        // DT_START.
        if (dt_Start != null)
        {
            htItems.put("DT_START", M4BusinessMethodArg.toString(dt_Start));
        }
        // CYC_ID_HR.
        if (cyc_Id_Hr != null)
        {
            htItems.put("CYC_ID_HR", M4BusinessMethodArg.toString(cyc_Id_Hr));
        }
        // P_NOMCOMPL.
        if (p_Nomcompl != null)
        {
            htItems.put("P_NOMCOMPL", M4BusinessMethodArg.toString(p_Nomcompl));
        }
        // CYC_ID_FASE.
        if (cyc_Id_Fase != null)
        {
            htItems.put("CYC_ID_FASE", M4BusinessMethodArg.toString(cyc_Id_Fase));
        }
        // STD_N_FIRST_NAME.
        if (std_N_First_Name != null)
        {
            htItems.put("STD_N_FIRST_NAME", M4BusinessMethodArg.toString(std_N_First_Name));
        }
        // STD_N_MAIDEN_NAME.
        if (std_N_Maiden_Name != null)
        {
            htItems.put("STD_N_MAIDEN_NAME", M4BusinessMethodArg.toString(std_N_Maiden_Name));
        }
        // SSP_PRIMER_APELLIDO.
        if (ssp_Primer_Apellido != null)
        {
            htItems.put("SSP_PRIMER_APELLIDO", M4BusinessMethodArg.toString(ssp_Primer_Apellido));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read CYC_FASE.
        sItemName = "CYC_FASE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Fase = sItemValue;

        // read DT_START.
        sItemName = "DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_ID_HR.
        sItemName = "CYC_ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Hr = sItemValue;

        // read P_NOMCOMPL.
        sItemName = "P_NOMCOMPL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Nomcompl = sItemValue;

        // read CYC_ID_FASE.
        sItemName = "CYC_ID_FASE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Fase = sItemValue;

        // read STD_N_FIRST_NAME.
        sItemName = "STD_N_FIRST_NAME";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_First_Name = sItemValue;

        // read STD_N_MAIDEN_NAME.
        sItemName = "STD_N_MAIDEN_NAME";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_Maiden_Name = sItemValue;

        // read SSP_PRIMER_APELLIDO.
        sItemName = "SSP_PRIMER_APELLIDO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        ssp_Primer_Apellido = sItemValue;


    } /* end of method readOperations */


} /* end of class Cyc_Buscador_FaseivRecord */

