/**
 * Cyc_Fase_IiiRecord.java
 * Self generated code for Bussines Object CYC_SERVICIO_FEEDBACK.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_servicio_feedback;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Fase_Iii.
 * @author Meta4
 */
public 
class Cyc_Fase_IiiRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_SERVICIO_FEEDBACK";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_FASE_III";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Fase_IiiRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item CYC_R9 */
    public Double cyc_R9 = null;
    private void setcyc_R9(Double ai_value)
    {
        cyc_R9 = ai_value;
    }
    private Double getcyc_R9()
    {
        return cyc_R9;
    }

    /* item DT_END */
    public Calendar dt_End = null;
    private void setdt_End(Calendar ai_value)
    {
        dt_End = ai_value;
    }
    private Calendar getdt_End()
    {
        return dt_End;
    }

    /* item CYC_R10 */
    public Double cyc_R10 = null;
    private void setcyc_R10(Double ai_value)
    {
        cyc_R10 = ai_value;
    }
    private Double getcyc_R10()
    {
        return cyc_R10;
    }

    /* item CYC_R11 */
    public Double cyc_R11 = null;
    private void setcyc_R11(Double ai_value)
    {
        cyc_R11 = ai_value;
    }
    private Double getcyc_R11()
    {
        return cyc_R11;
    }

    /* item CYC_R12 */
    public Double cyc_R12 = null;
    private void setcyc_R12(Double ai_value)
    {
        cyc_R12 = ai_value;
    }
    private Double getcyc_R12()
    {
        return cyc_R12;
    }

    /* item CYC_FASE */
    public String cyc_Fase = null;
    private void setcyc_Fase(String ai_value)
    {
        cyc_Fase = ai_value;
    }
    private String getcyc_Fase()
    {
        return cyc_Fase;
    }

    /* item DT_START */
    public Calendar dt_Start = null;
    private void setdt_Start(Calendar ai_value)
    {
        dt_Start = ai_value;
    }
    private Calendar getdt_Start()
    {
        return dt_Start;
    }

    /* item CYC_ID_HR */
    public String cyc_Id_Hr = null;
    private void setcyc_Id_Hr(String ai_value)
    {
        cyc_Id_Hr = ai_value;
    }
    private String getcyc_Id_Hr()
    {
        return cyc_Id_Hr;
    }

    /* item CYC_ID_FASE */
    public String cyc_Id_Fase = null;
    private void setcyc_Id_Fase(String ai_value)
    {
        cyc_Id_Fase = ai_value;
    }
    private String getcyc_Id_Fase()
    {
        return cyc_Id_Fase;
    }

    /* item CYC_RANKING */
    public Double cyc_Ranking = null;
    private void setcyc_Ranking(Double ai_value)
    {
        cyc_Ranking = ai_value;
    }
    private Double getcyc_Ranking()
    {
        return cyc_Ranking;
    }

    /* item CYC_ID_FASES */
    public String cyc_Id_Fases = null;
    private void setcyc_Id_Fases(String ai_value)
    {
        cyc_Id_Fases = ai_value;
    }
    private String getcyc_Id_Fases()
    {
        return cyc_Id_Fases;
    }

    /* item CYC_TOEIC_F3 */
    public Double cyc_Toeic_F3 = null;
    private void setcyc_Toeic_F3(Double ai_value)
    {
        cyc_Toeic_F3 = ai_value;
    }
    private Double getcyc_Toeic_F3()
    {
        return cyc_Toeic_F3;
    }

    /* item CYC_FEC_EVALUA */
    public Calendar cyc_Fec_Evalua = null;
    private void setcyc_Fec_Evalua(Calendar ai_value)
    {
        cyc_Fec_Evalua = ai_value;
    }
    private Calendar getcyc_Fec_Evalua()
    {
        return cyc_Fec_Evalua;
    }

    /* item ID_ORGANIZATION */
    public String id_Organization = null;
    private void setid_Organization(String ai_value)
    {
        id_Organization = ai_value;
    }
    private String getid_Organization()
    {
        return id_Organization;
    }

    /* item CYC_ORIENT_RTDOS_F3 */
    public Double cyc_Orient_Rtdos_F3 = null;
    private void setcyc_Orient_Rtdos_F3(Double ai_value)
    {
        cyc_Orient_Rtdos_F3 = ai_value;
    }
    private Double getcyc_Orient_Rtdos_F3()
    {
        return cyc_Orient_Rtdos_F3;
    }

    /* item CYC_PORC_DESARROLLO */
    public Double cyc_Porc_Desarrollo = null;
    private void setcyc_Porc_Desarrollo(Double ai_value)
    {
        cyc_Porc_Desarrollo = ai_value;
    }
    private Double getcyc_Porc_Desarrollo()
    {
        return cyc_Porc_Desarrollo;
    }

    /* item CYC_COMUN_IMP_INF_F3 */
    public Double cyc_Comun_Imp_Inf_F3 = null;
    private void setcyc_Comun_Imp_Inf_F3(Double ai_value)
    {
        cyc_Comun_Imp_Inf_F3 = ai_value;
    }
    private Double getcyc_Comun_Imp_Inf_F3()
    {
        return cyc_Comun_Imp_Inf_F3;
    }

    /* item CYC_CAPAC_ANALITIC_F3 */
    public Double cyc_Capac_Analitic_F3 = null;
    private void setcyc_Capac_Analitic_F3(Double ai_value)
    {
        cyc_Capac_Analitic_F3 = ai_value;
    }
    private Double getcyc_Capac_Analitic_F3()
    {
        return cyc_Capac_Analitic_F3;
    }

    /* item CYC_LIDER_DIR_EQUIP_F3 */
    public Double cyc_Lider_Dir_Equip_F3 = null;
    private void setcyc_Lider_Dir_Equip_F3(Double ai_value)
    {
        cyc_Lider_Dir_Equip_F3 = ai_value;
    }
    private Double getcyc_Lider_Dir_Equip_F3()
    {
        return cyc_Lider_Dir_Equip_F3;
    }

    /* item CYC_VISION_GBAL_EST_F3 */
    public Double cyc_Vision_Gbal_Est_F3 = null;
    private void setcyc_Vision_Gbal_Est_F3(Double ai_value)
    {
        cyc_Vision_Gbal_Est_F3 = ai_value;
    }
    private Double getcyc_Vision_Gbal_Est_F3()
    {
        return cyc_Vision_Gbal_Est_F3;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // CYC_R9.
        if (cyc_R9 != null)
        {
            htItems.put("CYC_R9", M4BusinessMethodArg.toString(cyc_R9));
        }
        // DT_END.
        if (dt_End != null)
        {
            htItems.put("DT_END", M4BusinessMethodArg.toString(dt_End));
        }
        // CYC_R10.
        if (cyc_R10 != null)
        {
            htItems.put("CYC_R10", M4BusinessMethodArg.toString(cyc_R10));
        }
        // CYC_R11.
        if (cyc_R11 != null)
        {
            htItems.put("CYC_R11", M4BusinessMethodArg.toString(cyc_R11));
        }
        // CYC_R12.
        if (cyc_R12 != null)
        {
            htItems.put("CYC_R12", M4BusinessMethodArg.toString(cyc_R12));
        }
        // CYC_FASE.
        if (cyc_Fase != null)
        {
            htItems.put("CYC_FASE", M4BusinessMethodArg.toString(cyc_Fase));
        }
        // DT_START.
        if (dt_Start != null)
        {
            htItems.put("DT_START", M4BusinessMethodArg.toString(dt_Start));
        }
        // CYC_ID_HR.
        if (cyc_Id_Hr != null)
        {
            htItems.put("CYC_ID_HR", M4BusinessMethodArg.toString(cyc_Id_Hr));
        }
        // CYC_ID_FASE.
        if (cyc_Id_Fase != null)
        {
            htItems.put("CYC_ID_FASE", M4BusinessMethodArg.toString(cyc_Id_Fase));
        }
        // CYC_RANKING.
        if (cyc_Ranking != null)
        {
            htItems.put("CYC_RANKING", M4BusinessMethodArg.toString(cyc_Ranking));
        }
        // CYC_ID_FASES.
        if (cyc_Id_Fases != null)
        {
            htItems.put("CYC_ID_FASES", M4BusinessMethodArg.toString(cyc_Id_Fases));
        }
        // CYC_TOEIC_F3.
        if (cyc_Toeic_F3 != null)
        {
            htItems.put("CYC_TOEIC_F3", M4BusinessMethodArg.toString(cyc_Toeic_F3));
        }
        // CYC_FEC_EVALUA.
        if (cyc_Fec_Evalua != null)
        {
            htItems.put("CYC_FEC_EVALUA", M4BusinessMethodArg.toString(cyc_Fec_Evalua));
        }
        // ID_ORGANIZATION.
        if (id_Organization != null)
        {
            htItems.put("ID_ORGANIZATION", M4BusinessMethodArg.toString(id_Organization));
        }
        // CYC_ORIENT_RTDOS_F3.
        if (cyc_Orient_Rtdos_F3 != null)
        {
            htItems.put("CYC_ORIENT_RTDOS_F3", M4BusinessMethodArg.toString(cyc_Orient_Rtdos_F3));
        }
        // CYC_PORC_DESARROLLO.
        if (cyc_Porc_Desarrollo != null)
        {
            htItems.put("CYC_PORC_DESARROLLO", M4BusinessMethodArg.toString(cyc_Porc_Desarrollo));
        }
        // CYC_COMUN_IMP_INF_F3.
        if (cyc_Comun_Imp_Inf_F3 != null)
        {
            htItems.put("CYC_COMUN_IMP_INF_F3", M4BusinessMethodArg.toString(cyc_Comun_Imp_Inf_F3));
        }
        // CYC_CAPAC_ANALITIC_F3.
        if (cyc_Capac_Analitic_F3 != null)
        {
            htItems.put("CYC_CAPAC_ANALITIC_F3", M4BusinessMethodArg.toString(cyc_Capac_Analitic_F3));
        }
        // CYC_LIDER_DIR_EQUIP_F3.
        if (cyc_Lider_Dir_Equip_F3 != null)
        {
            htItems.put("CYC_LIDER_DIR_EQUIP_F3", M4BusinessMethodArg.toString(cyc_Lider_Dir_Equip_F3));
        }
        // CYC_VISION_GBAL_EST_F3.
        if (cyc_Vision_Gbal_Est_F3 != null)
        {
            htItems.put("CYC_VISION_GBAL_EST_F3", M4BusinessMethodArg.toString(cyc_Vision_Gbal_Est_F3));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read CYC_R9.
        sItemName = "CYC_R9";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_R9 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read DT_END.
        sItemName = "DT_END";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_End = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_R10.
        sItemName = "CYC_R10";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_R10 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_R11.
        sItemName = "CYC_R11";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_R11 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_R12.
        sItemName = "CYC_R12";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_R12 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_FASE.
        sItemName = "CYC_FASE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Fase = sItemValue;

        // read DT_START.
        sItemName = "DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_ID_HR.
        sItemName = "CYC_ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Hr = sItemValue;

        // read CYC_ID_FASE.
        sItemName = "CYC_ID_FASE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Fase = sItemValue;

        // read CYC_RANKING.
        sItemName = "CYC_RANKING";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Ranking = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_ID_FASES.
        sItemName = "CYC_ID_FASES";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Fases = sItemValue;

        // read CYC_TOEIC_F3.
        sItemName = "CYC_TOEIC_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Toeic_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_FEC_EVALUA.
        sItemName = "CYC_FEC_EVALUA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Fec_Evalua = M4BusinessMethodArg.toCalendar(sItemValue);

        // read ID_ORGANIZATION.
        sItemName = "ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Organization = sItemValue;

        // read CYC_ORIENT_RTDOS_F3.
        sItemName = "CYC_ORIENT_RTDOS_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Orient_Rtdos_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_PORC_DESARROLLO.
        sItemName = "CYC_PORC_DESARROLLO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Porc_Desarrollo = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_COMUN_IMP_INF_F3.
        sItemName = "CYC_COMUN_IMP_INF_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Comun_Imp_Inf_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_CAPAC_ANALITIC_F3.
        sItemName = "CYC_CAPAC_ANALITIC_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Capac_Analitic_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_LIDER_DIR_EQUIP_F3.
        sItemName = "CYC_LIDER_DIR_EQUIP_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Lider_Dir_Equip_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_VISION_GBAL_EST_F3.
        sItemName = "CYC_VISION_GBAL_EST_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Vision_Gbal_Est_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);


    } /* end of method readOperations */


} /* end of class Cyc_Fase_IiiRecord */

