/**
 * Cyc_Feed_BackRecord.java
 * Self generated code for Bussines Object CYC_SERVICIO_FEEDBACK.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_servicio_feedback;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Feed_Back.
 * @author Meta4
 */
public 
class Cyc_Feed_BackRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_SERVICIO_FEEDBACK";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_FEED_BACK";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Feed_BackRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item DT_END */
    public Calendar dt_End = null;
    private void setdt_End(Calendar ai_value)
    {
        dt_End = ai_value;
    }
    private Calendar getdt_End()
    {
        return dt_End;
    }

    /* item DT_START */
    public Calendar dt_Start = null;
    private void setdt_Start(Calendar ai_value)
    {
        dt_Start = ai_value;
    }
    private Calendar getdt_Start()
    {
        return dt_Start;
    }

    /* item CYC_ID_HR */
    public String cyc_Id_Hr = null;
    private void setcyc_Id_Hr(String ai_value)
    {
        cyc_Id_Hr = ai_value;
    }
    private String getcyc_Id_Hr()
    {
        return cyc_Id_Hr;
    }

    /* item CYC_COMENT */
    public String cyc_Coment = null;
    private void setcyc_Coment(String ai_value)
    {
        cyc_Coment = ai_value;
    }
    private String getcyc_Coment()
    {
        return cyc_Coment;
    }

    /* item CYC_ESTADO */
    public String cyc_Estado = null;
    private void setcyc_Estado(String ai_value)
    {
        cyc_Estado = ai_value;
    }
    private String getcyc_Estado()
    {
        return cyc_Estado;
    }

    /* item CYC_ID_FASE */
    public String cyc_Id_Fase = null;
    private void setcyc_Id_Fase(String ai_value)
    {
        cyc_Id_Fase = ai_value;
    }
    private String getcyc_Id_Fase()
    {
        return cyc_Id_Fase;
    }

    /* item ID_ORGANIZATION */
    public String id_Organization = null;
    private void setid_Organization(String ai_value)
    {
        id_Organization = ai_value;
    }
    private String getid_Organization()
    {
        return id_Organization;
    }

    /* node CYC_FASE_I */
    public Cyc_Fase_IBlock Cyc_Fase_I = null;
    private void setcyc_Fase_I(Cyc_Fase_IBlock ai_value)
    {
        Cyc_Fase_I = ai_value;
    }
    private Cyc_Fase_IBlock getCyc_Fase_I()
    {
        return Cyc_Fase_I;
    }

    /* node CYC_FASE_II */
    public Cyc_Fase_IiBlock Cyc_Fase_Ii = null;
    private void setcyc_Fase_Ii(Cyc_Fase_IiBlock ai_value)
    {
        Cyc_Fase_Ii = ai_value;
    }
    private Cyc_Fase_IiBlock getCyc_Fase_Ii()
    {
        return Cyc_Fase_Ii;
    }

    /* node CYC_FASE_III */
    public Cyc_Fase_IiiBlock Cyc_Fase_Iii = null;
    private void setcyc_Fase_Iii(Cyc_Fase_IiiBlock ai_value)
    {
        Cyc_Fase_Iii = ai_value;
    }
    private Cyc_Fase_IiiBlock getCyc_Fase_Iii()
    {
        return Cyc_Fase_Iii;
    }

    /* node CYC_PUNTOS_MEJORA */
    public Cyc_Puntos_MejoraBlock Cyc_Puntos_Mejora = null;
    private void setcyc_Puntos_Mejora(Cyc_Puntos_MejoraBlock ai_value)
    {
        Cyc_Puntos_Mejora = ai_value;
    }
    private Cyc_Puntos_MejoraBlock getCyc_Puntos_Mejora()
    {
        return Cyc_Puntos_Mejora;
    }

    /* node CYC_PUNTOS_FUERTES */
    public Cyc_Puntos_FuertesBlock Cyc_Puntos_Fuertes = null;
    private void setcyc_Puntos_Fuertes(Cyc_Puntos_FuertesBlock ai_value)
    {
        Cyc_Puntos_Fuertes = ai_value;
    }
    private Cyc_Puntos_FuertesBlock getCyc_Puntos_Fuertes()
    {
        return Cyc_Puntos_Fuertes;
    }

    /* node CYC_EQUIVALENCIA_CAMPO_FASE */
    public Cyc_Equivalencia_Campo_FaseBlock Cyc_Equivalencia_Campo_Fase = null;
    private void setcyc_Equivalencia_Campo_Fase(Cyc_Equivalencia_Campo_FaseBlock ai_value)
    {
        Cyc_Equivalencia_Campo_Fase = ai_value;
    }
    private Cyc_Equivalencia_Campo_FaseBlock getCyc_Equivalencia_Campo_Fase()
    {
        return Cyc_Equivalencia_Campo_Fase;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // DT_END.
        if (dt_End != null)
        {
            htItems.put("DT_END", M4BusinessMethodArg.toString(dt_End));
        }
        // DT_START.
        if (dt_Start != null)
        {
            htItems.put("DT_START", M4BusinessMethodArg.toString(dt_Start));
        }
        // CYC_ID_HR.
        if (cyc_Id_Hr != null)
        {
            htItems.put("CYC_ID_HR", M4BusinessMethodArg.toString(cyc_Id_Hr));
        }
        // CYC_COMENT.
        if (cyc_Coment != null)
        {
            htItems.put("CYC_COMENT", M4BusinessMethodArg.toString(cyc_Coment));
        }
        // CYC_ESTADO.
        if (cyc_Estado != null)
        {
            htItems.put("CYC_ESTADO", M4BusinessMethodArg.toString(cyc_Estado));
        }
        // CYC_ID_FASE.
        if (cyc_Id_Fase != null)
        {
            htItems.put("CYC_ID_FASE", M4BusinessMethodArg.toString(cyc_Id_Fase));
        }
        // ID_ORGANIZATION.
        if (id_Organization != null)
        {
            htItems.put("ID_ORGANIZATION", M4BusinessMethodArg.toString(id_Organization));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

        // write data for node CYC_FASE_I.
        if ( Cyc_Fase_I != null) 
        {
           Cyc_Fase_I.writeOperations(ai_m4Op);
        }

        // write data for node CYC_FASE_II.
        if ( Cyc_Fase_Ii != null) 
        {
           Cyc_Fase_Ii.writeOperations(ai_m4Op);
        }

        // write data for node CYC_FASE_III.
        if ( Cyc_Fase_Iii != null) 
        {
           Cyc_Fase_Iii.writeOperations(ai_m4Op);
        }

        // write data for node CYC_PUNTOS_MEJORA.
        if ( Cyc_Puntos_Mejora != null) 
        {
           Cyc_Puntos_Mejora.writeOperations(ai_m4Op);
        }

        // write data for node CYC_PUNTOS_FUERTES.
        if ( Cyc_Puntos_Fuertes != null) 
        {
           Cyc_Puntos_Fuertes.writeOperations(ai_m4Op);
        }

        // write data for node CYC_EQUIVALENCIA_CAMPO_FASE.
        if ( Cyc_Equivalencia_Campo_Fase != null) 
        {
           Cyc_Equivalencia_Campo_Fase.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read DT_END.
        sItemName = "DT_END";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_End = M4BusinessMethodArg.toCalendar(sItemValue);

        // read DT_START.
        sItemName = "DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_ID_HR.
        sItemName = "CYC_ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Hr = sItemValue;

        // read CYC_COMENT.
        sItemName = "CYC_COMENT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Coment = sItemValue;

        // read CYC_ESTADO.
        sItemName = "CYC_ESTADO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Estado = sItemValue;

        // read CYC_ID_FASE.
        sItemName = "CYC_ID_FASE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Fase = sItemValue;

        // read ID_ORGANIZATION.
        sItemName = "ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Organization = sItemValue;

        // read data for node CYC_FASE_I.
        Cyc_Fase_I = new Cyc_Fase_IBlock();
        Cyc_Fase_I.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_Fase_IBlock.NODE_NAME));

        // read data for node CYC_FASE_II.
        Cyc_Fase_Ii = new Cyc_Fase_IiBlock();
        Cyc_Fase_Ii.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_Fase_IiBlock.NODE_NAME));

        // read data for node CYC_FASE_III.
        Cyc_Fase_Iii = new Cyc_Fase_IiiBlock();
        Cyc_Fase_Iii.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_Fase_IiiBlock.NODE_NAME));

        // read data for node CYC_PUNTOS_MEJORA.
        Cyc_Puntos_Mejora = new Cyc_Puntos_MejoraBlock();
        Cyc_Puntos_Mejora.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_Puntos_MejoraBlock.NODE_NAME));

        // read data for node CYC_PUNTOS_FUERTES.
        Cyc_Puntos_Fuertes = new Cyc_Puntos_FuertesBlock();
        Cyc_Puntos_Fuertes.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_Puntos_FuertesBlock.NODE_NAME));

        // read data for node CYC_EQUIVALENCIA_CAMPO_FASE.
        Cyc_Equivalencia_Campo_Fase = new Cyc_Equivalencia_Campo_FaseBlock();
        Cyc_Equivalencia_Campo_Fase.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_Equivalencia_Campo_FaseBlock.NODE_NAME));


    } /* end of method readOperations */


} /* end of class Cyc_Feed_BackRecord */

