//Original code file: g.bar.raw.js
//Use the above mentioned file for modifications or debugging.

(function(){function B(g,f,h,b,a,j,p,E){var l;if(a&&!b||!a&&!h)return p?"":E.path();j={round:"round",sharp:"sharp",soft:"soft",square:"square"}[j]||"square";b=Math.round(b);h=Math.round(h);g=Math.round(g);f=Math.round(f);switch(j){case "round":a?(a=~~(h/2),l=b<a?["M",g-~~(h/2),f,"l",0,0,"a",~~(h/2),b,0,0,1,h,0,"l",0,0,"z"]:["M",g-a,f,"l",0,a-b,"a",a,a,0,1,1,h,0,"l",0,b-a,"z"]):(a=~~(b/2),l=h<a?["M",g+0.5,f+0.5-~~(b/2),"l",0,0,"a",h,~~(b/2),0,0,1,0,b,"l",0,0,"z"]:["M",g+0.5,f+0.5-a,"l",h-a,0,"a",a,
a,0,1,1,0,b,"l",a-h,0,"z"]);break;case "sharp":a?(a=~~(h/2),l=["M",g+a,f,"l",-h,0,0,-G(b-a,0),a,-A(a,b),a,A(a,b),a,"z"]):(a=~~(b/2),l=["M",g,f+a,"l",0,-b,G(h-a,0),0,A(a,h),a,-A(a,h),a+(2*a<b),"z"]);break;case "square":l=a?["M",g+~~(h/2),f,"l",1-h,0,0,-b,h-1,0,"z"]:["M",g,f+~~(b/2),"l",0,-b,h,0,0,b,"z"];break;case "soft":a?(a=A(Math.round(h/5),b),l=["M",g-~~(h/2),f,"l",0,a-b,"a",a,a,0,0,1,a,-a,"l",h-2*a,0,"a",a,a,0,0,1,a,a,"l",0,b-a,"z"]):(a=A(h,Math.round(b/5)),l=["M",g+0.5,f+0.5-~~(b/2),"l",h-a,
0,"a",a,a,0,0,1,a,a,"l",0,b-2*a,"a",a,a,0,0,1,-a,a,"l",a-h,0,"z"])}return p?l.join(","):E.path(l)}function C(g,f,h,b,a,j,p){p=p||{};var E=p.type||"square",l=parseFloat(p.gutter||"20%"),u=g.set(),w=g.set(),r=g.set(),v=g.set(),y=Math.max.apply(Math,j),e=[],n=0,A=p.colors||this.colors,t=j.length;if(Raphael.is(j[0],"array")){for(var y=[],n=t,t=0,c=j.length;c--;)w.push(g.set()),y.push(Math.max.apply(Math,j[c])),t=Math.max(t,j[c].length);if(p.stacked)for(c=t;c--;){for(var m=0,k=j.length;k--;)m+=+j[k][c]||
0;e.push(m)}for(c=j.length;c--;)if(j[c].length<t)for(k=t;k--;)j[c].push(0);y=Math.max.apply(Math,p.stacked?e:y)}y=p.to||y;b=100*(b/(t*(100+l)+l));var l=b*l/100,s=null==p.vgutter?20:p.vgutter,e=[],m=f+l,x=(a-2*s)/y;p.stretch||(l=Math.round(l),b=Math.floor(b));!p.stacked&&(b/=n||1);for(c=0;c<t;c++){e=[];for(k=0;k<(n||1);k++){var d=Math.round((n?j[k][c]:j[c])*x),z=h+a-s-d,q=B(Math.round(m+b/2),z+d,b,d,!0,E,null,g).attr({stroke:"none",fill:A[n?k:c]});n?w[k].push(q):w.push(q);q.y=z;q.x=Math.round(m+b/
2);q.w=b;q.h=d;q.value=n?j[k][c]:j[c];p.stacked?e.push(q):m+=b}if(p.stacked){v.push(k=g.rect(e[0].x-e[0].w/2,h,b,a).attr(this.shim));k.bars=g.set();for(var z=0,D=e.length;D--;)e[D].toFront();for(var D=0,C=e.length;D<C;D++){var q=e[D],d=(z+q.value)*x,I=B(q.x,h+a-s-0.5*!!z,b,d,!0,E,1,g);k.bars.push(q);z&&q.attr({path:I});q.h=d;q.y=h+a-s-0.5*!!z-d;r.push(d=g.rect(q.x-q.w/2,q.y,b,q.value*x).attr(this.shim));d.bar=q;d.value=q.value;z+=q.value}m+=b}m+=l}v.toFront();m=f+l;if(!p.stacked)for(c=0;c<t;c++){for(k=
0;k<(n||1);k++)r.push(d=g.rect(Math.round(m),h+s,b,a-s).attr(this.shim)),d.bar=n?w[k][c]:w[c],d.value=d.bar.value,m+=b;m+=l}u.label=function(b,c,k){b=b||[];this.labels=g.set();var d,l=-Infinity;if(p.stacked)for(var f=0;f<t;f++)for(var e=c=0;e<(n||1);e++){if(c+=n?j[e][f]:j[f],e==n-1){d=labelise(b[f],c,y);d=g.text(w[f*(n||1)+e].x,h+a-s/2,d).attr(k).insertBefore(r[f*(n||1)+e]);var m=d.getBBox();m.x-7<l?d.remove():(this.labels.push(d),l=m.x+m.width)}}else for(f=0;f<t;f++)for(e=0;e<(n||1);e++)d=labelise(n?
b[e]&&b[e][f]:b[f],n?j[e][f]:j[f],y),d=g.text(w[f*(n||1)+e].x,c?h+a-s/2:w[f*(n||1)+e].y-10||h+a-s/2-20,d).attr(k).insertBefore(r[f*(n||1)+e]),m=d.getBBox(),m.x-7<l?d.remove():(this.labels.push(d),l=m.x+m.width);return this};u.hover=function(a,b){v.hide();r.show();r.mouseover(a).mouseout(b);return this};u.hoverColumn=function(a,b){r.hide();v.show();v.mouseover(a).mouseout(b||function(){});return this};u.click=function(a){v.hide();r.show();r.click(a);return this};u.each=function(a){if(!Raphael.is(a,
"function"))return this;for(var b=r.length;b--;)a.call(r[b]);return this};u.eachColumn=function(a){if(!Raphael.is(a,"function"))return this;for(var b=v.length;b--;)a.call(v[b]);return this};u.clickColumn=function(a){r.hide();v.show();v.click(a);return this};u.push(w,r,v);u.bars=w;u.covers=r;return u}function H(g,f,h,b,a,j,p){p=p||{};var A=p.type||"square",l=parseFloat(p.gutter||"20%"),u=g.set(),w=g.set(),r=g.set(),v=g.set(),y=Math.max.apply(Math,j),e=[],n=0,C=p.colors||this.colors,t=j.length;if(Raphael.is(j[0],
"array")){for(var y=[],n=t,t=0,c=j.length;c--;)w.push(g.set()),y.push(Math.max.apply(Math,j[c])),t=Math.max(t,j[c].length);if(p.stacked)for(c=t;c--;){for(var m=0,k=j.length;k--;)m+=+j[k][c]||0;e.push(m)}for(c=j.length;c--;)if(j[c].length<t)for(k=t;k--;)j[c].push(0);y=Math.max.apply(Math,p.stacked?e:y)}var y=p.to||y,s=Math.floor(100*(a/(t*(100+l)+l)));a=Math.floor(s*l/100);l=[];e=h+a;m=(b-1)/y;!p.stacked&&(s/=n||1);for(c=0;c<t;c++){l=[];for(k=0;k<(n||1);k++){var x=n?j[k][c]:j[c],d=B(f,e+s/2,Math.round(x*
m),s-1,!1,A,null,g).attr({stroke:"none",fill:C[n?k:c]});n?w[k].push(d):w.push(d);d.x=f+Math.round(x*m);d.y=e+s/2;d.w=Math.round(x*m);d.h=s;d.value=+x;p.stacked?l.push(d):e+=s}if(p.stacked){k=g.rect(f,l[0].y-l[0].h/2,b,s).attr(this.shim);v.push(k);k.bars=g.set();for(var z=0,q=l.length;q--;)l[q].toFront();for(var q=0,D=l.length;q<D;q++){var d=l[q],x=Math.round((z+d.value)*m),G=B(f,d.y,x,s-1,!1,A,1,g);k.bars.push(d);z&&d.attr({path:G});d.w=x;d.x=f+x;r.push(x=g.rect(f+z*m,d.y-d.h/2,d.value*m,s).attr(this.shim));
x.bar=d;z+=d.value}e+=s}e+=a}v.toFront();e=h+a;if(!p.stacked)for(c=0;c<t;c++){for(k=0;k<(n||1);k++)x=g.rect(f,e,b,s).attr(this.shim),r.push(x),x.bar=n?w[k][c]:w[c],x.value=x.bar.value,e+=s;e+=a}u.label=function(a,b){a=a||[];this.labels=g.set();for(var c=0;c<t;c++)for(var d=0;d<n;d++){var e=g.labelise(n?a[d]&&a[d][c]:a[c],n?j[d][c]:j[c],y),h=b?"end":"start";this.labels.push(e=g.text(b?w[c*(n||1)+d].x-s/2+3:f+5,w[c*(n||1)+d].y,e).attr(txtattr).attr({"text-anchor":h}).insertBefore(r[0]));e.getBBox().x<
f+5?e.attr({x:f+5,"text-anchor":"start"}):w[c*(n||1)+d].label=e}return this};u.hover=function(a,b){v.hide();r.show();r.mouseover(a).mouseout(b||function(){});return this};u.hoverColumn=function(a,b){r.hide();v.show();v.mouseover(a).mouseout(b||function(){});return this};u.each=function(a){if(!Raphael.is(a,"function"))return this;for(var b=r.length;b--;)a.call(r[b]);return this};u.eachColumn=function(a){if(!Raphael.is(a,"function"))return this;for(var b=v.length;b--;)a.call(v[b]);return this};u.click=
function(a){v.hide();r.show();r.click(a);return this};u.clickColumn=function(a){r.hide();v.show();v.click(a);return this};u.push(w,r,v);u.bars=w;u.covers=r;return u}var A=Math.min,G=Math.max,F=function(){};F.prototype=Raphael.g;H.prototype=C.prototype=new F;Raphael.fn.barchart=function(g,f,h,b,a,j){return new C(this,g,f,h,b,a,j)};Raphael.fn.hbarchart=function(g,f,h,b,a,j){return new H(this,g,f,h,b,a,j)}})();
function labelise(B,C,H){return B?(B+"").replace(/(##+(?:\.#+)?)|(%%+(?:\.%+)?)/g,function(A,B,F){if(B)return(+C).toFixed(B.replace(/^#+\.?/g,"").length);if(F)return(100*C/H).toFixed(F.replace(/^%+\.?/g,"").length)+"%"}):(+C).toFixed(0)};
