/**
 * Csp_Guardar_FeedbackBlock.java
 * Self generated code for Bussines Object CSP_GUARDAR_FEEDBACK.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.csp_guardar_feedback;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Csp_Guardar_Feedback.
 * @author Meta4
 */
public 
class Csp_Guardar_FeedbackBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_GUARDAR_FEEDBACK";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_GUARDAR_FEEDBACK";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Guardar_FeedbackBlock.class.getName());

    /* item P_AVANZAR */
    public Double p_Avanzar = null;
    private void setp_Avanzar(Double ai_value)
    {
        p_Avanzar = ai_value;
    }
    private Double getp_Avanzar()
    {
        return p_Avanzar;
    }

    /* the recordset */
    public Csp_Guardar_FeedbackRecord[] Csp_Guardar_FeedbackRecordSet = null;
    private void setCsp_Guardar_FeedbackRecordSet(Csp_Guardar_FeedbackRecord[] ai_arg)
    {
        Csp_Guardar_FeedbackRecordSet = ai_arg;
    }
    private Csp_Guardar_FeedbackRecord[] getCsp_Guardar_FeedbackRecordSet()
    {
        return Csp_Guardar_FeedbackRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Csp_Guardar_FeedbackBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // P_AVANZAR.
		if (p_Avanzar != null)
    	{
			htItems.put("P_AVANZAR", M4BusinessMethodArg.toString(p_Avanzar));
    	}


        // insert 'block scope' values in CSP_GUARDAR_FEEDBACK.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in CSP_GUARDAR_FEEDBACK.
        if (Csp_Guardar_FeedbackRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Csp_Guardar_FeedbackRecordSet.length; i++)
        {
            Csp_Guardar_FeedbackRecord record = Csp_Guardar_FeedbackRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in CSP_GUARDAR_FEEDBACK.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;

        // read P_AVANZAR.
        sItemName = "P_AVANZAR";
        nItem = ai_xml.findItem(ai_node, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Avanzar = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Csp_Guardar_FeedbackRecordSet = new Csp_Guardar_FeedbackRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Csp_Guardar_FeedbackRecord record = new Csp_Guardar_FeedbackRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Csp_Guardar_FeedbackRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Csp_Guardar_FeedbackBlock */

