/**
 * Csp_Pasar_EstadoRecord.java
 * Self generated code for Bussines Object CSP_GUARDAR_FEEDBACK.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_guardar_feedback;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Pasar_Estado.
 * @author Meta4
 */
public 
class Csp_Pasar_EstadoRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_GUARDAR_FEEDBACK";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_PASAR_ESTADO";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Pasar_EstadoRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item CYC_INDEX */
    public Double cyc_Index = null;
    private void setcyc_Index(Double ai_value)
    {
        cyc_Index = ai_value;
    }
    private Double getcyc_Index()
    {
        return cyc_Index;
    }

    /* item CYC_ESTADO */
    public String cyc_Estado = null;
    private void setcyc_Estado(String ai_value)
    {
        cyc_Estado = ai_value;
    }
    private String getcyc_Estado()
    {
        return cyc_Estado;
    }

    /* item CYC_NM_ESTADO */
    public String cyc_Nm_Estado = null;
    private void setcyc_Nm_Estado(String ai_value)
    {
        cyc_Nm_Estado = ai_value;
    }
    private String getcyc_Nm_Estado()
    {
        return cyc_Nm_Estado;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // CYC_INDEX.
        if (cyc_Index != null)
        {
            htItems.put("CYC_INDEX", M4BusinessMethodArg.toString(cyc_Index));
        }
        // CYC_ESTADO.
        if (cyc_Estado != null)
        {
            htItems.put("CYC_ESTADO", M4BusinessMethodArg.toString(cyc_Estado));
        }
        // CYC_NM_ESTADO.
        if (cyc_Nm_Estado != null)
        {
            htItems.put("CYC_NM_ESTADO", M4BusinessMethodArg.toString(cyc_Nm_Estado));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read CYC_INDEX.
        sItemName = "CYC_INDEX";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Index = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_ESTADO.
        sItemName = "CYC_ESTADO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Estado = sItemValue;

        // read CYC_NM_ESTADO.
        sItemName = "CYC_NM_ESTADO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Nm_Estado = sItemValue;


    } /* end of method readOperations */


} /* end of class Csp_Pasar_EstadoRecord */

