
;--------------------------------------------------------------------------------------
;  - file: WEB-INF/classes/com/meta4/soapservices/services/rpc/CSP_GUARDAR_FEEDBACK/service.properties
;  - description: Self generated service properties file for CSP_GUARDAR_FEEDBACK Soap Service
;  -
;  - Copyright Meta4 Spain S.A.
;  - Centro Europa Empresarial - Edf. Roma
;  - C/ Rozabella, 8
;  - 28230 Las Rozas - Madrid
;  - Spain
;  -
;--------------------------------------------------------------------------------------- 

metadate=2020-04-24 12:12:25

