/**
 * Csp_Lista_Proc_EvaluadorRecord.java
 * Self generated code for Bussines Object CSP_LISTA_PROC.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_lista_proc;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Lista_Proc_Evaluador.
 * @author Meta4
 */
public 
class Csp_Lista_Proc_EvaluadorRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_LISTA_PROC";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_LISTA_PROC_EVALUADOR";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Lista_Proc_EvaluadorRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item ID_ORGANIZATION */
    public String id_Organization = null;
    private void setid_Organization(String ai_value)
    {
        id_Organization = ai_value;
    }
    private String getid_Organization()
    {
        return id_Organization;
    }

    /* item CSP_ID_EVAL_PLAN */
    public String csp_Id_Eval_Plan = null;
    private void setcsp_Id_Eval_Plan(String ai_value)
    {
        csp_Id_Eval_Plan = ai_value;
    }
    private String getcsp_Id_Eval_Plan()
    {
        return csp_Id_Eval_Plan;
    }

    /* item CSP_NM_EVAL_PROC */
    public String csp_Nm_Eval_Proc = null;
    private void setcsp_Nm_Eval_Proc(String ai_value)
    {
        csp_Nm_Eval_Proc = ai_value;
    }
    private String getcsp_Nm_Eval_Proc()
    {
        return csp_Nm_Eval_Proc;
    }

    /* item CSP_DT_START_PROC */
    public Calendar csp_Dt_Start_Proc = null;
    private void setcsp_Dt_Start_Proc(Calendar ai_value)
    {
        csp_Dt_Start_Proc = ai_value;
    }
    private Calendar getcsp_Dt_Start_Proc()
    {
        return csp_Dt_Start_Proc;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // ID_ORGANIZATION.
        if (id_Organization != null)
        {
            htItems.put("ID_ORGANIZATION", M4BusinessMethodArg.toString(id_Organization));
        }
        // CSP_ID_EVAL_PLAN.
        if (csp_Id_Eval_Plan != null)
        {
            htItems.put("CSP_ID_EVAL_PLAN", M4BusinessMethodArg.toString(csp_Id_Eval_Plan));
        }
        // CSP_NM_EVAL_PROC.
        if (csp_Nm_Eval_Proc != null)
        {
            htItems.put("CSP_NM_EVAL_PROC", M4BusinessMethodArg.toString(csp_Nm_Eval_Proc));
        }
        // CSP_DT_START_PROC.
        if (csp_Dt_Start_Proc != null)
        {
            htItems.put("CSP_DT_START_PROC", M4BusinessMethodArg.toString(csp_Dt_Start_Proc));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read ID_ORGANIZATION.
        sItemName = "ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Organization = sItemValue;

        // read CSP_ID_EVAL_PLAN.
        sItemName = "CSP_ID_EVAL_PLAN";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Eval_Plan = sItemValue;

        // read CSP_NM_EVAL_PROC.
        sItemName = "CSP_NM_EVAL_PROC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Nm_Eval_Proc = sItemValue;

        // read CSP_DT_START_PROC.
        sItemName = "CSP_DT_START_PROC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Dt_Start_Proc = M4BusinessMethodArg.toCalendar(sItemValue);


    } /* end of method readOperations */


} /* end of class Csp_Lista_Proc_EvaluadorRecord */

