/**
 * M4_Pnet_Initial_DataBlock.java
 * Self generated code for Bussines Object M4_PNET_INITIAL_DATA.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.m4_pnet_initial_data;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node M4_Pnet_Initial_Data.
 * @author Meta4
 */
public 
class M4_Pnet_Initial_DataBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "M4_PNET_INITIAL_DATA";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "M4_PNET_INITIAL_DATA";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(M4_Pnet_Initial_DataBlock.class.getName());

    /* item WORKLIST_ITEM_NUMBER */
    public Double worklist_Item_Number = null;
    private void setworklist_Item_Number(Double ai_value)
    {
        worklist_Item_Number = ai_value;
    }
    private Double getworklist_Item_Number()
    {
        return worklist_Item_Number;
    }

    /* the recordset */
    public M4_Pnet_Initial_DataRecord[] M4_Pnet_Initial_DataRecordSet = null;
    private void setM4_Pnet_Initial_DataRecordSet(M4_Pnet_Initial_DataRecord[] ai_arg)
    {
        M4_Pnet_Initial_DataRecordSet = ai_arg;
    }
    private M4_Pnet_Initial_DataRecord[] getM4_Pnet_Initial_DataRecordSet()
    {
        return M4_Pnet_Initial_DataRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("M4_Pnet_Initial_DataBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // WORKLIST_ITEM_NUMBER.
		if (worklist_Item_Number != null)
    	{
			htItems.put("WORKLIST_ITEM_NUMBER", M4BusinessMethodArg.toString(worklist_Item_Number));
    	}


        // insert 'block scope' values in M4_PNET_INITIAL_DATA.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in M4_PNET_INITIAL_DATA.
        if (M4_Pnet_Initial_DataRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<M4_Pnet_Initial_DataRecordSet.length; i++)
        {
            M4_Pnet_Initial_DataRecord record = M4_Pnet_Initial_DataRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in M4_PNET_INITIAL_DATA.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;

        // read WORKLIST_ITEM_NUMBER.
        sItemName = "WORKLIST_ITEM_NUMBER";
        nItem = ai_xml.findItem(ai_node, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        worklist_Item_Number = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        M4_Pnet_Initial_DataRecordSet = new M4_Pnet_Initial_DataRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            M4_Pnet_Initial_DataRecord record = new M4_Pnet_Initial_DataRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      M4_Pnet_Initial_DataRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class M4_Pnet_Initial_DataBlock */

