/**
 * Cys_S_Carga_Fases_PBlock.java
 * Self generated code for Bussines Object CYC_S_CARGA_FASES_P.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.cyc_s_carga_fases_p;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Cys_S_Carga_Fases_P.
 * @author Meta4
 */
public 
class Cys_S_Carga_Fases_PBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_S_CARGA_FASES_P";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYS_S_CARGA_FASES_P";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cys_S_Carga_Fases_PBlock.class.getName());

    /* item CYC_P_ID_HR */
    public String cyc_P_Id_Hr = null;
    private void setcyc_P_Id_Hr(String ai_value)
    {
        cyc_P_Id_Hr = ai_value;
    }
    private String getcyc_P_Id_Hr()
    {
        return cyc_P_Id_Hr;
    }

    /* the recordset */
    public Cys_S_Carga_Fases_PRecord[] Cys_S_Carga_Fases_PRecordSet = null;
    private void setCys_S_Carga_Fases_PRecordSet(Cys_S_Carga_Fases_PRecord[] ai_arg)
    {
        Cys_S_Carga_Fases_PRecordSet = ai_arg;
    }
    private Cys_S_Carga_Fases_PRecord[] getCys_S_Carga_Fases_PRecordSet()
    {
        return Cys_S_Carga_Fases_PRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Cys_S_Carga_Fases_PBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // CYC_P_ID_HR.
        if (cyc_P_Id_Hr != null)
        {
            htItems.put("CYC_P_ID_HR", M4BusinessMethodArg.toString(cyc_P_Id_Hr));
        }

        // insert 'block scope' values in CYS_S_CARGA_FASES_P.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in CYS_S_CARGA_FASES_P.
        if (Cys_S_Carga_Fases_PRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Cys_S_Carga_Fases_PRecordSet.length; i++)
        {
            Cys_S_Carga_Fases_PRecord record = Cys_S_Carga_Fases_PRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in CYS_S_CARGA_FASES_P.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;

        // read CYC_P_ID_HR.
        sItemName = "CYC_P_ID_HR";
        nItem = ai_xml.findItem(ai_node, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_P_Id_Hr = sItemValue;

        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Cys_S_Carga_Fases_PRecordSet = new Cys_S_Carga_Fases_PRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Cys_S_Carga_Fases_PRecord record = new Cys_S_Carga_Fases_PRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Cys_S_Carga_Fases_PRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Cys_S_Carga_Fases_PBlock */

