
;--------------------------------------------------------------------------------------
;  - file: WEB-INF/classes/com/meta4/soapservices/services/rpc/PLCO_ES_WS_APP_USER/service.properties
;  - description: Self generated service properties file for PLCO_ES_WS_APP_USER Soap Service
;  -
;  - Copyright Meta4 Spain S.A.
;  - Centro Europa Empresarial - Edf. Roma
;  - C/ Rozabella, 8
;  - 28230 Las Rozas - Madrid
;  - Spain
;  -
;--------------------------------------------------------------------------------------- 

metadate=2018-07-30 09:44:23

