/**
 * Csp_Guardar_CompetenciasRecord.java
 * Self generated code for Bussines Object CSP_GUARDAR_COMPETENCIA.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_guardar_competencia;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Guardar_Competencias.
 * @author Meta4
 */
public 
class Csp_Guardar_CompetenciasRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_GUARDAR_COMPETENCIA";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_GUARDAR_COMPETENCIAS";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Guardar_CompetenciasRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item CSP_TIPO */
    public String csp_Tipo = null;
    private void setcsp_Tipo(String ai_value)
    {
        csp_Tipo = ai_value;
    }
    private String getcsp_Tipo()
    {
        return csp_Tipo;
    }

    /* item CSP_ID_HR */
    public String csp_Id_Hr = null;
    private void setcsp_Id_Hr(String ai_value)
    {
        csp_Id_Hr = ai_value;
    }
    private String getcsp_Id_Hr()
    {
        return csp_Id_Hr;
    }

    /* item CSP_ESTADO */
    public Double csp_Estado = null;
    private void setcsp_Estado(Double ai_value)
    {
        csp_Estado = ai_value;
    }
    private Double getcsp_Estado()
    {
        return csp_Estado;
    }

    /* item CSP_VALUE_RAT */
    public Double csp_Value_Rat = null;
    private void setcsp_Value_Rat(Double ai_value)
    {
        csp_Value_Rat = ai_value;
    }
    private Double getcsp_Value_Rat()
    {
        return csp_Value_Rat;
    }

    /* item CSP_OR_HR_ROLE */
    public Double csp_Or_Hr_Role = null;
    private void setcsp_Or_Hr_Role(Double ai_value)
    {
        csp_Or_Hr_Role = ai_value;
    }
    private Double getcsp_Or_Hr_Role()
    {
        return csp_Or_Hr_Role;
    }

    /* item CSP_EXPLANATION */
    public String csp_Explanation = null;
    private void setcsp_Explanation(String ai_value)
    {
        csp_Explanation = ai_value;
    }
    private String getcsp_Explanation()
    {
        return csp_Explanation;
    }

    /* item ID_ORGANIZATION */
    public String id_Organization = null;
    private void setid_Organization(String ai_value)
    {
        id_Organization = ai_value;
    }
    private String getid_Organization()
    {
        return id_Organization;
    }

    /* item CSP_ID_EVALUATOR */
    public String csp_Id_Evaluator = null;
    private void setcsp_Id_Evaluator(String ai_value)
    {
        csp_Id_Evaluator = ai_value;
    }
    private String getcsp_Id_Evaluator()
    {
        return csp_Id_Evaluator;
    }

    /* item CSP_ID_EVAL_PLAN */
    public String csp_Id_Eval_Plan = null;
    private void setcsp_Id_Eval_Plan(String ai_value)
    {
        csp_Id_Eval_Plan = ai_value;
    }
    private String getcsp_Id_Eval_Plan()
    {
        return csp_Id_Eval_Plan;
    }

    /* item CSP_OR_EVALUATOR */
    public Double csp_Or_Evaluator = null;
    private void setcsp_Or_Evaluator(Double ai_value)
    {
        csp_Or_Evaluator = ai_value;
    }
    private Double getcsp_Or_Evaluator()
    {
        return csp_Or_Evaluator;
    }

    /* item CSP_DT_START_EVAL */
    public Calendar csp_Dt_Start_Eval = null;
    private void setcsp_Dt_Start_Eval(Calendar ai_value)
    {
        csp_Dt_Start_Eval = ai_value;
    }
    private Calendar getcsp_Dt_Start_Eval()
    {
        return csp_Dt_Start_Eval;
    }

    /* item CSP_ID_CAPABILITY */
    public String csp_Id_Capability = null;
    private void setcsp_Id_Capability(String ai_value)
    {
        csp_Id_Capability = ai_value;
    }
    private String getcsp_Id_Capability()
    {
        return csp_Id_Capability;
    }

    /* item CSP_ID_CAP_RAT_LVL */
    public String csp_Id_Cap_Rat_Lvl = null;
    private void setcsp_Id_Cap_Rat_Lvl(String ai_value)
    {
        csp_Id_Cap_Rat_Lvl = ai_value;
    }
    private String getcsp_Id_Cap_Rat_Lvl()
    {
        return csp_Id_Cap_Rat_Lvl;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // CSP_TIPO.
        if (csp_Tipo != null)
        {
            htItems.put("CSP_TIPO", M4BusinessMethodArg.toString(csp_Tipo));
        }
        // CSP_ID_HR.
        if (csp_Id_Hr != null)
        {
            htItems.put("CSP_ID_HR", M4BusinessMethodArg.toString(csp_Id_Hr));
        }
        // CSP_ESTADO.
        if (csp_Estado != null)
        {
            htItems.put("CSP_ESTADO", M4BusinessMethodArg.toString(csp_Estado));
        }
        // CSP_VALUE_RAT.
        if (csp_Value_Rat != null)
        {
            htItems.put("CSP_VALUE_RAT", M4BusinessMethodArg.toString(csp_Value_Rat));
        }
        // CSP_OR_HR_ROLE.
        if (csp_Or_Hr_Role != null)
        {
            htItems.put("CSP_OR_HR_ROLE", M4BusinessMethodArg.toString(csp_Or_Hr_Role));
        }
        // CSP_EXPLANATION.
        if (csp_Explanation != null)
        {
            htItems.put("CSP_EXPLANATION", M4BusinessMethodArg.toString(csp_Explanation));
        }
        // ID_ORGANIZATION.
        if (id_Organization != null)
        {
            htItems.put("ID_ORGANIZATION", M4BusinessMethodArg.toString(id_Organization));
        }
        // CSP_ID_EVALUATOR.
        if (csp_Id_Evaluator != null)
        {
            htItems.put("CSP_ID_EVALUATOR", M4BusinessMethodArg.toString(csp_Id_Evaluator));
        }
        // CSP_ID_EVAL_PLAN.
        if (csp_Id_Eval_Plan != null)
        {
            htItems.put("CSP_ID_EVAL_PLAN", M4BusinessMethodArg.toString(csp_Id_Eval_Plan));
        }
        // CSP_OR_EVALUATOR.
        if (csp_Or_Evaluator != null)
        {
            htItems.put("CSP_OR_EVALUATOR", M4BusinessMethodArg.toString(csp_Or_Evaluator));
        }
        // CSP_DT_START_EVAL.
        if (csp_Dt_Start_Eval != null)
        {
            htItems.put("CSP_DT_START_EVAL", M4BusinessMethodArg.toString(csp_Dt_Start_Eval));
        }
        // CSP_ID_CAPABILITY.
        if (csp_Id_Capability != null)
        {
            htItems.put("CSP_ID_CAPABILITY", M4BusinessMethodArg.toString(csp_Id_Capability));
        }
        // CSP_ID_CAP_RAT_LVL.
        if (csp_Id_Cap_Rat_Lvl != null)
        {
            htItems.put("CSP_ID_CAP_RAT_LVL", M4BusinessMethodArg.toString(csp_Id_Cap_Rat_Lvl));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read CSP_TIPO.
        sItemName = "CSP_TIPO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Tipo = sItemValue;

        // read CSP_ID_HR.
        sItemName = "CSP_ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Hr = sItemValue;

        // read CSP_ESTADO.
        sItemName = "CSP_ESTADO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Estado = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CSP_VALUE_RAT.
        sItemName = "CSP_VALUE_RAT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Value_Rat = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CSP_OR_HR_ROLE.
        sItemName = "CSP_OR_HR_ROLE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Or_Hr_Role = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CSP_EXPLANATION.
        sItemName = "CSP_EXPLANATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Explanation = sItemValue;

        // read ID_ORGANIZATION.
        sItemName = "ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Organization = sItemValue;

        // read CSP_ID_EVALUATOR.
        sItemName = "CSP_ID_EVALUATOR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Evaluator = sItemValue;

        // read CSP_ID_EVAL_PLAN.
        sItemName = "CSP_ID_EVAL_PLAN";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Eval_Plan = sItemValue;

        // read CSP_OR_EVALUATOR.
        sItemName = "CSP_OR_EVALUATOR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Or_Evaluator = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CSP_DT_START_EVAL.
        sItemName = "CSP_DT_START_EVAL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Dt_Start_Eval = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CSP_ID_CAPABILITY.
        sItemName = "CSP_ID_CAPABILITY";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Capability = sItemValue;

        // read CSP_ID_CAP_RAT_LVL.
        sItemName = "CSP_ID_CAP_RAT_LVL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Cap_Rat_Lvl = sItemValue;


    } /* end of method readOperations */


} /* end of class Csp_Guardar_CompetenciasRecord */

