/**
 * Sntc_Sec_OptBlock.java
 * Self generated code for Bussines Object SNTC_SEC_OPT.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.sntc_sec_opt;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Sntc_Sec_Opt.
 * @author Meta4
 */
public 
class Sntc_Sec_OptBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "SNTC_SEC_OPT";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "SNTC_SEC_OPT";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Sntc_Sec_OptBlock.class.getName());

    /* the recordset */
    private Sntc_Sec_OptRecord[] Sntc_Sec_OptRecordSet = null;
    public void setSntc_Sec_OptRecordSet(Sntc_Sec_OptRecord[] ai_arg)
    {
        Sntc_Sec_OptRecordSet = ai_arg;
    }
    public Sntc_Sec_OptRecord[] getSntc_Sec_OptRecordSet()
    {
        return Sntc_Sec_OptRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Sntc_Sec_OptBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();

        // insert 'block scope' values in SNTC_SEC_OPT.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in SNTC_SEC_OPT.
        if (Sntc_Sec_OptRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Sntc_Sec_OptRecordSet.length; i++)
        {
            Sntc_Sec_OptRecord record = Sntc_Sec_OptRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in SNTC_SEC_OPT.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;


        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Sntc_Sec_OptRecordSet = new Sntc_Sec_OptRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Sntc_Sec_OptRecord record = new Sntc_Sec_OptRecord();
                      
			      record.setM4AutoGeneratedRecordID (sRecordID) ; 
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Sntc_Sec_OptRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Sntc_Sec_OptBlock */

