/**
 * Csp_Consulta_1Record.java
 * Self generated code for Bussines Object CSP_CONSULTA_EMP.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_consulta_emp;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Consulta_1.
 * @author Meta4
 */
public 
class Csp_Consulta_1Record 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_CONSULTA_EMP";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_CONSULTA_1";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Consulta_1Record.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item CORREO */
    public String correo = null;
    private void setcorreo(String ai_value)
    {
        correo = ai_value;
    }
    private String getcorreo()
    {
        return correo;
    }

    /* item NOMBRE */
    public String nombre = null;
    private void setnombre(String ai_value)
    {
        nombre = ai_value;
    }
    private String getnombre()
    {
        return nombre;
    }

    /* item ID_LEGAL */
    public String id_Legal = null;
    private void setid_Legal(String ai_value)
    {
        id_Legal = ai_value;
    }
    private String getid_Legal()
    {
        return id_Legal;
    }

    /* item APELLIDO_1 */
    public String apellido_1 = null;
    private void setapellido_1(String ai_value)
    {
        apellido_1 = ai_value;
    }
    private String getapellido_1()
    {
        return apellido_1;
    }

    /* item APELLIDO_2 */
    public String apellido_2 = null;
    private void setapellido_2(String ai_value)
    {
        apellido_2 = ai_value;
    }
    private String getapellido_2()
    {
        return apellido_2;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // CORREO.
        if (correo != null)
        {
            htItems.put("CORREO", M4BusinessMethodArg.toString(correo));
        }
        // NOMBRE.
        if (nombre != null)
        {
            htItems.put("NOMBRE", M4BusinessMethodArg.toString(nombre));
        }
        // ID_LEGAL.
        if (id_Legal != null)
        {
            htItems.put("ID_LEGAL", M4BusinessMethodArg.toString(id_Legal));
        }
        // APELLIDO_1.
        if (apellido_1 != null)
        {
            htItems.put("APELLIDO_1", M4BusinessMethodArg.toString(apellido_1));
        }
        // APELLIDO_2.
        if (apellido_2 != null)
        {
            htItems.put("APELLIDO_2", M4BusinessMethodArg.toString(apellido_2));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read CORREO.
        sItemName = "CORREO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        correo = sItemValue;

        // read NOMBRE.
        sItemName = "NOMBRE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        nombre = sItemValue;

        // read ID_LEGAL.
        sItemName = "ID_LEGAL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Legal = sItemValue;

        // read APELLIDO_1.
        sItemName = "APELLIDO_1";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        apellido_1 = sItemValue;

        // read APELLIDO_2.
        sItemName = "APELLIDO_2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        apellido_2 = sItemValue;


    } /* end of method readOperations */


} /* end of class Csp_Consulta_1Record */

