/**
 * Csp_Perfil_UserBlock.java
 * Self generated code for Bussines Object CSP_PERFIL_EMP.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.csp_perfil_emp;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Csp_Perfil_User.
 * @author Meta4
 */
public 
class Csp_Perfil_UserBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_PERFIL_EMP";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_PERFIL_USER";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Perfil_UserBlock.class.getName());

    /* item P_USUARIO */
    public String p_Usuario = null;
    private void setp_Usuario(String ai_value)
    {
        p_Usuario = ai_value;
    }
    private String getp_Usuario()
    {
        return p_Usuario;
    }

    /* the recordset */
    public Csp_Perfil_UserRecord[] Csp_Perfil_UserRecordSet = null;
    private void setCsp_Perfil_UserRecordSet(Csp_Perfil_UserRecord[] ai_arg)
    {
        Csp_Perfil_UserRecordSet = ai_arg;
    }
    private Csp_Perfil_UserRecord[] getCsp_Perfil_UserRecordSet()
    {
        return Csp_Perfil_UserRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Csp_Perfil_UserBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // P_USUARIO.
        if (p_Usuario != null)
        {
            htItems.put("P_USUARIO", M4BusinessMethodArg.toString(p_Usuario));
        }

        // insert 'block scope' values in CSP_PERFIL_USER.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in CSP_PERFIL_USER.
        if (Csp_Perfil_UserRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Csp_Perfil_UserRecordSet.length; i++)
        {
            Csp_Perfil_UserRecord record = Csp_Perfil_UserRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in CSP_PERFIL_USER.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;

        // read P_USUARIO.
        sItemName = "P_USUARIO";
        nItem = ai_xml.findItem(ai_node, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Usuario = sItemValue;

        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Csp_Perfil_UserRecordSet = new Csp_Perfil_UserRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Csp_Perfil_UserRecord record = new Csp_Perfil_UserRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Csp_Perfil_UserRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Csp_Perfil_UserBlock */

