import {
  BadgeCheck,
  Banknote,
  BookOpen,
  Briefcase,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  ChartColumn,
  CircleDollarSign,
  ClipboardCheck,
  Clock,
  Contact,
  FileBadge,
  FileText,
  Gift,
  GraduationCap,
  HandCoins,
  HeartPulse,
  Home,
  IdCard,
  Landmark,
  Link2,
  ListChecks,
  Mail,
  MapPin,
  MessagesSquare,
  Network,
  Package,
  Phone,
  PiggyBank,
  ReceiptText,
  Route,
  Scale,
  ScanSearch,
  Search,
  Shuffle,
  Target,
  TrendingUp,
  UserRoundCheck,
  UserRoundPlus,
  Users,
  UsersRound,
  Wallet,
  type LucideIcon,
} from "lucide-react";

import type { PortalIconName } from "@/lib/portal/types";

export const PORTAL_ICONS: Record<PortalIconName, LucideIcon> = {
  home: Home,
  tasks: ListChecks,
  org: Network,
  person: UserRoundCheck,
  "id-card": IdCard,
  contact: Contact,
  address: MapPin,
  mail: Mail,
  phone: Phone,
  family: UsersRound,
  emergency: HeartPulse,
  document: FileText,
  tax: Scale,
  bank: Landmark,
  payslip: ReceiptText,
  certificate: FileBadge,
  chart: ChartColumn,
  loan: HandCoins,
  benefit: Gift,
  package: Package,
  job: Briefcase,
  training: GraduationCap,
  evaluation: ClipboardCheck,
  career: TrendingUp,
  mobility: Shuffle,
  goal: Target,
  calendar: CalendarDays,
  vacation: CalendarCheck,
  absence: CalendarRange,
  clock: Clock,
  planning: CalendarClock,
  knowledge: BookOpen,
  team: Users,
  scope: ScanSearch,
  delegation: Route,
  approval: BadgeCheck,
  salary: Wallet,
  budget: PiggyBank,
  review: CircleDollarSign,
  vacancy: UserRoundPlus,
  interview: MessagesSquare,
  movement: Shuffle,
  link: Link2,
  search: Search,
  report: Banknote,
};
