/**
 * Csp_Oro_H_ResponsablesBlock.java
 * Self generated code for Bussines Object CSP_CONSULTA_ORO.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.csp_consulta_oro;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Csp_Oro_H_Responsables.
 * @author Meta4
 */
public 
class Csp_Oro_H_ResponsablesBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_CONSULTA_ORO";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_ORO_H_RESPONSABLES";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Oro_H_ResponsablesBlock.class.getName());

    /* the recordset */
    public Csp_Oro_H_ResponsablesRecord[] Csp_Oro_H_ResponsablesRecordSet = null;
    private void setCsp_Oro_H_ResponsablesRecordSet(Csp_Oro_H_ResponsablesRecord[] ai_arg)
    {
        Csp_Oro_H_ResponsablesRecordSet = ai_arg;
    }
    private Csp_Oro_H_ResponsablesRecord[] getCsp_Oro_H_ResponsablesRecordSet()
    {
        return Csp_Oro_H_ResponsablesRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Csp_Oro_H_ResponsablesBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();

        // insert 'block scope' values in CSP_ORO_H_RESPONSABLES.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in CSP_ORO_H_RESPONSABLES.
        if (Csp_Oro_H_ResponsablesRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Csp_Oro_H_ResponsablesRecordSet.length; i++)
        {
            Csp_Oro_H_ResponsablesRecord record = Csp_Oro_H_ResponsablesRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in CSP_ORO_H_RESPONSABLES.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;


        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Csp_Oro_H_ResponsablesRecordSet = new Csp_Oro_H_ResponsablesRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Csp_Oro_H_ResponsablesRecord record = new Csp_Oro_H_ResponsablesRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Csp_Oro_H_ResponsablesRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Csp_Oro_H_ResponsablesBlock */

