/**
 * Csp_Consulta_H_Oro_PersonaRecord.java
 * Self generated code for Bussines Object CSP_CONSULTA_ORO.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_consulta_oro;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Consulta_H_Oro_Persona.
 * @author Meta4
 */
public 
class Csp_Consulta_H_Oro_PersonaRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_CONSULTA_ORO";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_CONSULTA_H_ORO_PERSONA";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Consulta_H_Oro_PersonaRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item STD_EMAIL */
    public String std_Email = null;
    private void setstd_Email(String ai_value)
    {
        std_Email = ai_value;
    }
    private String getstd_Email()
    {
        return std_Email;
    }

    /* item STD_DT_BIRTH */
    public Calendar std_Dt_Birth = null;
    private void setstd_Dt_Birth(Calendar ai_value)
    {
        std_Dt_Birth = ai_value;
    }
    private Calendar getstd_Dt_Birth()
    {
        return std_Dt_Birth;
    }

    /* item STD_N_FIRST_NAME */
    public String std_N_First_Name = null;
    private void setstd_N_First_Name(String ai_value)
    {
        std_N_First_Name = ai_value;
    }
    private String getstd_N_First_Name()
    {
        return std_N_First_Name;
    }

    /* item STD_N_MAIDEN_NAME */
    public String std_N_Maiden_Name = null;
    private void setstd_N_Maiden_Name(String ai_value)
    {
        std_N_Maiden_Name = ai_value;
    }
    private String getstd_N_Maiden_Name()
    {
        return std_N_Maiden_Name;
    }

    /* item STD_N_FAMILY_NAME_1 */
    public String std_N_Family_Name_1 = null;
    private void setstd_N_Family_Name_1(String ai_value)
    {
        std_N_Family_Name_1 = ai_value;
    }
    private String getstd_N_Family_Name_1()
    {
        return std_N_Family_Name_1;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // STD_EMAIL.
        if (std_Email != null)
        {
            htItems.put("STD_EMAIL", M4BusinessMethodArg.toString(std_Email));
        }
        // STD_DT_BIRTH.
        if (std_Dt_Birth != null)
        {
            htItems.put("STD_DT_BIRTH", M4BusinessMethodArg.toString(std_Dt_Birth));
        }
        // STD_N_FIRST_NAME.
        if (std_N_First_Name != null)
        {
            htItems.put("STD_N_FIRST_NAME", M4BusinessMethodArg.toString(std_N_First_Name));
        }
        // STD_N_MAIDEN_NAME.
        if (std_N_Maiden_Name != null)
        {
            htItems.put("STD_N_MAIDEN_NAME", M4BusinessMethodArg.toString(std_N_Maiden_Name));
        }
        // STD_N_FAMILY_NAME_1.
        if (std_N_Family_Name_1 != null)
        {
            htItems.put("STD_N_FAMILY_NAME_1", M4BusinessMethodArg.toString(std_N_Family_Name_1));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read STD_EMAIL.
        sItemName = "STD_EMAIL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Email = sItemValue;

        // read STD_DT_BIRTH.
        sItemName = "STD_DT_BIRTH";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Dt_Birth = M4BusinessMethodArg.toCalendar(sItemValue);

        // read STD_N_FIRST_NAME.
        sItemName = "STD_N_FIRST_NAME";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_First_Name = sItemValue;

        // read STD_N_MAIDEN_NAME.
        sItemName = "STD_N_MAIDEN_NAME";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_Maiden_Name = sItemValue;

        // read STD_N_FAMILY_NAME_1.
        sItemName = "STD_N_FAMILY_NAME_1";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_Family_Name_1 = sItemValue;


    } /* end of method readOperations */


} /* end of class Csp_Consulta_H_Oro_PersonaRecord */

