/**
 * Csp_Consulta_H_Oro_TrabajoRecord.java
 * Self generated code for Bussines Object CSP_CONSULTA_ORO.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_consulta_oro;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Consulta_H_Oro_Trabajo.
 * @author Meta4
 */
public 
class Csp_Consulta_H_Oro_TrabajoRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_CONSULTA_ORO";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_CONSULTA_H_ORO_TRABAJO";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Consulta_H_Oro_TrabajoRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item STD_N_WORK_LOCATION */
    public String std_N_Work_Location = null;
    private void setstd_N_Work_Location(String ai_value)
    {
        std_N_Work_Location = ai_value;
    }
    private String getstd_N_Work_Location()
    {
        return std_N_Work_Location;
    }

    /* item STD_ID_WORK_LOCATION */
    public String std_Id_Work_Location = null;
    private void setstd_Id_Work_Location(String ai_value)
    {
        std_Id_Work_Location = ai_value;
    }
    private String getstd_Id_Work_Location()
    {
        return std_Id_Work_Location;
    }

    /* item CSP_ID_WORK_FUNCTIONAL */
    public String csp_Id_Work_Functional = null;
    private void setcsp_Id_Work_Functional(String ai_value)
    {
        csp_Id_Work_Functional = ai_value;
    }
    private String getcsp_Id_Work_Functional()
    {
        return csp_Id_Work_Functional;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // STD_N_WORK_LOCATION.
        if (std_N_Work_Location != null)
        {
            htItems.put("STD_N_WORK_LOCATION", M4BusinessMethodArg.toString(std_N_Work_Location));
        }
        // STD_ID_WORK_LOCATION.
        if (std_Id_Work_Location != null)
        {
            htItems.put("STD_ID_WORK_LOCATION", M4BusinessMethodArg.toString(std_Id_Work_Location));
        }
        // CSP_ID_WORK_FUNCTIONAL.
        if (csp_Id_Work_Functional != null)
        {
            htItems.put("CSP_ID_WORK_FUNCTIONAL", M4BusinessMethodArg.toString(csp_Id_Work_Functional));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read STD_N_WORK_LOCATION.
        sItemName = "STD_N_WORK_LOCATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_Work_Location = sItemValue;

        // read STD_ID_WORK_LOCATION.
        sItemName = "STD_ID_WORK_LOCATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Id_Work_Location = sItemValue;

        // read CSP_ID_WORK_FUNCTIONAL.
        sItemName = "CSP_ID_WORK_FUNCTIONAL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Work_Functional = sItemValue;


    } /* end of method readOperations */


} /* end of class Csp_Consulta_H_Oro_TrabajoRecord */

