/**
 * Cyc_Mayor_Certificado_3Record.java
 * Self generated code for Bussines Object CYC_BUSCADOR_FASE2.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_buscador_fase2;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Mayor_Certificado_3.
 * @author Meta4
 */
public 
class Cyc_Mayor_Certificado_3Record 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_BUSCADOR_FASE2";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_MAYOR_CERTIFICADO_3";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Mayor_Certificado_3Record.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item SCO_ID_HR */
    public String sco_Id_Hr = null;
    private void setsco_Id_Hr(String ai_value)
    {
        sco_Id_Hr = ai_value;
    }
    private String getsco_Id_Hr()
    {
        return sco_Id_Hr;
    }

    /* item SCO_COMMENT */
    public String sco_Comment = null;
    private void setsco_Comment(String ai_value)
    {
        sco_Comment = ai_value;
    }
    private String getsco_Comment()
    {
        return sco_Comment;
    }

    /* item SCO_DT_ISSUE */
    public Calendar sco_Dt_Issue = null;
    private void setsco_Dt_Issue(Calendar ai_value)
    {
        sco_Dt_Issue = ai_value;
    }
    private Calendar getsco_Dt_Issue()
    {
        return sco_Dt_Issue;
    }

    /* item SCO_N_CERTIF */
    public String sco_N_Certif = null;
    private void setsco_N_Certif(String ai_value)
    {
        sco_N_Certif = ai_value;
    }
    private String getsco_N_Certif()
    {
        return sco_N_Certif;
    }

    /* item SCO_DT_EXPIRED */
    public Calendar sco_Dt_Expired = null;
    private void setsco_Dt_Expired(Calendar ai_value)
    {
        sco_Dt_Expired = ai_value;
    }
    private Calendar getsco_Dt_Expired()
    {
        return sco_Dt_Expired;
    }

    /* item SCO_ID_COUNTRY */
    public String sco_Id_Country = null;
    private void setsco_Id_Country(String ai_value)
    {
        sco_Id_Country = ai_value;
    }
    private String getsco_Id_Country()
    {
        return sco_Id_Country;
    }

    /* item SCO_CERT_NUMBER */
    public String sco_Cert_Number = null;
    private void setsco_Cert_Number(String ai_value)
    {
        sco_Cert_Number = ai_value;
    }
    private String getsco_Cert_Number()
    {
        return sco_Cert_Number;
    }

    /* item SCO_OR_CERTIF_LIC */
    public Double sco_Or_Certif_Lic = null;
    private void setsco_Or_Certif_Lic(Double ai_value)
    {
        sco_Or_Certif_Lic = ai_value;
    }
    private Double getsco_Or_Certif_Lic()
    {
        return sco_Or_Certif_Lic;
    }

    /* item SCO_ID_CERTIF_TYPE */
    public String sco_Id_Certif_Type = null;
    private void setsco_Id_Certif_Type(String ai_value)
    {
        sco_Id_Certif_Type = ai_value;
    }
    private String getsco_Id_Certif_Type()
    {
        return sco_Id_Certif_Type;
    }

    /* item SCO_ID_ISSUE_ENTIT */
    public String sco_Id_Issue_Entit = null;
    private void setsco_Id_Issue_Entit(String ai_value)
    {
        sco_Id_Issue_Entit = ai_value;
    }
    private String getsco_Id_Issue_Entit()
    {
        return sco_Id_Issue_Entit;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // SCO_ID_HR.
        if (sco_Id_Hr != null)
        {
            htItems.put("SCO_ID_HR", M4BusinessMethodArg.toString(sco_Id_Hr));
        }
        // SCO_COMMENT.
        if (sco_Comment != null)
        {
            htItems.put("SCO_COMMENT", M4BusinessMethodArg.toString(sco_Comment));
        }
        // SCO_DT_ISSUE.
        if (sco_Dt_Issue != null)
        {
            htItems.put("SCO_DT_ISSUE", M4BusinessMethodArg.toString(sco_Dt_Issue));
        }
        // SCO_N_CERTIF.
        if (sco_N_Certif != null)
        {
            htItems.put("SCO_N_CERTIF", M4BusinessMethodArg.toString(sco_N_Certif));
        }
        // SCO_DT_EXPIRED.
        if (sco_Dt_Expired != null)
        {
            htItems.put("SCO_DT_EXPIRED", M4BusinessMethodArg.toString(sco_Dt_Expired));
        }
        // SCO_ID_COUNTRY.
        if (sco_Id_Country != null)
        {
            htItems.put("SCO_ID_COUNTRY", M4BusinessMethodArg.toString(sco_Id_Country));
        }
        // SCO_CERT_NUMBER.
        if (sco_Cert_Number != null)
        {
            htItems.put("SCO_CERT_NUMBER", M4BusinessMethodArg.toString(sco_Cert_Number));
        }
        // SCO_OR_CERTIF_LIC.
        if (sco_Or_Certif_Lic != null)
        {
            htItems.put("SCO_OR_CERTIF_LIC", M4BusinessMethodArg.toString(sco_Or_Certif_Lic));
        }
        // SCO_ID_CERTIF_TYPE.
        if (sco_Id_Certif_Type != null)
        {
            htItems.put("SCO_ID_CERTIF_TYPE", M4BusinessMethodArg.toString(sco_Id_Certif_Type));
        }
        // SCO_ID_ISSUE_ENTIT.
        if (sco_Id_Issue_Entit != null)
        {
            htItems.put("SCO_ID_ISSUE_ENTIT", M4BusinessMethodArg.toString(sco_Id_Issue_Entit));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read SCO_ID_HR.
        sItemName = "SCO_ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Hr = sItemValue;

        // read SCO_COMMENT.
        sItemName = "SCO_COMMENT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Comment = sItemValue;

        // read SCO_DT_ISSUE.
        sItemName = "SCO_DT_ISSUE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Dt_Issue = M4BusinessMethodArg.toCalendar(sItemValue);

        // read SCO_N_CERTIF.
        sItemName = "SCO_N_CERTIF";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_N_Certif = sItemValue;

        // read SCO_DT_EXPIRED.
        sItemName = "SCO_DT_EXPIRED";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Dt_Expired = M4BusinessMethodArg.toCalendar(sItemValue);

        // read SCO_ID_COUNTRY.
        sItemName = "SCO_ID_COUNTRY";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Country = sItemValue;

        // read SCO_CERT_NUMBER.
        sItemName = "SCO_CERT_NUMBER";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Cert_Number = sItemValue;

        // read SCO_OR_CERTIF_LIC.
        sItemName = "SCO_OR_CERTIF_LIC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Or_Certif_Lic = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read SCO_ID_CERTIF_TYPE.
        sItemName = "SCO_ID_CERTIF_TYPE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Certif_Type = sItemValue;

        // read SCO_ID_ISSUE_ENTIT.
        sItemName = "SCO_ID_ISSUE_ENTIT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Issue_Entit = sItemValue;


    } /* end of method readOperations */


} /* end of class Cyc_Mayor_Certificado_3Record */

