
;--------------------------------------------------------------------------------------
;  - file: WEB-INF/classes/com/meta4/soapservices/services/rpc/CYC_BUSCADOR_FASE2/service.properties
;  - description: Self generated service properties file for CYC_BUSCADOR_FASE2 Soap Service
;  -
;  - Copyright Meta4 Spain S.A.
;  - Centro Europa Empresarial - Edf. Roma
;  - C/ Rozabella, 8
;  - 28230 Las Rozas - Madrid
;  - Spain
;  -
;--------------------------------------------------------------------------------------- 

metadate=2020-01-14 13:56:32

