/**
 * Csp_Consulta_Oro_Intran_WuRecord.java
 * Self generated code for Bussines Object CSP_CONSULTA_ORO_INTRAN_WU.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_consulta_oro_intran_wu;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Consulta_Oro_Intran_Wu.
 * @author Meta4
 */
public 
class Csp_Consulta_Oro_Intran_WuRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_CONSULTA_ORO_INTRAN_WU";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_CONSULTA_ORO_INTRAN_WU";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Consulta_Oro_Intran_WuRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item NOMBRE */
    public String nombre = null;
    private void setnombre(String ai_value)
    {
        nombre = ai_value;
    }
    private String getnombre()
    {
        return nombre;
    }

    /* item ID_PUESTO */
    public String id_Puesto = null;
    private void setid_Puesto(String ai_value)
    {
        id_Puesto = ai_value;
    }
    private String getid_Puesto()
    {
        return id_Puesto;
    }

    /* item N_PUESTOV */
    public String n_Puestov = null;
    private void setn_Puestov(String ai_value)
    {
        n_Puestov = ai_value;
    }
    private String getn_Puestov()
    {
        return n_Puestov;
    }

    /* item APELLIDO_1 */
    public String apellido_1 = null;
    private void setapellido_1(String ai_value)
    {
        apellido_1 = ai_value;
    }
    private String getapellido_1()
    {
        return apellido_1;
    }

    /* item APELLIDO_2 */
    public String apellido_2 = null;
    private void setapellido_2(String ai_value)
    {
        apellido_2 = ai_value;
    }
    private String getapellido_2()
    {
        return apellido_2;
    }

    /* item ID_EMPLEADO */
    public String id_Empleado = null;
    private void setid_Empleado(String ai_value)
    {
        id_Empleado = ai_value;
    }
    private String getid_Empleado()
    {
        return id_Empleado;
    }

    /* item N_TIPO_PUESTO */
    public String n_Tipo_Puesto = null;
    private void setn_Tipo_Puesto(String ai_value)
    {
        n_Tipo_Puesto = ai_value;
    }
    private String getn_Tipo_Puesto()
    {
        return n_Tipo_Puesto;
    }

    /* item ID_TIPO_PUESTO */
    public String id_Tipo_Puesto = null;
    private void setid_Tipo_Puesto(String ai_value)
    {
        id_Tipo_Puesto = ai_value;
    }
    private String getid_Tipo_Puesto()
    {
        return id_Tipo_Puesto;
    }

    /* item STD_ID_WU_TYPE */
    public String std_Id_Wu_Type = null;
    private void setstd_Id_Wu_Type(String ai_value)
    {
        std_Id_Wu_Type = ai_value;
    }
    private String getstd_Id_Wu_Type()
    {
        return std_Id_Wu_Type;
    }

    /* item ID_ORGANIZATION */
    public String id_Organization = null;
    private void setid_Organization(String ai_value)
    {
        id_Organization = ai_value;
    }
    private String getid_Organization()
    {
        return id_Organization;
    }

    /* item STD_N_WORK_UNIT */
    public String std_N_Work_Unit = null;
    private void setstd_N_Work_Unit(String ai_value)
    {
        std_N_Work_Unit = ai_value;
    }
    private String getstd_N_Work_Unit()
    {
        return std_N_Work_Unit;
    }

    /* item STD_ID_WORK_UNIT */
    public String std_Id_Work_Unit = null;
    private void setstd_Id_Work_Unit(String ai_value)
    {
        std_Id_Work_Unit = ai_value;
    }
    private String getstd_Id_Work_Unit()
    {
        return std_Id_Work_Unit;
    }

    /* item STD_N_WORK_UNIT_1 */
    public String std_N_Work_Unit_1 = null;
    private void setstd_N_Work_Unit_1(String ai_value)
    {
        std_N_Work_Unit_1 = ai_value;
    }
    private String getstd_N_Work_Unit_1()
    {
        return std_N_Work_Unit_1;
    }

    /* item STD_ID_WU_INT_TYPE */
    public String std_Id_Wu_Int_Type = null;
    private void setstd_Id_Wu_Int_Type(String ai_value)
    {
        std_Id_Wu_Int_Type = ai_value;
    }
    private String getstd_Id_Wu_Int_Type()
    {
        return std_Id_Wu_Int_Type;
    }

    /* item SCO_ID_WORK_UNIT_PARENT */
    public String sco_Id_Work_Unit_Parent = null;
    private void setsco_Id_Work_Unit_Parent(String ai_value)
    {
        sco_Id_Work_Unit_Parent = ai_value;
    }
    private String getsco_Id_Work_Unit_Parent()
    {
        return sco_Id_Work_Unit_Parent;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // NOMBRE.
        if (nombre != null)
        {
            htItems.put("NOMBRE", M4BusinessMethodArg.toString(nombre));
        }
        // ID_PUESTO.
        if (id_Puesto != null)
        {
            htItems.put("ID_PUESTO", M4BusinessMethodArg.toString(id_Puesto));
        }
        // N_PUESTOV.
        if (n_Puestov != null)
        {
            htItems.put("N_PUESTOV", M4BusinessMethodArg.toString(n_Puestov));
        }
        // APELLIDO_1.
        if (apellido_1 != null)
        {
            htItems.put("APELLIDO_1", M4BusinessMethodArg.toString(apellido_1));
        }
        // APELLIDO_2.
        if (apellido_2 != null)
        {
            htItems.put("APELLIDO_2", M4BusinessMethodArg.toString(apellido_2));
        }
        // ID_EMPLEADO.
        if (id_Empleado != null)
        {
            htItems.put("ID_EMPLEADO", M4BusinessMethodArg.toString(id_Empleado));
        }
        // N_TIPO_PUESTO.
        if (n_Tipo_Puesto != null)
        {
            htItems.put("N_TIPO_PUESTO", M4BusinessMethodArg.toString(n_Tipo_Puesto));
        }
        // ID_TIPO_PUESTO.
        if (id_Tipo_Puesto != null)
        {
            htItems.put("ID_TIPO_PUESTO", M4BusinessMethodArg.toString(id_Tipo_Puesto));
        }
        // STD_ID_WU_TYPE.
        if (std_Id_Wu_Type != null)
        {
            htItems.put("STD_ID_WU_TYPE", M4BusinessMethodArg.toString(std_Id_Wu_Type));
        }
        // ID_ORGANIZATION.
        if (id_Organization != null)
        {
            htItems.put("ID_ORGANIZATION", M4BusinessMethodArg.toString(id_Organization));
        }
        // STD_N_WORK_UNIT.
        if (std_N_Work_Unit != null)
        {
            htItems.put("STD_N_WORK_UNIT", M4BusinessMethodArg.toString(std_N_Work_Unit));
        }
        // STD_ID_WORK_UNIT.
        if (std_Id_Work_Unit != null)
        {
            htItems.put("STD_ID_WORK_UNIT", M4BusinessMethodArg.toString(std_Id_Work_Unit));
        }
        // STD_N_WORK_UNIT_1.
        if (std_N_Work_Unit_1 != null)
        {
            htItems.put("STD_N_WORK_UNIT_1", M4BusinessMethodArg.toString(std_N_Work_Unit_1));
        }
        // STD_ID_WU_INT_TYPE.
        if (std_Id_Wu_Int_Type != null)
        {
            htItems.put("STD_ID_WU_INT_TYPE", M4BusinessMethodArg.toString(std_Id_Wu_Int_Type));
        }
        // SCO_ID_WORK_UNIT_PARENT.
        if (sco_Id_Work_Unit_Parent != null)
        {
            htItems.put("SCO_ID_WORK_UNIT_PARENT", M4BusinessMethodArg.toString(sco_Id_Work_Unit_Parent));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read NOMBRE.
        sItemName = "NOMBRE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        nombre = sItemValue;

        // read ID_PUESTO.
        sItemName = "ID_PUESTO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Puesto = sItemValue;

        // read N_PUESTOV.
        sItemName = "N_PUESTOV";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        n_Puestov = sItemValue;

        // read APELLIDO_1.
        sItemName = "APELLIDO_1";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        apellido_1 = sItemValue;

        // read APELLIDO_2.
        sItemName = "APELLIDO_2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        apellido_2 = sItemValue;

        // read ID_EMPLEADO.
        sItemName = "ID_EMPLEADO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Empleado = sItemValue;

        // read N_TIPO_PUESTO.
        sItemName = "N_TIPO_PUESTO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        n_Tipo_Puesto = sItemValue;

        // read ID_TIPO_PUESTO.
        sItemName = "ID_TIPO_PUESTO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Tipo_Puesto = sItemValue;

        // read STD_ID_WU_TYPE.
        sItemName = "STD_ID_WU_TYPE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Id_Wu_Type = sItemValue;

        // read ID_ORGANIZATION.
        sItemName = "ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Organization = sItemValue;

        // read STD_N_WORK_UNIT.
        sItemName = "STD_N_WORK_UNIT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_Work_Unit = sItemValue;

        // read STD_ID_WORK_UNIT.
        sItemName = "STD_ID_WORK_UNIT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Id_Work_Unit = sItemValue;

        // read STD_N_WORK_UNIT_1.
        sItemName = "STD_N_WORK_UNIT_1";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_Work_Unit_1 = sItemValue;

        // read STD_ID_WU_INT_TYPE.
        sItemName = "STD_ID_WU_INT_TYPE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Id_Wu_Int_Type = sItemValue;

        // read SCO_ID_WORK_UNIT_PARENT.
        sItemName = "SCO_ID_WORK_UNIT_PARENT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Work_Unit_Parent = sItemValue;


    } /* end of method readOperations */


} /* end of class Csp_Consulta_Oro_Intran_WuRecord */

