import { describe, expect, it } from "vitest";

import {
  buildFullName,
  dedupeUsersById,
  normalizeRecordSets,
  parseUsersListResponse,
} from "@/lib/meta4/users/parser";
import { Meta4UsersError } from "@/lib/meta4/users/errors";

const record = (fields: Record<string, string>) =>
  Object.entries(fields)
    .map(([key, value]) => `<${key}>${value}</${key}>`)
    .join("");

const listXml = (society: string, recordSetsXml: string) => `
  <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
      <CSP_POWER4_USER_ALLResponse xmlns="http://schemas.meta4.com/">
        <CSP_POWER4_USER_ALLReturn>
          <return>1.0</return>
          <Csp_Carga_Users>
            <p_Sociedad>${society}</p_Sociedad>
            ${recordSetsXml}
          </Csp_Carga_Users>
        </CSP_POWER4_USER_ALLReturn>
      </CSP_POWER4_USER_ALLResponse>
    </soap:Body>
  </soap:Envelope>`;

const fixtureRecordSets = `
  <Csp_Carga_UsersRecordSet>
    ${record({
      m4AutoGeneratedRecordID: "1",
      m4AutoGeneratedToDelete: "0",
      nombre: "Paula",
      apellido_1: "García",
      apellido_2: "López",
      clave_Self: "paula",
      id_Empleado: "0001",
    })}
  </Csp_Carga_UsersRecordSet>
  <Csp_Carga_UsersRecordSet>
    ${record({
      nombre: "Mariana",
      apellido_1: "Ruiz",
      apellido_2: "Soto",
      id_Empleado: "0013",
    })}
  </Csp_Carga_UsersRecordSet>
  <Csp_Carga_UsersRecordSet>
    ${record({
      nombre: "Mariana",
      apellido_1: "Duplicada",
      apellido_2: "Uno",
      id_Empleado: "0013",
    })}
  </Csp_Carga_UsersRecordSet>
  <Csp_Carga_UsersRecordSet>
    ${record({
      nombre: "Mariana",
      apellido_1: "Duplicada",
      apellido_2: "Dos",
      id_Empleado: "0013",
    })}
  </Csp_Carga_UsersRecordSet>
  <Csp_Carga_UsersRecordSet>
    ${record({
      nombre: "Raúl",
      apellido_1: "Pérez",
      apellido_2: "Núñez",
      id_Empleado: "0023",
    })}
  </Csp_Carga_UsersRecordSet>
  <Csp_Carga_UsersRecordSet>
    ${record({
      nombre: "Raúl",
      apellido_1: "Otro",
      apellido_2: "Nombre",
      id_Empleado: "0023",
    })}
  </Csp_Carga_UsersRecordSet>
  <Csp_Carga_UsersRecordSet>
    ${record({
      nombre: "María",
      apellido_1: "Sánchez",
      apellido_2: "Díaz",
      id_Empleado: "0024",
    })}
  </Csp_Carga_UsersRecordSet>
  <Csp_Carga_UsersRecordSet>
    ${record({
      nombre: "Federica",
      apellido_1: "Martín",
      apellido_2: ".",
      id_Empleado: "0021",
    })}
  </Csp_Carga_UsersRecordSet>
  <Csp_Carga_UsersRecordSet>
    ${record({
      nombre: "",
      apellido_1: "",
      apellido_2: "",
      id_Empleado: "0099",
    })}
  </Csp_Carga_UsersRecordSet>
  <Csp_Carga_UsersRecordSet>
    ${record({
      nombre: "SinId",
      apellido_1: "X",
      apellido_2: "Y",
      id_Empleado: "",
    })}
  </Csp_Carga_UsersRecordSet>`;

describe("Meta4 users list parser", () => {
  it("normalizes a single RecordSet, an array and undefined", () => {
    expect(normalizeRecordSets(undefined)).toEqual([]);
    expect(normalizeRecordSets(null)).toEqual([]);
    expect(normalizeRecordSets({ id_Empleado: "1" })).toEqual([{ id_Empleado: "1" }]);
    expect(normalizeRecordSets([{ id_Empleado: "1" }, { id_Empleado: "2" }])).toEqual([
      { id_Empleado: "1" },
      { id_Empleado: "2" },
    ]);
  });

  it("parses a single user response", () => {
    const xml = listXml(
      "CYC",
      `<Csp_Carga_UsersRecordSet>${record({
        nombre: "Paula",
        apellido_1: "García",
        apellido_2: "López",
        clave_Self: "paula",
        id_Empleado: "0001",
      })}</Csp_Carga_UsersRecordSet>`,
    );

    expect(parseUsersListResponse(xml, "CYC")).toEqual([
      { id: "0001", fullName: "Paula García López", claveSelf: "paula" },
    ]);
  });

  it("includes clave_Self in the parsed item", () => {
    const xml = listXml(
      "CYC",
      `<Csp_Carga_UsersRecordSet>${record({
        m4AutoGeneratedRecordID: "1",
        m4AutoGeneratedToDelete: "false",
        nombre: "Víctor",
        apellido_1: "Cruz",
        apellido_2: "Trueba",
        clave_Self: "vcruzt",
        id_Empleado: "1746",
      })}</Csp_Carga_UsersRecordSet>`,
    );

    expect(parseUsersListResponse(xml, "CYC")).toEqual([
      { id: "1746", fullName: "Víctor Cruz Trueba", claveSelf: "vcruzt" },
    ]);
  });

  it("defaults claveSelf to an empty string when clave_Self is absent", () => {
    const xml = listXml(
      "CYC",
      `<Csp_Carga_UsersRecordSet>${record({
        nombre: "Mariana",
        apellido_1: "Ruiz",
        apellido_2: "Soto",
        id_Empleado: "0013",
      })}</Csp_Carga_UsersRecordSet>`,
    );

    expect(parseUsersListResponse(xml, "CYC")).toEqual([
      { id: "0013", fullName: "Mariana Ruiz Soto", claveSelf: "" },
    ]);
  });

  it("parses multiple users and zero users as a valid empty list", () => {
    const many = parseUsersListResponse(listXml("CYC", fixtureRecordSets), "CYC");
    expect(many.map((user) => user.id)).toEqual(["0001", "0013", "0023", "0024", "0021"]);

    const empty = parseUsersListResponse(listXml("CYC", ""), "CYC");
    expect(empty).toEqual([]);
  });

  it("keeps leading zeros on id_Empleado and preserves accents", () => {
    const users = parseUsersListResponse(listXml("CYC", fixtureRecordSets), "CYC");
    expect(users.find((user) => user.id === "0001")?.fullName).toBe("Paula García López");
    expect(users.find((user) => user.id === "0023")?.fullName).toContain("Raúl");
    expect(users.find((user) => user.id === "0024")?.fullName).toContain("María");
  });

  it("treats apellido_2 '.' as empty and builds full names", () => {
    expect(buildFullName("Federica", "Martín", ".")).toBe("Federica Martín");
    expect(buildFullName("", "", "")).toBeNull();
    expect(buildFullName(".", ".", ".")).toBeNull();
    expect(buildFullName("  Ana  ", "  Luz  ", "")).toBe("Ana Luz");

    const users = parseUsersListResponse(listXml("CYC", fixtureRecordSets), "CYC");
    expect(users.find((user) => user.id === "0021")?.fullName).toBe("Federica Martín");
  });

  it("dedupes after discarding invalids and keeps the first valid occurrence", () => {
    const users = parseUsersListResponse(listXml("CYC", fixtureRecordSets), "CYC");
    // 10 raw RecordSets → 2 invalid (empty name / empty id) → 8 valid → 5 after dedupe
    expect(users).toHaveLength(5);
    expect(users.find((user) => user.id === "0013")?.fullName).toBe("Mariana Ruiz Soto");
    expect(users.find((user) => user.id === "0023")?.fullName).toBe("Raúl Pérez Núñez");
    expect(dedupeUsersById(users)).toEqual(users);
  });

  it("rejects society mismatch", () => {
    expect(() => parseUsersListResponse(listXml("IBER", fixtureRecordSets), "CYC")).toThrow(
      Meta4UsersError,
    );
    try {
      parseUsersListResponse(listXml("IBER", fixtureRecordSets), "CYC");
    } catch (error) {
      expect(error).toMatchObject({ code: "META4_USERS_SOCIETY_MISMATCH" });
    }
  });

  it("rejects SOAP Faults and invalid XML", () => {
    expect(() =>
      parseUsersListResponse(
        `<soap:Envelope><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>boom</faultstring></soap:Fault></soap:Body></soap:Envelope>`,
        "CYC",
      ),
    ).toThrow(/SOAP Fault/);

    expect(() => parseUsersListResponse("<not-xml", "CYC")).toThrow(Meta4UsersError);
  });

  it("treats missing required structures as invalid, not empty", () => {
    const missingResponse = `
      <soap:Envelope><soap:Body><other /></soap:Body></soap:Envelope>`;
    expect(() => parseUsersListResponse(missingResponse, "CYC")).toThrow(
      /CSP_POWER4_USER_ALLResponse/,
    );

    const missingReturn = `
      <soap:Envelope><soap:Body>
        <CSP_POWER4_USER_ALLResponse>
          <Csp_Carga_Users><p_Sociedad>CYC</p_Sociedad></Csp_Carga_Users>
        </CSP_POWER4_USER_ALLResponse>
      </soap:Body></soap:Envelope>`;
    expect(() => parseUsersListResponse(missingReturn, "CYC")).toThrow(Meta4UsersError);
    try {
      parseUsersListResponse(missingReturn, "CYC");
    } catch (error) {
      expect(error).toMatchObject({ code: "META4_USERS_INVALID_RESPONSE" });
      expect(String(error)).toMatch(/CSP_POWER4_USER_ALLReturn/);
    }

    const missingCarga = `
      <soap:Envelope><soap:Body>
        <CSP_POWER4_USER_ALLResponse>
          <CSP_POWER4_USER_ALLReturn><return>1.0</return></CSP_POWER4_USER_ALLReturn>
        </CSP_POWER4_USER_ALLResponse>
      </soap:Body></soap:Envelope>`;
    expect(() => parseUsersListResponse(missingCarga, "CYC")).toThrow(/Csp_Carga_Users/);

    const missingSociety = `
      <soap:Envelope><soap:Body>
        <CSP_POWER4_USER_ALLResponse>
          <CSP_POWER4_USER_ALLReturn>
            <Csp_Carga_Users></Csp_Carga_Users>
          </CSP_POWER4_USER_ALLReturn>
        </CSP_POWER4_USER_ALLResponse>
      </soap:Body></soap:Envelope>`;
    expect(() => parseUsersListResponse(missingSociety, "CYC")).toThrow(/p_Sociedad/);
  });

  it("does not reject solely because return is missing when structure is otherwise valid", () => {
    const xml = `
      <soap:Envelope><soap:Body>
        <CSP_POWER4_USER_ALLResponse>
          <CSP_POWER4_USER_ALLReturn>
            <Csp_Carga_Users>
              <p_Sociedad>COLL</p_Sociedad>
            </Csp_Carga_Users>
          </CSP_POWER4_USER_ALLReturn>
        </CSP_POWER4_USER_ALLResponse>
      </soap:Body></soap:Envelope>`;
    expect(parseUsersListResponse(xml, "COLL")).toEqual([]);
  });
});
