/**
 * Cyc_Matriz_Fase_IiiRecord.java
 * Self generated code for Bussines Object CYC_MATRIZ.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_matriz;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Matriz_Fase_Iii.
 * @author Meta4
 */
public 
class Cyc_Matriz_Fase_IiiRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_MATRIZ";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_MATRIZ_FASE_III";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Matriz_Fase_IiiRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item CSP_TOEIC */
    public Double csp_Toeic = null;
    private void setcsp_Toeic(Double ai_value)
    {
        csp_Toeic = ai_value;
    }
    private Double getcsp_Toeic()
    {
        return csp_Toeic;
    }

    /* item CYC_ID_HR */
    public String cyc_Id_Hr = null;
    private void setcyc_Id_Hr(String ai_value)
    {
        cyc_Id_Hr = ai_value;
    }
    private String getcyc_Id_Hr()
    {
        return cyc_Id_Hr;
    }

    /* item CLAVE_SELF */
    public String clave_Self = null;
    private void setclave_Self(String ai_value)
    {
        clave_Self = ai_value;
    }
    private String getclave_Self()
    {
        return clave_Self;
    }

    /* item SCO_GB_NAME */
    public String sco_Gb_Name = null;
    private void setsco_Gb_Name(String ai_value)
    {
        sco_Gb_Name = ai_value;
    }
    private String getsco_Gb_Name()
    {
        return sco_Gb_Name;
    }

    /* item CYC_ID_COLECTIVO */
    public String cyc_Id_Colectivo = null;
    private void setcyc_Id_Colectivo(String ai_value)
    {
        cyc_Id_Colectivo = ai_value;
    }
    private String getcyc_Id_Colectivo()
    {
        return cyc_Id_Colectivo;
    }

    /* item CYC_V_CAP_GTION_F3 */
    public Double cyc_V_Cap_Gtion_F3 = null;
    private void setcyc_V_Cap_Gtion_F3(Double ai_value)
    {
        cyc_V_Cap_Gtion_F3 = ai_value;
    }
    private Double getcyc_V_Cap_Gtion_F3()
    {
        return cyc_V_Cap_Gtion_F3;
    }

    /* item CYC_V_POTENCIAL_F3 */
    public Double cyc_V_Potencial_F3 = null;
    private void setcyc_V_Potencial_F3(Double ai_value)
    {
        cyc_V_Potencial_F3 = ai_value;
    }
    private Double getcyc_V_Potencial_F3()
    {
        return cyc_V_Potencial_F3;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // CSP_TOEIC.
        if (csp_Toeic != null)
        {
            htItems.put("CSP_TOEIC", M4BusinessMethodArg.toString(csp_Toeic));
        }
        // CYC_ID_HR.
        if (cyc_Id_Hr != null)
        {
            htItems.put("CYC_ID_HR", M4BusinessMethodArg.toString(cyc_Id_Hr));
        }
        // CLAVE_SELF.
        if (clave_Self != null)
        {
            htItems.put("CLAVE_SELF", M4BusinessMethodArg.toString(clave_Self));
        }
        // SCO_GB_NAME.
        if (sco_Gb_Name != null)
        {
            htItems.put("SCO_GB_NAME", M4BusinessMethodArg.toString(sco_Gb_Name));
        }
        // CYC_ID_COLECTIVO.
        if (cyc_Id_Colectivo != null)
        {
            htItems.put("CYC_ID_COLECTIVO", M4BusinessMethodArg.toString(cyc_Id_Colectivo));
        }
        // CYC_V_CAP_GTION_F3.
        if (cyc_V_Cap_Gtion_F3 != null)
        {
            htItems.put("CYC_V_CAP_GTION_F3", M4BusinessMethodArg.toString(cyc_V_Cap_Gtion_F3));
        }
        // CYC_V_POTENCIAL_F3.
        if (cyc_V_Potencial_F3 != null)
        {
            htItems.put("CYC_V_POTENCIAL_F3", M4BusinessMethodArg.toString(cyc_V_Potencial_F3));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read CSP_TOEIC.
        sItemName = "CSP_TOEIC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Toeic = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_ID_HR.
        sItemName = "CYC_ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Hr = sItemValue;

        // read CLAVE_SELF.
        sItemName = "CLAVE_SELF";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        clave_Self = sItemValue;

        // read SCO_GB_NAME.
        sItemName = "SCO_GB_NAME";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Gb_Name = sItemValue;

        // read CYC_ID_COLECTIVO.
        sItemName = "CYC_ID_COLECTIVO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Colectivo = sItemValue;

        // read CYC_V_CAP_GTION_F3.
        sItemName = "CYC_V_CAP_GTION_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_V_Cap_Gtion_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_V_POTENCIAL_F3.
        sItemName = "CYC_V_POTENCIAL_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_V_Potencial_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);


    } /* end of method readOperations */


} /* end of class Cyc_Matriz_Fase_IiiRecord */

