import type { PortalSqlQuery } from "../../types";

/**
 * Lecturas de «Mis datos» reproducidas desde las sentencias Meta4 originales
 * (`docs/portal/implementacion/lecturas-sql.md`). Los datos personales estándar
 * (`STD_*`) viven en la organización compartida `0000`; los de nómina, en la
 * sociedad. Los catálogos se leen en español (`…ESP`).
 */

const own = (tables: readonly string[], statement: string): PortalSqlQuery => ({
  scope: "own",
  tables,
  statement,
});

/** `SSE_ADDRESS!M4T_ADDRESS` / `SSE_ADDRESS_OTROS!M4T_ADDRESS_OTROS`: domicilios vigentes. */
const address = (locationFilter: string) =>
  own(
    [
      "STD_ADDRESS",
      "STD_COUNTRY",
      "STD_GEO_DIV",
      "STD_SUB_GEO_DIV",
      "STD_GEO_PLACE",
      "STD_LU_LOCAT_TYPE",
    ],
    `SELECT A.STD_ADDRESS_LINE_1 AS STD_ADDRESS_LINE_1, A.SSP_NUM_VIA AS SSP_NUM_VIA,
  A.SSP_BLOQUE AS SSP_BLOQUE, A.SSP_PISO AS SSP_PISO, A.SSP_ESCALERA AS SSP_ESCALERA,
  A.SSP_PUERTA AS SSP_PUERTA, COALESCE(A.SSP_DISTRIT_POSTAL, A.STD_ZIP_CODE) AS SSP_DISTRIT_POSTAL,
  P.STD_N_GEO_PLACESP AS STD_N_GEO_PLACE, S.STD_N_SUB_GEO_ESP AS STD_N_SUB_GEO_DIV,
  G.STD_N_GEO_DIVESP AS STD_N_GEO_DIV, C.STD_N_COUNTRYESP AS STD_N_COUNTRY,
  T.STD_N_LOCAT_TYESP AS STD_N_LOCATION_TYPE, A.STD_DT_START AS STD_DT_START
FROM STD_ADDRESS A
LEFT JOIN STD_COUNTRY C ON C.ID_ORGANIZATION = A.ID_ORGANIZATION AND C.STD_ID_COUNTRY = A.STD_ID_COUNTRY
LEFT JOIN STD_GEO_DIV G ON G.ID_ORGANIZATION = A.ID_ORGANIZATION AND G.STD_ID_COUNTRY = A.STD_ID_COUNTRY
  AND G.STD_ID_GEO_DIV = A.STD_ID_GEO_DIV
LEFT JOIN STD_SUB_GEO_DIV S ON S.ID_ORGANIZATION = A.ID_ORGANIZATION AND S.STD_ID_COUNTRY = A.STD_ID_COUNTRY
  AND S.STD_ID_GEO_DIV = A.STD_ID_GEO_DIV AND S.STD_ID_SUB_GEO_DIV = A.STD_ID_SUB_GEO_DIV
LEFT JOIN STD_GEO_PLACE P ON P.ID_ORGANIZATION = A.ID_ORGANIZATION AND P.STD_ID_COUNTRY = A.STD_ID_COUNTRY
  AND P.STD_ID_GEO_DIV = A.STD_ID_GEO_DIV AND P.STD_ID_SUB_GEO_DIV = A.STD_ID_SUB_GEO_DIV
  AND P.STD_ID_GEO_PLACE = A.STD_ID_GEO_PLACE
LEFT JOIN STD_LU_LOCAT_TYPE T ON T.ID_ORGANIZATION = A.ID_ORGANIZATION AND T.STD_ID_LOCAT_TYPE = A.STD_ID_LOCAT_TYPE
WHERE A.ID_ORGANIZATION IN ('0000', @organization) AND A.STD_ID_PERSON = @employeeId
  AND A.STD_DT_END >= @today AND ${locationFilter}
ORDER BY A.STD_DT_START DESC`,
  );

export const DATOS_SQL = {
  /** `CSP_QUIEN_ES_QUIEN!CSP_CUENTA_BENEFICIARIO`: cuenta propia de la orden de cobro principal vigente. */
  beneficiario: own(
    ["M4SCO_PAYMENT_DATA", "M4SCO_PERSON_BANK"],
    `SELECT DISTINCT B.SCO_GB_IBAN AS SCO_GB_IBAN
FROM M4SCO_PAYMENT_DATA D
JOIN M4SCO_PERSON_BANK B ON B.SCO_ID_PERSON = D.SCO_ID_HR AND B.SCO_OR_ACCOUNT = D.SCO_OR_ACCOUNT
WHERE D.ID_ORGANIZATION = @organization AND D.SCO_ID_HR = @employeeId
  AND D.SCO_EMP_CHECK = '1' AND D.SCO_DT_END = '4000-01-01' AND B.SCO_DT_END = '4000-01-01'`,
  ),
  /** `CSP_QUIEN_ES_QUIEN!CSP_FAM_IRPF`: familiares declarados para el IRPF. */
  famIrpf: own(
    ["M4CSP_FAM_EMPLEADOS", "STD_LU_ACT_DEP_TYP"],
    `SELECT LTRIM(RTRIM(CONCAT(A.STD_N_FIRST_NAME, ' ', A.SSP_PRIM_APELLIDO, ' ', A.STD_N_MAIDEN_NAME))) AS NOMBRECOMPLETO,
  A.STD_DT_BIRTH AS STD_DT_BIRTH, B.STD_ACT_DEP_TYESP AS STD_N_ACT_DEP_TYPE
FROM M4CSP_FAM_EMPLEADOS A
LEFT JOIN STD_LU_ACT_DEP_TYP B ON B.ID_ORGANIZATION IN ('0000', A.ID_ORGANIZATION)
  AND B.STD_ID_ACT_DEP_TYP = A.STD_ID_ACT_DEP_TYP
WHERE A.ID_ORGANIZATION IN ('0000', @organization) AND A.STD_ID_PERSON = @employeeId
ORDER BY A.STD_ID_ACT_DEP_TYP`,
  ),
  /** `CSP_QUIEN_ES_QUIEN!CSP_GRUPO_NIVEL`: categoría vigente. */
  grupoNivel: own(
    ["M4SSP_H_CATEGORIA", "M4SSP_CATEGORIAS"],
    `SELECT B.SSP_NM_CATEGORESP AS SSP_NM_CATEGORIA
FROM M4SSP_H_CATEGORIA A
LEFT JOIN M4SSP_CATEGORIAS B ON B.ID_ORGANIZATION = A.ID_ORGANIZATION AND B.SSP_ID_CATEGORIA = A.SSP_ID_CATEGORIA
WHERE A.ID_ORGANIZATION = @organization AND A.SCO_ID_HR = @employeeId AND A.SSP_FEC_FIN = '4000-01-01'`,
  ),
  /** Dirección fiscal: domicilio de tipo 1. */
  direccionFiscal: address("A.STD_ID_LOCAT_TYPE = '1'"),
  /** Otros domicilios: cualquier tipo distinto del fiscal. */
  otrasDirecciones: address("A.STD_ID_LOCAT_TYPE <> '1'"),
  /** Teletrabajo: domicilio de tipo 8 («Domicilio teletrabajo»). */
  teletrabajo: address("A.STD_ID_LOCAT_TYPE = '8'"),
  /** `SSE_PHONE_FAX!M4T_PHONE_FAX`: teléfonos vigentes. */
  telefonos: own(
    ["STD_PHONE_FAX", "STD_LU_LINE_TYPE", "STD_LU_LOCAT_TYPE"],
    `SELECT A.STD_PHONE AS STD_PHONE, L.STD_N_LINE_TYPEESP AS STD_N_LINE_TYPE,
  T.STD_N_LOCAT_TYESP AS STD_N_LOCATION_TYPE
FROM STD_PHONE_FAX A
LEFT JOIN STD_LU_LINE_TYPE L ON L.ID_ORGANIZATION = A.ID_ORGANIZATION AND L.STD_ID_LINE_TYPE = A.STD_ID_LINE_TYPE
LEFT JOIN STD_LU_LOCAT_TYPE T ON T.ID_ORGANIZATION = A.ID_ORGANIZATION AND T.STD_ID_LOCAT_TYPE = A.STD_ID_LOCAT_TYPE
WHERE A.ID_ORGANIZATION IN ('0000', @organization) AND A.STD_ID_PERSON = @employeeId
  AND A.STD_DT_END >= @today
ORDER BY A.STD_DT_START DESC`,
  ),
  /** `SSE_HT_MAR_STAT!M4T_HT_MAR_STAT`: histórico de estado civil. */
  estadoCivil: own(
    ["STD_HT_MAR_STAT", "STD_LU_MAR_STAT"],
    `SELECT A.STD_DT_START AS STD_DT_START, A.STD_DT_END AS STD_DT_END,
  B.STD_MARITAL_STESP AS STD_N_MARITAL_STAT
FROM STD_HT_MAR_STAT A
LEFT JOIN STD_LU_MAR_STAT B ON B.ID_ORGANIZATION = A.ID_ORGANIZATION AND B.STD_ID_MARITAL_ST = A.STD_ID_MAR_STAT
WHERE A.ID_ORGANIZATION IN ('0000', @organization) AND A.STD_ID_HR = @employeeId
ORDER BY A.STD_DT_START DESC`,
  ),
  /** `SSE_HOME_PAGE!M4T_HOME_PAGE`: página web de la persona. */
  paginaWeb: own(
    ["STD_PERSON"],
    `SELECT P.SCO_HOME_PAGE AS SCO_HOME_PAGE
FROM STD_PERSON P
WHERE P.ID_ORGANIZATION IN ('0000', @organization) AND P.STD_ID_PERSON = @employeeId`,
  ),
  /** `SSE_OTH_CONTACT_FORMS!M4T_OTH_CONTACT_FORMS`: otras formas de contacto vigentes. */
  otrasFormasContacto: own(
    ["M4SCO_OTH_CT_FORMS", "M4SCO_X_CT_TYPE"],
    `SELECT X.SCO_N_CONC_TYESP AS SCO_N_CONTACT_TYPE, O.SCO_CONTACTO AS SCO_CONTACTO,
  O.SCO_DT_START AS SCO_DT_START
FROM M4SCO_OTH_CT_FORMS O
LEFT JOIN M4SCO_X_CT_TYPE X ON X.ID_ORGANIZATION = O.ID_ORGANIZATION AND X.SCO_ID_CONTACT_TYP = O.SCO_ID_CONTACT_TYP
WHERE O.ID_ORGANIZATION IN ('0000', @organization) AND O.SCO_ID_PERSON = @employeeId
  AND O.SCO_DT_END >= @today
ORDER BY O.SCO_DT_START DESC`,
  ),
  /** `SSE_MOD_SITIRPF!SSE_DATA_DATOS_PERCEPTOR` + cónyuge de `SSE_DATA_DATOS_CONYUGE`. */
  irpf: own(
    ["M4SSP_HT_SIT_IRPF", "M4SSP_EST_CIV_IRPF", "M4SSP_TIPO_MINUSV", "M4SSP_DEPEND_IRPF"],
    `SELECT TOP 1 C.SSP_N_EST_IRPFESP AS SSP_N_EST_IRPF, M.SSP_N_MINUSVALESP AS SSP_N_MINUSVALIA,
  A.SSP_NUM_HIJOS_IRPF AS SSP_NUM_HIJOS_IRPF, A.SSP_CON_RED_VIVIEN AS SSP_CON_RED_VIVIENDA,
  (SELECT TOP 1 D.SSP_SSN_SPOUSE FROM M4SSP_DEPEND_IRPF D
    WHERE D.ID_ORGANIZATION = A.ID_ORGANIZATION AND D.STD_ID_HR = A.STD_ID_HR
      AND D.STD_ID_ACT_DEP_TYP = '1' AND D.STD_DT_START <= @today AND D.STD_DT_END >= @today) AS SSP_NIF_CONYUGE,
  A.DT_START AS DT_START
FROM M4SSP_HT_SIT_IRPF A
LEFT JOIN M4SSP_TIPO_MINUSV M ON M.ID_ORGANIZATION = '0000' AND M.SSP_ID_MINUSVALIA = A.SSP_ID_MINUSVALIA
LEFT JOIN M4SSP_EST_CIV_IRPF C ON C.ID_ORGANIZATION = '0000' AND C.SSP_ID_EST_IRPF = A.SSP_ID_EST_IRPF
WHERE A.ID_ORGANIZATION = @organization AND A.STD_ID_HR = @employeeId
ORDER BY A.DT_END DESC`,
  ),
  /** `SSE_HR_CONTACT!M4T_HR_CONTACT`: contactos de emergencia vigentes. */
  emergencia: own(
    ["STD_HR_CONTACT"],
    `SELECT C.STD_N_CONTACT AS STD_N_CONTACT, C.STD_PHONE_NUMBER_1 AS STD_PHONE_NUMBER_1,
  C.SCO_ICE AS SCO_ICE
FROM STD_HR_CONTACT C
WHERE C.ID_ORGANIZATION IN ('0000', @organization) AND C.STD_ID_HR = @employeeId
  AND C.STD_DT_END >= @today
ORDER BY C.SCO_ICE`,
  ),
  /** `SSE_FAMILY!M4T_FAMILY`: dependientes vigentes con sus datos personales. */
  dependientes: own(
    ["STD_FAMILY", "STD_PERSON", "STD_LU_DEP_TYPE"],
    `SELECT P.STD_N_FIRST_NAME AS STD_N_FIRST_NAME, P.SSP_PRIM_APELLIDO AS SSP_PRIMER_APELLIDO,
  P.STD_N_MAIDEN_NAME AS STD_N_MAIDEN_NAME, P.STD_DT_BIRTH AS STD_DT_BIRTH,
  D.STD_N_DEP_TYPEESP AS STD_N_DEP_TYPE, F.STD_DT_START AS STD_DT_START
FROM STD_FAMILY F
LEFT JOIN STD_PERSON P ON P.ID_ORGANIZATION = F.ID_ORGANIZATION AND P.STD_ID_PERSON = F.STD_ID_FAMILY_PERS
LEFT JOIN STD_LU_DEP_TYPE D ON D.ID_ORGANIZATION = F.ID_ORGANIZATION AND D.STD_ID_DEP_TYPE = F.STD_ID_DEP_TYPE
WHERE F.ID_ORGANIZATION IN ('0000', @organization) AND F.STD_ID_HR = @employeeId
  AND F.STD_DT_END >= @today
ORDER BY F.STD_DT_START`,
  ),
} as const satisfies Record<string, PortalSqlQuery>;

const level = (alias: string, column: string) =>
  `(SELECT TOP 1 L.STD_N_LANG_LEVESP FROM STD_LU_LANG_LEVEL L
    WHERE L.ID_ORGANIZATION = H.ID_ORGANIZATION AND L.STD_ID_LANG_LEVEL = H.${column}) AS ${alias}`;

/** «Datos profesionales»: nodos `M4T_*` de `SSE_EMP_BACKGROUND` y objetos afines. */
export const PROFESIONALES_SQL = {
  /** `M4T_EMP_BACKGROUND`: titulaciones académicas. */
  titulaciones: own(
    ["STD_HR_ACAD_BACKGR", "STD_LU_EDU_DIPLOMA", "STD_LU_EDU_SPECIAL"],
    `SELECT D.STD_N_DIPLOMAESP AS STD_N_DIPLOMA, S.STD_N_EDU_SPESP AS STD_N_EDU_SP,
  A.STD_DESC_EDU_CENTER AS STD_DESC_EDU_CENTER, A.STD_DT_EARNED_EXPE AS STD_DT_EARNED_EXPE
FROM STD_HR_ACAD_BACKGR A
LEFT JOIN STD_LU_EDU_DIPLOMA D ON D.ID_ORGANIZATION = A.ID_ORGANIZATION AND D.STD_ID_DIPLOMA = A.STD_ID_DIPLOMA
LEFT JOIN STD_LU_EDU_SPECIAL S ON S.ID_ORGANIZATION = A.ID_ORGANIZATION AND S.STD_ID_EDU_SP = A.STD_ID_EDU_SP
WHERE A.ID_ORGANIZATION IN ('0000', @organization) AND A.STD_ID_HR = @employeeId
ORDER BY A.STD_DT_START`,
  ),
  /** `M4T_EMP_LANGUAGES` + `M4T_HT_EMP_LANGUAGES`: idiomas con su nivel vigente. */
  idiomas: own(
    ["STD_HR_LANG", "STD_HT_HR_LANG", "STD_LU_LANGUAGES", "STD_LU_LANG_LEVEL"],
    `SELECT G.STD_N_LANGUAGEESP AS STD_N_LANGUAGE,
  ${level("STD_N_SPEAK_LEVEL", "STD_ID_SPEAK_LEVEL")},
  ${level("STD_N_LISTEN_LEVEL", "STD_ID_LISTEN_LEV")},
  ${level("STD_N_WRITE_LEVEL", "STD_ID_WRITE_LEVEL")}
FROM STD_HR_LANG A
LEFT JOIN STD_LU_LANGUAGES G ON G.ID_ORGANIZATION = A.ID_ORGANIZATION AND G.STD_ID_LANGUAGE = A.STD_ID_LANGUAGE
OUTER APPLY (SELECT TOP 1 * FROM STD_HT_HR_LANG X
  WHERE X.ID_ORGANIZATION = A.ID_ORGANIZATION AND X.STD_ID_HR = A.STD_ID_HR
    AND X.STD_ID_LANGUAGE = A.STD_ID_LANGUAGE AND X.STD_DT_START <= @today
  ORDER BY X.STD_DT_START DESC) H
WHERE A.ID_ORGANIZATION IN ('0000', @organization) AND A.STD_ID_HR = @employeeId`,
  ),
  /** `M4T_EMP_PREV_JOBS`: experiencia profesional. */
  experiencia: own(
    ["STD_HR_PREV_JOBS"],
    `SELECT A.STD_EMPLOYER AS STD_EMPLOYER, COALESCE(A.STD_FINAL_JOB, A.CSP_N_PREV_JOB) AS STD_FINAL_JOB,
  A.STD_DT_START AS STD_DT_START, A.STD_DT_END AS STD_DT_END
FROM STD_HR_PREV_JOBS A
WHERE A.ID_ORGANIZATION IN ('0000', @organization) AND A.STD_ID_HR = @employeeId
ORDER BY A.STD_DT_START DESC`,
  ),
  /** `M4T_CERTIFICATION_LICEN`: certificados y licencias. */
  certificados: own(
    ["M4SCO_CERTIF_LICEN", "STD_LU_CERTIF_TYPE"],
    `SELECT A.SCO_N_CERTIFESP AS SCO_N_CERTIF, T.STD_CERTIF_TYPEESP AS STD_N_CERTIF_TYPE,
  A.SCO_DT_ISSUE AS SCO_DT_ISSUE, A.SCO_DT_EXPIRED AS SCO_DT_EXPIRED
FROM M4SCO_CERTIF_LICEN A
LEFT JOIN STD_LU_CERTIF_TYPE T ON T.ID_ORGANIZATION = A.ID_ORGANIZATION AND T.STD_ID_CERTIF_TYPE = A.SCO_ID_CERTIF_TYPE
WHERE A.ID_ORGANIZATION IN ('0000', @organization) AND A.SCO_ID_HR = @employeeId
ORDER BY A.SCO_DT_ISSUE DESC`,
  ),
  /** `M4T_HR_COMP_BACKGROUND`: otros cursos (formación externa). */
  otrosCursos: own(
    ["M4SCO_HR_COMP_BACK"],
    `SELECT A.SCO_N_COURSE AS SCO_N_COURSE, A.SCO_N_CENTER AS SCO_N_CENTER,
  A.SCO_NUMBER_HOURS AS SCO_NUMBER_HOURS, A.SCO_DT_START AS SCO_DT_START, A.SCO_DT_END AS SCO_DT_END
FROM M4SCO_HR_COMP_BACK A
WHERE A.ID_ORGANIZATION IN ('0000', @organization) AND A.STD_ID_HR = @employeeId
  AND (A.CSP_INTERNA = '0' OR A.CSP_INTERNA IS NULL)
ORDER BY A.SCO_DT_START DESC`,
  ),
  /** `M4T_ASSOCIATION_ME`: asociaciones profesionales. */
  asociaciones: own(
    ["M4SCO_ASSOC_ME", "M4SCO_X_ASSOCIATIO"],
    `SELECT X.SCO_N_ASSOCIATION AS SCO_N_ASSOCIATION, A.SCO_NM_POSITIONESP AS SCO_NM_POSITION,
  A.SCO_DT_START AS SCO_DT_START, A.SCO_DT_END AS SCO_DT_END
FROM M4SCO_ASSOC_ME A
LEFT JOIN M4SCO_X_ASSOCIATIO X ON X.ID_ORGANIZATION = A.ID_ORGANIZATION AND X.SCO_ID_ASSOCIATION = A.SCO_ID_ASSOCIATION
WHERE A.ID_ORGANIZATION IN ('0000', @organization) AND A.SCO_ID_HR = @employeeId
ORDER BY A.SCO_DT_START DESC`,
  ),
  /** `CSP_CV!CSP_FORMACION_INTERNA`: formación interna registrada para el CV. */
  formacionInterna: own(
    ["M4SCO_HR_COMP_BACK"],
    `SELECT A.SCO_N_COURSE AS SCO_N_COURSE, A.SCO_N_CENTER AS SCO_N_CENTER,
  A.SCO_NUMBER_HOURS AS SCO_NUMBER_HOURS, A.SCO_DT_START AS SCO_DT_START, A.SCO_DT_END AS SCO_DT_END
FROM M4SCO_HR_COMP_BACK A
WHERE A.ID_ORGANIZATION IN ('0000', @organization) AND A.STD_ID_HR = @employeeId AND A.CSP_INTERNA = '1'
ORDER BY A.SCO_DT_START DESC`,
  ),
  /** `CSP_CV!CSP_OTROS_TITULOS`: otros títulos del CV corporativo. */
  otrosTitulos: own(
    ["M4CSP_OTROS_TITULOS"],
    `SELECT A.CSP_TITULO AS CSP_TITULO, A.DT_START AS DT_START, A.DT_END AS DT_END
FROM M4CSP_OTROS_TITULOS A
WHERE A.ID_ORGANIZATION = @organization AND A.STD_ID_HR = @employeeId
ORDER BY A.DT_START DESC`,
  ),
  /** `M4T_HR_COMP_INFORMATION`: información complementaria. */
  complementaria: own(
    ["M4SCO_HR_COMP_INFO"],
    `SELECT CASE A.SCO_CK_TRAVEL_DISP WHEN 1 THEN 'Sí' WHEN 0 THEN 'No' END AS SCO_CK_TRAVEL_DISP,
  CASE A.SCO_CK_MOV_NAC WHEN 1 THEN 'Sí' WHEN 0 THEN 'No' END AS SCO_CK_MOV_NAC,
  CASE A.SCO_CK_MOV_INTER WHEN 1 THEN 'Sí' WHEN 0 THEN 'No' END AS SCO_CK_MOV_INTER,
  A.SCO_HOBBIES AS SCO_HOBBIES, A.SCO_OTHERS AS SCO_OTHERS
FROM M4SCO_HR_COMP_INFO A
WHERE A.ID_ORGANIZATION IN ('0000', @organization) AND A.STD_ID_HR = @employeeId`,
  ),
} as const satisfies Record<string, PortalSqlQuery>;
