import type { PortalSqlQuery } from "../../types";

/**
 * Lecturas de «Retribución» reproducidas desde las sentencias Meta4 originales
 * (`docs/portal/implementacion/lecturas-sql.md`). Todas filtran por la sociedad
 * y la matrícula del servidor. `DOC_KEY` es la clave de descarga del documento
 * de la fila (ver `src/lib/portal/data/documents-core.ts`).
 */

const own = (tables: readonly string[], statement: string): PortalSqlQuery => ({
  scope: "own",
  tables,
  statement,
});

export const RETRIBUCION_SQL = {
  /**
   * `SSE_LAST_HR_PAY_DOCS`: recibos de nómina (tipo de documento 0001) de pagas
   * publicadas (`SCO_ID_PAY_PUB_ST = '02'`), del más reciente al más antiguo.
   */
  recibos: own(
    ["M4SCO_HR_PAY_DOC", "M4SCO_HT_PAYS"],
    `SELECT A.SCO_DT_PAYMENT AS SCO_DT_PAYMENT, I.SCO_NM_PAYESP AS SCO_NM_PAY,
  K.SCO_NM_PAYESP AS SCO_NM_PAY_ALLOCATION, A.SCO_NM_DOC AS SCO_NM_DOC,
  CONCAT(A.STD_OR_HR_PERIOD, '|', CONVERT(VARCHAR(10), A.SCO_DT_PAYMENT, 23), '|',
    A.SCO_PAY_FREQ_PAYM, '|', A.SCO_OR_DOC) AS DOC_KEY
FROM M4SCO_HR_PAY_DOC A
JOIN M4SCO_HT_PAYS I ON I.ID_ORGANIZATION = A.ID_ORGANIZATION AND I.SCO_DT_ACCRUED = A.SCO_DT_PAYMENT
  AND I.SCO_ID_PAY_FREQ = A.SCO_PAY_FREQ_PAYM
LEFT JOIN M4SCO_HT_PAYS K ON K.ID_ORGANIZATION = A.ID_ORGANIZATION AND K.SCO_DT_ACCRUED = A.SCO_DT_ALLOCATION
  AND K.SCO_ID_PAY_FREQ = A.SCO_PAY_FREQ_ALLOC
WHERE A.ID_ORGANIZATION = @organization AND A.STD_ID_HR = @employeeId
  AND A.SCO_ID_DOC_TYPE = '0001' AND I.SCO_ID_PAY_PUB_ST = '02'
ORDER BY A.SCO_DT_PAYMENT DESC, A.SCO_DT_ALLOCATION DESC`,
  ),
  /** `CSP_CERT_DOC`: certificados de retenciones guardados por año. */
  certificados: own(
    ["M4CSP_CERT_DOC"],
    `SELECT C.ANIO AS ANIO, C.SCO_NM_DOC AS SCO_NM_DOC,
  CONCAT(C.STD_OR_HR_PERIOD, '|', C.SCO_OR_DOC) AS DOC_KEY
FROM M4CSP_CERT_DOC C
WHERE C.ID_ORGANIZATION = @organization AND C.STD_ID_HR = @employeeId
ORDER BY C.ANIO DESC`,
  ),
  /** `SSE_OTHER_PDATA!M4T_OTHER_PDATA`: cuentas adicionales vigentes (no la principal). */
  otrasCuentas: own(
    ["M4SCO_PAYMENT_DATA", "M4SCO_PERSON_BANK", "M4SCO_PAYM_FORMULA", "M4SCO_PAYMENT_TYPE"],
    `SELECT COALESCE(F.SCO_ENTITLED, F.SCO_NM_BNK) AS SCO_ENTITLED, A.SCO_DT_START AS SCO_DT_START,
  A.SCO_DT_END AS SCO_DT_END, F.SCO_GB_IBAN AS SCO_GB_IBAN, E.SCO_NM_PAYFORMESP AS SCO_NM_PAYMFORMULA,
  T.SOC_NM_PAYM_TYPESP AS SCO_NM_PAYM_TYPE
FROM M4SCO_PAYMENT_DATA A
LEFT JOIN M4SCO_PERSON_BANK F ON F.SCO_ID_PERSON = A.SCO_ID_PERSON AND F.SCO_OR_ACCOUNT = A.SCO_OR_ACCOUNT
LEFT JOIN M4SCO_PAYM_FORMULA E ON E.ID_ORGANIZATION = A.ID_ORGANIZATION AND E.SCO_ID_PAY_FORMULA = A.SCO_ID_PAY_FORMULA
LEFT JOIN M4SCO_PAYMENT_TYPE T ON T.ID_ORGANIZATION = A.ID_ORGANIZATION AND T.SCO_ID_PAYM_TYPE = A.SCO_ID_PAYM_TYPE
WHERE A.ID_ORGANIZATION = @organization AND A.SCO_ID_HR = @employeeId
  AND A.SCO_EMP_CHECK = '0' AND A.SCO_DT_END >= @today
ORDER BY A.SCO_DT_START DESC`,
  ),
  /** `SSE_LOANS!M4T_LN_HT_HR_LOANS`: préstamos concedidos con su condición vigente. */
  prestamos: own(
    [
      "M4SCO_LN_HT_HR_LOA",
      "M4SCO_LN_LU_LOANS",
      "M4SCO_LN_HT_CONDIT",
      "M4SCO_LN_LU_REASON",
      "M4SCO_LN_LU_POFF_F",
    ],
    `SELECT B.SCO_NM_LOANESP AS SCO_NM_LOAN, A.SCO_DT_APPLICATION AS SCO_DT_APPLICATION,
  A.SCO_DT_APPROVAL AS SCO_DT_APPROVAL, A.SCO_AMT_LOAN AS SCO_AMT_LOAN, C.SCO_RATE AS SCO_RATE,
  C.SCO_NUM_QUOTAS AS SCO_NUM_QUOTAS, C.SCO_AMT_QUOTAS AS SCO_AMT_QUOTAS,
  R.SCO_NM_REASONESP AS SCO_NM_REASON, P.SCO_NM_PAY_OFFESP AS SCO_NM_PAY_OFF_FREQ,
  A.SCO_DT_REQ_PAYMENT AS SCO_DT_REQ_PAYMENT
FROM M4SCO_LN_HT_HR_LOA A
LEFT JOIN M4SCO_LN_LU_LOANS B ON B.ID_ORGANIZATION = A.ID_ORGANIZATION AND B.SCO_ID_LOAN = A.SCO_ID_LOAN
OUTER APPLY (SELECT TOP 1 * FROM M4SCO_LN_HT_CONDIT X
  WHERE X.ID_ORGANIZATION = A.ID_ORGANIZATION AND X.STD_ID_HR = A.STD_ID_HR
    AND X.STD_OR_HR_PERIOD = A.STD_OR_HR_PERIOD AND X.SCO_ID_LOAN = A.SCO_ID_LOAN
    AND X.SCO_OR_LOAN = A.SCO_OR_LOAN
  ORDER BY X.DT_START DESC) C
LEFT JOIN M4SCO_LN_LU_REASON R ON R.ID_ORGANIZATION = A.ID_ORGANIZATION
  AND R.SCO_ID_REASON = COALESCE(C.SCO_ID_REASON, A.SCO_ID_REASON)
LEFT JOIN M4SCO_LN_LU_POFF_F P ON P.ID_ORGANIZATION = A.ID_ORGANIZATION AND P.SCO_ID_PAY_OFF_FRE = C.SCO_ID_PAY_OFF_FRE
WHERE A.ID_ORGANIZATION = @organization AND A.STD_ID_HR = @employeeId
ORDER BY A.SCO_DT_REQ_PAYMENT DESC`,
  ),
  /** `SSE_BFT_H_EE_IN_BNFT!M4T_H_EE_IN_BNFT`: beneficios vigentes con sus costes. */
  beneficios: own(
    ["M4SUS_H_EE_IN_BNFT", "M4SUS_PLAN", "M4SUS_PLAN_OPTION"],
    `SELECT P.SUS_N_PLANESP AS SUS_N_PLAN, O.SUS_N_OPTIONESP AS SUS_N_OPTION,
  A.SUS_DT_START AS SUS_DT_START, A.SUS_DT_END AS SUS_DT_END,
  A.SUS_PRICE AS SUS_PRICE, A.SUS_ER_CONTR AS SUS_ER_CONTR
FROM M4SUS_H_EE_IN_BNFT A
LEFT JOIN M4SUS_PLAN P ON P.ID_ORGANIZATION = A.ID_ORGANIZATION AND P.SUS_ID_PLAN = A.SUS_ID_PLAN
LEFT JOIN M4SUS_PLAN_OPTION O ON O.ID_ORGANIZATION = A.ID_ORGANIZATION AND O.SUS_ID_PLAN = A.SUS_ID_PLAN
  AND O.SUS_ID_OPTION = A.SUS_ID_OPTION
WHERE A.ID_ORGANIZATION = @organization AND A.SUS_ID_HR = @employeeId AND A.SUS_DT_END >= @today
ORDER BY A.SUS_DT_START DESC`,
  ),
  /** `SSE_H_SAL_DATA`: paquete salarial vigente (teórico y real por jornada). */
  paquete: own(
    ["M4SCO_H_SAL_DATA"],
    `SELECT TOP 1 A.SCO_FIX_SALARY AS SCO_FIX_SALARY, A.SCO_FIX_SALARY_RL AS SCO_FIX_SALARY_REAL,
  A.SCO_VAR_SALARY AS SCO_VAR_SALARY, A.SCO_VAR_SALARY_RL AS SCO_VAR_SALARY_REAL,
  A.SCO_VAR_SALARY_PER AS SCO_VAR_SALARY_PER, A.SCO_BNFT_LEG_ENT AS SCO_BNFT_LEG_ENT,
  A.ID_CURRENCY AS ID_CURRENCY, A.SCO_DT_START AS SCO_DT_START
FROM M4SCO_H_SAL_DATA A
WHERE A.ID_ORGANIZATION = @organization AND A.SCO_ID_HR = @employeeId AND A.SCO_DT_START <= @today
ORDER BY A.SCO_DT_START DESC`,
  ),
  /** `CSP_RP_PROYECCIONES!SSE_DATOS_PROYECCION`: cabecera de la última proyección calculada. */
  proyeccionDatos: own(
    ["M4CSP_DATOS_PROYECCION"],
    `SELECT TOP 1 A.CSP_FEC_EJECUCION AS CSP_FEC_EJECUCION, A.SSP_NM_CATEGORIA AS SSP_NM_CATEGORIA,
  A.SCO_N_WORK_LOCATION AS SCO_N_WORK_LOCATION, A.PAGA_TOT AS PAGA_TOT
FROM M4CSP_DATOS_PROYECCION A
WHERE A.ID_ORGANIZATION = @organization AND A.STD_ID_HR = @employeeId
ORDER BY A.CSP_FEC_EJECUCION DESC`,
  ),
  /** `CSP_RP_PROYECCIONES!SSE_EXTRAC_PROYECCION`: conceptos de la proyección por bloque. */
  proyeccionConceptos: own(
    ["M4CSP_EXTRAC_PROYECCION"],
    `SELECT CASE A.CSP_ID_GRUPO WHEN 'RD' THEN 'Retribución directa'
    WHEN 'RI' THEN 'Retribución indirecta. Beneficios sociales'
    WHEN 'PPSE' THEN 'Plan de previsión social empresarial'
    WHEN 'RQ' THEN 'Compromisos a la jubilación'
    WHEN 'RET' THEN 'Retenciones'
    ELSE 'Resumen' END AS CSP_GRUPO,
  A.ID_ITEM AS ID_ITEM, A.TOTAL AS TOTAL
FROM M4CSP_EXTRAC_PROYECCION A
WHERE A.ID_ORGANIZATION = @organization AND A.STD_ID_HR = @employeeId
  AND A.STD_OR_HR_PERIOD = (SELECT MAX(X.STD_OR_HR_PERIOD) FROM M4CSP_EXTRAC_PROYECCION X
    WHERE X.ID_ORGANIZATION = A.ID_ORGANIZATION AND X.STD_ID_HR = A.STD_ID_HR)
ORDER BY A.CSP_ORDEN`,
  ),
  /** `CSP_RP_PROYECCIONES!CSP_ANIOS_PROYECCIONES`: informes de proyección guardados por año. */
  proyeccionInformes: own(
    ["M4CSP_PROYEC_DOC"],
    `SELECT P.ANIO AS ANIO, P.SCO_NM_DOC AS SCO_NM_DOC,
  CONCAT(P.STD_OR_HR_PERIOD, '|', P.ANIO) AS DOC_KEY
FROM M4CSP_PROYEC_DOC P
WHERE P.ID_ORGANIZATION = @organization AND P.STD_ID_HR = @employeeId
ORDER BY P.ANIO DESC`,
  ),
} as const satisfies Record<string, PortalSqlQuery>;
