import type { PortalSqlQuery } from "../../types";

/**
 * Lecturas de «Talento» reproducidas desde `SSE_JOB`, `SSE_H_HR_COURSE`,
 * `SSE_TRAINING_REQUEST`, `SSE_TRAINING_EVAL`, `SSCO_H_EVALUTE`,
 * `SSE_CAREER_PLAN`, `SSE_INT_MOVILITY`, `SSCO_DEV_PLAN` y `SSE_GN_INTERVIEW`
 * (`docs/portal/implementacion/lecturas-sql.md`).
 */

const own = (tables: readonly string[], statement: string): PortalSqlQuery => ({
  scope: "own",
  tables,
  statement,
});

const society = (tables: readonly string[], statement: string): PortalSqlQuery => ({
  scope: "society",
  tables,
  statement,
});

/** Cursos (subproductos) por su identificador, en español. */
const COURSE_NAME = `LEFT JOIN M4SCO_DEVEL_SUBPRO S ON S.ID_ORGANIZATION IN ('0000', A.ID_ORGANIZATION)
  AND S.SCO_ID_DEV_SUBPROD = A.SCO_ID_DEV_SUBPROD`;

export const TALENTO_SQL = {
  /** `SSE_JOB!SSE_H_HR_JOB`: historial de puestos. */
  puestos: own(
    ["M4SCO_H_HR_JOB", "STD_JOB"],
    `SELECT J.STD_N_JOB_CODEESP AS STD_N_JOB_CODE, A.SCO_DT_START AS SCO_DT_START,
  A.SCO_DT_END AS SCO_DT_END
FROM M4SCO_H_HR_JOB A
LEFT JOIN STD_JOB J ON J.ID_ORGANIZATION = A.ID_ORGANIZATION AND J.STD_ID_JOB_CODE = A.SCO_ID_JOB_CODE
  AND J.STD_DT_START <= A.SCO_DT_START AND J.STD_DT_END >= A.SCO_DT_START
WHERE A.ID_ORGANIZATION = @organization AND A.SCO_ID_HR = @employeeId
ORDER BY A.SCO_DT_START DESC`,
  ),
  /** `SSE_H_HR_COURSE`: formación realizada y su estado. */
  formacionRealizada: own(
    ["M4SCO_H_HR_COURSE", "M4SCO_DEVEL_SUBPRO", "M4SCO_X_STATE_COUR"],
    `SELECT S.SCO_NM_DEV_SUBESP AS SCO_NM_DEV_SUBPRODUCT, A.SCO_DT_START AS SCO_DT_START,
  A.SCO_DT_END AS SCO_DT_END, E.SCO_NM_STATEESP AS SCO_NM_STATE
FROM M4SCO_H_HR_COURSE A
${COURSE_NAME}
LEFT JOIN M4SCO_X_STATE_COUR E ON E.ID_ORGANIZATION IN ('0000', A.ID_ORGANIZATION) AND E.SCO_ID_STATE = A.SCO_ID_STATE
WHERE A.ID_ORGANIZATION = @organization AND A.SCO_ID_PERSON = @employeeId
ORDER BY A.SCO_DT_END DESC`,
  ),
  /** `SSE_TRAINING_REQUEST!M4T_CURSOS`: cursos publicados que se pueden solicitar. */
  cursosOfertados: society(
    ["M4SCO_TRTB_REQ", "M4SCO_DEVEL_SUBPRO"],
    `SELECT DISTINCT S.SCO_NM_DEV_SUBESP AS SCO_NM_DEV_SUBPRODUCT, S.SCO_DAYS AS SCO_DAYS,
  S.SCO_HOURS AS SCO_HOURS, S.SCO_HOURS_OTW AS SCO_HOURS_OTW, S.SCO_NB_MIN AS SCO_NB_MIN,
  S.SCO_NB_MAX AS SCO_NB_MAX, S.SCO_EDUCAT_OBJ AS SCO_EDUCAT_OBJ
FROM M4SCO_TRTB_REQ A
${COURSE_NAME}
WHERE A.ID_ORGANIZATION = @organization AND A.SCO_ID_TYPE = 11
  AND (A.DT_END >= @today OR A.DT_END IS NULL)
  AND S.SCO_DT_INI_PUBLISH IS NOT NULL AND S.SCO_DT_INI_PUBLISH <= @today AND S.SCO_DT_END_PUBLISH > @today`,
  ),
  /** `SSE_TRAINING_REQUEST!SSE_TRAINING_REQUEST`: solicitudes pendientes de validar. */
  solicitudesPendientes: own(
    ["M4SSE_TRAINING_REQUEST", "M4SSE_ACCIONES"],
    `SELECT A.SCO_NM_TRAINING AS SCO_NM_TRAINING, A.SCO_NM_TYPE AS SCO_NM_TYPE,
  COALESCE(X.N_ACCIONESP, A.ID_ESTADO_REG) AS N_ACCION
FROM M4SSE_TRAINING_REQUEST A
LEFT JOIN M4SSE_ACCIONES X ON X.ID_ORGANIZATION IN ('0000', A.ID_ORGANIZATION)
  AND X.ACCION_ACEPTADO = A.ACCION_ACEPTADO
WHERE A.ID_ORGANIZATION = @organization AND A.STD_ID_PERSON = @employeeId
  AND A.ID_ESTADO_REG = 'PENDIENTE'
ORDER BY A.ORDINAL DESC`,
  ),
  /** `SSE_TRAINING_REQUEST!M4T_SOLICITUDES_ACEPTADAS`: solicitudes tramitadas y su estado. */
  solicitudesAceptadas: own(
    [
      "M4SCO_REQ_DETAIL",
      "M4SCO_TRTB_REQ",
      "M4SCO_DEVEL_SUBPRO",
      "M4SCO_SUBACTION",
      "M4SCO_REQ_STATUS",
    ],
    `SELECT S.SCO_NM_DEV_SUBESP AS SCO_NM_DEV_SUBPRODUCT, E.SCO_NM_DEV_SUBESP AS SCO_NM_DEV_SUBACTION,
  R.SCO_NM_REQ_STATESP AS SCO_NM_REQ_STATUS, D.DT_START AS DT_START, D.DT_END AS DT_END
FROM M4SCO_REQ_DETAIL D
LEFT JOIN M4SCO_TRTB_REQ A ON A.ID_ORGANIZATION = D.ID_ORGANIZATION AND A.SCO_ID_TRTBREQ = D.SCO_ID_TRTBREQ
${COURSE_NAME}
LEFT JOIN M4SCO_SUBACTION E ON E.ID_ORGANIZATION = A.ID_ORGANIZATION AND E.SCO_ID_DEV_SUBACTI = A.SCO_ID_DEV_SUBACTI
LEFT JOIN M4SCO_REQ_STATUS R ON R.ID_ORGANIZATION IN ('0000', D.ID_ORGANIZATION)
  AND R.SCO_ID_REQ_STATUS = D.SCO_ID_REQ_STATUS
WHERE D.ID_ORGANIZATION = @organization AND D.STD_ID_PERSON = @employeeId
ORDER BY D.DT_START DESC`,
  ),
  /** `SSE_TRAINING_EVAL!SSE_EVEN_EVAL_SHEET`: cuestionarios de evaluación de cursos. */
  evaluacionCursos: own(
    ["M4SCO_EV_EVAL_SHT", "M4SCO_SUBACTION"],
    `SELECT E.SCO_NM_DEV_SUBESP AS SCO_NM_DEV_SUBACTION, E.DT_START AS DT_START, E.DT_END AS DT_END
FROM M4SCO_EV_EVAL_SHT A
LEFT JOIN M4SCO_SUBACTION E ON E.ID_ORGANIZATION = A.ID_ORGANIZATION AND E.SCO_ID_DEV_SUBACTI = A.SCO_ID_DEV_SUBACTI
WHERE A.ID_ORGANIZATION = @organization AND A.STD_ID_PERSON = @employeeId
ORDER BY E.DT_START DESC`,
  ),
  /** `SSCO_H_EVALUTE!SSCO_H_EVALUATE` + `SSCO_PROC_EVAL`: procesos de evaluación. */
  evaluaciones: own(
    ["M4SCO_H_EVALUATE", "M4SCO_H_EVAL_PROC", "M4SCO_SCALE_LEVEL"],
    `SELECT P.SCO_NM_EVAL_PROESP AS SCO_NM_EVAL_PROC, P.SCO_DT_ST_EV_PER AS SCO_DT_ST_EV_PER,
  P.SCO_DT_END_EV_PER AS SCO_DT_END_EV_PER,
  (SELECT TOP 1 L.SCO_NM_LEVELESP FROM M4SCO_SCALE_LEVEL L
    WHERE L.ID_ORGANIZATION IN ('0000', A.ID_ORGANIZATION) AND L.SCO_ID_LEVEL = A.SCO_ID_LEVEL_OBJ) AS SCO_NM_LEVEL_OBJ,
  (SELECT TOP 1 L.SCO_NM_LEVELESP FROM M4SCO_SCALE_LEVEL L
    WHERE L.ID_ORGANIZATION IN ('0000', A.ID_ORGANIZATION) AND L.SCO_ID_LEVEL = A.SCO_ID_LEVEL_CAP) AS SCO_NM_LEVEL_CAP
FROM M4SCO_H_EVALUATE A
LEFT JOIN M4SCO_H_EVAL_PROC P ON P.ID_ORGANIZATION = A.ID_ORGANIZATION
  AND P.SCO_ID_EVAL_PLAN = A.SCO_ID_EVAL_PLAN AND P.SCO_DT_START_PROC = A.SCO_DT_START_PROC
WHERE A.ID_ORGANIZATION = @organization AND A.SCO_ID_HR = @employeeId
ORDER BY A.SCO_DT_START_EVAL DESC`,
  ),
  /** `SSCO_H_EVALUTE!SSCO_EVALUATOR`: evaluaciones recibidas de cada evaluador. */
  evaluadores: own(
    ["M4SCO_EVALUATOR", "M4ORO_EMPLEADOS"],
    `SELECT LTRIM(RTRIM(CONCAT(O.NOMBRE, ' ', O.APELLIDO_1, ' ', O.APELLIDO_2))) AS SCO_NM_EVALUATOR,
  A.SCO_DT_START_EVAL AS SCO_DT_START_EVAL, A.SCO_EVALUAT_DATE AS SCO_EVALUAT_DATE
FROM M4SCO_EVALUATOR A
LEFT JOIN M4ORO_EMPLEADOS O ON O.ID_ORGANIZATION = A.ID_ORGANIZATION AND O.ID_EMPLEADO = A.SCO_ID_EVALUATOR
  AND O.COMPUTA = '1'
WHERE A.ID_ORGANIZATION = @organization AND A.SCO_ID_HR = @employeeId
ORDER BY A.SCO_DT_START_EVAL DESC`,
  ),
  /** `SSE_CAREER_PLAN!SSE_CR_PLAN_HT`: planes de carrera. */
  carrera: own(
    ["M4SCO_CR_PLAN_HT"],
    `SELECT A.SCO_NM_CR_PLANESP AS SCO_NM_CR_PLAN, A.DT_START AS DT_START, A.DT_END AS DT_END
FROM M4SCO_CR_PLAN_HT A
WHERE A.ID_ORGANIZATION = @organization AND A.STD_ID_HR = @employeeId
ORDER BY A.DT_START DESC`,
  ),
  /** `SSE_INT_MOVILITY!M4T_RECRUIT_PRO`: procesos de selección abiertos (vacantes). */
  vacantes: society(
    ["M4SCO_RECRUIT_PRO", "STD_JOB"],
    `SELECT A.SCO_NM_RECRUITESP AS SCO_NM_RECRUIT, J.STD_N_JOB_CODEESP AS STD_N_JOB_CODE,
  A.SCO_DT_LIMIT AS SCO_DT_LIMIT
FROM M4SCO_RECRUIT_PRO A
LEFT JOIN STD_JOB J ON J.ID_ORGANIZATION = A.ID_ORGANIZATION AND J.STD_ID_JOB_CODE = A.SCO_ID_JOB
  AND J.STD_DT_START <= @today AND J.STD_DT_END >= @today
WHERE A.ID_ORGANIZATION = @organization AND (A.SCO_DT_END >= @today OR A.SCO_DT_END IS NULL)
ORDER BY A.SCO_DT_START DESC`,
  ),
  /** `SSE_INT_MOVILITY!SSE_INT_MOVILITY`: mis peticiones de movilidad. */
  peticionesMovilidad: own(
    ["M4SSE_INT_MOVILITY"],
    `SELECT A.SCO_NM_RECRUITESP AS SCO_NM_RECRUIT, A.SSE_SOLIC_DATE AS SSE_SOLIC_DATE,
  A.ID_ESTADO_REG AS ID_ESTADO_REG
FROM M4SSE_INT_MOVILITY A
WHERE A.ID_ORGANIZATION = @organization AND A.STD_ID_PERSON = @employeeId
ORDER BY A.SSE_SOLIC_DATE DESC`,
  ),
  /** `SSCO_DEV_PLAN!SSCO_DEV_PLAN`: acciones de desarrollo visibles para el empleado. */
  desarrollo: own(
    ["M4SCO_CR_ACTION_HR"],
    `SELECT A.SCO_NM_ACTIONESP AS SCO_NM_ACTION, A.SCO_DT_START AS SCO_DT_START, A.SCO_DT_END AS SCO_DT_END,
  CASE A.SCO_IS_FINISHED WHEN 1 THEN 'Finalizada' ELSE 'En curso' END AS SCO_IS_FINISHED,
  A.SCO_FINISH_DESC AS SCO_FINISH_DESC
FROM M4SCO_CR_ACTION_HR A
WHERE A.ID_ORGANIZATION = @organization AND A.SCO_ID_HR = @employeeId
  AND (A.SCO_IS_VISIBLE = 1 OR A.SCO_IS_VISIBLE IS NULL)
ORDER BY A.SCO_DT_START DESC`,
  ),
  /** `CSP_PUBLICACIONES_ESS`: documentos de RR. HH. publicados para empleados. */
  publicaciones: society(
    ["M4RCH_TEMPL_DOC"],
    `SELECT A.N_TEMPLATE1ESP AS N_FILE, A.COMMENTSESP AS COMMENTS
FROM M4RCH_TEMPL_DOC A
WHERE A.ID_TEMPLATE = 'PUBLICACIONESESS'
ORDER BY A.N_TEMPLATE1ESP`,
  ),
  /** `SSE_GN_INTERVIEW!M4T_GN_INTERVIEW`: entrevistas. */
  entrevistas: own(
    ["M4SCO_GN_INTERVIEW", "M4SCO_X_IV_TYPE"],
    `SELECT A.SCO_INTERVIEW_NAME AS SCO_INTERVIEW_NAME, T.SCO_NM_IV_TYPEESP AS SCO_NM_IV_TYPE,
  A.SCO_DT_REQUEST AS SCO_DT_REQUEST, A.SCO_DT_FINISH AS SCO_DT_FINISH
FROM M4SCO_GN_INTERVIEW A
LEFT JOIN M4SCO_X_IV_TYPE T ON T.ID_ORGANIZATION IN ('0000', A.ID_ORGANIZATION) AND T.SCO_ID_IV_TYPE = A.SCO_ID_IV_TYPE
WHERE A.ID_ORGANIZATION = @organization AND A.SCO_ID_HR = @employeeId
ORDER BY A.SCO_DT_REQUEST DESC`,
  ),
} as const satisfies Record<string, PortalSqlQuery>;
