import type { PortalSqlQuery } from "../../types";

/**
 * Lecturas de «Tiempo» reproducidas desde `SSE_HOLYDAYS`, `SSE_REAL_TIME`,
 * `SSE_CARGA_FESTIVOS`, `SSE_GTA_PLAN` y `SSE_GTA_VIRTUAL_CLOCK_IN_OUT`
 * (`docs/portal/implementacion/lecturas-sql.md`). Las incidencias y sus
 * catálogos viven en la organización compartida `0000`.
 */

const own = (tables: readonly string[], statement: string): PortalSqlQuery => ({
  scope: "own",
  tables,
  statement,
});

/** Incidencias del grupo de vacaciones (`SFR_ID_ITR_GROUP = '02'`), como `SSE_HOLYDAYS!SSE_INCIDENCE`. */
const VACATION_INCIDENCES = `SELECT I.SCO_ID_INCIDENCE FROM M4SCO_INCIDENCE I
  JOIN M4SCO_INCIDENCE_GR G ON G.ID_ORGANIZATION = I.ID_ORGANIZATION AND G.SCO_ID_INC_GROUP = I.SCO_ID_INC_GROUP
  WHERE G.SFR_ID_ITR_GROUP = '02'`;

const INCIDENCE_JOINS = `LEFT JOIN M4SCO_INCIDENCE B ON B.ID_ORGANIZATION IN ('0000', A.ID_ORGANIZATION)
  AND B.SCO_ID_INCIDENCE = A.SCO_ID_INCIDENCE
LEFT JOIN M4SCO_X_TIME_UNIT C ON C.ID_ORGANIZATION IN ('0000', A.ID_ORGANIZATION)
  AND C.SCO_ID_TIME_UNIT = A.SCO_ID_TIME_UNIT`;

export const TIEMPO_SQL = {
  /** `SSE_HOLYDAYS!SSE_AB_HRP_ENT_SUMMARY`: derechos de vacaciones vigentes por incidencia. */
  bolsa: own(
    ["M4SCO_AB_H_HRP_ENT_SUMMARY", "M4SCO_X_AB_ENTITLEMENT_TYPE", "M4SCO_INCIDENCE"],
    `SELECT B.SCO_INCIDENCEESP AS SCO_NM_INCIDENCE, SUM(A.SCO_NUM_ENTITLEMENT) AS SCO_NUM_ENTITLEMENT,
  SUM(A.SCO_NUM_ENTITLEMENT_N1) AS SCO_NUM_ENTITLEMENT_N1, SUM(A.SCO_NUM_USED) AS SCO_NUM_USED,
  SUM(A.SCO_TOT_REMAINING) AS SCO_NUM_REMAINING, MIN(A.SCO_DT_END) AS SCO_DT_END
FROM M4SCO_AB_H_HRP_ENT_SUMMARY A
JOIN M4SCO_X_AB_ENTITLEMENT_TYPE T ON T.ID_ORGANIZATION = A.ID_ORGANIZATION
  AND T.SCO_ID_ENTITLEMENT_TYPE = A.SCO_ID_ENTITLEMENT_TYPE
LEFT JOIN M4SCO_INCIDENCE B ON B.ID_ORGANIZATION IN ('0000', A.ID_ORGANIZATION)
  AND B.SCO_ID_INCIDENCE = T.SCO_ID_INCIDENCE
WHERE A.ID_ORGANIZATION = @organization AND A.SCO_ID_HR = @employeeId AND A.SCO_DT_END >= @today
GROUP BY B.SCO_INCIDENCEESP`,
  ),
  /** `SSE_HOLYDAYS!SSE_REAL_TIME_PRD`: peticiones de vacaciones y su estado. */
  peticiones: own(
    ["M4SSE_REAL_TIME_PR", "M4SSE_ACCIONES", "M4SCO_INCIDENCE", "M4SCO_X_TIME_UNIT"],
    `SELECT B.SCO_INCIDENCEESP AS SCO_NM_INCIDENCE, A.SCO_DT_START AS SSE_DT_START,
  A.SCO_DT_END AS SSE_DT_END, A.SCO_UNITS AS SCO_UNITS, C.SCO_NM_TIME_UNIESP AS SCO_NM_TIME_UNIT,
  COALESCE(X.N_ACCIONESP, A.ID_ESTADO_REG) AS N_ACCION
FROM M4SSE_REAL_TIME_PR A
LEFT JOIN M4SSE_ACCIONES X ON X.ID_ORGANIZATION IN ('0000', A.ID_ORGANIZATION)
  AND X.ACCION_ACEPTADO = A.ACCION_ACEPTADO
${INCIDENCE_JOINS}
WHERE A.ID_ORGANIZATION = @organization AND A.STD_ID_HR = @employeeId
ORDER BY A.SCO_DT_START DESC`,
  ),
  /** `SSE_HOLYDAYS!M4T_REAL_TIME_PRD`: vacaciones registradas (aceptadas). */
  aceptadas: own(
    ["M4SCO_REAL_TM_PRD", "M4SCO_INCIDENCE", "M4SCO_INCIDENCE_GR", "M4SCO_X_TIME_UNIT"],
    `SELECT B.SCO_INCIDENCEESP AS SCO_NM_INCIDENCE, A.SCO_DT_START AS SCO_DT_START,
  A.SCO_DT_END AS SCO_DT_END, A.SCO_UNITS AS SCO_UNITS, C.SCO_NM_TIME_UNIESP AS SCO_NM_TIME_UNIT
FROM M4SCO_REAL_TM_PRD A
${INCIDENCE_JOINS}
WHERE A.ID_ORGANIZATION = @organization AND A.STD_ID_HR = @employeeId
  AND A.SCO_ID_INCIDENCE IN (${VACATION_INCIDENCES})
ORDER BY A.SCO_DT_START DESC`,
  ),
  /** `SSE_REAL_TIME!SSE_REAL_TIME`: ausencias registradas en el año en curso. */
  ausencias: own(
    ["M4SCO_REAL_TM_PRD", "M4SCO_INCIDENCE", "M4SCO_X_TIME_UNIT"],
    `SELECT B.SCO_INCIDENCEESP AS SCO_NM_INCIDENCE, A.SCO_DT_START AS SCO_DT_START,
  A.SCO_DT_END AS SCO_DT_END, A.SCO_UNITS AS SCO_UNITS, C.SCO_NM_TIME_UNIESP AS SCO_NM_TIME_UNIT
FROM M4SCO_REAL_TM_PRD A
${INCIDENCE_JOINS}
WHERE A.ID_ORGANIZATION = @organization AND A.STD_ID_HR = @employeeId
  AND YEAR(A.SCO_DT_START) = YEAR(@today)
ORDER BY A.SCO_DT_START DESC`,
  ),
  /** `SSE_CARGA_FESTIVOS!SSE_FESTIVOS`: festivos del año del calendario del empleado. */
  festivos: own(
    ["M4SCO_HR_REAL_WORK_DAYS", "M4SCO_CALENDAR_REP", "M4SCO_DAYCALEN_TP"],
    `SELECT R.SCO_DT_DAY AS SCO_DT_DAY, T.SCO_DAYCALEN_TESP AS SCO_NM_DAYCALEN_TYPE,
  R.SCO_COMMENT AS SCO_COMMENT
FROM M4SCO_CALENDAR_REP R
LEFT JOIN M4SCO_DAYCALEN_TP T ON T.ID_ORGANIZATION IN ('0000', R.ID_ORGANIZATION)
  AND T.SCO_ID_DAYCALEN_TY = R.SCO_ID_DAYCALEN_TY
WHERE R.ID_ORGANIZATION = @organization AND YEAR(R.SCO_DT_DAY) = YEAR(@today)
  AND R.SCO_ID_CALENDAR = (SELECT TOP 1 W.SCO_ID_CALENDAR FROM M4SCO_HR_REAL_WORK_DAYS W
    WHERE W.ID_ORGANIZATION = @organization AND W.STD_ID_HR = @employeeId AND W.DT_START <= @today
    ORDER BY W.DT_START DESC)
ORDER BY R.SCO_DT_DAY`,
  ),
  /** `SSE_GTA_PLAN!SSE_GTA_PLAN`: planificación de los próximos días. */
  planificacion: own(
    ["M4SCO_HR_REAL_WORK_DAYS", "M4SCO_DAY_TYPE"],
    `SELECT TOP 31 W.DT_START AS DT_START, D.NM_DAY_TYPEESP AS SCO_NM_DAY_TYPE,
  W.SCO_WORK_THEO_HRS AS SCO_WORK_THEO_HRS, W.SCO_REAL_WORK_HRS AS SCO_REAL_WORK_HRS
FROM M4SCO_HR_REAL_WORK_DAYS W
LEFT JOIN M4SCO_DAY_TYPE D ON D.ID_ORGANIZATION IN ('0000', W.ID_ORGANIZATION)
  AND D.SCO_ID_DAY_TYPE = W.SCO_ID_DAY_TYPE
WHERE W.ID_ORGANIZATION = @organization AND W.STD_ID_HR = @employeeId AND W.DT_START >= @today
ORDER BY W.DT_START`,
  ),
  /** `SSE_GTA_VIRTUAL_CLOCK_IN_OUT!SSE_GTA_VIRTUAL_CLOCK`: últimos fichajes validados. */
  fichajes: own(
    ["M4SCO_HR_CLOCK_IN_OUT_DEC"],
    `SELECT TOP 20 F.SCO_DT_DATE_AND_HOUR AS SCO_DT_DATE_AND_HOUR,
  CASE F.SCO_IN_OR_OUT WHEN 1 THEN 'Entrada' WHEN 0 THEN 'Salida' ELSE CAST(F.SCO_IN_OR_OUT AS VARCHAR(10)) END AS SCO_IN_OR_OUT
FROM M4SCO_HR_CLOCK_IN_OUT_DEC F
WHERE F.ID_ORGANIZATION = @organization AND F.STD_ID_HR = @employeeId AND F.SCO_ID_STATUS = 2
ORDER BY F.SCO_DT_DATE_AND_HOUR DESC`,
  ),
} as const satisfies Record<string, PortalSqlQuery>;
