;--------------------------------------------------------------------------------------
; @(#) FileVersion: 815.002.001
; @(#) FileDescription: Web Services initialization file.
; @(#) CompanyName: Meta4 Spain, S.A.
; @(#) LegalCopyright: (c) 2018
; @(#) ProductName: PeopleNet
;--------------------------------------------------------------------------------------- 
; full path to configclient.xml file - in classes dir according to Servlet 2.2
;---------------------------------------------------------------------------------------
configfile = C:/Program Files/Meta4/M4WS/default/WEB-INF/classes/properties/configclient.xml    
