/**
 * Snco_Ad_Ic_Knoledge_LevelRecord.java
 * Self generated code for Bussines Object SNCO_AD_IC_KNWLD_LV_TRANSLATOR.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.snco_ad_ic_knwld_lv_translator;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Snco_Ad_Ic_Knoledge_Level.
 * @author Meta4
 */
public 
class Snco_Ad_Ic_Knoledge_LevelRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "SNCO_AD_IC_KNWLD_LV_TRANSLATOR";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "SNCO_AD_IC_KNOLEDGE_LEVEL";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Snco_Ad_Ic_Knoledge_LevelRecord.class.getName());

    /* new persistence member - RecordID */    
    private String m4AutoGeneratedRecordID = null; 
    
    public String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    public void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    private boolean m4AutoGeneratedToDelete = false; 
    
    public boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    public void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item SCO_DT_END */
    private Calendar sco_Dt_End = null;
    public void setsco_Dt_End(Calendar ai_value)
    {
        sco_Dt_End = ai_value;
    }
    public Calendar getsco_Dt_End()
    {
        return sco_Dt_End;
    }

    /* item SCO_MEANING */
    private String sco_Meaning = null;
    public void setsco_Meaning(String ai_value)
    {
        sco_Meaning = ai_value;
    }
    public String getsco_Meaning()
    {
        return sco_Meaning;
    }

    /* item SCO_PERCENT */
    private Double sco_Percent = null;
    public void setsco_Percent(Double ai_value)
    {
        sco_Percent = ai_value;
    }
    public Double getsco_Percent()
    {
        return sco_Percent;
    }

    /* item SCO_DT_START */
    private Calendar sco_Dt_Start = null;
    public void setsco_Dt_Start(Calendar ai_value)
    {
        sco_Dt_Start = ai_value;
    }
    public Calendar getsco_Dt_Start()
    {
        return sco_Dt_Start;
    }

    /* item SCO_ID_LEVEL */
    private String sco_Id_Level = null;
    public void setsco_Id_Level(String ai_value)
    {
        sco_Id_Level = ai_value;
    }
    public String getsco_Id_Level()
    {
        return sco_Id_Level;
    }

    /* item SCO_ID_SCALE */
    private String sco_Id_Scale = null;
    public void setsco_Id_Scale(String ai_value)
    {
        sco_Id_Scale = ai_value;
    }
    public String getsco_Id_Scale()
    {
        return sco_Id_Scale;
    }

    /* item SCO_NM_LEVEL */
    private String sco_Nm_Level = null;
    public void setsco_Nm_Level(String ai_value)
    {
        sco_Nm_Level = ai_value;
    }
    public String getsco_Nm_Level()
    {
        return sco_Nm_Level;
    }

    /* item SCO_NM_SCALE */
    private String sco_Nm_Scale = null;
    public void setsco_Nm_Scale(String ai_value)
    {
        sco_Nm_Scale = ai_value;
    }
    public String getsco_Nm_Scale()
    {
        return sco_Nm_Scale;
    }

    /* item SCO_ID_EXTD_KN */
    private String sco_Id_Extd_Kn = null;
    public void setsco_Id_Extd_Kn(String ai_value)
    {
        sco_Id_Extd_Kn = ai_value;
    }
    public String getsco_Id_Extd_Kn()
    {
        return sco_Id_Extd_Kn;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // SCO_DT_END.
        if (sco_Dt_End != null)
        {
            htItems.put("SCO_DT_END", M4BusinessMethodArg.toString(sco_Dt_End));
        }
        // SCO_MEANING.
        if (sco_Meaning != null)
        {
            htItems.put("SCO_MEANING", M4BusinessMethodArg.toString(sco_Meaning));
        }
        // SCO_PERCENT.
        if (sco_Percent != null)
        {
            htItems.put("SCO_PERCENT", M4BusinessMethodArg.toString(sco_Percent));
        }
        // SCO_DT_START.
        if (sco_Dt_Start != null)
        {
            htItems.put("SCO_DT_START", M4BusinessMethodArg.toString(sco_Dt_Start));
        }
        // SCO_ID_LEVEL.
        if (sco_Id_Level != null)
        {
            htItems.put("SCO_ID_LEVEL", M4BusinessMethodArg.toString(sco_Id_Level));
        }
        // SCO_ID_SCALE.
        if (sco_Id_Scale != null)
        {
            htItems.put("SCO_ID_SCALE", M4BusinessMethodArg.toString(sco_Id_Scale));
        }
        // SCO_NM_LEVEL.
        if (sco_Nm_Level != null)
        {
            htItems.put("SCO_NM_LEVEL", M4BusinessMethodArg.toString(sco_Nm_Level));
        }
        // SCO_NM_SCALE.
        if (sco_Nm_Scale != null)
        {
            htItems.put("SCO_NM_SCALE", M4BusinessMethodArg.toString(sco_Nm_Scale));
        }
        // SCO_ID_EXTD_KN.
        if (sco_Id_Extd_Kn != null)
        {
            htItems.put("SCO_ID_EXTD_KN", M4BusinessMethodArg.toString(sco_Id_Extd_Kn));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read SCO_DT_END.
        sItemName = "SCO_DT_END";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Dt_End = M4BusinessMethodArg.toCalendar(sItemValue);

        // read SCO_MEANING.
        sItemName = "SCO_MEANING";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Meaning = sItemValue;

        // read SCO_PERCENT.
        sItemName = "SCO_PERCENT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Percent = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read SCO_DT_START.
        sItemName = "SCO_DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read SCO_ID_LEVEL.
        sItemName = "SCO_ID_LEVEL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Level = sItemValue;

        // read SCO_ID_SCALE.
        sItemName = "SCO_ID_SCALE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Scale = sItemValue;

        // read SCO_NM_LEVEL.
        sItemName = "SCO_NM_LEVEL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Nm_Level = sItemValue;

        // read SCO_NM_SCALE.
        sItemName = "SCO_NM_SCALE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Nm_Scale = sItemValue;

        // read SCO_ID_EXTD_KN.
        sItemName = "SCO_ID_EXTD_KN";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Extd_Kn = sItemValue;


    } /* end of method readOperations */


} /* end of class Snco_Ad_Ic_Knoledge_LevelRecord */

