/**
 * Snco_Ad_Ic_Know_Map_ConfigRecord.java
 * Self generated code for Bussines Object SNCO_AD_IC_KNWLD_LV_TRANSLATOR.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.snco_ad_ic_knwld_lv_translator;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Snco_Ad_Ic_Know_Map_Config.
 * @author Meta4
 */
public 
class Snco_Ad_Ic_Know_Map_ConfigRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "SNCO_AD_IC_KNWLD_LV_TRANSLATOR";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "SNCO_AD_IC_KNOW_MAP_CONFIG";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Snco_Ad_Ic_Know_Map_ConfigRecord.class.getName());

    /* new persistence member - RecordID */    
    private String m4AutoGeneratedRecordID = null; 
    
    public String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    public void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    private boolean m4AutoGeneratedToDelete = false; 
    
    public boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    public void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item DT_END */
    private Calendar dt_End = null;
    public void setdt_End(Calendar ai_value)
    {
        dt_End = ai_value;
    }
    public Calendar getdt_End()
    {
        return dt_End;
    }

    /* item DT_START */
    private Calendar dt_Start = null;
    public void setdt_Start(Calendar ai_value)
    {
        dt_Start = ai_value;
    }
    public Calendar getdt_Start()
    {
        return dt_Start;
    }

    /* item SCO_ORDINAL */
    private Double sco_Ordinal = null;
    public void setsco_Ordinal(Double ai_value)
    {
        sco_Ordinal = ai_value;
    }
    public Double getsco_Ordinal()
    {
        return sco_Ordinal;
    }

    /* item SCO_ID_EXTD_KN */
    private String sco_Id_Extd_Kn = null;
    public void setsco_Id_Extd_Kn(String ai_value)
    {
        sco_Id_Extd_Kn = ai_value;
    }
    public String getsco_Id_Extd_Kn()
    {
        return sco_Id_Extd_Kn;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // DT_END.
        if (dt_End != null)
        {
            htItems.put("DT_END", M4BusinessMethodArg.toString(dt_End));
        }
        // DT_START.
        if (dt_Start != null)
        {
            htItems.put("DT_START", M4BusinessMethodArg.toString(dt_Start));
        }
        // SCO_ORDINAL.
        if (sco_Ordinal != null)
        {
            htItems.put("SCO_ORDINAL", M4BusinessMethodArg.toString(sco_Ordinal));
        }
        // SCO_ID_EXTD_KN.
        if (sco_Id_Extd_Kn != null)
        {
            htItems.put("SCO_ID_EXTD_KN", M4BusinessMethodArg.toString(sco_Id_Extd_Kn));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read DT_END.
        sItemName = "DT_END";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_End = M4BusinessMethodArg.toCalendar(sItemValue);

        // read DT_START.
        sItemName = "DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read SCO_ORDINAL.
        sItemName = "SCO_ORDINAL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Ordinal = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read SCO_ID_EXTD_KN.
        sItemName = "SCO_ID_EXTD_KN";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Extd_Kn = sItemValue;


    } /* end of method readOperations */


} /* end of class Snco_Ad_Ic_Know_Map_ConfigRecord */

