/**
 * Snco_Ad_Ic_Whole_TranslationRecord.java
 * Self generated code for Bussines Object SNCO_AD_IC_KNWLD_LV_TRANSLATOR.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.snco_ad_ic_knwld_lv_translator;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Snco_Ad_Ic_Whole_Translation.
 * @author Meta4
 */
public 
class Snco_Ad_Ic_Whole_TranslationRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "SNCO_AD_IC_KNWLD_LV_TRANSLATOR";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "SNCO_AD_IC_WHOLE_TRANSLATION";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Snco_Ad_Ic_Whole_TranslationRecord.class.getName());

    /* new persistence member - RecordID */    
    private String m4AutoGeneratedRecordID = null; 
    
    public String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    public void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    private boolean m4AutoGeneratedToDelete = false; 
    
    public boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    public void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item AD_IC_ID_LEVEL */
    private String ad_Ic_Id_Level = null;
    public void setad_Ic_Id_Level(String ai_value)
    {
        ad_Ic_Id_Level = ai_value;
    }
    public String getad_Ic_Id_Level()
    {
        return ad_Ic_Id_Level;
    }

    /* item AD_IC_ID_EXTD_KN */
    private String ad_Ic_Id_Extd_Kn = null;
    public void setad_Ic_Id_Extd_Kn(String ai_value)
    {
        ad_Ic_Id_Extd_Kn = ai_value;
    }
    public String getad_Ic_Id_Extd_Kn()
    {
        return ad_Ic_Id_Extd_Kn;
    }

    /* item AD_IC_TRANSLATION_LEVEL_1 */
    private String ad_Ic_Translation_Level_1 = null;
    public void setad_Ic_Translation_Level_1(String ai_value)
    {
        ad_Ic_Translation_Level_1 = ai_value;
    }
    public String getad_Ic_Translation_Level_1()
    {
        return ad_Ic_Translation_Level_1;
    }

    /* item AD_IC_TRANSLATION_LEVEL_2 */
    private String ad_Ic_Translation_Level_2 = null;
    public void setad_Ic_Translation_Level_2(String ai_value)
    {
        ad_Ic_Translation_Level_2 = ai_value;
    }
    public String getad_Ic_Translation_Level_2()
    {
        return ad_Ic_Translation_Level_2;
    }

    /* item AD_IC_TRANSLATION_LEVEL_3 */
    private String ad_Ic_Translation_Level_3 = null;
    public void setad_Ic_Translation_Level_3(String ai_value)
    {
        ad_Ic_Translation_Level_3 = ai_value;
    }
    public String getad_Ic_Translation_Level_3()
    {
        return ad_Ic_Translation_Level_3;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // AD_IC_ID_LEVEL.
        if (ad_Ic_Id_Level != null)
        {
            htItems.put("AD_IC_ID_LEVEL", M4BusinessMethodArg.toString(ad_Ic_Id_Level));
        }
        // AD_IC_ID_EXTD_KN.
        if (ad_Ic_Id_Extd_Kn != null)
        {
            htItems.put("AD_IC_ID_EXTD_KN", M4BusinessMethodArg.toString(ad_Ic_Id_Extd_Kn));
        }
        // AD_IC_TRANSLATION_LEVEL_1.
        if (ad_Ic_Translation_Level_1 != null)
        {
            htItems.put("AD_IC_TRANSLATION_LEVEL_1", M4BusinessMethodArg.toString(ad_Ic_Translation_Level_1));
        }
        // AD_IC_TRANSLATION_LEVEL_2.
        if (ad_Ic_Translation_Level_2 != null)
        {
            htItems.put("AD_IC_TRANSLATION_LEVEL_2", M4BusinessMethodArg.toString(ad_Ic_Translation_Level_2));
        }
        // AD_IC_TRANSLATION_LEVEL_3.
        if (ad_Ic_Translation_Level_3 != null)
        {
            htItems.put("AD_IC_TRANSLATION_LEVEL_3", M4BusinessMethodArg.toString(ad_Ic_Translation_Level_3));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read AD_IC_ID_LEVEL.
        sItemName = "AD_IC_ID_LEVEL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        ad_Ic_Id_Level = sItemValue;

        // read AD_IC_ID_EXTD_KN.
        sItemName = "AD_IC_ID_EXTD_KN";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        ad_Ic_Id_Extd_Kn = sItemValue;

        // read AD_IC_TRANSLATION_LEVEL_1.
        sItemName = "AD_IC_TRANSLATION_LEVEL_1";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        ad_Ic_Translation_Level_1 = sItemValue;

        // read AD_IC_TRANSLATION_LEVEL_2.
        sItemName = "AD_IC_TRANSLATION_LEVEL_2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        ad_Ic_Translation_Level_2 = sItemValue;

        // read AD_IC_TRANSLATION_LEVEL_3.
        sItemName = "AD_IC_TRANSLATION_LEVEL_3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        ad_Ic_Translation_Level_3 = sItemValue;


    } /* end of method readOperations */


} /* end of class Snco_Ad_Ic_Whole_TranslationRecord */

