/* =========================================================
	@(#) FileVersion: 817.000.003
	@(#) FileDescription: double_factor_setup_fr.js
	@(#) CompanyName: Meta4 Spain, S.A.
	@(#) LegalCopyright: (c) 2019
	@(#) ProductName: PeopleNet
========================================================= */

// Autogenerated file. Do not touch.

var _secret_key_not_obtained = "La clé pour la configuration du double facteur d'authentification n'a pas pu être obtenue pour l'utilisateur d'application.";
var _token_connection_session = "Une connexion n'a pas pu être réalisée pour obtenir la clé pour la configuration du double facteur d'authentification.";
var _token_expired = "Le lien permettant de configurer le double facteur d'authentification a expiré. Contactez votre administrateur pour obtenir un nouveau lien.";
var _token_missing_or_invalid = "Le lien permettant de configurer le double facteur d'authentification n'est pas valide. Contactez votre administrateur pour obtenir un nouveau lien.";
var _user_empty = "L'utilisateur d'application pour la vérification de code n'a pas pu être déterminé.";
var _verify_code_empty = "Le code de vérification est vide";
var _verify_code_unverifiable = "Le code de vérification est incorrecte.";
