/* =========================================================
	@(#) FileVersion: 816.000.001
	@(#) FileDescription: double_factor_setup_en.js
	@(#) CompanyName: Meta4 Spain, S.A.
	@(#) LegalCopyright: (c) 2018
	@(#) ProductName: PeopleNet
========================================================= */

// Autogenerated file. Do not touch.

var _secret_key_not_obtained = "Unable to obtain the key for configuring the two-factor authentication for the application user.";
var _token_connection_session = "Unable to establish a connection in order to obtain the key for configuring the two-factor authentication.";
var _token_expired = "The link to configure the two-factor authentication has expired. To obtain a new link, please contact your administrator.";
var _token_missing_or_invalid = "The link to configure the two-factor authentication is invalid. To obtain a new link, please contact your administrator.";
var _user_empty = "Unable to determine the application user whose code is being verified.";
var _verify_code_empty = "The verification code is empty.";
var _verify_code_unverifiable = "The verification code is incorrect.";
