/* =========================================================
	@(#) FileVersion: 818.005.021
	@(#) FileDescription: http_error_page_en.js
	@(#) CompanyName: Meta4 Spain, S.A.
	@(#) LegalCopyright: (c) 2022
	@(#) ProductName: PeopleNet
========================================================= */

// Autogenerated file. Do not touch.

var back = "Back";
var error = "Error";
var page_not_found = "The page you requested was not found.";
var title = "Oops!";
