/* =========================================================
	@(#) FileVersion: 818.005.021
	@(#) FileDescription: http_error_page_es.js
	@(#) CompanyName: Meta4 Spain, S.A.
	@(#) LegalCopyright: (c) 2022
	@(#) ProductName: PeopleNet
========================================================= */

// Autogenerated file. Do not touch.

var back = "Volver";
var error = "Error";
var page_not_found = "La página solicitada no se encuentra.";
var title = "¡Uy!";
