/* =========================================================
	@(#) FileVersion: 820.002.047
	@(#) FileDescription: tc_login_de.js
	@(#) CompanyName: Cegid Spain, S.A.U.
	@(#) LegalCopyright: (c) 2023
	@(#) ProductName: Peoplenet
========================================================= */

// Autogenerated file. Do not touch.

var ChangePwd_Error_ChangePasswordContainsNameTokens = "The new password includes part of the user name. You must use a password that does not contain parts of the user name.";
var ChangePwd_Error_ChangePasswordNoPermission = "Sie sind nicht berechtigt, das Kennwort zu ändern. Wenden Sie sich an Ihren Administrator.";
var ChangePwd_Error_ChangePasswordNotStrongEnough = "Das neue Kennwort ist gemäß den festgelegten Kriterien nicht sicher genug. Geben Sie ein neues Kennwort ein, dass den festgelegten Kriterien entspricht.";
var ChangePwd_Error_ChangePasswordRecentlyUsed = "Das neue Kennwort wurde vor kurzem schon einmal verwendet. Geben Sie ein neues Kennwort ein, dass nicht bereits vor kurzem verwendet wurde.";
var ChangePwd_Error_ExceptionGettingUserSession = "Bei der Wiederherstellung der Benutzersitzung ist ein Fehler aufgetreten. Vor der Aktualisierung Ihres Kennworts müssen Sie eine Verbindung herstellen.";
var ChangePwd_Error_PasswordEqualUserId = "Das neue Kennwort stimmt mit Ihrem Benutzernamen überein. Geben Sie ein Kennwort ein, das nicht mit dem Benutzernamen übereinstimmt.";
var ChangePwd_InvalidLink = "Ihr Link zur Festlegung des Kennworts für Meta4 PeopleNet ist ungültig. Gehen Sie zurück zur Verbindungsseite, um den Prozess zur Kennwortwiederherstellung erneut duchzuführen.";
var _change_pwd_Error_CurrentPasswordIsNull = "Sie müssen das aktuelle Kennwort eingeben.";
var _change_pwd_Error_NewPasswordDoesNotMatchRetypePassword = "Das erneut eingegebene Kennwort ist nicht korrekt.";
var _change_pwd_Error_NewPasswordIsNull = "Sie müssen das neue Kennwort eingeben.";
var _change_pwd_Error_NewPasswordMatchCurrentPassword = "Das neue Kennwort muss von dem alten verschieden sein.";
var _change_pwd_Error_RetypePasswordIsNull = "Sie müssen das neue Kennwort erneut eingeben.";
var login_AmbiDataM = "Es wurden mehr als eine Person gefunden, die mit den angegebenen Daten übereinstimmen. Damit diese Identifizierung eindeutig ist, müssen Sie den Administrator informieren.";
var login_ChangePDo = "Die Kennwortänderung wurde korrekt durchgeführt";
var login_ChangePDoErr = "Bei der Kennwortänderung ist ein Fehler aufgetreten. Wenden Sie sich an Ihren Administrator.";
var login_ErrorConnection = "Das Kennwort kann nicht wiederhergestellt werden, weil wegen Ihrer Webserver-Einstellungen kein Datenzugriff besteht. Wenden Sie sich an Ihren Administrator.";
var login_ErrorConnectionSession = "Es konnte keine Verbindungssitzung für diesen Vorgang hergestellt werden. Wenden Sie sich an Ihren Administrator.";
var login_ExpiredLink = "Ihr Link zur Wiederherstellung des Kennworts für Meta4 PeopleNet ist abgelaufen. Auf der Verbindungsseite können Sie den Vorgang zur Wiederherstellung des Kennworts wiederholen.";
var login_NewIPass = "Sie müssen das neue Kennwort eingeben.";
var login_NewIRPass = "Sie müssen das neue Kennwort erneut eingeben.";
var login_NewIRPassErr = "Die erneute Eingabe des neuen Kennworts ist ungültig.";
var login_NoDataIdU = "Es müssen noch Daten eingegeben werden. Geben Sie alle angeforderten Daten ein.";
var login_NoDataM = "Die Anfrage konnte nicht verarbeitet werden: Die eingegebenen Daten sind nicht korrekt. Überprüfen Sie die Schreibweise der angeforderten Daten.";
var login_User = "Das System hat eine eMail mit den erforderlichen Daten für den Zugriff auf Ihr Konto gesendet.";
var login_UserEmailBased = "The system will send you an e-mail with the information you need to access your account. If you do not receive the message, try using \"Recover your password without entering the e-mail\".";
var login_UserHHRR = "Es wurde eine eMail an die Personalabteilung gesendet, um den Zugriff auf Ihr Konto zu ermöglichen.";
var login_WithOutCodeC = "Geben Sie ID Kunde ein.";
var login_currentConnection = "Current Connection";
var login_lastConnection = "Latest Connection";
