/* =========================================================
	@(#) FileVersion: 820.002.044
	@(#) FileDescription: tc_login_fr.js
	@(#) CompanyName: Cegid Spain, S.A.U.
	@(#) LegalCopyright: (c) 2023
	@(#) ProductName: Peoplenet
========================================================= */

// Autogenerated file. Do not touch.

var ChangePwd_Error_ChangePasswordContainsNameTokens = "Le nouveau mot de passe contient une partie du nom de l'utilisateur. Veuillez définir un mot de passe ne contenant aucune partie du nom de l'utilisateur.";
var ChangePwd_Error_ChangePasswordNoPermission = "Vous ne disposez pas des droits nécessaires pour modifier le mot de passe. Veuillez contacter votre administrateur.";
var ChangePwd_Error_ChangePasswordNotStrongEnough = "Votre nouveau mot de passe n'est pas assez sûr pour les critères de sécurité appliqués. Merci de saisir un autre mot de passe qui réponde à ces critères.";
var ChangePwd_Error_ChangePasswordRecentlyUsed = "Vous avez déjà utilisé ce mot de passe récemment. Veuillez saisir un mot de passe différent de ceux que vous avez utilisés dernièrement.";
var ChangePwd_Error_ExceptionGettingUserSession = "Erreur lors de la récupération de la session de l'utilisateur. Veuillez vous connecter avant de mettre à jour votre mot de passe.";
var ChangePwd_Error_PasswordEqualUserId = "Votre nouveau mot de passe est identique à votre nom d'utilisateur. Merci d'indiquer un mot de passe différent.";
var ChangePwd_InvalidLink = "Le lien permettant d'établir votre mot de passe n'est pas valide. Veuillez retourner à la page de connexion et recommencer le processus de récupération de votre mot de passe.";
var _change_pwd_Error_CurrentPasswordIsNull = "Veuillez saisir votre mot de passe actuel.";
var _change_pwd_Error_NewPasswordDoesNotMatchRetypePassword = "La confirmation de votre mot de passe est incorrecte.";
var _change_pwd_Error_NewPasswordIsNull = "Veuillez saisir votre nouveau mot de passe.";
var _change_pwd_Error_NewPasswordMatchCurrentPassword = "Le nouveau mot de passe doit être différent de l'ancien mot de passe.";
var _change_pwd_Error_RetypePasswordIsNull = "Veuillez confirmer votre nouveau mot de passe en le saisissant de nouveau.";
var login_AmbiDataM = "Plusieurs personnes correspondent aux informations indiquées. Veuillez informer votre administrateur afin de réaliser une identification unique.";
var login_ChangePDo = "Votre mot de passe a été modifié.";
var login_ChangePDoErr = "Une erreur s'est produite lors du changement de mot de passe. Merci de consulter votre administrateur.";
var login_ErrorConnection = "Il n'est pas possible de récupérer vos anciennes données d'identification en raison de la configuration de votre serveur Web. Merci de consulter votre administrateur.";
var login_ErrorConnectionSession = "Il n'a pas été; possible d'établir une session de connexion pour réaliser cette action. Merci de consulter votre administrateur.";
var login_ExpiredLink = "Le lien permettant de récupérer votre mot de passe a expiré. Veuillez revenir à la page de connexion et recommencer le processus de récupération de votre mot de passe.";
var login_NewIPass = "Vous devez indiquer votre nouveau mot de passe.";
var login_NewIRPass = "Vous devez confirmer votre nouveau mot de passe en le saisissant de nouveau.";
var login_NewIRPassErr = "La confirmation de votre nouveau mot de passe est inexacte.";
var login_NoDataIdU = "Informations manquantes. Vous devez indiquer toutes les informations demandées.";
var login_NoDataM = "Votre demande n'a pas pu être transmise : les informations indiquées sont incorrectes. Veuillez vérifier que vous avez correctement indiqué toutes les informations demandées.";
var login_User = "Un courriel vient de vous être envoyé. Il contient les informations nécessaires pour que vous puissiez accéder à nouveau à votre compte.";
var login_UserEmailBased = "Le système vous enverra un courriel avec les informations nécessaires pour accéder à votre compte. Si vous ne recevez pas ce courriel, essayez avec le mode 'Récupération du mot de passe sans indiquer d'adresse électronique'.";
var login_UserHHRR = "Un courriel vient d'être envoyé à votre département RH afin de répondre à votre problème d'accès à votre compte.";
var login_WithOutCodeC = "Veuillez saisir votre code client :";
var login_currentConnection = "Connexion actuelle";
var login_lastConnection = "Connexion la plus récente";
