//Original code file: functions_contact.raw.js
//Use the above mentioned file for modifications or debugging.

var m4Contact={}
m4Contact.table=function(){var l_sLinkEngineCont='/servlet/CheckSecurity/JSP/sse_g0/ssco_mn_contact.jsp';var l_aLabels=new Array;var l_aRow=new Array;var l_oTableCon=null;function _init(){var aParams=new Array;var objResp=null;document.title=$('sHeadTitle').get('text');aParams[0]=['Action','Load'];aParams[1]=['Column','Name'];aParams[2]=['Order','ASC'];meta4Ajax.ajax.sendSyncJSON(l_sLinkEngineCont,aParams);objResp=meta4Ajax.ajax.getResponseJSON();if(objResp){for(var item in objResp){if(typeof(objResp[item])=='string'){l_aLabels[item.substring(1)]=objResp[item];}}
var options={maxRows:15,orderAsc:l_aLabels['OrderAsc'],orderDesc:l_aLabels['OrderDesc'],orderNo:l_aLabels['NoOrder']};l_oTableCon=new meta4Table.Table('tblContact',options);l_oTableCon.setAction(l_aLabels['LoadingCon']);_endSortMe(objResp);}}
function _sortMe(me){var aParams=new Array;var sNameCol=l_aLabels['Ordering']+' '+$(me.id).get('text')+'...';aParams[0]=['Action','Sort'];aParams[1]=['Column',me.m4column];aParams[2]=['Order',me.m4sort];l_oTableCon.setAction(sNameCol);meta4Ajax.ajax.sendAsyncJSON(l_sLinkEngineCont,aParams,_endSortMe);}
function _endSortMe(objResult){var saTable=new Array;var sFormatCol0="<div><a href='#'><span title='sLiteral' idHR='sID' onmouseover='m4Contact.Functions.showPhoto(this);' onmouseout='meta4Photo.Photo.hidePhoto();' onclick='m4Contact.Functions.show(this)'>sName</span></a></div>";var sFormatCol1="<div><a href='/servlet/CheckSecurity/JSP/sse_g0/ssco_g0_org_chart.jsp?IdWUnit=sID'><span title='sLiteral'>sName</span></a></div>";var sFormatCol2="<div><span class='spanPhone'>sPhone</span><img class='imgPhone' title='sLiteral' src='sImg'/></div>";var sFormatCol3="<a href='mailto:sEmail'><span title='sLiteral'>sEmail</span></a>";var sFormatCol4="<span>sName</span>";var sFormatCol5="<img idHR='sID' class='m4tableImg' src='/iconos/lu_del_con_nor_24.png' title='sLiteral' onclick='m4Contact.table.deleteContact(event);'/>";objResult.saContact.each(function(item,index){var sCol0='';var sCol1='';var sCol2='';var sCol3='';var sCol4='';var sCol5='';sCol0=sFormatCol0.replace(/sID/g,item[0][0]);sCol0=sCol0.replace(/sLiteral/g,item[0][1]);sCol0=sCol0.replace(/sName/g,item[0][2]);sCol1=sFormatCol1.replace(/sID/g,item[1][0]);sCol1=sCol1.replace(/sLiteral/g,item[1][1]);sCol1=sCol1.replace(/sName/g,item[1][2]);sCol2='';if(item[2][0]){sCol2=sFormatCol2.replace(/sPhone/g,item[2][0]);sCol2=sCol2.replace(/sLiteral/g,item[2][1]);sCol2=sCol2.replace(/sImg/g,item[2][2]);}
sCol3='';if(item[3][0]){sCol3=sFormatCol3.replace(/sEmail/g,item[3][0]);sCol3=sCol3.replace(/sLiteral/g,item[3][1]);}
sCol4=sFormatCol4.replace(/sName/g,item[4][0]);sCol5=sFormatCol5.replace(/sID/g,item[5][0]);sCol5=sCol5.replace(/sLiteral/g,item[5][1]);saTable[saTable.length]=[sCol0,sCol1,sCol2,sCol3,sCol4,sCol5];});l_oTableCon.load(saTable);}
return{init:function(){_init();},sortMe:function(me){_sortMe(me);},deleteContact:function(ev){var objResult=meta4Table.functions.DeleteContact(ev);if(objResult.sResult=='0'){l_oTableCon.deleteRow(objResult.sIndexRow);l_oTableCon.setTempCaption(l_aLabels['ContactOK']);}else{l_oTableCon.setTempCaption(l_aLabels['ContactKO']);}}};}();m4Contact.Functions=function(){return{showPhoto:function(me){meta4Photo.Photo.showPhoto(me.getAttribute('idHR'));},show:function(me){meta4InfPers.Info.show(me.getAttribute('idHR'));}}}();window.addEvent('domready',function(){meta4Photo.Photo.init(document.body.getAttribute('m4path'),document.body.getAttribute('m4pathURI'),$('imgPhoto'));m4Contact.table.init();meta4InfPers.Info.init(null);});