//Original code file: meta4list.raw.js
//Use the above mentioned file for modifications or debugging.

var M4List=new Class(function(){function l(b,d,c,a,e){return(new Element("li",{id:e,html:a,styles:{"font-size":b.getStyle("font-size"),color:c.color}})).inject(d)}function z(b,d,c){b&&(b.addClass("hover"),b.set("styles",{"background-color":c.color,color:c.bgcolor}),d.set(n,b.get(n)))}function A(b,d,c){b&&(b.removeClass("hover"),b.set("styles",{"background-color":c.bgcolor,color:c.color}),b.get(n)===d.get(n)&&d.set(n,""))}function B(b,d,c,a){var e;if(b){d.set("value",b.get("text"));for(e=0;e<a.saResultItems.length;e++)d.set(r+
a.saResultItems[e],b.get(r+a.saResultItems[e]));t(d,a.sEventAttributesChanged);u(c);d.removeClass("scoDynamicListFilter");a.sFilterValue=b.get("text")}}function v(b,d,c,a){var e,f="";if(a.sFilterValue!==b.get("value")){if(""===b.get("value"))k=$clear(k),d.set("html",""),l(b,d,a,a.labelHelp),m(d,b);else{c[a.iIndexMainFilter][1]=b.get("value");a.hasOwnProperty("oAppStart")&&(c[a.iIndexAppStart][1]=a.oAppStart.get("value"));a.hasOwnProperty("oAppEnd")&&(c[a.iIndexAppEnd][1]=a.oAppEnd.get("value"));if(!a.bAllSecFilterElementsStatic){for(e=
0;e<a.oaSecondaryFilterElements.length;e++)0!==e&&(f+=","),f="object"===typeof a.oaSecondaryFilterElements[e]?f+a.oaSecondaryFilterElements[e].getAttribute(a.saSecondaryFilterAttributes[e]):f+a.oaSecondaryFilterElements[e];c[a.iIndexSecFilterElements][1]=f}k?k=$clear(k):(d.set("html",""),l(b,d,a,a.labelLoading),m(d,b));k=function(){meta4Ajax.ajax.sendAsyncJSON(C,c,a.processResult)}.delay(F)}a.sFilterValue=b.get("value")}else a.initValue&&(meta4Ajax.ajax.sendSyncJSON(C,c),D(b,d,a,meta4Ajax.ajax.getResponseJSON()))}
function D(b,d,c,a){var e,f,g,p,s=/[%,_]/,q=b.get("FilterValue").toLowerCase(),w=q.match(s);k=$clear(k);if(a)if(d.set("html",""),0===a.result.length)l(b,d,c,c.labelNoMatch);else{for(e=0;e<a.result.length;e++){p=a.result[e][c.saResultItems[0]];g=l(b,d,c,p,d.id+".li"+e);p=g.get("text");w&&(q=q.replace(/^[%_]*/,""),q=q.replace(/[%_]*$/,""),w=q.match(s));w||(f=p.toLowerCase().indexOf(q),p=p.substr(0,f)+'<span style="font-weight:bold;">'+p.substr(f,q.length)+"</span>"+p.substr(f+q.length),g.set("html",
p));g.set(n,e);for(f=0;f<c.saResultItems.length;f++)g.set(r+c.saResultItems[f],a.result[e][c.saResultItems[f]]);g.set("_m4valid",!0);g.addEvent("mouseover",function(a){a=$(a.target.id)||$($(a.target).getParent().id);z(a,d,c)});g.addEvent("mouseout",function(a){a=$(a.target.id)||$(a.target.getParent().id);A(a,d,c)});g.addEvent("mousedown",function(a){a=$(a.target.id)||$(a.target.getParent().id);B(a,b,d,c)})}a.limited?(e=c.saParametersNext[0][1],c.saParametersNext[4][1]=a.lTotalRec,c.saParametersNext[6][1]=
a.range,g="<div id='#PREX#.dvMoreList' style='height:16px; clear:both; padding:2px 2px'><span id='#PREX#.spnCount' style='margin:2px 0px 0px; float:left'>#COUNT#</span><div style='float:right;margin-top:2px;'><img id='#PREX#.btnFirst' src='/iconos/lu_dis_first_24.png' style='cursor:pointer;height:16px;width:16px'/><img id='#PREX#.btnPrev' src='/iconos/lu_dis_rew_24.png' style='cursor:pointer;height:16px;width:16px;margin-left:3px;'/><img id='#PREX#.btnNext' src='/iconos/lu_nor_for_24.png' style='cursor:pointer;height:16px;width:16px;margin-left:3px;'/><img id='#PREX#.btnLast' src='/iconos/lu_nor_last_24.png' style='cursor:pointer;height:16px;width:16px;margin-left:3px;'/></div></div>".replace(/#PREX#/g,
e),g=l(b,d,c,g.replace("#COUNT#","1.."+(a.range[1]+1)+" ("+a.lTotalRec+")")),g.setStyles({display:"block",cursor:"default","text-align":"center","background-color":"#f5f5f5",color:"#a9a9a9"}),g.addEvent("mousedown",function(a){a.preventDefault();a.stopPropagation()}),g.addEvent("mouseover",function(){b.set("m4listnav","1")}),g.addEvent("mouseout",function(){b.set("m4listnav","")}),a=$(e+".btnFirst"),g=$(e+".btnPrev"),s=$(e+".btnNext"),e=$(e+".btnLast"),a.addEvents({click:function(a){a.preventDefault();
a.stopPropagation();this.get("disabled")||(c.saParametersNext[5][1]=-2,meta4Ajax.ajax.sendAsyncJSON(sUrlListNext,c.saParametersNext,c.processResultNext))},mouseover:function(){this.get("disabled")||this.set("src","/iconos/lu_hot_first_24.png")},mouseout:function(){this.get("disabled")||this.set("src","/iconos/lu_nor_first_24.png")}}),g.addEvents({click:function(a){a.preventDefault();a.stopPropagation();this.get("disabled")||(c.saParametersNext[5][1]=-1,meta4Ajax.ajax.sendAsyncJSON(sUrlListNext,c.saParametersNext,
c.processResultNext))},mouseover:function(){this.get("disabled")||this.set("src","/iconos/lu_hot_rew_24.png")},mouseout:function(){this.get("disabled")||this.set("src","/iconos/lu_nor_rew_24.png")}}),s.addEvents({click:function(a){a.preventDefault();a.stopPropagation();this.get("disabled")||(c.saParametersNext[5][1]=1,meta4Ajax.ajax.sendAsyncJSON(sUrlListNext,c.saParametersNext,c.processResultNext))},mouseover:function(){this.get("disabled")||this.set("src","/iconos/lu_hot_for_24.png")},mouseout:function(){this.get("disabled")||
this.set("src","/iconos/lu_nor_for_24.png")}}),e.addEvents({click:function(a){a.preventDefault();a.stopPropagation();this.get("disabled")||(c.saParametersNext[5][1]=2,meta4Ajax.ajax.sendAsyncJSON(sUrlListNext,c.saParametersNext,c.processResultNext))},mouseover:function(){this.get("disabled")||this.set("src","/iconos/lu_hot_last_24.png")},mouseout:function(){this.get("disabled")||this.set("src","/iconos/lu_nor_last_24.png")}}),a.set("disabled",!0),a.setStyle("cursor",""),g.set("disabled",!0),g.setStyle("cursor",
""),s.set("disabled",!1),e.set("disabled",!1)):(c.saParametersNext[4][1]=0,c.saParametersNext[5][1]=0,c.saParametersNext[6][1].empty());d.set(n,"")}m(d,b)}function x(b){return"block"===b.getStyle("display")}function m(b,d){var c=$(document.body),a=d.getPosition(),e=d.getSize(),f;x(b)||(b.setPosition({x:a.x,y:a.y+e.y}),b.set("styles",{display:"block",width:e.x}),a=b.getPosition(),e=b.getSize(),f=c.getSize(),f.y<a.y+e.y&&c.set("styles",{height:a.y+e.y}));window.fireEvent("resize")}function u(b){x(b)&&
(b.setStyle("display","none"),window.fireEvent("resize"))}function t(b,d){b.fireEvent(y);d&&d!==y&&b.fireEvent(d)}function E(b,d){var c;d.bLoadInterrupted=!0;d.sFilterValue=void 0;for(c=0;c<d.saResultItems.length;c++)b.set(r+d.saResultItems[c],"");b.addClass("scoDynamicListFilter");t(b,d.sEventAttributesChanged)}var k,F=300,y="m4parentlistchanged",r="m4",n="_m4listindex",C="/servlet/CheckSecurity/JSP/sse_generico/sgco_list.jsp";sUrlListNext="/servlet/CheckSecurity/JSP/sse_generico/sgco_list_next.jsp";
return{initialize:function(b){var d,c,a={sFilterValue:void 0,initValue:b.initValue,iIndexMainFilter:void 0,saResultItems:void 0,oaSecondaryFilterElements:void 0,saSecondaryFilterAttributes:[],iIndexSecFilterElements:void 0,bAllSecFilterElementsStatic:!0,color:void 0,bgcolor:void 0,sEventAttributesChanged:b.eventAttributesChanged,labelHelp:b.labelHelp,labelLoading:b.labelLoading,labelAndMore:b.labelAndMore,labelNoMatch:b.labelNoMatch,saParametersNext:void 0,bLoadInterrupted:!1,processResult:function(b){D(f,
e,a,b)},processResultNext:function(b){var c=f,d=e,g=a;if(b){var j=void 0,h=0,k=0,k=0,l="",j="",m=g.saParametersNext[0][1];reWildcard=/[%,_]/;sAuxFilter=c.get("FilterValue").toLowerCase();bContainsWildcard=sAuxFilter.match(reWildcard);g.saParametersNext[6][1]=b.range;for(h=0;h<d.getChildren().length-1;h++)if(j=d.getChildren()[h],0>=-b.result.length+h+1){j.setStyle("display","block");d.getChildren()[h].set(n,b.range[0]+1+h);for(k=0;k<g.saResultItems.length;k++)j.set(r+g.saResultItems[k],b.result[h][g.saResultItems[k]]);
l=b.result[h][g.saResultItems[0]];bContainsWildcard&&(sAuxFilter=sAuxFilter.replace(/^[%_]*/,""),sAuxFilter=sAuxFilter.replace(/[%_]*$/,""),bContainsWildcard=sAuxFilter.match(reWildcard));bContainsWildcard||(k=l.toLowerCase().indexOf(sAuxFilter),l=l.substr(0,k)+'<span style="font-weight:bold;">'+l.substr(k,sAuxFilter.length)+"</span>"+l.substr(k+sAuxFilter.length));j.set("html",l)}else j.set("html",""),j.setStyle("display","none");c=$(m+".btnFirst");d=$(m+".btnPrev");j=$(m+".btnNext");h=$(m+".btnLast");
c.set("disabled",!1);c.setStyle("cursor","pointer");c.set("src","/iconos/lu_nor_first_24.png");d.set("disabled",!1);d.setStyle("cursor","pointer");d.set("src","/iconos/lu_nor_rew_24.png");j.set("disabled",!1);j.setStyle("cursor","pointer");j.set("src","/iconos/lu_nor_for_24.png");h.set("disabled",!1);h.setStyle("cursor","pointer");h.set("src","/iconos/lu_nor_last_24.png");b.bLastRec&&(j.set("disabled",!0),j.setStyle("cursor",""),j.set("src","/iconos/lu_dis_for_24.png"),h.set("disabled",!0),h.setStyle("cursor",
""),h.set("src","/iconos/lu_dis_last_24.png"));b.bFirstRec&&(c.set("disabled",!0),c.setStyle("cursor",""),c.set("src","/iconos/lu_dis_first_24.png"),d.set("disabled",!0),d.setStyle("cursor",""),d.set("src","/iconos/lu_dis_rew_24.png"));j=b.range[0]+1+".."+(b.range[1]+1)+" ("+g.saParametersNext[4][1]+")";$(m+".spnCount").set("text",j)}}},e,f,g;if(window.meta4Ajax)if(window.MooTools){g=[["Meta4Object",b.meta4Object],["NodeQBF",b.nodeQBF],["NodeTR",b.nodeTR],["ListMethod",b.listMethod],["SecondaryTI",
b.secondaryTI],["ListMethodArguments",b.listMethodArguments],["ResultItems",b.resultItems],["MaxRecords",b.maxRecords]];a.saParametersNext=[["Meta4Object",b.meta4Object],["NodeTR",b.nodeTR],["ResultItems",b.resultItems],["MaxRecords",b.maxRecords],["TotalRecords",0],["Direction","0"],["Range",[0,0]]];b.hasOwnProperty("appStart")&&(d=b.appStart,"undefined"===typeof b.appStart?(b.appStart="",d=b.appStart):"string"===typeof b.appStart?$(b.appStart)&&(a.oAppStart=$(b.appStart),a.iIndexAppStart=g.length,
d=void 0):"object"===typeof b.appStart&&(a.oAppStart=$(b.appStart.id),a.iIndexAppStart=g.length,d=void 0),g[g.length]=["AppStart",d]);b.hasOwnProperty("appEnd")&&(d=b.appEnd,"undefined"===typeof b.appEnd?(b.appEnd="",d=b.appEnd):"string"===typeof b.appEnd?$(b.appEnd)&&(a.oAppEnd=$(b.appEnd),a.iIndexAppEnd=g.length,d=void 0):"object"===typeof b.appEnd&&(a.oAppEnd=$(b.appEnd.id),a.iIndexAppEnd=g.length,d=void 0),g[g.length]=["AppEnd",d]);if("string"===typeof b.mainFilterElement)f=$(b.mainFilterElement);
else if("object"===typeof b.mainFilterElement)f=$(b.mainFilterElement.id);else{alert("Error: mainFilterElement should be of type string or object: "+b.mainFilterElement);return}if(f){f.set("FilterValue",f.get("value"));if(b.secondaryFilterElements){a.oaSecondaryFilterElements=b.secondaryFilterElements.split(",");for(c=0;c<a.oaSecondaryFilterElements.length;c++)if(a.oaSecondaryFilterElements[c].match(/[..]/))if(a.bAllSecFilterElementsStatic=!1,d=a.oaSecondaryFilterElements[c].split(".."),a.oaSecondaryFilterElements[c]=
$(d[0]),a.oaSecondaryFilterElements[c])a.saSecondaryFilterAttributes[c]=d[1],a.oaSecondaryFilterElements[c].addEvent(y,function(){E(f,a)});else{alert('Error: element "'+d[0]+'" does not refer to an object!');return}a.iIndexSecFilterElements=g.length;if(a.bAllSecFilterElementsStatic){g[a.iIndexSecFilterElements]=["ListMethodValues",a.oaSecondaryFilterElements[0]];for(c=1;c<a.oaSecondaryFilterElements.length;c++)g[a.iIndexSecFilterElements][1]+=","+a.oaSecondaryFilterElements[c]}else g[a.iIndexSecFilterElements]=
["ListMethodValues",""]}a.color=f.getStyle("color");a.bgcolor=f.getStyle("background-color");a.iIndexMainFilter=g.length;g[a.iIndexMainFilter]=[f.id,f.get("value")];a.saResultItems=b.resultItems.split(",");for(c=0;c<a.saResultItems.length;c++)a.saResultItems[c]=a.saResultItems[c].replace(/^\s+|\s+$/g,""),f.set(r+a.saResultItems[c],"");t(f,a.sEventAttributesChanged);e=new Element("ul",{id:f.id+".ul"});e.addClass("scoDynamicList");e.set("styles",{"background-color":f.getStyle("background-color"),"border-color":f.getStyle("border-color")});
e.inject(f,"after");l(f,e,a,b.labelHelp);a.initValue&&(a.sFilterValue=f.get("value"),v(f,e,g,a),a.initValue=!1);u(e);f.addEvent("keyup",function(){a.sFilterValue!==f.get("value")&&(this.set("FilterValue",this.get("value")),E(f,a),v(f,e,g,a))});f.addEvent("keydown",function(b){var c=!1,d=0,g,j=0,h;this.set("FilterValue",this.get("value"));if(x(e)){if("enter"===b.key){if(g=e.get(n))b=e.getChildren("li"),h=b.length,h>+g&&B(b[+g],f,e,a)}else"down"===b.key?(d=1,c=!0):"up"===b.key&&(d=-1,c=!0);if(c&&0!==
d&&(b=e.getChildren("li"),h=b.length,0<h)){b[h-1].get(n)||(h-=1);if(g=e.get(n))j=+g+d,A(b[+g],e,a);0>j?j=h-1:j>=h&&(j=0);z(b[j],e,a)}}else m(e,f)});f.addEvent("focus",function(){f.select();f.hasClass("scoInvalidValue")&&(f.removeClass("scoInvalidValue"),f.set("value",a.sFilterValue));f.addClass("scoDynamicListFilter");m(e,f);a.bLoadInterrupted&&(a.bLoadInterrupted=!1,v(f,e,g,a))});f.addEvent("click",function(){m(e,f)});f.addEvent("dblclick",function(){m(e,f);f.get("value")?a.sFilterValue="":f.set("value",
"%");this.set("FilterValue",this.get("value"));f.fireEvent("keyup")});f.addEvent("blur",function(b){this.get("m4listnav")?(b.preventDefault(),this.focus()):(k?(k=$clear(k),a.sFilterValue="",e.set("html",""),l(f,e,a,a.labelHelp),a.bLoadInterrupted=!0):f.get(r+a.saResultItems[0])?f.removeClass("scoDynamicListFilter"):(d=e.getChildren("li"),1===d.length&&d[0].get("_m4valid")&&d[0].fireEvent("mousedown",{target:{id:d[0].id,parentNode:{id:d[0].parentNode.id}}})),function(){u(e)}.delay(150))})}else alert("Error: mainFilterElement does not exist in page: "+
b.mainFilterElement)}else alert("Error: Library mootools.js missing!");else alert("Error: Library meta4ajax.js missing!")}}}());