/**
 * Cyc_Filt_DocRecord.java
 * Self generated code for Bussines Object CYC_FILT_DOC.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_filt_doc;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Filt_Doc.
 * @author Meta4
 */
public 
class Cyc_Filt_DocRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_FILT_DOC";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_FILT_DOC";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Filt_DocRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item DT_END */
    public Calendar dt_End = null;
    private void setdt_End(Calendar ai_value)
    {
        dt_End = ai_value;
    }
    private Calendar getdt_End()
    {
        return dt_End;
    }

    /* item DT_START */
    public Calendar dt_Start = null;
    private void setdt_Start(Calendar ai_value)
    {
        dt_Start = ai_value;
    }
    private Calendar getdt_Start()
    {
        return dt_Start;
    }

    /* item CYC_ID_HR */
    public String cyc_Id_Hr = null;
    private void setcyc_Id_Hr(String ai_value)
    {
        cyc_Id_Hr = ai_value;
    }
    private String getcyc_Id_Hr()
    {
        return cyc_Id_Hr;
    }

    /* item EXTENSION */
    public String extension = null;
    private void setextension(String ai_value)
    {
        extension = ai_value;
    }
    private String getextension()
    {
        return extension;
    }

    /* item CYC_N_DOCUMENTO */
    public String cyc_N_Documento = null;
    private void setcyc_N_Documento(String ai_value)
    {
        cyc_N_Documento = ai_value;
    }
    private String getcyc_N_Documento()
    {
        return cyc_N_Documento;
    }

    /* item CYC_DOCUMENTACION */
    public DataHandler cyc_Documentacion = null;
    private void setcyc_Documentacion(DataHandler ai_value)
    {
        cyc_Documentacion = ai_value;
    }
    private DataHandler getcyc_Documentacion()
    {
        return cyc_Documentacion;
    }

    /* item CYC_N_TP_DOCUMENTACION */
    public String cyc_N_Tp_Documentacion = null;
    private void setcyc_N_Tp_Documentacion(String ai_value)
    {
        cyc_N_Tp_Documentacion = ai_value;
    }
    private String getcyc_N_Tp_Documentacion()
    {
        return cyc_N_Tp_Documentacion;
    }

    /* item CYC_ID_TP_DOCUMENTACION */
    public String cyc_Id_Tp_Documentacion = null;
    private void setcyc_Id_Tp_Documentacion(String ai_value)
    {
        cyc_Id_Tp_Documentacion = ai_value;
    }
    private String getcyc_Id_Tp_Documentacion()
    {
        return cyc_Id_Tp_Documentacion;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // DT_END.
        if (dt_End != null)
        {
            htItems.put("DT_END", M4BusinessMethodArg.toString(dt_End));
        }
        // DT_START.
        if (dt_Start != null)
        {
            htItems.put("DT_START", M4BusinessMethodArg.toString(dt_Start));
        }
        // CYC_ID_HR.
        if (cyc_Id_Hr != null)
        {
            htItems.put("CYC_ID_HR", M4BusinessMethodArg.toString(cyc_Id_Hr));
        }
        // EXTENSION.
        if (extension != null)
        {
            htItems.put("EXTENSION", M4BusinessMethodArg.toString(extension));
        }
        // CYC_N_DOCUMENTO.
        if (cyc_N_Documento != null)
        {
            htItems.put("CYC_N_DOCUMENTO", M4BusinessMethodArg.toString(cyc_N_Documento));
        }
        // CYC_DOCUMENTACION.
        if ( cyc_Documentacion != null )
        {
            htBlobs.put("CYC_DOCUMENTACION", cyc_Documentacion.getName());
        }
        // CYC_N_TP_DOCUMENTACION.
        if (cyc_N_Tp_Documentacion != null)
        {
            htItems.put("CYC_N_TP_DOCUMENTACION", M4BusinessMethodArg.toString(cyc_N_Tp_Documentacion));
        }
        // CYC_ID_TP_DOCUMENTACION.
        if (cyc_Id_Tp_Documentacion != null)
        {
            htItems.put("CYC_ID_TP_DOCUMENTACION", M4BusinessMethodArg.toString(cyc_Id_Tp_Documentacion));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read DT_END.
        sItemName = "DT_END";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_End = M4BusinessMethodArg.toCalendar(sItemValue);

        // read DT_START.
        sItemName = "DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_ID_HR.
        sItemName = "CYC_ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Hr = sItemValue;

        // read EXTENSION.
        sItemName = "EXTENSION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        extension = sItemValue;

        // read CYC_N_DOCUMENTO.
        sItemName = "CYC_N_DOCUMENTO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_N_Documento = sItemValue;

        // read CYC_DOCUMENTACION.
        sItemName = "CYC_DOCUMENTACION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getOptionalAttValue(nItem, "fileindex");
        if (sItemValue != null)
        {
            sItemValue = ai_m4Op.getFileByIndex(Integer.parseInt(sItemValue));
            cyc_Documentacion = new DataHandler(new M4FileDataSource(sItemValue));
        } 
        else // the case where there is no file in the item
        {
            cyc_Documentacion = null;
        }


        // read CYC_DOCUMENTACION.
        sItemName = "CYC_DOCUMENTACION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getOptionalAttValue(nItem, "fileindex");
        if (sItemValue != null)
        {
            sItemValue = ai_m4Op.getFileByIndex(Integer.parseInt(sItemValue));
            cyc_Documentacion = new DataHandler(new M4FileDataSource(sItemValue));
        } 
        else // the case where there is no file in the item
        {
            cyc_Documentacion = null;
        }


        // read CYC_N_TP_DOCUMENTACION.
        sItemName = "CYC_N_TP_DOCUMENTACION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_N_Tp_Documentacion = sItemValue;

        // read CYC_ID_TP_DOCUMENTACION.
        sItemName = "CYC_ID_TP_DOCUMENTACION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Tp_Documentacion = sItemValue;


    } /* end of method readOperations */


} /* end of class Cyc_Filt_DocRecord */

