/**
 * Csp_Calcula_MailRecord.java
 * Self generated code for Bussines Object CSP_MAIL_RA_RIESGOS.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_mail_ra_riesgos;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Calcula_Mail.
 * @author Meta4
 */
public 
class Csp_Calcula_MailRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_MAIL_RA_RIESGOS";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_CALCULA_MAIL";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Calcula_MailRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item STD_EMAIL */
    public String std_Email = null;
    private void setstd_Email(String ai_value)
    {
        std_Email = ai_value;
    }
    private String getstd_Email()
    {
        return std_Email;
    }

    /* item STD_DT_END */
    public Calendar std_Dt_End = null;
    private void setstd_Dt_End(Calendar ai_value)
    {
        std_Dt_End = ai_value;
    }
    private Calendar getstd_Dt_End()
    {
        return std_Dt_End;
    }

    /* item SCO_GB_NAME */
    public String sco_Gb_Name = null;
    private void setsco_Gb_Name(String ai_value)
    {
        sco_Gb_Name = ai_value;
    }
    private String getsco_Gb_Name()
    {
        return sco_Gb_Name;
    }

    /* item STD_OR_MAIL */
    public Double std_Or_Mail = null;
    private void setstd_Or_Mail(Double ai_value)
    {
        std_Or_Mail = ai_value;
    }
    private Double getstd_Or_Mail()
    {
        return std_Or_Mail;
    }

    /* item STD_DT_START */
    public Calendar std_Dt_Start = null;
    private void setstd_Dt_Start(Calendar ai_value)
    {
        std_Dt_Start = ai_value;
    }
    private Calendar getstd_Dt_Start()
    {
        return std_Dt_Start;
    }

    /* item STD_ID_PERSON */
    public String std_Id_Person = null;
    private void setstd_Id_Person(String ai_value)
    {
        std_Id_Person = ai_value;
    }
    private String getstd_Id_Person()
    {
        return std_Id_Person;
    }

    /* item STD_ID_LOCATION_TYPE */
    public String std_Id_Location_Type = null;
    private void setstd_Id_Location_Type(String ai_value)
    {
        std_Id_Location_Type = ai_value;
    }
    private String getstd_Id_Location_Type()
    {
        return std_Id_Location_Type;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // STD_EMAIL.
        if (std_Email != null)
        {
            htItems.put("STD_EMAIL", M4BusinessMethodArg.toString(std_Email));
        }
        // STD_DT_END.
        if (std_Dt_End != null)
        {
            htItems.put("STD_DT_END", M4BusinessMethodArg.toString(std_Dt_End));
        }
        // SCO_GB_NAME.
        if (sco_Gb_Name != null)
        {
            htItems.put("SCO_GB_NAME", M4BusinessMethodArg.toString(sco_Gb_Name));
        }
        // STD_OR_MAIL.
        if (std_Or_Mail != null)
        {
            htItems.put("STD_OR_MAIL", M4BusinessMethodArg.toString(std_Or_Mail));
        }
        // STD_DT_START.
        if (std_Dt_Start != null)
        {
            htItems.put("STD_DT_START", M4BusinessMethodArg.toString(std_Dt_Start));
        }
        // STD_ID_PERSON.
        if (std_Id_Person != null)
        {
            htItems.put("STD_ID_PERSON", M4BusinessMethodArg.toString(std_Id_Person));
        }
        // STD_ID_LOCATION_TYPE.
        if (std_Id_Location_Type != null)
        {
            htItems.put("STD_ID_LOCATION_TYPE", M4BusinessMethodArg.toString(std_Id_Location_Type));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read STD_EMAIL.
        sItemName = "STD_EMAIL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Email = sItemValue;

        // read STD_DT_END.
        sItemName = "STD_DT_END";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Dt_End = M4BusinessMethodArg.toCalendar(sItemValue);

        // read SCO_GB_NAME.
        sItemName = "SCO_GB_NAME";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Gb_Name = sItemValue;

        // read STD_OR_MAIL.
        sItemName = "STD_OR_MAIL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Or_Mail = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read STD_DT_START.
        sItemName = "STD_DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read STD_ID_PERSON.
        sItemName = "STD_ID_PERSON";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Id_Person = sItemValue;

        // read STD_ID_LOCATION_TYPE.
        sItemName = "STD_ID_LOCATION_TYPE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Id_Location_Type = sItemValue;


    } /* end of method readOperations */


} /* end of class Csp_Calcula_MailRecord */

