/**
 * Cyc_Fb_Param_Entrada_EnviadosRecord.java
 * Self generated code for Bussines Object CYC_BUSCADOR_FEED_ENVIADOS.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_buscador_feed_enviados;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Fb_Param_Entrada_Enviados.
 * @author Meta4
 */
public 
class Cyc_Fb_Param_Entrada_EnviadosRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_BUSCADOR_FEED_ENVIADOS";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_FB_PARAM_ENTRADA_ENVIADOS";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Fb_Param_Entrada_EnviadosRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item ARG_AREA */
    public String arg_Area = null;
    private void setarg_Area(String ai_value)
    {
        arg_Area = ai_value;
    }
    private String getarg_Area()
    {
        return arg_Area;
    }

    /* item ARG_FASE */
    public String arg_Fase = null;
    private void setarg_Fase(String ai_value)
    {
        arg_Fase = ai_value;
    }
    private String getarg_Fase()
    {
        return arg_Fase;
    }

    /* item ARG_PUESTO */
    public String arg_Puesto = null;
    private void setarg_Puesto(String ai_value)
    {
        arg_Puesto = ai_value;
    }
    private String getarg_Puesto()
    {
        return arg_Puesto;
    }

    /* item ARG_UNIDAD */
    public String arg_Unidad = null;
    private void setarg_Unidad(String ai_value)
    {
        arg_Unidad = ai_value;
    }
    private String getarg_Unidad()
    {
        return arg_Unidad;
    }

    /* item ARG_NOMB_APE */
    public String arg_Nomb_Ape = null;
    private void setarg_Nomb_Ape(String ai_value)
    {
        arg_Nomb_Ape = ai_value;
    }
    private String getarg_Nomb_Ape()
    {
        return arg_Nomb_Ape;
    }

    /* item ARG_SERVICIO */
    public String arg_Servicio = null;
    private void setarg_Servicio(String ai_value)
    {
        arg_Servicio = ai_value;
    }
    private String getarg_Servicio()
    {
        return arg_Servicio;
    }

    /* item ARG_SOCIEDAD */
    public String arg_Sociedad = null;
    private void setarg_Sociedad(String ai_value)
    {
        arg_Sociedad = ai_value;
    }
    private String getarg_Sociedad()
    {
        return arg_Sociedad;
    }

    /* item ARG_DIRECCION */
    public String arg_Direccion = null;
    private void setarg_Direccion(String ai_value)
    {
        arg_Direccion = ai_value;
    }
    private String getarg_Direccion()
    {
        return arg_Direccion;
    }

    /* item ARG_GRUPO_NIV */
    public String arg_Grupo_Niv = null;
    private void setarg_Grupo_Niv(String ai_value)
    {
        arg_Grupo_Niv = ai_value;
    }
    private String getarg_Grupo_Niv()
    {
        return arg_Grupo_Niv;
    }

    /* item ARG_FECHA_PRUEBA */
    public String arg_Fecha_Prueba = null;
    private void setarg_Fecha_Prueba(String ai_value)
    {
        arg_Fecha_Prueba = ai_value;
    }
    private String getarg_Fecha_Prueba()
    {
        return arg_Fecha_Prueba;
    }

    /* item ARG_FEC_FIN_PRUEBA */
    public String arg_Fec_Fin_Prueba = null;
    private void setarg_Fec_Fin_Prueba(String ai_value)
    {
        arg_Fec_Fin_Prueba = ai_value;
    }
    private String getarg_Fec_Fin_Prueba()
    {
        return arg_Fec_Fin_Prueba;
    }

    /* item ARG_FEC_REALIZACION */
    public String arg_Fec_Realizacion = null;
    private void setarg_Fec_Realizacion(String ai_value)
    {
        arg_Fec_Realizacion = ai_value;
    }
    private String getarg_Fec_Realizacion()
    {
        return arg_Fec_Realizacion;
    }

    /* item ARG_FEC_FIN_REALIZACION */
    public String arg_Fec_Fin_Realizacion = null;
    private void setarg_Fec_Fin_Realizacion(String ai_value)
    {
        arg_Fec_Fin_Realizacion = ai_value;
    }
    private String getarg_Fec_Fin_Realizacion()
    {
        return arg_Fec_Fin_Realizacion;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // ARG_AREA.
        if (arg_Area != null)
        {
            htItems.put("ARG_AREA", M4BusinessMethodArg.toString(arg_Area));
        }
        // ARG_FASE.
        if (arg_Fase != null)
        {
            htItems.put("ARG_FASE", M4BusinessMethodArg.toString(arg_Fase));
        }
        // ARG_PUESTO.
        if (arg_Puesto != null)
        {
            htItems.put("ARG_PUESTO", M4BusinessMethodArg.toString(arg_Puesto));
        }
        // ARG_UNIDAD.
        if (arg_Unidad != null)
        {
            htItems.put("ARG_UNIDAD", M4BusinessMethodArg.toString(arg_Unidad));
        }
        // ARG_NOMB_APE.
        if (arg_Nomb_Ape != null)
        {
            htItems.put("ARG_NOMB_APE", M4BusinessMethodArg.toString(arg_Nomb_Ape));
        }
        // ARG_SERVICIO.
        if (arg_Servicio != null)
        {
            htItems.put("ARG_SERVICIO", M4BusinessMethodArg.toString(arg_Servicio));
        }
        // ARG_SOCIEDAD.
        if (arg_Sociedad != null)
        {
            htItems.put("ARG_SOCIEDAD", M4BusinessMethodArg.toString(arg_Sociedad));
        }
        // ARG_DIRECCION.
        if (arg_Direccion != null)
        {
            htItems.put("ARG_DIRECCION", M4BusinessMethodArg.toString(arg_Direccion));
        }
        // ARG_GRUPO_NIV.
        if (arg_Grupo_Niv != null)
        {
            htItems.put("ARG_GRUPO_NIV", M4BusinessMethodArg.toString(arg_Grupo_Niv));
        }
        // ARG_FECHA_PRUEBA.
        if (arg_Fecha_Prueba != null)
        {
            htItems.put("ARG_FECHA_PRUEBA", M4BusinessMethodArg.toString(arg_Fecha_Prueba));
        }
        // ARG_FEC_FIN_PRUEBA.
        if (arg_Fec_Fin_Prueba != null)
        {
            htItems.put("ARG_FEC_FIN_PRUEBA", M4BusinessMethodArg.toString(arg_Fec_Fin_Prueba));
        }
        // ARG_FEC_REALIZACION.
        if (arg_Fec_Realizacion != null)
        {
            htItems.put("ARG_FEC_REALIZACION", M4BusinessMethodArg.toString(arg_Fec_Realizacion));
        }
        // ARG_FEC_FIN_REALIZACION.
        if (arg_Fec_Fin_Realizacion != null)
        {
            htItems.put("ARG_FEC_FIN_REALIZACION", M4BusinessMethodArg.toString(arg_Fec_Fin_Realizacion));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read ARG_AREA.
        sItemName = "ARG_AREA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        arg_Area = sItemValue;

        // read ARG_FASE.
        sItemName = "ARG_FASE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        arg_Fase = sItemValue;

        // read ARG_PUESTO.
        sItemName = "ARG_PUESTO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        arg_Puesto = sItemValue;

        // read ARG_UNIDAD.
        sItemName = "ARG_UNIDAD";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        arg_Unidad = sItemValue;

        // read ARG_NOMB_APE.
        sItemName = "ARG_NOMB_APE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        arg_Nomb_Ape = sItemValue;

        // read ARG_SERVICIO.
        sItemName = "ARG_SERVICIO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        arg_Servicio = sItemValue;

        // read ARG_SOCIEDAD.
        sItemName = "ARG_SOCIEDAD";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        arg_Sociedad = sItemValue;

        // read ARG_DIRECCION.
        sItemName = "ARG_DIRECCION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        arg_Direccion = sItemValue;

        // read ARG_GRUPO_NIV.
        sItemName = "ARG_GRUPO_NIV";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        arg_Grupo_Niv = sItemValue;

        // read ARG_FECHA_PRUEBA.
        sItemName = "ARG_FECHA_PRUEBA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        arg_Fecha_Prueba = sItemValue;

        // read ARG_FEC_FIN_PRUEBA.
        sItemName = "ARG_FEC_FIN_PRUEBA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        arg_Fec_Fin_Prueba = sItemValue;

        // read ARG_FEC_REALIZACION.
        sItemName = "ARG_FEC_REALIZACION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        arg_Fec_Realizacion = sItemValue;

        // read ARG_FEC_FIN_REALIZACION.
        sItemName = "ARG_FEC_FIN_REALIZACION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        arg_Fec_Fin_Realizacion = sItemValue;


    } /* end of method readOperations */


} /* end of class Cyc_Fb_Param_Entrada_EnviadosRecord */

