/**
 * Csp_Consulta_8_UnidadBlock.java
 * Self generated code for Bussines Object CSP_CONSULTA_VALI_AREA.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.csp_consulta_vali_area;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Csp_Consulta_8_Unidad.
 * @author Meta4
 */
public 
class Csp_Consulta_8_UnidadBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_CONSULTA_VALI_AREA";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_CONSULTA_8_UNIDAD";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Consulta_8_UnidadBlock.class.getName());

    /* item P_UNIDAD_SUP */
    public String p_Unidad_Sup = null;
    private void setp_Unidad_Sup(String ai_value)
    {
        p_Unidad_Sup = ai_value;
    }
    private String getp_Unidad_Sup()
    {
        return p_Unidad_Sup;
    }

    /* the recordset */
    public Csp_Consulta_8_UnidadRecord[] Csp_Consulta_8_UnidadRecordSet = null;
    private void setCsp_Consulta_8_UnidadRecordSet(Csp_Consulta_8_UnidadRecord[] ai_arg)
    {
        Csp_Consulta_8_UnidadRecordSet = ai_arg;
    }
    private Csp_Consulta_8_UnidadRecord[] getCsp_Consulta_8_UnidadRecordSet()
    {
        return Csp_Consulta_8_UnidadRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Csp_Consulta_8_UnidadBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // P_UNIDAD_SUP.
        if (p_Unidad_Sup != null)
        {
            htItems.put("P_UNIDAD_SUP", M4BusinessMethodArg.toString(p_Unidad_Sup));
        }

        // insert 'block scope' values in CSP_CONSULTA_8_UNIDAD.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in CSP_CONSULTA_8_UNIDAD.
        if (Csp_Consulta_8_UnidadRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Csp_Consulta_8_UnidadRecordSet.length; i++)
        {
            Csp_Consulta_8_UnidadRecord record = Csp_Consulta_8_UnidadRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in CSP_CONSULTA_8_UNIDAD.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;

        // read P_UNIDAD_SUP.
        sItemName = "P_UNIDAD_SUP";
        nItem = ai_xml.findItem(ai_node, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Unidad_Sup = sItemValue;

        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Csp_Consulta_8_UnidadRecordSet = new Csp_Consulta_8_UnidadRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Csp_Consulta_8_UnidadRecord record = new Csp_Consulta_8_UnidadRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Csp_Consulta_8_UnidadRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Csp_Consulta_8_UnidadBlock */

