/**
 * Csp_Level_ObjetivosBlock.java
 * Self generated code for Bussines Object CSP_GUARDAR_OBJ_PLAN.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.csp_guardar_obj_plan;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Csp_Level_Objetivos.
 * @author Meta4
 */
public 
class Csp_Level_ObjetivosBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_GUARDAR_OBJ_PLAN";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_LEVEL_OBJETIVOS";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Level_ObjetivosBlock.class.getName());

    /* item P_LEVEL */
    public Double p_Level = null;
    private void setp_Level(Double ai_value)
    {
        p_Level = ai_value;
    }
    private Double getp_Level()
    {
        return p_Level;
    }

    /* the recordset */
    public Csp_Level_ObjetivosRecord[] Csp_Level_ObjetivosRecordSet = null;
    private void setCsp_Level_ObjetivosRecordSet(Csp_Level_ObjetivosRecord[] ai_arg)
    {
        Csp_Level_ObjetivosRecordSet = ai_arg;
    }
    private Csp_Level_ObjetivosRecord[] getCsp_Level_ObjetivosRecordSet()
    {
        return Csp_Level_ObjetivosRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Csp_Level_ObjetivosBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // P_LEVEL.
		if (p_Level != null)
    	{
			htItems.put("P_LEVEL", M4BusinessMethodArg.toString(p_Level));
    	}


        // insert 'block scope' values in CSP_LEVEL_OBJETIVOS.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in CSP_LEVEL_OBJETIVOS.
        if (Csp_Level_ObjetivosRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Csp_Level_ObjetivosRecordSet.length; i++)
        {
            Csp_Level_ObjetivosRecord record = Csp_Level_ObjetivosRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in CSP_LEVEL_OBJETIVOS.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;

        // read P_LEVEL.
        sItemName = "P_LEVEL";
        nItem = ai_xml.findItem(ai_node, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Level = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Csp_Level_ObjetivosRecordSet = new Csp_Level_ObjetivosRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Csp_Level_ObjetivosRecord record = new Csp_Level_ObjetivosRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Csp_Level_ObjetivosRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Csp_Level_ObjetivosBlock */

