/**
 * Csp_Obj_LevelBlock.java
 * Self generated code for Bussines Object CSP_GUARDAR_OBJ_PLAN.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.csp_guardar_obj_plan;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Csp_Obj_Level.
 * @author Meta4
 */
public 
class Csp_Obj_LevelBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_GUARDAR_OBJ_PLAN";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_OBJ_LEVEL";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Obj_LevelBlock.class.getName());

    /* item P_ID_OBJ */
    public String p_Id_Obj = null;
    private void setp_Id_Obj(String ai_value)
    {
        p_Id_Obj = ai_value;
    }
    private String getp_Id_Obj()
    {
        return p_Id_Obj;
    }

    /* the recordset */
    public Csp_Obj_LevelRecord[] Csp_Obj_LevelRecordSet = null;
    private void setCsp_Obj_LevelRecordSet(Csp_Obj_LevelRecord[] ai_arg)
    {
        Csp_Obj_LevelRecordSet = ai_arg;
    }
    private Csp_Obj_LevelRecord[] getCsp_Obj_LevelRecordSet()
    {
        return Csp_Obj_LevelRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Csp_Obj_LevelBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // P_ID_OBJ.
        if (p_Id_Obj != null)
        {
            htItems.put("P_ID_OBJ", M4BusinessMethodArg.toString(p_Id_Obj));
        }

        // insert 'block scope' values in CSP_OBJ_LEVEL.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in CSP_OBJ_LEVEL.
        if (Csp_Obj_LevelRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Csp_Obj_LevelRecordSet.length; i++)
        {
            Csp_Obj_LevelRecord record = Csp_Obj_LevelRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in CSP_OBJ_LEVEL.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;

        // read P_ID_OBJ.
        sItemName = "P_ID_OBJ";
        nItem = ai_xml.findItem(ai_node, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Id_Obj = sItemValue;

        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Csp_Obj_LevelRecordSet = new Csp_Obj_LevelRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Csp_Obj_LevelRecord record = new Csp_Obj_LevelRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Csp_Obj_LevelRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Csp_Obj_LevelBlock */

