/**
 * Cyc_S_Fase_I_PBlock.java
 * Self generated code for Bussines Object CYC_S_FASE_I_P.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.cyc_s_fase_i_p;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Cyc_S_Fase_I_P.
 * @author Meta4
 */
public 
class Cyc_S_Fase_I_PBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_S_FASE_I_P";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_S_FASE_I_P";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_S_Fase_I_PBlock.class.getName());

    /* item CYC_P_ID_HR */
    public Double cyc_P_Id_Hr = null;
    private void setcyc_P_Id_Hr(Double ai_value)
    {
        cyc_P_Id_Hr = ai_value;
    }
    private Double getcyc_P_Id_Hr()
    {
        return cyc_P_Id_Hr;
    }

    /* the recordset */
    public Cyc_S_Fase_I_PRecord[] Cyc_S_Fase_I_PRecordSet = null;
    private void setCyc_S_Fase_I_PRecordSet(Cyc_S_Fase_I_PRecord[] ai_arg)
    {
        Cyc_S_Fase_I_PRecordSet = ai_arg;
    }
    private Cyc_S_Fase_I_PRecord[] getCyc_S_Fase_I_PRecordSet()
    {
        return Cyc_S_Fase_I_PRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Cyc_S_Fase_I_PBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // CYC_P_ID_HR.
		if (cyc_P_Id_Hr != null)
    	{
			htItems.put("CYC_P_ID_HR", M4BusinessMethodArg.toString(cyc_P_Id_Hr));
    	}


        // insert 'block scope' values in CYC_S_FASE_I_P.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in CYC_S_FASE_I_P.
        if (Cyc_S_Fase_I_PRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Cyc_S_Fase_I_PRecordSet.length; i++)
        {
            Cyc_S_Fase_I_PRecord record = Cyc_S_Fase_I_PRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in CYC_S_FASE_I_P.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;

        // read CYC_P_ID_HR.
        sItemName = "CYC_P_ID_HR";
        nItem = ai_xml.findItem(ai_node, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_P_Id_Hr = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Cyc_S_Fase_I_PRecordSet = new Cyc_S_Fase_I_PRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Cyc_S_Fase_I_PRecord record = new Cyc_S_Fase_I_PRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Cyc_S_Fase_I_PRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Cyc_S_Fase_I_PBlock */

