/**
 * Csp_CvRecord.java
 * Self generated code for Bussines Object CSP_SERVICIO_CV.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_servicio_cv;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Cv.
 * @author Meta4
 */
public 
class Csp_CvRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_SERVICIO_CV";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_CV";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_CvRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item STD_EMAIL */
    public String std_Email = null;
    private void setstd_Email(String ai_value)
    {
        std_Email = ai_value;
    }
    private String getstd_Email()
    {
        return std_Email;
    }

    /* item STD_ID_HR */
    public String std_Id_Hr = null;
    private void setstd_Id_Hr(String ai_value)
    {
        std_Id_Hr = ai_value;
    }
    private String getstd_Id_Hr()
    {
        return std_Id_Hr;
    }

    /* item SCO_DT_START */
    public Calendar sco_Dt_Start = null;
    private void setsco_Dt_Start(Calendar ai_value)
    {
        sco_Dt_Start = ai_value;
    }
    private Calendar getsco_Dt_Start()
    {
        return sco_Dt_Start;
    }

    /* item STD_DT_BIRTH */
    public Calendar std_Dt_Birth = null;
    private void setstd_Dt_Birth(Calendar ai_value)
    {
        std_Dt_Birth = ai_value;
    }
    private Calendar getstd_Dt_Birth()
    {
        return std_Dt_Birth;
    }

    /* item SCO_BLOB_PHOTO */
    public DataHandler sco_Blob_Photo = null;
    private void setsco_Blob_Photo(DataHandler ai_value)
    {
        sco_Blob_Photo = ai_value;
    }
    private DataHandler getsco_Blob_Photo()
    {
        return sco_Blob_Photo;
    }

    /* item STD_N_JOB_CODE */
    public String std_N_Job_Code = null;
    private void setstd_N_Job_Code(String ai_value)
    {
        std_N_Job_Code = ai_value;
    }
    private String getstd_N_Job_Code()
    {
        return std_N_Job_Code;
    }

    /* item ID_ORGANIZATION */
    public String id_Organization = null;
    private void setid_Organization(String ai_value)
    {
        id_Organization = ai_value;
    }
    private String getid_Organization()
    {
        return id_Organization;
    }

    /* item SSP_ID_CATEGORIA */
    public String ssp_Id_Categoria = null;
    private void setssp_Id_Categoria(String ai_value)
    {
        ssp_Id_Categoria = ai_value;
    }
    private String getssp_Id_Categoria()
    {
        return ssp_Id_Categoria;
    }

    /* item SSP_NM_CATEGORIA */
    public String ssp_Nm_Categoria = null;
    private void setssp_Nm_Categoria(String ai_value)
    {
        ssp_Nm_Categoria = ai_value;
    }
    private String getssp_Nm_Categoria()
    {
        return ssp_Nm_Categoria;
    }

    /* item STD_N_FIRST_NAME */
    public String std_N_First_Name = null;
    private void setstd_N_First_Name(String ai_value)
    {
        std_N_First_Name = ai_value;
    }
    private String getstd_N_First_Name()
    {
        return std_N_First_Name;
    }

    /* item SSP_FEC_ANTIGUEDAD */
    public Calendar ssp_Fec_Antiguedad = null;
    private void setssp_Fec_Antiguedad(Calendar ai_value)
    {
        ssp_Fec_Antiguedad = ai_value;
    }
    private Calendar getssp_Fec_Antiguedad()
    {
        return ssp_Fec_Antiguedad;
    }

    /* item STD_N_FAMILY_NAME_1 */
    public String std_N_Family_Name_1 = null;
    private void setstd_N_Family_Name_1(String ai_value)
    {
        std_N_Family_Name_1 = ai_value;
    }
    private String getstd_N_Family_Name_1()
    {
        return std_N_Family_Name_1;
    }

    /* item CSP_N_WORK_FUNCTIONAL */
    public String csp_N_Work_Functional = null;
    private void setcsp_N_Work_Functional(String ai_value)
    {
        csp_N_Work_Functional = ai_value;
    }
    private String getcsp_N_Work_Functional()
    {
        return csp_N_Work_Functional;
    }

    /* item CSP_ID_WORK_FUNCTIONAL */
    public String csp_Id_Work_Functional = null;
    private void setcsp_Id_Work_Functional(String ai_value)
    {
        csp_Id_Work_Functional = ai_value;
    }
    private String getcsp_Id_Work_Functional()
    {
        return csp_Id_Work_Functional;
    }

    /* node CSP_IDIOMAS */
    public Csp_IdiomasBlock Csp_Idiomas = null;
    private void setcsp_Idiomas(Csp_IdiomasBlock ai_value)
    {
        Csp_Idiomas = ai_value;
    }
    private Csp_IdiomasBlock getCsp_Idiomas()
    {
        return Csp_Idiomas;
    }

    /* node CSP_TITULACION */
    public Csp_TitulacionBlock Csp_Titulacion = null;
    private void setcsp_Titulacion(Csp_TitulacionBlock ai_value)
    {
        Csp_Titulacion = ai_value;
    }
    private Csp_TitulacionBlock getCsp_Titulacion()
    {
        return Csp_Titulacion;
    }

    /* node CSP_OTROS_TITULOS */
    public Csp_Otros_TitulosBlock Csp_Otros_Titulos = null;
    private void setcsp_Otros_Titulos(Csp_Otros_TitulosBlock ai_value)
    {
        Csp_Otros_Titulos = ai_value;
    }
    private Csp_Otros_TitulosBlock getCsp_Otros_Titulos()
    {
        return Csp_Otros_Titulos;
    }

    /* node CSP_CERTIFICADOS_CV */
    public Csp_Certificados_CvBlock Csp_Certificados_Cv = null;
    private void setcsp_Certificados_Cv(Csp_Certificados_CvBlock ai_value)
    {
        Csp_Certificados_Cv = ai_value;
    }
    private Csp_Certificados_CvBlock getCsp_Certificados_Cv()
    {
        return Csp_Certificados_Cv;
    }

    /* node CSP_FORMACION_EXTERNA */
    public Csp_Formacion_ExternaBlock Csp_Formacion_Externa = null;
    private void setcsp_Formacion_Externa(Csp_Formacion_ExternaBlock ai_value)
    {
        Csp_Formacion_Externa = ai_value;
    }
    private Csp_Formacion_ExternaBlock getCsp_Formacion_Externa()
    {
        return Csp_Formacion_Externa;
    }

    /* node CSP_FORMACION_INTERNA */
    public Csp_Formacion_InternaBlock Csp_Formacion_Interna = null;
    private void setcsp_Formacion_Interna(Csp_Formacion_InternaBlock ai_value)
    {
        Csp_Formacion_Interna = ai_value;
    }
    private Csp_Formacion_InternaBlock getCsp_Formacion_Interna()
    {
        return Csp_Formacion_Interna;
    }

    /* node CSP_EXPERIENCIA_PROF_EXTERNA */
    public Csp_Experiencia_Prof_ExternaBlock Csp_Experiencia_Prof_Externa = null;
    private void setcsp_Experiencia_Prof_Externa(Csp_Experiencia_Prof_ExternaBlock ai_value)
    {
        Csp_Experiencia_Prof_Externa = ai_value;
    }
    private Csp_Experiencia_Prof_ExternaBlock getCsp_Experiencia_Prof_Externa()
    {
        return Csp_Experiencia_Prof_Externa;
    }

    /* node CSP_EXPERIENCIA_PROF_INTERNA */
    public Csp_Experiencia_Prof_InternaBlock Csp_Experiencia_Prof_Interna = null;
    private void setcsp_Experiencia_Prof_Interna(Csp_Experiencia_Prof_InternaBlock ai_value)
    {
        Csp_Experiencia_Prof_Interna = ai_value;
    }
    private Csp_Experiencia_Prof_InternaBlock getCsp_Experiencia_Prof_Interna()
    {
        return Csp_Experiencia_Prof_Interna;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // STD_EMAIL.
        if (std_Email != null)
        {
            htItems.put("STD_EMAIL", M4BusinessMethodArg.toString(std_Email));
        }
        // STD_ID_HR.
        if (std_Id_Hr != null)
        {
            htItems.put("STD_ID_HR", M4BusinessMethodArg.toString(std_Id_Hr));
        }
        // SCO_DT_START.
        if (sco_Dt_Start != null)
        {
            htItems.put("SCO_DT_START", M4BusinessMethodArg.toString(sco_Dt_Start));
        }
        // STD_DT_BIRTH.
        if (std_Dt_Birth != null)
        {
            htItems.put("STD_DT_BIRTH", M4BusinessMethodArg.toString(std_Dt_Birth));
        }
        // SCO_BLOB_PHOTO.
        if ( sco_Blob_Photo != null )
        {
            htBlobs.put("SCO_BLOB_PHOTO", sco_Blob_Photo.getName());
        }
        // STD_N_JOB_CODE.
        if (std_N_Job_Code != null)
        {
            htItems.put("STD_N_JOB_CODE", M4BusinessMethodArg.toString(std_N_Job_Code));
        }
        // ID_ORGANIZATION.
        if (id_Organization != null)
        {
            htItems.put("ID_ORGANIZATION", M4BusinessMethodArg.toString(id_Organization));
        }
        // SSP_ID_CATEGORIA.
        if (ssp_Id_Categoria != null)
        {
            htItems.put("SSP_ID_CATEGORIA", M4BusinessMethodArg.toString(ssp_Id_Categoria));
        }
        // SSP_NM_CATEGORIA.
        if (ssp_Nm_Categoria != null)
        {
            htItems.put("SSP_NM_CATEGORIA", M4BusinessMethodArg.toString(ssp_Nm_Categoria));
        }
        // STD_N_FIRST_NAME.
        if (std_N_First_Name != null)
        {
            htItems.put("STD_N_FIRST_NAME", M4BusinessMethodArg.toString(std_N_First_Name));
        }
        // SSP_FEC_ANTIGUEDAD.
        if (ssp_Fec_Antiguedad != null)
        {
            htItems.put("SSP_FEC_ANTIGUEDAD", M4BusinessMethodArg.toString(ssp_Fec_Antiguedad));
        }
        // STD_N_FAMILY_NAME_1.
        if (std_N_Family_Name_1 != null)
        {
            htItems.put("STD_N_FAMILY_NAME_1", M4BusinessMethodArg.toString(std_N_Family_Name_1));
        }
        // CSP_N_WORK_FUNCTIONAL.
        if (csp_N_Work_Functional != null)
        {
            htItems.put("CSP_N_WORK_FUNCTIONAL", M4BusinessMethodArg.toString(csp_N_Work_Functional));
        }
        // CSP_ID_WORK_FUNCTIONAL.
        if (csp_Id_Work_Functional != null)
        {
            htItems.put("CSP_ID_WORK_FUNCTIONAL", M4BusinessMethodArg.toString(csp_Id_Work_Functional));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

        // write data for node CSP_IDIOMAS.
        if ( Csp_Idiomas != null) 
        {
           Csp_Idiomas.writeOperations(ai_m4Op);
        }

        // write data for node CSP_TITULACION.
        if ( Csp_Titulacion != null) 
        {
           Csp_Titulacion.writeOperations(ai_m4Op);
        }

        // write data for node CSP_OTROS_TITULOS.
        if ( Csp_Otros_Titulos != null) 
        {
           Csp_Otros_Titulos.writeOperations(ai_m4Op);
        }

        // write data for node CSP_CERTIFICADOS_CV.
        if ( Csp_Certificados_Cv != null) 
        {
           Csp_Certificados_Cv.writeOperations(ai_m4Op);
        }

        // write data for node CSP_FORMACION_EXTERNA.
        if ( Csp_Formacion_Externa != null) 
        {
           Csp_Formacion_Externa.writeOperations(ai_m4Op);
        }

        // write data for node CSP_FORMACION_INTERNA.
        if ( Csp_Formacion_Interna != null) 
        {
           Csp_Formacion_Interna.writeOperations(ai_m4Op);
        }

        // write data for node CSP_EXPERIENCIA_PROF_EXTERNA.
        if ( Csp_Experiencia_Prof_Externa != null) 
        {
           Csp_Experiencia_Prof_Externa.writeOperations(ai_m4Op);
        }

        // write data for node CSP_EXPERIENCIA_PROF_INTERNA.
        if ( Csp_Experiencia_Prof_Interna != null) 
        {
           Csp_Experiencia_Prof_Interna.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read STD_EMAIL.
        sItemName = "STD_EMAIL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Email = sItemValue;

        // read STD_ID_HR.
        sItemName = "STD_ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Id_Hr = sItemValue;

        // read SCO_DT_START.
        sItemName = "SCO_DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read STD_DT_BIRTH.
        sItemName = "STD_DT_BIRTH";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Dt_Birth = M4BusinessMethodArg.toCalendar(sItemValue);

        // read SCO_BLOB_PHOTO.
        sItemName = "SCO_BLOB_PHOTO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getOptionalAttValue(nItem, "fileindex");
        if (sItemValue != null)
        {
            sItemValue = ai_m4Op.getFileByIndex(Integer.parseInt(sItemValue));
            sco_Blob_Photo = new DataHandler(new M4FileDataSource(sItemValue));
        } 
        else // the case where there is no file in the item
        {
            sco_Blob_Photo = null;
        }


        // read SCO_BLOB_PHOTO.
        sItemName = "SCO_BLOB_PHOTO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getOptionalAttValue(nItem, "fileindex");
        if (sItemValue != null)
        {
            sItemValue = ai_m4Op.getFileByIndex(Integer.parseInt(sItemValue));
            sco_Blob_Photo = new DataHandler(new M4FileDataSource(sItemValue));
        } 
        else // the case where there is no file in the item
        {
            sco_Blob_Photo = null;
        }


        // read STD_N_JOB_CODE.
        sItemName = "STD_N_JOB_CODE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_Job_Code = sItemValue;

        // read ID_ORGANIZATION.
        sItemName = "ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Organization = sItemValue;

        // read SSP_ID_CATEGORIA.
        sItemName = "SSP_ID_CATEGORIA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        ssp_Id_Categoria = sItemValue;

        // read SSP_NM_CATEGORIA.
        sItemName = "SSP_NM_CATEGORIA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        ssp_Nm_Categoria = sItemValue;

        // read STD_N_FIRST_NAME.
        sItemName = "STD_N_FIRST_NAME";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_First_Name = sItemValue;

        // read SSP_FEC_ANTIGUEDAD.
        sItemName = "SSP_FEC_ANTIGUEDAD";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        ssp_Fec_Antiguedad = M4BusinessMethodArg.toCalendar(sItemValue);

        // read STD_N_FAMILY_NAME_1.
        sItemName = "STD_N_FAMILY_NAME_1";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_Family_Name_1 = sItemValue;

        // read CSP_N_WORK_FUNCTIONAL.
        sItemName = "CSP_N_WORK_FUNCTIONAL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_N_Work_Functional = sItemValue;

        // read CSP_ID_WORK_FUNCTIONAL.
        sItemName = "CSP_ID_WORK_FUNCTIONAL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Work_Functional = sItemValue;

        // read data for node CSP_IDIOMAS.
        Csp_Idiomas = new Csp_IdiomasBlock();
        Csp_Idiomas.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_IdiomasBlock.NODE_NAME));

        // read data for node CSP_TITULACION.
        Csp_Titulacion = new Csp_TitulacionBlock();
        Csp_Titulacion.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_TitulacionBlock.NODE_NAME));

        // read data for node CSP_OTROS_TITULOS.
        Csp_Otros_Titulos = new Csp_Otros_TitulosBlock();
        Csp_Otros_Titulos.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_Otros_TitulosBlock.NODE_NAME));

        // read data for node CSP_CERTIFICADOS_CV.
        Csp_Certificados_Cv = new Csp_Certificados_CvBlock();
        Csp_Certificados_Cv.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_Certificados_CvBlock.NODE_NAME));

        // read data for node CSP_FORMACION_EXTERNA.
        Csp_Formacion_Externa = new Csp_Formacion_ExternaBlock();
        Csp_Formacion_Externa.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_Formacion_ExternaBlock.NODE_NAME));

        // read data for node CSP_FORMACION_INTERNA.
        Csp_Formacion_Interna = new Csp_Formacion_InternaBlock();
        Csp_Formacion_Interna.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_Formacion_InternaBlock.NODE_NAME));

        // read data for node CSP_EXPERIENCIA_PROF_EXTERNA.
        Csp_Experiencia_Prof_Externa = new Csp_Experiencia_Prof_ExternaBlock();
        Csp_Experiencia_Prof_Externa.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_Experiencia_Prof_ExternaBlock.NODE_NAME));

        // read data for node CSP_EXPERIENCIA_PROF_INTERNA.
        Csp_Experiencia_Prof_Interna = new Csp_Experiencia_Prof_InternaBlock();
        Csp_Experiencia_Prof_Interna.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Csp_Experiencia_Prof_InternaBlock.NODE_NAME));


    } /* end of method readOperations */


} /* end of class Csp_CvRecord */

