/**
 * Csp_TitulacionRecord.java
 * Self generated code for Bussines Object CSP_SERVICIO_CV.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_servicio_cv;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Titulacion.
 * @author Meta4
 */
public 
class Csp_TitulacionRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_SERVICIO_CV";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_TITULACION";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_TitulacionRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item STD_COMMENT */
    public String std_Comment = null;
    private void setstd_Comment(String ai_value)
    {
        std_Comment = ai_value;
    }
    private String getstd_Comment()
    {
        return std_Comment;
    }

    /* item STD_DT_START */
    public Calendar std_Dt_Start = null;
    private void setstd_Dt_Start(Calendar ai_value)
    {
        std_Dt_Start = ai_value;
    }
    private Calendar getstd_Dt_Start()
    {
        return std_Dt_Start;
    }

    /* item STD_N_EDU_SP */
    public String std_N_Edu_Sp = null;
    private void setstd_N_Edu_Sp(String ai_value)
    {
        std_N_Edu_Sp = ai_value;
    }
    private String getstd_N_Edu_Sp()
    {
        return std_N_Edu_Sp;
    }

    /* item STD_ID_EDU_SP */
    public String std_Id_Edu_Sp = null;
    private void setstd_Id_Edu_Sp(String ai_value)
    {
        std_Id_Edu_Sp = ai_value;
    }
    private String getstd_Id_Edu_Sp()
    {
        return std_Id_Edu_Sp;
    }

    /* item STD_ID_SECTOR */
    public String std_Id_Sector = null;
    private void setstd_Id_Sector(String ai_value)
    {
        std_Id_Sector = ai_value;
    }
    private String getstd_Id_Sector()
    {
        return std_Id_Sector;
    }

    /* item STD_N_COUNTRY */
    public String std_N_Country = null;
    private void setstd_N_Country(String ai_value)
    {
        std_N_Country = ai_value;
    }
    private String getstd_N_Country()
    {
        return std_N_Country;
    }

    /* item STD_N_EXT_ORG */
    public String std_N_Ext_Org = null;
    private void setstd_N_Ext_Org(String ai_value)
    {
        std_N_Ext_Org = ai_value;
    }
    private String getstd_N_Ext_Org()
    {
        return std_N_Ext_Org;
    }

    /* item SCO_CK_END_DIP */
    public Double sco_Ck_End_Dip = null;
    private void setsco_Ck_End_Dip(Double ai_value)
    {
        sco_Ck_End_Dip = ai_value;
    }
    private Double getsco_Ck_End_Dip()
    {
        return sco_Ck_End_Dip;
    }

    /* item STD_ID_DIPLOMA */
    public String std_Id_Diploma = null;
    private void setstd_Id_Diploma(String ai_value)
    {
        std_Id_Diploma = ai_value;
    }
    private String getstd_Id_Diploma()
    {
        return std_Id_Diploma;
    }

    /* item STD_N_EDU_TYPE */
    public String std_N_Edu_Type = null;
    private void setstd_N_Edu_Type(String ai_value)
    {
        std_N_Edu_Type = ai_value;
    }
    private String getstd_N_Edu_Type()
    {
        return std_N_Edu_Type;
    }

    /* item STD_ID_EDU_TYPE */
    public String std_Id_Edu_Type = null;
    private void setstd_Id_Edu_Type(String ai_value)
    {
        std_Id_Edu_Type = ai_value;
    }
    private String getstd_Id_Edu_Type()
    {
        return std_Id_Edu_Type;
    }

    /* item STD_ORD_ACD_BACK */
    public Double std_Ord_Acd_Back = null;
    private void setstd_Ord_Acd_Back(Double ai_value)
    {
        std_Ord_Acd_Back = ai_value;
    }
    private Double getstd_Ord_Acd_Back()
    {
        return std_Ord_Acd_Back;
    }

    /* item STD_ID_EDU_CENTER */
    public String std_Id_Edu_Center = null;
    private void setstd_Id_Edu_Center(String ai_value)
    {
        std_Id_Edu_Center = ai_value;
    }
    private String getstd_Id_Edu_Center()
    {
        return std_Id_Edu_Center;
    }

    /* item STD_DT_EARNED_EXPE */
    public Calendar std_Dt_Earned_Expe = null;
    private void setstd_Dt_Earned_Expe(Calendar ai_value)
    {
        std_Dt_Earned_Expe = ai_value;
    }
    private Calendar getstd_Dt_Earned_Expe()
    {
        return std_Dt_Earned_Expe;
    }

    /* item STD_ID_SUB_GEO_DIV */
    public String std_Id_Sub_Geo_Div = null;
    private void setstd_Id_Sub_Geo_Div(String ai_value)
    {
        std_Id_Sub_Geo_Div = ai_value;
    }
    private String getstd_Id_Sub_Geo_Div()
    {
        return std_Id_Sub_Geo_Div;
    }

    /* item STD_COMPLETED_YEARS */
    public Double std_Completed_Years = null;
    private void setstd_Completed_Years(Double ai_value)
    {
        std_Completed_Years = ai_value;
    }
    private Double getstd_Completed_Years()
    {
        return std_Completed_Years;
    }

    /* item STD_DESC_EDU_CENTER */
    public String std_Desc_Edu_Center = null;
    private void setstd_Desc_Edu_Center(String ai_value)
    {
        std_Desc_Edu_Center = ai_value;
    }
    private String getstd_Desc_Edu_Center()
    {
        return std_Desc_Edu_Center;
    }

    /* item STD_TOTAL_YEARS_DIP */
    public Double std_Total_Years_Dip = null;
    private void setstd_Total_Years_Dip(Double ai_value)
    {
        std_Total_Years_Dip = ai_value;
    }
    private Double getstd_Total_Years_Dip()
    {
        return std_Total_Years_Dip;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // STD_COMMENT.
        if (std_Comment != null)
        {
            htItems.put("STD_COMMENT", M4BusinessMethodArg.toString(std_Comment));
        }
        // STD_DT_START.
        if (std_Dt_Start != null)
        {
            htItems.put("STD_DT_START", M4BusinessMethodArg.toString(std_Dt_Start));
        }
        // STD_N_EDU_SP.
        if (std_N_Edu_Sp != null)
        {
            htItems.put("STD_N_EDU_SP", M4BusinessMethodArg.toString(std_N_Edu_Sp));
        }
        // STD_ID_EDU_SP.
        if (std_Id_Edu_Sp != null)
        {
            htItems.put("STD_ID_EDU_SP", M4BusinessMethodArg.toString(std_Id_Edu_Sp));
        }
        // STD_ID_SECTOR.
        if (std_Id_Sector != null)
        {
            htItems.put("STD_ID_SECTOR", M4BusinessMethodArg.toString(std_Id_Sector));
        }
        // STD_N_COUNTRY.
        if (std_N_Country != null)
        {
            htItems.put("STD_N_COUNTRY", M4BusinessMethodArg.toString(std_N_Country));
        }
        // STD_N_EXT_ORG.
        if (std_N_Ext_Org != null)
        {
            htItems.put("STD_N_EXT_ORG", M4BusinessMethodArg.toString(std_N_Ext_Org));
        }
        // SCO_CK_END_DIP.
        if (sco_Ck_End_Dip != null)
        {
            htItems.put("SCO_CK_END_DIP", M4BusinessMethodArg.toString(sco_Ck_End_Dip));
        }
        // STD_ID_DIPLOMA.
        if (std_Id_Diploma != null)
        {
            htItems.put("STD_ID_DIPLOMA", M4BusinessMethodArg.toString(std_Id_Diploma));
        }
        // STD_N_EDU_TYPE.
        if (std_N_Edu_Type != null)
        {
            htItems.put("STD_N_EDU_TYPE", M4BusinessMethodArg.toString(std_N_Edu_Type));
        }
        // STD_ID_EDU_TYPE.
        if (std_Id_Edu_Type != null)
        {
            htItems.put("STD_ID_EDU_TYPE", M4BusinessMethodArg.toString(std_Id_Edu_Type));
        }
        // STD_ORD_ACD_BACK.
        if (std_Ord_Acd_Back != null)
        {
            htItems.put("STD_ORD_ACD_BACK", M4BusinessMethodArg.toString(std_Ord_Acd_Back));
        }
        // STD_ID_EDU_CENTER.
        if (std_Id_Edu_Center != null)
        {
            htItems.put("STD_ID_EDU_CENTER", M4BusinessMethodArg.toString(std_Id_Edu_Center));
        }
        // STD_DT_EARNED_EXPE.
        if (std_Dt_Earned_Expe != null)
        {
            htItems.put("STD_DT_EARNED_EXPE", M4BusinessMethodArg.toString(std_Dt_Earned_Expe));
        }
        // STD_ID_SUB_GEO_DIV.
        if (std_Id_Sub_Geo_Div != null)
        {
            htItems.put("STD_ID_SUB_GEO_DIV", M4BusinessMethodArg.toString(std_Id_Sub_Geo_Div));
        }
        // STD_COMPLETED_YEARS.
        if (std_Completed_Years != null)
        {
            htItems.put("STD_COMPLETED_YEARS", M4BusinessMethodArg.toString(std_Completed_Years));
        }
        // STD_DESC_EDU_CENTER.
        if (std_Desc_Edu_Center != null)
        {
            htItems.put("STD_DESC_EDU_CENTER", M4BusinessMethodArg.toString(std_Desc_Edu_Center));
        }
        // STD_TOTAL_YEARS_DIP.
        if (std_Total_Years_Dip != null)
        {
            htItems.put("STD_TOTAL_YEARS_DIP", M4BusinessMethodArg.toString(std_Total_Years_Dip));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read STD_COMMENT.
        sItemName = "STD_COMMENT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Comment = sItemValue;

        // read STD_DT_START.
        sItemName = "STD_DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read STD_N_EDU_SP.
        sItemName = "STD_N_EDU_SP";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_Edu_Sp = sItemValue;

        // read STD_ID_EDU_SP.
        sItemName = "STD_ID_EDU_SP";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Id_Edu_Sp = sItemValue;

        // read STD_ID_SECTOR.
        sItemName = "STD_ID_SECTOR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Id_Sector = sItemValue;

        // read STD_N_COUNTRY.
        sItemName = "STD_N_COUNTRY";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_Country = sItemValue;

        // read STD_N_EXT_ORG.
        sItemName = "STD_N_EXT_ORG";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_Ext_Org = sItemValue;

        // read SCO_CK_END_DIP.
        sItemName = "SCO_CK_END_DIP";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Ck_End_Dip = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read STD_ID_DIPLOMA.
        sItemName = "STD_ID_DIPLOMA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Id_Diploma = sItemValue;

        // read STD_N_EDU_TYPE.
        sItemName = "STD_N_EDU_TYPE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_Edu_Type = sItemValue;

        // read STD_ID_EDU_TYPE.
        sItemName = "STD_ID_EDU_TYPE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Id_Edu_Type = sItemValue;

        // read STD_ORD_ACD_BACK.
        sItemName = "STD_ORD_ACD_BACK";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Ord_Acd_Back = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read STD_ID_EDU_CENTER.
        sItemName = "STD_ID_EDU_CENTER";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Id_Edu_Center = sItemValue;

        // read STD_DT_EARNED_EXPE.
        sItemName = "STD_DT_EARNED_EXPE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Dt_Earned_Expe = M4BusinessMethodArg.toCalendar(sItemValue);

        // read STD_ID_SUB_GEO_DIV.
        sItemName = "STD_ID_SUB_GEO_DIV";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Id_Sub_Geo_Div = sItemValue;

        // read STD_COMPLETED_YEARS.
        sItemName = "STD_COMPLETED_YEARS";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Completed_Years = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read STD_DESC_EDU_CENTER.
        sItemName = "STD_DESC_EDU_CENTER";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Desc_Edu_Center = sItemValue;

        // read STD_TOTAL_YEARS_DIP.
        sItemName = "STD_TOTAL_YEARS_DIP";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Total_Years_Dip = M4BusinessMethodArg.toDoubleNillable(sItemValue);


    } /* end of method readOperations */


} /* end of class Csp_TitulacionRecord */

