/**
 * Csp_Servicio_CvBlock.java
 * Self generated code for Bussines Object CSP_SERVICIO_CV.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.csp_servicio_cv;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Csp_Servicio_Cv.
 * @author Meta4
 */
public 
class Csp_Servicio_CvBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_SERVICIO_CV";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_SERVICIO_CV";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Servicio_CvBlock.class.getName());

    /* item RESULTADO */
    public String resultado = null;
    private void setresultado(String ai_value)
    {
        resultado = ai_value;
    }
    private String getresultado()
    {
        return resultado;
    }

    /* the recordset */
    public Csp_Servicio_CvRecord[] Csp_Servicio_CvRecordSet = null;
    private void setCsp_Servicio_CvRecordSet(Csp_Servicio_CvRecord[] ai_arg)
    {
        Csp_Servicio_CvRecordSet = ai_arg;
    }
    private Csp_Servicio_CvRecord[] getCsp_Servicio_CvRecordSet()
    {
        return Csp_Servicio_CvRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Csp_Servicio_CvBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // RESULTADO.
        if (resultado != null)
        {
            htItems.put("RESULTADO", M4BusinessMethodArg.toString(resultado));
        }

        // insert 'block scope' values in CSP_SERVICIO_CV.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in CSP_SERVICIO_CV.
        if (Csp_Servicio_CvRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Csp_Servicio_CvRecordSet.length; i++)
        {
            Csp_Servicio_CvRecord record = Csp_Servicio_CvRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in CSP_SERVICIO_CV.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;

        // read RESULTADO.
        sItemName = "RESULTADO";
        nItem = ai_xml.findItem(ai_node, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        resultado = sItemValue;

        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Csp_Servicio_CvRecordSet = new Csp_Servicio_CvRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Csp_Servicio_CvRecord record = new Csp_Servicio_CvRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Csp_Servicio_CvRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Csp_Servicio_CvBlock */

