/**
 * Csp_Formacion_ExternaRecord.java
 * Self generated code for Bussines Object CSP_SERVICIO_CV.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_servicio_cv;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Formacion_Externa.
 * @author Meta4
 */
public 
class Csp_Formacion_ExternaRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_SERVICIO_CV";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_FORMACION_EXTERNA";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Formacion_ExternaRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item SCO_DT_END */
    public Calendar sco_Dt_End = null;
    private void setsco_Dt_End(Calendar ai_value)
    {
        sco_Dt_End = ai_value;
    }
    private Calendar getsco_Dt_End()
    {
        return sco_Dt_End;
    }

    /* item SCO_DT_START */
    public Calendar sco_Dt_Start = null;
    private void setsco_Dt_Start(Calendar ai_value)
    {
        sco_Dt_Start = ai_value;
    }
    private Calendar getsco_Dt_Start()
    {
        return sco_Dt_Start;
    }

    /* item SCO_N_CENTER */
    public String sco_N_Center = null;
    private void setsco_N_Center(String ai_value)
    {
        sco_N_Center = ai_value;
    }
    private String getsco_N_Center()
    {
        return sco_N_Center;
    }

    /* item SCO_N_COURSE */
    public String sco_N_Course = null;
    private void setsco_N_Course(String ai_value)
    {
        sco_N_Course = ai_value;
    }
    private String getsco_N_Course()
    {
        return sco_N_Course;
    }

    /* item SCO_NUMBER_HOURS */
    public Double sco_Number_Hours = null;
    private void setsco_Number_Hours(Double ai_value)
    {
        sco_Number_Hours = ai_value;
    }
    private Double getsco_Number_Hours()
    {
        return sco_Number_Hours;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // SCO_DT_END.
        if (sco_Dt_End != null)
        {
            htItems.put("SCO_DT_END", M4BusinessMethodArg.toString(sco_Dt_End));
        }
        // SCO_DT_START.
        if (sco_Dt_Start != null)
        {
            htItems.put("SCO_DT_START", M4BusinessMethodArg.toString(sco_Dt_Start));
        }
        // SCO_N_CENTER.
        if (sco_N_Center != null)
        {
            htItems.put("SCO_N_CENTER", M4BusinessMethodArg.toString(sco_N_Center));
        }
        // SCO_N_COURSE.
        if (sco_N_Course != null)
        {
            htItems.put("SCO_N_COURSE", M4BusinessMethodArg.toString(sco_N_Course));
        }
        // SCO_NUMBER_HOURS.
        if (sco_Number_Hours != null)
        {
            htItems.put("SCO_NUMBER_HOURS", M4BusinessMethodArg.toString(sco_Number_Hours));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read SCO_DT_END.
        sItemName = "SCO_DT_END";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Dt_End = M4BusinessMethodArg.toCalendar(sItemValue);

        // read SCO_DT_START.
        sItemName = "SCO_DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read SCO_N_CENTER.
        sItemName = "SCO_N_CENTER";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_N_Center = sItemValue;

        // read SCO_N_COURSE.
        sItemName = "SCO_N_COURSE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_N_Course = sItemValue;

        // read SCO_NUMBER_HOURS.
        sItemName = "SCO_NUMBER_HOURS";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Number_Hours = M4BusinessMethodArg.toDoubleNillable(sItemValue);


    } /* end of method readOperations */


} /* end of class Csp_Formacion_ExternaRecord */

