/**
 * Csp_IdiomasRecord.java
 * Self generated code for Bussines Object CSP_SERVICIO_CV.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_servicio_cv;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Idiomas.
 * @author Meta4
 */
public 
class Csp_IdiomasRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_SERVICIO_CV";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_IDIOMAS";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_IdiomasRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item CSP_TOEIC */
    public Double csp_Toeic = null;
    private void setcsp_Toeic(Double ai_value)
    {
        csp_Toeic = ai_value;
    }
    private Double getcsp_Toeic()
    {
        return csp_Toeic;
    }

    /* item STD_N_LANGUAGE */
    public String std_N_Language = null;
    private void setstd_N_Language(String ai_value)
    {
        std_N_Language = ai_value;
    }
    private String getstd_N_Language()
    {
        return std_N_Language;
    }

    /* item CSP_FECHA_TOEIC */
    public Calendar csp_Fecha_Toeic = null;
    private void setcsp_Fecha_Toeic(Calendar ai_value)
    {
        csp_Fecha_Toeic = ai_value;
    }
    private Calendar getcsp_Fecha_Toeic()
    {
        return csp_Fecha_Toeic;
    }

    /* item STD_ID_LANGUAGE */
    public String std_Id_Language = null;
    private void setstd_Id_Language(String ai_value)
    {
        std_Id_Language = ai_value;
    }
    private String getstd_Id_Language()
    {
        return std_Id_Language;
    }

    /* item STD_N_LANG_LEVEL */
    public String std_N_Lang_Level = null;
    private void setstd_N_Lang_Level(String ai_value)
    {
        std_N_Lang_Level = ai_value;
    }
    private String getstd_N_Lang_Level()
    {
        return std_N_Lang_Level;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // CSP_TOEIC.
        if (csp_Toeic != null)
        {
            htItems.put("CSP_TOEIC", M4BusinessMethodArg.toString(csp_Toeic));
        }
        // STD_N_LANGUAGE.
        if (std_N_Language != null)
        {
            htItems.put("STD_N_LANGUAGE", M4BusinessMethodArg.toString(std_N_Language));
        }
        // CSP_FECHA_TOEIC.
        if (csp_Fecha_Toeic != null)
        {
            htItems.put("CSP_FECHA_TOEIC", M4BusinessMethodArg.toString(csp_Fecha_Toeic));
        }
        // STD_ID_LANGUAGE.
        if (std_Id_Language != null)
        {
            htItems.put("STD_ID_LANGUAGE", M4BusinessMethodArg.toString(std_Id_Language));
        }
        // STD_N_LANG_LEVEL.
        if (std_N_Lang_Level != null)
        {
            htItems.put("STD_N_LANG_LEVEL", M4BusinessMethodArg.toString(std_N_Lang_Level));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read CSP_TOEIC.
        sItemName = "CSP_TOEIC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Toeic = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read STD_N_LANGUAGE.
        sItemName = "STD_N_LANGUAGE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_Language = sItemValue;

        // read CSP_FECHA_TOEIC.
        sItemName = "CSP_FECHA_TOEIC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Fecha_Toeic = M4BusinessMethodArg.toCalendar(sItemValue);

        // read STD_ID_LANGUAGE.
        sItemName = "STD_ID_LANGUAGE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_Id_Language = sItemValue;

        // read STD_N_LANG_LEVEL.
        sItemName = "STD_N_LANG_LEVEL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        std_N_Lang_Level = sItemValue;


    } /* end of method readOperations */


} /* end of class Csp_IdiomasRecord */

