/**
 * Csp_Certificados_CvBlock.java
 * Self generated code for Bussines Object CSP_SERVICIO_CV.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.csp_servicio_cv;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Csp_Certificados_Cv.
 * @author Meta4
 */
public 
class Csp_Certificados_CvBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_SERVICIO_CV";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_CERTIFICADOS_CV";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Certificados_CvBlock.class.getName());

    /* item SCO_ID_HR */
    public String sco_Id_Hr = null;
    private void setsco_Id_Hr(String ai_value)
    {
        sco_Id_Hr = ai_value;
    }
    private String getsco_Id_Hr()
    {
        return sco_Id_Hr;
    }

    /* the recordset */
    public Csp_Certificados_CvRecord[] Csp_Certificados_CvRecordSet = null;
    private void setCsp_Certificados_CvRecordSet(Csp_Certificados_CvRecord[] ai_arg)
    {
        Csp_Certificados_CvRecordSet = ai_arg;
    }
    private Csp_Certificados_CvRecord[] getCsp_Certificados_CvRecordSet()
    {
        return Csp_Certificados_CvRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Csp_Certificados_CvBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // SCO_ID_HR.
        if (sco_Id_Hr != null)
        {
            htItems.put("SCO_ID_HR", M4BusinessMethodArg.toString(sco_Id_Hr));
        }

        // insert 'block scope' values in CSP_CERTIFICADOS_CV.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in CSP_CERTIFICADOS_CV.
        if (Csp_Certificados_CvRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Csp_Certificados_CvRecordSet.length; i++)
        {
            Csp_Certificados_CvRecord record = Csp_Certificados_CvRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in CSP_CERTIFICADOS_CV.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;

        // read SCO_ID_HR.
        sItemName = "SCO_ID_HR";
        nItem = ai_xml.findItem(ai_node, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Hr = sItemValue;

        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Csp_Certificados_CvRecordSet = new Csp_Certificados_CvRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Csp_Certificados_CvRecord record = new Csp_Certificados_CvRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Csp_Certificados_CvRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Csp_Certificados_CvBlock */

