/**
 * T_Aux_File_ManagerBlock.java
 * Self generated code for Bussines Object CSP_SERVICIO_CV.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.csp_servicio_cv;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node T_Aux_File_Manager.
 * @author Meta4
 */
public 
class T_Aux_File_ManagerBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_SERVICIO_CV";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "T_AUX_FILE_MANAGER";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(T_Aux_File_ManagerBlock.class.getName());

    /* item FILE */
    public DataHandler file = null;
    private void setfile(DataHandler ai_value)
    {
        file = ai_value;
    }
    private DataHandler getfile()
    {
        return file;
    }

    /* the recordset */
    public T_Aux_File_ManagerRecord[] T_Aux_File_ManagerRecordSet = null;
    private void setT_Aux_File_ManagerRecordSet(T_Aux_File_ManagerRecord[] ai_arg)
    {
        T_Aux_File_ManagerRecordSet = ai_arg;
    }
    private T_Aux_File_ManagerRecord[] getT_Aux_File_ManagerRecordSet()
    {
        return T_Aux_File_ManagerRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("T_Aux_File_ManagerBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // FILE.
        if ( file != null )
        {
            htBlobs.put("FILE", file.getName());
        }

        // insert 'block scope' values in T_AUX_FILE_MANAGER.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in T_AUX_FILE_MANAGER.
        if (T_Aux_File_ManagerRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<T_Aux_File_ManagerRecordSet.length; i++)
        {
            T_Aux_File_ManagerRecord record = T_Aux_File_ManagerRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in T_AUX_FILE_MANAGER.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;

        // read FILE.
        sItemName = "FILE";
        nItem = ai_xml.findItem(ai_node, sItemName);
        sItemValue = ai_xml.getOptionalAttValue(nItem, "fileindex");
        if (sItemValue != null)
        {
            sItemValue = ai_m4Op.getFileByIndex(Integer.parseInt(sItemValue));
            file = new DataHandler(new M4FileDataSource(sItemValue));
        } 
        else // the case where there is no file in the item
        {
            file = null;
        }



        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        T_Aux_File_ManagerRecordSet = new T_Aux_File_ManagerRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            T_Aux_File_ManagerRecord record = new T_Aux_File_ManagerRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      T_Aux_File_ManagerRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class T_Aux_File_ManagerBlock */

