/**
 * Csp_Numer_ObjBlock.java
 * Self generated code for Bussines Object CSP_NUMER_OBJ.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.csp_numer_obj;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Csp_Numer_Obj.
 * @author Meta4
 */
public 
class Csp_Numer_ObjBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_NUMER_OBJ";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_NUMER_OBJ";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Numer_ObjBlock.class.getName());

    /* item P_STD_ID_HR */
    public String p_Std_Id_Hr = null;
    private void setp_Std_Id_Hr(String ai_value)
    {
        p_Std_Id_Hr = ai_value;
    }
    private String getp_Std_Id_Hr()
    {
        return p_Std_Id_Hr;
    }

    /* the recordset */
    public Csp_Numer_ObjRecord[] Csp_Numer_ObjRecordSet = null;
    private void setCsp_Numer_ObjRecordSet(Csp_Numer_ObjRecord[] ai_arg)
    {
        Csp_Numer_ObjRecordSet = ai_arg;
    }
    private Csp_Numer_ObjRecord[] getCsp_Numer_ObjRecordSet()
    {
        return Csp_Numer_ObjRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Csp_Numer_ObjBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // P_STD_ID_HR.
        if (p_Std_Id_Hr != null)
        {
            htItems.put("P_STD_ID_HR", M4BusinessMethodArg.toString(p_Std_Id_Hr));
        }

        // insert 'block scope' values in CSP_NUMER_OBJ.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in CSP_NUMER_OBJ.
        if (Csp_Numer_ObjRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Csp_Numer_ObjRecordSet.length; i++)
        {
            Csp_Numer_ObjRecord record = Csp_Numer_ObjRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in CSP_NUMER_OBJ.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;

        // read P_STD_ID_HR.
        sItemName = "P_STD_ID_HR";
        nItem = ai_xml.findItem(ai_node, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Std_Id_Hr = sItemValue;

        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Csp_Numer_ObjRecordSet = new Csp_Numer_ObjRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Csp_Numer_ObjRecord record = new Csp_Numer_ObjRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Csp_Numer_ObjRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Csp_Numer_ObjBlock */

