/**
 * Csp_Insert_Obj_EvRecord.java
 * Self generated code for Bussines Object CSP_GUARDAR_OBJ.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_guardar_obj;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Insert_Obj_Ev.
 * @author Meta4
 */
public 
class Csp_Insert_Obj_EvRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_GUARDAR_OBJ";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_INSERT_OBJ_EV";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Insert_Obj_EvRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item CSP_VALUE */
    public Double csp_Value = null;
    private void setcsp_Value(Double ai_value)
    {
        csp_Value = ai_value;
    }
    private Double getcsp_Value()
    {
        return csp_Value;
    }

    /* item CSP_EXPLANATION */
    public String csp_Explanation = null;
    private void setcsp_Explanation(String ai_value)
    {
        csp_Explanation = ai_value;
    }
    private String getcsp_Explanation()
    {
        return csp_Explanation;
    }

    /* item CSP_ID_OBJECTIVE */
    public String csp_Id_Objective = null;
    private void setcsp_Id_Objective(String ai_value)
    {
        csp_Id_Objective = ai_value;
    }
    private String getcsp_Id_Objective()
    {
        return csp_Id_Objective;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // CSP_VALUE.
        if (csp_Value != null)
        {
            htItems.put("CSP_VALUE", M4BusinessMethodArg.toString(csp_Value));
        }
        // CSP_EXPLANATION.
        if (csp_Explanation != null)
        {
            htItems.put("CSP_EXPLANATION", M4BusinessMethodArg.toString(csp_Explanation));
        }
        // CSP_ID_OBJECTIVE.
        if (csp_Id_Objective != null)
        {
            htItems.put("CSP_ID_OBJECTIVE", M4BusinessMethodArg.toString(csp_Id_Objective));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read CSP_VALUE.
        sItemName = "CSP_VALUE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Value = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CSP_EXPLANATION.
        sItemName = "CSP_EXPLANATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Explanation = sItemValue;

        // read CSP_ID_OBJECTIVE.
        sItemName = "CSP_ID_OBJECTIVE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Objective = sItemValue;


    } /* end of method readOperations */


} /* end of class Csp_Insert_Obj_EvRecord */

