/**
 * Csp_Obj_PlanRecord.java
 * Self generated code for Bussines Object CSP_GUARDAR_OBJ.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_guardar_obj;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Obj_Plan.
 * @author Meta4
 */
public 
class Csp_Obj_PlanRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_GUARDAR_OBJ";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_OBJ_PLAN";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Obj_PlanRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item SCO_ID_HR */
    public String sco_Id_Hr = null;
    private void setsco_Id_Hr(String ai_value)
    {
        sco_Id_Hr = ai_value;
    }
    private String getsco_Id_Hr()
    {
        return sco_Id_Hr;
    }

    /* item SCO_WEIGHT */
    public Double sco_Weight = null;
    private void setsco_Weight(Double ai_value)
    {
        sco_Weight = ai_value;
    }
    private Double getsco_Weight()
    {
        return sco_Weight;
    }

    /* item SCO_COMMENT */
    public String sco_Comment = null;
    private void setsco_Comment(String ai_value)
    {
        sco_Comment = ai_value;
    }
    private String getsco_Comment()
    {
        return sco_Comment;
    }

    /* item SCO_DT_START */
    public Calendar sco_Dt_Start = null;
    private void setsco_Dt_Start(Calendar ai_value)
    {
        sco_Dt_Start = ai_value;
    }
    private Calendar getsco_Dt_Start()
    {
        return sco_Dt_Start;
    }

    /* item SCO_ID_LEVEL */
    public String sco_Id_Level = null;
    private void setsco_Id_Level(String ai_value)
    {
        sco_Id_Level = ai_value;
    }
    private String getsco_Id_Level()
    {
        return sco_Id_Level;
    }

    /* item SCO_OR_HR_ROLE */
    public Double sco_Or_Hr_Role = null;
    private void setsco_Or_Hr_Role(Double ai_value)
    {
        sco_Or_Hr_Role = ai_value;
    }
    private Double getsco_Or_Hr_Role()
    {
        return sco_Or_Hr_Role;
    }

    /* item ID_ORGANIZATION */
    public String id_Organization = null;
    private void setid_Organization(String ai_value)
    {
        id_Organization = ai_value;
    }
    private String getid_Organization()
    {
        return id_Organization;
    }

    /* item SCO_ID_OBJECTIVE */
    public String sco_Id_Objective = null;
    private void setsco_Id_Objective(String ai_value)
    {
        sco_Id_Objective = ai_value;
    }
    private String getsco_Id_Objective()
    {
        return sco_Id_Objective;
    }

    /* item SCO_EMPLOYEE_COMM */
    public String sco_Employee_Comm = null;
    private void setsco_Employee_Comm(String ai_value)
    {
        sco_Employee_Comm = ai_value;
    }
    private String getsco_Employee_Comm()
    {
        return sco_Employee_Comm;
    }

    /* item SCO_EMPLOYEE_AGREE */
    public String sco_Employee_Agree = null;
    private void setsco_Employee_Agree(String ai_value)
    {
        sco_Employee_Agree = ai_value;
    }
    private String getsco_Employee_Agree()
    {
        return sco_Employee_Agree;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // SCO_ID_HR.
        if (sco_Id_Hr != null)
        {
            htItems.put("SCO_ID_HR", M4BusinessMethodArg.toString(sco_Id_Hr));
        }
        // SCO_WEIGHT.
        if (sco_Weight != null)
        {
            htItems.put("SCO_WEIGHT", M4BusinessMethodArg.toString(sco_Weight));
        }
        // SCO_COMMENT.
        if (sco_Comment != null)
        {
            htItems.put("SCO_COMMENT", M4BusinessMethodArg.toString(sco_Comment));
        }
        // SCO_DT_START.
        if (sco_Dt_Start != null)
        {
            htItems.put("SCO_DT_START", M4BusinessMethodArg.toString(sco_Dt_Start));
        }
        // SCO_ID_LEVEL.
        if (sco_Id_Level != null)
        {
            htItems.put("SCO_ID_LEVEL", M4BusinessMethodArg.toString(sco_Id_Level));
        }
        // SCO_OR_HR_ROLE.
        if (sco_Or_Hr_Role != null)
        {
            htItems.put("SCO_OR_HR_ROLE", M4BusinessMethodArg.toString(sco_Or_Hr_Role));
        }
        // ID_ORGANIZATION.
        if (id_Organization != null)
        {
            htItems.put("ID_ORGANIZATION", M4BusinessMethodArg.toString(id_Organization));
        }
        // SCO_ID_OBJECTIVE.
        if (sco_Id_Objective != null)
        {
            htItems.put("SCO_ID_OBJECTIVE", M4BusinessMethodArg.toString(sco_Id_Objective));
        }
        // SCO_EMPLOYEE_COMM.
        if (sco_Employee_Comm != null)
        {
            htItems.put("SCO_EMPLOYEE_COMM", M4BusinessMethodArg.toString(sco_Employee_Comm));
        }
        // SCO_EMPLOYEE_AGREE.
        if (sco_Employee_Agree != null)
        {
            htItems.put("SCO_EMPLOYEE_AGREE", M4BusinessMethodArg.toString(sco_Employee_Agree));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read SCO_ID_HR.
        sItemName = "SCO_ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Hr = sItemValue;

        // read SCO_WEIGHT.
        sItemName = "SCO_WEIGHT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Weight = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read SCO_COMMENT.
        sItemName = "SCO_COMMENT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Comment = sItemValue;

        // read SCO_DT_START.
        sItemName = "SCO_DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read SCO_ID_LEVEL.
        sItemName = "SCO_ID_LEVEL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Level = sItemValue;

        // read SCO_OR_HR_ROLE.
        sItemName = "SCO_OR_HR_ROLE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Or_Hr_Role = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read ID_ORGANIZATION.
        sItemName = "ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Organization = sItemValue;

        // read SCO_ID_OBJECTIVE.
        sItemName = "SCO_ID_OBJECTIVE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Id_Objective = sItemValue;

        // read SCO_EMPLOYEE_COMM.
        sItemName = "SCO_EMPLOYEE_COMM";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Employee_Comm = sItemValue;

        // read SCO_EMPLOYEE_AGREE.
        sItemName = "SCO_EMPLOYEE_AGREE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        sco_Employee_Agree = sItemValue;


    } /* end of method readOperations */


} /* end of class Csp_Obj_PlanRecord */

