/**
 * Cyc_Actualizar_EntrevistaRecord.java
 * Self generated code for Bussines Object CYC_MODIFICAR_NOTAS.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_modificar_notas;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Actualizar_Entrevista.
 * @author Meta4
 */
public 
class Cyc_Actualizar_EntrevistaRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_MODIFICAR_NOTAS";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_ACTUALIZAR_ENTREVISTA";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Actualizar_EntrevistaRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item DT_START */
    public Calendar dt_Start = null;
    private void setdt_Start(Calendar ai_value)
    {
        dt_Start = ai_value;
    }
    private Calendar getdt_Start()
    {
        return dt_Start;
    }

    /* item CYC_ID_HR */
    public String cyc_Id_Hr = null;
    private void setcyc_Id_Hr(String ai_value)
    {
        cyc_Id_Hr = ai_value;
    }
    private String getcyc_Id_Hr()
    {
        return cyc_Id_Hr;
    }

    /* item CYC_AUDACIA */
    public Double cyc_Audacia = null;
    private void setcyc_Audacia(Double ai_value)
    {
        cyc_Audacia = ai_value;
    }
    private Double getcyc_Audacia()
    {
        return cyc_Audacia;
    }

    /* item CYC_CARISMA */
    public Double cyc_Carisma = null;
    private void setcyc_Carisma(Double ai_value)
    {
        cyc_Carisma = ai_value;
    }
    private Double getcyc_Carisma()
    {
        return cyc_Carisma;
    }

    /* item CYC_EMPATIA */
    public Double cyc_Empatia = null;
    private void setcyc_Empatia(Double ai_value)
    {
        cyc_Empatia = ai_value;
    }
    private Double getcyc_Empatia()
    {
        return cyc_Empatia;
    }

    /* item CYC_OPTIMISMO */
    public Double cyc_Optimismo = null;
    private void setcyc_Optimismo(Double ai_value)
    {
        cyc_Optimismo = ai_value;
    }
    private Double getcyc_Optimismo()
    {
        return cyc_Optimismo;
    }

    /* item ID_ORGANIZATION */
    public String id_Organization = null;
    private void setid_Organization(String ai_value)
    {
        id_Organization = ai_value;
    }
    private String getid_Organization()
    {
        return id_Organization;
    }

    /* item CYC_CAPAC_APREND */
    public Double cyc_Capac_Aprend = null;
    private void setcyc_Capac_Aprend(Double ai_value)
    {
        cyc_Capac_Aprend = ai_value;
    }
    private Double getcyc_Capac_Aprend()
    {
        return cyc_Capac_Aprend;
    }

    /* item CYC_FEC_ENTREVISTA */
    public Calendar cyc_Fec_Entrevista = null;
    private void setcyc_Fec_Entrevista(Calendar ai_value)
    {
        cyc_Fec_Entrevista = ai_value;
    }
    private Calendar getcyc_Fec_Entrevista()
    {
        return cyc_Fec_Entrevista;
    }

    /* item CYC_RELACIONES_INTERPERS */
    public Double cyc_Relaciones_Interpers = null;
    private void setcyc_Relaciones_Interpers(Double ai_value)
    {
        cyc_Relaciones_Interpers = ai_value;
    }
    private Double getcyc_Relaciones_Interpers()
    {
        return cyc_Relaciones_Interpers;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // DT_START.
        if (dt_Start != null)
        {
            htItems.put("DT_START", M4BusinessMethodArg.toString(dt_Start));
        }
        // CYC_ID_HR.
        if (cyc_Id_Hr != null)
        {
            htItems.put("CYC_ID_HR", M4BusinessMethodArg.toString(cyc_Id_Hr));
        }
        // CYC_AUDACIA.
        if (cyc_Audacia != null)
        {
            htItems.put("CYC_AUDACIA", M4BusinessMethodArg.toString(cyc_Audacia));
        }
        // CYC_CARISMA.
        if (cyc_Carisma != null)
        {
            htItems.put("CYC_CARISMA", M4BusinessMethodArg.toString(cyc_Carisma));
        }
        // CYC_EMPATIA.
        if (cyc_Empatia != null)
        {
            htItems.put("CYC_EMPATIA", M4BusinessMethodArg.toString(cyc_Empatia));
        }
        // CYC_OPTIMISMO.
        if (cyc_Optimismo != null)
        {
            htItems.put("CYC_OPTIMISMO", M4BusinessMethodArg.toString(cyc_Optimismo));
        }
        // ID_ORGANIZATION.
        if (id_Organization != null)
        {
            htItems.put("ID_ORGANIZATION", M4BusinessMethodArg.toString(id_Organization));
        }
        // CYC_CAPAC_APREND.
        if (cyc_Capac_Aprend != null)
        {
            htItems.put("CYC_CAPAC_APREND", M4BusinessMethodArg.toString(cyc_Capac_Aprend));
        }
        // CYC_FEC_ENTREVISTA.
        if (cyc_Fec_Entrevista != null)
        {
            htItems.put("CYC_FEC_ENTREVISTA", M4BusinessMethodArg.toString(cyc_Fec_Entrevista));
        }
        // CYC_RELACIONES_INTERPERS.
        if (cyc_Relaciones_Interpers != null)
        {
            htItems.put("CYC_RELACIONES_INTERPERS", M4BusinessMethodArg.toString(cyc_Relaciones_Interpers));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read DT_START.
        sItemName = "DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_ID_HR.
        sItemName = "CYC_ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Hr = sItemValue;

        // read CYC_AUDACIA.
        sItemName = "CYC_AUDACIA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Audacia = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_CARISMA.
        sItemName = "CYC_CARISMA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Carisma = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_EMPATIA.
        sItemName = "CYC_EMPATIA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Empatia = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_OPTIMISMO.
        sItemName = "CYC_OPTIMISMO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Optimismo = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read ID_ORGANIZATION.
        sItemName = "ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Organization = sItemValue;

        // read CYC_CAPAC_APREND.
        sItemName = "CYC_CAPAC_APREND";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Capac_Aprend = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_FEC_ENTREVISTA.
        sItemName = "CYC_FEC_ENTREVISTA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Fec_Entrevista = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_RELACIONES_INTERPERS.
        sItemName = "CYC_RELACIONES_INTERPERS";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Relaciones_Interpers = M4BusinessMethodArg.toDoubleNillable(sItemValue);


    } /* end of method readOperations */


} /* end of class Cyc_Actualizar_EntrevistaRecord */

