/**
 * Cyc_Actualizar_Fase_IiiRecord.java
 * Self generated code for Bussines Object CYC_MODIFICAR_NOTAS.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_modificar_notas;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Actualizar_Fase_Iii.
 * @author Meta4
 */
public 
class Cyc_Actualizar_Fase_IiiRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_MODIFICAR_NOTAS";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_ACTUALIZAR_FASE_III";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Actualizar_Fase_IiiRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item DT_START */
    public Calendar dt_Start = null;
    private void setdt_Start(Calendar ai_value)
    {
        dt_Start = ai_value;
    }
    private Calendar getdt_Start()
    {
        return dt_Start;
    }

    /* item CYC_ID_HR */
    public String cyc_Id_Hr = null;
    private void setcyc_Id_Hr(String ai_value)
    {
        cyc_Id_Hr = ai_value;
    }
    private String getcyc_Id_Hr()
    {
        return cyc_Id_Hr;
    }

    /* item ID_ORGANIZATION */
    public String id_Organization = null;
    private void setid_Organization(String ai_value)
    {
        id_Organization = ai_value;
    }
    private String getid_Organization()
    {
        return id_Organization;
    }

    /* item CYC_ORIENT_RTDOS_F3 */
    public Double cyc_Orient_Rtdos_F3 = null;
    private void setcyc_Orient_Rtdos_F3(Double ai_value)
    {
        cyc_Orient_Rtdos_F3 = ai_value;
    }
    private Double getcyc_Orient_Rtdos_F3()
    {
        return cyc_Orient_Rtdos_F3;
    }

    /* item CYC_COMUN_IMP_INF_F3 */
    public Double cyc_Comun_Imp_Inf_F3 = null;
    private void setcyc_Comun_Imp_Inf_F3(Double ai_value)
    {
        cyc_Comun_Imp_Inf_F3 = ai_value;
    }
    private Double getcyc_Comun_Imp_Inf_F3()
    {
        return cyc_Comun_Imp_Inf_F3;
    }

    /* item CYC_CAPAC_ANALITIC_F3 */
    public Double cyc_Capac_Analitic_F3 = null;
    private void setcyc_Capac_Analitic_F3(Double ai_value)
    {
        cyc_Capac_Analitic_F3 = ai_value;
    }
    private Double getcyc_Capac_Analitic_F3()
    {
        return cyc_Capac_Analitic_F3;
    }

    /* item CYC_LIDER_DIR_EQUIP_F3 */
    public Double cyc_Lider_Dir_Equip_F3 = null;
    private void setcyc_Lider_Dir_Equip_F3(Double ai_value)
    {
        cyc_Lider_Dir_Equip_F3 = ai_value;
    }
    private Double getcyc_Lider_Dir_Equip_F3()
    {
        return cyc_Lider_Dir_Equip_F3;
    }

    /* item CYC_VISION_GBAL_EST_F3 */
    public Double cyc_Vision_Gbal_Est_F3 = null;
    private void setcyc_Vision_Gbal_Est_F3(Double ai_value)
    {
        cyc_Vision_Gbal_Est_F3 = ai_value;
    }
    private Double getcyc_Vision_Gbal_Est_F3()
    {
        return cyc_Vision_Gbal_Est_F3;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // DT_START.
        if (dt_Start != null)
        {
            htItems.put("DT_START", M4BusinessMethodArg.toString(dt_Start));
        }
        // CYC_ID_HR.
        if (cyc_Id_Hr != null)
        {
            htItems.put("CYC_ID_HR", M4BusinessMethodArg.toString(cyc_Id_Hr));
        }
        // ID_ORGANIZATION.
        if (id_Organization != null)
        {
            htItems.put("ID_ORGANIZATION", M4BusinessMethodArg.toString(id_Organization));
        }
        // CYC_ORIENT_RTDOS_F3.
        if (cyc_Orient_Rtdos_F3 != null)
        {
            htItems.put("CYC_ORIENT_RTDOS_F3", M4BusinessMethodArg.toString(cyc_Orient_Rtdos_F3));
        }
        // CYC_COMUN_IMP_INF_F3.
        if (cyc_Comun_Imp_Inf_F3 != null)
        {
            htItems.put("CYC_COMUN_IMP_INF_F3", M4BusinessMethodArg.toString(cyc_Comun_Imp_Inf_F3));
        }
        // CYC_CAPAC_ANALITIC_F3.
        if (cyc_Capac_Analitic_F3 != null)
        {
            htItems.put("CYC_CAPAC_ANALITIC_F3", M4BusinessMethodArg.toString(cyc_Capac_Analitic_F3));
        }
        // CYC_LIDER_DIR_EQUIP_F3.
        if (cyc_Lider_Dir_Equip_F3 != null)
        {
            htItems.put("CYC_LIDER_DIR_EQUIP_F3", M4BusinessMethodArg.toString(cyc_Lider_Dir_Equip_F3));
        }
        // CYC_VISION_GBAL_EST_F3.
        if (cyc_Vision_Gbal_Est_F3 != null)
        {
            htItems.put("CYC_VISION_GBAL_EST_F3", M4BusinessMethodArg.toString(cyc_Vision_Gbal_Est_F3));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read DT_START.
        sItemName = "DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_ID_HR.
        sItemName = "CYC_ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Hr = sItemValue;

        // read ID_ORGANIZATION.
        sItemName = "ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Organization = sItemValue;

        // read CYC_ORIENT_RTDOS_F3.
        sItemName = "CYC_ORIENT_RTDOS_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Orient_Rtdos_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_COMUN_IMP_INF_F3.
        sItemName = "CYC_COMUN_IMP_INF_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Comun_Imp_Inf_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_CAPAC_ANALITIC_F3.
        sItemName = "CYC_CAPAC_ANALITIC_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Capac_Analitic_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_LIDER_DIR_EQUIP_F3.
        sItemName = "CYC_LIDER_DIR_EQUIP_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Lider_Dir_Equip_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_VISION_GBAL_EST_F3.
        sItemName = "CYC_VISION_GBAL_EST_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Vision_Gbal_Est_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);


    } /* end of method readOperations */


} /* end of class Cyc_Actualizar_Fase_IiiRecord */

