/**
 * Cyc_Modificar_Fase_IiRecord.java
 * Self generated code for Bussines Object CYC_MODIFICAR_NOTAS.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_modificar_notas;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Modificar_Fase_Ii.
 * @author Meta4
 */
public 
class Cyc_Modificar_Fase_IiRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_MODIFICAR_NOTAS";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_MODIFICAR_FASE_II";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Modificar_Fase_IiRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item P_AUDACIA */
    public Double p_Audacia = null;
    private void setp_Audacia(Double ai_value)
    {
        p_Audacia = ai_value;
    }
    private Double getp_Audacia()
    {
        return p_Audacia;
    }

    /* item P_CARISMA */
    public Double p_Carisma = null;
    private void setp_Carisma(Double ai_value)
    {
        p_Carisma = ai_value;
    }
    private Double getp_Carisma()
    {
        return p_Carisma;
    }

    /* item P_EMPATIA */
    public Double p_Empatia = null;
    private void setp_Empatia(Double ai_value)
    {
        p_Empatia = ai_value;
    }
    private Double getp_Empatia()
    {
        return p_Empatia;
    }

    /* item P_OPTIMISMO */
    public Double p_Optimismo = null;
    private void setp_Optimismo(Double ai_value)
    {
        p_Optimismo = ai_value;
    }
    private Double getp_Optimismo()
    {
        return p_Optimismo;
    }

    /* item P_COMP_IMPLI */
    public Double p_Comp_Impli = null;
    private void setp_Comp_Impli(Double ai_value)
    {
        p_Comp_Impli = ai_value;
    }
    private Double getp_Comp_Impli()
    {
        return p_Comp_Impli;
    }

    /* item P_TOMA_DECIS */
    public Double p_Toma_Decis = null;
    private void setp_Toma_Decis(Double ai_value)
    {
        p_Toma_Decis = ai_value;
    }
    private Double getp_Toma_Decis()
    {
        return p_Toma_Decis;
    }

    /* item P_DESA_PERSON */
    public Double p_Desa_Person = null;
    private void setp_Desa_Person(Double ai_value)
    {
        p_Desa_Person = ai_value;
    }
    private Double getp_Desa_Person()
    {
        return p_Desa_Person;
    }

    /* item P_MEJORA_CONT */
    public Double p_Mejora_Cont = null;
    private void setp_Mejora_Cont(Double ai_value)
    {
        p_Mejora_Cont = ai_value;
    }
    private Double getp_Mejora_Cont()
    {
        return p_Mejora_Cont;
    }

    /* item P_ORIENT_CAMB */
    public Double p_Orient_Camb = null;
    private void setp_Orient_Camb(Double ai_value)
    {
        p_Orient_Camb = ai_value;
    }
    private Double getp_Orient_Camb()
    {
        return p_Orient_Camb;
    }

    /* item P_TRAB_EQUIPO */
    public Double p_Trab_Equipo = null;
    private void setp_Trab_Equipo(Double ai_value)
    {
        p_Trab_Equipo = ai_value;
    }
    private Double getp_Trab_Equipo()
    {
        return p_Trab_Equipo;
    }

    /* item P_CAPAC_APREND */
    public Double p_Capac_Aprend = null;
    private void setp_Capac_Aprend(Double ai_value)
    {
        p_Capac_Aprend = ai_value;
    }
    private Double getp_Capac_Aprend()
    {
        return p_Capac_Aprend;
    }

    /* item P_COMUNICACION */
    public Double p_Comunicacion = null;
    private void setp_Comunicacion(Double ai_value)
    {
        p_Comunicacion = ai_value;
    }
    private Double getp_Comunicacion()
    {
        return p_Comunicacion;
    }

    /* item P_FLEXIBILIDAD */
    public Double p_Flexibilidad = null;
    private void setp_Flexibilidad(Double ai_value)
    {
        p_Flexibilidad = ai_value;
    }
    private Double getp_Flexibilidad()
    {
        return p_Flexibilidad;
    }

    /* item P_AUTOCONFIANZA */
    public Double p_Autoconfianza = null;
    private void setp_Autoconfianza(Double ai_value)
    {
        p_Autoconfianza = ai_value;
    }
    private Double getp_Autoconfianza()
    {
        return p_Autoconfianza;
    }

    /* item P_DIREC_EQUIPOS */
    public Double p_Direc_Equipos = null;
    private void setp_Direc_Equipos(Double ai_value)
    {
        p_Direc_Equipos = ai_value;
    }
    private Double getp_Direc_Equipos()
    {
        return p_Direc_Equipos;
    }

    /* item P_ORIENT_CLIENT */
    public Double p_Orient_Client = null;
    private void setp_Orient_Client(Double ai_value)
    {
        p_Orient_Client = ai_value;
    }
    private Double getp_Orient_Client()
    {
        return p_Orient_Client;
    }

    /* item P_ORIENT_RESULT */
    public Double p_Orient_Result = null;
    private void setp_Orient_Result(Double ai_value)
    {
        p_Orient_Result = ai_value;
    }
    private Double getp_Orient_Result()
    {
        return p_Orient_Result;
    }

    /* item P_CAPAC_ANALITIC */
    public Double p_Capac_Analitic = null;
    private void setp_Capac_Analitic(Double ai_value)
    {
        p_Capac_Analitic = ai_value;
    }
    private Double getp_Capac_Analitic()
    {
        return p_Capac_Analitic;
    }

    /* item P_PLANIF_ORGANIZ */
    public Double p_Planif_Organiz = null;
    private void setp_Planif_Organiz(Double ai_value)
    {
        p_Planif_Organiz = ai_value;
    }
    private Double getp_Planif_Organiz()
    {
        return p_Planif_Organiz;
    }

    /* item P_VISION_GBAL_EST */
    public Double p_Vision_Gbal_Est = null;
    private void setp_Vision_Gbal_Est(Double ai_value)
    {
        p_Vision_Gbal_Est = ai_value;
    }
    private Double getp_Vision_Gbal_Est()
    {
        return p_Vision_Gbal_Est;
    }

    /* item P_RELACIONES_INTERPERS */
    public Double p_Relaciones_Interpers = null;
    private void setp_Relaciones_Interpers(Double ai_value)
    {
        p_Relaciones_Interpers = ai_value;
    }
    private Double getp_Relaciones_Interpers()
    {
        return p_Relaciones_Interpers;
    }

    /* node CYC_ACTUALIZAR_FASE_II */
    public Cyc_Actualizar_Fase_IiBlock Cyc_Actualizar_Fase_Ii = null;
    private void setcyc_Actualizar_Fase_Ii(Cyc_Actualizar_Fase_IiBlock ai_value)
    {
        Cyc_Actualizar_Fase_Ii = ai_value;
    }
    private Cyc_Actualizar_Fase_IiBlock getCyc_Actualizar_Fase_Ii()
    {
        return Cyc_Actualizar_Fase_Ii;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // P_AUDACIA.
        if (p_Audacia != null)
        {
            htItems.put("P_AUDACIA", M4BusinessMethodArg.toString(p_Audacia));
        }
        // P_CARISMA.
        if (p_Carisma != null)
        {
            htItems.put("P_CARISMA", M4BusinessMethodArg.toString(p_Carisma));
        }
        // P_EMPATIA.
        if (p_Empatia != null)
        {
            htItems.put("P_EMPATIA", M4BusinessMethodArg.toString(p_Empatia));
        }
        // P_OPTIMISMO.
        if (p_Optimismo != null)
        {
            htItems.put("P_OPTIMISMO", M4BusinessMethodArg.toString(p_Optimismo));
        }
        // P_COMP_IMPLI.
        if (p_Comp_Impli != null)
        {
            htItems.put("P_COMP_IMPLI", M4BusinessMethodArg.toString(p_Comp_Impli));
        }
        // P_TOMA_DECIS.
        if (p_Toma_Decis != null)
        {
            htItems.put("P_TOMA_DECIS", M4BusinessMethodArg.toString(p_Toma_Decis));
        }
        // P_DESA_PERSON.
        if (p_Desa_Person != null)
        {
            htItems.put("P_DESA_PERSON", M4BusinessMethodArg.toString(p_Desa_Person));
        }
        // P_MEJORA_CONT.
        if (p_Mejora_Cont != null)
        {
            htItems.put("P_MEJORA_CONT", M4BusinessMethodArg.toString(p_Mejora_Cont));
        }
        // P_ORIENT_CAMB.
        if (p_Orient_Camb != null)
        {
            htItems.put("P_ORIENT_CAMB", M4BusinessMethodArg.toString(p_Orient_Camb));
        }
        // P_TRAB_EQUIPO.
        if (p_Trab_Equipo != null)
        {
            htItems.put("P_TRAB_EQUIPO", M4BusinessMethodArg.toString(p_Trab_Equipo));
        }
        // P_CAPAC_APREND.
        if (p_Capac_Aprend != null)
        {
            htItems.put("P_CAPAC_APREND", M4BusinessMethodArg.toString(p_Capac_Aprend));
        }
        // P_COMUNICACION.
        if (p_Comunicacion != null)
        {
            htItems.put("P_COMUNICACION", M4BusinessMethodArg.toString(p_Comunicacion));
        }
        // P_FLEXIBILIDAD.
        if (p_Flexibilidad != null)
        {
            htItems.put("P_FLEXIBILIDAD", M4BusinessMethodArg.toString(p_Flexibilidad));
        }
        // P_AUTOCONFIANZA.
        if (p_Autoconfianza != null)
        {
            htItems.put("P_AUTOCONFIANZA", M4BusinessMethodArg.toString(p_Autoconfianza));
        }
        // P_DIREC_EQUIPOS.
        if (p_Direc_Equipos != null)
        {
            htItems.put("P_DIREC_EQUIPOS", M4BusinessMethodArg.toString(p_Direc_Equipos));
        }
        // P_ORIENT_CLIENT.
        if (p_Orient_Client != null)
        {
            htItems.put("P_ORIENT_CLIENT", M4BusinessMethodArg.toString(p_Orient_Client));
        }
        // P_ORIENT_RESULT.
        if (p_Orient_Result != null)
        {
            htItems.put("P_ORIENT_RESULT", M4BusinessMethodArg.toString(p_Orient_Result));
        }
        // P_CAPAC_ANALITIC.
        if (p_Capac_Analitic != null)
        {
            htItems.put("P_CAPAC_ANALITIC", M4BusinessMethodArg.toString(p_Capac_Analitic));
        }
        // P_PLANIF_ORGANIZ.
        if (p_Planif_Organiz != null)
        {
            htItems.put("P_PLANIF_ORGANIZ", M4BusinessMethodArg.toString(p_Planif_Organiz));
        }
        // P_VISION_GBAL_EST.
        if (p_Vision_Gbal_Est != null)
        {
            htItems.put("P_VISION_GBAL_EST", M4BusinessMethodArg.toString(p_Vision_Gbal_Est));
        }
        // P_RELACIONES_INTERPERS.
        if (p_Relaciones_Interpers != null)
        {
            htItems.put("P_RELACIONES_INTERPERS", M4BusinessMethodArg.toString(p_Relaciones_Interpers));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

        // write data for node CYC_ACTUALIZAR_FASE_II.
        if ( Cyc_Actualizar_Fase_Ii != null) 
        {
           Cyc_Actualizar_Fase_Ii.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read P_AUDACIA.
        sItemName = "P_AUDACIA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Audacia = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_CARISMA.
        sItemName = "P_CARISMA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Carisma = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_EMPATIA.
        sItemName = "P_EMPATIA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Empatia = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_OPTIMISMO.
        sItemName = "P_OPTIMISMO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Optimismo = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_COMP_IMPLI.
        sItemName = "P_COMP_IMPLI";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Comp_Impli = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_TOMA_DECIS.
        sItemName = "P_TOMA_DECIS";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Toma_Decis = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_DESA_PERSON.
        sItemName = "P_DESA_PERSON";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Desa_Person = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_MEJORA_CONT.
        sItemName = "P_MEJORA_CONT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Mejora_Cont = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_ORIENT_CAMB.
        sItemName = "P_ORIENT_CAMB";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Orient_Camb = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_TRAB_EQUIPO.
        sItemName = "P_TRAB_EQUIPO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Trab_Equipo = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_CAPAC_APREND.
        sItemName = "P_CAPAC_APREND";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Capac_Aprend = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_COMUNICACION.
        sItemName = "P_COMUNICACION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Comunicacion = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_FLEXIBILIDAD.
        sItemName = "P_FLEXIBILIDAD";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Flexibilidad = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_AUTOCONFIANZA.
        sItemName = "P_AUTOCONFIANZA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Autoconfianza = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_DIREC_EQUIPOS.
        sItemName = "P_DIREC_EQUIPOS";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Direc_Equipos = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_ORIENT_CLIENT.
        sItemName = "P_ORIENT_CLIENT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Orient_Client = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_ORIENT_RESULT.
        sItemName = "P_ORIENT_RESULT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Orient_Result = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_CAPAC_ANALITIC.
        sItemName = "P_CAPAC_ANALITIC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Capac_Analitic = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_PLANIF_ORGANIZ.
        sItemName = "P_PLANIF_ORGANIZ";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Planif_Organiz = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_VISION_GBAL_EST.
        sItemName = "P_VISION_GBAL_EST";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Vision_Gbal_Est = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read P_RELACIONES_INTERPERS.
        sItemName = "P_RELACIONES_INTERPERS";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Relaciones_Interpers = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read data for node CYC_ACTUALIZAR_FASE_II.
        Cyc_Actualizar_Fase_Ii = new Cyc_Actualizar_Fase_IiBlock();
        Cyc_Actualizar_Fase_Ii.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_Actualizar_Fase_IiBlock.NODE_NAME));


    } /* end of method readOperations */


} /* end of class Cyc_Modificar_Fase_IiRecord */

