import type { HireExtraFields } from "./types";

/** Minimal valid branches for tests; individual tests override relevant cells. */
export const hireExtraFixture = {
  positionChoice: "job",
  occupationType: "",
  legalRepresentativeNif: "",
  birthDate: "",
  atradiusId: "",
  phonePrefix: "",
  phoneNumber: "",
  mobilePrefix: "",
  mobileNumber: "",
  addressLine1: "Calle Ejemplo",
  addressLine2: "",
  streetNumber: "1",
  buildingBlock: "",
  staircase: "",
  floor: "",
  door: "",
  postalCode: "28001",
  occupationHours: "",
  occupationEjc: "",
  occupationHeadcount: "",
  keyEmployee: false,
  strategicEmployee: false,
  ssNumberChoice: "unassigned",
  ssNumberPrefix: "",
  ssNumberBody: "",
  ssNumberSuffix: "",
  contractEnd: "",
  scheduleChoice: "full",
  partialSchedulePercent: "",
  hourType: "",
  numberOfHours: "",
  partialScheduleType: "",
  weeklyWorkDays: "",
  legalReductionPercent: "",
  replacedSsPrefix: "",
  replacedSsBody: "",
  replacedSsSuffix: "",
  disabilityChoice: "without",
  disabilityPercent: "",
  contractSeniorityStart: "",
  womanMaternity24: false,
  underrepresentedWoman: false,
  activeInsertionIncome: false,
  reliefContract: false,
  readmittedDisabled: false,
  firstSelfEmployedWorker: false,
  probationDays: "",
  probationEnd: "",
  additionalClause: "",
  annualGross: "",
  seniorityDate: "",
  timeManagementPay: false,
  bankFormatChoice: "iban",
  iban: "ES5200491500061234567890",
  bankBranch: "",
  accountNumber: "",
} as const satisfies HireExtraFields;
