import type { PayrollReceipt } from "@/types/payroll-receipt";

/** Recibo de ejemplo con importes de una paga real de CYC y datos personales ficticios. */
export const sampleReceipt: PayrollReceipt = {
  currencyId: "EUR",
  company: { name: "ACYC España", taxId: "A28008795", socialSecurityRegistration: "28000618251" },
  periodLabel: "Del 1 al 30 Abril 2026",
  worker: {
    employeeId: "1013",
    fullName: "Ana Pérez Gómez",
    nationalId: "00000000T",
    socialSecurityNumber: "280000000000",
    contributionGroup: "1",
  },
  workCenter: "Madrid - Mendez Álvaro",
  professionalGroup: "Grupo I – Nivel 1",
  seniorityDate: "2004-03-01",
  lines: [
    {
      id: "salario-base",
      section: "concept",
      level: 0,
      concept: "Salario Base",
      units: 1,
      unitsFormat: "decimal",
      price: 2606.04,
      percentage: null,
      earning: 2606.04,
      deduction: null,
    },
    {
      id: "irpf",
      section: "concept",
      level: 0,
      concept: "Retención a Cuenta del IRPF",
      units: 34.16,
      unitsFormat: "percentage",
      price: 7735.57,
      percentage: null,
      earning: null,
      deduction: 2642.47,
    },
    {
      id: "coste-empresa",
      section: "informative",
      level: 0,
      concept: "Coste Empresa",
      units: null,
      unitsFormat: "decimal",
      price: null,
      percentage: null,
      earning: null,
      deduction: 1708.71,
    },
    {
      id: "cc-empresa",
      section: "informative",
      level: 1,
      concept: "Cotiz. Contingencias Comunes Empresa",
      units: null,
      unitsFormat: "decimal",
      price: null,
      percentage: null,
      earning: null,
      deduction: 1203.88,
    },
  ],
  bases: {
    totalRemuneration: 11139.86,
    extraPayProration: 0,
    totalBase: 11139.86,
    generalRegimeBase: 5101.2,
    unemploymentBase: 5101.2,
  },
  totals: { accrued: 7809.85, deducted: 3287.5, netPay: 4522.35 },
  accumulated: { irpfBase: 59385.01, irpfQuota: 20151.2, socialSecurityQuota: 1295.72 },
  bankPayments: [{ account: "ES00 0000 0000 0000 0000 0001", amount: 4522.35 }],
  beneficiaryPayments: [],
  unmapped: { accrued: 0, deducted: 0 },
};
