/**
 * Csp_Ult_ProBlock.java
 * Self generated code for Bussines Object CSP_ESTADO_PROC.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */
package com.meta4.soapservices.services.rpc.csp_estado_proc;

import org.w3c.dom.Node;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;


/**
 * Bean for node Csp_Ult_Pro.
 * @author Meta4
 */
public 
class Csp_Ult_ProBlock 
{
    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_ESTADO_PROC";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_ULT_PRO";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Ult_ProBlock.class.getName());

    /* item P_SOC */
    public String p_Soc = null;
    private void setp_Soc(String ai_value)
    {
        p_Soc = ai_value;
    }
    private String getp_Soc()
    {
        return p_Soc;
    }

    /* the recordset */
    public Csp_Ult_ProRecord[] Csp_Ult_ProRecordSet = null;
    private void setCsp_Ult_ProRecordSet(Csp_Ult_ProRecord[] ai_arg)
    {
        Csp_Ult_ProRecordSet = ai_arg;
    }
    private Csp_Ult_ProRecord[] getCsp_Ult_ProRecordSet()
    {
        return Csp_Ult_ProRecordSet;
    }

    /**
     *
     */
    void 
    writeOperations(M4SoapOperations ai_m4Op) 
    throws Exception
    {
        m_log.debug("Csp_Ult_ProBlock.writeOperations(...)");

        // items 'block' scope.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // P_SOC.
        if (p_Soc != null)
        {
            htItems.put("P_SOC", M4BusinessMethodArg.toString(p_Soc));
        }

        // insert 'block scope' values in CSP_ULT_PRO.
        ai_m4Op.setNodeItems(M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);

        // insert 'record scope' values in CSP_ULT_PRO.
        if (Csp_Ult_ProRecordSet==null)
        {
            throw M4SoapException.makeException("NULL input value for recordset in node \"" + NODE_NAME + "\".");
        }
        for (int i=0; i<Csp_Ult_ProRecordSet.length; i++)
        {
            Csp_Ult_ProRecord record = Csp_Ult_ProRecordSet[i];
            if (record==null)
            {
                throw M4SoapException.makeException("NULL input value for record[" + i + "] in node \"" + NODE_NAME + "\".");
            }
                        
            record.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void 
    readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_node) 
    throws Exception
    {
        // read 'block scope' values in CSP_ULT_PRO.
        String sItemName = null;
        String sItemValue = null;
        Node nItem = null;

        // read P_SOC.
        sItemName = "P_SOC";
        nItem = ai_xml.findItem(ai_node, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Soc = sItemValue;

        // create recordset.
        int iRecordNumber = ai_xml.countRecords(ai_node);
        Csp_Ult_ProRecordSet = new Csp_Ult_ProRecord[iRecordNumber];
        
        // read records.
        for (int i=0; i<iRecordNumber; i++)
        {
            Node nRecord = ai_xml.findRecord(ai_node, Integer.toString(i));
            
      	    String sRecordID = ai_xml.getAttValue(nRecord, "id");

            Csp_Ult_ProRecord record = new Csp_Ult_ProRecord();
                      
			      record.m4AutoGeneratedRecordID = sRecordID;
			
            record.readOperations(ai_m4Op, ai_xml, nRecord);
            
			      Csp_Ult_ProRecordSet[i] = record;
        }


    } /* end of method readOperations */



} /* end of class Csp_Ult_ProBlock */

