/**
 * Csp_Estado_EvalRecord.java
 * Self generated code for Bussines Object CSP_ESTADO_PROC.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_estado_proc;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Estado_Eval.
 * @author Meta4
 */
public 
class Csp_Estado_EvalRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_ESTADO_PROC";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_ESTADO_EVAL";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Estado_EvalRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item CSP_TIPO */
    public String csp_Tipo = null;
    private void setcsp_Tipo(String ai_value)
    {
        csp_Tipo = ai_value;
    }
    private String getcsp_Tipo()
    {
        return csp_Tipo;
    }

    /* item CSP_ID_HR */
    public String csp_Id_Hr = null;
    private void setcsp_Id_Hr(String ai_value)
    {
        csp_Id_Hr = ai_value;
    }
    private String getcsp_Id_Hr()
    {
        return csp_Id_Hr;
    }

    /* item CSP_DT_END */
    public Calendar csp_Dt_End = null;
    private void setcsp_Dt_End(Calendar ai_value)
    {
        csp_Dt_End = ai_value;
    }
    private Calendar getcsp_Dt_End()
    {
        return csp_Dt_End;
    }

    /* item CSP_ESTADO */
    public Double csp_Estado = null;
    private void setcsp_Estado(Double ai_value)
    {
        csp_Estado = ai_value;
    }
    private Double getcsp_Estado()
    {
        return csp_Estado;
    }

    /* item CSP_COMMENT */
    public String csp_Comment = null;
    private void setcsp_Comment(String ai_value)
    {
        csp_Comment = ai_value;
    }
    private String getcsp_Comment()
    {
        return csp_Comment;
    }

    /* item CSP_CALCUL_CAP */
    public Double csp_Calcul_Cap = null;
    private void setcsp_Calcul_Cap(Double ai_value)
    {
        csp_Calcul_Cap = ai_value;
    }
    private Double getcsp_Calcul_Cap()
    {
        return csp_Calcul_Cap;
    }

    /* item CSP_DT_END_SEG */
    public Calendar csp_Dt_End_Seg = null;
    private void setcsp_Dt_End_Seg(Calendar ai_value)
    {
        csp_Dt_End_Seg = ai_value;
    }
    private Calendar getcsp_Dt_End_Seg()
    {
        return csp_Dt_End_Seg;
    }

    /* item CSP_OR_HR_ROLE */
    public Double csp_Or_Hr_Role = null;
    private void setcsp_Or_Hr_Role(Double ai_value)
    {
        csp_Or_Hr_Role = ai_value;
    }
    private Double getcsp_Or_Hr_Role()
    {
        return csp_Or_Hr_Role;
    }

    /* item CSP_ID_JOB_CODE */
    public String csp_Id_Job_Code = null;
    private void setcsp_Id_Job_Code(String ai_value)
    {
        csp_Id_Job_Code = ai_value;
    }
    private String getcsp_Id_Job_Code()
    {
        return csp_Id_Job_Code;
    }

    /* item CSP_ID_EVAL_PLAN */
    public String csp_Id_Eval_Plan = null;
    private void setcsp_Id_Eval_Plan(String ai_value)
    {
        csp_Id_Eval_Plan = ai_value;
    }
    private String getcsp_Id_Eval_Plan()
    {
        return csp_Id_Eval_Plan;
    }

    /* item CSP_ID_LEVEL_CAP */
    public String csp_Id_Level_Cap = null;
    private void setcsp_Id_Level_Cap(String ai_value)
    {
        csp_Id_Level_Cap = ai_value;
    }
    private String getcsp_Id_Level_Cap()
    {
        return csp_Id_Level_Cap;
    }

    /* item CSP_ID_LEVEL_OBJ */
    public String csp_Id_Level_Obj = null;
    private void setcsp_Id_Level_Obj(String ai_value)
    {
        csp_Id_Level_Obj = ai_value;
    }
    private String getcsp_Id_Level_Obj()
    {
        return csp_Id_Level_Obj;
    }

    /* item CSP_DT_LIMIT_EVAL */
    public Calendar csp_Dt_Limit_Eval = null;
    private void setcsp_Dt_Limit_Eval(Calendar ai_value)
    {
        csp_Dt_Limit_Eval = ai_value;
    }
    private Calendar getcsp_Dt_Limit_Eval()
    {
        return csp_Dt_Limit_Eval;
    }

    /* item CSP_DT_START_EVAL */
    public Calendar csp_Dt_Start_Eval = null;
    private void setcsp_Dt_Start_Eval(Calendar ai_value)
    {
        csp_Dt_Start_Eval = ai_value;
    }
    private Calendar getcsp_Dt_Start_Eval()
    {
        return csp_Dt_Start_Eval;
    }

    /* item CSP_DT_START_PROC */
    public Calendar csp_Dt_Start_Proc = null;
    private void setcsp_Dt_Start_Proc(Calendar ai_value)
    {
        csp_Dt_Start_Proc = ai_value;
    }
    private Calendar getcsp_Dt_Start_Proc()
    {
        return csp_Dt_Start_Proc;
    }

    /* item CSP_ID_SUPERVISOR */
    public String csp_Id_Supervisor = null;
    private void setcsp_Id_Supervisor(String ai_value)
    {
        csp_Id_Supervisor = ai_value;
    }
    private String getcsp_Id_Supervisor()
    {
        return csp_Id_Supervisor;
    }

    /* item CSP_OR_SUPERVISOR */
    public Double csp_Or_Supervisor = null;
    private void setcsp_Or_Supervisor(Double ai_value)
    {
        csp_Or_Supervisor = ai_value;
    }
    private Double getcsp_Or_Supervisor()
    {
        return csp_Or_Supervisor;
    }

    /* item CSP_SUPERVIS_COMM */
    public String csp_Supervis_Comm = null;
    private void setcsp_Supervis_Comm(String ai_value)
    {
        csp_Supervis_Comm = ai_value;
    }
    private String getcsp_Supervis_Comm()
    {
        return csp_Supervis_Comm;
    }

    /* item CSP_ID_EMMITED_CAP */
    public String csp_Id_Emmited_Cap = null;
    private void setcsp_Id_Emmited_Cap(String ai_value)
    {
        csp_Id_Emmited_Cap = ai_value;
    }
    private String getcsp_Id_Emmited_Cap()
    {
        return csp_Id_Emmited_Cap;
    }

    /* item CSP_ID_EMMITED_OBJ */
    public String csp_Id_Emmited_Obj = null;
    private void setcsp_Id_Emmited_Obj(String ai_value)
    {
        csp_Id_Emmited_Obj = ai_value;
    }
    private String getcsp_Id_Emmited_Obj()
    {
        return csp_Id_Emmited_Obj;
    }

    /* item CSP_VALUE_OBJ_QUANT */
    public Double csp_Value_Obj_Quant = null;
    private void setcsp_Value_Obj_Quant(Double ai_value)
    {
        csp_Value_Obj_Quant = ai_value;
    }
    private Double getcsp_Value_Obj_Quant()
    {
        return csp_Value_Obj_Quant;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // CSP_TIPO.
        if (csp_Tipo != null)
        {
            htItems.put("CSP_TIPO", M4BusinessMethodArg.toString(csp_Tipo));
        }
        // CSP_ID_HR.
        if (csp_Id_Hr != null)
        {
            htItems.put("CSP_ID_HR", M4BusinessMethodArg.toString(csp_Id_Hr));
        }
        // CSP_DT_END.
        if (csp_Dt_End != null)
        {
            htItems.put("CSP_DT_END", M4BusinessMethodArg.toString(csp_Dt_End));
        }
        // CSP_ESTADO.
        if (csp_Estado != null)
        {
            htItems.put("CSP_ESTADO", M4BusinessMethodArg.toString(csp_Estado));
        }
        // CSP_COMMENT.
        if (csp_Comment != null)
        {
            htItems.put("CSP_COMMENT", M4BusinessMethodArg.toString(csp_Comment));
        }
        // CSP_CALCUL_CAP.
        if (csp_Calcul_Cap != null)
        {
            htItems.put("CSP_CALCUL_CAP", M4BusinessMethodArg.toString(csp_Calcul_Cap));
        }
        // CSP_DT_END_SEG.
        if (csp_Dt_End_Seg != null)
        {
            htItems.put("CSP_DT_END_SEG", M4BusinessMethodArg.toString(csp_Dt_End_Seg));
        }
        // CSP_OR_HR_ROLE.
        if (csp_Or_Hr_Role != null)
        {
            htItems.put("CSP_OR_HR_ROLE", M4BusinessMethodArg.toString(csp_Or_Hr_Role));
        }
        // CSP_ID_JOB_CODE.
        if (csp_Id_Job_Code != null)
        {
            htItems.put("CSP_ID_JOB_CODE", M4BusinessMethodArg.toString(csp_Id_Job_Code));
        }
        // CSP_ID_EVAL_PLAN.
        if (csp_Id_Eval_Plan != null)
        {
            htItems.put("CSP_ID_EVAL_PLAN", M4BusinessMethodArg.toString(csp_Id_Eval_Plan));
        }
        // CSP_ID_LEVEL_CAP.
        if (csp_Id_Level_Cap != null)
        {
            htItems.put("CSP_ID_LEVEL_CAP", M4BusinessMethodArg.toString(csp_Id_Level_Cap));
        }
        // CSP_ID_LEVEL_OBJ.
        if (csp_Id_Level_Obj != null)
        {
            htItems.put("CSP_ID_LEVEL_OBJ", M4BusinessMethodArg.toString(csp_Id_Level_Obj));
        }
        // CSP_DT_LIMIT_EVAL.
        if (csp_Dt_Limit_Eval != null)
        {
            htItems.put("CSP_DT_LIMIT_EVAL", M4BusinessMethodArg.toString(csp_Dt_Limit_Eval));
        }
        // CSP_DT_START_EVAL.
        if (csp_Dt_Start_Eval != null)
        {
            htItems.put("CSP_DT_START_EVAL", M4BusinessMethodArg.toString(csp_Dt_Start_Eval));
        }
        // CSP_DT_START_PROC.
        if (csp_Dt_Start_Proc != null)
        {
            htItems.put("CSP_DT_START_PROC", M4BusinessMethodArg.toString(csp_Dt_Start_Proc));
        }
        // CSP_ID_SUPERVISOR.
        if (csp_Id_Supervisor != null)
        {
            htItems.put("CSP_ID_SUPERVISOR", M4BusinessMethodArg.toString(csp_Id_Supervisor));
        }
        // CSP_OR_SUPERVISOR.
        if (csp_Or_Supervisor != null)
        {
            htItems.put("CSP_OR_SUPERVISOR", M4BusinessMethodArg.toString(csp_Or_Supervisor));
        }
        // CSP_SUPERVIS_COMM.
        if (csp_Supervis_Comm != null)
        {
            htItems.put("CSP_SUPERVIS_COMM", M4BusinessMethodArg.toString(csp_Supervis_Comm));
        }
        // CSP_ID_EMMITED_CAP.
        if (csp_Id_Emmited_Cap != null)
        {
            htItems.put("CSP_ID_EMMITED_CAP", M4BusinessMethodArg.toString(csp_Id_Emmited_Cap));
        }
        // CSP_ID_EMMITED_OBJ.
        if (csp_Id_Emmited_Obj != null)
        {
            htItems.put("CSP_ID_EMMITED_OBJ", M4BusinessMethodArg.toString(csp_Id_Emmited_Obj));
        }
        // CSP_VALUE_OBJ_QUANT.
        if (csp_Value_Obj_Quant != null)
        {
            htItems.put("CSP_VALUE_OBJ_QUANT", M4BusinessMethodArg.toString(csp_Value_Obj_Quant));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read CSP_TIPO.
        sItemName = "CSP_TIPO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Tipo = sItemValue;

        // read CSP_ID_HR.
        sItemName = "CSP_ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Hr = sItemValue;

        // read CSP_DT_END.
        sItemName = "CSP_DT_END";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Dt_End = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CSP_ESTADO.
        sItemName = "CSP_ESTADO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Estado = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CSP_COMMENT.
        sItemName = "CSP_COMMENT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Comment = sItemValue;

        // read CSP_CALCUL_CAP.
        sItemName = "CSP_CALCUL_CAP";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Calcul_Cap = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CSP_DT_END_SEG.
        sItemName = "CSP_DT_END_SEG";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Dt_End_Seg = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CSP_OR_HR_ROLE.
        sItemName = "CSP_OR_HR_ROLE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Or_Hr_Role = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CSP_ID_JOB_CODE.
        sItemName = "CSP_ID_JOB_CODE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Job_Code = sItemValue;

        // read CSP_ID_EVAL_PLAN.
        sItemName = "CSP_ID_EVAL_PLAN";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Eval_Plan = sItemValue;

        // read CSP_ID_LEVEL_CAP.
        sItemName = "CSP_ID_LEVEL_CAP";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Level_Cap = sItemValue;

        // read CSP_ID_LEVEL_OBJ.
        sItemName = "CSP_ID_LEVEL_OBJ";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Level_Obj = sItemValue;

        // read CSP_DT_LIMIT_EVAL.
        sItemName = "CSP_DT_LIMIT_EVAL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Dt_Limit_Eval = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CSP_DT_START_EVAL.
        sItemName = "CSP_DT_START_EVAL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Dt_Start_Eval = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CSP_DT_START_PROC.
        sItemName = "CSP_DT_START_PROC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Dt_Start_Proc = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CSP_ID_SUPERVISOR.
        sItemName = "CSP_ID_SUPERVISOR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Supervisor = sItemValue;

        // read CSP_OR_SUPERVISOR.
        sItemName = "CSP_OR_SUPERVISOR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Or_Supervisor = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CSP_SUPERVIS_COMM.
        sItemName = "CSP_SUPERVIS_COMM";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Supervis_Comm = sItemValue;

        // read CSP_ID_EMMITED_CAP.
        sItemName = "CSP_ID_EMMITED_CAP";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Emmited_Cap = sItemValue;

        // read CSP_ID_EMMITED_OBJ.
        sItemName = "CSP_ID_EMMITED_OBJ";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Emmited_Obj = sItemValue;

        // read CSP_VALUE_OBJ_QUANT.
        sItemName = "CSP_VALUE_OBJ_QUANT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Value_Obj_Quant = M4BusinessMethodArg.toDoubleNillable(sItemValue);


    } /* end of method readOperations */


} /* end of class Csp_Estado_EvalRecord */

