/**
 * Sntc_Gr_Filter_DataRecord.java
 * Self generated code for Bussines Object SNTC_GRAPH_BASE_TEMPLATE.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.sntc_graph_base_template;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Sntc_Gr_Filter_Data.
 * @author Meta4
 */
public 
class Sntc_Gr_Filter_DataRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "SNTC_GRAPH_BASE_TEMPLATE";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "SNTC_GR_FILTER_DATA";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Sntc_Gr_Filter_DataRecord.class.getName());

    /* new persistence member - RecordID */    
    private String m4AutoGeneratedRecordID = null; 
    
    public String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    public void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    private boolean m4AutoGeneratedToDelete = false; 
    
    public boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    public void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item VALUE */
    private String value = null;
    public void setvalue(String ai_value)
    {
        value = ai_value;
    }
    public String getvalue()
    {
        return value;
    }

    /* item ID_FILTER */
    private String id_Filter = null;
    public void setid_Filter(String ai_value)
    {
        id_Filter = ai_value;
    }
    public String getid_Filter()
    {
        return id_Filter;
    }

    /* item FILTER_TYPE */
    private Double filter_Type = null;
    public void setfilter_Type(Double ai_value)
    {
        filter_Type = ai_value;
    }
    public Double getfilter_Type()
    {
        return filter_Type;
    }

    /* item ID_OPERATOR */
    private Double id_Operator = null;
    public void setid_Operator(Double ai_value)
    {
        id_Operator = ai_value;
    }
    public Double getid_Operator()
    {
        return id_Operator;
    }

    /* item STR_OPERATOR */
    private String str_Operator = null;
    public void setstr_Operator(String ai_value)
    {
        str_Operator = ai_value;
    }
    public String getstr_Operator()
    {
        return str_Operator;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // VALUE.
        if (value != null)
        {
            htItems.put("VALUE", M4BusinessMethodArg.toString(value));
        }
        // ID_FILTER.
        if (id_Filter != null)
        {
            htItems.put("ID_FILTER", M4BusinessMethodArg.toString(id_Filter));
        }
        // FILTER_TYPE.
        if (filter_Type != null)
        {
            htItems.put("FILTER_TYPE", M4BusinessMethodArg.toString(filter_Type));
        }
        // ID_OPERATOR.
        if (id_Operator != null)
        {
            htItems.put("ID_OPERATOR", M4BusinessMethodArg.toString(id_Operator));
        }
        // STR_OPERATOR.
        if (str_Operator != null)
        {
            htItems.put("STR_OPERATOR", M4BusinessMethodArg.toString(str_Operator));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read VALUE.
        sItemName = "VALUE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        value = sItemValue;

        // read ID_FILTER.
        sItemName = "ID_FILTER";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Filter = sItemValue;

        // read FILTER_TYPE.
        sItemName = "FILTER_TYPE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        filter_Type = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read ID_OPERATOR.
        sItemName = "ID_OPERATOR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Operator = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read STR_OPERATOR.
        sItemName = "STR_OPERATOR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        str_Operator = sItemValue;


    } /* end of method readOperations */


} /* end of class Sntc_Gr_Filter_DataRecord */

