/**
 * Cyc_Filt_Fases_F3Record.java
 * Self generated code for Bussines Object CYC_FILT_VALORES_F3.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_filt_valores_f3;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Filt_Fases_F3.
 * @author Meta4
 */
public 
class Cyc_Filt_Fases_F3Record 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_FILT_VALORES_F3";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_FILT_FASES_F3";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Filt_Fases_F3Record.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item CYC_RANKING */
    public Double cyc_Ranking = null;
    private void setcyc_Ranking(Double ai_value)
    {
        cyc_Ranking = ai_value;
    }
    private Double getcyc_Ranking()
    {
        return cyc_Ranking;
    }

    /* item CYC_SUPERADA_F3 */
    public String cyc_Superada_F3 = null;
    private void setcyc_Superada_F3(String ai_value)
    {
        cyc_Superada_F3 = ai_value;
    }
    private String getcyc_Superada_F3()
    {
        return cyc_Superada_F3;
    }

    /* item CYC_ORIENT_RTDOS_F3 */
    public Double cyc_Orient_Rtdos_F3 = null;
    private void setcyc_Orient_Rtdos_F3(Double ai_value)
    {
        cyc_Orient_Rtdos_F3 = ai_value;
    }
    private Double getcyc_Orient_Rtdos_F3()
    {
        return cyc_Orient_Rtdos_F3;
    }

    /* item CYC_PORC_DESARROLLO */
    public Double cyc_Porc_Desarrollo = null;
    private void setcyc_Porc_Desarrollo(Double ai_value)
    {
        cyc_Porc_Desarrollo = ai_value;
    }
    private Double getcyc_Porc_Desarrollo()
    {
        return cyc_Porc_Desarrollo;
    }

    /* item CYC_COMUN_IMP_INF_F3 */
    public Double cyc_Comun_Imp_Inf_F3 = null;
    private void setcyc_Comun_Imp_Inf_F3(Double ai_value)
    {
        cyc_Comun_Imp_Inf_F3 = ai_value;
    }
    private Double getcyc_Comun_Imp_Inf_F3()
    {
        return cyc_Comun_Imp_Inf_F3;
    }

    /* item CYC_CAPAC_ANALITIC_F3 */
    public Double cyc_Capac_Analitic_F3 = null;
    private void setcyc_Capac_Analitic_F3(Double ai_value)
    {
        cyc_Capac_Analitic_F3 = ai_value;
    }
    private Double getcyc_Capac_Analitic_F3()
    {
        return cyc_Capac_Analitic_F3;
    }

    /* item CYC_LIDER_DIR_EQUIP_F3 */
    public Double cyc_Lider_Dir_Equip_F3 = null;
    private void setcyc_Lider_Dir_Equip_F3(Double ai_value)
    {
        cyc_Lider_Dir_Equip_F3 = ai_value;
    }
    private Double getcyc_Lider_Dir_Equip_F3()
    {
        return cyc_Lider_Dir_Equip_F3;
    }

    /* item CYC_VISION_GBAL_EST_F3 */
    public Double cyc_Vision_Gbal_Est_F3 = null;
    private void setcyc_Vision_Gbal_Est_F3(Double ai_value)
    {
        cyc_Vision_Gbal_Est_F3 = ai_value;
    }
    private Double getcyc_Vision_Gbal_Est_F3()
    {
        return cyc_Vision_Gbal_Est_F3;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // CYC_RANKING.
        if (cyc_Ranking != null)
        {
            htItems.put("CYC_RANKING", M4BusinessMethodArg.toString(cyc_Ranking));
        }
        // CYC_SUPERADA_F3.
        if (cyc_Superada_F3 != null)
        {
            htItems.put("CYC_SUPERADA_F3", M4BusinessMethodArg.toString(cyc_Superada_F3));
        }
        // CYC_ORIENT_RTDOS_F3.
        if (cyc_Orient_Rtdos_F3 != null)
        {
            htItems.put("CYC_ORIENT_RTDOS_F3", M4BusinessMethodArg.toString(cyc_Orient_Rtdos_F3));
        }
        // CYC_PORC_DESARROLLO.
        if (cyc_Porc_Desarrollo != null)
        {
            htItems.put("CYC_PORC_DESARROLLO", M4BusinessMethodArg.toString(cyc_Porc_Desarrollo));
        }
        // CYC_COMUN_IMP_INF_F3.
        if (cyc_Comun_Imp_Inf_F3 != null)
        {
            htItems.put("CYC_COMUN_IMP_INF_F3", M4BusinessMethodArg.toString(cyc_Comun_Imp_Inf_F3));
        }
        // CYC_CAPAC_ANALITIC_F3.
        if (cyc_Capac_Analitic_F3 != null)
        {
            htItems.put("CYC_CAPAC_ANALITIC_F3", M4BusinessMethodArg.toString(cyc_Capac_Analitic_F3));
        }
        // CYC_LIDER_DIR_EQUIP_F3.
        if (cyc_Lider_Dir_Equip_F3 != null)
        {
            htItems.put("CYC_LIDER_DIR_EQUIP_F3", M4BusinessMethodArg.toString(cyc_Lider_Dir_Equip_F3));
        }
        // CYC_VISION_GBAL_EST_F3.
        if (cyc_Vision_Gbal_Est_F3 != null)
        {
            htItems.put("CYC_VISION_GBAL_EST_F3", M4BusinessMethodArg.toString(cyc_Vision_Gbal_Est_F3));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read CYC_RANKING.
        sItemName = "CYC_RANKING";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Ranking = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_SUPERADA_F3.
        sItemName = "CYC_SUPERADA_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Superada_F3 = sItemValue;

        // read CYC_ORIENT_RTDOS_F3.
        sItemName = "CYC_ORIENT_RTDOS_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Orient_Rtdos_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_PORC_DESARROLLO.
        sItemName = "CYC_PORC_DESARROLLO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Porc_Desarrollo = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_COMUN_IMP_INF_F3.
        sItemName = "CYC_COMUN_IMP_INF_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Comun_Imp_Inf_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_CAPAC_ANALITIC_F3.
        sItemName = "CYC_CAPAC_ANALITIC_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Capac_Analitic_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_LIDER_DIR_EQUIP_F3.
        sItemName = "CYC_LIDER_DIR_EQUIP_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Lider_Dir_Equip_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_VISION_GBAL_EST_F3.
        sItemName = "CYC_VISION_GBAL_EST_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Vision_Gbal_Est_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);


    } /* end of method readOperations */


} /* end of class Cyc_Filt_Fases_F3Record */

