/* =========================================================
	@(#) FileVersion: 818.005.001
	@(#) FileDescription: dms_sign_documents.properties
	@(#) CompanyName: Meta4 Spain, S.A.
	@(#) LegalCopyright: (c) 2021
	@(#) ProductName: PeopleNet
========================================================= */


SignatureImplementationPage=/shco_ds/dms_sign_docs_impl_none.jsp

// Example: 
// SignatureImplementationPage=/shco_ds/dms_sign_docs_impl_websigner.jsp