/**
 * Cyc_Datos_Pb_3Record.java
 * Self generated code for Bussines Object CYC_BUSCADOR_FASE3.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_buscador_fase3;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Datos_Pb_3.
 * @author Meta4
 */
public 
class Cyc_Datos_Pb_3Record 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_BUSCADOR_FASE3";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_DATOS_PB_3";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Datos_Pb_3Record.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item NOMBRE */
    public String nombre = null;
    private void setnombre(String ai_value)
    {
        nombre = ai_value;
    }
    private String getnombre()
    {
        return nombre;
    }

    /* item APELLIDO1 */
    public String apellido1 = null;
    private void setapellido1(String ai_value)
    {
        apellido1 = ai_value;
    }
    private String getapellido1()
    {
        return apellido1;
    }

    /* item APELLIDO2 */
    public String apellido2 = null;
    private void setapellido2(String ai_value)
    {
        apellido2 = ai_value;
    }
    private String getapellido2()
    {
        return apellido2;
    }

    /* item ID_PERSON */
    public String id_Person = null;
    private void setid_Person(String ai_value)
    {
        id_Person = ai_value;
    }
    private String getid_Person()
    {
        return id_Person;
    }

    /* item FECHA_PROC */
    public Calendar fecha_Proc = null;
    private void setfecha_Proc(Calendar ai_value)
    {
        fecha_Proc = ai_value;
    }
    private Calendar getfecha_Proc()
    {
        return fecha_Proc;
    }

    /* item ID_PROCESO */
    public String id_Proceso = null;
    private void setid_Proceso(String ai_value)
    {
        id_Proceso = ai_value;
    }
    private String getid_Proceso()
    {
        return id_Proceso;
    }

    /* item ID_ORGANIZATION */
    public String id_Organization = null;
    private void setid_Organization(String ai_value)
    {
        id_Organization = ai_value;
    }
    private String getid_Organization()
    {
        return id_Organization;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // NOMBRE.
        if (nombre != null)
        {
            htItems.put("NOMBRE", M4BusinessMethodArg.toString(nombre));
        }
        // APELLIDO1.
        if (apellido1 != null)
        {
            htItems.put("APELLIDO1", M4BusinessMethodArg.toString(apellido1));
        }
        // APELLIDO2.
        if (apellido2 != null)
        {
            htItems.put("APELLIDO2", M4BusinessMethodArg.toString(apellido2));
        }
        // ID_PERSON.
        if (id_Person != null)
        {
            htItems.put("ID_PERSON", M4BusinessMethodArg.toString(id_Person));
        }
        // FECHA_PROC.
        if (fecha_Proc != null)
        {
            htItems.put("FECHA_PROC", M4BusinessMethodArg.toString(fecha_Proc));
        }
        // ID_PROCESO.
        if (id_Proceso != null)
        {
            htItems.put("ID_PROCESO", M4BusinessMethodArg.toString(id_Proceso));
        }
        // ID_ORGANIZATION.
        if (id_Organization != null)
        {
            htItems.put("ID_ORGANIZATION", M4BusinessMethodArg.toString(id_Organization));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read NOMBRE.
        sItemName = "NOMBRE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        nombre = sItemValue;

        // read APELLIDO1.
        sItemName = "APELLIDO1";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        apellido1 = sItemValue;

        // read APELLIDO2.
        sItemName = "APELLIDO2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        apellido2 = sItemValue;

        // read ID_PERSON.
        sItemName = "ID_PERSON";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Person = sItemValue;

        // read FECHA_PROC.
        sItemName = "FECHA_PROC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        fecha_Proc = M4BusinessMethodArg.toCalendar(sItemValue);

        // read ID_PROCESO.
        sItemName = "ID_PROCESO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Proceso = sItemValue;

        // read ID_ORGANIZATION.
        sItemName = "ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Organization = sItemValue;


    } /* end of method readOperations */


} /* end of class Cyc_Datos_Pb_3Record */

