/**
 * Csp_Insert_Obj_EvRecord.java
 * Self generated code for Bussines Object CSP_CREAR_OBJ.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.csp_crear_obj;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Csp_Insert_Obj_Ev.
 * @author Meta4
 */
public 
class Csp_Insert_Obj_EvRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CSP_CREAR_OBJ";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CSP_INSERT_OBJ_EV";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Csp_Insert_Obj_EvRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item DT_END */
    public Calendar dt_End = null;
    private void setdt_End(Calendar ai_value)
    {
        dt_End = ai_value;
    }
    private Calendar getdt_End()
    {
        return dt_End;
    }

    /* item CSP_VALUE */
    public Double csp_Value = null;
    private void setcsp_Value(Double ai_value)
    {
        csp_Value = ai_value;
    }
    private Double getcsp_Value()
    {
        return csp_Value;
    }

    /* item CSP_WEIGHT */
    public Double csp_Weight = null;
    private void setcsp_Weight(Double ai_value)
    {
        csp_Weight = ai_value;
    }
    private Double getcsp_Weight()
    {
        return csp_Weight;
    }

    /* item CSP_COMMENT */
    public String csp_Comment = null;
    private void setcsp_Comment(String ai_value)
    {
        csp_Comment = ai_value;
    }
    private String getcsp_Comment()
    {
        return csp_Comment;
    }

    /* item CSP_OR_HR_ROLE */
    public Double csp_Or_Hr_Role = null;
    private void setcsp_Or_Hr_Role(Double ai_value)
    {
        csp_Or_Hr_Role = ai_value;
    }
    private Double getcsp_Or_Hr_Role()
    {
        return csp_Or_Hr_Role;
    }

    /* item CSP_EXPLANATION */
    public String csp_Explanation = null;
    private void setcsp_Explanation(String ai_value)
    {
        csp_Explanation = ai_value;
    }
    private String getcsp_Explanation()
    {
        return csp_Explanation;
    }

    /* item CSP_ID_MAGNITUD */
    public String csp_Id_Magnitud = null;
    private void setcsp_Id_Magnitud(String ai_value)
    {
        csp_Id_Magnitud = ai_value;
    }
    private String getcsp_Id_Magnitud()
    {
        return csp_Id_Magnitud;
    }

    /* item CSP_SCHED_VALUE */
    public Double csp_Sched_Value = null;
    private void setcsp_Sched_Value(Double ai_value)
    {
        csp_Sched_Value = ai_value;
    }
    private Double getcsp_Sched_Value()
    {
        return csp_Sched_Value;
    }

    /* item CSP_DT_START_LVL */
    public Calendar csp_Dt_Start_Lvl = null;
    private void setcsp_Dt_Start_Lvl(Calendar ai_value)
    {
        csp_Dt_Start_Lvl = ai_value;
    }
    private Calendar getcsp_Dt_Start_Lvl()
    {
        return csp_Dt_Start_Lvl;
    }

    /* item CSP_DT_START_RAT */
    public Calendar csp_Dt_Start_Rat = null;
    private void setcsp_Dt_Start_Rat(Calendar ai_value)
    {
        csp_Dt_Start_Rat = ai_value;
    }
    private Calendar getcsp_Dt_Start_Rat()
    {
        return csp_Dt_Start_Rat;
    }

    /* item CSP_DT_START_REQ */
    public Calendar csp_Dt_Start_Req = null;
    private void setcsp_Dt_Start_Req(Calendar ai_value)
    {
        csp_Dt_Start_Req = ai_value;
    }
    private Calendar getcsp_Dt_Start_Req()
    {
        return csp_Dt_Start_Req;
    }

    /* item CSP_DT_START_SEG */
    public Calendar csp_Dt_Start_Seg = null;
    private void setcsp_Dt_Start_Seg(Calendar ai_value)
    {
        csp_Dt_Start_Seg = ai_value;
    }
    private Calendar getcsp_Dt_Start_Seg()
    {
        return csp_Dt_Start_Seg;
    }

    /* item CSP_ID_EVALUATOR */
    public String csp_Id_Evaluator = null;
    private void setcsp_Id_Evaluator(String ai_value)
    {
        csp_Id_Evaluator = ai_value;
    }
    private String getcsp_Id_Evaluator()
    {
        return csp_Id_Evaluator;
    }

    /* item CSP_ID_OBJECTIVE */
    public String csp_Id_Objective = null;
    private void setcsp_Id_Objective(String ai_value)
    {
        csp_Id_Objective = ai_value;
    }
    private String getcsp_Id_Objective()
    {
        return csp_Id_Objective;
    }

    /* item CSP_OR_EVALUATOR */
    public Double csp_Or_Evaluator = null;
    private void setcsp_Or_Evaluator(Double ai_value)
    {
        csp_Or_Evaluator = ai_value;
    }
    private Double getcsp_Or_Evaluator()
    {
        return csp_Or_Evaluator;
    }

    /* item CSP_ACCOMP_DEGREE */
    public Double csp_Accomp_Degree = null;
    private void setcsp_Accomp_Degree(Double ai_value)
    {
        csp_Accomp_Degree = ai_value;
    }
    private Double getcsp_Accomp_Degree()
    {
        return csp_Accomp_Degree;
    }

    /* item CSP_ID_OBJ_RAT_LVL */
    public String csp_Id_Obj_Rat_Lvl = null;
    private void setcsp_Id_Obj_Rat_Lvl(String ai_value)
    {
        csp_Id_Obj_Rat_Lvl = ai_value;
    }
    private String getcsp_Id_Obj_Rat_Lvl()
    {
        return csp_Id_Obj_Rat_Lvl;
    }

    /* item CSP_ID_OBJ_REQ_LVL */
    public String csp_Id_Obj_Req_Lvl = null;
    private void setcsp_Id_Obj_Req_Lvl(String ai_value)
    {
        csp_Id_Obj_Req_Lvl = ai_value;
    }
    private String getcsp_Id_Obj_Req_Lvl()
    {
        return csp_Id_Obj_Req_Lvl;
    }

    /* item CSP_ID_OBJ_SEG_LVL */
    public String csp_Id_Obj_Seg_Lvl = null;
    private void setcsp_Id_Obj_Seg_Lvl(String ai_value)
    {
        csp_Id_Obj_Seg_Lvl = ai_value;
    }
    private String getcsp_Id_Obj_Seg_Lvl()
    {
        return csp_Id_Obj_Seg_Lvl;
    }

    /* item CSP_ID_CRITERIA_TYPE */
    public String csp_Id_Criteria_Type = null;
    private void setcsp_Id_Criteria_Type(String ai_value)
    {
        csp_Id_Criteria_Type = ai_value;
    }
    private String getcsp_Id_Criteria_Type()
    {
        return csp_Id_Criteria_Type;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // DT_END.
        if (dt_End != null)
        {
            htItems.put("DT_END", M4BusinessMethodArg.toString(dt_End));
        }
        // CSP_VALUE.
        if (csp_Value != null)
        {
            htItems.put("CSP_VALUE", M4BusinessMethodArg.toString(csp_Value));
        }
        // CSP_WEIGHT.
        if (csp_Weight != null)
        {
            htItems.put("CSP_WEIGHT", M4BusinessMethodArg.toString(csp_Weight));
        }
        // CSP_COMMENT.
        if (csp_Comment != null)
        {
            htItems.put("CSP_COMMENT", M4BusinessMethodArg.toString(csp_Comment));
        }
        // CSP_OR_HR_ROLE.
        if (csp_Or_Hr_Role != null)
        {
            htItems.put("CSP_OR_HR_ROLE", M4BusinessMethodArg.toString(csp_Or_Hr_Role));
        }
        // CSP_EXPLANATION.
        if (csp_Explanation != null)
        {
            htItems.put("CSP_EXPLANATION", M4BusinessMethodArg.toString(csp_Explanation));
        }
        // CSP_ID_MAGNITUD.
        if (csp_Id_Magnitud != null)
        {
            htItems.put("CSP_ID_MAGNITUD", M4BusinessMethodArg.toString(csp_Id_Magnitud));
        }
        // CSP_SCHED_VALUE.
        if (csp_Sched_Value != null)
        {
            htItems.put("CSP_SCHED_VALUE", M4BusinessMethodArg.toString(csp_Sched_Value));
        }
        // CSP_DT_START_LVL.
        if (csp_Dt_Start_Lvl != null)
        {
            htItems.put("CSP_DT_START_LVL", M4BusinessMethodArg.toString(csp_Dt_Start_Lvl));
        }
        // CSP_DT_START_RAT.
        if (csp_Dt_Start_Rat != null)
        {
            htItems.put("CSP_DT_START_RAT", M4BusinessMethodArg.toString(csp_Dt_Start_Rat));
        }
        // CSP_DT_START_REQ.
        if (csp_Dt_Start_Req != null)
        {
            htItems.put("CSP_DT_START_REQ", M4BusinessMethodArg.toString(csp_Dt_Start_Req));
        }
        // CSP_DT_START_SEG.
        if (csp_Dt_Start_Seg != null)
        {
            htItems.put("CSP_DT_START_SEG", M4BusinessMethodArg.toString(csp_Dt_Start_Seg));
        }
        // CSP_ID_EVALUATOR.
        if (csp_Id_Evaluator != null)
        {
            htItems.put("CSP_ID_EVALUATOR", M4BusinessMethodArg.toString(csp_Id_Evaluator));
        }
        // CSP_ID_OBJECTIVE.
        if (csp_Id_Objective != null)
        {
            htItems.put("CSP_ID_OBJECTIVE", M4BusinessMethodArg.toString(csp_Id_Objective));
        }
        // CSP_OR_EVALUATOR.
        if (csp_Or_Evaluator != null)
        {
            htItems.put("CSP_OR_EVALUATOR", M4BusinessMethodArg.toString(csp_Or_Evaluator));
        }
        // CSP_ACCOMP_DEGREE.
        if (csp_Accomp_Degree != null)
        {
            htItems.put("CSP_ACCOMP_DEGREE", M4BusinessMethodArg.toString(csp_Accomp_Degree));
        }
        // CSP_ID_OBJ_RAT_LVL.
        if (csp_Id_Obj_Rat_Lvl != null)
        {
            htItems.put("CSP_ID_OBJ_RAT_LVL", M4BusinessMethodArg.toString(csp_Id_Obj_Rat_Lvl));
        }
        // CSP_ID_OBJ_REQ_LVL.
        if (csp_Id_Obj_Req_Lvl != null)
        {
            htItems.put("CSP_ID_OBJ_REQ_LVL", M4BusinessMethodArg.toString(csp_Id_Obj_Req_Lvl));
        }
        // CSP_ID_OBJ_SEG_LVL.
        if (csp_Id_Obj_Seg_Lvl != null)
        {
            htItems.put("CSP_ID_OBJ_SEG_LVL", M4BusinessMethodArg.toString(csp_Id_Obj_Seg_Lvl));
        }
        // CSP_ID_CRITERIA_TYPE.
        if (csp_Id_Criteria_Type != null)
        {
            htItems.put("CSP_ID_CRITERIA_TYPE", M4BusinessMethodArg.toString(csp_Id_Criteria_Type));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read DT_END.
        sItemName = "DT_END";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_End = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CSP_VALUE.
        sItemName = "CSP_VALUE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Value = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CSP_WEIGHT.
        sItemName = "CSP_WEIGHT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Weight = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CSP_COMMENT.
        sItemName = "CSP_COMMENT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Comment = sItemValue;

        // read CSP_OR_HR_ROLE.
        sItemName = "CSP_OR_HR_ROLE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Or_Hr_Role = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CSP_EXPLANATION.
        sItemName = "CSP_EXPLANATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Explanation = sItemValue;

        // read CSP_ID_MAGNITUD.
        sItemName = "CSP_ID_MAGNITUD";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Magnitud = sItemValue;

        // read CSP_SCHED_VALUE.
        sItemName = "CSP_SCHED_VALUE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Sched_Value = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CSP_DT_START_LVL.
        sItemName = "CSP_DT_START_LVL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Dt_Start_Lvl = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CSP_DT_START_RAT.
        sItemName = "CSP_DT_START_RAT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Dt_Start_Rat = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CSP_DT_START_REQ.
        sItemName = "CSP_DT_START_REQ";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Dt_Start_Req = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CSP_DT_START_SEG.
        sItemName = "CSP_DT_START_SEG";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Dt_Start_Seg = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CSP_ID_EVALUATOR.
        sItemName = "CSP_ID_EVALUATOR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Evaluator = sItemValue;

        // read CSP_ID_OBJECTIVE.
        sItemName = "CSP_ID_OBJECTIVE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Objective = sItemValue;

        // read CSP_OR_EVALUATOR.
        sItemName = "CSP_OR_EVALUATOR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Or_Evaluator = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CSP_ACCOMP_DEGREE.
        sItemName = "CSP_ACCOMP_DEGREE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Accomp_Degree = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CSP_ID_OBJ_RAT_LVL.
        sItemName = "CSP_ID_OBJ_RAT_LVL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Obj_Rat_Lvl = sItemValue;

        // read CSP_ID_OBJ_REQ_LVL.
        sItemName = "CSP_ID_OBJ_REQ_LVL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Obj_Req_Lvl = sItemValue;

        // read CSP_ID_OBJ_SEG_LVL.
        sItemName = "CSP_ID_OBJ_SEG_LVL";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Obj_Seg_Lvl = sItemValue;

        // read CSP_ID_CRITERIA_TYPE.
        sItemName = "CSP_ID_CRITERIA_TYPE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        csp_Id_Criteria_Type = sItemValue;


    } /* end of method readOperations */


} /* end of class Csp_Insert_Obj_EvRecord */

