/**
 * Sntc_Adb_View_AlertRecord.java
 * Self generated code for Bussines Object SNTC_ADB_VIEW_ALERT.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.sntc_adb_view_alert;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Sntc_Adb_View_Alert.
 * @author Meta4
 */
public 
class Sntc_Adb_View_AlertRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "SNTC_ADB_VIEW_ALERT";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "SNTC_ADB_VIEW_ALERT";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Sntc_Adb_View_AlertRecord.class.getName());

    /* new persistence member - RecordID */    
    private String m4AutoGeneratedRecordID = null; 
    
    public String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    public void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    private boolean m4AutoGeneratedToDelete = false; 
    
    public boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    public void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item ID_BPC */
    private Double id_Bpc = null;
    public void setid_Bpc(Double ai_value)
    {
        id_Bpc = ai_value;
    }
    public Double getid_Bpc()
    {
        return id_Bpc;
    }

    /* item ID_BPO */
    private String id_Bpo = null;
    public void setid_Bpo(String ai_value)
    {
        id_Bpo = ai_value;
    }
    public String getid_Bpo()
    {
        return id_Bpo;
    }

    /* item ID_TASK */
    private String id_Task = null;
    public void setid_Task(String ai_value)
    {
        id_Task = ai_value;
    }
    public String getid_Task()
    {
        return id_Task;
    }

    /* item ID_USER */
    private String id_User = null;
    public void setid_User(String ai_value)
    {
        id_User = ai_value;
    }
    public String getid_User()
    {
        return id_User;
    }

    /* item BPC_DESC */
    private String bpc_Desc = null;
    public void setbpc_Desc(String ai_value)
    {
        bpc_Desc = ai_value;
    }
    public String getbpc_Desc()
    {
        return bpc_Desc;
    }

    /* item CODE_TYPE */
    private Double code_Type = null;
    public void setcode_Type(Double ai_value)
    {
        code_Type = ai_value;
    }
    public Double getcode_Type()
    {
        return code_Type;
    }

    /* item PROP_ID_WU */
    private String prop_Id_Wu = null;
    public void setprop_Id_Wu(String ai_value)
    {
        prop_Id_Wu = ai_value;
    }
    public String getprop_Id_Wu()
    {
        return prop_Id_Wu;
    }

    /* item ID_WORKITEM */
    private String id_Workitem = null;
    public void setid_Workitem(String ai_value)
    {
        id_Workitem = ai_value;
    }
    public String getid_Workitem()
    {
        return id_Workitem;
    }

    /* item PROP_DT_END */
    private Calendar prop_Dt_End = null;
    public void setprop_Dt_End(Calendar ai_value)
    {
        prop_Dt_End = ai_value;
    }
    public Calendar getprop_Dt_End()
    {
        return prop_Dt_End;
    }

    /* item PROP_PARAMS */
    private String prop_Params = null;
    public void setprop_Params(String ai_value)
    {
        prop_Params = ai_value;
    }
    public String getprop_Params()
    {
        return prop_Params;
    }

    /* item PROP_MESSAGE */
    private String prop_Message = null;
    public void setprop_Message(String ai_value)
    {
        prop_Message = ai_value;
    }
    public String getprop_Message()
    {
        return prop_Message;
    }

    /* item PROP_N_ALERT */
    private String prop_N_Alert = null;
    public void setprop_N_Alert(String ai_value)
    {
        prop_N_Alert = ai_value;
    }
    public String getprop_N_Alert()
    {
        return prop_N_Alert;
    }

    /* item PROP_DT_START */
    private Calendar prop_Dt_Start = null;
    public void setprop_Dt_Start(Calendar ai_value)
    {
        prop_Dt_Start = ai_value;
    }
    public Calendar getprop_Dt_Start()
    {
        return prop_Dt_Start;
    }

    /* item PROP_ID_ALERT */
    private String prop_Id_Alert = null;
    public void setprop_Id_Alert(String ai_value)
    {
        prop_Id_Alert = ai_value;
    }
    public String getprop_Id_Alert()
    {
        return prop_Id_Alert;
    }

    /* item PROP_ID_GRAPH */
    private String prop_Id_Graph = null;
    public void setprop_Id_Graph(String ai_value)
    {
        prop_Id_Graph = ai_value;
    }
    public String getprop_Id_Graph()
    {
        return prop_Id_Graph;
    }

    /* item PROP_TYPE_ALERT */
    private String prop_Type_Alert = null;
    public void setprop_Type_Alert(String ai_value)
    {
        prop_Type_Alert = ai_value;
    }
    public String getprop_Type_Alert()
    {
        return prop_Type_Alert;
    }

    /* item DT_INSTANTIATION */
    private Calendar dt_Instantiation = null;
    public void setdt_Instantiation(Calendar ai_value)
    {
        dt_Instantiation = ai_value;
    }
    public Calendar getdt_Instantiation()
    {
        return dt_Instantiation;
    }

    /* item ID_WKITEM_STATUS */
    private Double id_Wkitem_Status = null;
    public void setid_Wkitem_Status(Double ai_value)
    {
        id_Wkitem_Status = ai_value;
    }
    public Double getid_Wkitem_Status()
    {
        return id_Wkitem_Status;
    }

    /* item PROP_ID_ORGANIZATION */
    private String prop_Id_Organization = null;
    public void setprop_Id_Organization(String ai_value)
    {
        prop_Id_Organization = ai_value;
    }
    public String getprop_Id_Organization()
    {
        return prop_Id_Organization;
    }

    /* node SNTC_ADB_VIEW_ALERT_PROPS */
    private Sntc_Adb_View_Alert_PropsBlock Sntc_Adb_View_Alert_Props = null;
    public void setsntc_Adb_View_Alert_Props(Sntc_Adb_View_Alert_PropsBlock ai_value)
    {
        Sntc_Adb_View_Alert_Props = ai_value;
    }
    public Sntc_Adb_View_Alert_PropsBlock getSntc_Adb_View_Alert_Props()
    {
        return Sntc_Adb_View_Alert_Props;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // ID_BPC.
        if (id_Bpc != null)
        {
            htItems.put("ID_BPC", M4BusinessMethodArg.toString(id_Bpc));
        }
        // ID_BPO.
        if (id_Bpo != null)
        {
            htItems.put("ID_BPO", M4BusinessMethodArg.toString(id_Bpo));
        }
        // ID_TASK.
        if (id_Task != null)
        {
            htItems.put("ID_TASK", M4BusinessMethodArg.toString(id_Task));
        }
        // ID_USER.
        if (id_User != null)
        {
            htItems.put("ID_USER", M4BusinessMethodArg.toString(id_User));
        }
        // BPC_DESC.
        if (bpc_Desc != null)
        {
            htItems.put("BPC_DESC", M4BusinessMethodArg.toString(bpc_Desc));
        }
        // CODE_TYPE.
        if (code_Type != null)
        {
            htItems.put("CODE_TYPE", M4BusinessMethodArg.toString(code_Type));
        }
        // PROP_ID_WU.
        if (prop_Id_Wu != null)
        {
            htItems.put("PROP_ID_WU", M4BusinessMethodArg.toString(prop_Id_Wu));
        }
        // ID_WORKITEM.
        if (id_Workitem != null)
        {
            htItems.put("ID_WORKITEM", M4BusinessMethodArg.toString(id_Workitem));
        }
        // PROP_DT_END.
        if (prop_Dt_End != null)
        {
            htItems.put("PROP_DT_END", M4BusinessMethodArg.toString(prop_Dt_End));
        }
        // PROP_PARAMS.
        if (prop_Params != null)
        {
            htItems.put("PROP_PARAMS", M4BusinessMethodArg.toString(prop_Params));
        }
        // PROP_MESSAGE.
        if (prop_Message != null)
        {
            htItems.put("PROP_MESSAGE", M4BusinessMethodArg.toString(prop_Message));
        }
        // PROP_N_ALERT.
        if (prop_N_Alert != null)
        {
            htItems.put("PROP_N_ALERT", M4BusinessMethodArg.toString(prop_N_Alert));
        }
        // PROP_DT_START.
        if (prop_Dt_Start != null)
        {
            htItems.put("PROP_DT_START", M4BusinessMethodArg.toString(prop_Dt_Start));
        }
        // PROP_ID_ALERT.
        if (prop_Id_Alert != null)
        {
            htItems.put("PROP_ID_ALERT", M4BusinessMethodArg.toString(prop_Id_Alert));
        }
        // PROP_ID_GRAPH.
        if (prop_Id_Graph != null)
        {
            htItems.put("PROP_ID_GRAPH", M4BusinessMethodArg.toString(prop_Id_Graph));
        }
        // PROP_TYPE_ALERT.
        if (prop_Type_Alert != null)
        {
            htItems.put("PROP_TYPE_ALERT", M4BusinessMethodArg.toString(prop_Type_Alert));
        }
        // DT_INSTANTIATION.
        if (dt_Instantiation != null)
        {
            htItems.put("DT_INSTANTIATION", M4BusinessMethodArg.toString(dt_Instantiation));
        }
        // ID_WKITEM_STATUS.
        if (id_Wkitem_Status != null)
        {
            htItems.put("ID_WKITEM_STATUS", M4BusinessMethodArg.toString(id_Wkitem_Status));
        }
        // PROP_ID_ORGANIZATION.
        if (prop_Id_Organization != null)
        {
            htItems.put("PROP_ID_ORGANIZATION", M4BusinessMethodArg.toString(prop_Id_Organization));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

        // write data for node SNTC_ADB_VIEW_ALERT_PROPS.
        if ( Sntc_Adb_View_Alert_Props != null) 
        {
           Sntc_Adb_View_Alert_Props.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read ID_BPC.
        sItemName = "ID_BPC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Bpc = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read ID_BPO.
        sItemName = "ID_BPO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Bpo = sItemValue;

        // read ID_TASK.
        sItemName = "ID_TASK";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Task = sItemValue;

        // read ID_USER.
        sItemName = "ID_USER";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_User = sItemValue;

        // read BPC_DESC.
        sItemName = "BPC_DESC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        bpc_Desc = sItemValue;

        // read CODE_TYPE.
        sItemName = "CODE_TYPE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        code_Type = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read PROP_ID_WU.
        sItemName = "PROP_ID_WU";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        prop_Id_Wu = sItemValue;

        // read ID_WORKITEM.
        sItemName = "ID_WORKITEM";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Workitem = sItemValue;

        // read PROP_DT_END.
        sItemName = "PROP_DT_END";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        prop_Dt_End = M4BusinessMethodArg.toCalendar(sItemValue);

        // read PROP_PARAMS.
        sItemName = "PROP_PARAMS";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        prop_Params = sItemValue;

        // read PROP_MESSAGE.
        sItemName = "PROP_MESSAGE";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        prop_Message = sItemValue;

        // read PROP_N_ALERT.
        sItemName = "PROP_N_ALERT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        prop_N_Alert = sItemValue;

        // read PROP_DT_START.
        sItemName = "PROP_DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        prop_Dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read PROP_ID_ALERT.
        sItemName = "PROP_ID_ALERT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        prop_Id_Alert = sItemValue;

        // read PROP_ID_GRAPH.
        sItemName = "PROP_ID_GRAPH";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        prop_Id_Graph = sItemValue;

        // read PROP_TYPE_ALERT.
        sItemName = "PROP_TYPE_ALERT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        prop_Type_Alert = sItemValue;

        // read DT_INSTANTIATION.
        sItemName = "DT_INSTANTIATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_Instantiation = M4BusinessMethodArg.toCalendar(sItemValue);

        // read ID_WKITEM_STATUS.
        sItemName = "ID_WKITEM_STATUS";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Wkitem_Status = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read PROP_ID_ORGANIZATION.
        sItemName = "PROP_ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        prop_Id_Organization = sItemValue;

        // read data for node SNTC_ADB_VIEW_ALERT_PROPS.
        Sntc_Adb_View_Alert_Props = new Sntc_Adb_View_Alert_PropsBlock();
        Sntc_Adb_View_Alert_Props.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Sntc_Adb_View_Alert_PropsBlock.NODE_NAME));


    } /* end of method readOperations */


} /* end of class Sntc_Adb_View_AlertRecord */

