/**
 * Cyc_Informe_TotalesRecord.java
 * Self generated code for Bussines Object CYC_INFORMES_PCP.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_informes_pcp;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Informe_Totales.
 * @author Meta4
 */
public 
class Cyc_Informe_TotalesRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_INFORMES_PCP";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_INFORME_TOTALES";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Informe_TotalesRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item FEBK_CYC */
    public Double febk_Cyc = null;
    private void setfebk_Cyc(Double ai_value)
    {
        febk_Cyc = ai_value;
    }
    private Double getfebk_Cyc()
    {
        return febk_Cyc;
    }

    /* item BAJAS_CYC */
    public Double bajas_Cyc = null;
    private void setbajas_Cyc(Double ai_value)
    {
        bajas_Cyc = ai_value;
    }
    private Double getbajas_Cyc()
    {
        return bajas_Cyc;
    }

    /* item FEBK_IBER */
    public Double febk_Iber = null;
    private void setfebk_Iber(Double ai_value)
    {
        febk_Iber = ai_value;
    }
    private Double getfebk_Iber()
    {
        return febk_Iber;
    }

    /* item BAJAS_IBER */
    public Double bajas_Iber = null;
    private void setbajas_Iber(Double ai_value)
    {
        bajas_Iber = ai_value;
    }
    private Double getbajas_Iber()
    {
        return bajas_Iber;
    }

    /* item ID_EMPLEADO */
    public Double id_Empleado = null;
    private void setid_Empleado(Double ai_value)
    {
        id_Empleado = ai_value;
    }
    private Double getid_Empleado()
    {
        return id_Empleado;
    }

    /* item SUPERAN_CYC */
    public Double superan_Cyc = null;
    private void setsuperan_Cyc(Double ai_value)
    {
        superan_Cyc = ai_value;
    }
    private Double getsuperan_Cyc()
    {
        return superan_Cyc;
    }

    /* item TOTALES_CYC */
    public Double totales_Cyc = null;
    private void settotales_Cyc(Double ai_value)
    {
        totales_Cyc = ai_value;
    }
    private Double gettotales_Cyc()
    {
        return totales_Cyc;
    }

    /* item SUPERAN_IBER */
    public Double superan_Iber = null;
    private void setsuperan_Iber(Double ai_value)
    {
        superan_Iber = ai_value;
    }
    private Double getsuperan_Iber()
    {
        return superan_Iber;
    }

    /* item TOTALES_IBER */
    public Double totales_Iber = null;
    private void settotales_Iber(Double ai_value)
    {
        totales_Iber = ai_value;
    }
    private Double gettotales_Iber()
    {
        return totales_Iber;
    }

    /* item NO_SUPERAN_CYC */
    public Double no_Superan_Cyc = null;
    private void setno_Superan_Cyc(Double ai_value)
    {
        no_Superan_Cyc = ai_value;
    }
    private Double getno_Superan_Cyc()
    {
        return no_Superan_Cyc;
    }

    /* item NO_SUPERAN_IBER */
    public Double no_Superan_Iber = null;
    private void setno_Superan_Iber(Double ai_value)
    {
        no_Superan_Iber = ai_value;
    }
    private Double getno_Superan_Iber()
    {
        return no_Superan_Iber;
    }

    /* item POTENCIAL_DES_CYC */
    public Double potencial_Des_Cyc = null;
    private void setpotencial_Des_Cyc(Double ai_value)
    {
        potencial_Des_Cyc = ai_value;
    }
    private Double getpotencial_Des_Cyc()
    {
        return potencial_Des_Cyc;
    }

    /* item POTENCIAL_DES_ING */
    public Double potencial_Des_Ing = null;
    private void setpotencial_Des_Ing(Double ai_value)
    {
        potencial_Des_Ing = ai_value;
    }
    private Double getpotencial_Des_Ing()
    {
        return potencial_Des_Ing;
    }

    /* item CONTRIBUYENTES_CYC */
    public Double contribuyentes_Cyc = null;
    private void setcontribuyentes_Cyc(Double ai_value)
    {
        contribuyentes_Cyc = ai_value;
    }
    private Double getcontribuyentes_Cyc()
    {
        return contribuyentes_Cyc;
    }

    /* item CONTRIBUYENTES_ING */
    public Double contribuyentes_Ing = null;
    private void setcontribuyentes_Ing(Double ai_value)
    {
        contribuyentes_Ing = ai_value;
    }
    private Double getcontribuyentes_Ing()
    {
        return contribuyentes_Ing;
    }

    /* item POTENCIAL_DES_IBER */
    public Double potencial_Des_Iber = null;
    private void setpotencial_Des_Iber(Double ai_value)
    {
        potencial_Des_Iber = ai_value;
    }
    private Double getpotencial_Des_Iber()
    {
        return potencial_Des_Iber;
    }

    /* item CAP_GESTION_DES_CYC */
    public Double cap_Gestion_Des_Cyc = null;
    private void setcap_Gestion_Des_Cyc(Double ai_value)
    {
        cap_Gestion_Des_Cyc = ai_value;
    }
    private Double getcap_Gestion_Des_Cyc()
    {
        return cap_Gestion_Des_Cyc;
    }

    /* item CAP_GESTION_DES_ING */
    public Double cap_Gestion_Des_Ing = null;
    private void setcap_Gestion_Des_Ing(Double ai_value)
    {
        cap_Gestion_Des_Ing = ai_value;
    }
    private Double getcap_Gestion_Des_Ing()
    {
        return cap_Gestion_Des_Ing;
    }

    /* item CONTRIBUYENTES_IBER */
    public Double contribuyentes_Iber = null;
    private void setcontribuyentes_Iber(Double ai_value)
    {
        contribuyentes_Iber = ai_value;
    }
    private Double getcontribuyentes_Iber()
    {
        return contribuyentes_Iber;
    }

    /* item CAP_GESTION_BAJO_CYC */
    public Double cap_Gestion_Bajo_Cyc = null;
    private void setcap_Gestion_Bajo_Cyc(Double ai_value)
    {
        cap_Gestion_Bajo_Cyc = ai_value;
    }
    private Double getcap_Gestion_Bajo_Cyc()
    {
        return cap_Gestion_Bajo_Cyc;
    }

    /* item CAP_GESTION_BAJO_ING */
    public Double cap_Gestion_Bajo_Ing = null;
    private void setcap_Gestion_Bajo_Ing(Double ai_value)
    {
        cap_Gestion_Bajo_Ing = ai_value;
    }
    private Double getcap_Gestion_Bajo_Ing()
    {
        return cap_Gestion_Bajo_Ing;
    }

    /* item CAP_GESTION_DES_IBER */
    public Double cap_Gestion_Des_Iber = null;
    private void setcap_Gestion_Des_Iber(Double ai_value)
    {
        cap_Gestion_Des_Iber = ai_value;
    }
    private Double getcap_Gestion_Des_Iber()
    {
        return cap_Gestion_Des_Iber;
    }

    /* item CAP_GESTION_BAJO_IBER */
    public Double cap_Gestion_Bajo_Iber = null;
    private void setcap_Gestion_Bajo_Iber(Double ai_value)
    {
        cap_Gestion_Bajo_Iber = ai_value;
    }
    private Double getcap_Gestion_Bajo_Iber()
    {
        return cap_Gestion_Bajo_Iber;
    }

    /* node CYC_SUPERAN */
    public Cyc_SuperanBlock Cyc_Superan = null;
    private void setcyc_Superan(Cyc_SuperanBlock ai_value)
    {
        Cyc_Superan = ai_value;
    }
    private Cyc_SuperanBlock getCyc_Superan()
    {
        return Cyc_Superan;
    }

    /* node CYC_TOT_CURSANTES */
    public Cyc_Tot_CursantesBlock Cyc_Tot_Cursantes = null;
    private void setcyc_Tot_Cursantes(Cyc_Tot_CursantesBlock ai_value)
    {
        Cyc_Tot_Cursantes = ai_value;
    }
    private Cyc_Tot_CursantesBlock getCyc_Tot_Cursantes()
    {
        return Cyc_Tot_Cursantes;
    }

    /* node CYC_BAJAS_CURSANTES */
    public Cyc_Bajas_CursantesBlock Cyc_Bajas_Cursantes = null;
    private void setcyc_Bajas_Cursantes(Cyc_Bajas_CursantesBlock ai_value)
    {
        Cyc_Bajas_Cursantes = ai_value;
    }
    private Cyc_Bajas_CursantesBlock getCyc_Bajas_Cursantes()
    {
        return Cyc_Bajas_Cursantes;
    }

    /* node CYC_FEEDBACK_CURSANTES */
    public Cyc_Feedback_CursantesBlock Cyc_Feedback_Cursantes = null;
    private void setcyc_Feedback_Cursantes(Cyc_Feedback_CursantesBlock ai_value)
    {
        Cyc_Feedback_Cursantes = ai_value;
    }
    private Cyc_Feedback_CursantesBlock getCyc_Feedback_Cursantes()
    {
        return Cyc_Feedback_Cursantes;
    }

    /* node CYC_COLECTIVO_CURSANTES */
    public Cyc_Colectivo_CursantesBlock Cyc_Colectivo_Cursantes = null;
    private void setcyc_Colectivo_Cursantes(Cyc_Colectivo_CursantesBlock ai_value)
    {
        Cyc_Colectivo_Cursantes = ai_value;
    }
    private Cyc_Colectivo_CursantesBlock getCyc_Colectivo_Cursantes()
    {
        return Cyc_Colectivo_Cursantes;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // FEBK_CYC.
        if (febk_Cyc != null)
        {
            htItems.put("FEBK_CYC", M4BusinessMethodArg.toString(febk_Cyc));
        }
        // BAJAS_CYC.
        if (bajas_Cyc != null)
        {
            htItems.put("BAJAS_CYC", M4BusinessMethodArg.toString(bajas_Cyc));
        }
        // FEBK_IBER.
        if (febk_Iber != null)
        {
            htItems.put("FEBK_IBER", M4BusinessMethodArg.toString(febk_Iber));
        }
        // BAJAS_IBER.
        if (bajas_Iber != null)
        {
            htItems.put("BAJAS_IBER", M4BusinessMethodArg.toString(bajas_Iber));
        }
        // ID_EMPLEADO.
        if (id_Empleado != null)
        {
            htItems.put("ID_EMPLEADO", M4BusinessMethodArg.toString(id_Empleado));
        }
        // SUPERAN_CYC.
        if (superan_Cyc != null)
        {
            htItems.put("SUPERAN_CYC", M4BusinessMethodArg.toString(superan_Cyc));
        }
        // TOTALES_CYC.
        if (totales_Cyc != null)
        {
            htItems.put("TOTALES_CYC", M4BusinessMethodArg.toString(totales_Cyc));
        }
        // SUPERAN_IBER.
        if (superan_Iber != null)
        {
            htItems.put("SUPERAN_IBER", M4BusinessMethodArg.toString(superan_Iber));
        }
        // TOTALES_IBER.
        if (totales_Iber != null)
        {
            htItems.put("TOTALES_IBER", M4BusinessMethodArg.toString(totales_Iber));
        }
        // NO_SUPERAN_CYC.
        if (no_Superan_Cyc != null)
        {
            htItems.put("NO_SUPERAN_CYC", M4BusinessMethodArg.toString(no_Superan_Cyc));
        }
        // NO_SUPERAN_IBER.
        if (no_Superan_Iber != null)
        {
            htItems.put("NO_SUPERAN_IBER", M4BusinessMethodArg.toString(no_Superan_Iber));
        }
        // POTENCIAL_DES_CYC.
        if (potencial_Des_Cyc != null)
        {
            htItems.put("POTENCIAL_DES_CYC", M4BusinessMethodArg.toString(potencial_Des_Cyc));
        }
        // POTENCIAL_DES_ING.
        if (potencial_Des_Ing != null)
        {
            htItems.put("POTENCIAL_DES_ING", M4BusinessMethodArg.toString(potencial_Des_Ing));
        }
        // CONTRIBUYENTES_CYC.
        if (contribuyentes_Cyc != null)
        {
            htItems.put("CONTRIBUYENTES_CYC", M4BusinessMethodArg.toString(contribuyentes_Cyc));
        }
        // CONTRIBUYENTES_ING.
        if (contribuyentes_Ing != null)
        {
            htItems.put("CONTRIBUYENTES_ING", M4BusinessMethodArg.toString(contribuyentes_Ing));
        }
        // POTENCIAL_DES_IBER.
        if (potencial_Des_Iber != null)
        {
            htItems.put("POTENCIAL_DES_IBER", M4BusinessMethodArg.toString(potencial_Des_Iber));
        }
        // CAP_GESTION_DES_CYC.
        if (cap_Gestion_Des_Cyc != null)
        {
            htItems.put("CAP_GESTION_DES_CYC", M4BusinessMethodArg.toString(cap_Gestion_Des_Cyc));
        }
        // CAP_GESTION_DES_ING.
        if (cap_Gestion_Des_Ing != null)
        {
            htItems.put("CAP_GESTION_DES_ING", M4BusinessMethodArg.toString(cap_Gestion_Des_Ing));
        }
        // CONTRIBUYENTES_IBER.
        if (contribuyentes_Iber != null)
        {
            htItems.put("CONTRIBUYENTES_IBER", M4BusinessMethodArg.toString(contribuyentes_Iber));
        }
        // CAP_GESTION_BAJO_CYC.
        if (cap_Gestion_Bajo_Cyc != null)
        {
            htItems.put("CAP_GESTION_BAJO_CYC", M4BusinessMethodArg.toString(cap_Gestion_Bajo_Cyc));
        }
        // CAP_GESTION_BAJO_ING.
        if (cap_Gestion_Bajo_Ing != null)
        {
            htItems.put("CAP_GESTION_BAJO_ING", M4BusinessMethodArg.toString(cap_Gestion_Bajo_Ing));
        }
        // CAP_GESTION_DES_IBER.
        if (cap_Gestion_Des_Iber != null)
        {
            htItems.put("CAP_GESTION_DES_IBER", M4BusinessMethodArg.toString(cap_Gestion_Des_Iber));
        }
        // CAP_GESTION_BAJO_IBER.
        if (cap_Gestion_Bajo_Iber != null)
        {
            htItems.put("CAP_GESTION_BAJO_IBER", M4BusinessMethodArg.toString(cap_Gestion_Bajo_Iber));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

        // write data for node CYC_SUPERAN.
        if ( Cyc_Superan != null) 
        {
           Cyc_Superan.writeOperations(ai_m4Op);
        }

        // write data for node CYC_TOT_CURSANTES.
        if ( Cyc_Tot_Cursantes != null) 
        {
           Cyc_Tot_Cursantes.writeOperations(ai_m4Op);
        }

        // write data for node CYC_BAJAS_CURSANTES.
        if ( Cyc_Bajas_Cursantes != null) 
        {
           Cyc_Bajas_Cursantes.writeOperations(ai_m4Op);
        }

        // write data for node CYC_FEEDBACK_CURSANTES.
        if ( Cyc_Feedback_Cursantes != null) 
        {
           Cyc_Feedback_Cursantes.writeOperations(ai_m4Op);
        }

        // write data for node CYC_COLECTIVO_CURSANTES.
        if ( Cyc_Colectivo_Cursantes != null) 
        {
           Cyc_Colectivo_Cursantes.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read FEBK_CYC.
        sItemName = "FEBK_CYC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        febk_Cyc = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read BAJAS_CYC.
        sItemName = "BAJAS_CYC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        bajas_Cyc = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read FEBK_IBER.
        sItemName = "FEBK_IBER";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        febk_Iber = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read BAJAS_IBER.
        sItemName = "BAJAS_IBER";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        bajas_Iber = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read ID_EMPLEADO.
        sItemName = "ID_EMPLEADO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Empleado = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read SUPERAN_CYC.
        sItemName = "SUPERAN_CYC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        superan_Cyc = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read TOTALES_CYC.
        sItemName = "TOTALES_CYC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        totales_Cyc = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read SUPERAN_IBER.
        sItemName = "SUPERAN_IBER";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        superan_Iber = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read TOTALES_IBER.
        sItemName = "TOTALES_IBER";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        totales_Iber = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read NO_SUPERAN_CYC.
        sItemName = "NO_SUPERAN_CYC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        no_Superan_Cyc = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read NO_SUPERAN_IBER.
        sItemName = "NO_SUPERAN_IBER";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        no_Superan_Iber = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read POTENCIAL_DES_CYC.
        sItemName = "POTENCIAL_DES_CYC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        potencial_Des_Cyc = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read POTENCIAL_DES_ING.
        sItemName = "POTENCIAL_DES_ING";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        potencial_Des_Ing = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CONTRIBUYENTES_CYC.
        sItemName = "CONTRIBUYENTES_CYC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        contribuyentes_Cyc = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CONTRIBUYENTES_ING.
        sItemName = "CONTRIBUYENTES_ING";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        contribuyentes_Ing = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read POTENCIAL_DES_IBER.
        sItemName = "POTENCIAL_DES_IBER";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        potencial_Des_Iber = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CAP_GESTION_DES_CYC.
        sItemName = "CAP_GESTION_DES_CYC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cap_Gestion_Des_Cyc = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CAP_GESTION_DES_ING.
        sItemName = "CAP_GESTION_DES_ING";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cap_Gestion_Des_Ing = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CONTRIBUYENTES_IBER.
        sItemName = "CONTRIBUYENTES_IBER";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        contribuyentes_Iber = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CAP_GESTION_BAJO_CYC.
        sItemName = "CAP_GESTION_BAJO_CYC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cap_Gestion_Bajo_Cyc = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CAP_GESTION_BAJO_ING.
        sItemName = "CAP_GESTION_BAJO_ING";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cap_Gestion_Bajo_Ing = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CAP_GESTION_DES_IBER.
        sItemName = "CAP_GESTION_DES_IBER";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cap_Gestion_Des_Iber = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CAP_GESTION_BAJO_IBER.
        sItemName = "CAP_GESTION_BAJO_IBER";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cap_Gestion_Bajo_Iber = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read data for node CYC_SUPERAN.
        Cyc_Superan = new Cyc_SuperanBlock();
        Cyc_Superan.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_SuperanBlock.NODE_NAME));

        // read data for node CYC_TOT_CURSANTES.
        Cyc_Tot_Cursantes = new Cyc_Tot_CursantesBlock();
        Cyc_Tot_Cursantes.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_Tot_CursantesBlock.NODE_NAME));

        // read data for node CYC_BAJAS_CURSANTES.
        Cyc_Bajas_Cursantes = new Cyc_Bajas_CursantesBlock();
        Cyc_Bajas_Cursantes.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_Bajas_CursantesBlock.NODE_NAME));

        // read data for node CYC_FEEDBACK_CURSANTES.
        Cyc_Feedback_Cursantes = new Cyc_Feedback_CursantesBlock();
        Cyc_Feedback_Cursantes.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_Feedback_CursantesBlock.NODE_NAME));

        // read data for node CYC_COLECTIVO_CURSANTES.
        Cyc_Colectivo_Cursantes = new Cyc_Colectivo_CursantesBlock();
        Cyc_Colectivo_Cursantes.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_Colectivo_CursantesBlock.NODE_NAME));


    } /* end of method readOperations */


} /* end of class Cyc_Informe_TotalesRecord */

