/**
 * Cyc_Potencial_FiiiRecord.java
 * Self generated code for Bussines Object CYC_INFORMES_PCP.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_informes_pcp;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Potencial_Fiii.
 * @author Meta4
 */
public 
class Cyc_Potencial_FiiiRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_INFORMES_PCP";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_POTENCIAL_FIII";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Potencial_FiiiRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item ID_ORGANIZATION */
    public String id_Organization = null;
    private void setid_Organization(String ai_value)
    {
        id_Organization = ai_value;
    }
    private String getid_Organization()
    {
        return id_Organization;
    }

    /* item P_COMUN_IMP_INF */
    public String p_Comun_Imp_Inf = null;
    private void setp_Comun_Imp_Inf(String ai_value)
    {
        p_Comun_Imp_Inf = ai_value;
    }
    private String getp_Comun_Imp_Inf()
    {
        return p_Comun_Imp_Inf;
    }

    /* item P_CAPAC_ANALITIC */
    public String p_Capac_Analitic = null;
    private void setp_Capac_Analitic(String ai_value)
    {
        p_Capac_Analitic = ai_value;
    }
    private String getp_Capac_Analitic()
    {
        return p_Capac_Analitic;
    }

    /* item P_VISION_GBAL_EST */
    public String p_Vision_Gbal_Est = null;
    private void setp_Vision_Gbal_Est(String ai_value)
    {
        p_Vision_Gbal_Est = ai_value;
    }
    private String getp_Vision_Gbal_Est()
    {
        return p_Vision_Gbal_Est;
    }

    /* item CYC_COMUN_IMP_INF_F3 */
    public Double cyc_Comun_Imp_Inf_F3 = null;
    private void setcyc_Comun_Imp_Inf_F3(Double ai_value)
    {
        cyc_Comun_Imp_Inf_F3 = ai_value;
    }
    private Double getcyc_Comun_Imp_Inf_F3()
    {
        return cyc_Comun_Imp_Inf_F3;
    }

    /* item CYC_CAPAC_ANALITIC_F3 */
    public Double cyc_Capac_Analitic_F3 = null;
    private void setcyc_Capac_Analitic_F3(Double ai_value)
    {
        cyc_Capac_Analitic_F3 = ai_value;
    }
    private Double getcyc_Capac_Analitic_F3()
    {
        return cyc_Capac_Analitic_F3;
    }

    /* item CYC_VISION_GBAL_EST_F3 */
    public Double cyc_Vision_Gbal_Est_F3 = null;
    private void setcyc_Vision_Gbal_Est_F3(Double ai_value)
    {
        cyc_Vision_Gbal_Est_F3 = ai_value;
    }
    private Double getcyc_Vision_Gbal_Est_F3()
    {
        return cyc_Vision_Gbal_Est_F3;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // ID_ORGANIZATION.
        if (id_Organization != null)
        {
            htItems.put("ID_ORGANIZATION", M4BusinessMethodArg.toString(id_Organization));
        }
        // P_COMUN_IMP_INF.
        if (p_Comun_Imp_Inf != null)
        {
            htItems.put("P_COMUN_IMP_INF", M4BusinessMethodArg.toString(p_Comun_Imp_Inf));
        }
        // P_CAPAC_ANALITIC.
        if (p_Capac_Analitic != null)
        {
            htItems.put("P_CAPAC_ANALITIC", M4BusinessMethodArg.toString(p_Capac_Analitic));
        }
        // P_VISION_GBAL_EST.
        if (p_Vision_Gbal_Est != null)
        {
            htItems.put("P_VISION_GBAL_EST", M4BusinessMethodArg.toString(p_Vision_Gbal_Est));
        }
        // CYC_COMUN_IMP_INF_F3.
        if (cyc_Comun_Imp_Inf_F3 != null)
        {
            htItems.put("CYC_COMUN_IMP_INF_F3", M4BusinessMethodArg.toString(cyc_Comun_Imp_Inf_F3));
        }
        // CYC_CAPAC_ANALITIC_F3.
        if (cyc_Capac_Analitic_F3 != null)
        {
            htItems.put("CYC_CAPAC_ANALITIC_F3", M4BusinessMethodArg.toString(cyc_Capac_Analitic_F3));
        }
        // CYC_VISION_GBAL_EST_F3.
        if (cyc_Vision_Gbal_Est_F3 != null)
        {
            htItems.put("CYC_VISION_GBAL_EST_F3", M4BusinessMethodArg.toString(cyc_Vision_Gbal_Est_F3));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read ID_ORGANIZATION.
        sItemName = "ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Organization = sItemValue;

        // read P_COMUN_IMP_INF.
        sItemName = "P_COMUN_IMP_INF";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Comun_Imp_Inf = sItemValue;

        // read P_CAPAC_ANALITIC.
        sItemName = "P_CAPAC_ANALITIC";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Capac_Analitic = sItemValue;

        // read P_VISION_GBAL_EST.
        sItemName = "P_VISION_GBAL_EST";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Vision_Gbal_Est = sItemValue;

        // read CYC_COMUN_IMP_INF_F3.
        sItemName = "CYC_COMUN_IMP_INF_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Comun_Imp_Inf_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_CAPAC_ANALITIC_F3.
        sItemName = "CYC_CAPAC_ANALITIC_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Capac_Analitic_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_VISION_GBAL_EST_F3.
        sItemName = "CYC_VISION_GBAL_EST_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Vision_Gbal_Est_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);


    } /* end of method readOperations */


} /* end of class Cyc_Potencial_FiiiRecord */

