/**
 * Cyc_Cap_Ges_Grupo_FiiRecord.java
 * Self generated code for Bussines Object CYC_INFORMES_PCP.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_informes_pcp;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Cap_Ges_Grupo_Fii.
 * @author Meta4
 */
public 
class Cyc_Cap_Ges_Grupo_FiiRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_INFORMES_PCP";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_CAP_GES_GRUPO_FII";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Cap_Ges_Grupo_FiiRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item P_COMP_IMPLI */
    public String p_Comp_Impli = null;
    private void setp_Comp_Impli(String ai_value)
    {
        p_Comp_Impli = ai_value;
    }
    private String getp_Comp_Impli()
    {
        return p_Comp_Impli;
    }

    /* item P_TOMA_DECIS */
    public String p_Toma_Decis = null;
    private void setp_Toma_Decis(String ai_value)
    {
        p_Toma_Decis = ai_value;
    }
    private String getp_Toma_Decis()
    {
        return p_Toma_Decis;
    }

    /* item P_DESA_PERSON */
    public String p_Desa_Person = null;
    private void setp_Desa_Person(String ai_value)
    {
        p_Desa_Person = ai_value;
    }
    private String getp_Desa_Person()
    {
        return p_Desa_Person;
    }

    /* item ID_ORGANIZATION */
    public String id_Organization = null;
    private void setid_Organization(String ai_value)
    {
        id_Organization = ai_value;
    }
    private String getid_Organization()
    {
        return id_Organization;
    }

    /* item P_DIREC_EQUIPOS */
    public String p_Direc_Equipos = null;
    private void setp_Direc_Equipos(String ai_value)
    {
        p_Direc_Equipos = ai_value;
    }
    private String getp_Direc_Equipos()
    {
        return p_Direc_Equipos;
    }

    /* item P_ORIENT_CLIENT */
    public String p_Orient_Client = null;
    private void setp_Orient_Client(String ai_value)
    {
        p_Orient_Client = ai_value;
    }
    private String getp_Orient_Client()
    {
        return p_Orient_Client;
    }

    /* item P_ORIENT_RESULT */
    public String p_Orient_Result = null;
    private void setp_Orient_Result(String ai_value)
    {
        p_Orient_Result = ai_value;
    }
    private String getp_Orient_Result()
    {
        return p_Orient_Result;
    }

    /* item P_PLANIF_ORGANIZ */
    public String p_Planif_Organiz = null;
    private void setp_Planif_Organiz(String ai_value)
    {
        p_Planif_Organiz = ai_value;
    }
    private String getp_Planif_Organiz()
    {
        return p_Planif_Organiz;
    }

    /* item CYC_COMP_IMPLI_F2 */
    public Double cyc_Comp_Impli_F2 = null;
    private void setcyc_Comp_Impli_F2(Double ai_value)
    {
        cyc_Comp_Impli_F2 = ai_value;
    }
    private Double getcyc_Comp_Impli_F2()
    {
        return cyc_Comp_Impli_F2;
    }

    /* item CYC_TOMA_DECIS_F2 */
    public Double cyc_Toma_Decis_F2 = null;
    private void setcyc_Toma_Decis_F2(Double ai_value)
    {
        cyc_Toma_Decis_F2 = ai_value;
    }
    private Double getcyc_Toma_Decis_F2()
    {
        return cyc_Toma_Decis_F2;
    }

    /* item CYC_DESA_PERSON_F2 */
    public Double cyc_Desa_Person_F2 = null;
    private void setcyc_Desa_Person_F2(Double ai_value)
    {
        cyc_Desa_Person_F2 = ai_value;
    }
    private Double getcyc_Desa_Person_F2()
    {
        return cyc_Desa_Person_F2;
    }

    /* item CYC_DIREC_EQUIPOS_F2 */
    public Double cyc_Direc_Equipos_F2 = null;
    private void setcyc_Direc_Equipos_F2(Double ai_value)
    {
        cyc_Direc_Equipos_F2 = ai_value;
    }
    private Double getcyc_Direc_Equipos_F2()
    {
        return cyc_Direc_Equipos_F2;
    }

    /* item CYC_ORIENT_CLIENT_F2 */
    public Double cyc_Orient_Client_F2 = null;
    private void setcyc_Orient_Client_F2(Double ai_value)
    {
        cyc_Orient_Client_F2 = ai_value;
    }
    private Double getcyc_Orient_Client_F2()
    {
        return cyc_Orient_Client_F2;
    }

    /* item CYC_ORIENT_RESULT_F2 */
    public Double cyc_Orient_Result_F2 = null;
    private void setcyc_Orient_Result_F2(Double ai_value)
    {
        cyc_Orient_Result_F2 = ai_value;
    }
    private Double getcyc_Orient_Result_F2()
    {
        return cyc_Orient_Result_F2;
    }

    /* item CYC_PLANIF_ORGANIZ_F2 */
    public Double cyc_Planif_Organiz_F2 = null;
    private void setcyc_Planif_Organiz_F2(Double ai_value)
    {
        cyc_Planif_Organiz_F2 = ai_value;
    }
    private Double getcyc_Planif_Organiz_F2()
    {
        return cyc_Planif_Organiz_F2;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // P_COMP_IMPLI.
        if (p_Comp_Impli != null)
        {
            htItems.put("P_COMP_IMPLI", M4BusinessMethodArg.toString(p_Comp_Impli));
        }
        // P_TOMA_DECIS.
        if (p_Toma_Decis != null)
        {
            htItems.put("P_TOMA_DECIS", M4BusinessMethodArg.toString(p_Toma_Decis));
        }
        // P_DESA_PERSON.
        if (p_Desa_Person != null)
        {
            htItems.put("P_DESA_PERSON", M4BusinessMethodArg.toString(p_Desa_Person));
        }
        // ID_ORGANIZATION.
        if (id_Organization != null)
        {
            htItems.put("ID_ORGANIZATION", M4BusinessMethodArg.toString(id_Organization));
        }
        // P_DIREC_EQUIPOS.
        if (p_Direc_Equipos != null)
        {
            htItems.put("P_DIREC_EQUIPOS", M4BusinessMethodArg.toString(p_Direc_Equipos));
        }
        // P_ORIENT_CLIENT.
        if (p_Orient_Client != null)
        {
            htItems.put("P_ORIENT_CLIENT", M4BusinessMethodArg.toString(p_Orient_Client));
        }
        // P_ORIENT_RESULT.
        if (p_Orient_Result != null)
        {
            htItems.put("P_ORIENT_RESULT", M4BusinessMethodArg.toString(p_Orient_Result));
        }
        // P_PLANIF_ORGANIZ.
        if (p_Planif_Organiz != null)
        {
            htItems.put("P_PLANIF_ORGANIZ", M4BusinessMethodArg.toString(p_Planif_Organiz));
        }
        // CYC_COMP_IMPLI_F2.
        if (cyc_Comp_Impli_F2 != null)
        {
            htItems.put("CYC_COMP_IMPLI_F2", M4BusinessMethodArg.toString(cyc_Comp_Impli_F2));
        }
        // CYC_TOMA_DECIS_F2.
        if (cyc_Toma_Decis_F2 != null)
        {
            htItems.put("CYC_TOMA_DECIS_F2", M4BusinessMethodArg.toString(cyc_Toma_Decis_F2));
        }
        // CYC_DESA_PERSON_F2.
        if (cyc_Desa_Person_F2 != null)
        {
            htItems.put("CYC_DESA_PERSON_F2", M4BusinessMethodArg.toString(cyc_Desa_Person_F2));
        }
        // CYC_DIREC_EQUIPOS_F2.
        if (cyc_Direc_Equipos_F2 != null)
        {
            htItems.put("CYC_DIREC_EQUIPOS_F2", M4BusinessMethodArg.toString(cyc_Direc_Equipos_F2));
        }
        // CYC_ORIENT_CLIENT_F2.
        if (cyc_Orient_Client_F2 != null)
        {
            htItems.put("CYC_ORIENT_CLIENT_F2", M4BusinessMethodArg.toString(cyc_Orient_Client_F2));
        }
        // CYC_ORIENT_RESULT_F2.
        if (cyc_Orient_Result_F2 != null)
        {
            htItems.put("CYC_ORIENT_RESULT_F2", M4BusinessMethodArg.toString(cyc_Orient_Result_F2));
        }
        // CYC_PLANIF_ORGANIZ_F2.
        if (cyc_Planif_Organiz_F2 != null)
        {
            htItems.put("CYC_PLANIF_ORGANIZ_F2", M4BusinessMethodArg.toString(cyc_Planif_Organiz_F2));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read P_COMP_IMPLI.
        sItemName = "P_COMP_IMPLI";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Comp_Impli = sItemValue;

        // read P_TOMA_DECIS.
        sItemName = "P_TOMA_DECIS";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Toma_Decis = sItemValue;

        // read P_DESA_PERSON.
        sItemName = "P_DESA_PERSON";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Desa_Person = sItemValue;

        // read ID_ORGANIZATION.
        sItemName = "ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Organization = sItemValue;

        // read P_DIREC_EQUIPOS.
        sItemName = "P_DIREC_EQUIPOS";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Direc_Equipos = sItemValue;

        // read P_ORIENT_CLIENT.
        sItemName = "P_ORIENT_CLIENT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Orient_Client = sItemValue;

        // read P_ORIENT_RESULT.
        sItemName = "P_ORIENT_RESULT";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Orient_Result = sItemValue;

        // read P_PLANIF_ORGANIZ.
        sItemName = "P_PLANIF_ORGANIZ";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Planif_Organiz = sItemValue;

        // read CYC_COMP_IMPLI_F2.
        sItemName = "CYC_COMP_IMPLI_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Comp_Impli_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_TOMA_DECIS_F2.
        sItemName = "CYC_TOMA_DECIS_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Toma_Decis_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_DESA_PERSON_F2.
        sItemName = "CYC_DESA_PERSON_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Desa_Person_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_DIREC_EQUIPOS_F2.
        sItemName = "CYC_DIREC_EQUIPOS_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Direc_Equipos_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_ORIENT_CLIENT_F2.
        sItemName = "CYC_ORIENT_CLIENT_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Orient_Client_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_ORIENT_RESULT_F2.
        sItemName = "CYC_ORIENT_RESULT_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Orient_Result_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_PLANIF_ORGANIZ_F2.
        sItemName = "CYC_PLANIF_ORGANIZ_F2";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Planif_Organiz_F2 = M4BusinessMethodArg.toDoubleNillable(sItemValue);


    } /* end of method readOperations */


} /* end of class Cyc_Cap_Ges_Grupo_FiiRecord */

