/**
 * Cyc_Competencias_FiiiRecord.java
 * Self generated code for Bussines Object CYC_INFORMES_PCP.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_informes_pcp;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Competencias_Fiii.
 * @author Meta4
 */
public 
class Cyc_Competencias_FiiiRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_INFORMES_PCP";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_COMPETENCIAS_FIII";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Competencias_FiiiRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item P_ORIENT_RTDOS */
    public String p_Orient_Rtdos = null;
    private void setp_Orient_Rtdos(String ai_value)
    {
        p_Orient_Rtdos = ai_value;
    }
    private String getp_Orient_Rtdos()
    {
        return p_Orient_Rtdos;
    }

    /* item ID_ORGANIZATION */
    public String id_Organization = null;
    private void setid_Organization(String ai_value)
    {
        id_Organization = ai_value;
    }
    private String getid_Organization()
    {
        return id_Organization;
    }

    /* item P_LIDER_DIR_EQUIP */
    public String p_Lider_Dir_Equip = null;
    private void setp_Lider_Dir_Equip(String ai_value)
    {
        p_Lider_Dir_Equip = ai_value;
    }
    private String getp_Lider_Dir_Equip()
    {
        return p_Lider_Dir_Equip;
    }

    /* item CYC_ORIENT_RTDOS_F3 */
    public Double cyc_Orient_Rtdos_F3 = null;
    private void setcyc_Orient_Rtdos_F3(Double ai_value)
    {
        cyc_Orient_Rtdos_F3 = ai_value;
    }
    private Double getcyc_Orient_Rtdos_F3()
    {
        return cyc_Orient_Rtdos_F3;
    }

    /* item CYC_LIDER_DIR_EQUIP_F3 */
    public Double cyc_Lider_Dir_Equip_F3 = null;
    private void setcyc_Lider_Dir_Equip_F3(Double ai_value)
    {
        cyc_Lider_Dir_Equip_F3 = ai_value;
    }
    private Double getcyc_Lider_Dir_Equip_F3()
    {
        return cyc_Lider_Dir_Equip_F3;
    }

    /* node CYC_POTENCIAL_FIII */
    public Cyc_Potencial_FiiiBlock Cyc_Potencial_Fiii = null;
    private void setcyc_Potencial_Fiii(Cyc_Potencial_FiiiBlock ai_value)
    {
        Cyc_Potencial_Fiii = ai_value;
    }
    private Cyc_Potencial_FiiiBlock getCyc_Potencial_Fiii()
    {
        return Cyc_Potencial_Fiii;
    }

    /* node CYC_CURSANTES_COLECTIVOS_FIII */
    public Cyc_Cursantes_Colectivos_FiiiBlock Cyc_Cursantes_Colectivos_Fiii = null;
    private void setcyc_Cursantes_Colectivos_Fiii(Cyc_Cursantes_Colectivos_FiiiBlock ai_value)
    {
        Cyc_Cursantes_Colectivos_Fiii = ai_value;
    }
    private Cyc_Cursantes_Colectivos_FiiiBlock getCyc_Cursantes_Colectivos_Fiii()
    {
        return Cyc_Cursantes_Colectivos_Fiii;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // P_ORIENT_RTDOS.
        if (p_Orient_Rtdos != null)
        {
            htItems.put("P_ORIENT_RTDOS", M4BusinessMethodArg.toString(p_Orient_Rtdos));
        }
        // ID_ORGANIZATION.
        if (id_Organization != null)
        {
            htItems.put("ID_ORGANIZATION", M4BusinessMethodArg.toString(id_Organization));
        }
        // P_LIDER_DIR_EQUIP.
        if (p_Lider_Dir_Equip != null)
        {
            htItems.put("P_LIDER_DIR_EQUIP", M4BusinessMethodArg.toString(p_Lider_Dir_Equip));
        }
        // CYC_ORIENT_RTDOS_F3.
        if (cyc_Orient_Rtdos_F3 != null)
        {
            htItems.put("CYC_ORIENT_RTDOS_F3", M4BusinessMethodArg.toString(cyc_Orient_Rtdos_F3));
        }
        // CYC_LIDER_DIR_EQUIP_F3.
        if (cyc_Lider_Dir_Equip_F3 != null)
        {
            htItems.put("CYC_LIDER_DIR_EQUIP_F3", M4BusinessMethodArg.toString(cyc_Lider_Dir_Equip_F3));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

        // write data for node CYC_POTENCIAL_FIII.
        if ( Cyc_Potencial_Fiii != null) 
        {
           Cyc_Potencial_Fiii.writeOperations(ai_m4Op);
        }

        // write data for node CYC_CURSANTES_COLECTIVOS_FIII.
        if ( Cyc_Cursantes_Colectivos_Fiii != null) 
        {
           Cyc_Cursantes_Colectivos_Fiii.writeOperations(ai_m4Op);
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read P_ORIENT_RTDOS.
        sItemName = "P_ORIENT_RTDOS";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Orient_Rtdos = sItemValue;

        // read ID_ORGANIZATION.
        sItemName = "ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Organization = sItemValue;

        // read P_LIDER_DIR_EQUIP.
        sItemName = "P_LIDER_DIR_EQUIP";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        p_Lider_Dir_Equip = sItemValue;

        // read CYC_ORIENT_RTDOS_F3.
        sItemName = "CYC_ORIENT_RTDOS_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Orient_Rtdos_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_LIDER_DIR_EQUIP_F3.
        sItemName = "CYC_LIDER_DIR_EQUIP_F3";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Lider_Dir_Equip_F3 = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read data for node CYC_POTENCIAL_FIII.
        Cyc_Potencial_Fiii = new Cyc_Potencial_FiiiBlock();
        Cyc_Potencial_Fiii.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_Potencial_FiiiBlock.NODE_NAME));

        // read data for node CYC_CURSANTES_COLECTIVOS_FIII.
        Cyc_Cursantes_Colectivos_Fiii = new Cyc_Cursantes_Colectivos_FiiiBlock();
        Cyc_Cursantes_Colectivos_Fiii.readOperations(ai_m4Op, ai_xml, ai_xml.findDataNode(ai_record, M4OBJECT_ALIAS + "!" + Cyc_Cursantes_Colectivos_FiiiBlock.NODE_NAME));


    } /* end of method readOperations */


} /* end of class Cyc_Competencias_FiiiRecord */

