/**
 * Cyc_Val_Fase_IRecord.java
 * Self generated code for Bussines Object CYC_VAL_FASE_I.
 *
 * Copyright Meta4 Spain S.A.
 * Centro Europa Empresarial - Edf. Roma
 * C/ Rozabella, 8
 * 28230 Las Rozas - Madrid
 * Spain
 *
 * Private and Confidential
 * The information contained in this document is the property of Meta4 Spain S.A.
 * It is for the exclusive use of designated employees
 * and not for distribution without prior written authorization.
 */

package com.meta4.soapservices.services.rpc.cyc_val_fase_i;

import org.w3c.dom.Node;
import org.w3c.dom.NamedNodeMap;
import java.util.Hashtable;
import java.util.Calendar;
import javax.activation.DataHandler;

import com.meta4.soapservices.operations.M4SoapOperations;
import com.meta4.soapservices.operations.M4XML;
import com.meta4.soapservices.exception.M4SoapException;
import com.meta4.soapservices.businessobject.M4BusinessMethodArg;
import com.meta4.soapservices.types.M4FileDataSource;

import com.meta4.common.utils.logsystem.M4LogManager;
import com.meta4.common.utils.logsystem.M4ILogger;

/**
 * Bean for node Cyc_Val_Fase_I.
 * @author Meta4
 */
public 
class Cyc_Val_Fase_IRecord 
{

    /* M4Object definitions */
    public static final String M4OBJECT_NAME = "CYC_VAL_FASE_I";
    public static final String M4OBJECT_ALIAS = M4OBJECT_NAME;

    /* Node definition */
    public static final String NODE_NAME = "CYC_VAL_FASE_I";
    public static final String NODE_OUTPUTDEF = NODE_NAME + "_OUTPUTDEF";

    /* the log object */
    static private M4ILogger m_log = M4LogManager.getInstance(Cyc_Val_Fase_IRecord.class.getName());

    /* new persistence member - RecordID */    
    public String m4AutoGeneratedRecordID = null; 
    
    private String getM4AutoGeneratedRecordID () 
    {
    	return m4AutoGeneratedRecordID; 
    }       
    
    private void setM4AutoGeneratedRecordID (String ai_M4AutoGeneratedRecordID) 
    {
    	m4AutoGeneratedRecordID = ai_M4AutoGeneratedRecordID;
    	return; 
    }
    
    /* new persistence member - ToDelete */    
    public boolean m4AutoGeneratedToDelete = false; 
    
    private boolean getM4AutoGeneratedToDelete () 
    {
    	return m4AutoGeneratedToDelete; 
    }       
    
    private void setM4AutoGeneratedToDelete (boolean ai_M4AutoGeneratedToDelete) 
    {
    	m4AutoGeneratedToDelete = ai_M4AutoGeneratedToDelete;
    	return; 
    }




    /* item DT_END */
    public Calendar dt_End = null;
    private void setdt_End(Calendar ai_value)
    {
        dt_End = ai_value;
    }
    private Calendar getdt_End()
    {
        return dt_End;
    }

    /* item CYC_16PF */
    public Double cyc_16Pf = null;
    private void setcyc_16Pf(Double ai_value)
    {
        cyc_16Pf = ai_value;
    }
    private Double getcyc_16Pf()
    {
        return cyc_16Pf;
    }

    /* item DT_START */
    public Calendar dt_Start = null;
    private void setdt_Start(Calendar ai_value)
    {
        dt_Start = ai_value;
    }
    private Calendar getdt_Start()
    {
        return dt_Start;
    }

    /* item CYC_ID_HR */
    public String cyc_Id_Hr = null;
    private void setcyc_Id_Hr(String ai_value)
    {
        cyc_Id_Hr = ai_value;
    }
    private String getcyc_Id_Hr()
    {
        return cyc_Id_Hr;
    }

    /* item CYC_ESTUDIOS */
    public Double cyc_Estudios = null;
    private void setcyc_Estudios(Double ai_value)
    {
        cyc_Estudios = ai_value;
    }
    private Double getcyc_Estudios()
    {
        return cyc_Estudios;
    }

    /* item CYC_RUTA_PDF */
    public String cyc_Ruta_Pdf = null;
    private void setcyc_Ruta_Pdf(String ai_value)
    {
        cyc_Ruta_Pdf = ai_value;
    }
    private String getcyc_Ruta_Pdf()
    {
        return cyc_Ruta_Pdf;
    }

    /* item CYC_LIDERAZGO */
    public Double cyc_Liderazgo = null;
    private void setcyc_Liderazgo(Double ai_value)
    {
        cyc_Liderazgo = ai_value;
    }
    private Double getcyc_Liderazgo()
    {
        return cyc_Liderazgo;
    }

    /* item CYC_ABSENTISMO */
    public Double cyc_Absentismo = null;
    private void setcyc_Absentismo(Double ai_value)
    {
        cyc_Absentismo = ai_value;
    }
    private Double getcyc_Absentismo()
    {
        return cyc_Absentismo;
    }

    /* item CYC_EVALUACION */
    public Double cyc_Evaluacion = null;
    private void setcyc_Evaluacion(Double ai_value)
    {
        cyc_Evaluacion = ai_value;
    }
    private Double getcyc_Evaluacion()
    {
        return cyc_Evaluacion;
    }

    /* item CYC_PROMOCIONES */
    public Double cyc_Promociones = null;
    private void setcyc_Promociones(Double ai_value)
    {
        cyc_Promociones = ai_value;
    }
    private Double getcyc_Promociones()
    {
        return cyc_Promociones;
    }

    /* item ID_ORGANIZATION */
    public String id_Organization = null;
    private void setid_Organization(String ai_value)
    {
        id_Organization = ai_value;
    }
    private String getid_Organization()
    {
        return id_Organization;
    }

    /* item CYC_INTERES_FORM */
    public Double cyc_Interes_Form = null;
    private void setcyc_Interes_Form(Double ai_value)
    {
        cyc_Interes_Form = ai_value;
    }
    private Double getcyc_Interes_Form()
    {
        return cyc_Interes_Form;
    }

    /* item CYC_ORDEN_PLANIF */
    public Double cyc_Orden_Planif = null;
    private void setcyc_Orden_Planif(Double ai_value)
    {
        cyc_Orden_Planif = ai_value;
    }
    private Double getcyc_Orden_Planif()
    {
        return cyc_Orden_Planif;
    }

    /* item CYC_POLIVALENCIA */
    public Double cyc_Polivalencia = null;
    private void setcyc_Polivalencia(Double ai_value)
    {
        cyc_Polivalencia = ai_value;
    }
    private Double getcyc_Polivalencia()
    {
        return cyc_Polivalencia;
    }

    /* item CYC_RAZONAMIENTO */
    public Double cyc_Razonamiento = null;
    private void setcyc_Razonamiento(Double ai_value)
    {
        cyc_Razonamiento = ai_value;
    }
    private Double getcyc_Razonamiento()
    {
        return cyc_Razonamiento;
    }

    /* item CYC_GESTION_TIEMPO */
    public Double cyc_Gestion_Tiempo = null;
    private void setcyc_Gestion_Tiempo(Double ai_value)
    {
        cyc_Gestion_Tiempo = ai_value;
    }
    private Double getcyc_Gestion_Tiempo()
    {
        return cyc_Gestion_Tiempo;
    }

    /* item CYC_GESTION_EQUIPOS */
    public Double cyc_Gestion_Equipos = null;
    private void setcyc_Gestion_Equipos(Double ai_value)
    {
        cyc_Gestion_Equipos = ai_value;
    }
    private Double getcyc_Gestion_Equipos()
    {
        return cyc_Gestion_Equipos;
    }

    /* item CYC_TOMA_DECISIONES */
    public Double cyc_Toma_Decisiones = null;
    private void setcyc_Toma_Decisiones(Double ai_value)
    {
        cyc_Toma_Decisiones = ai_value;
    }
    private Double getcyc_Toma_Decisiones()
    {
        return cyc_Toma_Decisiones;
    }

    /* item CYC_CAPACIDAD_NEGOCIA */
    public Double cyc_Capacidad_Negocia = null;
    private void setcyc_Capacidad_Negocia(Double ai_value)
    {
        cyc_Capacidad_Negocia = ai_value;
    }
    private Double getcyc_Capacidad_Negocia()
    {
        return cyc_Capacidad_Negocia;
    }

    /* item CYC_ANALISIS_PROBLEMAS */
    public Double cyc_Analisis_Problemas = null;
    private void setcyc_Analisis_Problemas(Double ai_value)
    {
        cyc_Analisis_Problemas = ai_value;
    }
    private Double getcyc_Analisis_Problemas()
    {
        return cyc_Analisis_Problemas;
    }


    /**
     *
     */
    void writeOperations(M4SoapOperations ai_m4Op)
    throws Exception
    {
        // items.
        Hashtable htItems = new Hashtable();
        Hashtable htBlobs = new Hashtable();
        // DT_END.
        if (dt_End != null)
        {
            htItems.put("DT_END", M4BusinessMethodArg.toString(dt_End));
        }
        // CYC_16PF.
        if (cyc_16Pf != null)
        {
            htItems.put("CYC_16PF", M4BusinessMethodArg.toString(cyc_16Pf));
        }
        // DT_START.
        if (dt_Start != null)
        {
            htItems.put("DT_START", M4BusinessMethodArg.toString(dt_Start));
        }
        // CYC_ID_HR.
        if (cyc_Id_Hr != null)
        {
            htItems.put("CYC_ID_HR", M4BusinessMethodArg.toString(cyc_Id_Hr));
        }
        // CYC_ESTUDIOS.
        if (cyc_Estudios != null)
        {
            htItems.put("CYC_ESTUDIOS", M4BusinessMethodArg.toString(cyc_Estudios));
        }
        // CYC_RUTA_PDF.
        if (cyc_Ruta_Pdf != null)
        {
            htItems.put("CYC_RUTA_PDF", M4BusinessMethodArg.toString(cyc_Ruta_Pdf));
        }
        // CYC_LIDERAZGO.
        if (cyc_Liderazgo != null)
        {
            htItems.put("CYC_LIDERAZGO", M4BusinessMethodArg.toString(cyc_Liderazgo));
        }
        // CYC_ABSENTISMO.
        if (cyc_Absentismo != null)
        {
            htItems.put("CYC_ABSENTISMO", M4BusinessMethodArg.toString(cyc_Absentismo));
        }
        // CYC_EVALUACION.
        if (cyc_Evaluacion != null)
        {
            htItems.put("CYC_EVALUACION", M4BusinessMethodArg.toString(cyc_Evaluacion));
        }
        // CYC_PROMOCIONES.
        if (cyc_Promociones != null)
        {
            htItems.put("CYC_PROMOCIONES", M4BusinessMethodArg.toString(cyc_Promociones));
        }
        // ID_ORGANIZATION.
        if (id_Organization != null)
        {
            htItems.put("ID_ORGANIZATION", M4BusinessMethodArg.toString(id_Organization));
        }
        // CYC_INTERES_FORM.
        if (cyc_Interes_Form != null)
        {
            htItems.put("CYC_INTERES_FORM", M4BusinessMethodArg.toString(cyc_Interes_Form));
        }
        // CYC_ORDEN_PLANIF.
        if (cyc_Orden_Planif != null)
        {
            htItems.put("CYC_ORDEN_PLANIF", M4BusinessMethodArg.toString(cyc_Orden_Planif));
        }
        // CYC_POLIVALENCIA.
        if (cyc_Polivalencia != null)
        {
            htItems.put("CYC_POLIVALENCIA", M4BusinessMethodArg.toString(cyc_Polivalencia));
        }
        // CYC_RAZONAMIENTO.
        if (cyc_Razonamiento != null)
        {
            htItems.put("CYC_RAZONAMIENTO", M4BusinessMethodArg.toString(cyc_Razonamiento));
        }
        // CYC_GESTION_TIEMPO.
        if (cyc_Gestion_Tiempo != null)
        {
            htItems.put("CYC_GESTION_TIEMPO", M4BusinessMethodArg.toString(cyc_Gestion_Tiempo));
        }
        // CYC_GESTION_EQUIPOS.
        if (cyc_Gestion_Equipos != null)
        {
            htItems.put("CYC_GESTION_EQUIPOS", M4BusinessMethodArg.toString(cyc_Gestion_Equipos));
        }
        // CYC_TOMA_DECISIONES.
        if (cyc_Toma_Decisiones != null)
        {
            htItems.put("CYC_TOMA_DECISIONES", M4BusinessMethodArg.toString(cyc_Toma_Decisiones));
        }
        // CYC_CAPACIDAD_NEGOCIA.
        if (cyc_Capacidad_Negocia != null)
        {
            htItems.put("CYC_CAPACIDAD_NEGOCIA", M4BusinessMethodArg.toString(cyc_Capacidad_Negocia));
        }
        // CYC_ANALISIS_PROBLEMAS.
        if (cyc_Analisis_Problemas != null)
        {
            htItems.put("CYC_ANALISIS_PROBLEMAS", M4BusinessMethodArg.toString(cyc_Analisis_Problemas));
        }

        // Persistence. If the record ID is not specified, the default is addRecord
        // If the record ID is specified, it can be a delete or modify operation
        if (m4AutoGeneratedRecordID == null) 
        {
           m_log.debug ( "Write Operation for "+NODE_NAME+" is ADD");
           ai_m4Op.addRecord (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs);
        }
        else
        {
           if (m4AutoGeneratedToDelete == false)
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is MODIFY record ID " + m4AutoGeneratedRecordID);
              ai_m4Op.setRecordItems (M4OBJECT_ALIAS, NODE_NAME, htItems, htBlobs, m4AutoGeneratedRecordID);
           }
           else 
           {
              m_log.debug ( "Write Operation for "+NODE_NAME+" is DELETE record ID "+  m4AutoGeneratedRecordID);
              ai_m4Op.deleteRecord (NODE_OUTPUTDEF, M4OBJECT_ALIAS, NODE_NAME, m4AutoGeneratedRecordID);
           }
        }

    } /* end of method writeOperations */


    /**
     *
     */
    void readOperations(M4SoapOperations ai_m4Op, M4XML ai_xml, Node ai_record)
    throws Exception
    {
        // localvar.
        String sItemName = null;
        String sItemValue = null;

        Node nItem = null;

   

        
        // read items.
        // read DT_END.
        sItemName = "DT_END";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_End = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_16PF.
        sItemName = "CYC_16PF";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_16Pf = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read DT_START.
        sItemName = "DT_START";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        dt_Start = M4BusinessMethodArg.toCalendar(sItemValue);

        // read CYC_ID_HR.
        sItemName = "CYC_ID_HR";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Id_Hr = sItemValue;

        // read CYC_ESTUDIOS.
        sItemName = "CYC_ESTUDIOS";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Estudios = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_RUTA_PDF.
        sItemName = "CYC_RUTA_PDF";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Ruta_Pdf = sItemValue;

        // read CYC_LIDERAZGO.
        sItemName = "CYC_LIDERAZGO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Liderazgo = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_ABSENTISMO.
        sItemName = "CYC_ABSENTISMO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Absentismo = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_EVALUACION.
        sItemName = "CYC_EVALUACION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Evaluacion = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_PROMOCIONES.
        sItemName = "CYC_PROMOCIONES";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Promociones = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read ID_ORGANIZATION.
        sItemName = "ID_ORGANIZATION";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        id_Organization = sItemValue;

        // read CYC_INTERES_FORM.
        sItemName = "CYC_INTERES_FORM";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Interes_Form = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_ORDEN_PLANIF.
        sItemName = "CYC_ORDEN_PLANIF";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Orden_Planif = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_POLIVALENCIA.
        sItemName = "CYC_POLIVALENCIA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Polivalencia = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_RAZONAMIENTO.
        sItemName = "CYC_RAZONAMIENTO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Razonamiento = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_GESTION_TIEMPO.
        sItemName = "CYC_GESTION_TIEMPO";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Gestion_Tiempo = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_GESTION_EQUIPOS.
        sItemName = "CYC_GESTION_EQUIPOS";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Gestion_Equipos = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_TOMA_DECISIONES.
        sItemName = "CYC_TOMA_DECISIONES";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Toma_Decisiones = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_CAPACIDAD_NEGOCIA.
        sItemName = "CYC_CAPACIDAD_NEGOCIA";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Capacidad_Negocia = M4BusinessMethodArg.toDoubleNillable(sItemValue);

        // read CYC_ANALISIS_PROBLEMAS.
        sItemName = "CYC_ANALISIS_PROBLEMAS";
        nItem = ai_xml.findItem(ai_record, sItemName);
        sItemValue = ai_xml.getAttValue(nItem, "value");
        cyc_Analisis_Problemas = M4BusinessMethodArg.toDoubleNillable(sItemValue);


    } /* end of method readOperations */


} /* end of class Cyc_Val_Fase_IRecord */

